<?php $topResults = array(
"a" => array(
array("amazon","0","2","",""),
array("aol","0","2","",""),
array("american airlines","0","2","",""),
array("apple","0","1","",""),
array("at&t","2","3","",""),
array("att","0","","",""),
array("academy","0","","",""),
array("abc","0","","",""),
array("ask","0","","",""),
array("amc","0","","",""),
array("autozone","0","","",""),
array("airsoft guns","1","","",""),
array("arcade fire","1","","",""),
array("avatar","1","","",""),
array("adidas","1","","",""),
array("air conditioner","1","","",""),
array("alarm clock","1","","",""),
array("airsoft","1","","",""),
array("apple ipad","1","","",""),
array("asus","1","","",""),
array("ask jeeves","2","","",""),
array("american idol","2","","",""),
array("autotrader","2","","",""),
array("aaliyah","2","","",""),
array("american express","2","","",""),
array("angelina jolie","2","","",""),
array("albuterol","3","","",""),
array("appie baantjer","3","","",""),
array("austin powers","3","","",""),
array("apartments for rent","3","","",""),
array("airline tickets","3","","",""),
array("att.com","3","","",""),
array("are vampires real","3","","",""),
array("area codes","3","","",""),
array("address search","3","","",""),
array("alejandro lady gaga","4","","",""),
array("airplanes","4","","",""),
array("airplanes b.o.b","4","","",""),
array("annoying orange","4","","",""),
array("akon","4","","",""),
array("alejandro","4","","",""),
array("alicia keys","4","","",""),
array("airplanes hayley williams","4","","",""),
array("avril lavigne","4","","",""),
array("all i do is win","4","","","")),
"b" => array(
array("best buy","0","2","3",""),
array("bed bath and beyond","0","2","3",""),
array("baby names","0","2","3",""),
array("britney spears","1","2","4",""),
array("bank of america","0","2","",""),
array("bing","0","3","",""),
array("blockbuster","0","2","",""),
array("barnes and noble","0","2","",""),
array("big lots","0","","",""),
array("bp","0","","",""),
array("big 12","0","","",""),
array("blackberry","1","","",""),
array("blackberry torch","1","","",""),
array("backpack","1","","",""),
array("blackberry bold 9700","1","","",""),
array("bluetooth headset","1","","",""),
array("blackberry unlocked","1","","",""),
array("bose","1","","",""),
array("blender","1","","",""),
array("blu ray player","1","","",""),
array("blank","2","","",""),
array("bbc","2","","",""),
array("babies r us","2","","",""),
array("boca sabrina","3","","",""),
array("brasil jogou","3","","",""),
array("bret hart","3","","",""),
array("bing.com","3","","",""),
array("bestbuy.com","3","","",""),
array("best buy.com","3","","",""),
array("baby justin bieber","4","","",""),
array("billionaire","4","","",""),
array("baby","4","","",""),
array("beyonce","4","","",""),
array("billionaire travis mccoy","4","","",""),
array("black eyed peas","4","","",""),
array("break your heart","4","","",""),
array("bad romance","4","","",""),
array("bob marley","4","","","")),
"c" => array(
array("craigslist","0","2","",""),
array("cnn","0","2","",""),
array("chase","0","2","",""),
array("costco","0","2","",""),
array("calorie counter","3","4","",""),
array("craigslist dallas","0","","",""),
array("cinemark","0","","",""),
array("carmax","0","","",""),
array("cvs","0","","",""),
array("city of dallas","0","","",""),
array("cnet","0","","",""),
array("crocs","1","","",""),
array("camera","1","","",""),
array("coffee maker","1","","",""),
array("call of duty black ops","1","","",""),
array("canon 7d","1","","",""),
array("canon t2i","1","","",""),
array("cell phone","1","","",""),
array("converse","1","","",""),
array("computer speakers","1","","",""),
array("coach","1","","",""),
array("circuit city","2","","",""),
array("chat","2","","",""),
array("cingular","2","","",""),
array("cartoon network","2","","",""),
array("capital one","2","","",""),
array("comcast","2","","",""),
array("christina hendricks cup size","3","","",""),
array("coursecompass","3","","",""),
array("cala boca justen","3","","",""),
array("cheap airline tickets","3","","",""),
array("cash for clunkers","3","","",""),
array("cheap flights","3","","",""),
array("cellular service","3","","",""),
array("car rentals","3","","",""),
array("calculator","3","","",""),
array("california gurls katy perry","4","","",""),
array("chris brown","4","","",""),
array("cooler than me mike posner","4","","",""),
array("charlie bit my finger","4","","",""),
array("cooler than me","4","","",""),
array("chris brown deuces","4","","",""),
array("can't be tamed","4","","",""),
array("ciara","4","","",""),
array("celine dion","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("dell","0","2","",""),
array("delta airlines","2","3","",""),
array("driving directions","2","3","",""),
array("dillards","0","","",""),
array("dallas morning news","0","","",""),
array("dallas zoo","0","","",""),
array("dominos","0","","",""),
array("dfw airport","0","","",""),
array("dart","0","","",""),
array("dallas county","0","","",""),
array("direct tv","0","","",""),
array("droid x","1","","",""),
array("digital camera","1","","",""),
array("diapers","1","","",""),
array("dexter","1","","",""),
array("dexter season 4","1","","",""),
array("dsi","1","","",""),
array("dvd player","1","","",""),
array("dehumidifier","1","","",""),
array("droid","1","","",""),
array("desk","1","","",""),
array("disney channel","2","","",""),
array("dancing with the stars","2","","",""),
array("david letterman","2","","",""),
array("dish network","2","","",""),
array("directions","2","","",""),
array("dmv","2","","",""),
array("dancing with the stars cast","3","","",""),
array("dancing with the stars season 11","3","","",""),
array("dwts","3","","",""),
array("disneychannel.com","3","","",""),
array("does justin bieber have a girlfriend","3","","",""),
array("distance between 2 cities","3","","",""),
array("dictionary.com","3","","",""),
array("drake","4","","",""),
array("dynamite taio cruz","4","","",""),
array("drake find your love","4","","",""),
array("david guetta","4","","",""),
array("double rainbow","4","","",""),
array("dynamite","4","","",""),
array("drake over","4","","",""),
array("despicable me","4","","",""),
array("demi lovato","4","","",""),
array("drake miss me","4","","","")),
"e" => array(
array("eminem","0","1","2","4"),
array("ebay","0","2","3",""),
array("eclipse","0","1","4",""),
array("espn","0","2","",""),
array("expedia","0","2","",""),
array("eminem recovery","1","4","",""),
array("enterprise car rental","2","3","",""),
array("evite","0","","",""),
array("express","0","","",""),
array("etsy","0","","",""),
array("eecu","0","","",""),
array("enterprise","0","","",""),
array("external hard drive","1","","",""),
array("eat pray love","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("ethernet cable","1","","",""),
array("ed hardy","1","","",""),
array("eclipse dvd","1","","",""),
array("elisabeth hasselbeck","2","","",""),
array("elin nordegren","2","","",""),
array("emma watson","2","","",""),
array("ecards","2","","",""),
array("ebay motors","2","","",""),
array("emmett till","3","","",""),
array("esthetician","3","","",""),
array("emmy awards 2010","3","","",""),
array("ebay.com","3","","",""),
array("expedia.com","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("english to spanish translation","3","","",""),
array("engagement rings","3","","",""),
array("eminem not afraid","4","","",""),
array("eminem love the way you lie","4","","",""),
array("enrique iglesias","4","","",""),
array("eenie meenie justin bieber","4","","",""),
array("eenie meenie","4","","",""),
array("enrique iglesias i like it","4","","",""),
array("eminem ft rihanna","4","","","")),
"f" => array(
array("facebook","0","2","3",""),
array("facebook login","0","2","",""),
array("firefox","0","2","",""),
array("fox news","0","2","",""),
array("fafsa","0","2","",""),
array("fedex","0","2","",""),
array("ford","0","2","",""),
array("free online games","2","3","",""),
array("frys","0","","",""),
array("fifa","0","","",""),
array("fort worth zoo","0","","",""),
array("flash drive","1","","",""),
array("fan","1","","",""),
array("fleshlight","1","","",""),
array("food processor","1","","",""),
array("futon","1","","",""),
array("fantasia","1","","",""),
array("fallout 3","1","","",""),
array("fifa 11","1","","",""),
array("flip video","1","","",""),
array("fallout new vegas","1","","",""),
array("food network","2","","",""),
array("fantasy football","2","","",""),
array("face transplant","3","","",""),
array("france","3","","",""),
array("free ringtones","3","","",""),
array("free music downloads","3","","",""),
array("free games","3","","",""),
array("free people search","3","","",""),
array("find a person","3","","",""),
array("free credit report","3","","",""),
array("funny video","4","","",""),
array("funny","4","","",""),
array("fred","4","","",""),
array("female hair transplant","4","","",""),
array("find your love drake","4","","",""),
array("family guy","4","","",""),
array("funny pranks","4","","",""),
array("funny cats","4","","",""),
array("fireflies","4","","",""),
array("fifa world cup 2010","4","","","")),
"g" => array(
array("google maps","0","2","3",""),
array("games","0","2","3",""),
array("glee","0","1","4",""),
array("gmail","0","2","",""),
array("google earth","0","2","",""),
array("garmin","0","1","",""),
array("google","2","4","",""),
array("google search","2","3","",""),
array("google.com","0","","",""),
array("gamestop","0","","",""),
array("gary coleman","0","","",""),
array("google translate","0","","",""),
array("gps","1","","",""),
array("garmin gps","1","","",""),
array("gift card","1","","",""),
array("guitar","1","","",""),
array("garmin nuvi","1","","",""),
array("girl with the dragon tattoo","1","","",""),
array("god of war 3","1","","",""),
array("guess","1","","",""),
array("google homepage","2","","",""),
array("gap","2","","",""),
array("greeting cards","2","","",""),
array("guitar tabs","2","","",""),
array("grandin","3","","",""),
array("george clooney","3","","",""),
array("glenn beck","3","","",""),
array("google search engine","3","","",""),
array("games.com","3","","",""),
array("girl games","3","","",""),
array("games for kids","3","","",""),
array("gummy bear song","4","","",""),
array("gucci mane","4","","",""),
array("green day","4","","",""),
array("ghost","4","","",""),
array("getting over you david guetta","4","","",""),
array("gorillaz","4","","",""),
array("ghost caught on tape","4","","",""),
array("guns n roses","4","","","")),
"h" => array(
array("home depot","0","2","3",""),
array("hotmail","0","2","",""),
array("honda","0","2","",""),
array("htc evo","0","1","",""),
array("harry potter","1","2","",""),
array("halo","1","4","",""),
array("how to kiss","3","4","",""),
array("hulu","0","","",""),
array("hobby lobby","0","","",""),
array("hp","0","","",""),
array("hurricane harbor","0","","",""),
array("hawaiian falls","0","","",""),
array("half price books","0","","",""),
array("halo reach","1","","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("hunger games","1","","",""),
array("hello kitty","1","","",""),
array("how to train your dragon","1","","",""),
array("hard drive","1","","",""),
array("hitler dna","2","","",""),
array("hayden panettiere","2","","",""),
array("horoscopes","2","","",""),
array("hi5","2","","",""),
array("holiday inn","2","","",""),
array("halloween costumes","2","","",""),
array("hurricane earl path","3","","",""),
array("hurricane earl","3","","",""),
array("halle berry","3","","",""),
array("how much should i weigh","3","","",""),
array("how to get pregnant","3","","",""),
array("how do you spell a word","3","","",""),
array("how to make a website","3","","",""),
array("hotmail.com","3","","",""),
array("hey soul sister","4","","",""),
array("harry potter and the deathly hallows trailer","4","","",""),
array("hannah montana","4","","",""),
array("happy tree friends","4","","",""),
array("hello good morning","4","","",""),
array("hey soul sister train","4","","",""),
array("hallelujah","4","","",""),
array("hannah montana songs","4","","","")),
"i" => array(
array("itunes","0","2","3",""),
array("ipad","0","1","3",""),
array("iphone 4","0","1","4",""),
array("iphone","0","1","2",""),
array("ikea","0","2","",""),
array("imdb","0","2","",""),
array("irs","0","2","",""),
array("inception","0","4","",""),
array("ipod touch","1","3","",""),
array("ipod","1","2","",""),
array("inspirational quotes","2","3","",""),
array("indeed","0","","",""),
array("iphone 4g","0","","",""),
array("iphone 4 case","1","","",""),
array("ipod nano","1","","",""),
array("iphone 3gs","1","","",""),
array("ipad case","1","","",""),
array("itouch","1","","",""),
array("internet explorer","2","","",""),
array("imeem","2","","",""),
array("ign","2","","",""),
array("indonesia","3","","",""),
array("intel","3","","",""),
array("is the world going to end in 2012","3","","",""),
array("italy travel","3","","",""),
array("internet explorer 8","3","","",""),
array("is bronchitis contagious","3","","",""),
array("i like it enrique iglesias","4","","",""),
array("i love the way you lie","4","","",""),
array("impossible shontelle","4","","",""),
array("inception trailer","4","","",""),
array("i like it","4","","",""),
array("i wanna be a billionaire","4","","",""),
array("in my head jason derulo","4","","",""),
array("is not afraid eminem","4","","","")),
"j" => array(
array("justin bieber","0","1","3","4"),
array("jobs","0","2","3",""),
array("jcpenney","0","2","",""),
array("jokes","0","2","",""),
array("james avery","0","","",""),
array("java","0","","",""),
array("jason's deli","0","","",""),
array("jimmy johns","0","","",""),
array("jet blue","0","","",""),
array("jack in the box","0","","",""),
array("jansport backpack","1","","",""),
array("juicer","1","","",""),
array("jillian michaels","1","","",""),
array("juicy couture","1","","",""),
array("jansport","1","","",""),
array("james patterson","1","","",""),
array("jewelry box","1","","",""),
array("john mayer","1","","",""),
array("jack johnson","1","","",""),
array("jessica simpson","2","","",""),
array("jennifer aniston","2","","",""),
array("jessica alba","2","","",""),
array("jennifer lopez","2","","",""),
array("jennifer love hewitt","2","","",""),
array("john travolta","2","","",""),
array("jetblue","2","","",""),
array("jcp l","3","","",""),
array("jimmy fallon emmy opening","3","","",""),
array("jessica rudd","3","","",""),
array("jobs in my area","3","","",""),
array("justin bieber cell number","3","","",""),
array("job search","3","","",""),
array("jcpenney.com","3","","",""),
array("justin bieber quiz","3","","",""),
array("justin bieber baby","4","","",""),
array("justin bieber eenie meenie","4","","",""),
array("justin bieber one time","4","","",""),
array("justin bieber never say never","4","","",""),
array("justin bieber somebody to love","4","","",""),
array("jason derulo ridin solo","4","","",""),
array("justin bieber love me","4","","",""),
array("jay z","4","","",""),
array("justin timberlake","4","","","")),
"k" => array(
array("kmart","0","2","3",""),
array("katy perry","1","2","4",""),
array("kohls","0","3","",""),
array("kim kardashian","2","3","",""),
array("kroger","0","","",""),
array("keller isd","0","","",""),
array("kfc","0","","",""),
array("kayak","0","","",""),
array("klty","0","","",""),
array("kera","0","","",""),
array("kesha","0","","",""),
array("kinkos","0","","",""),
array("kindle","1","","",""),
array("keurig","1","","",""),
array("kindle dx","1","","",""),
array("k cups","1","","",""),
array("kindle cover","1","","",""),
array("keyboard","1","","",""),
array("kinect","1","","",""),
array("kindle 2","1","","",""),
array("knife","1","","",""),
array("katie holmes","2","","",""),
array("kristen bell","2","","",""),
array("kristi gibson","2","","",""),
array("kelley blue book","2","","",""),
array("kohl's","2","","",""),
array("kirstie alley","2","","",""),
array("kelly clarkson","2","","",""),
array("kyrgyzstan","3","","",""),
array("kohls.com","3","","",""),
array("kelly blue book","3","","",""),
array("kmart.com","3","","",""),
array("kids games","3","","",""),
array("kijiji","3","","",""),
array("kayak.com","3","","",""),
array("katy perry california","4","","",""),
array("kesha your love is my drug","4","","",""),
array("katy perry california girlz","4","","",""),
array("kiss","4","","",""),
array("kid cudi","4","","",""),
array("kanye west","4","","",""),
array("keong racun","4","","",""),
array("keisha tik tok","4","","",""),
array("kanye west power","4","","","")),
"l" => array(
array("lady gaga","0","1","2","4"),
array("lost","0","1","2",""),
array("lyrics","0","2","3",""),
array("lowes","0","3","",""),
array("limewire","0","2","",""),
array("la fitness","0","","",""),
array("linkedin","0","","",""),
array("lone star park","0","","",""),
array("lebron james","0","","",""),
array("lexus","0","","",""),
array("laptop","1","","",""),
array("lost season 6","1","","",""),
array("luggage","1","","",""),
array("lego star wars","1","","",""),
array("laptop computer","1","","",""),
array("lego","1","","",""),
array("laptop bag","1","","",""),
array("lunch box","1","","",""),
array("leann rimes","2","","",""),
array("lottery ticket","2","","",""),
array("lauryn hill","2","","",""),
array("lindsay lohan","2","","",""),
array("lowe's","2","","",""),
array("lisa murkowski","2","","",""),
array("la barbie","3","","",""),
array("little league","3","","",""),
array("laura salpietro","3","","",""),
array("lyrics to songs","3","","",""),
array("lowes.com","3","","",""),
array("love poems","3","","",""),
array("lingerie","3","","",""),
array("love quotes","3","","",""),
array("love the way you lie","4","","",""),
array("lady gaga alejandro","4","","",""),
array("lil wayne","4","","",""),
array("loan mods","4","","",""),
array("love the way you lie eminem","4","","",""),
array("lady gaga bad romance","4","","",""),
array("linkin park","4","","",""),
array("love the way you lie lyrics","4","","",""),
array("lil wayne drop the world","4","","","")),
"m" => array(
array("maps","0","2","3",""),
array("myspace","0","2","",""),
array("mapquest","0","2","",""),
array("msn","0","2","",""),
array("movies","0","2","",""),
array("music","2","4","",""),
array("mariah carey","2","4","",""),
array("msnbc","0","","",""),
array("metro pcs","0","","",""),
array("mtv","0","","",""),
array("movie tavern","0","","",""),
array("michaels","0","","",""),
array("mockingjay","1","","",""),
array("macbook","1","","",""),
array("madden 11","1","","",""),
array("macbook pro","1","","",""),
array("mafia 2","1","","",""),
array("micro sd","1","","",""),
array("messenger bag","1","","",""),
array("microsoft office 2010","1","","",""),
array("mp3 player","1","","",""),
array("mad men","1","","",""),
array("miss universe 2010","2","","",""),
array("mail","2","","",""),
array("macaulay culkin","2","","",""),
array("margaret cho","3","","",""),
array("monmouth county power outage","3","","",""),
array("monday night football schedule 2010","3","","",""),
array("mapquest driving directions","3","","",""),
array("myspace layouts","3","","",""),
array("mortgage calculator","3","","",""),
array("medical dictionary","3","","",""),
array("math answers","3","","",""),
array("meaning of names","3","","",""),
array("michael jackson","4","","",""),
array("miley cyrus","4","","",""),
array("my wife having an affair","4","","",""),
array("miley cyrus can't be tamed","4","","",""),
array("my first kiss","4","","",""),
array("metallica","4","","",""),
array("miley cyrus party in the usa","4","","",""),
array("muse","4","","","")),
"n" => array(
array("netflix","0","2","3",""),
array("nissan","0","2","3",""),
array("nordstrom","0","2","",""),
array("nba","0","2","",""),
array("news","0","3","",""),
array("nbc","0","2","",""),
array("nokia","1","2","",""),
array("nfl","2","3","",""),
array("ntta","0","","",""),
array("ntb","0","","",""),
array("nada","0","","",""),
array("nick","0","","",""),
array("netbook","1","","",""),
array("nikon d90","1","","",""),
array("nike","1","","",""),
array("nook","1","","",""),
array("nintendo ds","1","","",""),
array("nikon d5000","1","","",""),
array("nintendo dsi","1","","",""),
array("nikon d3000","1","","",""),
array("nintendo wii","1","","",""),
array("nick jr","2","","",""),
array("nascar","2","","",""),
array("northwest airlines","2","","",""),
array("ndamukong suh jake delhomme","3","","",""),
array("netherlands","3","","",""),
array("name meanings","3","","",""),
array("netflix.com","3","","",""),
array("nudyphotos","3","","",""),
array("nissan.com","3","","",""),
array("not afraid eminem","4","","",""),
array("nicki minaj","4","","",""),
array("never say never","4","","",""),
array("never say never justin bieber","4","","",""),
array("not afraid","4","","",""),
array("nigahiga","4","","",""),
array("nicki minaj your love","4","","",""),
array("new songs 2010","4","","",""),
array("nothing on you b.o.b","4","","",""),
array("nickelback","4","","","")),
"o" => array(
array("old navy","0","2","3",""),
array("online games","0","2","3",""),
array("office depot","0","2","",""),
array("orbitz","0","2","",""),
array("overstock","0","2","",""),
array("oprah","0","2","",""),
array("online dictionary","2","3","",""),
array("omg","2","4","",""),
array("olive garden","0","","",""),
array("oil spill","0","","",""),
array("office max","0","","",""),
array("on the border","0","","",""),
array("oakley","1","","",""),
array("otterbox","1","","",""),
array("otterbox iphone 4","1","","",""),
array("oakley sunglasses","1","","",""),
array("office 2010","1","","",""),
array("one tree hill","1","","",""),
array("ooma","1","","",""),
array("office chair","1","","",""),
array("one tree hill season 7","1","","",""),
array("opi nail polish","1","","",""),
array("ozzy osbourne","2","","",""),
array("orkut","2","","",""),
array("osama bin laden","3","","",""),
array("online pregnancy test","3","","",""),
array("ovulation calendar","3","","",""),
array("ovulation calculator","3","","",""),
array("overstock.com","3","","",""),
array("obituaries","3","","",""),
array("obituary searches","3","","",""),
array("omg usher","4","","",""),
array("oil rig employment","4","","",""),
array("old spice commercial","4","","",""),
array("old spice","4","","",""),
array("one time justin bieber","4","","",""),
array("one time","4","","",""),
array("over drake","4","","",""),
array("omg usher will i am","4","","",""),
array("owl city fireflies","4","","","")),
"p" => array(
array("pizza hut","0","2","",""),
array("paypal","0","2","",""),
array("p90x","0","1","",""),
array("photobucket","0","2","",""),
array("priceline","0","2","",""),
array("pokemon","1","4","",""),
array("people search","2","3","",""),
array("pandora","0","","",""),
array("petsmart","0","","",""),
array("pei wei","0","","",""),
array("party city","0","","",""),
array("pac-man 30th anniversary","0","","",""),
array("ps3","1","","",""),
array("psp","1","","",""),
array("playstation 3","1","","",""),
array("pillow pets","1","","",""),
array("posters","1","","",""),
array("ps3 console","1","","",""),
array("portable dvd player","1","","",""),
array("projector","1","","",""),
array("pogo","2","","",""),
array("paul hogan","2","","",""),
array("powerball","2","","",""),
array("people magazine","2","","",""),
array("pottery barn","2","","",""),
array("perla ferrar","3","","",""),
array("previewuckermann","3","","",""),
array("paula abdul","3","","",""),
array("pregnancy week by week","3","","",""),
array("priceline.com","3","","",""),
array("people finder","3","","",""),
array("phone number lookup","3","","",""),
array("people search for free","3","","",""),
array("pregnancy symptoms","3","","",""),
array("paramore","4","","",""),
array("pretty boy swag","4","","",""),
array("pyramid charice","4","","",""),
array("party in the usa","4","","",""),
array("pitbull","4","","",""),
array("pink","4","","",""),
array("pyramid","4","","",""),
array("pretty boy swag soulja boy","4","","",""),
array("poker face","4","","","")),
"q" => array(
array("quickbooks","0","1","2","3"),
array("quotes","0","2","3",""),
array("qvc","0","2","",""),
array("quicktime","0","2","",""),
array("quiznos","0","2","",""),
array("quicken","0","1","",""),
array("quotes about life","0","3","",""),
array("queen","1","4","",""),
array("queens of the stone age","1","4","",""),
array("quizzes","2","3","",""),
array("quick trip","0","","",""),
array("quinoa","0","","",""),
array("qt","0","","",""),
array("quiksilver","1","","",""),
array("quickbooks pro 2010","1","","",""),
array("queen mattress","1","","",""),
array("quilt","1","","",""),
array("quicksilver","1","","",""),
array("queer as folk","1","","",""),
array("quest diagnostics","2","","",""),
array("qwest","2","","",""),
array("query string","2","","",""),
array("quizilla","2","","",""),
array("quotes of the day","3","","",""),
array("quotes and sayings","3","","",""),
array("quinceanera dresses","3","","",""),
array("quick mileage city to city","3","","",""),
array("questions to ask your boyfriend","3","","",""),
array("qvc home shopping","3","","",""),
array("queen bohemian rhapsody","4","","",""),
array("quest crew","4","","",""),
array("queen we will rock you","4","","",""),
array("queen don't stop me now","4","","",""),
array("queen i want to break free","4","","",""),
array("queen somebody to love","4","","",""),
array("queen seondeok","4","","",""),
array("queen we are the champions","4","","","")),
"e" => array(
array("eminem","0","1","2","4"),
array("ebay","0","2","3",""),
array("eclipse","0","1","4",""),
array("espn","0","2","",""),
array("expedia","0","2","",""),
array("eminem recovery","1","4","",""),
array("enterprise car rental","2","3","",""),
array("evite","0","","",""),
array("express","0","","",""),
array("etsy","0","","",""),
array("eecu","0","","",""),
array("enterprise","0","","",""),
array("external hard drive","1","","",""),
array("eat pray love","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("ethernet cable","1","","",""),
array("ed hardy","1","","",""),
array("eclipse dvd","1","","",""),
array("elisabeth hasselbeck","2","","",""),
array("elin nordegren","2","","",""),
array("emma watson","2","","",""),
array("ecards","2","","",""),
array("ebay motors","2","","",""),
array("emmett till","3","","",""),
array("esthetician","3","","",""),
array("emmy awards 2010","3","","",""),
array("ebay.com","3","","",""),
array("expedia.com","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("english to spanish translation","3","","",""),
array("engagement rings","3","","",""),
array("eminem not afraid","4","","",""),
array("eminem love the way you lie","4","","",""),
array("enrique iglesias","4","","",""),
array("eenie meenie justin bieber","4","","",""),
array("eenie meenie","4","","",""),
array("enrique iglesias i like it","4","","",""),
array("eminem ft rihanna","4","","","")),
"s" => array(
array("southwest airlines","0","2","3",""),
array("sears","0","2","",""),
array("skype","0","2","",""),
array("sprint","0","2","",""),
array("song lyrics","2","3","",""),
array("shakira","2","4","",""),
array("sonic","0","","",""),
array("sams club","0","","",""),
array("subway","0","","",""),
array("sbec","0","","",""),
array("studio movie grill","0","","",""),
array("speed test","0","","",""),
array("starcraft 2","1","","",""),
array("scott pilgrim","1","","",""),
array("silly bandz","1","","",""),
array("sunglasses","1","","",""),
array("star wars","1","","",""),
array("samsung vibrant","1","","",""),
array("sd card","1","","",""),
array("samsung captivate","1","","",""),
array("starcraft","1","","",""),
array("shoes","1","","",""),
array("staples","2","","",""),
array("sean connery","2","","",""),
array("susan boyle","2","","",""),
array("sandra bullock","2","","",""),
array("sydney dalton","3","","",""),
array("survivor philippines","3","","",""),
array("splitter","3","","",""),
array("spanish dictionary","3","","",""),
array("signs of pregnancy","3","","",""),
array("sexy","3","","",""),
array("swine flu symptoms","3","","",""),
array("spanish translator","3","","",""),
array("shakira waka waka","4","","",""),
array("solo","4","","",""),
array("somebody to love justin bieber","4","","",""),
array("solo iyaz","4","","",""),
array("selena gomez","4","","",""),
array("sexist video of man and woman","4","","",""),
array("soulja boy","4","","",""),
array("shane dawson","4","","",""),
array("stereo love","4","","","")),
"t" => array(
array("target","0","2","3",""),
array("tmz","0","2","",""),
array("ticketmaster","0","2","",""),
array("travelocity","0","2","",""),
array("toy story 3","1","4","",""),
array("taylor swift","2","4","",""),
array("texas rangers","0","","",""),
array("texas lottery","0","","",""),
array("twitter","0","","",""),
array("txu","0","","",""),
array("tcc","0","","",""),
array("translator","0","","",""),
array("twilight","1","","",""),
array("true blood","1","","",""),
array("the girl with the dragon tattoo","1","","",""),
array("toy story","1","","",""),
array("the help","1","","",""),
array("tv","1","","",""),
array("the office","1","","",""),
array("transformers","1","","",""),
array("the hunger games","1","","",""),
array("toys r us","2","","",""),
array("toyota","2","","",""),
array("tagged","2","","",""),
array("t-mobile","2","","",""),
array("tiger woods","2","","",""),
array("thelma todd","3","","",""),
array("troy polamalu","3","","",""),
array("tattoo designs","3","","",""),
array("tattoos","3","","",""),
array("translate english to spanish","3","","",""),
array("teen pregnancy signs","3","","",""),
array("translate spanish to english","3","","",""),
array("telephone directory","3","","",""),
array("tires","3","","",""),
array("teach me how to dougie","4","","",""),
array("tik tok","4","","",""),
array("tattoo patterns","4","","",""),
array("trey songz","4","","",""),
array("the annoying orange","4","","",""),
array("taio cruz dynamite","4","","",""),
array("tom and jerry","4","","",""),
array("telephone lady gaga lyrics","4","","","")),
"u" => array(
array("ufc","0","2","3","4"),
array("us airways","0","2","3",""),
array("united airlines","0","2","3",""),
array("usps","0","2","",""),
array("ups","0","2","",""),
array("usaa","0","2","",""),
array("univision","0","2","",""),
array("usher","1","4","",""),
array("used cars","2","3","",""),
array("utube","0","","",""),
array("uhaul","0","","",""),
array("ups tracking","0","","",""),
array("unlocked cell phones","1","","",""),
array("usb flash drive","1","","",""),
array("usb hub","1","","",""),
array("umbrella","1","","",""),
array("under armour","1","","",""),
array("uncharted 2","1","","",""),
array("uggs","1","","",""),
array("usb cable","1","","",""),
array("usb","1","","",""),
array("us bank","2","","",""),
array("utusan malaysia","2","","",""),
array("uzbekistan","3","","",""),
array("used cars for sale","3","","",""),
array("unique baby names","3","","",""),
array("unemployment benefits","3","","",""),
array("us airways.com","3","","",""),
array("used cars for sale in my area","3","","",""),
array("usher omg","4","","",""),
array("usher there goes my baby","4","","",""),
array("unthinkable alicia keys","4","","",""),
array("u2","4","","",""),
array("usher daddy's home","4","","",""),
array("ufo","4","","",""),
array("usher yeah","4","","",""),
array("up all night drake nicki minaj","4","","","")),
"v" => array(
array("verizon","0","2","3",""),
array("verizon wireless","0","2","3",""),
array("vuvuzela","0","1","4",""),
array("vh1","0","2","",""),
array("vonage","0","2","",""),
array("verizon cell phones","1","3","",""),
array("vanessa hudgens","2","4","",""),
array("virgin mobile","2","3","",""),
array("vlc","0","","",""),
array("verizon fios","0","","",""),
array("victoria secret","0","","",""),
array("vrbo","0","","",""),
array("verizon.net","0","","",""),
array("vacuum cleaner","1","","",""),
array("vera bradley","1","","",""),
array("vampire diaries","1","","",""),
array("vans","1","","",""),
array("vacuum","1","","",""),
array("video camera","1","","",""),
array("vibratores for women","1","","",""),
array("vibram five fingers","1","","",""),
array("victoria's secret","2","","",""),
array("video","2","","",""),
array("victoria beckham","2","","",""),
array("value city furniture","2","","",""),
array("viet cong","3","","",""),
array("verizon.com","3","","",""),
array("verizonwireless.com","3","","",""),
array("virtual worlds","3","","",""),
array("very early symptoms of pregnancy","3","","",""),
array("vending machine","3","","",""),
array("vanilla twilight","4","","",""),
array("vybz kartel","4","","",""),
array("vampire weekend","4","","",""),
array("vicente fernandez","4","","",""),
array("videos grasiosos","4","","",""),
array("vanilla twilight owl city","4","","",""),
array("video phone","4","","",""),
array("van halen","4","","","")),
"w" => array(
array("weather","0","2","3",""),
array("white pages","0","2","3",""),
array("wells fargo","0","2","",""),
array("walgreens","0","2","",""),
array("wikipedia","0","2","",""),
array("webmd","0","2","",""),
array("wwe","2","4","",""),
array("walmart","0","","",""),
array("wfaa","0","","",""),
array("web md","0","","",""),
array("www.facebook.com","0","","",""),
array("wii","1","","",""),
array("wireless router","1","","",""),
array("windows 7","1","","",""),
array("webcam","1","","",""),
array("wii console","1","","",""),
array("wii games","1","","",""),
array("watches","1","","",""),
array("world of warcraft","1","","",""),
array("wireless mouse","1","","",""),
array("wallet","1","","",""),
array("wal mart","2","","",""),
array("webkinz","2","","",""),
array("wachovia","2","","",""),
array("weeds season 6 episode 3","3","","",""),
array("what does my last name mean","3","","",""),
array("where can i watch free movies online","3","","",""),
array("what is love","3","","",""),
array("what is the meaning of my name","3","","",""),
array("when will the world end","3","","",""),
array("what is justin biebers phone number","3","","",""),
array("walmart.com","3","","",""),
array("waka waka","4","","",""),
array("waka waka shakira","4","","",""),
array("waving flag","4","","",""),
array("we no speak americano","4","","",""),
array("waving flag k'naan","4","","",""),
array("wisin y yandel","4","","",""),
array("world cup 2010 song","4","","",""),
array("we are the world","4","","",""),
array("wiz khalifa","4","","","")),
"x" => array(
array("xbox 360","1","2","3","4"),
array("xbox","0","1","3",""),
array("xm radio","0","2","3",""),
array("xbox live","0","1","2",""),
array("xanax","0","2","",""),
array("xbox 360 slim","1","4","",""),
array("xbox 360 games","1","3","",""),
array("xbox cheats","2","3","",""),
array("x factor","2","4","",""),
array("xkcd","0","","",""),
array("xbmc","0","","",""),
array("xanga","0","","",""),
array("xto","0","","",""),
array("xto energy","0","","",""),
array("xe","0","","",""),
array("xbox 360 console","1","","",""),
array("xbox 360 controller","1","","",""),
array("xbox 360 wireless adapter","1","","",""),
array("xbox 360 elite","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("x games","2","","",""),
array("xvid","2","","",""),
array("x17","2","","",""),
array("xerox","2","","",""),
array("xbox 360 cheats","3","","",""),
array("x ray schools","3","","",""),
array("xbox 360 cheat codes","3","","",""),
array("xxl tv live","3","","",""),
array("xbox 360 problems","3","","",""),
array("x factor 2010","4","","",""),
array("xzibit","4","","",""),
array("xb gensan","4","","",""),
array("x","4","","",""),
array("xbox 720","4","","",""),
array("xb gensan in show time","4","","",""),
array("xscape","4","","","")),
"y" => array(
array("youtube","0","2","3","4"),
array("yahoo mail","0","2","3",""),
array("yellow pages","0","2","3",""),
array("yahoo","0","2","",""),
array("yahoo maps","0","2","",""),
array("young jeezy","1","4","",""),
array("yahoomail.com","0","","",""),
array("ymca","0","","",""),
array("yahoo answers","0","","",""),
array("yahoo music","0","","",""),
array("y8","0","","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yoga dvd","1","","",""),
array("yugioh cards","1","","",""),
array("yo gabba gabba","1","","",""),
array("your baby can read","1","","",""),
array("yugioh","1","","",""),
array("yarn","1","","",""),
array("yogurt maker","1","","",""),
array("youtube video","2","","",""),
array("yahoo messenger","2","","",""),
array("youtube broadcast yourself","2","","",""),
array("you","2","","",""),
array("yahoo games","2","","",""),
array("youtube videos","3","","",""),
array("yellowpages.com","3","","",""),
array("yellow pages.com","3","","",""),
array("yahoo.com","3","","",""),
array("youtube music","3","","",""),
array("youtube music videos","3","","",""),
array("yahoo.com email","3","","",""),
array("your love is my drug","4","","",""),
array("your love nicki minaj","4","","",""),
array("your love is my drug kesha","4","","",""),
array("your love","4","","",""),
array("you belong with me","4","","",""),
array("young money","4","","",""),
array("yolanda be cool we no speak americano","4","","",""),
array("you belong with me taylor swift","4","","","")),
"z" => array(
array("zip codes","0","2","3",""),
array("zumba","0","1","4",""),
array("zune","0","1","2",""),
array("zodiac signs","0","2","3",""),
array("zappos","0","2","",""),
array("zillow","0","2","",""),
array("zales","0","2","",""),
array("zac brown band","1","4","",""),
array("zip code lookup","2","3","",""),
array("zac efron","2","4","",""),
array("zip code finder","2","3","",""),
array("zumiez","0","","",""),
array("zoosk","0","","",""),
array("zagg","0","","",""),
array("zune hd","1","","",""),
array("zhu zhu pets","1","","",""),
array("zippo","1","","",""),
array("zumba fitness dvd","1","","",""),
array("zelda","1","","",""),
array("zumba dvd","1","","",""),
array("zippo lighter","1","","",""),
array("zuma","2","","",""),
array("zip code list","3","","",""),
array("zucchini bread recipes","3","","",""),
array("zucchini recipes","3","","",""),
array("zip code directory","3","","",""),
array("zappos.com","3","","",""),
array("zip code maps free","3","","",""),
array("zombie","4","","",""),
array("zidane","4","","",""),
array("zz top","4","","",""),
array("zombie cranberries","4","","",""),
array("zombieland","4","","",""),
array("zidane headbutt","4","","",""),
array("zac brown band free","4","","","")));
?>