<?php $topResults = array(
"a" => array(
array("air conditioner","1","","",""),
array("airsoft guns","1","","",""),
array("avatar","1","","",""),
array("adidas","1","","",""),
array("alice in wonderland","1","","",""),
array("avenged sevenfold","1","","",""),
array("apple","1","","",""),
array("avatar the last airbender","1","","",""),
array("apple ipad","1","","",""),
array("airsoft","1","","",""),
array("amazon","2","","",""),
array("aol","2","","",""),
array("ask jeeves","2","","",""),
array("andy griffith","2","","",""),
array("american idol","2","","",""),
array("amanda bynes","2","","",""),
array("at&t","2","","",""),
array("autotrader","2","","",""),
array("american airlines","2","","",""),
array("angelina jolie","2","","",""),
array("at t","3","","",""),
array("airline tickets","3","","",""),
array("apartments for rent","3","","",""),
array("are vampires real","3","","",""),
array("att.com","3","","",""),
array("area codes","3","","",""),
array("att","3","","",""),
array("am i pregnant","3","","",""),
array("aaa","3","","",""),
array("ancestry.com","3","","",""),
array("alejandro lady gaga","4","","",""),
array("airplanes","4","","",""),
array("airplanes b.o.b","4","","",""),
array("annoying orange","4","","",""),
array("akon","4","","",""),
array("alejandro","4","","",""),
array("alicia keys","4","","",""),
array("airplanes hayley williams","4","","",""),
array("avril lavigne","4","","",""),
array("america's got talent","4","","","")),
"b" => array(
array("britney spears","1","2","4",""),
array("best buy","2","3","",""),
array("bank of america","2","3","",""),
array("baby names","2","3","",""),
array("bed bath and beyond","2","3","",""),
array("babies r us","2","3","",""),
array("blackberry","1","","",""),
array("backpack","1","","",""),
array("bluetooth headset","1","","",""),
array("blackberry bold 9700","1","","",""),
array("blu ray","1","","",""),
array("bose","1","","",""),
array("blu ray player","1","","",""),
array("blackberry unlocked","1","","",""),
array("blender","1","","",""),
array("brittany murphy","2","","",""),
array("blank","2","","",""),
array("barnes and noble","2","","",""),
array("blockbuster","2","","",""),
array("baby shower games","3","","",""),
array("baby boy names","3","","",""),
array("bmi","3","","",""),
array("baby girl names","3","","",""),
array("bing","3","","",""),
array("baby justin bieber","4","","",""),
array("billionaire","4","","",""),
array("baby","4","","",""),
array("beyonce","4","","",""),
array("billionaire travis mccoy","4","","",""),
array("black eyed peas","4","","",""),
array("break your heart","4","","",""),
array("bad romance","4","","",""),
array("b.o.b airplanes","4","","","")),
"c" => array(
array("calorie counter","3","4","",""),
array("crocs","1","","",""),
array("camera","1","","",""),
array("canon t2i","1","","",""),
array("coffee maker","1","","",""),
array("canon 7d","1","","",""),
array("cell phone","1","","",""),
array("clash of the titans","1","","",""),
array("canon","1","","",""),
array("converse","1","","",""),
array("call of duty modern warfare 2","1","","",""),
array("craigslist","2","","",""),
array("cnn","2","","",""),
array("cheesecake factory","2","","",""),
array("circuit city","2","","",""),
array("chelsea clinton","2","","",""),
array("costco","2","","",""),
array("chat","2","","",""),
array("chase","2","","",""),
array("cingular","2","","",""),
array("cartoon network","2","","",""),
array("cheap airline tickets","3","","",""),
array("cheap flights","3","","",""),
array("car rentals","3","","",""),
array("calculator","3","","",""),
array("coupons","3","","",""),
array("cars","3","","",""),
array("cheat codes","3","","",""),
array("cheap hotels","3","","",""),
array("clip art","3","","",""),
array("california gurls katy perry","4","","",""),
array("chris brown","4","","",""),
array("cooler than me mike posner","4","","",""),
array("charlie bit my finger","4","","",""),
array("can't be tamed","4","","",""),
array("cooler than me","4","","",""),
array("can't be tamed miley cyrus","4","","",""),
array("cristiano ronaldo","4","","",""),
array("ciara","4","","","")),
"d" => array(
array("drake","1","4","",""),
array("dictionary","2","3","",""),
array("dell","2","3","",""),
array("delta airlines","2","3","",""),
array("driving directions","2","3","",""),
array("droid x","1","","",""),
array("digital camera","1","","",""),
array("diapers","1","","",""),
array("dexter","1","","",""),
array("dsi","1","","",""),
array("dvd player","1","","",""),
array("dehumidifier","1","","",""),
array("droid","1","","",""),
array("dvd","1","","",""),
array("disney channel","2","","",""),
array("donna mccall butch patrick","2","","",""),
array("dancing with the stars","2","","",""),
array("dish network","2","","",""),
array("directions","2","","",""),
array("dmv","2","","",""),
array("disneychannel.com","3","","",""),
array("dogs","3","","",""),
array("dictionary.com","3","","",""),
array("download free music","3","","",""),
array("delta.com","3","","",""),
array("direct tv","3","","",""),
array("drake find your love","4","","",""),
array("dynamite taio cruz","4","","",""),
array("david guetta","4","","",""),
array("drake over","4","","",""),
array("demi lovato","4","","",""),
array("dynamite","4","","",""),
array("double rainbow","4","","",""),
array("drake miss me","4","","",""),
array("despicable me","4","","","")),
"e" => array(
array("eminem","1","2","4",""),
array("eclipse","1","4","",""),
array("eminem recovery","1","4","",""),
array("ebay","2","3","",""),
array("expedia","2","3","",""),
array("enterprise car rental","2","3","",""),
array("external hard drive","1","","",""),
array("eat pray love","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("entourage","1","","",""),
array("eclipse soundtrack","1","","",""),
array("ed hardy","1","","",""),
array("espn","2","","",""),
array("embedded img","2","","",""),
array("ecards","2","","",""),
array("elin nordegren","2","","",""),
array("ebay motors","2","","",""),
array("eva longoria","2","","",""),
array("ebay.com","3","","",""),
array("expedia.com","3","","",""),
array("eharmony","3","","",""),
array("english to spanish translation","3","","",""),
array("engagement rings","3","","",""),
array("eharmony.com","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("eminem not afraid","4","","",""),
array("eenie meenie","4","","",""),
array("eenie meenie justin bieber","4","","",""),
array("eclipse trailer official 2010","4","","",""),
array("enrique iglesias","4","","",""),
array("eminem love the way you lie","4","","",""),
array("eminem beautiful","4","","","")),
"f" => array(
array("family guy","1","4","",""),
array("free online games","2","3","",""),
array("flash drive","1","","",""),
array("fan","1","","",""),
array("fleshlight","1","","",""),
array("food processor","1","","",""),
array("flip video","1","","",""),
array("fallout 3","1","","",""),
array("fushigi ball","1","","",""),
array("final fantasy xiii","1","","",""),
array("futon","1","","",""),
array("facebook","2","","",""),
array("facebook login","2","","",""),
array("food network","2","","",""),
array("fox news","2","","",""),
array("fat joe","2","","",""),
array("fedex","2","","",""),
array("fantasy football","2","","",""),
array("fafsa","2","","",""),
array("firefox","2","","",""),
array("free ringtones","3","","",""),
array("free music downloads","3","","",""),
array("free games","3","","",""),
array("free ecards","3","","",""),
array("find people","3","","",""),
array("free people search","3","","",""),
array("find a person","3","","",""),
array("free music","3","","",""),
array("free credit report","3","","",""),
array("funny video","4","","",""),
array("funny","4","","",""),
array("fred","4","","",""),
array("female hair transplant","4","","",""),
array("find your love drake","4","","",""),
array("fifa world cup 2010","4","","",""),
array("funny cats","4","","",""),
array("funny pranks","4","","",""),
array("fireflies","4","","","")),
"g" => array(
array("glee","1","4","",""),
array("google","2","4","",""),
array("games","2","3","",""),
array("google search","2","3","",""),
array("google maps","2","3","",""),
array("gps","1","","",""),
array("garmin","1","","",""),
array("garmin gps","1","","",""),
array("girl with the dragon tattoo","1","","",""),
array("garmin nuvi","1","","",""),
array("gift card","1","","",""),
array("guitar","1","","",""),
array("god of war 3","1","","",""),
array("guess","1","","",""),
array("gmail","2","","",""),
array("guns n roses","2","","",""),
array("gwyneth paltrow","2","","",""),
array("google homepage","2","","",""),
array("gap","2","","",""),
array("google earth","2","","",""),
array("global warming","3","","",""),
array("games.com","3","","",""),
array("google search engine","3","","",""),
array("girl games","3","","",""),
array("gnc","3","","",""),
array("genital warts","3","","",""),
array("game cheats","3","","",""),
array("gummy bear song","4","","",""),
array("gucci mane","4","","",""),
array("green day","4","","",""),
array("gorillaz","4","","",""),
array("ghost","4","","",""),
array("getting over you david guetta","4","","",""),
array("ghost caught on tape","4","","",""),
array("glee don't stop believe","4","","","")),
"h" => array(
array("harry potter","1","2","",""),
array("hotmail","2","3","",""),
array("home depot","2","3","",""),
array("halloween costumes","2","3","",""),
array("how to kiss","3","4","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("halo reach","1","","",""),
array("htc evo","1","","",""),
array("how to train your dragon","1","","",""),
array("hello kitty","1","","",""),
array("hard drive","1","","",""),
array("htc","1","","",""),
array("heart rate monitor","1","","",""),
array("horoscopes","2","","",""),
array("hi5","2","","",""),
array("honda","2","","",""),
array("holiday inn","2","","",""),
array("helen mirren","2","","",""),
array("harian metro","2","","",""),
array("how much should i weigh","3","","",""),
array("how to get pregnant","3","","",""),
array("how do you spell a word","3","","",""),
array("hotmail.com","3","","",""),
array("how to make a website","3","","",""),
array("how to write a resume","3","","",""),
array("hey soul sister","4","","",""),
array("harry potter and the deathly hallows trailer","4","","",""),
array("hannah montana","4","","",""),
array("happy tree friends","4","","",""),
array("hello good morning","4","","",""),
array("hey soul sister train","4","","",""),
array("hallelujah","4","","",""),
array("halo","4","","",""),
array("hero","4","","","")),
"i" => array(
array("iphone","1","2","3",""),
array("ipod","1","2","3",""),
array("ipod touch","1","3","",""),
array("iphone 4","1","4","",""),
array("itunes","2","3","",""),
array("inspirational quotes","2","3","",""),
array("ipad","1","","",""),
array("iphone 4 case","1","","",""),
array("ipod nano","1","","",""),
array("iphone 3gs","1","","",""),
array("ipad case","1","","",""),
array("itouch","1","","",""),
array("ikea","2","","",""),
array("irs","2","","",""),
array("imdb","2","","",""),
array("internet explorer","2","","",""),
array("imeem","2","","",""),
array("ign","2","","",""),
array("is the world going to end in 2012","3","","",""),
array("iq test","3","","",""),
array("is bronchitis contagious","3","","",""),
array("images","3","","",""),
array("is pneumonia contagious","3","","",""),
array("i love the way you lie","4","","",""),
array("impossible shontelle","4","","",""),
array("i like it enrique iglesias","4","","",""),
array("i wanna be a billionaire","4","","",""),
array("i like it","4","","",""),
array("in my head jason derulo","4","","",""),
array("is not afraid eminem","4","","",""),
array("i made it","4","","",""),
array("inception trailer","4","","","")),
"j" => array(
array("justin bieber","1","3","4",""),
array("jokes","2","3","",""),
array("jansport backpack","1","","",""),
array("jillian michaels","1","","",""),
array("juicer","1","","",""),
array("jack johnson","1","","",""),
array("juicy couture","1","","",""),
array("james patterson","1","","",""),
array("janet evanovich","1","","",""),
array("jewelry","1","","",""),
array("just cause 2","1","","",""),
array("jobs","2","","",""),
array("jessica simpson","2","","",""),
array("jennifer love hewitt","2","","",""),
array("jcpenney","2","","",""),
array("jessica alba","2","","",""),
array("jennifer lopez","2","","",""),
array("jennifer aniston","2","","",""),
array("jack hanna","2","","",""),
array("jetblue","2","","",""),
array("jobs in my area","3","","",""),
array("job search","3","","",""),
array("justin bieber cell number","3","","",""),
array("jcpenney.com","3","","",""),
array("joann fabrics","3","","",""),
array("jobs for teens","3","","",""),
array("jc penney","3","","",""),
array("jcp.com","3","","",""),
array("justin bieber baby","4","","",""),
array("justin bieber eenie meenie","4","","",""),
array("justin bieber one time","4","","",""),
array("justin bieber love me","4","","",""),
array("justin bieber never say never","4","","",""),
array("justin bieber somebody to love","4","","",""),
array("jason derulo ridin solo","4","","",""),
array("jay z","4","","",""),
array("justin timberlake","4","","","")),
"k" => array(
array("kindle","1","3","",""),
array("katy perry","1","4","",""),
array("kmart","2","3","",""),
array("kim kardashian","2","3","",""),
array("kindle dx","1","","",""),
array("keurig","1","","",""),
array("kindle 2","1","","",""),
array("kinect","1","","",""),
array("kindle cover","1","","",""),
array("kindle books","1","","",""),
array("k cups","1","","",""),
array("keyboard","1","","",""),
array("kara dioguardi","2","","",""),
array("kate winslet","2","","",""),
array("kelley blue book","2","","",""),
array("kohl's","2","","",""),
array("kate gosselin","2","","",""),
array("kelly clarkson","2","","",""),
array("kristen stewart","2","","",""),
array("kbb","2","","",""),
array("kohls.com","3","","",""),
array("kohls","3","","",""),
array("kmart.com","3","","",""),
array("kids games","3","","",""),
array("kijiji","3","","",""),
array("kayak.com","3","","",""),
array("kayak","3","","",""),
array("katy perry california","4","","",""),
array("kesha your love is my drug","4","","",""),
array("katy perry california girlz","4","","",""),
array("kiss","4","","",""),
array("keisha tik tok","4","","",""),
array("kid cudi","4","","",""),
array("kanye west","4","","",""),
array("kesha blah blah blah","4","","",""),
array("karate kid","4","","","")),
"l" => array(
array("lady gaga","1","2","4",""),
array("lost","1","2","",""),
array("limewire","2","3","",""),
array("lyrics","2","3","",""),
array("love poems","2","3","",""),
array("love quotes","2","3","",""),
array("lil wayne","3","4","",""),
array("laptop","1","","",""),
array("lego","1","","",""),
array("luggage","1","","",""),
array("lego star wars","1","","",""),
array("lego harry potter","1","","",""),
array("laptop computer","1","","",""),
array("lcd tv","1","","",""),
array("laptop bag","1","","",""),
array("leann rimes","2","","",""),
array("lindsay lohan","2","","",""),
array("lowe's","2","","",""),
array("liev schreiber","2","","",""),
array("lowes","3","","",""),
array("lyrics to songs","3","","",""),
array("lowes.com","3","","",""),
array("lingerie","3","","",""),
array("lesbians","3","","",""),
array("lady gaga alejandro","4","","",""),
array("love the way you lie","4","","",""),
array("lady gaga bad romance","4","","",""),
array("loan mods","4","","",""),
array("linkin park","4","","",""),
array("love the way you lie eminem","4","","",""),
array("lil wayne drop the world","4","","",""),
array("lady gaga alejandro official music video","4","","","")),
"m" => array(
array("music","2","3","4",""),
array("maps","2","3","",""),
array("macbook","1","","",""),
array("mp3 player","1","","",""),
array("macbook pro","1","","",""),
array("micro sd","1","","",""),
array("mac mini","1","","",""),
array("mad men","1","","",""),
array("modern warfare 2","1","","",""),
array("mp3","1","","",""),
array("microwave","1","","",""),
array("messenger bag","1","","",""),
array("myspace","2","","",""),
array("mapquest","2","","",""),
array("msn","2","","",""),
array("mail","2","","",""),
array("movies","2","","",""),
array("mapquest driving directions","2","","",""),
array("macy's","2","","",""),
array("melissa rycroft","2","","",""),
array("myspace layouts","3","","",""),
array("math answers","3","","",""),
array("mortgage calculator","3","","",""),
array("music videos","3","","",""),
array("medical dictionary","3","","",""),
array("match.com","3","","",""),
array("myspace backgrounds","3","","",""),
array("map","3","","",""),
array("michael jackson","4","","",""),
array("miley cyrus","4","","",""),
array("my wife having an affair","4","","",""),
array("miley cyrus can't be tamed","4","","",""),
array("mariah carey","4","","",""),
array("my first kiss","4","","",""),
array("metallica","4","","",""),
array("miley cyrus party in the usa","4","","",""),
array("michael jackson billie jean","4","","","")),
"n" => array(
array("nike","1","3","",""),
array("nokia","1","2","",""),
array("netflix","2","3","",""),
array("nissan","2","3","",""),
array("northwest airlines","2","3","",""),
array("netbook","1","","",""),
array("nintendo ds","1","","",""),
array("nikon d90","1","","",""),
array("nook","1","","",""),
array("nikon d5000","1","","",""),
array("nintendo dsi","1","","",""),
array("nintendo wii","1","","",""),
array("nikon","1","","",""),
array("nick jr","2","","",""),
array("nfl","2","","",""),
array("nascar","2","","",""),
array("nordstrom","2","","",""),
array("nba","2","","",""),
array("nbc","2","","",""),
array("name meanings","3","","",""),
array("netflix.com","3","","",""),
array("news","3","","",""),
array("names","3","","",""),
array("nick.com","3","","",""),
array("nada","3","","",""),
array("not afraid eminem","4","","",""),
array("nicki minaj","4","","",""),
array("never say never","4","","",""),
array("not afraid","4","","",""),
array("never say never justin bieber","4","","",""),
array("nothing on you b.o.b","4","","",""),
array("nigahiga","4","","",""),
array("new songs 2010","4","","",""),
array("nickelback","4","","",""),
array("nicki minaj your love","4","","","")),
"o" => array(
array("old navy","2","3","",""),
array("orbitz","2","3","",""),
array("office depot","2","3","",""),
array("online dictionary","2","3","",""),
array("online games","2","3","",""),
array("omg","2","4","",""),
array("oakley","1","","",""),
array("otterbox","1","","",""),
array("oakley sunglasses","1","","",""),
array("office 2010","1","","",""),
array("otterbox iphone 4","1","","",""),
array("olympus pen","1","","",""),
array("one day","1","","",""),
array("ooma","1","","",""),
array("one tree hill","1","","",""),
array("oakley sunglasses for men","1","","",""),
array("oprah","2","","",""),
array("overstock","2","","",""),
array("orkut","2","","",""),
array("olive garden","2","","",""),
array("overstock.com","3","","",""),
array("ovulation calendar","3","","",""),
array("ovulation calculator","3","","",""),
array("online pregnancy test","3","","",""),
array("obama","3","","",""),
array("omg usher","4","","",""),
array("oil rig employment","4","","",""),
array("old spice commercial","4","","",""),
array("one time justin bieber","4","","",""),
array("old spice","4","","",""),
array("over drake","4","","",""),
array("one time","4","","",""),
array("omg usher will i am","4","","",""),
array("omg usher lyrics","4","","","")),
"p" => array(
array("pokemon","1","4","",""),
array("people search","2","3","",""),
array("paypal","2","3","",""),
array("ps3","1","","",""),
array("psp","1","","",""),
array("playstation 3","1","","",""),
array("p90x","1","","",""),
array("ps3 games","1","","",""),
array("pillow pets","1","","",""),
array("portable dvd player","1","","",""),
array("ps3 console","1","","",""),
array("portable air conditioner","1","","",""),
array("photobucket","2","","",""),
array("pizza hut","2","","",""),
array("pogo","2","","",""),
array("priceline","2","","",""),
array("powerball","2","","",""),
array("people magazine","2","","",""),
array("pottery barn","2","","",""),
array("petsmart","2","","",""),
array("pregnancy week by week","3","","",""),
array("prom dresses","3","","",""),
array("people finder","3","","",""),
array("poems","3","","",""),
array("priceline.com","3","","",""),
array("pregnancy symptoms","3","","",""),
array("pregnancy","3","","",""),
array("proxy","3","","",""),
array("paramore","4","","",""),
array("party in the usa","4","","",""),
array("pyramid charice","4","","",""),
array("pitbull","4","","",""),
array("pyramid","4","","",""),
array("pink","4","","",""),
array("pretty boy swag","4","","",""),
array("pretty boy swag soulja boy","4","","",""),
array("poker face","4","","","")),
"q" => array(
array("quickbooks","1","2","3",""),
array("queen","1","4","",""),
array("quotes","2","3","",""),
array("quizzes","2","3","",""),
array("quicken","1","","",""),
array("quickbooks pro 2010","1","","",""),
array("quiksilver","1","","",""),
array("queen mattress","1","","",""),
array("quilt","1","","",""),
array("quicksilver","1","","",""),
array("queer as folk","1","","",""),
array("quicken 2010","1","","",""),
array("qvc","2","","",""),
array("quicktime","2","","",""),
array("quest diagnostics","2","","",""),
array("qwest","2","","",""),
array("query string","2","","",""),
array("quiznos","2","","",""),
array("quizilla","2","","",""),
array("questions and answers","3","","",""),
array("qvc.com","3","","",""),
array("quotes of the day","3","","",""),
array("questions","3","","",""),
array("quotes about life","3","","",""),
array("quotes and sayings","3","","",""),
array("quinceanera dresses","3","","",""),
array("queen bohemian rhapsody","4","","",""),
array("quest crew","4","","",""),
array("queen we will rock you","4","","",""),
array("queen don't stop me now","4","","",""),
array("queens of the stone age","4","","",""),
array("queen i want to break free","4","","",""),
array("queen somebody to love","4","","",""),
array("queen seondeok","4","","",""),
array("queen we are the champions","4","","","")),
"e" => array(
array("eminem","1","2","4",""),
array("eclipse","1","4","",""),
array("eminem recovery","1","4","",""),
array("ebay","2","3","",""),
array("expedia","2","3","",""),
array("enterprise car rental","2","3","",""),
array("external hard drive","1","","",""),
array("eat pray love","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("entourage","1","","",""),
array("eclipse soundtrack","1","","",""),
array("ed hardy","1","","",""),
array("espn","2","","",""),
array("embedded img","2","","",""),
array("ecards","2","","",""),
array("elin nordegren","2","","",""),
array("ebay motors","2","","",""),
array("eva longoria","2","","",""),
array("ebay.com","3","","",""),
array("expedia.com","3","","",""),
array("eharmony","3","","",""),
array("english to spanish translation","3","","",""),
array("engagement rings","3","","",""),
array("eharmony.com","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("eminem not afraid","4","","",""),
array("eenie meenie","4","","",""),
array("eenie meenie justin bieber","4","","",""),
array("eclipse trailer official 2010","4","","",""),
array("enrique iglesias","4","","",""),
array("eminem love the way you lie","4","","",""),
array("eminem beautiful","4","","","")),
"s" => array(
array("southwest airlines","2","3","",""),
array("sears","2","3","",""),
array("song lyrics","2","3","",""),
array("shakira","2","4","",""),
array("starcraft 2","1","","",""),
array("silly bandz","1","","",""),
array("starcraft","1","","",""),
array("sunglasses","1","","",""),
array("shoes","1","","",""),
array("sd card","1","","",""),
array("star wars","1","","",""),
array("scott pilgrim","1","","",""),
array("search amazon.com","1","","",""),
array("speakers","1","","",""),
array("sandra bullock","2","","",""),
array("sprint","2","","",""),
array("staples","2","","",""),
array("sara gilbert","2","","",""),
array("sony","2","","",""),
array("skype","2","","",""),
array("science fair projects","3","","",""),
array("spanish dictionary","3","","",""),
array("sexy","3","","",""),
array("swine flu","3","","",""),
array("search engines","3","","",""),
array("spanish translator","3","","",""),
array("sears.com","3","","",""),
array("shakira waka waka","4","","",""),
array("solo","4","","",""),
array("solo iyaz","4","","",""),
array("somebody to love justin bieber","4","","",""),
array("selena gomez","4","","",""),
array("soulja boy","4","","",""),
array("sexist video of man and woman","4","","",""),
array("shane dawson","4","","",""),
array("stereo love","4","","","")),
"t" => array(
array("twilight","1","3","",""),
array("toy story 3","1","4","",""),
array("toys r us","2","3","",""),
array("travelocity","2","3","",""),
array("toyota","2","3","",""),
array("taylor swift","2","4","",""),
array("true blood","1","","",""),
array("the girl with the dragon tattoo","1","","",""),
array("toy story","1","","",""),
array("tv","1","","",""),
array("the help","1","","",""),
array("transformers","1","","",""),
array("tent","1","","",""),
array("the passage","1","","",""),
array("target","2","","",""),
array("ticketmaster","2","","",""),
array("tom jones","2","","",""),
array("tagged","2","","",""),
array("t-mobile","2","","",""),
array("tom brady","2","","",""),
array("tattoos","3","","",""),
array("tattoo designs","3","","",""),
array("translate english to spanish","3","","",""),
array("tires","3","","",""),
array("teen pregnancy","3","","",""),
array("telephone directory","3","","",""),
array("teach me how to dougie","4","","",""),
array("tattoo patterns","4","","",""),
array("tik tok","4","","",""),
array("trey songz","4","","",""),
array("the annoying orange","4","","",""),
array("telephone lady gaga lyrics","4","","",""),
array("twilight eclipse","4","","",""),
array("tom and jerry","4","","","")),
"u" => array(
array("usher","1","4","",""),
array("u2","1","4","",""),
array("united airlines","2","3","",""),
array("used cars","2","3","",""),
array("us airways","2","3","",""),
array("ufc","2","4","",""),
array("unlocked cell phones","1","","",""),
array("usb flash drive","1","","",""),
array("usb hub","1","","",""),
array("under armour","1","","",""),
array("umbrella","1","","",""),
array("uncharted 2","1","","",""),
array("up","1","","",""),
array("usb cable","1","","",""),
array("ups","2","","",""),
array("usps","2","","",""),
array("us bank","2","","",""),
array("univision","2","","",""),
array("usaa","2","","",""),
array("utusan malaysia","2","","",""),
array("used cars for sale","3","","",""),
array("ugg boots","3","","",""),
array("unique baby names","3","","",""),
array("unemployment benefits","3","","",""),
array("university of phoenix","3","","",""),
array("unemployment","3","","",""),
array("us air","3","","",""),
array("usher omg","4","","",""),
array("usher there goes my baby","4","","",""),
array("unthinkable alicia keys","4","","",""),
array("usher daddy's home","4","","",""),
array("ufo","4","","",""),
array("usher yeah","4","","",""),
array("ufc 116","4","","","")),
"v" => array(
array("vuvuzela","1","4","",""),
array("vera bradley","1","3","",""),
array("victoria's secret","1","2","",""),
array("verizon wireless","2","3","",""),
array("verizon","2","3","",""),
array("vanessa hudgens","2","4","",""),
array("virgin mobile","2","3","",""),
array("vacuum cleaner","1","","",""),
array("video camera","1","","",""),
array("vans","1","","",""),
array("vibratores for women","1","","",""),
array("verizon cell phones","1","","",""),
array("vampire diaries","1","","",""),
array("vacuum","1","","",""),
array("vanilla ice","2","","",""),
array("video","2","","",""),
array("vh1","2","","",""),
array("victoria beckham","2","","",""),
array("vonage","2","","",""),
array("verizon.com","3","","",""),
array("volcanoes","3","","",""),
array("victoria secret","3","","",""),
array("videos","3","","",""),
array("viagra","3","","",""),
array("virtual worlds","3","","",""),
array("vanilla twilight","4","","",""),
array("vybz kartel","4","","",""),
array("vampire weekend","4","","",""),
array("vicente fernandez","4","","",""),
array("vanilla twilight owl city","4","","",""),
array("video phone","4","","",""),
array("videos grasiosos","4","","",""),
array("van halen","4","","","")),
"w" => array(
array("weather","2","3","",""),
array("white pages","2","3","",""),
array("wwe","2","4","",""),
array("wii","1","","",""),
array("wii games","1","","",""),
array("windows 7","1","","",""),
array("wireless router","1","","",""),
array("watches","1","","",""),
array("webcam","1","","",""),
array("wii console","1","","",""),
array("world of warcraft","1","","",""),
array("wii fit","1","","",""),
array("wireless mouse","1","","",""),
array("wal mart","2","","",""),
array("wikipedia","2","","",""),
array("wells fargo","2","","",""),
array("webmd","2","","",""),
array("webkinz","2","","",""),
array("william shatner","2","","",""),
array("walgreens","2","","",""),
array("what does my name mean","3","","",""),
array("what is love","3","","",""),
array("when will the world end","3","","",""),
array("what does my last name mean","3","","",""),
array("what is global warming","3","","",""),
array("what are the symptoms of swine flu","3","","",""),
array("wedding dresses","3","","",""),
array("where can i watch free movies online","3","","",""),
array("waka waka","4","","",""),
array("waka waka shakira","4","","",""),
array("waving flag","4","","",""),
array("waving flag k'naan","4","","",""),
array("world cup 2010 song","4","","",""),
array("world cup 2010","4","","",""),
array("we no speak americano","4","","",""),
array("we are the world","4","","",""),
array("wisin y yandel","4","","","")),
"x" => array(
array("xbox 360","1","2","3","4"),
array("xbox","1","3","",""),
array("xbox 360 slim","1","4","",""),
array("xbox live","1","2","",""),
array("xbox 360 games","1","3","",""),
array("xm radio","2","3","",""),
array("xanax","2","3","",""),
array("x factor","2","4","",""),
array("xbox 360 console","1","","",""),
array("xbox 360 controller","1","","",""),
array("xbox 360 elite","1","","",""),
array("xbox 360 wireless adapter","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("x games 2010","2","","",""),
array("xbox cheats","2","","",""),
array("xbox games","2","","",""),
array("x17","2","","",""),
array("xerox","2","","",""),
array("xbox 360 cheats","3","","",""),
array("xxl video","3","","",""),
array("xbox 360 cheat codes","3","","",""),
array("xbox 360 problems","3","","",""),
array("xxl tv live","3","","",""),
array("x factor 2010","4","","",""),
array("xbox 720","4","","",""),
array("xzibit","4","","",""),
array("x","4","","",""),
array("xxl tv 18","4","","",""),
array("xbox 360 kinect","4","","",""),
array("xscape","4","","","")),
"y" => array(
array("youtube","2","3","4",""),
array("young jeezy","1","4","",""),
array("yahoo","2","3","",""),
array("yahoo mail","2","3","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yugioh cards","1","","",""),
array("yoga dvd","1","","",""),
array("yo gabba gabba","1","","",""),
array("your baby can read","1","","",""),
array("yugioh","1","","",""),
array("yarn","1","","",""),
array("yogurt maker","1","","",""),
array("youtube video","2","","",""),
array("yoko ono","2","","",""),
array("yahoo messenger","2","","",""),
array("yahoo maps","2","","",""),
array("youtube broadcast yourself","2","","",""),
array("you","2","","",""),
array("yahoo games","2","","",""),
array("yellow pages","3","","",""),
array("youtube videos","3","","",""),
array("yellowpages.com","3","","",""),
array("yellow pages.com","3","","",""),
array("youtube music","3","","",""),
array("youtube music videos","3","","",""),
array("yellowbook.com","3","","",""),
array("your love is my drug","4","","",""),
array("your love is my drug kesha","4","","",""),
array("your love nicki minaj","4","","",""),
array("you belong with me","4","","",""),
array("young money","4","","",""),
array("your love","4","","",""),
array("you belong with me taylor swift","4","","",""),
array("your love is my drug lyrics","4","","","")),
"z" => array(
array("zumba","1","4","",""),
array("zhu zhu pets","1","3","",""),
array("zombieland","1","4","",""),
array("zip codes","2","3","",""),
array("zappos","2","3","",""),
array("zales","2","3","",""),
array("zodiac signs","2","3","",""),
array("zuma","2","3","",""),
array("zip code lookup","2","3","",""),
array("zac efron","2","4","",""),
array("zip code finder","2","3","",""),
array("zune","1","","",""),
array("zune hd","1","","",""),
array("zippo","1","","",""),
array("zumba fitness dvd","1","","",""),
array("zelda","1","","",""),
array("zumba dvd","1","","",""),
array("zhu zhu","1","","",""),
array("zsa zsa gabor","2","","",""),
array("zillow","2","","",""),
array("zappos.com","3","","",""),
array("zip code list","3","","",""),
array("zombie","4","","",""),
array("zac brown band","4","","",""),
array("zidane","4","","",""),
array("zidane headbutt","4","","",""),
array("zz top","4","","",""),
array("zombie cranberries","4","","",""),
array("zara nach ke dikha","4","","","")));
?>