<?php $topResults = array(
"a" => array(
array("amazon","0","2","",""),
array("aol","0","2","",""),
array("apple store","0","3","",""),
array("att","0","3","",""),
array("adele","1","4","",""),
array("at&t","2","3","",""),
array("amtrak","0","","",""),
array("american eagle","0","","",""),
array("airtran","0","","",""),
array("addicting games","0","","",""),
array("american horror story","0","","",""),
array("allrecipes","0","","",""),
array("asus transformer prime","1","","",""),
array("amazon prime","1","","",""),
array("apple tv","1","","",""),
array("angry birds","1","","",""),
array("airsoft guns","1","","",""),
array("adidas","1","","",""),
array("android tablet","1","","",""),
array("apple","1","","",""),
array("amazon mom","1","","",""),
array("amber rose","2","","",""),
array("angelina jolie","2","","",""),
array("autotrader","2","","",""),
array("american airlines","2","","",""),
array("ask jeeves","2","","",""),
array("american idol","2","","",""),
array("amber portwood","2","","",""),
array("airline baby ban","3","","",""),
array("a 1099 form to print off","3","","",""),
array("adp payroll login","3","","",""),
array("amazon.com","3","","",""),
array("apartments for rent","3","","",""),
array("answers.com","3","","",""),
array("airline tickets","3","","",""),
array("adele someone like you","4","","",""),
array("all i want for christmas is you mariah carey","4","","",""),
array("adele rolling in the deep","4","","",""),
array("adele set fire to the rain","4","","",""),
array("annoying orange","4","","",""),
array("avicii levels","4","","",""),
array("all i want for christmas is you","4","","",""),
array("avril lavigne","4","","",""),
array("akon","4","","","")),
"b" => array(
array("best buy","0","2","3",""),
array("bank of america","0","2","3",""),
array("bed bath and beyond","0","2","3",""),
array("barnes and noble","0","2","3",""),
array("britney spears","2","4","",""),
array("baltimore sun","0","","",""),
array("bge","0","","",""),
array("baltimore ravens","0","","",""),
array("bjs","0","","",""),
array("black friday 2011","0","","",""),
array("bolt bus","0","","",""),
array("blackberry","1","","",""),
array("beats by dre","1","","",""),
array("battlefield 3","1","","",""),
array("beats","1","","",""),
array("bose","1","","",""),
array("backpack","1","","",""),
array("boots","1","","",""),
array("blu ray player","1","","",""),
array("bluetooth headset","1","","",""),
array("blackberry playbook","1","","",""),
array("blank","2","","",""),
array("bing","2","","",""),
array("blue ivy carter","2","","",""),
array("ben roethlisberger","2","","",""),
array("broken heart syndrome","2","","",""),
array("betty white","3","","",""),
array("bill moyers","3","","",""),
array("blood sugar","3","","",""),
array("baby names","3","","",""),
array("bmi calculator","3","","",""),
array("babies r us","3","","",""),
array("beyonce","4","","",""),
array("bruno mars","4","","",""),
array("bruno mars it will rain","4","","",""),
array("black eyed peas","4","","",""),
array("beyonce countdown","4","","",""),
array("baby justin bieber","4","","",""),
array("beyonce love on top","4","","",""),
array("big sean dance","4","","",""),
array("bruno mars lazy song","4","","","")),
"c" => array(
array("craigslist","0","2","3",""),
array("cnn","0","2","",""),
array("costco","0","2","",""),
array("capital one","0","2","",""),
array("comcast","0","2","",""),
array("casey anthony","2","3","",""),
array("comcast.net","0","","",""),
array("carmax","0","","",""),
array("cool math games","0","","",""),
array("chick fil a","0","","",""),
array("cbs","0","","",""),
array("camera","1","","",""),
array("coffee maker","1","","",""),
array("canon t3i","1","","",""),
array("calendars 2012 wall calendars","1","","",""),
array("crocs","1","","",""),
array("canon","1","","",""),
array("call of duty modern warfare 3","1","","",""),
array("coach","1","","",""),
array("cell phone","1","","",""),
array("canon 60d","1","","",""),
array("chase","2","","",""),
array("countdown to 2012","2","","",""),
array("cheryl tiegs","2","","",""),
array("charlie sheen","2","","",""),
array("carol burnett","3","","",""),
array("chris bosh","3","","",""),
array("cheap airline tickets","3","","",""),
array("craigslist.org","3","","",""),
array("calculator","3","","",""),
array("cheap flights","3","","",""),
array("coupons","3","","",""),
array("charlotte russe","3","","",""),
array("christmas songs","4","","",""),
array("chris brown","4","","",""),
array("coldplay paradise","4","","",""),
array("coldplay","4","","",""),
array("cat daddy","4","","",""),
array("chikni chameli","4","","",""),
array("christmas","4","","",""),
array("christina aguilera","4","","",""),
array("chammak challo","4","","",""),
array("charlie bit my finger","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("disney channel","0","2","",""),
array("driving directions","0","3","",""),
array("delta airlines","2","3","",""),
array("dominos","0","","",""),
array("dsw","0","","",""),
array("dropbox","0","","",""),
array("disney","0","","",""),
array("delta","0","","",""),
array("directions","0","","",""),
array("discover","0","","",""),
array("diablo 3","1","","",""),
array("downton abbey","1","","",""),
array("digital camera","1","","",""),
array("diapers","1","","",""),
array("dvd player","1","","",""),
array("drive","1","","",""),
array("desk","1","","",""),
array("doctor who","1","","",""),
array("dexter","1","","",""),
array("dvd","1","","",""),
array("dolly parton","2","","",""),
array("drew barrymore","2","","",""),
array("dancing with the stars","2","","",""),
array("dayana mendoza","2","","",""),
array("demi lovato","2","","",""),
array("dash diet","2","","",""),
array("dennis quaid","2","","",""),
array("duke basketball","3","","",""),
array("denver nuggets","3","","",""),
array("dancing with the stars season 14","3","","",""),
array("dictionary online","3","","",""),
array("definitions.com","3","","",""),
array("direct tv","3","","",""),
array("dictionary definitions","3","","",""),
array("drake","4","","",""),
array("dubstep","4","","",""),
array("drake headlines","4","","",""),
array("drake take care","4","","",""),
array("dance big sean","4","","",""),
array("david guetta","4","","",""),
array("drake make me proud","4","","",""),
array("danza kuduro","4","","",""),
array("deadmau5","4","","",""),
array("drake marvins room","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("espn","0","2","",""),
array("ebay motors","2","3","",""),
array("edline","0","","",""),
array("etsy","0","","",""),
array("espn3","0","","",""),
array("express","0","","",""),
array("evite","0","","",""),
array("edible arrangements","0","","",""),
array("easybib","0","","",""),
array("external hard drive","1","","",""),
array("earbuds","1","","",""),
array("earphones","1","","",""),
array("electric blanket","1","","",""),
array("ebooks","1","","",""),
array("elliptical","1","","",""),
array("earrings","1","","",""),
array("espresso machine","1","","",""),
array("ethernet cable","1","","",""),
array("electronic cigarette","1","","",""),
array("elin nordegren","2","","",""),
array("emmy rossum","2","","",""),
array("eva longoria","2","","",""),
array("enterprise car rental","2","","",""),
array("elisabeth hasselbeck","2","","",""),
array("evangelina paredes","2","","",""),
array("elizabeth smart","3","","",""),
array("erin brady","3","","",""),
array("elizabeth taylor","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("extreme couponing","3","","",""),
array("earliest pregnancy sign","3","","",""),
array("eminem","4","","",""),
array("etta james","4","","",""),
array("epic rap battles of history","4","","",""),
array("epic meal time","4","","",""),
array("enrique iglesias","4","","",""),
array("eminem space bound","4","","",""),
array("eminem lose yourself","4","","",""),
array("ed sheeran lego house","4","","",""),
array("eminem not afraid","4","","",""),
array("evanescence","4","","","")),
"f" => array(
array("facebook","0","2","3","4"),
array("food network","0","2","",""),
array("fox news","0","2","",""),
array("facebook login","0","3","",""),
array("fedex","0","2","",""),
array("firefox","0","2","",""),
array("free online games","2","3","",""),
array("free music downloads","2","3","",""),
array("fandango","0","","",""),
array("forever 21","0","","",""),
array("food lion","0","","",""),
array("first in math","0","","",""),
array("free kindle books","1","","",""),
array("flash drive","1","","",""),
array("food processor","1","","",""),
array("final fantasy xiii-2","1","","",""),
array("fifa 12","1","","",""),
array("floor lamp","1","","",""),
array("fitbit","1","","",""),
array("flashlight","1","","",""),
array("futon","1","","",""),
array("furniture","1","","",""),
array("friendster","2","","",""),
array("ford","2","","",""),
array("fantasy football","2","","",""),
array("fab melo","3","","",""),
array("free 1099 tax form","3","","",""),
array("free ringtones","3","","",""),
array("free credit report","3","","",""),
array("free games","3","","",""),
array("free resume form to print","3","","",""),
array("funny video","4","","",""),
array("funny","4","","",""),
array("funny pranks","4","","",""),
array("foster the people pumped up kicks","4","","",""),
array("flo rida good feeling","4","","",""),
array("funny cats","4","","",""),
array("feliz navidad","4","","",""),
array("fred","4","","",""),
array("friday rebecca black","4","","","")),
"g" => array(
array("google","0","2","3","4"),
array("gmail","0","2","3",""),
array("google maps","0","2","3",""),
array("games","1","2","3",""),
array("glee","0","4","",""),
array("google search","2","3","",""),
array("google translate","0","","",""),
array("gamestop","0","","",""),
array("google earth","0","","",""),
array("giant","0","","",""),
array("geico","0","","",""),
array("greyhound","0","","",""),
array("gps","1","","",""),
array("gift card","1","","",""),
array("galaxy nexus","1","","",""),
array("game of thrones","1","","",""),
array("galaxy s2","1","","",""),
array("galaxy note","1","","",""),
array("garmin","1","","",""),
array("guitar","1","","",""),
array("galaxy tab","1","","",""),
array("goo","2","","",""),
array("gina carano","2","","",""),
array("gayle king","2","","",""),
array("gsp trooper fired","2","","",""),
array("george stephanopoulos","2","","",""),
array("girl scout cookies","3","","",""),
array("girl scout cookie order form","3","","",""),
array("greenville news","3","","",""),
array("google.com","3","","",""),
array("gnc","3","","",""),
array("good feeling","4","","",""),
array("good feeling florida","4","","",""),
array("give me everything pitbull","4","","",""),
array("gummy bear song","4","","",""),
array("god gave me you","4","","",""),
array("grenade bruno mars","4","","",""),
array("gym class heroes stereo hearts","4","","",""),
array("gisingin ang puso lyrics","4","","","")),
"h" => array(
array("home depot","0","2","3",""),
array("hotmail","0","2","3",""),
array("hulu","0","2","",""),
array("hhgregg","0","","",""),
array("h&m","0","","",""),
array("hollister","0","","",""),
array("herman cain","0","","",""),
array("horoscope","0","","",""),
array("huffington post","0","","",""),
array("how i met your mother","0","","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("hunger games","1","","",""),
array("humidifier","1","","",""),
array("harry potter","1","","",""),
array("hello kitty","1","","",""),
array("hard drive","1","","",""),
array("hp touchpad","1","","",""),
array("hdmi","1","","",""),
array("htc","1","","",""),
array("human barbie","2","","",""),
array("heidi klum","2","","",""),
array("halle berry","2","","",""),
array("how to tie a tie","2","","",""),
array("honey badger","2","","",""),
array("huong hoang","2","","",""),
array("heidi montag","2","","",""),
array("heidi klum and seal divorce","3","","",""),
array("haley joel osment","3","","",""),
array("how_much_does_the_human_brain_weigh","3","","",""),
array("how much should i weigh","3","","",""),
array("how to kiss","3","","",""),
array("how to get pregnant","3","","",""),
array("how many calories should i eat a day","3","","",""),
array("hotmail.com","3","","","")),
"i" => array(
array("itunes","0","2","3",""),
array("ipad","0","1","3",""),
array("imdb","0","2","",""),
array("ikea","0","2","",""),
array("indeed","0","2","",""),
array("iphone 4s","0","1","",""),
array("iphone 5","2","4","",""),
array("icloud","0","","",""),
array("ipad 3","0","","",""),
array("ing direct","0","","",""),
array("ign","0","","",""),
array("ipad 2","1","","",""),
array("ipod touch","1","","",""),
array("iphone 4s case","1","","",""),
array("iphone 4 case","1","","",""),
array("ipod","1","","",""),
array("iphone 4","1","","",""),
array("iphone","1","","",""),
array("ipad 2 case","1","","",""),
array("irs","2","","",""),
array("iphone birthday","2","","",""),
array("internet explorer","2","","",""),
array("isohunt","2","","",""),
array("illinois lottery","2","","",""),
array("irs w2 form 2011","3","","",""),
array("is margaret thatcher still alive","3","","",""),
array("i need a free blank 1099 tax form","3","","",""),
array("is the world going to end in 2012","3","","",""),
array("is selena gomez pregnant","3","","",""),
array("is santa claus real yes or no","3","","",""),
array("instant math answers free","3","","",""),
array("inspirational quotes","3","","",""),
array("it will rain bruno mars","4","","",""),
array("it will rain","4","","",""),
array("im sexay and i know it lmfao video","4","","",""),
array("international love","4","","",""),
array("it girl-jason derulo lyrics","4","","",""),
array("it will rain bruno mars lyrics","4","","",""),
array("if i die young the band perry","4","","",""),
array("i like it like that hot chelle rae","4","","",""),
array("i love you like a love song selena gomez","4","","","")),
"j" => array(
array("justin bieber","0","1","4",""),
array("jcpenney","0","2","",""),
array("jennifer lopez","2","4","",""),
array("jobs","2","3","",""),
array("j crew","0","","",""),
array("johns hopkins","0","","",""),
array("joann fabrics","0","","",""),
array("jerry sandusky","0","","",""),
array("jetblue","0","","",""),
array("java","0","","",""),
array("justin tv","0","","",""),
array("journeys","0","","",""),
array("juicer","1","","",""),
array("just dance 3","1","","",""),
array("jewelry","1","","",""),
array("jillian michaels","1","","",""),
array("jewelry box","1","","",""),
array("juicy couture","1","","",""),
array("justified","1","","",""),
array("just dance 3 wii","1","","",""),
array("just dance","1","","",""),
array("john 3 16","2","","",""),
array("joel osteen","2","","",""),
array("jennifer aniston","2","","",""),
array("jill hennessy","2","","",""),
array("jessica simpson","2","","",""),
array("justin and jessica","2","","",""),
array("joran van der sloot","2","","",""),
array("joepa","3","","",""),
array("joe paterno near death","3","","",""),
array("joe paterno","3","","",""),
array("jcpenney.com","3","","",""),
array("justin bieber phone number for real","3","","",""),
array("justin bieber quiz","3","","",""),
array("jobs in my area","3","","",""),
array("jobs hiring in my area","3","","",""),
array("justin bieber cell number","3","","",""),
array("justin bieber mistletoe","4","","",""),
array("justin bieber baby","4","","",""),
array("jingle bells","4","","",""),
array("jingle bell rock","4","","",""),
array("j cole work out","4","","",""),
array("jennifer lopez on the floor","4","","",""),
array("justin bieber never say never","4","","",""),
array("jar of hearts","4","","","")),
"k" => array(
array("kmart","0","2","3",""),
array("kindle","0","1","3",""),
array("kohls","0","3","",""),
array("kindle fire","0","1","",""),
array("keurig","0","1","",""),
array("kelley blue book","0","2","",""),
array("kelly clarkson","2","4","",""),
array("katy perry","2","4","",""),
array("kayak","0","","",""),
array("kennedy center","0","","",""),
array("khan academy","0","","",""),
array("kris humphries","0","","",""),
array("kindle fire case","1","","",""),
array("kinect","1","","",""),
array("kindle cover","1","","",""),
array("kindle books","1","","",""),
array("k cups","1","","",""),
array("kindle fire accessories","1","","",""),
array("kindle touch","1","","",""),
array("kim kardashian","2","","",""),
array("kristy mcnichol","2","","",""),
array("katie holmes","2","","",""),
array("kate middleton","2","","",""),
array("keri russell","2","","",""),
array("kate gosselin","2","","",""),
array("king jr speech","3","","",""),
array("kara warner","3","","",""),
array("karen talley","3","","",""),
array("kelly blue book","3","","",""),
array("kia","3","","",""),
array("kim kardashian and ray j full video","3","","",""),
array("kohls coupons","3","","",""),
array("kolaveri di","4","","",""),
array("katy perry the one that got away","4","","",""),
array("katy perry last friday night t.g.i.f","4","","",""),
array("kanye west","4","","",""),
array("kesha","4","","",""),
array("kid cudi","4","","",""),
array("kelly clarkson mr know it all","4","","",""),
array("kiss","4","","","")),
"l" => array(
array("lowes","0","3","",""),
array("linkedin","0","2","",""),
array("louis vuitton","0","1","",""),
array("lady gaga","2","4","",""),
array("limewire","2","3","",""),
array("living social","0","","",""),
array("long and foster","0","","",""),
array("lands end","0","","",""),
array("ll bean","0","","",""),
array("lord and taylor","0","","",""),
array("labcorp","0","","",""),
array("letmewatchthis","0","","",""),
array("laptop","1","","",""),
array("lego","1","","",""),
array("leappad","1","","",""),
array("luggage","1","","",""),
array("laptop computer","1","","",""),
array("lego star wars","1","","",""),
array("lord of the rings","1","","",""),
array("led tv","1","","",""),
array("laptop bag","1","","",""),
array("leann rimes","2","","",""),
array("lindsay lohan","2","","",""),
array("lou ferrigno","2","","",""),
array("lowe's home improvement","2","","",""),
array("lyrics","2","","",""),
array("leah messer","2","","",""),
array("lowes stores","2","","",""),
array("larry page","3","","",""),
array("lunar new year","3","","",""),
array("list of potassium rich foods","3","","",""),
array("lyrics to songs","3","","",""),
array("lingerie","3","","",""),
array("love quotes","3","","",""),
array("love poems","3","","",""),
array("love calculator","3","","",""),
array("lil wayne","4","","",""),
array("lmfao","4","","",""),
array("lmfao party rock anthem","4","","",""),
array("look at me now chris brown","4","","",""),
array("lil wayne how to love","4","","",""),
array("last christmas","4","","",""),
array("lady gaga marry the night","4","","",""),
array("linkin park","4","","",""),
array("love you like a love song selena gomez","4","","","")),
"m" => array(
array("mapquest","0","2","3",""),
array("msn","0","2","3",""),
array("maps","0","3","",""),
array("mariah carey","2","4","",""),
array("macy's","0","","",""),
array("mva","0","","",""),
array("maryland judiciary case search","0","","",""),
array("md lottery","0","","",""),
array("michaels","0","","",""),
array("mega millions","0","","",""),
array("m&t bank","0","","",""),
array("macbook pro","1","","",""),
array("mp3 player","1","","",""),
array("macbook air","1","","",""),
array("micro sd card","1","","",""),
array("macbook","1","","",""),
array("monster high","1","","",""),
array("modern warfare 3","1","","",""),
array("moneyball","1","","",""),
array("mass effect 3","1","","",""),
array("mw3","1","","",""),
array("myspace","2","","",""),
array("megan fox","2","","",""),
array("mail","2","","",""),
array("monster hotjobs","2","","",""),
array("miley cyrus","2","","",""),
array("mike tyson","2","","",""),
array("music","2","","",""),
array("mary tyler moore","3","","",""),
array("miranda july","3","","",""),
array("marist","3","","",""),
array("mapquest driving directions","3","","",""),
array("macys.com","3","","",""),
array("math answers","3","","",""),
array("mapquest.com","3","","",""),
array("mistletoe justin bieber","4","","",""),
array("moves like jagger","4","","",""),
array("michael jackson","4","","",""),
array("moves like jagger maroon 5","4","","",""),
array("mac miller","4","","",""),
array("minecraft","4","","",""),
array("marry the night","4","","",""),
array("michael buble","4","","",""),
array("mariah carey all i want for christmas","4","","","")),
"n" => array(
array("netflix","0","2","3",""),
array("nordstrom","0","2","",""),
array("nfl","0","2","",""),
array("nike","1","3","",""),
array("nfl standings","0","","",""),
array("nfl scores","0","","",""),
array("new york times","0","","",""),
array("news","0","","",""),
array("nick","0","","",""),
array("nfl power rankings","0","","",""),
array("nbc","0","","",""),
array("nook","1","","",""),
array("nintendo 3ds","1","","",""),
array("nintendo ds","1","","",""),
array("netbook","1","","",""),
array("nikon d7000","1","","",""),
array("nikon","1","","",""),
array("nook tablet","1","","",""),
array("nikon d5100","1","","",""),
array("nba 2k12","1","","",""),
array("nick cannon","2","","",""),
array("new girl scout cookie","2","","",""),
array("nick jr","2","","",""),
array("nascar","2","","",""),
array("natalee holloway","2","","",""),
array("natalie wood","2","","",""),
array("nba","2","","",""),
array("newt gingrich","3","","",""),
array("new postal rates 2012","3","","",""),
array("normal blood sugar range","3","","",""),
array("nissan","3","","",""),
array("names and meaning","3","","",""),
array("nissan cars","3","","",""),
array("name meanings","3","","",""),
array("national weather service","3","","",""),
array("nicki minaj","4","","",""),
array("nicki minaj super bass","4","","",""),
array("nigahiga","4","","",""),
array("new songs 2011","4","","",""),
array("nickelback","4","","",""),
array("nyan cat","4","","",""),
array("nickelback when we stand together","4","","",""),
array("no sleep wiz khalifa","4","","",""),
array("nicole scherzinger","4","","",""),
array("nicki minaj moment 4 life","4","","","")),
"o" => array(
array("old navy","0","2","3",""),
array("office depot","0","2","3",""),
array("overstock","0","2","",""),
array("orbitz","0","2","",""),
array("one direction","1","4","",""),
array("online dictionary","2","3","",""),
array("occupy wall street","0","","",""),
array("once upon a time","0","","",""),
array("oovoo","0","","",""),
array("omegle","0","","",""),
array("outback","0","","",""),
array("open table","0","","",""),
array("otterbox iphone 4","1","","",""),
array("otterbox iphone 4s","1","","",""),
array("otterbox","1","","",""),
array("oakley","1","","",""),
array("office chair","1","","",""),
array("oxyelite pro","1","","",""),
array("opi nail polish","1","","",""),
array("otterbox ipod touch 4g","1","","",""),
array("oakley sunglasses","1","","",""),
array("omg","2","","",""),
array("oprah winfrey","2","","",""),
array("olivia wilde","2","","",""),
array("orkut","2","","",""),
array("office max","2","","",""),
array("oscar","3","","",""),
array("obtaining a copy of my w2 form","3","","",""),
array("oscar nominations 2012 list","3","","",""),
array("online pregnancy test","3","","",""),
array("ovulation calculator","3","","",""),
array("ovulation calendar","3","","",""),
array("orbitz.com","3","","",""),
array("one direction what makes you beautiful","4","","",""),
array("olly murs dance with me tonight","4","","",""),
array("on the floor jennifer lopez","4","","",""),
array("ombak rindu","4","","",""),
array("ours taylor swift","4","","",""),
array("ombak rindu full movie","4","","",""),
array("one direction gotta be you","4","","",""),
array("on the floor","4","","",""),
array("otis","4","","","")),
"p" => array(
array("pandora","0","2","",""),
array("paypal","0","2","",""),
array("poptropica","0","2","",""),
array("pizza hut","0","2","",""),
array("people search","2","3","",""),
array("papa johns","0","","",""),
array("powerball","0","","",""),
array("party city","0","","",""),
array("pinterest","0","","",""),
array("pnc","0","","",""),
array("people","0","","",""),
array("ps3","1","","",""),
array("playstation 3","1","","",""),
array("psp","1","","",""),
array("p90x","1","","",""),
array("ps vita","1","","",""),
array("ps3 games","1","","",""),
array("ps3 controller","1","","",""),
array("posters","1","","",""),
array("projector","1","","",""),
array("printer","1","","",""),
array("pogo","2","","",""),
array("photobucket","2","","",""),
array("priceline","2","","",""),
array("pro","2","","",""),
array("paul westphal","2","","",""),
array("palmetto","3","","",""),
array("pope joan","3","","",""),
array("pcs pay bill online metro","3","","",""),
array("pregnancy week by week","3","","",""),
array("phone number lookup","3","","",""),
array("people search for free","3","","",""),
array("pregnancy calculator","3","","",""),
array("pottery barn","3","","",""),
array("put my word in a sentence","3","","",""),
array("party rock anthem","4","","",""),
array("pitbull","4","","",""),
array("paradise coldplay","4","","",""),
array("pumped up kicks","4","","",""),
array("pitbull give me everything","4","","",""),
array("party rock anthem lmfao","4","","",""),
array("pumped up kicks foster the people","4","","",""),
array("pitbull rain over me","4","","",""),
array("price tag","4","","",""),
array("pink","4","","","")),
"q" => array(
array("qvc","0","2","3",""),
array("quotes","0","2","3",""),
array("quest diagnostics","0","2","",""),
array("qwop","0","4","",""),
array("quotes about life","0","3","",""),
array("quicktime","0","2","",""),
array("quiznos","0","2","",""),
array("queenstown outlets","0","","",""),
array("qdoba","0","","",""),
array("quizlet","0","","",""),
array("quicken","1","","",""),
array("quickbooks","1","","",""),
array("quicken 2012","1","","",""),
array("quickbooks pro 2012","1","","",""),
array("quiksilver","1","","",""),
array("queen mattress","1","","",""),
array("quinoa","1","","",""),
array("quilt","1","","",""),
array("quicken deluxe 2012","1","","",""),
array("queen bed frame","1","","",""),
array("queen latifah","2","","",""),
array("queen elizabeth ii fields challenge","2","","",""),
array("qwest","2","","",""),
array("quality inn","2","","",""),
array("query string","2","","",""),
array("qb tom brady","3","","",""),
array("quick call","3","","",""),
array("quentin hardy san francisco","3","","",""),
array("qvc home shopping","3","","",""),
array("quotes of the day","3","","",""),
array("quotes and sayings","3","","",""),
array("quick mileage city to city","3","","",""),
array("queen","4","","",""),
array("queen bohemian rhapsody","4","","",""),
array("quest crew","4","","",""),
array("queen don't stop me now","4","","",""),
array("quickie miguel","4","","",""),
array("queen somebody to love","4","","",""),
array("queen we will rock you","4","","",""),
array("queens of the stone age","4","","",""),
array("queen under pressure","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("espn","0","2","",""),
array("ebay motors","2","3","",""),
array("edline","0","","",""),
array("etsy","0","","",""),
array("espn3","0","","",""),
array("express","0","","",""),
array("evite","0","","",""),
array("edible arrangements","0","","",""),
array("easybib","0","","",""),
array("external hard drive","1","","",""),
array("earbuds","1","","",""),
array("earphones","1","","",""),
array("electric blanket","1","","",""),
array("ebooks","1","","",""),
array("elliptical","1","","",""),
array("earrings","1","","",""),
array("espresso machine","1","","",""),
array("ethernet cable","1","","",""),
array("electronic cigarette","1","","",""),
array("elin nordegren","2","","",""),
array("emmy rossum","2","","",""),
array("eva longoria","2","","",""),
array("enterprise car rental","2","","",""),
array("elisabeth hasselbeck","2","","",""),
array("evangelina paredes","2","","",""),
array("elizabeth smart","3","","",""),
array("erin brady","3","","",""),
array("elizabeth taylor","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("extreme couponing","3","","",""),
array("earliest pregnancy sign","3","","",""),
array("eminem","4","","",""),
array("etta james","4","","",""),
array("epic rap battles of history","4","","",""),
array("epic meal time","4","","",""),
array("enrique iglesias","4","","",""),
array("eminem space bound","4","","",""),
array("eminem lose yourself","4","","",""),
array("ed sheeran lego house","4","","",""),
array("eminem not afraid","4","","",""),
array("evanescence","4","","","")),
"s" => array(
array("sears","0","2","3",""),
array("skyrim","0","1","4",""),
array("skype","0","2","",""),
array("sprint","0","2","",""),
array("staples","0","2","",""),
array("southwest airlines","2","3","",""),
array("southwest","0","","",""),
array("sams club","0","","",""),
array("safeway","0","","",""),
array("suntrust","0","","",""),
array("sparknotes","0","","",""),
array("skylanders","1","","",""),
array("samsung galaxy s2","1","","",""),
array("shoes","1","","",""),
array("skylanders figures","1","","",""),
array("star wars","1","","",""),
array("sd card","1","","",""),
array("skullcandy headphones","1","","",""),
array("sunglasses","1","","",""),
array("samsung galaxy tab 10.1","1","","",""),
array("sandra bullock","2","","",""),
array("sarah jones cheerleader","2","","",""),
array("scarlett johansson","2","","",""),
array("sal alosi","2","","",""),
array("sienna miller","2","","",""),
array("supercross","3","","",""),
array("saul alinsky","3","","",""),
array("south carolina primary results","3","","",""),
array("scary maze game","3","","",""),
array("spanish dictionary","3","","",""),
array("spanish to english translation","3","","",""),
array("science fair projects","3","","",""),
array("spell check","3","","",""),
array("super bass nicki minaj","4","","",""),
array("someone like you adele","4","","",""),
array("skrillex","4","","",""),
array("selena gomez","4","","",""),
array("stereo hearts gym class heroes","4","","",""),
array("smosh","4","","",""),
array("selena gomez love you like a love song","4","","",""),
array("shakira","4","","",""),
array("sopa","4","","","")),
"t" => array(
array("target","0","2","3",""),
array("toys r us","0","2","3",""),
array("twitter","0","2","",""),
array("thesaurus","0","2","",""),
array("ticketmaster","0","2","",""),
array("tmz","0","2","",""),
array("taylor swift","2","4","",""),
array("translate","0","","",""),
array("towson university","0","","",""),
array("tumblr","0","","",""),
array("t mobile","0","","",""),
array("tablet","1","","",""),
array("tv","1","","",""),
array("the hunger games","1","","",""),
array("transformer prime","1","","",""),
array("the help","1","","",""),
array("turbotax 2011","1","","",""),
array("toms","1","","",""),
array("treadmill","1","","",""),
array("tv stand","1","","",""),
array("toshiba thrive","1","","",""),
array("tiger woods","2","","",""),
array("travelocity","2","","",""),
array("tagged","2","","",""),
array("the notebook","3","","",""),
array("tuskegee airmen","3","","",""),
array("tina brown","3","","",""),
array("translate english to spanish","3","","",""),
array("travelocity.com","3","","",""),
array("translate spanish to english","3","","",""),
array("target.com","3","","",""),
array("teen pregnancy signs","3","","",""),
array("teach me how to dougie","4","","",""),
array("the one that got away katy perry","4","","",""),
array("the motto drake","4","","",""),
array("tom and jerry","4","","",""),
array("teach me how to dougie official video","4","","",""),
array("the motto","4","","",""),
array("take care drake","4","","",""),
array("tyga","4","","",""),
array("take care drake rihanna","4","","","")),
"u" => array(
array("usaa","0","2","3",""),
array("us airways","0","2","3",""),
array("usps","0","2","",""),
array("ups","0","2","",""),
array("under armour","0","1","",""),
array("ugg boots","1","3","",""),
array("united airlines","2","3","",""),
array("used cars","2","3","",""),
array("urban dictionary","0","","",""),
array("university of maryland","0","","",""),
array("umbc","0","","",""),
array("urban outfitters","0","","",""),
array("usa jobs","0","","",""),
array("uggs","1","","",""),
array("uncharted 3","1","","",""),
array("usb flash drive","1","","",""),
array("unlocked cell phones","1","","",""),
array("usb hub","1","","",""),
array("umbrella","1","","",""),
array("ultrabook","1","","",""),
array("uncharted","1","","",""),
array("upcoming","2","","",""),
array("us bank","2","","",""),
array("univision","2","","",""),
array("university of phoenix","2","","",""),
array("usps rate chart 2012","3","","",""),
array("us east","3","","",""),
array("university park","3","","",""),
array("used cars for sale in my area","3","","",""),
array("ups tracking","3","","",""),
array("usher","4","","",""),
array("usher without you","4","","",""),
array("ultimate dog teaser","4","","",""),
array("uberhaxornova","4","","",""),
array("ufc","4","","",""),
array("u2","4","","",""),
array("usher dj got us falling in love","4","","",""),
array("under the mistletoe justin bieber","4","","",""),
array("ufo","4","","",""),
array("up up and away lil wayne","4","","","")),
"v" => array(
array("verizon wireless","0","2","3",""),
array("virgin mobile","0","2","3",""),
array("van halen","1","2","4",""),
array("victoria secret","0","3","",""),
array("vera bradley","0","1","",""),
array("vh1","0","2","",""),
array("victoria's secret","1","2","",""),
array("verizon","2","3","",""),
array("verizon.net","0","","",""),
array("verizon email","0","","",""),
array("value city","0","","",""),
array("verizon fios","0","","",""),
array("voxer","0","","",""),
array("vacuum cleaner","1","","",""),
array("vitamix","1","","",""),
array("vans","1","","",""),
array("verizon cell phones","1","","",""),
array("vaporizer","1","","",""),
array("vacuum","1","","",""),
array("vibratorsfor women","1","","",""),
array("victoria gotti","2","","",""),
array("vanessa hudgens","2","","",""),
array("van der sloot","2","","",""),
array("victoria beckham","2","","",""),
array("vitamin d study","3","","",""),
array("valentine","3","","",""),
array("valentine day","3","","",""),
array("verizon.com","3","","",""),
array("verizonwireless.com","3","","",""),
array("very early symptoms of pregnancy","3","","",""),
array("victoria's secret fashion show 2011","4","","",""),
array("victorious","4","","",""),
array("vevo","4","","",""),
array("victoria justice","4","","",""),
array("vybz kartel","4","","",""),
array("veena malik","4","","",""),
array("video lucu","4","","",""),
array("vicente fernandez","4","","",""),
array("virgin diaries tlc","4","","","")),
"w" => array(
array("white pages","0","2","3",""),
array("walmart","0","2","",""),
array("weather","0","2","",""),
array("wikipedia","0","2","",""),
array("wells fargo","0","2","",""),
array("www.facebook.com","0","","",""),
array("washington post","0","","",""),
array("wbal","0","","",""),
array("www.yahoo.com","0","","",""),
array("worldstarhiphop","0","","",""),
array("wii","1","","",""),
array("wii games","1","","",""),
array("wireless router","1","","",""),
array("watch","1","","",""),
array("wii console","1","","",""),
array("wallet","1","","",""),
array("windows 7","1","","",""),
array("wireless mouse","1","","",""),
array("wireless headphones","1","","",""),
array("webcam","1","","",""),
array("webmd","2","","",""),
array("wwe","2","","",""),
array("william daley","2","","",""),
array("walgreens","2","","",""),
array("webkinz","2","","",""),
array("when is chinese new years","3","","",""),
array("www heartandstroke ca calendar winners list","3","","",""),
array("w2 form 2011","3","","",""),
array("what does my last name mean","3","","",""),
array("what is the meaning of my name","3","","",""),
array("what does my name mean","3","","",""),
array("what does my dream mean","3","","",""),
array("walmart.com","3","","",""),
array("what is a hobnocker","3","","",""),
array("we found love","4","","",""),
array("why this kolaveri di","4","","",""),
array("wiz khalifa","4","","",""),
array("we found love rihanna calvin harris","4","","",""),
array("without you david guetta","4","","",""),
array("work out j cole","4","","",""),
array("what makes you beautiful one direction","4","","",""),
array("waka waka shakira","4","","",""),
array("without you","4","","",""),
array("wish you were here avril lavigne","4","","","")),
"x" => array(
array("xbox","0","1","3",""),
array("xbox live","0","1","2",""),
array("xm radio","0","2","3",""),
array("xbox 360","1","2","3",""),
array("x factor","0","4","",""),
array("x factor usa","0","4","",""),
array("xbox 720","0","4","",""),
array("xanax","0","2","",""),
array("xbox 360 console","1","3","",""),
array("xfinity","0","","",""),
array("xkcd","0","","",""),
array("xbmc","0","","",""),
array("xbox 360 kinect","1","","",""),
array("xbox 360 controller","1","","",""),
array("xbox 360 games","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("xbox kinect","1","","",""),
array("xbox controller","1","","",""),
array("x-men first class","2","","",""),
array("xvid","2","","",""),
array("x factor winner","2","","",""),
array("xxxv full movie","2","","",""),
array("xha","2","","",""),
array("xnxsxs","2","","",""),
array("xperia","3","","",""),
array("xxl movie","3","","",""),
array("xbox 360 cheats","3","","",""),
array("xxl tv live","3","","",""),
array("xfinity.com","3","","",""),
array("xnx 18 free pon film","3","","",""),
array("x factor 2011","4","","",""),
array("xjawz","4","","",""),
array("xmas songs","4","","",""),
array("x factor usa 2011","4","","",""),
array("x factor 2011 uk","4","","",""),
array("xavier cincinnati fight","4","","",""),
array("xx3","4","","","")),
"y" => array(
array("youtube","0","2","3","4"),
array("yahoo mail","0","2","3",""),
array("yahoo","0","3","",""),
array("yellow pages","0","3","",""),
array("yahoo finance","0","2","",""),
array("yahoo answers","0","2","",""),
array("young jeezy","1","4","",""),
array("yahoo fantasy football","0","","",""),
array("youtube to mp3","0","","",""),
array("y8","0","","",""),
array("yelp","0","","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yarn","1","","",""),
array("yoga dvd","1","","",""),
array("yoga pants","1","","",""),
array("yankee candle","1","","",""),
array("yugioh cards","1","","",""),
array("yo gabba gabba","1","","",""),
array("yugioh","1","","",""),
array("yahoo calendar","2","","",""),
array("yahoo sports","2","","",""),
array("yahoo weather","2","","",""),
array("yahoo bookmarks","2","","",""),
array("yahoo people search","2","","",""),
array("yahoo travel","2","","",""),
array("yahooo","3","","",""),
array("yahooo com","3","","",""),
array("yahoo mail login","3","","",""),
array("youtube videos","3","","",""),
array("youtube.com","3","","",""),
array("yellowpages.com","3","","",""),
array("young wild and free wiz khalifa","4","","",""),
array("you da one rihanna","4","","",""),
array("you da one","4","","",""),
array("you make me feel cobra starship","4","","",""),
array("you and i lady gaga","4","","",""),
array("you and i","4","","",""),
array("yelawolf","4","","",""),
array("yogscast","4","","","")),
"z" => array(
array("zappos","0","2","3",""),
array("zip codes","0","2","3",""),
array("zodiac signs","0","2","3",""),
array("zumba","1","3","4",""),
array("zillow","0","2","",""),
array("zales","0","2","",""),
array("zooey deschanel","0","2","",""),
array("zara","0","4","",""),
array("zombie","1","4","",""),
array("z104.3","0","","",""),
array("zabasearch","0","","",""),
array("zumiez","0","","",""),
array("zippo","1","","",""),
array("zumba wii","1","","",""),
array("zumba fitness dvd","1","","",""),
array("zune","1","","",""),
array("zelda","1","","",""),
array("zumba dvd","1","","",""),
array("zippo lighter","1","","",""),
array("zelda skyward sword","1","","",""),
array("zsa zsa gabor","2","","",""),
array("zombie bees","2","","",""),
array("zuma","2","","",""),
array("zoe saldana","2","","",""),
array("zakim bridge","3","","",""),
array("zabihullah mujahid","3","","",""),
array("zombie samurai","3","","",""),
array("zip code finder","3","","",""),
array("zappos.com","3","","",""),
array("zip code lookup","3","","",""),
array("zac brown band","4","","",""),
array("zakkum anason 2011","4","","",""),
array("zaz je veux","4","","",""),
array("zombie cranberries","4","","",""),
array("zek zek dadum le","4","","",""),
array("zumba dance workout","4","","",""),
array("zelda rap","4","","","")));
?>