<?php $topResults = array(
"a" => array(
array("amazon","0","2","",""),
array("aol","0","2","",""),
array("apple","0","1","",""),
array("american airlines","0","2","",""),
array("adele","1","4","",""),
array("american idol","2","3","",""),
array("att","0","","",""),
array("ask","0","","",""),
array("allegiant air","0","","",""),
array("aria","0","","",""),
array("abc","0","","",""),
array("auto trader","0","","",""),
array("airsoft guns","1","","",""),
array("apple tv","1","","",""),
array("adidas","1","","",""),
array("amazon mom","1","","",""),
array("apple ipad","1","","",""),
array("android tablet","1","","",""),
array("airsoft","1","","",""),
array("atrix","1","","",""),
array("at&t","2","","",""),
array("anna faris","2","","",""),
array("autotrader","2","","",""),
array("addicting games","2","","",""),
array("ashley judd","2","","",""),
array("abigail breslin","2","","",""),
array("alice in chains","3","","",""),
array("aa2","3","","",""),
array("are vampires real","3","","",""),
array("answers.com","3","","",""),
array("ancestry.com","3","","",""),
array("apartments for rent","3","","",""),
array("airline tickets","3","","",""),
array("att.com","3","","",""),
array("am i pregnant quiz","3","","",""),
array("akon","4","","",""),
array("avril lavigne what the hell","4","","",""),
array("annoying orange","4","","",""),
array("avril lavigne","4","","",""),
array("adele rolling in the deep","4","","",""),
array("adele someone like you","4","","",""),
array("all of the lights kanye west","4","","",""),
array("american idol 2011","4","","",""),
array("alicia keys","4","","","")),
"b" => array(
array("best buy","0","2","3",""),
array("bed bath and beyond","0","2","3",""),
array("bank of america","0","2","",""),
array("bing","0","2","",""),
array("black swan","0","1","",""),
array("britney spears","2","4","",""),
array("beyonce","2","4","",""),
array("bellagio","0","","",""),
array("big 5","0","","",""),
array("borders","0","","",""),
array("blockbuster","0","","",""),
array("big lots","0","","",""),
array("blackberry","1","","",""),
array("beats by dre","1","","",""),
array("black ops","1","","",""),
array("bulletstorm","1","","",""),
array("blackberry torch","1","","",""),
array("bluetooth headset","1","","",""),
array("backpack","1","","",""),
array("bose","1","","",""),
array("bambi","1","","",""),
array("blank","2","","",""),
array("bristol palin","2","","",""),
array("barnes and noble","2","","",""),
array("babies r us","2","","",""),
array("boost mobile","3","","",""),
array("bangu","3","","",""),
array("beija-flor","3","","",""),
array("black friday 2010","3","","",""),
array("baby names","3","","",""),
array("black friday ads","3","","",""),
array("black friday sales","3","","",""),
array("black friday","3","","",""),
array("black and yellow wiz khalifa","4","","",""),
array("black and yellow","4","","",""),
array("bruno mars grenade","4","","",""),
array("black eyed peas","4","","",""),
array("britney spears hold it against me","4","","",""),
array("born this way lady gaga","4","","",""),
array("bruno mars","4","","",""),
array("baby justin bieber","4","","","")),
"c" => array(
array("craigslist","0","2","",""),
array("chase","0","2","",""),
array("cnn","0","2","",""),
array("costco","0","2","",""),
array("charlie sheen","2","3","",""),
array("christina aguilera","2","4","",""),
array("craigslist las vegas","0","","",""),
array("csn","0","","",""),
array("ccsd","0","","",""),
array("cox","0","","",""),
array("carmax","0","","",""),
array("cox.net","0","","",""),
array("camera","1","","",""),
array("coffee maker","1","","",""),
array("canon 7d","1","","",""),
array("call of duty black ops","1","","",""),
array("crocs","1","","",""),
array("canon 60d","1","","",""),
array("canon","1","","",""),
array("canon t2i","1","","",""),
array("cell phone","1","","",""),
array("converse","1","","",""),
array("capital one","2","","",""),
array("club penguin","2","","",""),
array("cartoon network","2","","",""),
array("comcast","2","","",""),
array("coupons","3","","",""),
array("carl icahn","3","","",""),
array("cheap airline tickets","3","","",""),
array("calculator","3","","",""),
array("cheap flights","3","","",""),
array("cheat codes","3","","",""),
array("cheap halloween costumes","3","","",""),
array("credit cards","3","","",""),
array("car rentals","3","","",""),
array("chris brown","4","","",""),
array("chris brown yeah 3x","4","","",""),
array("coming home","4","","",""),
array("cat daddy","4","","",""),
array("california gurls katy perry","4","","",""),
array("charlie bit my finger","4","","",""),
array("chris brown look at me now","4","","",""),
array("celine dion","4","","",""),
array("captain america movie trailer 2011","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("dell","0","2","",""),
array("delta airlines","2","3","",""),
array("driving directions","2","3","",""),
array("delta","0","","",""),
array("dillards","0","","",""),
array("dmv nevada","0","","",""),
array("disneyland","0","","",""),
array("dmv","0","","",""),
array("dominos","0","","",""),
array("direct tv","0","","",""),
array("detr","0","","",""),
array("dragon age 2","1","","",""),
array("deal ajax","1","","",""),
array("diapers","1","","",""),
array("digital camera","1","","",""),
array("dead space 2","1","","",""),
array("dragon age","1","","",""),
array("dsi","1","","",""),
array("dvd player","1","","",""),
array("droid x","1","","",""),
array("d7000","1","","",""),
array("disney channel","2","","",""),
array("demi lovato","2","","",""),
array("diane lane","2","","",""),
array("dancing with the stars","2","","",""),
array("dish network","2","","",""),
array("directv","2","","",""),
array("david broder","3","","",""),
array("david cook","3","","",""),
array("dbl arena sby","3","","",""),
array("definitions.com","3","","",""),
array("disneychannel.com","3","","",""),
array("does justin bieber have a girlfriend","3","","",""),
array("download free music","3","","",""),
array("drake","4","","",""),
array("dubstep","4","","",""),
array("dynamite taio cruz","4","","",""),
array("down on me","4","","",""),
array("david guetta","4","","",""),
array("dynamite","4","","",""),
array("dirty bit","4","","",""),
array("dj got us falling in love","4","","",""),
array("do it like a dude","4","","",""),
array("deadmau5","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("eminem","0","1","4",""),
array("espn","0","2","",""),
array("egypt","0","4","",""),
array("etsy","0","","",""),
array("e","0","","",""),
array("express","0","","",""),
array("easter 2011","0","","",""),
array("edmodo","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("electronic cigarette","1","","",""),
array("ethernet cable","1","","",""),
array("elliptical","1","","",""),
array("espresso machine","1","","",""),
array("external hard drive 1tb","1","","",""),
array("ebooks","1","","",""),
array("elizabeth hurley","2","","",""),
array("emma watson","2","","",""),
array("emily blunt","2","","",""),
array("elin nordegren","2","","",""),
array("enterprise car rental","2","","",""),
array("ebay motors","2","","",""),
array("eva longoria","2","","",""),
array("eva braun","3","","",""),
array("erin brockovich","3","","",""),
array("ebt","3","","",""),
array("ebay.com","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("expedia.com","3","","",""),
array("engagement rings","3","","",""),
array("eminem not afraid","4","","",""),
array("enrique iglesias tonight","4","","",""),
array("enrique iglesias","4","","",""),
array("eminem love the way you lie","4","","",""),
array("eminem lose yourself","4","","",""),
array("eminem no love","4","","",""),
array("eminem when im gone","4","","",""),
array("evanescence","4","","","")),
"f" => array(
array("facebook","0","2","3","4"),
array("fandango","0","2","",""),
array("fedex","0","2","",""),
array("ford","0","2","",""),
array("fox news","0","2","",""),
array("food network","0","2","",""),
array("free online games","2","3","",""),
array("free music downloads","2","3","",""),
array("frys","0","","",""),
array("firefox","0","","",""),
array("frostwire","0","","",""),
array("forever 21","0","","",""),
array("flash drive","1","","",""),
array("free kindle books","1","","",""),
array("food processor","1","","",""),
array("flip video","1","","",""),
array("futon","1","","",""),
array("flashlight","1","","",""),
array("fable 3","1","","",""),
array("flip","1","","",""),
array("fight night champion","1","","",""),
array("flowers","1","","",""),
array("fafsa","2","","",""),
array("fantasy football","2","","",""),
array("fab melo","3","","",""),
array("forbes","3","","",""),
array("free ringtones","3","","",""),
array("free games","3","","",""),
array("find a person","3","","",""),
array("free credit report","3","","",""),
array("free people search","3","","",""),
array("firework katy perry","4","","",""),
array("funny video","4","","",""),
array("funny","4","","",""),
array("firework","4","","",""),
array("fred","4","","",""),
array("funny pranks","4","","",""),
array("funny cats","4","","",""),
array("firework katy perry lyrics","4","","",""),
array("family guy","4","","","")),
"g" => array(
array("google maps","0","2","3",""),
array("games","0","2","3",""),
array("glee","0","1","4",""),
array("google","0","2","",""),
array("gmail","0","2","",""),
array("google translate","0","","",""),
array("google earth","0","","",""),
array("gamestop","0","","",""),
array("gap","0","","",""),
array("green valley ranch","0","","",""),
array("gps","1","","",""),
array("galaxy tab","1","","",""),
array("gift card","1","","",""),
array("garmin","1","","",""),
array("guitar","1","","",""),
array("garmin gps","1","","",""),
array("gears of war 3","1","","",""),
array("g shock","1","","",""),
array("guess","1","","",""),
array("google search","2","","",""),
array("gary busey","2","","",""),
array("glenn beck","2","","",""),
array("gabrielle giffords","2","","",""),
array("gas prices","2","","",""),
array("gwyneth paltrow","2","","",""),
array("grocery coupons","3","","",""),
array("garageband","3","","",""),
array("gary mcghee","3","","",""),
array("global warming","3","","",""),
array("games.com","3","","",""),
array("games for kids","3","","",""),
array("girl games","3","","",""),
array("google search engine","3","","",""),
array("grenade bruno mars","4","","",""),
array("green and yellow","4","","",""),
array("grenade","4","","",""),
array("grenade bruno mars lyrics","4","","",""),
array("green and yellow lil wayne","4","","",""),
array("gummy bear song","4","","",""),
array("g6","4","","",""),
array("gucci mane","4","","",""),
array("green day","4","","","")),
"h" => array(
array("hotmail","0","2","",""),
array("hulu","0","2","",""),
array("home depot","0","2","",""),
array("honda","0","2","",""),
array("how to kiss","3","4","",""),
array("hp","0","","",""),
array("h&m","0","","",""),
array("horoscope","0","","",""),
array("hoover dam","0","","",""),
array("hollister","0","","",""),
array("hsn","0","","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("harry potter","1","","",""),
array("homefront","1","","",""),
array("hello kitty","1","","",""),
array("hard drive","1","","",""),
array("humidifier","1","","",""),
array("halo reach","1","","",""),
array("htc","1","","",""),
array("hdmi","1","","",""),
array("heart attack grill","2","","",""),
array("horoscopes","2","","",""),
array("hi5","2","","",""),
array("heidi montag","2","","",""),
array("hugh laurie","2","","",""),
array("harian metro","2","","",""),
array("haare","3","","",""),
array("hana kimi","3","","",""),
array("hans donner","3","","",""),
array("how much should i weigh","3","","",""),
array("how to get pregnant","3","","",""),
array("how long does it take to digest gum","3","","",""),
array("how do you spell a word","3","","",""),
array("halloween costumes","3","","",""),
array("hotmail.com","3","","",""),
array("hold it against me","4","","",""),
array("hold it against me britney spears","4","","",""),
array("higher taio cruz","4","","",""),
array("hey soul sister","4","","",""),
array("hey baby pitbull","4","","",""),
array("hannah montana","4","","",""),
array("hello","4","","",""),
array("hold my hand akon michael jackson","4","","",""),
array("happy tree friends","4","","","")),
"i" => array(
array("itunes","0","2","3",""),
array("ipad","0","1","3",""),
array("irs","0","2","",""),
array("imdb","0","2","",""),
array("ikea","0","2","",""),
array("ipad 2","0","1","",""),
array("indeed","0","2","",""),
array("ipod touch","1","3","",""),
array("ipod","1","2","",""),
array("iphone","1","2","",""),
array("iphone 5","0","","",""),
array("ign","0","","",""),
array("images","0","","",""),
array("iphone 4","1","","",""),
array("iphone 4 case","1","","",""),
array("ipod touch 4th generation","1","","",""),
array("ipod nano","1","","",""),
array("ipad 2nd generation","1","","",""),
array("isla fisher","2","","",""),
array("internet explorer","2","","",""),
array("illinois lottery","2","","",""),
array("illinois death penalty","3","","",""),
array("indosat awards","3","","",""),
array("is the world going to end in 2012","3","","",""),
array("inspirational quotes","3","","",""),
array("is bronchitis contagious","3","","",""),
array("is pneumonia contagious","3","","",""),
array("is it going to rain","3","","",""),
array("i need a doctor","4","","",""),
array("im coming home","4","","",""),
array("i love the way you lie","4","","",""),
array("i just had sex-akon","4","","",""),
array("i whip my hair back and forth","4","","",""),
array("if i die young","4","","",""),
array("i need a doctor eminem","4","","",""),
array("i love you","4","","",""),
array("i am number four trailer","4","","",""),
array("indian songs","4","","","")),
"j" => array(
array("justin bieber","0","1","4",""),
array("japan earthquake","0","3","",""),
array("jcpenney","0","2","",""),
array("jennifer aniston","2","3","",""),
array("jet blue","0","","",""),
array("java","0","","",""),
array("jersey shore","0","","",""),
array("japan tsunami","0","","",""),
array("jobs in las vegas","0","","",""),
array("justin tv","0","","",""),
array("jack in the box","0","","",""),
array("jillian michaels","1","","",""),
array("juicer","1","","",""),
array("jackass 3d","1","","",""),
array("juicy couture","1","","",""),
array("jackass 3","1","","",""),
array("jack3d","1","","",""),
array("just dance 2","1","","",""),
array("just dance","1","","",""),
array("jewelry box","1","","",""),
array("john stamos","2","","",""),
array("jennifer lopez","2","","",""),
array("jason ritter","2","","",""),
array("john travolta","2","","",""),
array("jessica simpson","2","","",""),
array("jennifer love hewitt","2","","",""),
array("johnny depp","2","","",""),
array("jamarcus russell","2","","",""),
array("jared loughner","3","","",""),
array("jobs in my area","3","","",""),
array("jobs","3","","",""),
array("justin bieber cell number","3","","",""),
array("jcpenney.com","3","","",""),
array("job search","3","","",""),
array("joann fabrics","3","","",""),
array("justin bieber phone number for real","3","","",""),
array("justin bieber baby","4","","",""),
array("justin bieber never say never","4","","",""),
array("justin bieber ticket","4","","",""),
array("justin bieber jan","4","","",""),
array("just the way you are","4","","",""),
array("justin bieber somebody to love","4","","",""),
array("just the way you are bruno mars","4","","",""),
array("justin bieber pray","4","","",""),
array("jar of hearts","4","","","")),
"k" => array(
array("kmart","0","2","3",""),
array("kindle","0","1","3",""),
array("katy perry","2","3","4",""),
array("kohls","0","3","",""),
array("kbb","0","","",""),
array("kayak","0","","",""),
array("kfc","0","","",""),
array("klas","0","","",""),
array("kinkos","0","","",""),
array("ktnv","0","","",""),
array("kia","0","","",""),
array("kinect","1","","",""),
array("killzone 3","1","","",""),
array("keurig","1","","",""),
array("k cups","1","","",""),
array("kindle cover","1","","",""),
array("kindle case","1","","",""),
array("keyboard","1","","",""),
array("knife","1","","",""),
array("keurig coffee maker","1","","",""),
array("kim kardashian","2","","",""),
array("kenny rogers","2","","",""),
array("kirstie alley","2","","",""),
array("kelley blue book","2","","",""),
array("kathy hilton","2","","",""),
array("katie holmes","2","","",""),
array("kathy griffin","2","","",""),
array("kate gosselin","2","","",""),
array("kemba walker","3","","",""),
array("khan academy","3","","",""),
array("kohls.com","3","","",""),
array("kelly blue book","3","","",""),
array("kmart.com","3","","",""),
array("kids games","3","","",""),
array("katy perry firework","4","","",""),
array("kesha we r who we r","4","","",""),
array("kanye west","4","","",""),
array("kid cudi","4","","",""),
array("katy perry teenage dream","4","","",""),
array("kesha take it off","4","","",""),
array("keri hilson","4","","",""),
array("kanye west all of the lights","4","","",""),
array("katy perry california girlz","4","","","")),
"l" => array(
array("lady gaga","1","2","4",""),
array("lowes","0","3","",""),
array("limewire","0","2","",""),
array("lyrics","2","3","",""),
array("love quotes","2","3","",""),
array("lil wayne","2","4","",""),
array("las vegas sun","0","","",""),
array("las vegas review journal","0","","",""),
array("las vegas news","0","","",""),
array("las vegas weather","0","","",""),
array("lvac","0","","",""),
array("las vegas dmv","0","","",""),
array("las vegas jobs","0","","",""),
array("luxor","0","","",""),
array("laptop computer","1","","",""),
array("lego","1","","",""),
array("luggage","1","","",""),
array("lupe fiasco","1","","",""),
array("laptop","1","","",""),
array("lego star wars","1","","",""),
array("lord of the rings","1","","",""),
array("laptop bag","1","","",""),
array("louis vuitton","1","","",""),
array("lindsay lohan","2","","",""),
array("lowe's home improvement","2","","",""),
array("la rntj","2","","",""),
array("lebron james","2","","",""),
array("leann rimes","2","","",""),
array("la lakers","3","","",""),
array("los angeles lakers","3","","",""),
array("lent","3","","",""),
array("lyrics to songs","3","","",""),
array("love poems","3","","",""),
array("lowes.com","3","","",""),
array("lingerie","3","","",""),
array("lady gaga born this way","4","","",""),
array("like a g6","4","","",""),
array("love the way you lie","4","","",""),
array("linkin park","4","","",""),
array("love the way you lie part 2","4","","",""),
array("look at me now chris brown","4","","",""),
array("lady gaga bad romance","4","","",""),
array("lil wayne green and yellow","4","","","")),
"m" => array(
array("mapquest","0","2","",""),
array("msn","0","2","",""),
array("maps","0","3","",""),
array("myspace","0","2","",""),
array("miley cyrus","2","4","",""),
array("mariah carey","2","4","",""),
array("music","3","4","",""),
array("macys","0","","",""),
array("minecraft","0","","",""),
array("mandalay bay","0","","",""),
array("michaels","0","","",""),
array("msnbc","0","","",""),
array("mtv","0","","",""),
array("macbook pro","1","","",""),
array("motorola xoom","1","","",""),
array("marvel vs capcom 3","1","","",""),
array("macbook","1","","",""),
array("mp3 player","1","","",""),
array("mouse","1","","",""),
array("macbook air","1","","",""),
array("mortal kombat","1","","",""),
array("micro sd","1","","",""),
array("megamind","1","","",""),
array("megan fox","2","","",""),
array("mclobster rumor","2","","",""),
array("melissa gilbert","2","","",""),
array("martin sheen","2","","",""),
array("mail","2","","",""),
array("mauritius","3","","",""),
array("miami heat","3","","",""),
array("mary stuart masterson","3","","",""),
array("mapquest driving directions","3","","",""),
array("math answers","3","","",""),
array("medical dictionary","3","","",""),
array("meaning of names","3","","",""),
array("myspace layouts","3","","",""),
array("michael jackson","4","","",""),
array("moment 4 life","4","","",""),
array("moment for life nicki minaj","4","","",""),
array("metallica","4","","",""),
array("mumford and sons","4","","",""),
array("more usher","4","","",""),
array("moment for life","4","","","")),
"n" => array(
array("netflix","0","2","3",""),
array("news","0","2","3",""),
array("nfl","0","2","",""),
array("nba","0","2","",""),
array("nike","0","1","",""),
array("nissan","2","3","",""),
array("nevada dmv","0","","",""),
array("nv energy","0","","",""),
array("nevada unemployment","0","","",""),
array("nevada state bank","0","","",""),
array("nevada state college","0","","",""),
array("nintendo ds","1","","",""),
array("nook","1","","",""),
array("nintendo 3ds","1","","",""),
array("nikon d7000","1","","",""),
array("nokia n8","1","","",""),
array("nikon d3100","1","","",""),
array("nook color","1","","",""),
array("nikon d90","1","","",""),
array("nikon","1","","",""),
array("nick jr","2","","",""),
array("nascar","2","","",""),
array("nordstrom","2","","",""),
array("nickelodeon","2","","",""),
array("nbc","2","","",""),
array("ncaa basketball","3","","",""),
array("notorious big","3","","",""),
array("naima","3","","",""),
array("name meanings","3","","",""),
array("netflix.com","3","","",""),
array("names and meaning","3","","",""),
array("northwest airlines","3","","",""),
array("nicki minaj","4","","",""),
array("never say never","4","","",""),
array("no hands","4","","",""),
array("never say never justin bieber","4","","",""),
array("nicki minaj moment 4 life","4","","",""),
array("nigahiga","4","","",""),
array("nelly just a dream","4","","",""),
array("new songs 2011","4","","",""),
array("nicki minaj right through me","4","","",""),
array("nickelback","4","","","")),
"o" => array(
array("old navy","0","2","3",""),
array("office depot","0","2","",""),
array("orbitz","0","2","",""),
array("overstock","0","2","",""),
array("online dictionary","2","3","",""),
array("omg","2","4","",""),
array("online games","2","3","",""),
array("office max","0","","",""),
array("olive garden","0","","",""),
array("oprah","0","","",""),
array("opportunity village","0","","",""),
array("omegle","0","","",""),
array("orleans","0","","",""),
array("otterbox","1","","",""),
array("oakley","1","","",""),
array("otterbox iphone 4","1","","",""),
array("oakley sunglasses","1","","",""),
array("opi","1","","",""),
array("office chair","1","","",""),
array("opi nail polish","1","","",""),
array("office 2010","1","","",""),
array("otterbox iphone 3gs","1","","",""),
array("obi110","1","","",""),
array("olivia wilde","2","","",""),
array("oprah winfrey","2","","",""),
array("orkut","2","","",""),
array("ohio","3","","",""),
array("overstock.com","3","","",""),
array("online pregnancy test","3","","",""),
array("ovulation calendar","3","","",""),
array("ovulation calculator","3","","",""),
array("online calculator","3","","",""),
array("obituaries","3","","",""),
array("omg usher","4","","",""),
array("one time justin bieber","4","","",""),
array("one in a million ne yo","4","","",""),
array("one republic secrets","4","","",""),
array("ok iyaz","4","","",""),
array("owl city","4","","",""),
array("oasis","4","","",""),
array("one republic","4","","",""),
array("one time","4","","","")),
"p" => array(
array("pandora","0","2","",""),
array("pizza hut","0","2","",""),
array("paypal","0","2","",""),
array("photobucket","0","2","",""),
array("priceline","0","2","",""),
array("pokemon","1","4","",""),
array("people search","2","3","",""),
array("pink","2","4","",""),
array("parentlink","0","","",""),
array("palms","0","","",""),
array("pirate bay","0","","",""),
array("papa johns","0","","",""),
array("petco","0","","",""),
array("ps3","1","","",""),
array("psp","1","","",""),
array("playstation 3","1","","",""),
array("p90x","1","","",""),
array("pokemon black","1","","",""),
array("pokemon white","1","","",""),
array("pokemon black and white","1","","",""),
array("ps3 controller","1","","",""),
array("portable dvd player","1","","",""),
array("pogo","2","","",""),
array("phil collins","2","","",""),
array("plentyoffish","2","","",""),
array("prison planet","3","","",""),
array("pi day","3","","",""),
array("printable coupons","3","","",""),
array("pregnancy week by week","3","","",""),
array("priceline.com","3","","",""),
array("phone number lookup","3","","",""),
array("people finder","3","","",""),
array("people search for free","3","","",""),
array("pregnancy symptoms","3","","",""),
array("pink raise your glass","4","","",""),
array("pitbull","4","","",""),
array("price tag","4","","",""),
array("paramore","4","","",""),
array("pray justin bieber","4","","",""),
array("please don't go mike posner","4","","",""),
array("party in the usa","4","","",""),
array("pink perfect lyrics","4","","","")),
"q" => array(
array("qvc","0","2","3",""),
array("quotes","0","2","3",""),
array("quickbooks","1","2","3",""),
array("qwop","0","4","",""),
array("quest diagnostics","0","2","",""),
array("quiznos","0","2","",""),
array("quicktime","0","2","",""),
array("quotes about life","0","3","",""),
array("quicken","0","1","",""),
array("quinoa","0","1","",""),
array("queen","1","4","",""),
array("queens of the stone age","1","4","",""),
array("quest diagnostics las vegas","0","","",""),
array("quickbooks pro 2011","1","","",""),
array("quiksilver","1","","",""),
array("quicken 2011","1","","",""),
array("queen mattress","1","","",""),
array("quicken deluxe 2011","1","","",""),
array("qwest","2","","",""),
array("query string","2","","",""),
array("qatar airways","2","","",""),
array("quentin tarantino","2","","",""),
array("quotes of the day","3","","",""),
array("quizzes","3","","",""),
array("quotes and sayings","3","","",""),
array("qvc home shopping","3","","",""),
array("quote of the day","3","","",""),
array("questions to ask your boyfriend","3","","",""),
array("queen bohemian rhapsody","4","","",""),
array("qro4yzeyl0i","4","","",""),
array("quest crew","4","","",""),
array("queen we will rock you","4","","",""),
array("queen don't stop me now","4","","",""),
array("queen somebody to love","4","","",""),
array("queen under pressure","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("eminem","0","1","4",""),
array("espn","0","2","",""),
array("egypt","0","4","",""),
array("etsy","0","","",""),
array("e","0","","",""),
array("express","0","","",""),
array("easter 2011","0","","",""),
array("edmodo","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("electronic cigarette","1","","",""),
array("ethernet cable","1","","",""),
array("elliptical","1","","",""),
array("espresso machine","1","","",""),
array("external hard drive 1tb","1","","",""),
array("ebooks","1","","",""),
array("elizabeth hurley","2","","",""),
array("emma watson","2","","",""),
array("emily blunt","2","","",""),
array("elin nordegren","2","","",""),
array("enterprise car rental","2","","",""),
array("ebay motors","2","","",""),
array("eva longoria","2","","",""),
array("eva braun","3","","",""),
array("erin brockovich","3","","",""),
array("ebt","3","","",""),
array("ebay.com","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("expedia.com","3","","",""),
array("engagement rings","3","","",""),
array("eminem not afraid","4","","",""),
array("enrique iglesias tonight","4","","",""),
array("enrique iglesias","4","","",""),
array("eminem love the way you lie","4","","",""),
array("eminem lose yourself","4","","",""),
array("eminem no love","4","","",""),
array("eminem when im gone","4","","",""),
array("evanescence","4","","","")),
"s" => array(
array("southwest airlines","0","2","3",""),
array("sprint","0","2","3",""),
array("skype","0","2","",""),
array("sears","0","2","",""),
array("selena gomez","2","4","",""),
array("southwest gas","0","","",""),
array("smiths","0","","",""),
array("sams club","0","","",""),
array("starbucks","0","","",""),
array("station casinos","0","","",""),
array("speed test","0","","",""),
array("sunglasses","1","","",""),
array("samsung galaxy tab","1","","",""),
array("search amazon.com","1","","",""),
array("sd card","1","","",""),
array("star wars","1","","",""),
array("skullcandy headphones","1","","",""),
array("speakers","1","","",""),
array("sewing machine","1","","",""),
array("ssd","1","","",""),
array("scale","1","","",""),
array("scarlett johansson","2","","",""),
array("skippy peanut butter","2","","",""),
array("sandra bullock","2","","",""),
array("search","2","","",""),
array("staples","2","","",""),
array("sprint phones","3","","",""),
array("second amendment","3","","",""),
array("science fair projects","3","","",""),
array("spanish dictionary","3","","",""),
array("song lyrics","3","","",""),
array("scary maze game","3","","",""),
array("sexy","3","","",""),
array("spanish translator","3","","",""),
array("shakira","4","","",""),
array("stereo love","4","","",""),
array("sexist video men and women","4","","",""),
array("soulja boy","4","","",""),
array("shakira waka waka","4","","",""),
array("super bowl commercials 2011","4","","",""),
array("shane dawson","4","","",""),
array("smosh","4","","",""),
array("snoop dogg","4","","","")),
"t" => array(
array("toys r us","0","2","3",""),
array("target","0","2","",""),
array("twitter","0","2","",""),
array("tmz","0","2","",""),
array("tron","0","1","",""),
array("travelocity","0","2","",""),
array("taylor swift","2","4","",""),
array("translator","0","","",""),
array("tmobile","0","","",""),
array("thesaurus","0","","",""),
array("tumblr","0","","",""),
array("tangled","1","","",""),
array("tablet","1","","",""),
array("the walking dead","1","","",""),
array("true grit","1","","",""),
array("true blood","1","","",""),
array("treadmill","1","","",""),
array("tv stand","1","","",""),
array("turbotax 2010","1","","",""),
array("tron legacy","1","","",""),
array("tia mowry","2","","",""),
array("ticketmaster","2","","",""),
array("tiger woods","2","","",""),
array("tagged","2","","",""),
array("tibetan","3","","",""),
array("tirol","3","","",""),
array("tokiohotelagaininbrazil","3","","",""),
array("tattoo designs","3","","",""),
array("translate english to spanish","3","","",""),
array("tattoos","3","","",""),
array("teen pregnancy signs","3","","",""),
array("translate spanish to english","3","","",""),
array("thanksgiving history","3","","",""),
array("teach me how to dougie","4","","",""),
array("tonight enrique iglesias","4","","",""),
array("the time","4","","",""),
array("the time black eyed peas","4","","",""),
array("trey songz","4","","",""),
array("teenage dream katy perry","4","","",""),
array("tom and jerry","4","","",""),
array("transformers 3","4","","",""),
array("taylor swift back to december","4","","","")),
"u" => array(
array("ufc","0","2","4",""),
array("united airlines","0","2","3",""),
array("us airways","0","2","3",""),
array("usps","0","2","",""),
array("ups","0","2","",""),
array("usaa","0","2","",""),
array("us bank","0","2","",""),
array("uggs","1","3","",""),
array("used cars","2","3","",""),
array("unlv","0","","",""),
array("unr","0","","",""),
array("ulta","0","","",""),
array("usb flash drive","1","","",""),
array("unlocked cell phones","1","","",""),
array("umbrella","1","","",""),
array("usb hub","1","","",""),
array("under armour","1","","",""),
array("unbroken","1","","",""),
array("uncharted 2","1","","",""),
array("usb","1","","",""),
array("usb cable","1","","",""),
array("univision","2","","",""),
array("utusan malaysia","2","","",""),
array("uconn-pitt","3","","",""),
array("ugg boots","3","","",""),
array("unique baby names","3","","",""),
array("ugg boots on sale","3","","",""),
array("unemployment benefits","3","","",""),
array("used cars for sale","3","","",""),
array("usher","4","","",""),
array("usher dj got us falling in love","4","","",""),
array("usher more","4","","",""),
array("usher omg","4","","",""),
array("u2","4","","",""),
array("ufo","4","","",""),
array("usher there goes my baby","4","","",""),
array("usher yeah","4","","",""),
array("u smile justin bieber","4","","","")),
"v" => array(
array("verizon wireless","0","2","3",""),
array("victoria secret","0","3","",""),
array("vans","0","1","",""),
array("victoria's secret","1","2","",""),
array("vanessa hudgens","2","4","",""),
array("verizon","2","3","",""),
array("venetian","0","","",""),
array("vons","0","","",""),
array("verizon iphone","0","","",""),
array("vlc","0","","",""),
array("v","0","","",""),
array("vegas.com","0","","",""),
array("virgin america","0","","",""),
array("vod-player-list","1","","",""),
array("vacuum cleaner","1","","",""),
array("vera bradley","1","","",""),
array("video camera","1","","",""),
array("vacuum","1","","",""),
array("vampire diaries","1","","",""),
array("verizon iphone 4 case","1","","",""),
array("vitamix","1","","",""),
array("vh1","2","","",""),
array("virgin mobile","2","","",""),
array("valerie bertinelli","2","","",""),
array("victoria beckham","2","","",""),
array("value city furniture","2","","",""),
array("video","2","","",""),
array("vivian schiller","3","","",""),
array("velez","3","","",""),
array("villareal","3","","",""),
array("verizon.com","3","","",""),
array("verizonwireless.com","3","","",""),
array("volcanoes","3","","",""),
array("very early symptoms of pregnancy","3","","",""),
array("vevo","4","","",""),
array("victorious","4","","",""),
array("vybz kartel","4","","",""),
array("valentine","4","","",""),
array("valentines day","4","","",""),
array("van halen","4","","",""),
array("vampire weekend","4","","",""),
array("vi sao","4","","",""),
array("vicente fernandez","4","","","")),
"w" => array(
array("white pages","0","2","3",""),
array("walmart","0","2","",""),
array("weather","0","2","",""),
array("wells fargo","0","2","",""),
array("wikipedia","0","2","",""),
array("walgreens","0","2","",""),
array("wikileaks","0","","",""),
array("wynn","0","","",""),
array("wiki","0","","",""),
array("weather las vegas","0","","",""),
array("wii","1","","",""),
array("wii games","1","","",""),
array("wireless router","1","","",""),
array("windows 7","1","","",""),
array("water for elephants","1","","",""),
array("watch","1","","",""),
array("webcam","1","","",""),
array("wii console","1","","",""),
array("walking dead","1","","",""),
array("wireless mouse","1","","",""),
array("welcome to facebook","2","","",""),
array("wwe","2","","",""),
array("webmd","2","","",""),
array("webkinz","2","","",""),
array("wagner moura","3","","",""),
array("wtk","3","","",""),
array("wal-mart","3","","",""),
array("what does my name mean","3","","",""),
array("what does my last name mean","3","","",""),
array("what is justin biebers phone number","3","","",""),
array("what is the meaning of my name","3","","",""),
array("what is love","3","","",""),
array("when will the world end","3","","",""),
array("wiz khalifa","4","","",""),
array("what the hell avril lavigne","4","","",""),
array("whats my name rihanna","4","","",""),
array("we r who we r","4","","",""),
array("whip my hair","4","","",""),
array("what the hell","4","","",""),
array("waka waka shakira","4","","",""),
array("waka waka","4","","",""),
array("whip my hair willow smith","4","","",""),
array("who's that chick","4","","","")),
"x" => array(
array("xbox 360","1","2","3","4"),
array("xbox","0","1","3",""),
array("xbox live","0","1","2",""),
array("xm radio","0","2","3",""),
array("xoom","0","1","2",""),
array("xbox 360 console","1","3","",""),
array("xbox 360 kinect","1","4","",""),
array("xbox 360 games","1","3","",""),
array("xs","0","","",""),
array("xbmc","0","","",""),
array("xda","0","","",""),
array("xkcd","0","","",""),
array("xtranormal","0","","",""),
array("xe","0","","",""),
array("xbox 360 controller","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("xbox kinect","1","","",""),
array("xanax","2","","",""),
array("x17","2","","",""),
array("xhamstster","2","","",""),
array("xem phim","2","","",""),
array("x games","2","","",""),
array("xbox cheats","2","","",""),
array("xcode","3","","",""),
array("xbox 360 cheats","3","","",""),
array("xbox 360 elite","3","","",""),
array("xbox 360 cheat codes","3","","",""),
array("xbox 360 problems","3","","",""),
array("x men first class trailer","4","","",""),
array("xjawz","4","","",""),
array("x factor 2010","4","","",""),
array("x men first class","4","","",""),
array("x factor","4","","",""),
array("xxl movie six","4","","",""),
array("xzibit","4","","",""),
array("x","4","","","")),
"y" => array(
array("youtube","0","2","3",""),
array("yellow pages","0","2","3",""),
array("yahoo","0","2","",""),
array("yahoo mail","0","2","",""),
array("yahoo maps","0","2","",""),
array("y8","0","2","",""),
array("yelp","0","","",""),
array("yahoo answers","0","","",""),
array("y","0","","",""),
array("youtube to mp3","0","","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yoga dvd","1","","",""),
array("yo gabba gabba","1","","",""),
array("yarn","1","","",""),
array("yugioh cards","1","","",""),
array("you don't know jack","1","","",""),
array("yugioh","1","","",""),
array("yoga pants","1","","",""),
array("your baby can read","1","","",""),
array("youtube video","2","","",""),
array("youtube broadcast yourself","2","","",""),
array("yahoo music","2","","",""),
array("yahoo messenger","2","","",""),
array("yogi berra","3","","",""),
array("yago","3","","",""),
array("youtube videos","3","","",""),
array("yellowpages.com","3","","",""),
array("youtube music","3","","",""),
array("youtube.com","3","","",""),
array("yellow pages.com","3","","",""),
array("youtube music videos","3","","","")),
"z" => array(
array("zip codes","0","2","3",""),
array("zumba","0","1","4",""),
array("zillow","0","2","",""),
array("zappos","0","2","",""),
array("zune","0","1","",""),
array("zales","0","2","",""),
array("zodiac signs","2","3","",""),
array("zodiac","0","","",""),
array("zumiez","0","","",""),
array("zara","0","","",""),
array("zumanity","0","","",""),
array("zumba wii","1","","",""),
array("zumba fitness dvd","1","","",""),
array("zune hd","1","","",""),
array("zippo","1","","",""),
array("zumba dvd","1","","",""),
array("zelda","1","","",""),
array("zippo lighter","1","","",""),
array("zumba fitness","1","","",""),
array("zsa zsa gabor","2","","",""),
array("zombie ants","2","","",""),
array("zuma","2","","",""),
array("zooey deschanel","2","","",""),
array("zoe saldana","2","","",""),
array("zenit","3","","",""),
array("zhu zhu pets","3","","",""),
array("zip code finder","3","","",""),
array("zhu zhu","3","","",""),
array("zappos.com","3","","",""),
array("zip code list","3","","",""),
array("zhu zhu pet","3","","",""),
array("zip code lookup","3","","",""),
array("zombie","4","","",""),
array("zac brown band","4","","",""),
array("zeitgeist","4","","",""),
array("zzirgrizz","4","","",""),
array("zombie cranberries","4","","",""),
array("zor ka jhatka","4","","",""),
array("zee cine awards 2011","4","","",""),
array("zombie love song","4","","",""),
array("zz top","4","","","")));
?>