<?php $topResults = array(
"a" => array(
array("amazon","0","2","",""),
array("aol","0","2","",""),
array("american idol","0","2","",""),
array("avatar","1","4","",""),
array("american airlines","0","","",""),
array("academy","0","","",""),
array("autotrader","0","","",""),
array("at&t wireless","0","","",""),
array("att","0","","",""),
array("ask.com","0","","",""),
array("atmos energy","0","","",""),
array("apple ipad","1","","",""),
array("avatar blu-ray","1","","",""),
array("alice in wonderland","1","","",""),
array("airsoft guns","1","","",""),
array("alan wake","1","","",""),
array("adidas","1","","",""),
array("avatar dvd","1","","",""),
array("apple","1","","",""),
array("airsoft","1","","",""),
array("ask jeeves","2","","",""),
array("anne hathaway","2","","",""),
array("at&t","2","","",""),
array("annette bening","2","","",""),
array("addicting games","2","","",""),
array("abc","2","","",""),
array("aim","2","","",""),
array("akon","4","","",""),
array("annoying orange","4","","",""),
array("alicia keys","4","","",""),
array("avril lavigne","4","","",""),
array("american idol 2010","4","","",""),
array("alice in wonderland trailer","4","","",""),
array("alicia keys try sleeping with a broken heart","4","","",""),
array("aventura","4","","",""),
array("all the way turned up","4","","","")),
"b" => array(
array("britney spears","1","2","4",""),
array("bank of america","0","2","",""),
array("best buy","0","2","",""),
array("bed bath and beyond","0","2","",""),
array("barnes and noble","0","2","",""),
array("baby names","0","2","",""),
array("bank of america online banking","0","","",""),
array("bing","0","","",""),
array("blockbuster","0","","",""),
array("big lots","0","","",""),
array("burlington coat factory","0","","",""),
array("blackberry","1","","",""),
array("bluetooth headset","1","","",""),
array("blu ray","1","","",""),
array("blackberry bold 9700","1","","",""),
array("blu ray player","1","","",""),
array("bose","1","","",""),
array("battlefield bad company 2","1","","",""),
array("backpack","1","","",""),
array("blackberry unlocked","1","","",""),
array("burt reynolds","2","","",""),
array("bobby brown","2","","",""),
array("bo bice","2","","",""),
array("blank","2","","",""),
array("baby justin bieber","4","","",""),
array("baby","4","","",""),
array("bedrock","4","","",""),
array("beyonce","4","","",""),
array("bad romance","4","","",""),
array("blah blah blah kesha","4","","",""),
array("black eyed peas","4","","",""),
array("baby justin bieber lyrics","4","","",""),
array("bad romance lady gaga","4","","","")),
"c" => array(
array("craigslist","0","2","",""),
array("cnn","0","2","",""),
array("chase","0","2","",""),
array("costco","0","2","",""),
array("capital one","0","2","",""),
array("chase bank","0","","",""),
array("cinemark","0","","",""),
array("carmax","0","","",""),
array("craigslist dallas","0","","",""),
array("compass bank","0","","",""),
array("crocs","1","","",""),
array("camera","1","","",""),
array("canon 7d","1","","",""),
array("canon t2i","1","","",""),
array("coffee maker","1","","",""),
array("canon","1","","",""),
array("charlaine harris","1","","",""),
array("call of duty modern warfare 2","1","","",""),
array("cell phone","1","","",""),
array("canon powershot","1","","",""),
array("cingular","2","","",""),
array("chat","2","","",""),
array("cartoon network","2","","",""),
array("comcast","2","","",""),
array("cynthia nixon","2","","",""),
array("chris brown","4","","",""),
array("charlie bit my finger","4","","",""),
array("cross tattoos","4","","",""),
array("christina aguilera","4","","",""),
array("celine dion","4","","",""),
array("carry out","4","","",""),
array("crazy frog","4","","",""),
array("coldplay","4","","",""),
array("clash of the titans","4","","",""),
array("chris brown crawl","4","","","")),
"d" => array(
array("dictionary","0","2","",""),
array("dallas morning news","0","","",""),
array("dillards","0","","",""),
array("disney channel","0","","",""),
array("dfw airport","0","","",""),
array("dominos","0","","",""),
array("discount tire","0","","",""),
array("dallas cowboys","0","","",""),
array("delta airlines","0","","",""),
array("direct tv","0","","",""),
array("digital camera","1","","",""),
array("daria","1","","",""),
array("dead in the family","1","","",""),
array("dvd","1","","",""),
array("dsi","1","","",""),
array("droid","1","","",""),
array("dsi xl","1","","",""),
array("dvd player","1","","",""),
array("dexter","1","","",""),
array("droid incredible","1","","",""),
array("disney","2","","",""),
array("dell","2","","",""),
array("dunkin donuts","2","","",""),
array("dancing with the stars","2","","",""),
array("directions","2","","",""),
array("delta","2","","",""),
array("dmv","2","","",""),
array("directv","2","","",""),
array("danica patrick","2","","",""),
array("drake","4","","",""),
array("david guetta","4","","",""),
array("down","4","","",""),
array("drake over","4","","",""),
array("do you remember jay sean","4","","",""),
array("drop the world","4","","",""),
array("down jay sean","4","","",""),
array("david guetta memories","4","","",""),
array("demi lovato","4","","",""),
array("drake forever","4","","","")),
"e" => array(
array("eminem","1","2","4",""),
array("ebay","0","2","",""),
array("espn","0","2","",""),
array("expedia","0","2","",""),
array("ebay motors","0","2","",""),
array("eclipse","1","4","",""),
array("easter 2010","0","","",""),
array("english to spanish translation","0","","",""),
array("evite","0","","",""),
array("express","0","","",""),
array("etsy","0","","",""),
array("edible arrangements","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("ed hardy","1","","",""),
array("external hard drive 1tb","1","","",""),
array("exile on main street","1","","",""),
array("entourage","1","","",""),
array("espresso machine","1","","",""),
array("evangeline lilly","2","","",""),
array("erica blasberg","2","","",""),
array("enterprise car rental","2","","",""),
array("elena kagan","2","","",""),
array("ellen barkin","2","","",""),
array("eclipse trailer official 2010","4","","",""),
array("eclipse trailer","4","","",""),
array("empire state of mind","4","","",""),
array("eminem beautiful","4","","",""),
array("enrique iglesias","4","","",""),
array("evanescence","4","","",""),
array("erykah badu","4","","",""),
array("eminem lose yourself","4","","","")),
"f" => array(
array("family guy","1","2","4",""),
array("facebook","0","2","",""),
array("facebook login","0","2","",""),
array("food network","0","2","",""),
array("fox news","0","","",""),
array("firefox","0","","",""),
array("funbrain","0","","",""),
array("fort worth star telegram","0","","",""),
array("fedex","0","","",""),
array("frys","0","","",""),
array("forever 21","0","","",""),
array("final fantasy xiii","1","","",""),
array("flash drive","1","","",""),
array("flip video","1","","",""),
array("flowers","1","","",""),
array("flip","1","","",""),
array("fallout 3","1","","",""),
array("fleshlight","1","","",""),
array("food processor","1","","",""),
array("fan","1","","",""),
array("free online games","2","","",""),
array("fafsa","2","","",""),
array("face","2","","",""),
array("fandango","2","","",""),
array("fidelity","2","","",""),
array("fergie","2","","",""),
array("fireflies","4","","",""),
array("funny video","4","","",""),
array("female hair transplant","4","","",""),
array("fireflies owl city","4","","",""),
array("funny","4","","",""),
array("funny accidents","4","","",""),
array("fred","4","","",""),
array("funny cats","4","","",""),
array("funny pranks","4","","","")),
"g" => array(
array("gmail","0","2","",""),
array("google maps","0","2","",""),
array("google earth","0","2","",""),
array("games","0","2","",""),
array("glee","1","4","",""),
array("god of war 3","1","4","",""),
array("google.com","0","","",""),
array("gamestop","0","","",""),
array("google translate","0","","",""),
array("garland isd","0","","",""),
array("great wolf lodge","0","","",""),
array("geico","0","","",""),
array("gps","1","","",""),
array("garmin","1","","",""),
array("garmin gps","1","","",""),
array("gift card","1","","",""),
array("garmin nuvi","1","","",""),
array("guitar","1","","",""),
array("god of war","1","","",""),
array("guess","1","","",""),
array("google search","2","","",""),
array("gwyneth paltrow","2","","",""),
array("gap","2","","",""),
array("gas prices","2","","",""),
array("grand ole opry","2","","",""),
array("greeting cards","2","","",""),
array("google slap","4","","",""),
array("gummy bear song","4","","",""),
array("gorillaz","4","","",""),
array("gucci mane","4","","",""),
array("green day","4","","",""),
array("guns n roses","4","","",""),
array("glee don't stop believe","4","","",""),
array("google","4","","","")),
"h" => array(
array("hotmail","0","2","",""),
array("home depot","0","2","",""),
array("harry potter","1","2","",""),
array("hulu","0","","",""),
array("hobby lobby","0","","",""),
array("haiti","0","","",""),
array("half price books","0","","",""),
array("house of blues dallas","0","","",""),
array("hotels.com","0","","",""),
array("harbor freight","0","","",""),
array("hollister","0","","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("htc incredible","1","","",""),
array("halo reach","1","","",""),
array("htc hd2","1","","",""),
array("how to train your dragon","1","","",""),
array("hard drive","1","","",""),
array("heavy rain","1","","",""),
array("hello kitty","1","","",""),
array("horoscopes","2","","",""),
array("heidi klum","2","","",""),
array("holiday inn","2","","",""),
array("honda","2","","",""),
array("hummus","2","","",""),
array("hsbc","2","","",""),
array("hgtv","2","","",""),
array("hannah montana","4","","",""),
array("hey soul sister","4","","",""),
array("how low can you go ludacris","4","","",""),
array("happy tree friends","4","","",""),
array("halo","4","","",""),
array("halo beyonce","4","","",""),
array("hey soul sister train","4","","",""),
array("hallelujah","4","","",""),
array("how to kiss","4","","",""),
array("hotel room service","4","","","")),
"i" => array(
array("ipad","0","1","4",""),
array("irs","0","2","",""),
array("imdb","0","2","",""),
array("itunes","0","2","",""),
array("ikea","0","2","",""),
array("ipod","1","2","",""),
array("iphone","1","2","",""),
array("itunes download","0","","",""),
array("indeed","0","","",""),
array("irving isd","0","","",""),
array("ihop","0","","",""),
array("inspirational quotes","0","","",""),
array("ipod touch","1","","",""),
array("ipod nano","1","","",""),
array("ipad case","1","","",""),
array("iphone 3gs","1","","",""),
array("itouch","1","","",""),
array("iphone case","1","","",""),
array("ipod touch 3rd generation","1","","",""),
array("internet explorer","2","","",""),
array("imeem","2","","",""),
array("ign","2","","",""),
array("images","2","","",""),
array("in my head jason derulo","4","","",""),
array("imma be","4","","",""),
array("in my head","4","","",""),
array("imma be black eyed peas","4","","",""),
array("iyaz replay","4","","",""),
array("iron man 2 trailer","4","","",""),
array("i gotta feeling","4","","",""),
array("i made it","4","","",""),
array("i made it kevin rudolf","4","","","")),
