<?php $topResults = array(
"a" => array(
array("american idol","0","2","4",""),
array("amazon","0","2","",""),
array("aol","0","2","",""),
array("att","0","3","",""),
array("avatar","1","4","",""),
array("american airlines","0","","",""),
array("academy","0","","",""),
array("at&t wireless","0","","",""),
array("autotrader","0","","",""),
array("ask.com","0","","",""),
array("ashley furniture","0","","",""),
array("apple ipad","1","","",""),
array("alice in wonderland","1","","",""),
array("airsoft guns","1","","",""),
array("adidas","1","","",""),
array("apple","1","","",""),
array("avatar blu-ray","1","","",""),
array("assassins creed 2","1","","",""),
array("airsoft","1","","",""),
array("audio books","1","","",""),
array("ask jeeves","2","","",""),
array("ads bluelithium","2","","",""),
array("at&t","2","","",""),
array("addams family musical","2","","",""),
array("addicting games","2","","",""),
array("abc","2","","",""),
array("aim","2","","",""),
array("at t","3","","",""),
array("answers.com","3","","",""),
array("airline tickets","3","","",""),
array("att.com","3","","",""),
array("apartments for rent","3","","",""),
array("area codes","3","","",""),
array("are vampires real","3","","",""),
array("am i pregnant","3","","",""),
array("aaa","3","","",""),
array("akon","4","","",""),
array("alicia keys","4","","",""),
array("annoying orange","4","","",""),
array("avril lavigne","4","","",""),
array("alice in wonderland trailer","4","","",""),
array("american idol 2010","4","","",""),
array("alicia keys try sleeping with a broken heart","4","","",""),
array("aventura","4","","","")),
"b" => array(
array("bank of america","0","2","3",""),
array("best buy","0","2","3",""),
array("bed bath and beyond","0","2","3",""),
array("britney spears","1","2","4",""),
array("barnes and noble","0","2","",""),
array("blockbuster","0","2","",""),
array("baby names","2","3","",""),
array("babies r us","2","3","",""),
array("bank of america online banking","0","","",""),
array("brittany murphy","0","","",""),
array("bing","0","","",""),
array("burlington coat factory","0","","",""),
array("big lots","0","","",""),
array("blackberry","1","","",""),
array("battlefield bad company 2","1","","",""),
array("bluetooth headset","1","","",""),
array("blu ray","1","","",""),
array("blackberry bold 9700","1","","",""),
array("blu ray player","1","","",""),
array("bose","1","","",""),
array("blackberry unlocked","1","","",""),
array("backpack","1","","",""),
array("blank","2","","",""),
array("ben roethlisberger","2","","",""),
array("baby shower games","3","","",""),
array("baby boy names","3","","",""),
array("bmi","3","","",""),
array("black friday 2009","3","","",""),
array("barack obama","3","","",""),
array("baby justin bieber","4","","",""),
array("bad romance","4","","",""),
array("bedrock","4","","",""),
array("beyonce","4","","",""),
array("blah blah blah kesha","4","","",""),
array("bad romance lady gaga","4","","",""),
array("black eyed peas","4","","",""),
array("baby","4","","",""),
array("bedrock lil wayne","4","","","")),
"c" => array(
array("craigslist","0","2","",""),
array("cnn","0","2","",""),
array("chase","0","2","",""),
array("costco","0","2","",""),
array("call of duty modern warfare 2","1","4","",""),
array("chase bank","0","","",""),
array("cinemark","0","","",""),
array("carmax","0","","",""),
array("craigslist dallas","0","","",""),
array("capital one","0","","",""),
array("club penguin","0","","",""),
array("canon 7d","1","","",""),
array("crocs","1","","",""),
array("camera","1","","",""),
array("coffee maker","1","","",""),
array("canon t2i","1","","",""),
array("canon","1","","",""),
array("converse","1","","",""),
array("canon powershot","1","","",""),
array("coach","1","","",""),
array("crystal bowersox","2","","",""),
array("cingular","2","","",""),
array("camilla parker bowles","2","","",""),
array("chat","2","","",""),
array("cartoon network","2","","",""),
array("caylee anthony","2","","",""),
array("cheap airline tickets","3","","",""),
array("cheap flights","3","","",""),
array("coupons","3","","",""),
array("car rentals","3","","",""),
array("cars","3","","",""),
array("cheat codes","3","","",""),
array("calculator","3","","",""),
array("calorie counter","3","","",""),
array("cheap hotels","3","","",""),
array("clip art","3","","",""),
array("chris brown","4","","",""),
array("charlie bit my finger","4","","",""),
array("celine dion","4","","",""),
array("coldplay","4","","",""),
array("christina aguilera","4","","",""),
array("chris brown crawl","4","","",""),
array("crazy frog","4","","",""),
array("charlie the unicorn","4","","",""),
array("carry out","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("dallas morning news","0","2","",""),
array("dallas cowboys","0","2","",""),
array("direct tv","0","3","",""),
array("dell","2","3","",""),
array("dillards","0","","",""),
array("disney channel","0","","",""),
array("dfw airport","0","","",""),
array("dominos","0","","",""),
array("discount tire","0","","",""),
array("dallas weather","0","","",""),
array("digital camera","1","","",""),
array("dsi","1","","",""),
array("dsi xl","1","","",""),
array("droid","1","","",""),
array("dvd","1","","",""),
array("dexter","1","","",""),
array("dvd player","1","","",""),
array("ds","1","","",""),
array("dexter season 4","1","","",""),
array("diary of a wimpy kid","1","","",""),
array("dancing with the stars","2","","",""),
array("deals deals express","2","","",""),
array("drudge report","2","","",""),
array("dr conrad murray","2","","",""),
array("dixie carter","2","","",""),
array("dailymotion","2","","",""),
array("delta airlines","3","","",""),
array("dogs","3","","",""),
array("disneychannel.com","3","","",""),
array("driving directions","3","","",""),
array("delta.com","3","","",""),
array("dictionary.com","3","","",""),
array("dog breeds","3","","",""),
array("drake","4","","",""),
array("down","4","","",""),
array("david guetta","4","","",""),
array("do you remember jay sean","4","","",""),
array("down jay sean","4","","",""),
array("drake forever","4","","",""),
array("drop the world","4","","",""),
array("demi lovato","4","","",""),
array("don't stop believing","4","","",""),
array("drop it low","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("ebay motors","0","2","3",""),
array("espn","0","2","",""),
array("english to spanish translation","0","3","",""),
array("ed hardy","1","3","",""),
array("eminem","2","4","",""),
array("eharmony","2","3","",""),
array("easter 2010","0","","",""),
array("express","0","","",""),
array("evite","0","","",""),
array("etsy","0","","",""),
array("edible arrangements","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("erykah badu","1","","",""),
array("earbuds","1","","",""),
array("external hard drive 1tb","1","","",""),
array("eclipse","1","","",""),
array("easter","1","","",""),
array("ethernet cable","1","","",""),
array("entourage","1","","",""),
array("elizabeth taylor","2","","",""),
array("erin andrews","2","","",""),
array("elin nordegren","2","","",""),
array("enterprise car rental","2","","",""),
array("ebay.com","3","","",""),
array("expedia.com","3","","",""),
array("eharmony.com","3","","",""),
array("engagement rings","3","","",""),
array("empire state of mind","4","","",""),
array("eclipse trailer official 2010","4","","",""),
array("eclipse trailer","4","","",""),
array("eminem beautiful","4","","",""),
array("enrique iglesias","4","","",""),
array("evanescence","4","","",""),
array("eminem lose yourself","4","","",""),
array("eye of the tiger","4","","",""),
array("elvis presley","4","","","")),
"f" => array(
array("facebook","0","2","",""),
array("facebook login","0","2","",""),
array("fox news","0","2","",""),
array("food network","0","2","",""),
array("free online games","2","3","",""),
array("family guy","2","4","",""),
array("firefox","0","","",""),
array("funbrain","0","","",""),
array("frys","0","","",""),
array("fort worth star telegram","0","","",""),
array("fedex","0","","",""),
array("forever 21","0","","",""),
array("final fantasy xiii","1","","",""),
array("flash drive","1","","",""),
array("final fantasy","1","","",""),
array("flip video","1","","",""),
array("fallout 3","1","","",""),
array("final fantasy 13","1","","",""),
array("fleshlight","1","","",""),
array("flip","1","","",""),
array("food processor","1","","",""),
array("food inc","1","","",""),
array("fafsa","2","","",""),
array("face","2","","",""),
array("fandango","2","","",""),
array("farrah fawcett","2","","",""),
array("free ringtones","3","","",""),
array("free music downloads","3","","",""),
array("free games","3","","",""),
array("free ecards","3","","",""),
array("find people","3","","",""),
array("free music","3","","",""),
array("free people search","3","","",""),
array("find a person","3","","",""),
array("free credit report","3","","",""),
array("fireflies","4","","",""),
array("funny video","4","","",""),
array("fireflies owl city","4","","",""),
array("funny","4","","",""),
array("funny accidents","4","","",""),
array("fred","4","","",""),
array("funny cats","4","","",""),
array("forever","4","","",""),
array("forever drake lil wayne","4","","","")),
"g" => array(
array("games","0","2","3",""),
array("glee","1","2","4",""),
array("gmail","0","2","",""),
array("google maps","0","2","",""),
array("google earth","0","2","",""),
array("gorillaz","1","4","",""),
array("google search","2","3","",""),
array("google.com","0","","",""),
array("gamestop","0","","",""),
array("gaylord texan","0","","",""),
array("grapevine mills mall","0","","",""),
array("google translate","0","","",""),
array("great wolf lodge","0","","",""),
array("god of war 3","1","","",""),
array("gps","1","","",""),
array("garmin","1","","",""),
array("god of war","1","","",""),
array("garmin gps","1","","",""),
array("guitar","1","","",""),
array("garmin nuvi","1","","",""),
array("gift card","1","","",""),
array("google","2","","",""),
array("gap","2","","",""),
array("geico","2","","",""),
array("gas prices","2","","",""),
array("global warming","3","","",""),
array("games.com","3","","",""),
array("gnc","3","","",""),
array("genital warts","3","","",""),
array("game cheats","3","","",""),
array("google search engine","3","","",""),
array("girl games","3","","",""),
array("gout","3","","",""),
array("google slap","4","","",""),
array("gummy bear song","4","","",""),
array("giant squid in california","4","","",""),
array("green day","4","","",""),
array("gucci mane","4","","",""),
array("glee don't stop believe","4","","",""),
array("guns n roses","4","","",""),
array("ghost","4","","","")),
"h" => array(
array("hotmail","0","2","3",""),
array("home depot","0","2","3",""),
array("hulu","0","2","",""),
array("harry potter","1","2","",""),
array("hobby lobby","0","","",""),
array("half price books","0","","",""),
array("haiti","0","","",""),
array("house of blues dallas","0","","",""),
array("hotels.com","0","","",""),
array("hollister","0","","",""),
array("harbor freight","0","","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("heavy rain","1","","",""),
array("htc hd2","1","","",""),
array("how to train your dragon","1","","",""),
array("hard drive","1","","",""),
array("hello kitty","1","","",""),
array("heart rate monitor","1","","",""),
array("hdmi","1","","",""),
array("hallmark","2","","",""),
array("harley davidson","2","","",""),
array("hampton inn","2","","",""),
array("heath ledger","2","","",""),
array("hbo","2","","",""),
array("hayden panettiere","2","","",""),
array("how much should i weigh","3","","",""),
array("how to kiss","3","","",""),
array("how to get pregnant","3","","",""),
array("halloween costumes","3","","",""),
array("hotmail.com","3","","",""),
array("how do you spell a word","3","","",""),
array("how to make a website","3","","",""),
array("how to write a resume","3","","",""),
array("hannah montana","4","","",""),
array("how low can you go ludacris","4","","",""),
array("happy tree friends","4","","",""),
array("hey soul sister","4","","",""),
array("halo","4","","",""),
array("hard rihanna","4","","",""),
array("halo beyonce","4","","",""),
array("how to jerk","4","","",""),
array("hallelujah","4","","",""),
array("hotel room service","4","","","")),
"i" => array(
array("itunes","0","2","3",""),
array("iphone","0","1","3",""),
array("ipod","1","2","3",""),
array("imdb","0","2","",""),
array("irs","0","2","",""),
array("ipad","0","1","",""),
array("ikea","0","2","",""),
array("inspirational quotes","0","3","",""),
array("ipod touch","1","3","",""),
array("images","2","3","",""),
array("itunes download","0","","",""),
array("indeed","0","","",""),
array("ihop","0","","",""),
array("ipod nano","1","","",""),
array("iphone 3gs","1","","",""),
array("itouch","1","","",""),
array("iphone case","1","","",""),
array("ipad case","1","","",""),
array("ipod shuffle","1","","",""),
array("internet explorer","2","","",""),
array("iphone os 4","2","","",""),
array("imeem","2","","",""),
array("ign","2","","",""),
array("is the world going to end in 2012","3","","",""),
array("iq test","3","","",""),
array("is bronchitis contagious","3","","",""),
array("is pneumonia contagious","3","","",""),
array("in my head jason derulo","4","","",""),
array("imma be","4","","",""),
array("in my head","4","","",""),
array("iyaz replay","4","","",""),
array("i gotta feeling","4","","",""),
array("imma be black eyed peas","4","","",""),
array("iron man 2 trailer","4","","",""),
array("i can transform ya chris brown","4","","",""),
array("if we ever meet again","4","","",""),
array("im on a boat","4","","","")),
"j" => array(
array("justin bieber","0","1","4",""),
array("jcpenney","0","2","",""),
array("jokes","2","3","",""),
array("james avery","0","","",""),
array("jason's deli","0","","",""),
array("jersey shore","0","","",""),
array("jimmy johns","0","","",""),
array("jack in the box","0","","",""),
array("justin tv","0","","",""),
array("justice for girls","0","","",""),
array("jet blue","0","","",""),
array("just cause 2","1","","",""),
array("jillian michaels","1","","",""),
array("juicer","1","","",""),
array("jewelry","1","","",""),
array("juicy couture","1","","",""),
array("jamie oliver","1","","",""),
array("jack johnson","1","","",""),
array("jimi hendrix","1","","",""),
array("jim butcher","1","","",""),
array("jennifer love hewitt","2","","",""),
array("jobs","2","","",""),
array("jessica simpson","2","","",""),
array("jessica alba","2","","",""),
array("jennifer hudson","2","","",""),
array("jennifer aniston","2","","",""),
array("janet jackson","2","","",""),
array("jetblue","2","","",""),
array("jobs in my area","3","","",""),
array("job search","3","","",""),
array("jcpenney.com","3","","",""),
array("joann fabrics","3","","",""),
array("jc penney","3","","",""),
array("jobs for teens","3","","",""),
array("jordans","3","","",""),
array("jcp.com","3","","",""),
array("jobs.com","3","","",""),
array("justin bieber baby","4","","",""),
array("justin bieber one time","4","","",""),
array("jason derulo in my head","4","","",""),
array("jay z","4","","",""),
array("justin bieber love me","4","","",""),
array("jason derulo","4","","",""),
array("justin timberlake","4","","",""),
array("justin bieber one less lonelygirl","4","","",""),
array("jay sean","4","","","")),
"k" => array(
array("kmart","0","2","3",""),
array("kohls","0","3","",""),
array("kim kardashian","0","3","",""),
array("kayak","0","3","",""),
array("kindle","1","3","",""),
array("kelly clarkson","2","4","",""),
array("kelly blue book","0","","",""),
array("kroger","0","","",""),
array("keller isd","0","","",""),
array("keller williams","0","","",""),
array("kirklands","0","","",""),
array("kroger store locator","0","","",""),
array("keurig","1","","",""),
array("kindle books","1","","",""),
array("k cups","1","","",""),
array("kindle 2","1","","",""),
array("keyboard","1","","",""),
array("kindle dx","1","","",""),
array("kindle cover","1","","",""),
array("keurig coffee maker","1","","",""),
array("kitchenaid mixer","1","","",""),
array("kate middleton","2","","",""),
array("kraken","2","","",""),
array("kal penn","2","","",""),
array("kobe bryant","2","","",""),
array("kohl's","2","","",""),
array("keira knightley","2","","",""),
array("kristen stewart","2","","",""),
array("kbb","2","","",""),
array("kohls.com","3","","",""),
array("kmart.com","3","","",""),
array("kids games","3","","",""),
array("kijiji","3","","",""),
array("kayak.com","3","","",""),
array("keisha tik tok","4","","",""),
array("kesha blah blah blah","4","","",""),
array("katy perry","4","","",""),
array("kiss","4","","",""),
array("kanye west","4","","",""),
array("kid cudi","4","","",""),
array("kiss me thru the phone","4","","",""),
array("kings of leon","4","","",""),
array("keri hilson","4","","","")),
"l" => array(
array("lady gaga","0","1","2","4"),
array("lyrics","0","2","3",""),
array("limewire","0","2","3",""),
array("love quotes","0","2","3",""),
array("lost","0","1","2",""),
array("lowes","0","3","",""),
array("love poems","2","3","",""),
array("lil wayne","3","4","",""),
array("la fitness","0","","",""),
array("louis vuitton","0","","",""),
array("linkedin","0","","",""),
array("lifetime fitness","0","","",""),
array("laptop","1","","",""),
array("lego","1","","",""),
array("lord of the rings","1","","",""),
array("luggage","1","","",""),
array("lord of the rings blu ray","1","","",""),
array("lego star wars","1","","",""),
array("laptop computer","1","","",""),
array("lcd tv","1","","",""),
array("lindsay lohan","2","","",""),
array("lowe's","2","","",""),
array("letters to god","2","","",""),
array("las vegas","2","","",""),
array("lyrics to songs","3","","",""),
array("lingerie","3","","",""),
array("lowes.com","3","","",""),
array("love","3","","",""),
array("lady gaga bad romance","4","","",""),
array("lady gaga telephone","4","","",""),
array("lady gaga paparazzi","4","","",""),
array("lady gaga poker face","4","","",""),
array("linkin park","4","","",""),
array("lil wayne no ceiling","4","","",""),
array("luge crash","4","","",""),
array("love story","4","","","")),
"m" => array(
array("music","1","2","3","4"),
array("maps","0","2","3",""),
array("myspace","0","2","",""),
array("msn","0","2","",""),
array("mapquest driving directions","0","2","",""),
array("mortgage calculator","0","3","",""),
array("modern warfare 2","1","4","",""),
array("mapquest","0","","",""),
array("macys","0","","",""),
array("metro pcs","0","","",""),
array("monster.com","0","","",""),
array("michaels","0","","",""),
array("macbook","1","","",""),
array("mp3 player","1","","",""),
array("macbook pro","1","","",""),
array("mass effect 2","1","","",""),
array("micro sd","1","","",""),
array("mp3","1","","",""),
array("mgmt","1","","",""),
array("motorola droid","1","","",""),
array("movies","2","","",""),
array("macy's","2","","",""),
array("maura tierney","2","","",""),
array("mel gibson","2","","",""),
array("mtv","2","","",""),
array("myspace layouts","3","","",""),
array("music videos","3","","",""),
array("math answers","3","","",""),
array("match.com","3","","",""),
array("myspace backgrounds","3","","",""),
array("map","3","","",""),
array("medical dictionary","3","","",""),
array("michael jackson","4","","",""),
array("miley cyrus","4","","",""),
array("mariah carey","4","","",""),
array("miley cyrus party in the usa","4","","",""),
array("metallica","4","","",""),
array("michael jackson billie jean","4","","",""),
array("meet me halfway","4","","",""),
array("madonna","4","","","")),
"n" => array(
array("netflix","0","2","3",""),
array("nexus one","0","1","",""),
array("nike","1","3","",""),
array("nicki minaj","2","4","",""),
array("nascar","2","3","",""),
array("naruto","2","4","",""),
array("nada","2","3","",""),
array("nordstrom","0","","",""),
array("nfl","0","","",""),
array("nick jr","0","","",""),
array("ntta","0","","",""),
array("new york times","0","","",""),
array("neiman marcus","0","","",""),
array("northpark mall","0","","",""),
array("nbc","0","","",""),
array("new moon","1","","",""),
array("nintendo ds","1","","",""),
array("netbook","1","","",""),
array("nikon d90","1","","",""),
array("nintendo dsi","1","","",""),
array("nikon d5000","1","","",""),
array("nintendo wii","1","","",""),
array("new moon dvd","1","","",""),
array("nfl trade rumors","2","","",""),
array("nicollette sheridan","2","","",""),
array("nancy kerrigan","2","","",""),
array("national weather service","2","","",""),
array("nasa","2","","",""),
array("name meanings","3","","",""),
array("nissan","3","","",""),
array("netflix.com","3","","",""),
array("news","3","","",""),
array("northwest airlines","3","","",""),
array("names","3","","",""),
array("nigahiga","4","","",""),
array("naturally selena gomez","4","","",""),
array("nickelback","4","","",""),
array("new songs 2010","4","","",""),
array("nothing on you b.o.b","4","","",""),
array("need you now lady antebellum","4","","",""),
array("nobody","4","","",""),
array("naruto shippuden","4","","","")),
"o" => array(
array("office depot","0","2","3",""),
array("orbitz","0","2","3",""),
array("online games","0","2","3",""),
array("olive garden","0","2","",""),
array("overstock","0","2","",""),
array("old navy","0","3","",""),
array("office max","0","3","",""),
array("oprah","1","2","",""),
array("owl city","1","4","",""),
array("online dictionary","2","3","",""),
array("obama","2","3","",""),
array("olympics","0","","",""),
array("olympics 2010","0","","",""),
array("oreilly auto parts","0","","",""),
array("oakley","1","","",""),
array("otterbox","1","","",""),
array("oakley sunglasses","1","","",""),
array("ooma","1","","",""),
array("oakley sunglasses for men","1","","",""),
array("office 2007","1","","",""),
array("outliers","1","","",""),
array("one tree hill","1","","",""),
array("orkut","2","","",""),
array("omg","2","","",""),
array("overstock.com","3","","",""),
array("ovulation calendar","3","","",""),
array("ovulation calculator","3","","",""),
array("owl city fireflies","4","","",""),
array("one time","4","","",""),
array("one time justin bieber","4","","",""),
array("one less lonely justin bieber","4","","",""),
array("one republic all the right moves","4","","",""),
array("on to the next one jay z","4","","",""),
array("oh snsd","4","","",""),
array("old spice commercial","4","","",""),
array("ok go","4","","","")),
"p" => array(
array("pandora","0","2","",""),
array("pizza hut","0","2","",""),
array("petsmart","0","2","",""),
array("people search","2","3","",""),
array("paypal","2","3","",""),
array("people finder","2","3","",""),
array("photobucket","0","","",""),
array("poptropica","0","","",""),
array("papa johns","0","","",""),
array("party city","0","","",""),
array("plano isd","0","","",""),
array("primary games","0","","",""),
array("people of walmart","0","","",""),
array("ps3","1","","",""),
array("playstation 3","1","","",""),
array("p90x","1","","",""),
array("psp","1","","",""),
array("ps3 games","1","","",""),
array("pokemon","1","","",""),
array("ps3 console","1","","",""),
array("portable dvd player","1","","",""),
array("percy jackson","1","","",""),
array("princess and the frog","1","","",""),
array("paul mccartney","2","","",""),
array("payless shoes","2","","",""),
array("perez hilton","2","","",""),
array("petco","2","","",""),
array("pregnancy week by week","3","","",""),
array("prom dresses","3","","",""),
array("poems","3","","",""),
array("priceline.com","3","","",""),
array("pregnancy","3","","",""),
array("proxy","3","","",""),
array("pregnancy symptoms","3","","",""),
array("party in the usa","4","","",""),
array("pants on the ground","4","","",""),
array("pitbull","4","","",""),
array("pink","4","","",""),
array("paramore","4","","",""),
array("poker face","4","","",""),
array("paparazzi lady gaga","4","","",""),
array("pilipinas got talent","4","","",""),
array("poker face lady gaga","4","","",""),
array("pink floyd","4","","","")),
"q" => array(
array("quotes","0","2","3",""),
array("quickbooks","0","1","3",""),
array("qvc","0","2","",""),
array("quotes about life","0","3","",""),
array("quicktime","0","2","",""),
array("quiznos","0","2","",""),
array("quicken","0","1","",""),
array("queen","1","4","",""),
array("quizzes","2","3","",""),
array("quotes to live by","0","","",""),
array("quotes about love","0","","",""),
array("quest diagnostics locations","0","","",""),
array("quickbooks pro 2010","1","","",""),
array("quicken 2010","1","","",""),
array("quiksilver","1","","",""),
array("queer as folk","1","","",""),
array("quick trim","1","","",""),
array("quilt","1","","",""),
array("quinoa","1","","",""),
array("query string","2","","",""),
array("quest diagnostics","2","","",""),
array("qwest","2","","",""),
array("qantas","2","","",""),
array("qatar airways","2","","",""),
array("questions and answers","3","","",""),
array("questions","3","","",""),
array("quotes of the day","3","","",""),
array("qvc.com","3","","",""),
array("quit smoking","3","","",""),
array("quest","3","","",""),
array("queen bohemian rhapsody","4","","",""),
array("quest crew","4","","",""),
array("queen we will rock you","4","","",""),
array("queen don't stop me now","4","","",""),
array("queens of the stone age","4","","",""),
array("queen i want to break free","4","","",""),
array("queen seondeok","4","","",""),
array("queen somebody to love","4","","",""),
array("quest crew compilation","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("ebay motors","0","2","3",""),
array("espn","0","2","",""),
array("english to spanish translation","0","3","",""),
array("ed hardy","1","3","",""),
array("eminem","2","4","",""),
array("eharmony","2","3","",""),
array("easter 2010","0","","",""),
array("express","0","","",""),
array("evite","0","","",""),
array("etsy","0","","",""),
array("edible arrangements","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("erykah badu","1","","",""),
array("earbuds","1","","",""),
array("external hard drive 1tb","1","","",""),
array("eclipse","1","","",""),
array("easter","1","","",""),
array("ethernet cable","1","","",""),
array("entourage","1","","",""),
array("elizabeth taylor","2","","",""),
array("erin andrews","2","","",""),
array("elin nordegren","2","","",""),
array("enterprise car rental","2","","",""),
array("ebay.com","3","","",""),
array("expedia.com","3","","",""),
array("eharmony.com","3","","",""),
array("engagement rings","3","","",""),
array("empire state of mind","4","","",""),
array("eclipse trailer official 2010","4","","",""),
array("eclipse trailer","4","","",""),
array("eminem beautiful","4","","",""),
array("enrique iglesias","4","","",""),
array("evanescence","4","","",""),
array("eminem lose yourself","4","","",""),
array("eye of the tiger","4","","",""),
array("elvis presley","4","","","")),
"s" => array(
array("southwest airlines","0","2","3",""),
array("sears","0","2","3",""),
array("skype","0","2","",""),
array("sprint","0","2","",""),
array("shoes","1","3","",""),
array("star wars","1","2","",""),
array("sams club","0","","",""),
array("spanish translation","0","","",""),
array("super bowl 2010","0","","",""),
array("studio movie grill","0","","",""),
array("speed test","0","","",""),
array("sports authority","0","","",""),
array("sunglasses","1","","",""),
array("sherlock holmes","1","","",""),
array("sony cybershot","1","","",""),
array("starcraft 2","1","","",""),
array("splinter cell conviction","1","","",""),
array("sd card","1","","",""),
array("slash","1","","",""),
array("star trek","1","","",""),
array("sandra bullock","2","","",""),
array("scottie pippen","2","","",""),
array("steven tyler","2","","",""),
array("staples","2","","",""),
array("sony","2","","",""),
array("science fair projects","3","","",""),
array("song lyrics","3","","",""),
array("swine flu","3","","",""),
array("swine flu symptoms","3","","",""),
array("symptoms of swine flu","3","","",""),
array("spanish dictionary","3","","",""),
array("search engines","3","","",""),
array("shakira","4","","",""),
array("small wood projects","4","","",""),
array("selena gomez","4","","",""),
array("soulja boy","4","","",""),
array("starstruck","4","","",""),
array("sexist video indian","4","","",""),
array("selena gomez naturally","4","","",""),
array("shane dawson","4","","",""),
array("say ahh trey songz","4","","",""),
array("snoop dogg","4","","","")),
"t" => array(
array("target","0","2","",""),
array("tmz","0","2","",""),
array("twilight","1","3","",""),
array("travelocity","2","3","",""),
array("toys r us","2","3","",""),
array("taylor swift","2","4","",""),
array("texas lottery","0","","",""),
array("translator","0","","",""),
array("texas workforce commission","0","","",""),
array("twitter","0","","",""),
array("thesaurus","0","","",""),
array("time warner cable","0","","",""),
array("tmobile","0","","",""),
array("ticketmaster","0","","",""),
array("true blood","1","","",""),
array("tv","1","","",""),
array("toy story","1","","",""),
array("the blind side","1","","",""),
array("the help","1","","",""),
array("true blood season 2","1","","",""),
array("the big short","1","","",""),
array("t2i","1","","",""),
array("the last song","1","","",""),
array("tiki barber","2","","",""),
array("tiger woods","2","","",""),
array("tagged","2","","",""),
array("tina fey","2","","",""),
array("t-mobile","2","","",""),
array("tattoos","3","","",""),
array("tattoo designs","3","","",""),
array("tires","3","","",""),
array("translate english to spanish","3","","",""),
array("toyota","3","","",""),
array("teen pregnancy","3","","",""),
array("telephone directory","3","","",""),
array("tik tok","4","","",""),
array("telephone lady gaga","4","","",""),
array("tik tok keisha","4","","",""),
array("taylor swift you belong with me","4","","",""),
array("telephone","4","","",""),
array("telephone lady gaga beyonce","4","","",""),
array("tom and jerry","4","","",""),
array("trey songz","4","","",""),
array("two is better than one","4","","","")),
"u" => array(
array("us airways","0","2","3",""),
array("usps","0","2","",""),
array("ups","0","2","",""),
array("united airlines","0","3","",""),
array("univision","0","2","",""),
array("usher","1","4","",""),
array("uggs","1","3","",""),
array("ufc","2","4","",""),
array("university of phoenix","2","3","",""),
array("ups tracking","0","","",""),
array("urban dictionary","0","","",""),
array("unt","0","","",""),
array("uta","0","","",""),
array("utd","0","","",""),
array("unlocked cell phones","1","","",""),
array("usb flash drive","1","","",""),
array("uncharted 2","1","","",""),
array("up","1","","",""),
array("usb hub","1","","",""),
array("up in the air","1","","",""),
array("umbrella","1","","",""),
array("under armour","1","","",""),
array("united","2","","",""),
array("undercover boss","2","","",""),
array("universal studios","2","","",""),
array("urban outfitters","2","","",""),
array("used cars","3","","",""),
array("ugg boots","3","","",""),
array("used cars for sale","3","","",""),
array("unique baby names","3","","",""),
array("unemployment","3","","",""),
array("used books","3","","",""),
array("usher daddy's home","4","","",""),
array("u2","4","","",""),
array("ufo","4","","",""),
array("usher papers","4","","",""),
array("unforgivable","4","","",""),
array("united states of pop 2009","4","","",""),
array("usher yeah","4","","",""),
array("undertaker","4","","","")),
"v" => array(
array("verizon","0","2","3",""),
array("verizon wireless","0","3","",""),
array("victoria secret","0","3","",""),
array("vancouver 2010","0","4","",""),
array("vampire diaries","0","1","",""),
array("vera bradley","1","3","",""),
array("vampire weekend","1","4","",""),
array("vanessa hudgens","2","4","",""),
array("verizon.net","0","","",""),
array("verizon fios","0","","",""),
array("vlc","0","","",""),
array("viewpoint bank","0","","",""),
array("verizon email","0","","",""),
array("vacuum cleaner","1","","",""),
array("video camera","1","","",""),
array("verizon cell phones","1","","",""),
array("vans","1","","",""),
array("vacuum","1","","",""),
array("vibratores for women","1","","",""),
array("victoria's secret","1","","",""),
array("video","2","","",""),
array("vh1","2","","",""),
array("v-22 osprey","2","","",""),
array("vonage","2","","",""),
array("vanguard","2","","",""),
array("value city furniture","2","","",""),
array("volkswagen","2","","",""),
array("victoria beckham","2","","",""),
array("verizon.com","3","","",""),
array("verizonwireless.com","3","","",""),
array("volcanoes","3","","",""),
array("videos","3","","",""),
array("virgin mobile","3","","",""),
array("viagra","3","","",""),
array("valentines day trailer","4","","",""),
array("various artists","4","","",""),
array("video phone","4","","",""),
array("video phone beyonce official video","4","","",""),
array("vanilla twilight","4","","",""),
array("valentines day","4","","",""),
array("vanilla twilight owl city","4","","","")),
"w" => array(
array("weather","0","2","3",""),
array("white pages","0","2","3",""),
array("walmart","0","2","",""),
array("wikipedia","0","2","",""),
array("wells fargo","0","2","",""),
array("walgreens","0","2","",""),
array("wwe","2","4","",""),
array("www.facebook.com","0","","",""),
array("wfaa","0","","",""),
array("www.yahoo.com","0","","",""),
array("watch-movies.net","0","","",""),
array("wii","1","","",""),
array("wii games","1","","",""),
array("windows 7","1","","",""),
array("wii fit","1","","",""),
array("wii console","1","","",""),
array("watches","1","","",""),
array("wireless router","1","","",""),
array("webcam","1","","",""),
array("wii fit plus","1","","",""),
array("wii fit plus with balance board","1","","",""),
array("webkinz","2","","",""),
array("winona ryder","2","","",""),
array("wachovia","2","","",""),
array("what does my name mean","3","","",""),
array("what is love","3","","",""),
array("when will the world end","3","","",""),
array("what are the symptoms of swine flu","3","","",""),
array("what is global warming","3","","",""),
array("wedding dresses","3","","",""),
array("what does my last name mean","3","","",""),
array("weather forecast","3","","",""),
array("we are the world","4","","",""),
array("whatcha say","4","","",""),
array("we are the world haiti","4","","",""),
array("we are the world 2010","4","","",""),
array("wisin y yandel","4","","",""),
array("whatcha say jason derulo","4","","",""),
array("whitney houston","4","","",""),
array("we are the world michael jackson","4","","",""),
array("when i look at you miley cyrus","4","","","")),
"x" => array(
array("xbox 360","0","1","2","3"),
array("xm radio","0","2","3",""),
array("xbox live","0","1","2",""),
array("xanax","0","2","3",""),
array("xbox 360 games","0","1","3",""),
array("xbox 720","0","4","",""),
array("xbox","1","3","",""),
array("xbox 360 elite","1","3","",""),
array("xbox cheats","2","3","",""),
array("xkcd","0","","",""),
array("xto energy","0","","",""),
array("xbmc","0","","",""),
array("xm radio online","0","","",""),
array("xbox 360 console","1","","",""),
array("xbox 360 controller","1","","",""),
array("xbox 360 wireless adapter","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("xbox 360 headset","1","","",""),
array("x games","2","","",""),
array("xvid","2","","",""),
array("xbox red ring of death","2","","",""),
array("x17","2","","",""),
array("xerox","2","","",""),
array("xbox 360 cheats","3","","",""),
array("xbox 360 cheat codes","3","","",""),
array("xbox360","3","","",""),
array("x factor 2009","4","","",""),
array("xxl movie","4","","",""),
array("x factor","4","","",""),
array("x factor 2010","4","","",""),
array("xzibit","4","","",""),
array("xxl tv 18","4","","",""),
array("x factor 2010 danmark","4","","",""),
array("xatzigiannis","4","","","")),
"y" => array(
array("youtube","0","2","3","4"),
array("yahoo mail","0","2","3",""),
array("yellow pages","0","2","3",""),
array("yahoo maps","0","2","",""),
array("youtube music","0","3","",""),
array("yahoo messenger","0","2","",""),
array("young money","1","4","",""),
array("yahoo","0","","",""),
array("yahoo answers","0","","",""),
array("yahoo finance","0","","",""),
array("yahoo music","0","","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yoga dvd","1","","",""),
array("yo gabba gabba","1","","",""),
array("yugioh cards","1","","",""),
array("your baby can read","1","","",""),
array("yugioh","1","","",""),
array("yakuza 3","1","","",""),
array("yarn","1","","",""),
array("yahoo games","2","","",""),
array("youtube video","2","","",""),
array("yeti","2","","",""),
array("yahoo groups","2","","",""),
array("youtube broadcast yourself","2","","",""),
array("youtube videos","3","","",""),
array("yellowpages.com","3","","",""),
array("yellow pages.com","3","","",""),
array("yahoo.com","3","","",""),
array("yellowbook.com","3","","",""),
array("yellow book","3","","",""),
array("you belong with me","4","","",""),
array("you belong with me taylor swift","4","","",""),
array("your a jerk","4","","",""),
array("young jeezy","4","","",""),
array("young money bedrock","4","","",""),
array("your love is my drug","4","","",""),
array("you belong with me taylor swift lyrics","4","","",""),
array("yetenek sizsiniz türkiye","4","","","")),
"z" => array(
array("zappos","0","2","3",""),
array("zodiac signs","0","2","3",""),
array("zales","0","2","3",""),
array("zune","0","1","2",""),
array("zombieland","0","1","4",""),
array("zillow","0","2","",""),
array("zip codes","0","3","",""),
array("zhu zhu pets","1","3","",""),
array("zumba","1","4","",""),
array("zhu zhu","1","3","",""),
array("zuma","2","3","",""),
array("zip code finder","2","3","",""),
array("zip codes by city","0","","",""),
array("zumiez","0","","",""),
array("zip code map","0","","",""),
array("zune hd","1","","",""),
array("zippo","1","","",""),
array("zumba fitness dvd","1","","",""),
array("zelda","1","","",""),
array("zumba dvd","1","","",""),
array("zip code lookup","2","","",""),
array("zedge","2","","",""),
array("zooey deschanel","2","","",""),
array("zappos.com","3","","",""),
array("zip code list","3","","",""),
array("zombie","4","","",""),
array("zz top","4","","",""),
array("zac efron","4","","",""),
array("zac brown band","4","","",""),
array("zeljko joksimovic ljubavi","4","","",""),
array("zidane","4","","",""),
array("zach galifianakis","4","","",""),
array("zeitgeist","4","","","")));
?>