<?php $topResults = array(
"a" => array(
array("amazon","0","2","",""),
array("aol","0","2","",""),
array("american idol","0","2","",""),
array("avatar","1","4","",""),
array("allegiant air","0","","",""),
array("american airlines","0","","",""),
array("aria las vegas","0","","",""),
array("at&t wireless","0","","",""),
array("ask.com","0","","",""),
array("autotrader","0","","",""),
array("american express","0","","",""),
array("apple ipad","1","","",""),
array("alice in wonderland","1","","",""),
array("avatar blu-ray","1","","",""),
array("alan wake","1","","",""),
array("airsoft guns","1","","",""),
array("adidas","1","","",""),
array("avatar dvd","1","","",""),
array("apple","1","","",""),
array("airsoft","1","","",""),
array("ask jeeves","2","","",""),
array("anne hathaway","2","","",""),
array("at&t","2","","",""),
array("addicting games","2","","",""),
array("abc","2","","",""),
array("aim","2","","",""),
array("ako","2","","",""),
array("at t","3","","",""),
array("answers.com","3","","",""),
array("airline tickets","3","","",""),
array("att.com","3","","",""),
array("apartments for rent","3","","",""),
array("att","3","","",""),
array("area codes","3","","",""),
array("are vampires real","3","","",""),
array("am i pregnant","3","","",""),
array("aaa","3","","",""),
array("akon","4","","",""),
array("annoying orange","4","","",""),
array("alicia keys","4","","",""),
array("avril lavigne","4","","",""),
array("american idol 2010","4","","",""),
array("alice in wonderland trailer","4","","",""),
array("alicia keys try sleeping with a broken heart","4","","",""),
array("aventura","4","","",""),
array("all the way turned up","4","","","")),
"b" => array(
array("bank of america","0","2","3",""),
array("best buy","0","2","3",""),
array("bed bath and beyond","0","2","3",""),
array("britney spears","1","2","4",""),
array("barnes and noble","0","2","",""),
array("baby names","2","3","",""),
array("bank of america online banking","0","","",""),
array("bellagio","0","","",""),
array("bing","0","","",""),
array("big 5","0","","",""),
array("blockbuster","0","","",""),
array("buffalo wild wings","0","","",""),
array("blackberry","1","","",""),
array("bluetooth headset","1","","",""),
array("blu ray","1","","",""),
array("blackberry bold 9700","1","","",""),
array("blu ray player","1","","",""),
array("bose","1","","",""),
array("backpack","1","","",""),
array("blackberry unlocked","1","","",""),
array("battlefield bad company 2","1","","",""),
array("burt reynolds","2","","",""),
array("bobby brown","2","","",""),
array("bo bice","2","","",""),
array("blank","2","","",""),
array("babies r us","3","","",""),
array("baby shower games","3","","",""),
array("baby boy names","3","","",""),
array("bmi","3","","",""),
array("black friday 2009","3","","",""),
array("barack obama","3","","",""),
array("baby justin bieber","4","","",""),
array("baby","4","","",""),
array("bedrock","4","","",""),
array("beyonce","4","","",""),
array("bad romance","4","","",""),
array("blah blah blah kesha","4","","",""),
array("black eyed peas","4","","",""),
array("baby justin bieber lyrics","4","","",""),
array("bad romance lady gaga","4","","","")),
"c" => array(
array("craigslist","0","2","",""),
array("costco","0","2","",""),
array("cnn","0","2","",""),
array("chase","0","2","",""),
array("craigslist las vegas","0","","",""),
array("csn","0","","",""),
array("clark county assessor","0","","",""),
array("clark county school district","0","","",""),
array("cox.net","0","","",""),
array("chase bank","0","","",""),
array("crocs","1","","",""),
array("camera","1","","",""),
array("canon 7d","1","","",""),
array("canon t2i","1","","",""),
array("coffee maker","1","","",""),
array("canon","1","","",""),
array("charlaine harris","1","","",""),
array("call of duty modern warfare 2","1","","",""),
array("cell phone","1","","",""),
array("canon powershot","1","","",""),
array("cingular","2","","",""),
array("chat","2","","",""),
array("cartoon network","2","","",""),
array("capital one","2","","",""),
array("comcast","2","","",""),
array("cynthia nixon","2","","",""),
array("cheap airline tickets","3","","",""),
array("cheap flights","3","","",""),
array("coupons","3","","",""),
array("car rentals","3","","",""),
array("cars","3","","",""),
array("cheat codes","3","","",""),
array("calculator","3","","",""),
array("calorie counter","3","","",""),
array("cheap hotels","3","","",""),
array("clip art","3","","",""),
array("chris brown","4","","",""),
array("charlie bit my finger","4","","",""),
array("cross tattoos","4","","",""),
array("christina aguilera","4","","",""),
array("celine dion","4","","",""),
array("carry out","4","","",""),
array("crazy frog","4","","",""),
array("coldplay","4","","",""),
array("clash of the titans","4","","",""),
array("chris brown crawl","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("delta airlines","0","3","",""),
array("direct tv","0","3","",""),
array("dmv","0","2","",""),
array("dell","2","3","",""),
array("disney channel","0","","",""),
array("dominos","0","","",""),
array("disneyland","0","","",""),
array("dmv nevada","0","","",""),
array("dillards","0","","",""),
array("discount tire","0","","",""),
array("digital camera","1","","",""),
array("daria","1","","",""),
array("dead in the family","1","","",""),
array("dvd","1","","",""),
array("dsi","1","","",""),
array("droid","1","","",""),
array("dvd player","1","","",""),
array("dexter","1","","",""),
array("dsi xl","1","","",""),
array("droid incredible","1","","",""),
array("disney","2","","",""),
array("dunkin donuts","2","","",""),
array("dancing with the stars","2","","",""),
array("delta","2","","",""),
array("directions","2","","",""),
array("danica patrick","2","","",""),
array("dress up games","2","","",""),
array("dogs","3","","",""),
array("disneychannel.com","3","","",""),
array("driving directions","3","","",""),
array("delta.com","3","","",""),
array("dictionary.com","3","","",""),
array("dog breeds","3","","",""),
array("drake","4","","",""),
array("david guetta","4","","",""),
array("down","4","","",""),
array("drake over","4","","",""),
array("do you remember jay sean","4","","",""),
array("drop the world","4","","",""),
array("down jay sean","4","","",""),
array("david guetta memories","4","","",""),
array("demi lovato","4","","",""),
array("drake forever","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("ebay motors","0","2","3",""),
array("eminem","1","2","4",""),
array("espn","0","2","",""),
array("english to spanish translation","0","3","",""),
array("eclipse","1","4","",""),
array("ed hardy","1","3","",""),
array("eharmony","2","3","",""),
array("easter 2010","0","","",""),
array("eppicard","0","","",""),
array("embarq","0","","",""),
array("encore las vegas","0","","",""),
array("extreme thing 2010","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("exile on main street","1","","",""),
array("earbuds","1","","",""),
array("external hard drive 1tb","1","","",""),
array("entourage","1","","",""),
array("espresso machine","1","","",""),
array("evangeline lilly","2","","",""),
array("erica blasberg","2","","",""),
array("enterprise car rental","2","","",""),
array("elena kagan","2","","",""),
array("ebay.com","3","","",""),
array("expedia.com","3","","",""),
array("eharmony.com","3","","",""),
array("engagement rings","3","","",""),
array("eclipse trailer official 2010","4","","",""),
array("eclipse trailer","4","","",""),
array("empire state of mind","4","","",""),
array("eminem beautiful","4","","",""),
array("enrique iglesias","4","","",""),
array("evanescence","4","","",""),
array("erykah badu","4","","",""),
array("eminem lose yourself","4","","","")),
"f" => array(
array("free online games","0","2","3",""),
array("family guy","1","2","4",""),
array("facebook","0","2","",""),
array("facebook login","0","2","",""),
array("fandango","0","2","",""),
array("food network","0","2","",""),
array("fox news","0","","",""),
array("frys","0","","",""),
array("firefox","0","","",""),
array("fedex","0","","",""),
array("funbrain","0","","",""),
array("final fantasy xiii","1","","",""),
array("flash drive","1","","",""),
array("flip video","1","","",""),
array("flowers","1","","",""),
array("flip","1","","",""),
array("fallout 3","1","","",""),
array("fleshlight","1","","",""),
array("food processor","1","","",""),
array("fan","1","","",""),
array("fafsa","2","","",""),
array("face","2","","",""),
array("fidelity","2","","",""),
array("fergie","2","","",""),
array("free ringtones","3","","",""),
array("free music downloads","3","","",""),
array("free games","3","","",""),
array("free ecards","3","","",""),
array("find people","3","","",""),
array("free music","3","","",""),
array("free people search","3","","",""),
array("find a person","3","","",""),
array("free credit report","3","","",""),
array("fireflies","4","","",""),
array("funny video","4","","",""),
array("female hair transplant","4","","",""),
array("fireflies owl city","4","","",""),
array("funny","4","","",""),
array("funny accidents","4","","",""),
array("fred","4","","",""),
array("funny cats","4","","",""),
array("funny pranks","4","","","")),
"g" => array(
array("games","0","2","3",""),
array("google","0","2","4",""),
array("gmail","0","2","",""),
array("google maps","0","2","",""),
array("google earth","0","2","",""),
array("glee","1","4","",""),
array("god of war 3","1","4","",""),
array("google search","2","3","",""),
array("google.com","0","","",""),
array("gamestop","0","","",""),
array("green valley ranch","0","","",""),
array("google translate","0","","",""),
array("greyhound","0","","",""),
array("gps","1","","",""),
array("garmin","1","","",""),
array("garmin gps","1","","",""),
array("gift card","1","","",""),
array("garmin nuvi","1","","",""),
array("guitar","1","","",""),
array("god of war","1","","",""),
array("guess","1","","",""),
array("gisele bundchen","2","","",""),
array("gwyneth paltrow","2","","",""),
array("gap","2","","",""),
array("gas prices","2","","",""),
array("global warming","3","","",""),
array("games.com","3","","",""),
array("gnc","3","","",""),
array("genital warts","3","","",""),
array("game cheats","3","","",""),
array("google search engine","3","","",""),
array("girl games","3","","",""),
array("gout","3","","",""),
array("google slap","4","","",""),
array("gummy bear song","4","","",""),
array("gorillaz","4","","",""),
array("gucci mane","4","","",""),
array("green day","4","","",""),
array("guns n roses","4","","",""),
array("glee don't stop believe","4","","","")),
"h" => array(
array("hotmail","0","2","3",""),
array("home depot","0","2","3",""),
array("harry potter","1","2","",""),
array("how to kiss","3","4","",""),
array("hulu","0","","",""),
array("hotels.com","0","","",""),
array("haiti","0","","",""),
array("horoscope","0","","",""),
array("hawaiian airlines","0","","",""),
array("harbor freight","0","","",""),
array("hp","0","","",""),
array("house of blues las vegas","0","","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("htc incredible","1","","",""),
array("halo reach","1","","",""),
array("htc hd2","1","","",""),
array("how to train your dragon","1","","",""),
array("hard drive","1","","",""),
array("heavy rain","1","","",""),
array("hello kitty","1","","",""),
array("horoscopes","2","","",""),
array("heidi klum","2","","",""),
array("holiday inn","2","","",""),
array("honda","2","","",""),
array("hummus","2","","",""),
array("hsbc","2","","",""),
array("hgtv","2","","",""),
array("how much should i weigh","3","","",""),
array("how to get pregnant","3","","",""),
array("halloween costumes","3","","",""),
array("hotmail.com","3","","",""),
array("how do you spell a word","3","","",""),
array("how to make a website","3","","",""),
array("how to write a resume","3","","",""),
array("hannah montana","4","","",""),
array("hey soul sister","4","","",""),
array("how low can you go ludacris","4","","",""),
array("happy tree friends","4","","",""),
array("halo","4","","",""),
array("halo beyonce","4","","",""),
array("hey soul sister train","4","","",""),
array("hallelujah","4","","",""),
array("hotel room service","4","","","")),
"i" => array(
array("itunes","0","2","3",""),
array("ipad","0","1","4",""),
array("ipod","1","2","3",""),
array("iphone","1","2","3",""),
array("irs","0","2","",""),
array("imdb","0","2","",""),
array("ikea","0","2","",""),
array("ign","0","2","",""),
array("inspirational quotes","0","3","",""),
array("ipod touch","1","3","",""),
array("images","2","3","",""),
array("itunes download","0","","",""),
array("isohunt","0","","",""),
array("internet speed test","0","","",""),
array("ipod nano","1","","",""),
array("ipad case","1","","",""),
array("iphone 3gs","1","","",""),
array("itouch","1","","",""),
array("iphone case","1","","",""),
array("ipod touch 3rd generation","1","","",""),
array("internet explorer","2","","",""),
array("imeem","2","","",""),
array("is the world going to end in 2012","3","","",""),
array("iq test","3","","",""),
array("is bronchitis contagious","3","","",""),
array("is pneumonia contagious","3","","",""),
array("in my head jason derulo","4","","",""),
array("imma be","4","","",""),
array("in my head","4","","",""),
array("imma be black eyed peas","4","","",""),
array("iyaz replay","4","","",""),
array("iron man 2 trailer","4","","",""),
array("i gotta feeling","4","","",""),
array("i made it","4","","",""),
array("i made it kevin rudolf","4","","","")),
"j" => array(
array("justin bieber","0","1","4",""),
array("jcpenney","0","2","",""),
array("java","0","2","",""),
array("joann fabrics","0","3","",""),
array("juicy couture","0","1","",""),
array("jokes","2","3","",""),
array("jay z","2","4","",""),
array("jet blue","0","","",""),
array("jersey shore","0","","",""),
array("justin tv","0","","",""),
array("jack in the box","0","","",""),
array("jobs in las vegas","0","","",""),
array("jillian michaels","1","","",""),
array("just cause 2","1","","",""),
array("juicer","1","","",""),
array("jewelry","1","","",""),
array("james patterson","1","","",""),
array("jack johnson","1","","",""),
array("jewelry box","1","","",""),
array("jawbone","1","","",""),
array("jobs","2","","",""),
array("jessica simpson","2","","",""),
array("jennifer aniston","2","","",""),
array("jessica alba","2","","",""),
array("jetblue","2","","",""),
array("jennifer love hewitt","2","","",""),
array("jobs in my area","3","","",""),
array("job search","3","","",""),
array("jcpenney.com","3","","",""),
array("jc penney","3","","",""),
array("jobs for teens","3","","",""),
array("jordans","3","","",""),
array("jcp.com","3","","",""),
array("jobs.com","3","","",""),
array("justin bieber baby","4","","",""),
array("justin bieber one time","4","","",""),
array("jason derulo in my head","4","","",""),
array("justin bieber love me","4","","",""),
array("justin timberlake","4","","",""),
array("justin bieber one less lonelygirl","4","","",""),
array("jason derulo","4","","",""),
array("justin bieber baby lyrics","4","","","")),
"k" => array(
array("kmart","0","2","3",""),
array("kohls","0","3","",""),
array("kim kardashian","0","3","",""),
array("kbb","0","2","",""),
array("kayak","0","3","",""),
array("kindle","1","3","",""),
array("kelly clarkson","2","4","",""),
array("kesha","0","","",""),
array("klas tv","0","","",""),
array("knotts berry farm","0","","",""),
array("kinkos","0","","",""),
array("klas","0","","",""),
array("keurig","1","","",""),
array("kindle books","1","","",""),
array("k cups","1","","",""),
array("kindle cover","1","","",""),
array("keyboard","1","","",""),
array("kindle 2","1","","",""),
array("kitchenaid mixer","1","","",""),
array("knife","1","","",""),
array("kindle dx","1","","",""),
array("katharine hepburn","2","","",""),
array("katherine heigl","2","","",""),
array("kristin chenoweth","2","","",""),
array("kohl's","2","","",""),
array("keira knightley","2","","",""),
array("katie holmes","2","","",""),
array("kellie pickler","2","","",""),
array("kohls.com","3","","",""),
array("kmart.com","3","","",""),
array("kids games","3","","",""),
array("kijiji","3","","",""),
array("kayak.com","3","","",""),
array("keisha tik tok","4","","",""),
array("kesha blah blah blah","4","","",""),
array("katy perry","4","","",""),
array("kiss","4","","",""),
array("kid cudi","4","","",""),
array("kanye west","4","","",""),
array("kiss me thru the phone","4","","",""),
array("korn","4","","",""),
array("kings of leon","4","","","")),
"l" => array(
array("lady gaga","0","1","2","4"),
array("limewire","0","2","3",""),
array("lowes","0","3","",""),
array("lost","1","2","",""),
array("lyrics","2","3","",""),
array("love poems","2","3","",""),
array("love quotes","2","3","",""),
array("lil wayne","3","4","",""),
array("love","3","4","",""),
array("las vegas review journal","0","","",""),
array("las vegas weather","0","","",""),
array("las vegas news","0","","",""),
array("las vegas sun","0","","",""),
array("louis vuitton","0","","",""),
array("lvac","0","","",""),
array("las vegas dmv","0","","",""),
array("laptop","1","","",""),
array("lego","1","","",""),
array("luggage","1","","",""),
array("lego star wars","1","","",""),
array("laptop computer","1","","",""),
array("lord of the rings","1","","",""),
array("lcd tv","1","","",""),
array("laptop bag","1","","",""),
array("lindsay lohan","2","","",""),
array("lowe's","2","","",""),
array("law and order","2","","",""),
array("las vegas","2","","",""),
array("lyrics to songs","3","","",""),
array("lingerie","3","","",""),
array("lowes.com","3","","",""),
array("lady gaga telephone","4","","",""),
array("lady gaga bad romance","4","","",""),
array("lady gaga paparazzi","4","","",""),
array("lady gaga poker face","4","","",""),
array("linkin park","4","","",""),
array("ludacris","4","","",""),
array("lil wayne no ceiling","4","","","")),
"m" => array(
array("music","1","2","3","4"),
array("maps","0","2","3",""),
array("myspace","0","2","",""),
array("msn","0","2","",""),
array("mapquest driving directions","0","2","",""),
array("myspace layouts","0","3","",""),
array("mapquest","0","","",""),
array("mandalay bay","0","","",""),
array("mgm grand las vegas","0","","",""),
array("mccarran airport","0","","",""),
array("macys","0","","",""),
array("macbook","1","","",""),
array("mp3 player","1","","",""),
array("macbook pro","1","","",""),
array("micro sd","1","","",""),
array("modern warfare 2","1","","",""),
array("mp3","1","","",""),
array("mothers day","1","","",""),
array("macbook pro 13","1","","",""),
array("mass effect 2","1","","",""),
array("men in black iii","2","","",""),
array("movies","2","","",""),
array("macy's","2","","",""),
array("mtv","2","","",""),
array("megan fox","2","","",""),
array("music videos","3","","",""),
array("math answers","3","","",""),
array("mortgage calculator","3","","",""),
array("match.com","3","","",""),
array("myspace backgrounds","3","","",""),
array("map","3","","",""),
array("medical dictionary","3","","",""),
array("michael jackson","4","","",""),
array("miley cyrus","4","","",""),
array("mariah carey","4","","",""),
array("miley cyrus party in the usa","4","","",""),
array("my wife having an affair","4","","",""),
array("metallica","4","","",""),
array("michael jackson billie jean","4","","",""),
array("my chick bad","4","","",""),
array("madonna","4","","","")),
"n" => array(
array("netflix","0","2","3",""),
array("nfl","0","2","",""),
array("nick jr","0","2","",""),
array("nike","1","3","",""),
array("nascar","2","3","",""),
array("nissan","2","3","",""),
array("news","2","3","",""),
array("nevada dmv","0","","",""),
array("nevada unemployment","0","","",""),
array("nv energy","0","","",""),
array("nevada state bank","0","","",""),
array("nevada secretary of state","0","","",""),
array("nevada state college","0","","",""),
array("nevada federal credit union","0","","",""),
array("nintendo ds","1","","",""),
array("netbook","1","","",""),
array("nikon d90","1","","",""),
array("nikon d5000","1","","",""),
array("new moon","1","","",""),
array("nintendo dsi","1","","",""),
array("nintendo wii","1","","",""),
array("nikon","1","","",""),
array("nexus one","1","","",""),
array("nba","2","","",""),
array("nordstrom","2","","",""),
array("nokia","2","","",""),
array("nbc","2","","",""),
array("name meanings","3","","",""),
array("netflix.com","3","","",""),
array("northwest airlines","3","","",""),
array("names","3","","",""),
array("nada","3","","",""),
array("nicki minaj","4","","",""),
array("nothing on you b.o.b","4","","",""),
array("new songs 2010","4","","",""),
array("nigahiga","4","","",""),
array("nickelback","4","","",""),
array("naturally selena gomez","4","","",""),
array("nothing on you","4","","",""),
array("naruto","4","","",""),
array("need you now lady antebellum","4","","",""),
array("never let you go justin bieber","4","","","")),
"o" => array(
array("office depot","0","2","3",""),
array("orbitz","0","2","3",""),
array("online games","0","2","3",""),
array("olive garden","0","2","",""),
array("overstock","0","2","",""),
array("office max","0","3","",""),
array("online dictionary","2","3","",""),
array("orleans hotel las vegas","0","","",""),
array("olympics","0","","",""),
array("olympics 2010","0","","",""),
array("oscar nominations 2010","0","","",""),
array("oakley","1","","",""),
array("otterbox","1","","",""),
array("oakley sunglasses","1","","",""),
array("office 2010","1","","",""),
array("oh my dog","1","","",""),
array("ooma","1","","",""),
array("office 2007","1","","",""),
array("oakley sunglasses for men","1","","",""),
array("one tree hill","1","","",""),
array("outdoor furniture","1","","",""),
array("oprah","2","","",""),
array("orkut","2","","",""),
array("omg","2","","",""),
array("orlando bloom","2","","",""),
array("old navy","3","","",""),
array("overstock.com","3","","",""),
array("obama","3","","",""),
array("ovulation calendar","3","","",""),
array("ovulation calculator","3","","",""),
array("owl city fireflies","4","","",""),
array("one time justin bieber","4","","",""),
array("one time","4","","",""),
array("owl city","4","","",""),
array("over drake","4","","",""),
array("one republic all the right moves","4","","",""),
array("one less lonely justin bieber","4","","",""),
array("ok go","4","","",""),
array("owl city vanilla twilight","4","","",""),
array("on to the next one jay z","4","","","")),
"p" => array(
array("paypal","0","2","3",""),
array("pandora","0","2","",""),
array("pizza hut","0","2","",""),
array("people search","2","3","",""),
array("people finder","2","3","",""),
array("parentlink","0","","",""),
array("photobucket","0","","",""),
array("pac-man 30th anniversary","0","","",""),
array("poptropica","0","","",""),
array("planet hollywood las vegas","0","","",""),
array("papa johns","0","","",""),
array("pirate bay","0","","",""),
array("ps3","1","","",""),
array("p90x","1","","",""),
array("playstation 3","1","","",""),
array("psp","1","","",""),
array("ps3 games","1","","",""),
array("ps3 console","1","","",""),
array("portable dvd player","1","","",""),
array("pokemon","1","","",""),
array("projector","1","","",""),
array("percy jackson","1","","",""),
array("phil mickelson","2","","",""),
array("preakness stakes","2","","",""),
array("payless shoes","2","","",""),
array("perez hilton","2","","",""),
array("petco","2","","",""),
array("pregnancy week by week","3","","",""),
array("prom dresses","3","","",""),
array("poems","3","","",""),
array("priceline.com","3","","",""),
array("pregnancy","3","","",""),
array("proxy","3","","",""),
array("pregnancy symptoms","3","","",""),
array("party in the usa","4","","",""),
array("pitbull","4","","",""),
array("paramore","4","","",""),
array("pink","4","","",""),
array("pilipinas got talent","4","","",""),
array("pants on the ground","4","","",""),
array("poker face","4","","",""),
array("paparazzi lady gaga","4","","",""),
array("pass out tinie tempah","4","","",""),
array("pacquiao vs clottey","4","","","")),
"q" => array(
array("quotes","0","2","3",""),
array("quickbooks","1","2","3",""),
array("quest diagnostics","0","2","",""),
array("qvc","0","2","",""),
array("quiznos","0","2","",""),
array("quicktime","0","2","",""),
array("quotes about life","0","3","",""),
array("queen","1","4","",""),
array("quizzes","2","3","",""),
array("quest diagnostics locations","0","","",""),
array("quest diagnostics appointments","0","","",""),
array("quick trim","0","","",""),
array("quotes to live by","0","","",""),
array("quicken","1","","",""),
array("quickbooks pro 2010","1","","",""),
array("quiksilver","1","","",""),
array("quicken 2010","1","","",""),
array("queer as folk","1","","",""),
array("quilt","1","","",""),
array("quicksilver","1","","",""),
array("quantum of solace","1","","",""),
array("query string","2","","",""),
array("qwest","2","","",""),
array("qantas","2","","",""),
array("questions and answers","3","","",""),
array("questions","3","","",""),
array("quotes of the day","3","","",""),
array("qvc.com","3","","",""),
array("quit smoking","3","","",""),
array("quest","3","","",""),
array("queen bohemian rhapsody","4","","",""),
array("quest crew","4","","",""),
array("queen we will rock you","4","","",""),
array("queen don't stop me now","4","","",""),
array("queen seondeok","4","","",""),
array("queens of the stone age","4","","",""),
array("queen i want to break free","4","","",""),
array("queen somebody to love","4","","",""),
array("quest crew compilation","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("ebay motors","0","2","3",""),
array("eminem","1","2","4",""),
array("espn","0","2","",""),
array("english to spanish translation","0","3","",""),
array("eclipse","1","4","",""),
array("ed hardy","1","3","",""),
array("eharmony","2","3","",""),
array("easter 2010","0","","",""),
array("eppicard","0","","",""),
array("embarq","0","","",""),
array("encore las vegas","0","","",""),
array("extreme thing 2010","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("exile on main street","1","","",""),
array("earbuds","1","","",""),
array("external hard drive 1tb","1","","",""),
array("entourage","1","","",""),
array("espresso machine","1","","",""),
array("evangeline lilly","2","","",""),
array("erica blasberg","2","","",""),
array("enterprise car rental","2","","",""),
array("elena kagan","2","","",""),
array("ebay.com","3","","",""),
array("expedia.com","3","","",""),
array("eharmony.com","3","","",""),
array("engagement rings","3","","",""),
array("eclipse trailer official 2010","4","","",""),
array("eclipse trailer","4","","",""),
array("empire state of mind","4","","",""),
array("eminem beautiful","4","","",""),
array("enrique iglesias","4","","",""),
array("evanescence","4","","",""),
array("erykah badu","4","","",""),
array("eminem lose yourself","4","","","")),
"s" => array(
array("southwest airlines","0","2","3",""),
array("sears","0","2","3",""),
array("sprint","0","2","",""),
array("shoes","1","3","",""),
array("southwest gas","0","","",""),
array("skype","0","","",""),
array("sams club","0","","",""),
array("station casinos","0","","",""),
array("speed test","0","","",""),
array("super bowl 2010","0","","",""),
array("smiths grocery","0","","",""),
array("silly bandz","1","","",""),
array("starcraft 2","1","","",""),
array("sunglasses","1","","",""),
array("star wars","1","","",""),
array("sd card","1","","",""),
array("super street fighter 4","1","","",""),
array("sony cybershot","1","","",""),
array("sherlock holmes","1","","",""),
array("star trek","1","","",""),
array("search","2","","",""),
array("sarah palin","2","","",""),
array("samsung","2","","",""),
array("scarlett johansson","2","","",""),
array("steve nash","2","","",""),
array("sbc","2","","",""),
array("shawn johnson","2","","",""),
array("science fair projects","3","","",""),
array("song lyrics","3","","",""),
array("swine flu","3","","",""),
array("swine flu symptoms","3","","",""),
array("symptoms of swine flu","3","","",""),
array("spanish dictionary","3","","",""),
array("search engines","3","","",""),
array("shakira","4","","",""),
array("selena gomez","4","","",""),
array("soulja boy","4","","",""),
array("selena gomez naturally","4","","",""),
array("shane dawson","4","","",""),
array("say ahh trey songz","4","","",""),
array("starstruck","4","","",""),
array("snoop dogg","4","","",""),
array("sean paul","4","","",""),
array("single ladies","4","","","")),
"t" => array(
array("travelocity","0","2","3",""),
array("toyota","0","2","3",""),
array("target","0","2","",""),
array("tmz","0","2","",""),
array("twilight","1","3","",""),
array("toys r us","2","3","",""),
array("taylor swift","2","4","",""),
array("twitter","0","","",""),
array("translator","0","","",""),
array("thesaurus","0","","",""),
array("tmobile","0","","",""),
array("turbotax","0","","",""),
array("town square las vegas","0","","",""),
array("true blood","1","","",""),
array("tv","1","","",""),
array("true blood season 2","1","","",""),
array("the help","1","","",""),
array("toy story","1","","",""),
array("t2i","1","","",""),
array("the girl with the dragon tattoo","1","","",""),
array("transformers","1","","",""),
array("tent","1","","",""),
array("tiger woods","2","","",""),
array("tagged","2","","",""),
array("t-mobile","2","","",""),
array("tyra banks","2","","",""),
array("tattoos","3","","",""),
array("tattoo designs","3","","",""),
array("tires","3","","",""),
array("translate english to spanish","3","","",""),
array("teen pregnancy","3","","",""),
array("telephone directory","3","","",""),
array("telephone lady gaga","4","","",""),
array("tik tok","4","","",""),
array("telephone","4","","",""),
array("telephone lady gaga beyonce","4","","",""),
array("tik tok keisha","4","","",""),
array("taylor swift you belong with me","4","","",""),
array("tom and jerry","4","","",""),
array("tinie tempah pass out","4","","",""),
array("trey songz","4","","","")),
"u" => array(
array("us airways","0","2","3",""),
array("usps","0","2","",""),
array("united airlines","0","3","",""),
array("ups","0","2","",""),
array("university of phoenix","0","3","",""),
array("usher","1","4","",""),
array("u2","1","4","",""),
array("used cars","2","3","",""),
array("ufc","2","4","",""),
array("unlv","0","","",""),
array("ups tracking","0","","",""),
array("urban dictionary","0","","",""),
array("us bank","0","","",""),
array("unlv basketball","0","","",""),
array("unlocked cell phones","1","","",""),
array("usb flash drive","1","","",""),
array("uncharted 2","1","","",""),
array("usb hub","1","","",""),
array("umbrella","1","","",""),
array("under armour","1","","",""),
array("up","1","","",""),
array("up in the air","1","","",""),
array("unclaimed money","2","","",""),
array("univision","2","","",""),
array("usaa","2","","",""),
array("usa today","2","","",""),
array("us postal service","2","","",""),
array("ugg boots","3","","",""),
array("used cars for sale","3","","",""),
array("unique baby names","3","","",""),
array("uggs","3","","",""),
array("unemployment","3","","",""),
array("used books","3","","",""),
array("usher daddy's home","4","","",""),
array("usher omg","4","","",""),
array("ufo","4","","",""),
array("usher yeah","4","","",""),
array("usher papers","4","","",""),
array("unforgivable","4","","",""),
array("undertaker","4","","","")),
"v" => array(
array("verizon","0","2","3",""),
array("verizon wireless","0","3","",""),
array("victoria secret","0","3","",""),
array("vh1","0","2","",""),
array("vampire diaries","0","1","",""),
array("vera bradley","1","3","",""),
array("vanessa hudgens","2","4","",""),
array("venetian hotel las vegas","0","","",""),
array("vancouver 2010","0","","",""),
array("virgin america","0","","",""),
array("vons","0","","",""),
array("vlc","0","","",""),
array("vacuum cleaner","1","","",""),
array("video camera","1","","",""),
array("verizon cell phones","1","","",""),
array("vibratores for women","1","","",""),
array("vans","1","","",""),
array("vacuum","1","","",""),
array("victoria's secret","1","","",""),
array("vampire academy","1","","",""),
array("video","2","","",""),
array("vanessa redgrave","2","","",""),
array("vonage","2","","",""),
array("value city furniture","2","","",""),
array("volkswagen","2","","",""),
array("vanguard","2","","",""),
array("victoria beckham","2","","",""),
array("verizon.com","3","","",""),
array("verizonwireless.com","3","","",""),
array("volcanoes","3","","",""),
array("videos","3","","",""),
array("virgin mobile","3","","",""),
array("viagra","3","","",""),
array("video phone","4","","",""),
array("various artists","4","","",""),
array("video phone beyonce official video","4","","",""),
array("vanilla twilight","4","","",""),
array("vanilla twilight owl city","4","","",""),
array("vampire weekend","4","","",""),
array("vevo","4","","",""),
array("viva la vida","4","","",""),
array("vicente fernandez","4","","","")),
"w" => array(
array("weather","0","2","3",""),
array("white pages","0","2","3",""),
array("walmart","0","2","",""),
array("wells fargo","0","2","",""),
array("wikipedia","0","2","",""),
array("walgreens","0","2","",""),
array("wwe","2","4","",""),
array("watch-movies.net","0","","",""),
array("www.facebook.com","0","","",""),
array("www.yahoo.com","0","","",""),
array("web md","0","","",""),
array("wii","1","","",""),
array("wii games","1","","",""),
array("windows 7","1","","",""),
array("watches","1","","",""),
array("wireless router","1","","",""),
array("women food and god","1","","",""),
array("wii fit","1","","",""),
array("webcam","1","","",""),
array("wii console","1","","",""),
array("world of warcraft","1","","",""),
array("webkinz","2","","",""),
array("wachovia","2","","",""),
array("www","2","","",""),
array("what does my name mean","3","","",""),
array("what is love","3","","",""),
array("when will the world end","3","","",""),
array("what are the symptoms of swine flu","3","","",""),
array("what is global warming","3","","",""),
array("wedding dresses","3","","",""),
array("what does my last name mean","3","","",""),
array("weather forecast","3","","",""),
array("we are the world","4","","",""),
array("we are the world haiti","4","","",""),
array("whatcha say","4","","",""),
array("when i look at you miley cyrus","4","","",""),
array("we are the world 2010","4","","",""),
array("wisin y yandel","4","","",""),
array("wrestlemania 26","4","","",""),
array("whatcha say jason derulo","4","","",""),
array("waving flag","4","","","")),
"x" => array(
array("xbox 360","0","1","2","3"),
array("xm radio","0","2","3",""),
array("xbox live","0","1","2",""),
array("xanax","0","2","3",""),
array("xbox 720","0","4","",""),
array("xbox","1","3","",""),
array("xbox 360 elite","1","3","",""),
array("xbox 360 games","1","3","",""),
array("xbox cheats","2","3","",""),
array("xs las vegas","0","","",""),
array("xkcd","0","","",""),
array("xtreme couture","0","","",""),
array("x107.5","0","","",""),
array("xradio.biz","0","","",""),
array("xbox 360 console","1","","",""),
array("xbox 360 controller","1","","",""),
array("xbox 360 wireless adapter","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("xbox 360 headset","1","","",""),
array("x games","2","","",""),
array("xvid","2","","",""),
array("x17","2","","",""),
array("xerox","2","","",""),
array("xbox cheat codes","2","","",""),
array("xbox 360 cheats","3","","",""),
array("xbox 360 cheat codes","3","","",""),
array("xbox360","3","","",""),
array("x factor 2009","4","","",""),
array("x factor 2010","4","","",""),
array("xxl movie","4","","",""),
array("x factor","4","","",""),
array("xzibit","4","","",""),
array("xxl tv 18","4","","",""),
array("x factor 2010 danmark","4","","",""),
array("xatzigiannis","4","","","")),
"y" => array(
array("youtube","0","2","3","4"),
array("yahoo mail","0","2","3",""),
array("yellow pages","0","2","3",""),
array("yahoo","0","2","",""),
array("youtube music","0","3","",""),
array("yahoo maps","0","2","",""),
array("yahoo messenger","0","2","",""),
array("young jeezy","1","4","",""),
array("yahoo answers","0","","",""),
array("yahoo finance","0","","",""),
array("ymca las vegas","0","","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yugioh cards","1","","",""),
array("yoga dvd","1","","",""),
array("yo gabba gabba","1","","",""),
array("your baby can read","1","","",""),
array("yugioh","1","","",""),
array("yarn","1","","",""),
array("yogurt maker","1","","",""),
array("youtube video","2","","",""),
array("yahoo games","2","","",""),
array("youtube broadcast yourself","2","","",""),
array("yamaha","2","","",""),
array("youtube videos","3","","",""),
array("yellowpages.com","3","","",""),
array("yellow pages.com","3","","",""),
array("yahoo.com","3","","",""),
array("yellowbook.com","3","","",""),
array("yellow book","3","","",""),
array("you belong with me","4","","",""),
array("young money","4","","",""),
array("you belong with me taylor swift","4","","",""),
array("your a jerk","4","","",""),
array("your love is my drug","4","","",""),
array("young money bedrock","4","","",""),
array("young money roger that","4","","",""),
array("young forever","4","","","")),
"z" => array(
array("zappos","0","2","3",""),
array("zodiac signs","0","2","3",""),
array("zombieland","0","1","4",""),
array("zillow","0","2","",""),
array("zip codes","0","3","",""),
array("zune","1","2","",""),
array("zumba","1","4","",""),
array("zhu zhu pets","1","3","",""),
array("zac brown band","1","4","",""),
array("zales","2","3","",""),
array("zuma","2","3","",""),
array("zip code finder","2","3","",""),
array("zion national park","0","","",""),
array("zip codes by city","0","","",""),
array("zumiez","0","","",""),
array("zumanity","0","","",""),
array("zabasearch","0","","",""),
array("zune hd","1","","",""),
array("zippo","1","","",""),
array("zumba fitness dvd","1","","",""),
array("zumba dvd","1","","",""),
array("zelda","1","","",""),
array("zip code lookup","2","","",""),
array("zedge","2","","",""),
array("zaba","2","","",""),
array("zappos.com","3","","",""),
array("zip code list","3","","",""),
array("zhu zhu","3","","",""),
array("zombie","4","","",""),
array("zz top","4","","",""),
array("zac efron","4","","",""),
array("zach galifianakis","4","","",""),
array("zeljko joksimovic ljubavi","4","","",""),
array("zidane","4","","",""),
array("zeitgeist","4","","","")));
?>