<?php $topResults = array(
"a" => array(
array("aol","0","2","",""),
array("amazon","0","2","",""),
array("apple","0","1","",""),
array("at&t","2","3","",""),
array("amtrak","0","","",""),
array("acme","0","","",""),
array("att","0","","",""),
array("ask.com","0","","",""),
array("aim","0","","",""),
array("abc","0","","",""),
array("addicting games","0","","",""),
array("apple tv","1","","",""),
array("airsoft guns","1","","",""),
array("adidas","1","","",""),
array("avatar","1","","",""),
array("alarm clock","1","","",""),
array("airsoft","1","","",""),
array("apple ipad","1","","",""),
array("arcade fire","1","","",""),
array("asus","1","","",""),
array("ask jeeves","2","","",""),
array("american idol","2","","",""),
array("american airlines","2","","",""),
array("autotrader","2","","",""),
array("american express","2","","",""),
array("angelina jolie","2","","",""),
array("amber tamblyn","2","","",""),
array("abatido","3","","",""),
array("about facebook","3","","",""),
array("afterwards","3","","",""),
array("apartments for rent","3","","",""),
array("airline tickets","3","","",""),
array("att.com","3","","",""),
array("are vampires real","3","","",""),
array("area codes","3","","",""),
array("address search","3","","",""),
array("airplanes","4","","",""),
array("alejandro lady gaga","4","","",""),
array("airplanes b.o.b","4","","",""),
array("annoying orange","4","","",""),
array("akon","4","","",""),
array("alejandro","4","","",""),
array("alicia keys","4","","",""),
array("airplanes hayley williams","4","","",""),
array("avril lavigne","4","","",""),
array("america's got talent 2010","4","","","")),
"b" => array(
array("best buy","0","2","3",""),
array("bed bath and beyond","0","2","3",""),
array("bank of america","0","2","",""),
array("bing","0","3","",""),
array("barnes and noble","0","2","",""),
array("blockbuster","0","2","",""),
array("britney spears","2","4","",""),
array("baby names","2","3","",""),
array("boscovs","0","","",""),
array("borders","0","","",""),
array("bolt bus","0","","",""),
array("borgata","0","","",""),
array("blackberry","1","","",""),
array("blackberry torch","1","","",""),
array("backpack","1","","",""),
array("bluetooth headset","1","","",""),
array("blackberry bold 9700","1","","",""),
array("bose","1","","",""),
array("blackberry unlocked","1","","",""),
array("black ops","1","","",""),
array("boots","1","","",""),
array("blu ray player","1","","",""),
array("betty white","2","","",""),
array("bob barker","2","","",""),
array("blank","2","","",""),
array("barrett jackson","3","","",""),
array("big bang theory full episodes","3","","",""),
array("bones season 6 episode 1","3","","",""),
array("bing.com","3","","",""),
array("bestbuy.com","3","","",""),
array("best buy.com","3","","",""),
array("baby justin bieber","4","","",""),
array("billionaire","4","","",""),
array("beyonce","4","","",""),
array("baby","4","","",""),
array("billionaire travis mccoy","4","","",""),
array("black eyed peas","4","","",""),
array("bad romance","4","","",""),
array("break your heart","4","","",""),
array("bob marley","4","","","")),
"c" => array(
array("craigslist","0","2","",""),
array("cnn","0","2","",""),
array("costco","0","2","",""),
array("chase","0","2","",""),
array("calorie counter","3","4","",""),
array("comcast.net","0","","",""),
array("comcast","0","","",""),
array("cvs","0","","",""),
array("cnet","0","","",""),
array("citizens bank","0","","",""),
array("craigslist philadelphia","0","","",""),
array("call of duty black ops","1","","",""),
array("civilization 5","1","","",""),
array("camera","1","","",""),
array("coffee maker","1","","",""),
array("crocs","1","","",""),
array("canon 7d","1","","",""),
array("cell phone","1","","",""),
array("converse","1","","",""),
array("canon t2i","1","","",""),
array("canon","1","","",""),
array("circuit city","2","","",""),
array("chat","2","","",""),
array("cingular","2","","",""),
array("cartoon network","2","","",""),
array("carmelo anthony","2","","",""),
array("capital one","2","","",""),
array("cabs","3","","",""),
array("caiobaldansanchez","3","","",""),
array("convocado","3","","",""),
array("cheap airline tickets","3","","",""),
array("cash for clunkers","3","","",""),
array("cheap flights","3","","",""),
array("cellular service","3","","",""),
array("car rentals","3","","",""),
array("calculator","3","","",""),
array("california gurls katy perry","4","","",""),
array("chris brown","4","","",""),
array("cooler than me mike posner","4","","",""),
array("chris brown deuces","4","","",""),
array("charlie bit my finger","4","","",""),
array("cooler than me","4","","",""),
array("christina aguilera","4","","",""),
array("california gurls katy perry lyrics","4","","",""),
array("ciara","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("delta airlines","0","2","3",""),
array("droid x","0","1","",""),
array("dell","0","2","",""),
array("drake","0","4","",""),
array("driving directions","2","3","",""),
array("dancing with the stars","2","3","",""),
array("dorney park","0","","",""),
array("dominos","0","","",""),
array("dsw","0","","",""),
array("disney","0","","",""),
array("dutch wonderland","0","","",""),
array("digital camera","1","","",""),
array("diapers","1","","",""),
array("dexter","1","","",""),
array("dsi","1","","",""),
array("dvd player","1","","",""),
array("dead rising 2","1","","",""),
array("dvd","1","","",""),
array("desk","1","","",""),
array("droid","1","","",""),
array("disney channel","2","","",""),
array("dish network","2","","",""),
array("directions","2","","",""),
array("dmv","2","","",""),
array("danica patrick","2","","",""),
array("dns failure","3","","",""),
array("dag","3","","",""),
array("disneychannel.com","3","","",""),
array("does justin bieber have a girlfriend","3","","",""),
array("distance between 2 cities","3","","",""),
array("dictionary.com","3","","",""),
array("dynamite taio cruz","4","","",""),
array("drake find your love","4","","",""),
array("double rainbow","4","","",""),
array("david guetta","4","","",""),
array("dynamite","4","","",""),
array("drake miss me","4","","",""),
array("demi lovato","4","","",""),
array("drake over","4","","",""),
array("deuces chris brown","4","","","")),
"e" => array(
array("eminem","0","1","2","4"),
array("ebay","0","2","3",""),
array("espn","0","2","",""),
array("expedia","0","2","",""),
array("enterprise car rental","2","3","",""),
array("espn3","0","","",""),
array("express","0","","",""),
array("etsy","0","","",""),
array("eagles","0","","",""),
array("ez pass","0","","",""),
array("entourage","0","","",""),
array("external hard drive","1","","",""),
array("eclipse","1","","",""),
array("eat pray love","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("eclipse dvd","1","","",""),
array("ethernet cable","1","","",""),
array("earth","1","","",""),
array("espresso machine","1","","",""),
array("ecards","2","","",""),
array("elizabeth warren","2","","",""),
array("emma stone","2","","",""),
array("elin nordegren","2","","",""),
array("ebay motors","2","","",""),
array("eddie","3","","",""),
array("eddie long","3","","",""),
array("ellen gracie","3","","",""),
array("ebay.com","3","","",""),
array("expedia.com","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("english to spanish translation","3","","",""),
array("engagement rings","3","","",""),
array("eminem not afraid","4","","",""),
array("eminem love the way you lie","4","","",""),
array("enrique iglesias i like it","4","","",""),
array("enrique iglesias","4","","",""),
array("eminem recovery","4","","",""),
array("eminem ft rihanna","4","","",""),
array("eenie meenie justin bieber","4","","",""),
array("eenie meenie","4","","",""),
array("eminem beautiful","4","","","")),
"f" => array(
array("facebook","0","2","3",""),
array("facebook login","0","2","",""),
array("firefox","0","2","",""),
array("food network","0","2","",""),
array("ford","0","2","",""),
array("fox news","0","2","",""),
array("fafsa","0","2","",""),
array("fedex","0","2","",""),
array("free online games","2","3","",""),
array("fandango","0","","",""),
array("flyers","0","","",""),
array("freedom","1","","",""),
array("flash drive","1","","",""),
array("fifa 11","1","","",""),
array("fallout new vegas","1","","",""),
array("food processor","1","","",""),
array("final fantasy xiv","1","","",""),
array("fable 3","1","","",""),
array("fleshlight","1","","",""),
array("futon","1","","",""),
array("fringe","1","","",""),
array("fantasy football","2","","",""),
array("face transplant","3","","",""),
array("facebook isnt working","3","","",""),
array("free ringtones","3","","",""),
array("free music downloads","3","","",""),
array("free games","3","","",""),
array("free people search","3","","",""),
array("find a person","3","","",""),
array("free credit report","3","","",""),
array("funny video","4","","",""),
array("funny","4","","",""),
array("fred","4","","",""),
array("female hair transplant","4","","",""),
array("family guy","4","","",""),
array("funny pranks","4","","",""),
array("funny cats","4","","",""),
array("find your love drake","4","","",""),
array("flip top","4","","",""),
array("fireflies","4","","","")),
"g" => array(
array("glee","0","1","3","4"),
array("google maps","0","2","3",""),
array("games","0","2","3",""),
array("gmail","0","2","",""),
array("google earth","0","2","",""),
array("google","2","4","",""),
array("google search","2","3","",""),
array("google.com","0","","",""),
array("gamestop","0","","",""),
array("gary coleman","0","","",""),
array("geico","0","","",""),
array("giant","0","","",""),
array("gps","1","","",""),
array("garmin","1","","",""),
array("gift card","1","","",""),
array("guitar","1","","",""),
array("garmin gps","1","","",""),
array("garmin nuvi","1","","",""),
array("gran turismo 5","1","","",""),
array("greys anatomy season 6","1","","",""),
array("guess","1","","",""),
array("gwen stefani","2","","",""),
array("google homepage","2","","",""),
array("gold prices","2","","",""),
array("gap","2","","",""),
array("grey s anatomy","3","","",""),
array("gefeliciteerd","3","","",""),
array("google search engine","3","","",""),
array("games.com","3","","",""),
array("girl games","3","","",""),
array("games for kids","3","","",""),
array("gummy bear song","4","","",""),
array("gucci mane","4","","",""),
array("green day","4","","",""),
array("ghost","4","","",""),
array("getting over you david guetta","4","","",""),
array("gorillaz","4","","",""),
array("ghost caught on tape","4","","",""),
array("guns n roses","4","","","")),
"h" => array(
array("hulu","0","2","3",""),
array("home depot","0","2","3",""),
array("hotmail","0","2","",""),
array("honda","0","2","",""),
array("halo reach","1","4","",""),
array("halloween costumes","1","2","",""),
array("halo","1","4","",""),
array("harry potter","1","2","",""),
array("halloween","1","3","",""),
array("how to kiss","3","4","",""),
array("hollister","0","","",""),
array("hershey park","0","","",""),
array("hp","0","","",""),
array("h&m","0","","",""),
array("hbo","0","","",""),
array("hhgregg","0","","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("htc evo","1","","",""),
array("hello kitty","1","","",""),
array("hunger games","1","","",""),
array("heidi montag","2","","",""),
array("horoscopes","2","","",""),
array("holiday inn","2","","",""),
array("harian metro","2","","",""),
array("helen slater","3","","",""),
array("how much should i weigh","3","","",""),
array("how to get pregnant","3","","",""),
array("how do you spell a word","3","","",""),
array("how to make a website","3","","",""),
array("hotmail.com","3","","",""),
array("hey soul sister","4","","",""),
array("hannah montana","4","","",""),
array("harry potter and the deathly hallows trailer","4","","",""),
array("happy tree friends","4","","",""),
array("hello good morning","4","","",""),
array("hannah montana songs","4","","",""),
array("hallelujah","4","","","")),
"i" => array(
array("ipad","0","1","3",""),
array("itunes","0","2","3",""),
array("iphone 4","0","1","4",""),
array("iphone","0","1","2",""),
array("ikea","0","2","",""),
array("imdb","0","2","",""),
array("inception","0","4","",""),
array("irs","0","2","",""),
array("ipod touch","1","3","",""),
array("ipod","1","2","",""),
array("indeed","0","","",""),
array("iron pigs","0","","",""),
array("ipod nano","1","","",""),
array("iphone 4 case","1","","",""),
array("ipod touch 4th generation","1","","",""),
array("iphone 3gs","1","","",""),
array("iron man 2","1","","",""),
array("internet explorer","2","","",""),
array("ihop","2","","",""),
array("imeem","2","","",""),
array("ign","2","","",""),
array("idiot abroad","3","","",""),
array("internal server","3","","",""),
array("itaintgoodsex","3","","",""),
array("is the world going to end in 2012","3","","",""),
array("italy travel","3","","",""),
array("inspirational quotes","3","","",""),
array("internet explorer 8","3","","",""),
array("i love the way you lie","4","","",""),
array("i like it enrique iglesias","4","","",""),
array("i like it","4","","",""),
array("inception trailer","4","","",""),
array("impossible shontelle","4","","",""),
array("i wanna be a billionaire","4","","",""),
array("in my head jason derulo","4","","",""),
array("inna","4","","","")),
"j" => array(
array("justin bieber","0","1","3","4"),
array("jobs","0","2","3",""),
array("jcpenney","0","2","",""),
array("jokes","0","2","",""),
array("jennifer aniston","2","3","",""),
array("jay z","2","4","",""),
array("jersey shore","0","","",""),
array("jeep","0","","",""),
array("java","0","","",""),
array("jcrew","0","","",""),
array("jet blue","0","","",""),
array("josef frank","0","","",""),
array("jansport backpack","1","","",""),
array("jillian michaels","1","","",""),
array("juicer","1","","",""),
array("juicy couture","1","","",""),
array("jewelry box","1","","",""),
array("jonathan franzen","1","","",""),
array("james patterson","1","","",""),
array("jack3d","1","","",""),
array("jewelry","1","","",""),
array("jennifer grey","2","","",""),
array("jessica simpson","2","","",""),
array("jessica alba","2","","",""),
array("jennifer lopez","2","","",""),
array("jennifer love hewitt","2","","",""),
array("justin bieber on csi","3","","",""),
array("jodie foster","3","","",""),
array("jobs in my area","3","","",""),
array("justin bieber cell number","3","","",""),
array("job search","3","","",""),
array("jcpenney.com","3","","",""),
array("justin bieber quiz","3","","",""),
array("justin bieber baby","4","","",""),
array("justin bieber eenie meenie","4","","",""),
array("justin bieber one time","4","","",""),
array("justin bieber somebody to love","4","","",""),
array("justin bieber never say never","4","","",""),
array("jason derulo ridin solo","4","","",""),
array("justin bieber love me","4","","",""),
array("justin timberlake","4","","","")),
"k" => array(
array("kmart","0","2","3",""),
array("katy perry","0","1","4",""),
array("kohls","0","3","",""),
array("kindle","0","1","",""),
array("kim kardashian","2","3","",""),
array("king of prussia mall","0","","",""),
array("knoebels","0","","",""),
array("kesha","0","","",""),
array("kayak","0","","",""),
array("kfc","0","","",""),
array("kia","0","","",""),
array("kindle cover","1","","",""),
array("keurig","1","","",""),
array("kinect","1","","",""),
array("k cups","1","","",""),
array("kindle books","1","","",""),
array("keyboard","1","","",""),
array("kingdom hearts","1","","",""),
array("kindle dx","1","","",""),
array("kelly mcgillis","2","","",""),
array("kelley blue book","2","","",""),
array("kohl's","2","","",""),
array("kate walsh","2","","",""),
array("kid rock","2","","",""),
array("kate winslet","2","","",""),
array("kelly clarkson","2","","",""),
array("kristen stewart","2","","",""),
array("keeping up with the kardashians","3","","",""),
array("kevin costner","3","","",""),
array("kohls.com","3","","",""),
array("kelly blue book","3","","",""),
array("kmart.com","3","","",""),
array("kids games","3","","",""),
array("kijiji","3","","",""),
array("katy perry california girlz","4","","",""),
array("katy perry california","4","","",""),
array("keong racun","4","","",""),
array("kesha your love is my drug","4","","",""),
array("kiss","4","","",""),
array("kid cudi","4","","",""),
array("kanye west power","4","","",""),
array("kanye west","4","","",""),
array("katy perry teenage dream","4","","","")),
"l" => array(
array("lady gaga","0","1","2","4"),
array("lost","0","1","2",""),
array("lyrics","0","2","3",""),
array("love quotes","0","2","3",""),
array("lowes","0","3","",""),
array("limewire","0","2","",""),
array("linkin park","1","4","",""),
array("love poems","2","3","",""),
array("linkedin","0","","",""),
array("lands end","0","","",""),
array("la fitness","0","","",""),
array("longwood gardens","0","","",""),
array("laptop","1","","",""),
array("lego","1","","",""),
array("luggage","1","","",""),
array("lego star wars","1","","",""),
array("laptop computer","1","","",""),
array("lost season 6","1","","",""),
array("lcd tv","1","","",""),
array("lindsay lohan","2","","",""),
array("lowe's","2","","",""),
array("las vegas","2","","",""),
array("lynyrd skynyrd","2","","",""),
array("late night","3","","",""),
array("letterman","3","","",""),
array("lightning","3","","",""),
array("lyrics to songs","3","","",""),
array("lowes.com","3","","",""),
array("lingerie","3","","",""),
array("love the way you lie","4","","",""),
array("lady gaga alejandro","4","","",""),
array("lil wayne","4","","",""),
array("love the way you lie eminem","4","","",""),
array("loan mods","4","","",""),
array("lady gaga bad romance","4","","",""),
array("love the way you lie lyrics","4","","",""),
array("love","4","","","")),
"m" => array(
array("maps","0","2","3",""),
array("mapquest","0","2","",""),
array("myspace","0","2","",""),
array("msn","0","2","",""),
array("movies","0","2","",""),
array("macy's","0","2","",""),
array("music","2","4","",""),
array("mapquest driving directions","2","3","",""),
array("mlb","0","","",""),
array("mtv","0","","",""),
array("msnbc","0","","",""),
array("michaels","0","","",""),
array("macbook","1","","",""),
array("mouse","1","","",""),
array("macbook pro","1","","",""),
array("mp3 player","1","","",""),
array("mockingjay","1","","",""),
array("madden 11","1","","",""),
array("micro sd","1","","",""),
array("mad men","1","","",""),
array("modern family","1","","",""),
array("maroon 5","1","","",""),
array("mail","2","","",""),
array("miniclip","2","","",""),
array("mindy cohn","3","","",""),
array("my generation tv show","3","","",""),
array("my generation","3","","",""),
array("myspace layouts","3","","",""),
array("mortgage calculator","3","","",""),
array("medical dictionary","3","","",""),
array("math answers","3","","",""),
array("meaning of names","3","","",""),
array("michael jackson","4","","",""),
array("miley cyrus","4","","",""),
array("my wife having an affair","4","","",""),
array("mariah carey","4","","",""),
array("my first kiss","4","","",""),
array("miley cyrus can't be tamed","4","","",""),
array("metallica","4","","",""),
array("magic b.o.b","4","","",""),
array("miley cyrus party in the usa","4","","","")),
"n" => array(
array("netflix","0","2","3",""),
array("nfl","0","2","3",""),
array("nissan","0","2","3",""),
array("news","0","3","",""),
array("nbc","0","2","",""),
array("nokia","1","2","",""),
array("nj transit","0","","",""),
array("nhl","0","","",""),
array("nj lottery","0","","",""),
array("nj dmv","0","","",""),
array("new york times","0","","",""),
array("netbook","1","","",""),
array("nintendo ds","1","","",""),
array("nikon d90","1","","",""),
array("nike","1","","",""),
array("nook","1","","",""),
array("nintendo dsi","1","","",""),
array("nikon d5000","1","","",""),
array("nokia n8","1","","",""),
array("nikon d7000","1","","",""),
array("nicole kidman","2","","",""),
array("nick jr","2","","",""),
array("nascar","2","","",""),
array("nordstrom","2","","",""),
array("nba","2","","",""),
array("nicole richie","3","","",""),
array("nederlands","3","","",""),
array("name meanings","3","","",""),
array("netflix.com","3","","",""),
array("nudyphotos","3","","",""),
array("nissan.com","3","","",""),
array("not afraid eminem","4","","",""),
array("nicki minaj","4","","",""),
array("never say never","4","","",""),
array("never say never justin bieber","4","","",""),
array("nicki minaj your love","4","","",""),
array("nigahiga","4","","",""),
array("not afraid","4","","",""),
array("new songs 2010","4","","",""),
array("nickelback","4","","",""),
array("nothing on you b.o.b","4","","","")),
"o" => array(
array("old navy","0","2","3",""),
array("orbitz","0","2","",""),
array("overstock","0","2","",""),
array("olive garden","0","2","",""),
array("office depot","0","2","",""),
array("oprah","0","2","",""),
array("online dictionary","2","3","",""),
array("online games","2","3","",""),
array("omg","2","4","",""),
array("oovoo","0","","",""),
array("ocean city nj","0","","",""),
array("oil spill","0","","",""),
array("omegle","0","","",""),
array("oakley","1","","",""),
array("otterbox","1","","",""),
array("otterbox iphone 4","1","","",""),
array("oakley sunglasses","1","","",""),
array("office 2010","1","","",""),
array("one tree hill","1","","",""),
array("office chair","1","","",""),
array("ooma","1","","",""),
array("opi nail polish","1","","",""),
array("oakley sunglasses for men","1","","",""),
array("orkut","2","","",""),
array("outsourced","3","","",""),
array("outsourced nbc","3","","",""),
array("onweer","3","","",""),
array("online pregnancy test","3","","",""),
array("ovulation calendar","3","","",""),
array("ovulation calculator","3","","",""),
array("overstock.com","3","","",""),
array("omg usher","4","","",""),
array("oil rig employment","4","","",""),
array("old spice commercial","4","","",""),
array("old spice","4","","",""),
array("one time justin bieber","4","","",""),
array("one time","4","","",""),
array("over drake","4","","",""),
array("ordinary girl-hannah montana","4","","",""),
array("once upon a time in mumbai","4","","","")),
"p" => array(
array("powerball","0","2","",""),
array("paypal","0","2","",""),
array("people search","2","3","",""),
array("phillies","0","","",""),
array("pandora","0","","",""),
array("peco","0","","",""),
array("penndot","0","","",""),
array("pa lottery","0","","",""),
array("philadelphia zoo","0","","",""),
array("pnc bank","0","","",""),
array("philadelphia union","0","","",""),
array("ps3","1","","",""),
array("playstation 3","1","","",""),
array("psp","1","","",""),
array("playstation move","1","","",""),
array("p90x","1","","",""),
array("pillow pets","1","","",""),
array("posters","1","","",""),
array("ps3 console","1","","",""),
array("ps3 games","1","","",""),
array("ps3 move","1","","",""),
array("photobucket","2","","",""),
array("pizza hut","2","","",""),
array("pogo","2","","",""),
array("priceline","2","","",""),
array("people magazine","2","","",""),
array("pottery barn","2","","",""),
array("petsmart","2","","",""),
array("parks and recreation","3","","",""),
array("pandora radio","3","","",""),
array("private practice","3","","",""),
array("pregnancy week by week","3","","",""),
array("priceline.com","3","","",""),
array("people finder","3","","",""),
array("phone number lookup","3","","",""),
array("people search for free","3","","",""),
array("pregnancy symptoms","3","","",""),
array("paramore","4","","",""),
array("pretty boy swag","4","","",""),
array("pitbull","4","","",""),
array("pyramid charice","4","","",""),
array("pink","4","","",""),
array("party in the usa","4","","",""),
array("pretty boy swag soulja boy","4","","",""),
array("pyramid","4","","",""),
array("poker face","4","","",""),
array("pokemon","4","","","")),
"q" => array(
array("quotes","0","2","3",""),
array("quickbooks","1","2","3",""),
array("qvc","0","2","",""),
array("quest diagnostics","0","2","",""),
array("quicktime","0","2","",""),
array("quotes about life","0","3","",""),
array("quiznos","0","2","",""),
array("quran","1","4","",""),
array("queen","1","4","",""),
array("quizzes","2","3","",""),
array("q102","0","","",""),
array("qdoba","0","","",""),
array("quotes about love","0","","",""),
array("quinoa","0","","",""),
array("quicken","1","","",""),
array("quickbooks pro 2010","1","","",""),
array("quiksilver","1","","",""),
array("quilt","1","","",""),
array("quicksilver","1","","",""),
array("queen mattress","1","","",""),
array("queer as folk","1","","",""),
array("qwest","2","","",""),
array("query string","2","","",""),
array("quizilla","2","","",""),
array("quotes of the day","3","","",""),
array("quotes and sayings","3","","",""),
array("quinceanera dresses","3","","",""),
array("quick mileage city to city","3","","",""),
array("questions to ask your boyfriend","3","","",""),
array("qvc home shopping","3","","",""),
array("queen bohemian rhapsody","4","","",""),
array("quest crew","4","","",""),
array("queen we will rock you","4","","",""),
array("queen don't stop me now","4","","",""),
array("queens of the stone age","4","","",""),
array("queen i want to break free","4","","",""),
array("queen somebody to love","4","","",""),
array("queen seondeok","4","","","")),
"e" => array(
array("eminem","0","1","2","4"),
array("ebay","0","2","3",""),
array("espn","0","2","",""),
array("expedia","0","2","",""),
array("enterprise car rental","2","3","",""),
array("espn3","0","","",""),
array("express","0","","",""),
array("etsy","0","","",""),
array("eagles","0","","",""),
array("ez pass","0","","",""),
array("entourage","0","","",""),
array("external hard drive","1","","",""),
array("eclipse","1","","",""),
array("eat pray love","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("eclipse dvd","1","","",""),
array("ethernet cable","1","","",""),
array("earth","1","","",""),
array("espresso machine","1","","",""),
array("ecards","2","","",""),
array("elizabeth warren","2","","",""),
array("emma stone","2","","",""),
array("elin nordegren","2","","",""),
array("ebay motors","2","","",""),
array("eddie","3","","",""),
array("eddie long","3","","",""),
array("ellen gracie","3","","",""),
array("ebay.com","3","","",""),
array("expedia.com","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("english to spanish translation","3","","",""),
array("engagement rings","3","","",""),
array("eminem not afraid","4","","",""),
array("eminem love the way you lie","4","","",""),
array("enrique iglesias i like it","4","","",""),
array("enrique iglesias","4","","",""),
array("eminem recovery","4","","",""),
array("eminem ft rihanna","4","","",""),
array("eenie meenie justin bieber","4","","",""),
array("eenie meenie","4","","",""),
array("eminem beautiful","4","","","")),
"s" => array(
array("southwest airlines","0","2","3",""),
array("sears","0","2","",""),
array("staples","0","2","",""),
array("skype","0","2","",""),
array("sprint","0","2","",""),
array("song lyrics","2","3","",""),
array("selena gomez","2","4","",""),
array("shakira","2","4","",""),
array("septa","0","","",""),
array("shoprite","0","","",""),
array("subway","0","","",""),
array("six flags","0","","",""),
array("sesame place","0","","",""),
array("starcraft 2","1","","",""),
array("silly bandz","1","","",""),
array("shoes","1","","",""),
array("scott pilgrim","1","","",""),
array("sunglasses","1","","",""),
array("star wars","1","","",""),
array("sd card","1","","",""),
array("samsung vibrant","1","","",""),
array("samsung captivate","1","","",""),
array("supernatural","1","","",""),
array("sophia loren","2","","",""),
array("sandra bullock","2","","",""),
array("sara evans","3","","",""),
array("similac","3","","",""),
array("steven tyler","3","","",""),
array("spanish dictionary","3","","",""),
array("signs of pregnancy","3","","",""),
array("sexy","3","","",""),
array("swine flu symptoms","3","","",""),
array("spanish translator","3","","",""),
array("shakira waka waka","4","","",""),
array("solo","4","","",""),
array("somebody to love justin bieber","4","","",""),
array("sexist video of man and woman","4","","",""),
array("solo iyaz","4","","",""),
array("shane dawson","4","","",""),
array("soulja boy","4","","",""),
array("stereo love","4","","","")),
"t" => array(
array("target","0","2","",""),
array("tmz","0","2","",""),
array("ticketmaster","0","2","",""),
array("true blood","0","1","",""),
array("travelocity","0","2","",""),
array("toy story 3","1","4","",""),
array("trey songz","1","4","",""),
array("the office","1","3","",""),
array("taylor swift","2","4","",""),
array("td bank","0","","",""),
array("twitter","0","","",""),
array("translator","0","","",""),
array("tmobile","0","","",""),
array("thesaurus","0","","",""),
array("twilight","1","","",""),
array("tv","1","","",""),
array("the girl with the dragon tattoo","1","","",""),
array("toy story","1","","",""),
array("the help","1","","",""),
array("the hunger games","1","","",""),
array("toys r us","2","","",""),
array("toyota","2","","",""),
array("tagged","2","","",""),
array("t-mobile","2","","",""),
array("tiger woods","2","","",""),
array("teresa lewis execution","3","","",""),
array("the office season 7","3","","",""),
array("tattoo designs","3","","",""),
array("tattoos","3","","",""),
array("translate english to spanish","3","","",""),
array("teen pregnancy signs","3","","",""),
array("translate spanish to english","3","","",""),
array("telephone directory","3","","",""),
array("tires","3","","",""),
array("teach me how to dougie","4","","",""),
array("teenage dream katy perry","4","","",""),
array("tik tok","4","","",""),
array("taio cruz dynamite","4","","",""),
array("the annoying orange","4","","",""),
array("tom and jerry","4","","",""),
array("teenage dream","4","","","")),
"u" => array(
array("us airways","0","2","3",""),
array("ufc","0","2","4",""),
array("united airlines","0","2","3",""),
array("usps","0","2","",""),
array("ups","0","2","",""),
array("usher","1","4","",""),
array("used cars","2","3","",""),
array("utube","0","","",""),
array("urban outfitters","0","","",""),
array("uhaul","0","","",""),
array("ups tracking","0","","",""),
array("urban dictionary","0","","",""),
array("unlocked cell phones","1","","",""),
array("usb flash drive","1","","",""),
array("usb hub","1","","",""),
array("uggs","1","","",""),
array("umbrella","1","","",""),
array("under armour","1","","",""),
array("undefined","1","","",""),
array("ugg boots","1","","",""),
array("uncharted 2","1","","",""),
array("us bank","2","","",""),
array("univision","2","","",""),
array("utusan malaysia","2","","",""),
array("usaa","2","","",""),
array("uniqlo lucky line","3","","",""),
array("used cars for sale","3","","",""),
array("unique baby names","3","","",""),
array("unemployment benefits","3","","",""),
array("us airways.com","3","","",""),
array("used cars for sale in my area","3","","",""),
array("usairways.com","3","","",""),
array("usher omg","4","","",""),
array("usher there goes my baby","4","","",""),
array("u2","4","","",""),
array("unthinkable alicia keys","4","","",""),
array("ufo","4","","",""),
array("usher daddy's home","4","","",""),
array("usher yeah","4","","",""),
array("up all night drake nicki minaj","4","","","")),
"v" => array(
array("verizon","0","2","3",""),
array("verizon wireless","0","2","3",""),
array("vh1","0","2","",""),
array("vampire diaries","1","3","",""),
array("verizon cell phones","1","3","",""),
array("victoria's secret","1","2","",""),
array("vanessa hudgens","2","4","",""),
array("verizon.net","0","","",""),
array("victoria secret","0","","",""),
array("verizon email","0","","",""),
array("vanguard","0","","",""),
array("verizon fios","0","","",""),
array("villanova","0","","",""),
array("vuvuzela","0","","",""),
array("vacuum cleaner","1","","",""),
array("vera bradley","1","","",""),
array("vans","1","","",""),
array("video camera","1","","",""),
array("vacuum","1","","",""),
array("vibratores for women","1","","",""),
array("vibram five fingers","1","","",""),
array("vanilla ice","2","","",""),
array("video","2","","",""),
array("victoria beckham","2","","",""),
array("virgin mobile","2","","",""),
array("vonage","2","","",""),
array("virginia execution","3","","",""),
array("verdict","3","","",""),
array("verizon.com","3","","",""),
array("verizonwireless.com","3","","",""),
array("virtual worlds","3","","",""),
array("very early symptoms of pregnancy","3","","",""),
array("vevo","4","","",""),
array("vybz kartel","4","","",""),
array("vanilla twilight","4","","",""),
array("vicente fernandez","4","","",""),
array("vampire weekend","4","","",""),
array("videos grasiosos","4","","",""),
array("van halen","4","","",""),
array("vanilla twilight owl city","4","","",""),
array("victorious","4","","","")),
"w" => array(
array("weather","0","2","3",""),
array("white pages","0","2","3",""),
array("wachovia","0","2","",""),
array("wikipedia","0","2","",""),
array("webmd","0","2","",""),
array("wwe","2","4","",""),
array("walmart","0","","",""),
array("www.facebook.com","0","","",""),
array("wawa","0","","",""),
array("web md","0","","",""),
array("wegmans","0","","",""),
array("wii","1","","",""),
array("wireless router","1","","",""),
array("watches","1","","",""),
array("windows 7","1","","",""),
array("wii games","1","","",""),
array("webcam","1","","",""),
array("wii console","1","","",""),
array("world of warcraft","1","","",""),
array("wireless mouse","1","","",""),
array("wallet","1","","",""),
array("wal mart","2","","",""),
array("wells fargo","2","","",""),
array("webkinz","2","","",""),
array("walgreens","2","","",""),
array("what channel is cbs","3","","",""),
array("what channel is csi on","3","","",""),
array("william shatner","3","","",""),
array("what does my last name mean","3","","",""),
array("where can i watch free movies online","3","","",""),
array("what is love","3","","",""),
array("what is the meaning of my name","3","","",""),
array("when will the world end","3","","",""),
array("waka waka","4","","",""),
array("waka waka shakira","4","","",""),
array("we no speak americano","4","","",""),
array("waving flag","4","","",""),
array("wisin y yandel","4","","",""),
array("wiz khalifa","4","","",""),
array("waving flag k'naan","4","","",""),
array("what if jason derulo","4","","",""),
array("waka flocka flames","4","","","")),
"x" => array(
array("xbox 360","1","2","3","4"),
array("xm radio","0","2","3",""),
array("xbox live","0","1","2",""),
array("xbox","0","1","",""),
array("xanax","0","2","",""),
array("xbox 360 slim","1","4","",""),
array("xbox 360 games","1","3","",""),
array("xbox cheats","2","3","",""),
array("x factor","2","4","",""),
array("xtu","0","","",""),
array("xkcd","0","","",""),
array("xpn","0","","",""),
array("xfinity","0","","",""),
array("xanga","0","","",""),
array("xanga quotes","0","","",""),
array("xbox 360 console","1","","",""),
array("xbox 360 controller","1","","",""),
array("xbox 360 wireless adapter","1","","",""),
array("xbox live 12 month","1","","",""),
array("xbox 360 elite","1","","",""),
array("x games","2","","",""),
array("xvid","2","","",""),
array("x17","2","","",""),
array("xerox","2","","",""),
array("xbox 360 cheats","3","","",""),
array("x ray schools","3","","",""),
array("xbox 360 cheat codes","3","","",""),
array("xxl tv live","3","","",""),
array("xbox 360 problems","3","","",""),
array("xm satellite radio","3","","",""),
array("xb gensan","4","","",""),
array("x factor 2010","4","","",""),
array("xzibit","4","","",""),
array("x","4","","",""),
array("xb gensan in show time","4","","",""),
array("x games 2010","4","","",""),
array("xbox 360 kinect","4","","","")),
"y" => array(
array("youtube","0","2","3","4"),
array("yahoo mail","0","2","3",""),
array("yellow pages","0","2","3",""),
array("yahoo","0","2","",""),
array("yahoo maps","0","2","",""),
array("young jeezy","1","4","",""),
array("y8","0","","",""),
array("ymca","0","","",""),
array("yahoo finance","0","","",""),
array("yahoo answers","0","","",""),
array("yahoomail.com","0","","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yo gabba gabba","1","","",""),
array("yoga dvd","1","","",""),
array("yugioh cards","1","","",""),
array("your baby can read","1","","",""),
array("yarn","1","","",""),
array("yugioh","1","","",""),
array("yankee candle","1","","",""),
array("youtube video","2","","",""),
array("yahoo messenger","2","","",""),
array("you","2","","",""),
array("youtube broadcast yourself","2","","",""),
array("yahoo games","2","","",""),
array("youtube videos","3","","",""),
array("yellowpages.com","3","","",""),
array("yellow pages.com","3","","",""),
array("yahoo.com","3","","",""),
array("youtube music","3","","",""),
array("youtube music videos","3","","",""),
array("yahoo.com email","3","","",""),
array("your love nicki minaj","4","","",""),
array("your love is my drug","4","","",""),
array("your love","4","","",""),
array("your love is my drug kesha","4","","",""),
array("you belong with me","4","","",""),
array("young money","4","","",""),
array("yolanda be cool we no speak americano","4","","",""),
array("you belong with me taylor swift","4","","","")),
"z" => array(
array("zip codes","0","2","3",""),
array("zumba","0","1","4",""),
array("zune","0","1","2",""),
array("zodiac signs","0","2","3",""),
array("zac brown band","0","1","4",""),
array("zillow","0","2","",""),
array("zappos","0","2","",""),
array("zales","0","2","",""),
array("zip code lookup","2","3","",""),
array("zac efron","2","4","",""),
array("zip code finder","2","3","",""),
array("zumiez","0","","",""),
array("zoosk","0","","",""),
array("zune hd","1","","",""),
array("zippo","1","","",""),
array("zhu zhu pets","1","","",""),
array("zumba fitness dvd","1","","",""),
array("zumba dvd","1","","",""),
array("zelda","1","","",""),
array("zoobles","1","","",""),
array("zuma","2","","",""),
array("zaterdag","3","","",""),
array("zuckerberg","3","","",""),
array("zana marjanovic","3","","",""),
array("zip code list","3","","",""),
array("zucchini bread recipes","3","","",""),
array("zucchini recipes","3","","",""),
array("zombie","4","","",""),
array("zombie cranberries","4","","",""),
array("zz top","4","","",""),
array("zidane","4","","",""),
array("zach galifianakis","4","","",""),
array("zzirgrizz","4","","",""),
array("zombieland","4","","","")));
?>