<?php $topResults = array(
"a" => array(
array("amazon","0","2","",""),
array("aol","0","2","",""),
array("american airlines","0","2","",""),
array("apple","0","1","",""),
array("adele","1","4","",""),
array("allegiant air","0","","",""),
array("att","0","","",""),
array("addicting games","0","","",""),
array("autozone","0","","",""),
array("aol mail","0","","",""),
array("auto trader","0","","",""),
array("airsoft guns","1","","",""),
array("asus transformer","1","","",""),
array("adidas","1","","",""),
array("apple tv","1","","",""),
array("angry birds","1","","",""),
array("alarm clock","1","","",""),
array("android tablet","1","","",""),
array("amazon mom","1","","",""),
array("apple rumors","2","","",""),
array("at&t","2","","",""),
array("anne hathaway","2","","",""),
array("autotrader","2","","",""),
array("aaliyah","2","","",""),
array("american idol","2","","",""),
array("ask jeeves","2","","",""),
array("aesop","3","","",""),
array("arsenal transfer news","3","","",""),
array("airline baby ban","3","","",""),
array("apartments for rent","3","","",""),
array("answers.com","3","","",""),
array("airline tickets","3","","",""),
array("are vampires real","3","","",""),
array("apple store","3","","",""),
array("am i pregnant quiz","3","","",""),
array("amazon.com","3","","",""),
array("amy winehouse","4","","",""),
array("adele rolling in the deep","4","","",""),
array("adele someone like you","4","","",""),
array("annoying orange","4","","",""),
array("amy winehouse rehab","4","","",""),
array("avril lavigne","4","","",""),
array("akon","4","","",""),
array("adele set fire to the rain","4","","",""),
array("amy winehouse dead","4","","","")),
"b" => array(
array("bank of america","0","2","3",""),
array("best buy","0","2","3",""),
array("bed bath and beyond","0","2","3",""),
array("barnes and noble","0","2","",""),
array("britney spears","2","4","",""),
array("bing","2","3","",""),
array("borders","0","","",""),
array("big 5","0","","",""),
array("blockbuster","0","","",""),
array("bellagio","0","","",""),
array("big lots","0","","",""),
array("backpage","0","","",""),
array("blackberry","1","","",""),
array("backpack","1","","",""),
array("beats by dre","1","","",""),
array("battlefield 3","1","","",""),
array("blackberry torch","1","","",""),
array("bose","1","","",""),
array("bluetooth headset","1","","",""),
array("blackberry unlocked","1","","",""),
array("blackberry 9900","1","","",""),
array("blender","1","","",""),
array("blank","2","","",""),
array("billy ray cyrus","2","","",""),
array("brenda song","2","","",""),
array("big brother","2","","",""),
array("bereavement","3","","",""),
array("basketball","3","","",""),
array("brian austin green","3","","",""),
array("baby names","3","","",""),
array("bmi calculator","3","","",""),
array("baby names and meanings","3","","",""),
array("beyonce","4","","",""),
array("bruno mars lazy song","4","","",""),
array("beyonce best thing i never had","4","","",""),
array("bruno mars","4","","",""),
array("black and yellow wiz khalifa","4","","",""),
array("beyonce run the world","4","","",""),
array("baby justin bieber","4","","",""),
array("black eyed peas","4","","",""),
array("best thing i never had","4","","","")),
"c" => array(
array("craigslist","0","2","3",""),
array("chase","0","2","",""),
array("costco","0","2","",""),
array("cnn","0","2","",""),
array("capital one","2","3","",""),
array("christina aguilera","2","4","",""),
array("craigslist las vegas","0","","",""),
array("csn","0","","",""),
array("ccsd","0","","",""),
array("carmax","0","","",""),
array("clark county assessor","0","","",""),
array("cox","0","","",""),
array("camera","1","","",""),
array("crocs","1","","",""),
array("coffee maker","1","","",""),
array("cell phone","1","","",""),
array("canon 60d","1","","",""),
array("canon","1","","",""),
array("converse","1","","",""),
array("canon 7d","1","","",""),
array("computer speakers","1","","",""),
array("call of duty black ops","1","","",""),
array("colorado quake","2","","",""),
array("cartoon network","2","","",""),
array("comcast","2","","",""),
array("condoleezza rice","2","","",""),
array("chick fil a","3","","",""),
array("casey anthony","3","","",""),
array("chris hansen","3","","",""),
array("cheap airline tickets","3","","",""),
array("calculator","3","","",""),
array("cheap flights","3","","",""),
array("calorie counter","3","","",""),
array("currency converter","3","","",""),
array("chris brown","4","","",""),
array("california king bed","4","","",""),
array("chris brown look at me now","4","","",""),
array("cat daddy","4","","",""),
array("chris brown she aint you","4","","",""),
array("champagne showers lmfao","4","","",""),
array("charlie bit my finger","4","","",""),
array("cher lloyd swagger jagger","4","","",""),
array("coldplay","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("disney channel","0","2","",""),
array("delta airlines","2","3","",""),
array("driving directions","2","3","",""),
array("delta","0","","",""),
array("dmv nevada","0","","",""),
array("dominos","0","","",""),
array("dmv","0","","",""),
array("dillards","0","","",""),
array("disneyland","0","","",""),
array("direct tv","0","","",""),
array("disney","0","","",""),
array("deus ex","1","","",""),
array("digital camera","1","","",""),
array("dexter","1","","",""),
array("diapers","1","","",""),
array("deus ex human revolution","1","","",""),
array("desk","1","","",""),
array("dexter season 5","1","","",""),
array("dvd player","1","","",""),
array("doctor who","1","","",""),
array("dead island","1","","",""),
array("dakota fanning","2","","",""),
array("dallas cowboys preseason 2011","2","","",""),
array("danica patrick","2","","",""),
array("dancing with the stars","2","","",""),
array("dell","2","","",""),
array("dish network","2","","",""),
array("district 9","3","","",""),
array("drop dead diva","3","","",""),
array("david bentley","3","","",""),
array("does justin bieber have a girlfriend","3","","",""),
array("definitions.com","3","","",""),
array("dictionary online","3","","",""),
array("disneychannel.com","3","","",""),
array("drake","4","","",""),
array("dubstep","4","","",""),
array("drake marvin's room","4","","",""),
array("david guetta","4","","",""),
array("demi lovato skyscraper","4","","",""),
array("dirt road anthem jason aldean","4","","",""),
array("danza kuduro","4","","",""),
array("don omar danza kuduro","4","","",""),
array("dynamite taio cruz","4","","",""),
array("demi lovato","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("espn","0","2","",""),
array("eminem","1","4","",""),
array("enterprise car rental","2","3","",""),
array("edc","0","","",""),
array("etsy","0","","",""),
array("enterprise","0","","",""),
array("edc las vegas","0","","",""),
array("eppicard","0","","",""),
array("earthquake","0","","",""),
array("ebay motors","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("ethernet cable","1","","",""),
array("espresso machine","1","","",""),
array("electronic cigarette","1","","",""),
array("ebooks","1","","",""),
array("external hard drive 1tb","1","","",""),
array("earrings","1","","",""),
array("emma stone","2","","",""),
array("elizabeth banks","2","","",""),
array("eva marie saint","2","","",""),
array("elin nordegren","2","","",""),
array("eva longoria","2","","",""),
array("earl bradley","2","","",""),
array("edu","3","","",""),
array("eras","3","","",""),
array("emma watson","3","","",""),
array("expedia.com","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("extreme couponing","3","","",""),
array("eminem space bound","4","","",""),
array("enrique iglesias","4","","",""),
array("eminem not afraid","4","","",""),
array("epicmealtime","4","","",""),
array("epic rap battles of history","4","","",""),
array("et katty perry","4","","",""),
array("eminem lose yourself","4","","",""),
array("everyday im shuffling","4","","",""),
array("edge of glory lady gaga","4","","","")),
"f" => array(
array("facebook","0","2","3","4"),
array("firefox","0","2","",""),
array("food network","0","2","",""),
array("fox news","0","2","",""),
array("free online games","2","3","",""),
array("free music downloads","2","3","",""),
array("fandango","0","","",""),
array("facebook login","0","","",""),
array("frys","0","","",""),
array("forever 21","0","","",""),
array("fafsa","0","","",""),
array("frontier airlines","0","","",""),
array("flash drive","1","","",""),
array("flashlight","1","","",""),
array("fifa 12","1","","",""),
array("fan","1","","",""),
array("futon","1","","",""),
array("free kindle books","1","","",""),
array("fast five","1","","",""),
array("food processor","1","","",""),
array("feather hair extension","1","","",""),
array("floor lamp","1","","",""),
array("fedex","2","","",""),
array("ford","2","","",""),
array("fantasy football","2","","",""),
array("faith hill barbie","2","","",""),
array("football game","3","","",""),
array("fresh tomatoes","3","","",""),
array("free ringtones","3","","",""),
array("free games","3","","",""),
array("free credit report","3","","",""),
array("find a person","3","","",""),
array("first name meanings","3","","",""),
array("friday rebecca black","4","","",""),
array("funny video","4","","",""),
array("friday","4","","",""),
array("funny","4","","",""),
array("funny pranks","4","","",""),
array("fred","4","","",""),
array("firework katy perry","4","","",""),
array("freddiew","4","","",""),
array("funny cats","4","","","")),
"g" => array(
array("google","0","2","3","4"),
array("google maps","0","2","3",""),
array("games","0","2","3",""),
array("gmail","0","2","",""),
array("glee","1","4","",""),
array("google search","2","3","",""),
array("google translate","0","","",""),
array("google plus","0","","",""),
array("green valley ranch","0","","",""),
array("google earth","0","","",""),
array("gamestop","0","","",""),
array("groupon","0","","",""),
array("gps","1","","",""),
array("generator","1","","",""),
array("game of thrones","1","","",""),
array("gears of war 3","1","","",""),
array("galaxy tab 10.1","1","","",""),
array("garmin","1","","",""),
array("gift card","1","","",""),
array("galaxy tab","1","","",""),
array("guitar","1","","",""),
array("goo","2","","",""),
array("glenn beck israel","2","","",""),
array("george michael","2","","",""),
array("gap","2","","",""),
array("gisele bundchen","2","","",""),
array("goodbye august","3","","",""),
array("georgie thompson","3","","",""),
array("goggle maps","3","","",""),
array("google.com","3","","",""),
array("google search engine","3","","",""),
array("gnc","3","","",""),
array("give me everything pitbull","4","","",""),
array("grenade bruno mars","4","","",""),
array("good life one republic","4","","",""),
array("gucci gucci","4","","",""),
array("gummy bear song","4","","",""),
array("give me everything tonight pitbull ft. ne-yo afrojack & nayer","4","","",""),
array("give me everything","4","","",""),
array("gucci gucci kreayshawn","4","","","")),
"h" => array(
array("home depot","0","2","3",""),
array("hotmail","0","2","",""),
array("hulu","0","2","",""),
array("harry potter","0","1","",""),
array("how to kiss","3","4","",""),
array("h&m","0","","",""),
array("hollister","0","","",""),
array("hotels.com","0","","",""),
array("hoover dam","0","","",""),
array("house of blues las vegas","0","","",""),
array("hertz","0","","",""),
array("hp touchpad","1","","",""),
array("hp tablet","1","","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("hp touchpad case","1","","",""),
array("hunger games","1","","",""),
array("hello kitty","1","","",""),
array("htc sensation","1","","",""),
array("htc","1","","",""),
array("hurricane irene 2011","2","","",""),
array("halle berry","2","","",""),
array("how to tie a tie","2","","",""),
array("heidi montag","2","","",""),
array("hi5","2","","",""),
array("honda","2","","",""),
array("harian metro","2","","",""),
array("how to draw","3","","",""),
array("haley joel osment","3","","",""),
array("hello september","3","","",""),
array("how much should i weigh","3","","",""),
array("how to get pregnant","3","","",""),
array("how many calories should i eat a day","3","","",""),
array("how do you spell a word","3","","",""),
array("home depot.com","3","","",""),
array("how to love lil wayne","4","","",""),
array("how to love","4","","",""),
array("harry potter and the deathly hallows part 2 trailer","4","","",""),
array("how to love lil wayne lyrics","4","","",""),
array("hurricane irene","4","","",""),
array("happy tree friends","4","","",""),
array("happy birthday song","4","","",""),
array("harry potter and the deathly hallows part 2","4","","",""),
array("headlines drake","4","","","")),
"i" => array(
array("ipad","0","1","3",""),
array("imdb","0","2","",""),
array("ikea","0","2","",""),
array("itunes","0","2","",""),
array("irs","0","2","",""),
array("indeed","0","2","",""),
array("ipod","1","2","",""),
array("iphone","1","2","",""),
array("iphone 5","0","","",""),
array("ign","0","","",""),
array("iphone 5 release date","0","","",""),
array("itunes download","0","","",""),
array("ipad 2","1","","",""),
array("iphone 4","1","","",""),
array("ipod touch","1","","",""),
array("iphone 4 case","1","","",""),
array("ipod touch 4th generation","1","","",""),
array("ipod nano","1","","",""),
array("ipad 2 case","1","","",""),
array("internet explorer","2","","",""),
array("illinois lottery","2","","",""),
array("isohunt","2","","",""),
array("inkling","3","","",""),
array("i 29 highway conditions","3","","",""),
array("i 90 road closures","3","","",""),
array("is the world going to end in 2012","3","","",""),
array("instant math answers free","3","","",""),
array("inspirational quotes","3","","",""),
array("is pneumonia contagious","3","","",""),
array("images","3","","",""),
array("is bronchitis contagious","3","","",""),
array("im on one","4","","",""),
array("if i die young the band perry","4","","",""),
array("im on one drake","4","","",""),
array("i need a doctor","4","","",""),
array("i wanna go britney spears","4","","",""),
array("i wanna go","4","","",""),
array("i just had sex-akon","4","","",""),
array("inna","4","","",""),
array("i love you like a love song selena gomez","4","","",""),
array("i love you","4","","","")),
"j" => array(
array("justin bieber","0","1","2","3"),
array("jennifer lopez","0","2","4",""),
array("jcpenney","0","2","",""),
array("jet blue","0","","",""),
array("jack in the box","0","","",""),
array("java","0","","",""),
array("jobs in las vegas","0","","",""),
array("joanns","0","","",""),
array("justin tv","0","","",""),
array("jersey shore","0","","",""),
array("juicer","1","","",""),
array("jansport backpack","1","","",""),
array("jane eyre","1","","",""),
array("jansport","1","","",""),
array("juicy couture","1","","",""),
array("jillian michaels","1","","",""),
array("jewelry box","1","","",""),
array("jack3d","1","","",""),
array("jordan shoes","1","","",""),
array("jennifer aniston","2","","",""),
array("jennifer garner","2","","",""),
array("jennifer hudson","2","","",""),
array("joe the plumber","2","","",""),
array("jessica alba","2","","",""),
array("jessica simpson","2","","",""),
array("jim carrey","2","","",""),
array("julianne hough","3","","",""),
array("jfk turtles","3","","",""),
array("joe cole","3","","",""),
array("justin bieber cell number","3","","",""),
array("justin bieber phone number for real","3","","",""),
array("jcpenney.com","3","","",""),
array("jobs in my area","3","","",""),
array("justin bieber quiz","3","","",""),
array("jobs","3","","",""),
array("justin bieber baby","4","","",""),
array("jennifer lopez on the floor","4","","",""),
array("justin bieber never say never","4","","",""),
array("jason derulo don't want go home","4","","",""),
array("jenna marbles","4","","",""),
array("jar of hearts","4","","",""),
array("jar of hearts christina perri","4","","",""),
array("justin bieber somebody to love","4","","","")),
"k" => array(
array("kmart","0","2","3",""),
array("katy perry","0","2","4",""),
array("kohls","0","3","",""),
array("kindle","1","3","",""),
array("kayak","0","","",""),
array("kbb","0","","",""),
array("knotts berry farm","0","","",""),
array("ktnv","0","","",""),
array("kfc","0","","",""),
array("kinkos","0","","",""),
array("kris humphries","0","","",""),
array("keurig","1","","",""),
array("kindle cover","1","","",""),
array("kinect","1","","",""),
array("k cups","1","","",""),
array("keyboard","1","","",""),
array("knife","1","","",""),
array("kindle case","1","","",""),
array("kitchenaid mixer","1","","",""),
array("keurig coffee maker","1","","",""),
array("kim kardashian","2","","",""),
array("katie holmes","2","","",""),
array("kelley blue book","2","","",""),
array("kate gosselin","2","","",""),
array("kohl's","2","","",""),
array("kristen stewart","2","","",""),
array("kings of leon","2","","",""),
array("kate winslet","2","","",""),
array("kate hudson","3","","",""),
array("kiosk","3","","",""),
array("kim kardashian full video","3","","",""),
array("kelly blue book","3","","",""),
array("kids games","3","","",""),
array("kellybluebook.com","3","","",""),
array("kia","3","","",""),
array("katy perry last friday night t.g.i.f","4","","",""),
array("katy perry et","4","","",""),
array("kesha","4","","",""),
array("kanye west","4","","",""),
array("katy perry firework","4","","",""),
array("kelly rowland motivation","4","","",""),
array("kid cudi","4","","",""),
array("kiss","4","","",""),
array("kevjumba","4","","","")),
"l" => array(
array("lowes","0","3","",""),
array("lil wayne","1","4","",""),
array("lady gaga","2","4","",""),
array("lyrics","2","3","",""),
array("las vegas review journal","0","","",""),
array("las vegas sun","0","","",""),
array("lake las vegas","0","","",""),
array("lvac","0","","",""),
array("linkedin","0","","",""),
array("las vegas craigslist","0","","",""),
array("las vegas weather","0","","",""),
array("las vegas news","0","","",""),
array("las vegas library","0","","",""),
array("laptop computer","1","","",""),
array("luggage","1","","",""),
array("laptop","1","","",""),
array("lego star wars","1","","",""),
array("lunch box","1","","",""),
array("laptop bag","1","","",""),
array("legos","1","","",""),
array("louis vuitton","1","","",""),
array("lord of the rings","1","","",""),
array("lindsay lohan","2","","",""),
array("leann rimes","2","","",""),
array("lil wayne accident","2","","",""),
array("limewire","2","","",""),
array("lowe's home improvement","2","","",""),
array("la la vasquez","2","","",""),
array("lita ford","2","","",""),
array("lindsay sloane","2","","",""),
array("labor day","3","","",""),
array("land rover defender","3","","",""),
array("lol :d","3","","",""),
array("lowes.com","3","","",""),
array("lyrics to songs","3","","",""),
array("love poems","3","","",""),
array("lingerie","3","","",""),
array("love quotes","3","","",""),
array("lazy song bruno mars","4","","",""),
array("lil wayne how to love","4","","",""),
array("last friday night","4","","",""),
array("look at me now chris brown","4","","",""),
array("lmfao party rock anthem","4","","",""),
array("last friday night t.g.i.f. katy perry","4","","",""),
array("love you like a love song selena gomez","4","","",""),
array("look at me now","4","","","")),
"m" => array(
array("mapquest","0","2","3",""),
array("msn","0","2","",""),
array("maps","0","3","",""),
array("myspace","0","2","",""),
array("minecraft","0","4","",""),
array("megan fox","2","3","",""),
array("mandalay bay","0","","",""),
array("macys","0","","",""),
array("mccarran airport","0","","",""),
array("michaels","0","","",""),
array("m resort","0","","",""),
array("macbook air","1","","",""),
array("macbook pro","1","","",""),
array("madden 12","1","","",""),
array("macbook","1","","",""),
array("mp3 player","1","","",""),
array("mouse","1","","",""),
array("messenger bag","1","","",""),
array("micro sd","1","","",""),
array("mac mini","1","","",""),
array("microwave","1","","",""),
array("melissa gilbert","2","","",""),
array("mail","2","","",""),
array("maggie gyllenhaal","2","","",""),
array("mark wahlberg","2","","",""),
array("minka kelly","2","","",""),
array("machine gun kelly","2","","",""),
array("melaleuca","3","","",""),
array("mel gibson","3","","",""),
array("mapquest driving directions","3","","",""),
array("math answers","3","","",""),
array("macys.com","3","","",""),
array("music","3","","",""),
array("medical dictionary","3","","",""),
array("michael jackson","4","","",""),
array("motivation kelly rowland","4","","",""),
array("moves like jagger","4","","",""),
array("miley cyrus","4","","",""),
array("man down rihanna","4","","",""),
array("mac miller","4","","",""),
array("marry you bruno mars","4","","",""),
array("mariah carey","4","","",""),
array("mr saxobeat","4","","","")),
"n" => array(
array("netflix","0","2","3",""),
array("nfl","0","2","",""),
array("nordstrom","0","2","",""),
array("nv energy","0","","",""),
array("nevada dmv","0","","",""),
array("nevada unemployment","0","","",""),
array("nevada state bank","0","","",""),
array("nick","0","","",""),
array("nevada federal credit union","0","","",""),
array("nevada state college","0","","",""),
array("nintendo 3ds","1","","",""),
array("nook","1","","",""),
array("nintendo ds","1","","",""),
array("nike","1","","",""),
array("nikon d7000","1","","",""),
array("nook color","1","","",""),
array("nokia n8","1","","",""),
array("nikon","1","","",""),
array("nikon d3100","1","","",""),
array("nikon d5100","1","","",""),
array("nick ashford dies","2","","",""),
array("nursing board passers 2011","2","","",""),
array("nascar","2","","",""),
array("nick jr","2","","",""),
array("new psoriasis drugs","2","","",""),
array("nursing licensure exam results 2011","2","","",""),
array("national weather service","2","","",""),
array("nursery rhymes","3","","",""),
array("numbers form","3","","",""),
array("nfl football game schedule","3","","",""),
array("name meanings","3","","",""),
array("names and meaning","3","","",""),
array("nissan","3","","",""),
array("nickelodeon games","3","","",""),
array("naked","3","","",""),
array("nissan cars","3","","",""),
array("nicki minaj","4","","",""),
array("nicki minaj super bass","4","","",""),
array("next to you chris brown ft justin bieber","4","","",""),
array("nigahiga","4","","",""),
array("new songs 2011","4","","",""),
array("nyan cat","4","","",""),
array("nicole scherzinger right there","4","","",""),
array("never say never","4","","",""),
array("next to you","4","","",""),
array("nicki minaj moment 4 life","4","","","")),
"o" => array(
array("old navy","0","2","3",""),
array("orbitz","0","2","",""),
array("office depot","0","2","",""),
array("overstock","0","2","",""),
array("online dictionary","2","3","",""),
array("office max","0","","",""),
array("omegle","0","","",""),
array("olive garden","0","","",""),
array("orchard bank","0","","",""),
array("orleans","0","","",""),
array("oovoo","0","","",""),
array("oakley","1","","",""),
array("otterbox iphone 4","1","","",""),
array("one day","1","","",""),
array("oakley sunglasses","1","","",""),
array("office chair","1","","",""),
array("otterbox","1","","",""),
array("opi","1","","",""),
array("opi nail polish","1","","",""),
array("onsale","1","","",""),
array("oxyelite pro","1","","",""),
array("omg","2","","",""),
array("oprah winfrey","2","","",""),
array("orkut","2","","",""),
array("ocracoke island","2","","",""),
array("olivia wilde","2","","",""),
array("open office","3","","",""),
array("oscar de la hoya","3","","",""),
array("outages","3","","",""),
array("online pregnancy test","3","","",""),
array("ovulation calculator","3","","",""),
array("ovulation calendar","3","","",""),
array("online games","3","","",""),
array("online calculator","3","","",""),
array("on the floor jennifer lopez","4","","",""),
array("on the floor","4","","",""),
array("on my level wiz khalifa","4","","",""),
array("one republic good life","4","","",""),
array("otis","4","","",""),
array("on the floor jennifer lopez ft pitbull","4","","",""),
array("one republic","4","","",""),
array("oh my dj drama","4","","",""),
array("owl city","4","","",""),
array("out of my head lupe fiasco","4","","","")),
"p" => array(
array("pandora","0","2","",""),
array("pizza hut","0","2","",""),
array("paypal","0","2","",""),
array("priceline","0","2","",""),
array("photobucket","0","2","",""),
array("planking","0","4","",""),
array("people search","2","3","",""),
array("parentlink","0","","",""),
array("poptropica","0","","",""),
array("papa johns","0","","",""),
array("pirate bay","0","","",""),
array("ps3","1","","",""),
array("playstation 3","1","","",""),
array("psp","1","","",""),
array("posters","1","","",""),
array("p90x","1","","",""),
array("printer","1","","",""),
array("ps3 controller","1","","",""),
array("projector","1","","",""),
array("pokemon","1","","",""),
array("ps3 console","1","","",""),
array("powerball results july 20,2011","2","","",""),
array("pogo","2","","",""),
array("paula deen","2","","",""),
array("patti smith","2","","",""),
array("play playhouse disney","3","","",""),
array("play disney channel games","3","","",""),
array("phschool com math","3","","",""),
array("pregnancy week by week","3","","",""),
array("phone number lookup","3","","",""),
array("prom dresses","3","","",""),
array("people search for free","3","","",""),
array("people finder","3","","",""),
array("put my word in a sentence","3","","",""),
array("party rock anthem","4","","",""),
array("pitbull give me everything","4","","",""),
array("pitbull","4","","",""),
array("price tag","4","","",""),
array("party rock anthem lmfao","4","","",""),
array("pink","4","","",""),
array("pumped up kicks","4","","",""),
array("porque maldita","4","","",""),
array("party rock","4","","","")),
"q" => array(
array("qvc","0","2","3",""),
array("quotes","0","2","3",""),
array("quest diagnostics","0","2","",""),
array("quicktime","0","2","",""),
array("quiznos","0","2","",""),
array("quotes about life","0","3","",""),
array("quinoa","0","1","",""),
array("queen","1","4","",""),
array("qwop","0","","",""),
array("quest diagnostics las vegas","0","","",""),
array("quibids","0","","",""),
array("quickbooks","1","","",""),
array("quicken","1","","",""),
array("quiksilver","1","","",""),
array("quickbooks pro 2011","1","","",""),
array("queen mattress","1","","",""),
array("quilt","1","","",""),
array("queen bed frame","1","","",""),
array("queen sheet set","1","","",""),
array("queen latifah clothing line","2","","",""),
array("qwest","2","","",""),
array("query string","2","","",""),
array("quality inn","2","","",""),
array("quentin tarantino","2","","",""),
array("quien la razon","3","","",""),
array("quien razon","3","","",""),
array("quien tiene la","3","","",""),
array("quotes of the day","3","","",""),
array("quizzes","3","","",""),
array("quotes and sayings","3","","",""),
array("quick mileage city to city","3","","",""),
array("quickie miguel","4","","",""),
array("queen bohemian rhapsody","4","","",""),
array("quest crew","4","","",""),
array("queen we will rock you","4","","",""),
array("quickie","4","","",""),
array("queens of the stone age","4","","",""),
array("queen don't stop me now","4","","",""),
array("quran","4","","",""),
array("quickie miguel with lyrics","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("espn","0","2","",""),
array("eminem","1","4","",""),
array("enterprise car rental","2","3","",""),
array("edc","0","","",""),
array("etsy","0","","",""),
array("enterprise","0","","",""),
array("edc las vegas","0","","",""),
array("eppicard","0","","",""),
array("earthquake","0","","",""),
array("ebay motors","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("ethernet cable","1","","",""),
array("espresso machine","1","","",""),
array("electronic cigarette","1","","",""),
array("ebooks","1","","",""),
array("external hard drive 1tb","1","","",""),
array("earrings","1","","",""),
array("emma stone","2","","",""),
array("elizabeth banks","2","","",""),
array("eva marie saint","2","","",""),
array("elin nordegren","2","","",""),
array("eva longoria","2","","",""),
array("earl bradley","2","","",""),
array("edu","3","","",""),
array("eras","3","","",""),
array("emma watson","3","","",""),
array("expedia.com","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("extreme couponing","3","","",""),
array("eminem space bound","4","","",""),
array("enrique iglesias","4","","",""),
array("eminem not afraid","4","","",""),
array("epicmealtime","4","","",""),
array("epic rap battles of history","4","","",""),
array("et katty perry","4","","",""),
array("eminem lose yourself","4","","",""),
array("everyday im shuffling","4","","",""),
array("edge of glory lady gaga","4","","","")),
"s" => array(
array("southwest airlines","0","2","3",""),
array("sears","0","2","3",""),
array("skype","0","2","",""),
array("sprint","0","2","",""),
array("spirit airlines","0","","",""),
array("southwest gas","0","","",""),
array("smiths","0","","",""),
array("sams club","0","","",""),
array("station casinos","0","","",""),
array("starbucks","0","","",""),
array("search amazon.com","1","","",""),
array("samsung galaxy tab 10.1","1","","",""),
array("star wars","1","","",""),
array("samsung galaxy s2","1","","",""),
array("sunglasses","1","","",""),
array("star wars blu ray","1","","",""),
array("sd card","1","","",""),
array("speakers","1","","",""),
array("skyrim","1","","",""),
array("samsung galaxy","1","","",""),
array("sara gilbert","2","","",""),
array("soleil moon frye","2","","",""),
array("sandra bullock","2","","",""),
array("staples","2","","",""),
array("supernova","2","","",""),
array("scarlett johansson","2","","",""),
array("september","3","","",""),
array("sinead o connor","3","","",""),
array("stage","3","","",""),
array("scary maze game","3","","",""),
array("sears.com","3","","",""),
array("spanish dictionary","3","","",""),
array("sexy","3","","",""),
array("song lyrics","3","","",""),
array("super bass nicki minaj","4","","",""),
array("selena gomez","4","","",""),
array("super bass","4","","",""),
array("skyscraper demi lovato","4","","",""),
array("shakira","4","","",""),
array("smosh","4","","",""),
array("selena gomez love you like a love song","4","","",""),
array("selena gomez who says","4","","",""),
array("super bass nicki minaj lyrics","4","","",""),
array("skrillex","4","","","")),
"t" => array(
array("target","0","2","",""),
array("twitter","0","2","",""),
array("translator","0","3","",""),
array("thesaurus","0","2","",""),
array("tmz","0","2","",""),
array("travelocity","0","2","",""),
array("ticketmaster","0","2","",""),
array("taylor swift","2","4","",""),
array("tumblr","0","","",""),
array("town square las vegas","0","","",""),
array("tmobile","0","","",""),
array("touchpad","1","","",""),
array("the help","1","","",""),
array("tablet","1","","",""),
array("thor","1","","",""),
array("toms","1","","",""),
array("the hunger games","1","","",""),
array("true blood","1","","",""),
array("textbooks","1","","",""),
array("transformers","1","","",""),
array("tv stand","1","","",""),
array("toys r us","2","","",""),
array("tiger woods","2","","",""),
array("tagged","2","","",""),
array("texas a m","3","","",""),
array("tina brown","3","","",""),
array("tea leoni","3","","",""),
array("translate english to spanish","3","","",""),
array("tattoo designs","3","","",""),
array("translate spanish to english","3","","",""),
array("travelocity.com","3","","",""),
array("teen pregnancy signs","3","","",""),
array("tattoos","3","","",""),
array("the lazy song bruno mars","4","","",""),
array("tonight tonight hot chelle rae","4","","",""),
array("teach me how to dougie","4","","",""),
array("tonight tonight","4","","",""),
array("the lazy song","4","","",""),
array("tyler the creator","4","","",""),
array("tom and jerry","4","","",""),
array("teach me how to dougie official video","4","","",""),
array("the wanted glad you came","4","","","")),
"u" => array(
array("united airlines","0","2","3",""),
array("us airways","0","2","3",""),
array("ufc","0","2","4",""),
array("usps","0","2","",""),
array("ups","0","2","",""),
array("usaa","0","2","",""),
array("ups tracking","0","3","",""),
array("used cars","2","3","",""),
array("unlv","0","","",""),
array("us bank","0","","",""),
array("uhaul","0","","",""),
array("usb flash drive","1","","",""),
array("unlocked cell phones","1","","",""),
array("under armour","1","","",""),
array("umbrella","1","","",""),
array("usb hub","1","","",""),
array("uncharted 3","1","","",""),
array("unbroken","1","","",""),
array("ugg","1","","",""),
array("usb","1","","",""),
array("uncharted","1","","",""),
array("upcoming","2","","",""),
array("univision","2","","",""),
array("utusan malaysia","2","","",""),
array("ui","3","","",""),
array("um","3","","",""),
array("unclaimed money name","3","","",""),
array("used cars for sale in my area","3","","",""),
array("used cars for sale","3","","",""),
array("unique baby names","3","","",""),
array("usher","4","","",""),
array("usher more","4","","",""),
array("usher dj got us falling in love","4","","",""),
array("u2","4","","",""),
array("ultimate dog teaser","4","","",""),
array("ufo","4","","",""),
array("usain bolt","4","","",""),
array("usher yeah","4","","",""),
array("unfriend you greyson chance","4","","","")),
"v" => array(
array("verizon","0","2","3",""),
array("verizon wireless","0","2","3",""),
array("victoria secret","0","3","",""),
array("vans","0","1","",""),
array("victoria's secret","1","2","",""),
array("vanessa hudgens","2","4","",""),
array("virgin mobile","2","3","",""),
array("venetian","0","","",""),
array("vons","0","","",""),
array("virgin america","0","","",""),
array("volaris","0","","",""),
array("vlc","0","","",""),
array("vimeo","0","","",""),
array("vacuum cleaner","1","","",""),
array("verizon cell phones","1","","",""),
array("vera bradley","1","","",""),
array("vitamix","1","","",""),
array("vacuum","1","","",""),
array("video camera","1","","",""),
array("vampire diaries","1","","",""),
array("vaporizer","1","","",""),
array("valeriya shevchenko","2","","",""),
array("victoria beckham","2","","",""),
array("vh1","2","","",""),
array("video","2","","",""),
array("value city furniture","2","","",""),
array("vitamin d study","3","","",""),
array("vi","3","","",""),
array("verizon.com","3","","",""),
array("very early symptoms of pregnancy","3","","",""),
array("verizonwireless.com","3","","",""),
array("videos","3","","",""),
array("vma 2011","4","","",""),
array("victorious","4","","",""),
array("vevo","4","","",""),
array("victoria justice","4","","",""),
array("vybz kartel","4","","",""),
array("valerie amy winehouse","4","","",""),
array("victoria justice beggin on your knees","4","","",""),
array("vma","4","","",""),
array("video lucu","4","","","")),
"w" => array(
array("white pages","0","2","3",""),
array("walmart","0","2","",""),
array("wells fargo","0","2","",""),
array("weather","0","2","",""),
array("wikipedia","0","2","",""),
array("webmd","0","2","",""),
array("wwe","2","4","",""),
array("walgreens","0","","",""),
array("www.facebook.com","0","","",""),
array("weather las vegas","0","","",""),
array("wynn","0","","",""),
array("wii","1","","",""),
array("watch the throne","1","","",""),
array("wireless router","1","","",""),
array("watch","1","","",""),
array("wii games","1","","",""),
array("windows 7","1","","",""),
array("webcam","1","","",""),
array("wallet","1","","",""),
array("wireless mouse","1","","",""),
array("watches for men","1","","",""),
array("watch summerslam 2011 online","2","","",""),
array("winehouse toxicology","2","","",""),
array("webkinz","2","","",""),
array("wesley sneijder","3","","",""),
array("what is a thesis statement","3","","",""),
array("what is a variable","3","","",""),
array("what is justin biebers phone number","3","","",""),
array("what does my last name mean","3","","",""),
array("what is the meaning of my name","3","","",""),
array("what is love","3","","",""),
array("what does my dream mean","3","","",""),
array("where can i watch free movies online","3","","",""),
array("wiz khalifa","4","","",""),
array("who says selena gomez","4","","",""),
array("waka waka shakira","4","","",""),
array("wiz khalifa on my level","4","","",""),
array("written in the stars","4","","",""),
array("wiz khalifa roll up","4","","",""),
array("wiz khalifa no sleep","4","","",""),
array("who says","4","","",""),
array("what the hell avril lavigne","4","","","")),
"x" => array(
array("xbox 360","1","2","3","4"),
array("xbox","0","1","3",""),
array("xbox live","0","1","2",""),
array("xm radio","0","2","3",""),
array("xoom","0","1","",""),
array("xbox 360 games","1","3","",""),
array("xs las vegas","0","","",""),
array("xmen first class","0","","",""),
array("xda","0","","",""),
array("x107.5","0","","",""),
array("xkcd","0","","",""),
array("xbmc","0","","",""),
array("xbox 360 console","1","","",""),
array("xbox 360 controller","1","","",""),
array("xperia play","1","","",""),
array("xbox 360 kinect","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("x-men first class","2","","",""),
array("xvid","2","","",""),
array("x games 2011","2","","",""),
array("xanax","2","","",""),
array("xxxv full movie","2","","",""),
array("x17","2","","",""),
array("xha","2","","",""),
array("xperia","3","","",""),
array("xxl movie","3","","",""),
array("xbox 360 cheats","3","","",""),
array("xxl tv live","3","","",""),
array("xm satellite radio","3","","",""),
array("xbox live 2 month free trial","3","","",""),
array("xjawz","4","","",""),
array("x factor 2011","4","","",""),
array("x factor","4","","",""),
array("x men first class trailer","4","","",""),
array("x factor australia 2011","4","","",""),
array("xzibit","4","","",""),
array("xx3","4","","",""),
array("x men first class","4","","",""),
array("x factor 2011 auditions","4","","","")),
"y" => array(
array("youtube","0","2","3","4"),
array("yahoo mail","0","2","3",""),
array("yahoo","0","3","",""),
array("yahoo answers","0","2","",""),
array("yellow pages","0","3","",""),
array("yelp","0","","",""),
array("youtube to mp3","0","","",""),
array("ymca las vegas","0","","",""),
array("yahoo maps","0","","",""),
array("y8","0","","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yugioh cards","1","","",""),
array("yugioh","1","","",""),
array("yoga dvd","1","","",""),
array("yo gabba gabba","1","","",""),
array("your highness","1","","",""),
array("yarn","1","","",""),
array("yankee candle","1","","",""),
array("yogurt maker","1","","",""),
array("yahoo calendar","2","","",""),
array("yahoo sports","2","","",""),
array("yahoo weather","2","","",""),
array("yahoo bookmarks","2","","",""),
array("yahoo finance","2","","",""),
array("yahoo travel","2","","",""),
array("yahoo horoscopes","2","","",""),
array("york state driving","3","","",""),
array("york state road","3","","",""),
array("youtube videos","3","","",""),
array("yahoo mail login","3","","",""),
array("yellowpages.com","3","","",""),
array("youtube music","3","","",""),
array("young jeezy","4","","",""),
array("yonkers","4","","",""),
array("you make me feel cobra starship","4","","",""),
array("yogscast","4","","",""),
array("yeah 3x chris brown","4","","",""),
array("yeah 3x","4","","",""),
array("young wild and free wiz khalifa","4","","",""),
array("you and tequila kenny chesney","4","","",""),
array("you belong with me","4","","","")),
"z" => array(
array("zappos","0","2","3",""),
array("zip codes","0","2","3",""),
array("zodiac signs","0","2","3",""),
array("zumba","1","3","4",""),
array("zillow","0","2","",""),
array("zune","0","1","",""),
array("zombie","1","4","",""),
array("zion national park","0","","",""),
array("zumiez","0","","",""),
array("zillow las vegas","0","","",""),
array("zappos jobs","0","","",""),
array("zumanity","0","","",""),
array("zippo","1","","",""),
array("zumba fitness dvd","1","","",""),
array("zune hd","1","","",""),
array("zelda","1","","",""),
array("zumba dvd","1","","",""),
array("zippo lighter","1","","",""),
array("zumba wii","1","","",""),
array("zooey deschanel","2","","",""),
array("zsa zsa gabor","2","","",""),
array("zoe saldana","2","","",""),
array("zales","2","","",""),
array("zuma","2","","",""),
array("zedge","2","","",""),
array("zip lookup address","3","","",""),
array("zip code lookup by address","3","","",""),
array("zones map","3","","",""),
array("zip code finder","3","","",""),
array("zappos.com","3","","",""),
array("zip code lookup","3","","",""),
array("zindagi na milegi dobara songs","4","","",""),
array("zindagi na milegi dobara","4","","",""),
array("zac brown band","4","","",""),
array("zaz je veux","4","","",""),
array("zindagi na milegi dobara trailer","4","","",""),
array("zumba dance workout","4","","",""),
array("zombie cranberries","4","","",""),
array("zac brown band knee deep","4","","","")));
?>