<?php $topResults = array(
"a" => array(
array("angry birds","1","","",""),
array("amazon prime","1","","",""),
array("assassins creed revelations","1","","",""),
array("apple tv","1","","",""),
array("adidas","1","","",""),
array("airsoft guns","1","","",""),
array("android tablet","1","","",""),
array("apple","1","","",""),
array("arkham city","1","","",""),
array("asus transformer","1","","",""),
array("amazon","2","","",""),
array("aol","2","","",""),
array("at&t","2","","",""),
array("angelina jolie","2","","",""),
array("autotrader","2","","",""),
array("american airlines","2","","",""),
array("ask jeeves","2","","",""),
array("american idol","2","","",""),
array("adele surgery","2","","",""),
array("addicting games","2","","",""),
array("annie","3","","",""),
array("airline baby ban","3","","",""),
array("austin rivers","3","","",""),
array("apartments for rent","3","","",""),
array("antonym dictionary","3","","",""),
array("are vampires real","3","","",""),
array("airline tickets","3","","",""),
array("amazon.com","3","","",""),
array("am i pregnant quiz","3","","",""),
array("answers.com","3","","",""),
array("adele someone like you","4","","",""),
array("adele","4","","",""),
array("adele rolling in the deep","4","","",""),
array("adele set fire to the rain","4","","",""),
array("avril lavigne","4","","",""),
array("annoying orange","4","","",""),
array("akon","4","","",""),
array("adele someone like you lyrics","4","","",""),
array("avengers trailer","4","","",""),
array("avenged sevenfold","4","","","")),
"b" => array(
array("best buy","2","3","",""),
array("bank of america","2","3","",""),
array("britney spears","2","4","",""),
array("bed bath and beyond","2","3","",""),
array("battlefield 3","1","","",""),
array("blackberry","1","","",""),
array("batman arkham city","1","","",""),
array("boots","1","","",""),
array("beats by dre","1","","",""),
array("bose","1","","",""),
array("batman","1","","",""),
array("bluetooth headset","1","","",""),
array("barbie","1","","",""),
array("blackberry torch","1","","",""),
array("blank","2","","",""),
array("black friday 2011 walmart","2","","",""),
array("brody jenner","2","","",""),
array("bing","2","","",""),
array("barnes and noble","2","","",""),
array("blake lively","2","","",""),
array("black friday 2011","3","","",""),
array("best floor cleaners","3","","",""),
array("blood sugar","3","","",""),
array("baby names","3","","",""),
array("bmi calculator","3","","",""),
array("baby names and meanings","3","","",""),
array("baby girl names","3","","",""),
array("beyonce","4","","",""),
array("bruno mars","4","","",""),
array("beyonce best thing i never had","4","","",""),
array("bruno mars lazy song","4","","",""),
array("baby justin bieber","4","","",""),
array("black eyed peas","4","","",""),
array("beyonce countdown","4","","",""),
array("black and yellow wiz khalifa","4","","",""),
array("bruno mars marry you","4","","","")),
"c" => array(
array("coldplay","1","4","",""),
array("craigslist","2","3","",""),
array("capital one","2","3","",""),
array("call of duty modern warfare 3","1","","",""),
array("cars 2","1","","",""),
array("camera","1","","",""),
array("call of duty","1","","",""),
array("christmas decorations","1","","",""),
array("christmas tree","1","","",""),
array("coffee maker","1","","",""),
array("captain america","1","","",""),
array("canon 60d","1","","",""),
array("chase","2","","",""),
array("cnn","2","","",""),
array("costco","2","","",""),
array("chelsea handler","2","","",""),
array("comcast","2","","",""),
array("continental airlines","2","","",""),
array("channing tatum","2","","",""),
array("cartoon network","2","","",""),
array("chris hansen","3","","",""),
array("casey anthony","3","","",""),
array("chris bosh","3","","",""),
array("cheap airline tickets","3","","",""),
array("calculator","3","","",""),
array("cheap flights","3","","",""),
array("calorie counter","3","","",""),
array("currency converter","3","","",""),
array("chris brown","4","","",""),
array("cat daddy","4","","",""),
array("california king bed","4","","",""),
array("christina aguilera","4","","",""),
array("chris brown look at me now","4","","",""),
array("cobra starship you make me feel","4","","",""),
array("countdown beyonce","4","","",""),
array("champagne showers lmfao","4","","",""),
array("coldplay paradise","4","","","")),
"d" => array(
array("drake","1","4","",""),
array("dictionary","2","3","",""),
array("delta airlines","2","3","",""),
array("digital camera","1","","",""),
array("droid razr","1","","",""),
array("dsi","1","","",""),
array("dark souls","1","","",""),
array("diapers","1","","",""),
array("diablo 3","1","","",""),
array("dvd player","1","","",""),
array("dead island","1","","",""),
array("ds","1","","",""),
array("disney channel","2","","",""),
array("dippin dots","2","","",""),
array("dancing with the stars","2","","",""),
array("demi lovato","2","","",""),
array("dwight arrington myers","2","","",""),
array("dish network","2","","",""),
array("duggar family","2","","",""),
array("dakota fanning","2","","",""),
array("duke basketball","3","","",""),
array("duke basketball schedule","3","","",""),
array("de futbol vivo","3","","",""),
array("definitions.com","3","","",""),
array("dictionary online","3","","",""),
array("driving directions","3","","",""),
array("does justin bieber have a girlfriend","3","","",""),
array("direct tv","3","","",""),
array("dubstep","4","","",""),
array("drake headlines","4","","",""),
array("david guetta","4","","",""),
array("danza kuduro","4","","",""),
array("drake marvins room","4","","",""),
array("don omar danza kuduro","4","","",""),
array("deadmau5","4","","",""),
array("demi lovato skyscraper","4","","",""),
array("dappy no regrets","4","","","")),
"e" => array(
array("ebay","2","3","",""),
array("expedia","2","3","",""),
array("enterprise car rental","2","3","",""),
array("ebay motors","2","3","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("electric blanket","1","","",""),
array("earbuds","1","","",""),
array("elf on the shelf","1","","",""),
array("eragon","1","","",""),
array("elmo","1","","",""),
array("espresso machine","1","","",""),
array("easy bake oven","1","","",""),
array("electric fireplace","1","","",""),
array("espn","2","","",""),
array("ellen degeneres","2","","",""),
array("elin nordegren","2","","",""),
array("eva longoria","2","","",""),
array("eddie murphy","2","","",""),
array("elizabeth warren","2","","",""),
array("elisabeth hasselbeck","3","","",""),
array("erin brady","3","","",""),
array("emma watson","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("extreme couponing","3","","",""),
array("eminem","4","","",""),
array("epic rap battles of history","4","","",""),
array("eminem space bound","4","","",""),
array("enrique iglesias","4","","",""),
array("epic meal time","4","","",""),
array("eminem lose yourself","4","","",""),
array("eminem not afraid","4","","",""),
array("evanescence","4","","",""),
array("everyday im shuffling","4","","",""),
array("eminem lighters","4","","","")),
"f" => array(
array("facebook","2","3","4",""),
array("free online games","2","3","",""),
array("fifa 12","1","","",""),
array("flash drive","1","","",""),
array("free kindle books","1","","",""),
array("food processor","1","","",""),
array("florence and the machine","1","","",""),
array("fire","1","","",""),
array("fisher price","1","","",""),
array("flashlight","1","","",""),
array("forza 4","1","","",""),
array("floor lamp","1","","",""),
array("friendster","2","","",""),
array("fox news","2","","",""),
array("food network","2","","",""),
array("fedex","2","","",""),
array("fantasy football","2","","",""),
array("ford","2","","",""),
array("firefox","2","","",""),
array("funbrain","2","","",""),
array("fire island","3","","",""),
array("free thanksgiving worksheets","3","","",""),
array("free music downloads","3","","",""),
array("free ringtones","3","","",""),
array("free games","3","","",""),
array("free credit report","3","","",""),
array("facebook login","3","","",""),
array("free cell phone number search","3","","",""),
array("funny video","4","","",""),
array("foster the people pumped up kicks","4","","",""),
array("funny","4","","",""),
array("fly nicki minaj","4","","",""),
array("funny pranks","4","","",""),
array("friday rebecca black","4","","",""),
array("fred","4","","",""),
array("freddiew","4","","",""),
array("funny cats","4","","","")),
"g" => array(
array("google","2","3","4",""),
array("gears of war 3","1","4","",""),
array("google search","2","3","",""),
array("games","2","3","",""),
array("google maps","2","3","",""),
array("gps","1","","",""),
array("gift card","1","","",""),
array("game of thrones","1","","",""),
array("galaxy s2","1","","",""),
array("generator","1","","",""),
array("garmin","1","","",""),
array("galaxy tab","1","","",""),
array("guitar","1","","",""),
array("galaxy nexus","1","","",""),
array("gmail","2","","",""),
array("goo","2","","",""),
array("gwar","2","","",""),
array("gloria allred","2","","",""),
array("george takei","2","","",""),
array("green energy","2","","",""),
array("gabby giffords","3","","",""),
array("gabrielle giffords","3","","",""),
array("gabby giffords interview","3","","",""),
array("google.com","3","","",""),
array("gnc","3","","",""),
array("google earth","3","","",""),
array("give me everything pitbull","4","","",""),
array("gucci gucci","4","","",""),
array("gym class heroes stereo hearts","4","","",""),
array("glee","4","","",""),
array("god gave me you","4","","",""),
array("gummy bear song","4","","",""),
array("grenade bruno mars","4","","",""),
array("good life one republic","4","","","")),
"h" => array(
array("halloween costumes","1","2","3",""),
array("home depot","2","3","",""),
array("heavy d","2","4","",""),
array("hunger games trailer","3","4","",""),
array("harry potter","1","","",""),
array("headphones","1","","",""),
array("harry potter and the deathly hallows part 2","1","","",""),
array("hp touchpad","1","","",""),
array("hdmi cable","1","","",""),
array("humidifier","1","","",""),
array("harry potter and the deathly hallows part 2 dvd","1","","",""),
array("hello kitty","1","","",""),
array("harry potter box set","1","","",""),
array("hotmail","2","","",""),
array("hilary swank","2","","",""),
array("hulu","2","","",""),
array("how to tie a tie","2","","",""),
array("halle berry","2","","",""),
array("heidi montag","2","","",""),
array("hi5","2","","",""),
array("heather locklear","3","","",""),
array("haley joel osment","3","","",""),
array("how much should i weigh","3","","",""),
array("how to kiss","3","","",""),
array("how to get pregnant","3","","",""),
array("how do you spell a word","3","","",""),
array("how many calories should i eat a day","3","","",""),
array("how to love lil wayne","4","","",""),
array("how to love","4","","",""),
array("headlines drake","4","","",""),
array("happy birthday song","4","","",""),
array("honey badger","4","","",""),
array("how to love lil wayne official video","4","","",""),
array("headlines","4","","",""),
array("happy tree friends","4","","","")),
"i" => array(
array("ipad","1","3","",""),
array("iphone 4s","1","4","",""),
array("iphone 5","2","4","",""),
array("ipod touch","1","","",""),
array("ipad 2","1","","",""),
array("iphone 4","1","","",""),
array("ipod","1","","",""),
array("iphone 4s case","1","","",""),
array("iphone 4 case","1","","",""),
array("iphone","1","","",""),
array("ipod nano","1","","",""),
array("itunes","2","","",""),
array("iphone 4s problem","2","","",""),
array("imdb","2","","",""),
array("internet explorer","2","","",""),
array("ikea","2","","",""),
array("irs","2","","",""),
array("indeed","2","","",""),
array("isohunt","2","","",""),
array("illinois lottery","2","","",""),
array("interactive data","3","","",""),
array("interactive data managed","3","","",""),
array("is chelsea clinton married","3","","",""),
array("is the world going to end in 2012","3","","",""),
array("is it going to rain","3","","",""),
array("is santa claus real yes or no","3","","",""),
array("is selena gomez pregnant","3","","",""),
array("inspirational quotes","3","","",""),
array("instant math answers free","3","","",""),
array("if i die young the band perry","4","","",""),
array("it girl-jason derulo lyrics","4","","",""),
array("im on one","4","","",""),
array("i love you like a love song selena gomez","4","","",""),
array("in the dark dev","4","","",""),
array("i wanna go britney spears","4","","",""),
array("i need a doctor","4","","",""),
array("i just had sex-akon","4","","","")),
"j" => array(
array("justin bieber","1","2","4",""),
array("jennifer lopez","2","4","",""),
array("just dance 3","1","","",""),
array("juicer","1","","",""),
array("jawbone up","1","","",""),
array("just dance 3 wii","1","","",""),
array("jewelry box","1","","",""),
array("juicy couture","1","","",""),
array("jerry sandusky","1","","",""),
array("jurassic park","1","","",""),
array("jacket","1","","",""),
array("jennifer aniston","2","","",""),
array("jessica biel","2","","",""),
array("jay wornick","2","","",""),
array("jcpenney","2","","",""),
array("jessica simpson","2","","",""),
array("jim mcneil","2","","",""),
array("jessica chastain","2","","",""),
array("julianne hough","2","","",""),
array("john hughes","3","","",""),
array("jerry sandusky interview","3","","",""),
array("jack wagner","3","","",""),
array("justin bieber phone number for real","3","","",""),
array("justin bieber quiz","3","","",""),
array("jcpenney.com","3","","",""),
array("justin bieber cell number","3","","",""),
array("jobs in my area","3","","",""),
array("jobs","3","","",""),
array("jobs hiring in my area","3","","",""),
array("justin bieber baby","4","","",""),
array("jar of hearts","4","","",""),
array("jennifer lopez on the floor","4","","",""),
array("justin bieber never say never","4","","",""),
array("j cole work out","4","","",""),
array("jar of hearts christina perri","4","","",""),
array("j cole","4","","",""),
array("justin bieber mistletoe","4","","","")),
"k" => array(
array("kindle","1","3","",""),
array("kmart","2","3","",""),
array("katy perry","2","4","",""),
array("kindle fire","1","","",""),
array("keurig","1","","",""),
array("kinect","1","","",""),
array("keurig coffee maker","1","","",""),
array("k cups","1","","",""),
array("kitchenaid mixer","1","","",""),
array("kindle touch","1","","",""),
array("kindle cover","1","","",""),
array("keyboard","1","","",""),
array("kim kardashian","2","","",""),
array("kris humphries","2","","",""),
array("kate gosselin","2","","",""),
array("kristen stewart","2","","",""),
array("kelly osbourne","2","","",""),
array("kelley blue book","2","","",""),
array("kelly slater","2","","",""),
array("kate middleton","2","","",""),
array("kentucky basketball","3","","",""),
array("kindle fire review","3","","",""),
array("kindle fire review mossberg","3","","",""),
array("kohls","3","","",""),
array("kohls coupons","3","","",""),
array("kia","3","","",""),
array("kids games","3","","",""),
array("kids dictionary","3","","",""),
array("katy perry last friday night t.g.i.f","4","","",""),
array("kesha","4","","",""),
array("kanye west","4","","",""),
array("kelly clarkson","4","","",""),
array("kid cudi","4","","",""),
array("kevjumba","4","","",""),
array("kiss","4","","",""),
array("katy perry firework","4","","",""),
array("kelly clarkson mr know it all","4","","","")),
"l" => array(
array("lady gaga","2","4","",""),
array("limewire","2","3","",""),
array("love quotes","2","3","",""),
array("laptop computer","1","","",""),
array("legos","1","","",""),
array("leappad","1","","",""),
array("laptop","1","","",""),
array("lego star wars","1","","",""),
array("luggage","1","","",""),
array("lalaloopsy","1","","",""),
array("lion king","1","","",""),
array("louis vuitton","1","","",""),
array("levis","1","","",""),
array("lindsay lohan","2","","",""),
array("lindsey vonn","2","","",""),
array("lowe's home improvement","2","","",""),
array("leann rimes","2","","",""),
array("lyrics","2","","",""),
array("lowes stores","2","","",""),
array("linkedin","2","","",""),
array("live oak","3","","",""),
array("leymah gbowee","3","","",""),
array("love and hip hop","3","","",""),
array("lowes","3","","",""),
array("lyrics to songs","3","","",""),
array("lingerie","3","","",""),
array("love poems","3","","",""),
array("love calculator","3","","",""),
array("lil wayne","4","","",""),
array("lmfao","4","","",""),
array("lil wayne how to love","4","","",""),
array("lmfao party rock anthem","4","","",""),
array("look at me now chris brown","4","","",""),
array("lighters eminem","4","","",""),
array("lazy song bruno mars","4","","",""),
array("lady gaga you and i","4","","",""),
array("lil wayne she will","4","","","")),
"m" => array(
array("mw3","1","4","",""),
array("mapquest","2","3","",""),
array("megan fox","2","3","",""),
array("miley cyrus","2","4","",""),
array("modern warfare 3","1","","",""),
array("macbook pro","1","","",""),
array("mp3 player","1","","",""),
array("macbook air","1","","",""),
array("monster high","1","","",""),
array("macbook","1","","",""),
array("metal gear solid hd collection","1","","",""),
array("micro sd card","1","","",""),
array("mouse","1","","",""),
array("myspace","2","","",""),
array("msn","2","","",""),
array("meghan daum","2","","",""),
array("mail","2","","",""),
array("michael j fox","2","","",""),
array("miss world pageant","2","","",""),
array("mariah carey","2","","",""),
array("mirror mirror","3","","",""),
array("mark kelly","3","","",""),
array("mapquest driving directions","3","","",""),
array("maps","3","","",""),
array("math answers","3","","",""),
array("make me a sentence","3","","",""),
array("macys.com","3","","",""),
array("metric conversion chart","3","","",""),
array("moves like jagger","4","","",""),
array("michael jackson","4","","",""),
array("moves like jagger maroon 5","4","","",""),
array("mac miller","4","","",""),
array("maroon 5","4","","",""),
array("minecraft","4","","",""),
array("mr saxobeat","4","","",""),
array("marry you bruno mars","4","","","")),
"n" => array(
array("nike","1","3","",""),
array("netflix","2","3","",""),
array("nintendo 3ds","1","","",""),
array("nintendo ds","1","","",""),
array("nook","1","","",""),
array("nikon d7000","1","","",""),
array("nikon","1","","",""),
array("nikon d3100","1","","",""),
array("nintendo dsi","1","","",""),
array("nikon d5100","1","","",""),
array("north face","1","","",""),
array("north beach","2","","",""),
array("nancy grace","2","","",""),
array("nick cannon","2","","",""),
array("nfl","2","","",""),
array("nascar","2","","",""),
array("nordstrom","2","","",""),
array("neil patrick harris","2","","",""),
array("nick jr","2","","",""),
array("news","2","","",""),
array("newt gingrich","3","","",""),
array("newt gingrich scandal","3","","",""),
array("nusa dua bali","3","","",""),
array("names and meaning","3","","",""),
array("name meanings","3","","",""),
array("nissan","3","","",""),
array("nickelodeon games","3","","",""),
array("nissan cars","3","","",""),
array("nicki minaj","4","","",""),
array("nicki minaj super bass","4","","",""),
array("nigahiga","4","","",""),
array("new songs 2011","4","","",""),
array("nyan cat","4","","",""),
array("next to you chris brown ft justin bieber","4","","",""),
array("nickelback","4","","",""),
array("no sleep wiz khalifa","4","","",""),
array("nothing the script","4","","",""),
array("never say never","4","","","")),
"o" => array(
array("old navy","2","3","",""),
array("online dictionary","2","3","",""),
array("otterbox iphone 4","1","","",""),
array("otterbox iphone 4s","1","","",""),
array("otterbox","1","","",""),
array("oakley","1","","",""),
array("oakley sunglasses","1","","",""),
array("otterbox defender iphone 4s","1","","",""),
array("opi","1","","",""),
array("oxyelite pro","1","","",""),
array("office chair","1","","",""),
array("opi nail polish","1","","",""),
array("ohio polls 2011","2","","",""),
array("omg","2","","",""),
array("orbitz","2","","",""),
array("office depot","2","","",""),
array("overstock","2","","",""),
array("oprah winfrey","2","","",""),
array("olivia wilde","2","","",""),
array("orkut","2","","",""),
array("ohio state basketball","3","","",""),
array("ohio state basketball schedule","3","","",""),
array("ows","3","","",""),
array("online pregnancy test","3","","",""),
array("ovulation calculator","3","","",""),
array("ovulation calendar","3","","",""),
array("online calculator","3","","",""),
array("ounce conversion chart","3","","",""),
array("one direction what makes you beautiful","4","","",""),
array("on the floor jennifer lopez","4","","",""),
array("one direction","4","","",""),
array("otis","4","","",""),
array("otis kanye west","4","","",""),
array("on the floor","4","","",""),
array("olly murs heart skips a beat","4","","",""),
array("one republic good life","4","","",""),
array("occupy wall street","4","","",""),
array("one republic","4","","","")),
"p" => array(
array("people search","2","3","",""),
array("ps3","1","","",""),
array("playstation 3","1","","",""),
array("psp","1","","",""),
array("ps3 controller","1","","",""),
array("p90x","1","","",""),
array("projector","1","","",""),
array("ps3 console","1","","",""),
array("portable dvd player","1","","",""),
array("pillow pets","1","","",""),
array("posters","1","","",""),
array("powerball results november 2 2011","2","","",""),
array("pandora","2","","",""),
array("paypal","2","","",""),
array("pizza hut","2","","",""),
array("photobucket","2","","",""),
array("pogo","2","","",""),
array("priceline","2","","",""),
array("pro","2","","",""),
array("poptropica","2","","",""),
array("patti labelle","3","","",""),
array("patti labelle songs","3","","",""),
array("pfister hotel","3","","",""),
array("pregnancy week by week","3","","",""),
array("phone number lookup","3","","",""),
array("put my word in a sentence","3","","",""),
array("pregnancy calculator","3","","",""),
array("people search for free","3","","",""),
array("people finder","3","","",""),
array("party rock anthem","4","","",""),
array("pumped up kicks","4","","",""),
array("pitbull","4","","",""),
array("pitbull give me everything","4","","",""),
array("pumped up kicks foster the people","4","","",""),
array("paranormal activity 3","4","","",""),
array("party rock anthem lmfao","4","","",""),
array("price tag","4","","",""),
array("pitbull rain over me","4","","",""),
array("party rock","4","","","")),
"q" => array(
array("quickbooks","1","2","",""),
array("queen","1","4","",""),
array("qvc","2","3","",""),
array("quotes","2","3","",""),
array("quicken 2012","1","","",""),
array("quiksilver","1","","",""),
array("quicken","1","","",""),
array("quilt","1","","",""),
array("quickbooks pro 2012","1","","",""),
array("queen mattress","1","","",""),
array("quelf","1","","",""),
array("queen bed frame","1","","",""),
array("quest diagnostics","2","","",""),
array("quicktime","2","","",""),
array("queen latifah","2","","",""),
array("quiznos","2","","",""),
array("quality inn","2","","",""),
array("qwest","2","","",""),
array("query string","2","","",""),
array("quest diagnostics hours","3","","",""),
array("quest labs appointments","3","","",""),
array("quest diagnostics appointments","3","","",""),
array("quotes of the day","3","","",""),
array("quotes about life","3","","",""),
array("quotes and sayings","3","","",""),
array("quick mileage city to city","3","","",""),
array("qvc home shopping","3","","",""),
array("quickie miguel","4","","",""),
array("queen bohemian rhapsody","4","","",""),
array("quest crew","4","","",""),
array("queen somebody to love","4","","",""),
array("queen don't stop me now","4","","",""),
array("quickie","4","","",""),
array("queen we will rock you","4","","",""),
array("quickie miguel with lyrics","4","","",""),
array("queens of the stone age","4","","","")),
"e" => array(
array("ebay","2","3","",""),
array("expedia","2","3","",""),
array("enterprise car rental","2","3","",""),
array("ebay motors","2","3","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("electric blanket","1","","",""),
array("earbuds","1","","",""),
array("elf on the shelf","1","","",""),
array("eragon","1","","",""),
array("elmo","1","","",""),
array("espresso machine","1","","",""),
array("easy bake oven","1","","",""),
array("electric fireplace","1","","",""),
array("espn","2","","",""),
array("ellen degeneres","2","","",""),
array("elin nordegren","2","","",""),
array("eva longoria","2","","",""),
array("eddie murphy","2","","",""),
array("elizabeth warren","2","","",""),
array("elisabeth hasselbeck","3","","",""),
array("erin brady","3","","",""),
array("emma watson","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("extreme couponing","3","","",""),
array("eminem","4","","",""),
array("epic rap battles of history","4","","",""),
array("eminem space bound","4","","",""),
array("enrique iglesias","4","","",""),
array("epic meal time","4","","",""),
array("eminem lose yourself","4","","",""),
array("eminem not afraid","4","","",""),
array("evanescence","4","","",""),
array("everyday im shuffling","4","","",""),
array("eminem lighters","4","","","")),
"s" => array(
array("skyrim","1","4","",""),
array("southwest airlines","2","3","",""),
array("steve jobs","1","","",""),
array("samsung galaxy s2","1","","",""),
array("search amazon.com","1","","",""),
array("star wars","1","","",""),
array("skyward sword","1","","",""),
array("samsung galaxy tab 10.1","1","","",""),
array("samsung galaxy tab","1","","",""),
array("sunglasses","1","","",""),
array("sewing machine","1","","",""),
array("sears","2","","",""),
array("staples","2","","",""),
array("social security","2","","",""),
array("scarlett johansson","2","","",""),
array("sandra bullock","2","","",""),
array("skype","2","","",""),
array("sprint","2","","",""),
array("susan boyle","2","","",""),
array("sharon bialek","2","","",""),
array("sopa","3","","",""),
array("sopapilla","3","","",""),
array("short thanksgiving poems","3","","",""),
array("scary maze game","3","","",""),
array("science fair projects","3","","",""),
array("spanish dictionary","3","","",""),
array("spanish to english translation","3","","",""),
array("spell check","3","","",""),
array("sexy","3","","",""),
array("super bass nicki minaj","4","","",""),
array("someone like you adele","4","","",""),
array("stereo hearts gym class heroes","4","","",""),
array("super bass","4","","",""),
array("selena gomez","4","","",""),
array("skrillex","4","","",""),
array("selena gomez love you like a love song","4","","",""),
array("smosh","4","","",""),
array("someone like you","4","","","")),
"t" => array(
array("toys r us","2","3","",""),
array("taylor swift","2","4","",""),
array("tablet","1","","",""),
array("twilight","1","","",""),
array("transformers","1","","",""),
array("toms","1","","",""),
array("toshiba thrive","1","","",""),
array("the help","1","","",""),
array("the walking dead","1","","",""),
array("telescope","1","","",""),
array("thermos","1","","",""),
array("tv","1","","",""),
array("target","2","","",""),
array("tiger woods","2","","",""),
array("travelocity","2","","",""),
array("twitter","2","","",""),
array("thesaurus","2","","",""),
array("tmz","2","","",""),
array("ticketmaster","2","","",""),
array("tappan zee bridge","2","","",""),
array("tanuki","3","","",""),
array("toronto international film festival","3","","",""),
array("tina brown","3","","",""),
array("translate english to spanish","3","","",""),
array("tattoo designs","3","","",""),
array("translate spanish to english","3","","",""),
array("teen pregnancy signs","3","","",""),
array("translator","3","","",""),
array("tractor supply","3","","",""),
array("teach me how to dougie","4","","",""),
array("teach me how to dougie official video","4","","",""),
array("tonight tonight hot chelle rae","4","","",""),
array("tom and jerry","4","","",""),
array("tyler the creator","4","","",""),
array("the lazy song bruno mars","4","","",""),
array("teri meri bodyguard","4","","",""),
array("trey songz","4","","",""),
array("tom and jerry cartoon","4","","","")),
"u" => array(
array("ugg boots","1","3","",""),
array("united airlines","2","3","",""),
array("us airways","2","3","",""),
array("uncharted 3","1","","",""),
array("ugg","1","","",""),
array("under armour","1","","",""),
array("uncharted","1","","",""),
array("umbrella","1","","",""),
array("unlocked cell phones","1","","",""),
array("usb flash drive","1","","",""),
array("ugg boots women","1","","",""),
array("usb hub","1","","",""),
array("usps","2","","",""),
array("ups","2","","",""),
array("upcoming","2","","",""),
array("ufc 138 results","2","","",""),
array("underworld awakening","2","","",""),
array("unemployment benefits","2","","",""),
array("usaa","2","","",""),
array("univision","2","","",""),
array("uc berkeley","3","","",""),
array("uk basketball","3","","",""),
array("uc berkeley shooting","3","","",""),
array("used cars","3","","",""),
array("used cars for sale in my area","3","","",""),
array("ups tracking","3","","",""),
array("unique baby names","3","","",""),
array("usher","4","","",""),
array("usher dj got us falling in love","4","","",""),
array("up up and away lil wayne","4","","",""),
array("u2","4","","",""),
array("ufo","4","","",""),
array("ufc","4","","",""),
array("uberhaxornova","4","","",""),
array("usher without you","4","","",""),
array("usher yeah","4","","",""),
array("ultimate dog teaser","4","","","")),
"v" => array(
array("verizon wireless","2","3","",""),
array("verizon","2","3","",""),
array("virgin mobile","2","3","",""),
array("vacuum cleaner","1","","",""),
array("verizon cell phones","1","","",""),
array("vans","1","","",""),
array("vera bradley","1","","",""),
array("video camera","1","","",""),
array("vampire diaries","1","","",""),
array("video games","1","","",""),
array("vitamix","1","","",""),
array("vizio tablet","1","","",""),
array("vacuum","1","","",""),
array("victoria's secret","2","","",""),
array("vanessa hudgens","2","","",""),
array("victoria beckham","2","","",""),
array("vh1","2","","",""),
array("video","2","","",""),
array("vanguard","2","","",""),
array("value city furniture","2","","",""),
array("vitamin d study","3","","",""),
array("vikings game","3","","",""),
array("victoria secret friday","3","","",""),
array("verizon.com","3","","",""),
array("very early symptoms of pregnancy","3","","",""),
array("victoria secret","3","","",""),
array("verizonwireless.com","3","","",""),
array("victorious","4","","",""),
array("vevo","4","","",""),
array("victoria justice","4","","",""),
array("vybz kartel","4","","",""),
array("video lucu","4","","",""),
array("valerie amy winehouse","4","","",""),
array("viva la vida","4","","",""),
array("vampire diaries season 3","4","","",""),
array("vybz kartel 2011","4","","",""),
array("van halen","4","","","")),
"w" => array(
array("white pages","2","3","",""),
array("wwe","2","4","",""),
array("wii","1","","",""),
array("wii games","1","","",""),
array("watch","1","","",""),
array("wii console","1","","",""),
array("wireless router","1","","",""),
array("wallet","1","","",""),
array("windows 7","1","","",""),
array("watches for men","1","","",""),
array("walking dead","1","","",""),
array("wireless mouse","1","","",""),
array("walmart","2","","",""),
array("weather","2","","",""),
array("wells fargo","2","","",""),
array("wikipedia","2","","",""),
array("womens world cup 2011","2","","",""),
array("webmd","2","","",""),
array("walgreens","2","","",""),
array("wilmer valderrama","2","","",""),
array("will rogers","3","","",""),
array("will rogers quotes","3","","",""),
array("watch packer game online","3","","",""),
array("what does my last name mean","3","","",""),
array("what is the meaning of my name","3","","",""),
array("what does my name mean","3","","",""),
array("what does my dream mean","3","","",""),
array("what is a hobnocker","3","","",""),
array("where can i watch free movies online","3","","",""),
array("wiz khalifa","4","","",""),
array("we found love","4","","",""),
array("we found love rihanna calvin harris","4","","",""),
array("without you david guetta","4","","",""),
array("without you","4","","",""),
array("waka waka shakira","4","","",""),
array("wiz khalifa on my level","4","","",""),
array("wiz khalifa no sleep","4","","",""),
array("work out j cole","4","","","")),
"x" => array(
array("xbox 360","1","2","3",""),
array("xbox 360 console","1","3","",""),
array("xbox live","1","2","",""),
array("xbox 360 games","1","3","",""),
array("xbox kinect","1","3","",""),
array("x factor 2011","2","4","",""),
array("xm radio","2","3","",""),
array("xbox","1","","",""),
array("xbox 360 kinect","1","","",""),
array("xbox 360 controller","1","","",""),
array("xoom","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("x-men first class","2","","",""),
array("xvid","2","","",""),
array("xxxv full movie","2","","",""),
array("xanax","2","","",""),
array("xha","2","","",""),
array("xnxsxs","2","","",""),
array("xbox live 12 month free","3","","",""),
array("xxl movie","3","","",""),
array("xbox 360 cheats","3","","",""),
array("xxl tv live","3","","",""),
array("xbox 360 cheat codes","3","","",""),
array("x factor","4","","",""),
array("x factor usa","4","","",""),
array("x factor 2011 uk","4","","",""),
array("x factor usa 2011","4","","",""),
array("xjawz","4","","",""),
array("x factor usa judges houses","4","","",""),
array("x factor australia 2011","4","","",""),
array("xx3","4","","",""),
array("x factor auditions 2011","4","","","")),
"y" => array(
array("youtube","2","3","4",""),
array("yahoo mail","2","3","",""),
array("yoga mat","1","","",""),
array("yo gabba gabba","1","","",""),
array("yoga","1","","",""),
array("yarn","1","","",""),
array("yankee candle","1","","",""),
array("yugioh cards","1","","",""),
array("yoga dvd","1","","",""),
array("yoga pants","1","","",""),
array("yugioh","1","","",""),
array("yoyo","1","","",""),
array("yahoo calendar","2","","",""),
array("yahoo sports","2","","",""),
array("yahoo answers","2","","",""),
array("yahoo weather","2","","",""),
array("yahoo horoscopes","2","","",""),
array("yahoo people search","2","","",""),
array("yahoo bookmarks","2","","",""),
array("yahoo travel","2","","",""),
array("you tube broadcast","3","","",""),
array("you tube broadcast yourself","3","","",""),
array("yellow pages","3","","",""),
array("youtube videos","3","","",""),
array("yahoo","3","","",""),
array("yahoo mail login","3","","",""),
array("yellowpages.com","3","","",""),
array("youtube.com","3","","",""),
array("you and i lady gaga","4","","",""),
array("you make me feel cobra starship","4","","",""),
array("you and i","4","","",""),
array("yogscast","4","","",""),
array("young wild and free wiz khalifa","4","","",""),
array("you make me feel","4","","",""),
array("yelawolf","4","","",""),
array("young jeezy","4","","",""),
array("yeah 3x chris brown","4","","","")),
"z" => array(
array("zumba","1","4","",""),
array("zombie","1","4","",""),
array("zappos","2","3","",""),
array("zip codes","2","3","",""),
array("zodiac signs","2","3","",""),
array("zelda","1","","",""),
array("zune","1","","",""),
array("zelda skyward sword","1","","",""),
array("zippo","1","","",""),
array("zumba fitness dvd","1","","",""),
array("zune hd","1","","",""),
array("zippo lighter","1","","",""),
array("zelda skyward sword special edition","1","","",""),
array("zsa zsa gabor","2","","",""),
array("zooey deschanel","2","","",""),
array("zillow","2","","",""),
array("zales","2","","",""),
array("zuma","2","","",""),
array("zoe saldana","2","","",""),
array("zedge","2","","",""),
array("zuccotti park","3","","",""),
array("zuccotti park map","3","","",""),
array("zuccotti park new york","3","","",""),
array("zip code finder","3","","",""),
array("zappos.com","3","","",""),
array("zip code lookup","3","","",""),
array("zip code list","3","","",""),
array("zac brown band","4","","",""),
array("zaz je veux","4","","",""),
array("zombie cranberries","4","","",""),
array("zumba dance workout","4","","",""),
array("zindagi na milegi dobara songs","4","","",""),
array("zakkum anason 2011","4","","",""),
array("zaz","4","","",""),
array("zz top","4","","","")));
?>