<?php $topResults = array(
"a" => array(
array("amazon","0","2","3",""),
array("aol","0","2","3",""),
array("addicting games","0","2","",""),
array("apple","0","1","",""),
array("autotrader","0","2","",""),
array("ask.com","0","3","",""),
array("att wireless","0","3","",""),
array("american idol","2","4","",""),
array("at&t","0","","",""),
array("american airlines","0","","",""),
array("avg","0","","",""),
array("acer aspire one","1","","",""),
array("adidas","1","","",""),
array("airsoft guns","1","","",""),
array("atlas shrugged","1","","",""),
array("audio books","1","","",""),
array("apple iphone","1","","",""),
array("asus 1000he","1","","",""),
array("asus","1","","",""),
array("australia","1","","",""),
array("ask jeeves","2","","",""),
array("abc","2","","",""),
array("argos","2","","",""),
array("angelina jolie","2","","",""),
array("aaa","2","","",""),
array("amazon.com","3","","",""),
array("aol.com","3","","",""),
array("att","3","","",""),
array("ask for kids","3","","",""),
array("ask","3","","",""),
array("american eagle","3","","",""),
array("akon","4","","",""),
array("avril lavigne","4","","",""),
array("akon right now na na na","4","","",""),
array("arcangel","4","","",""),
array("akon right now","4","","",""),
array("alicia keys","4","","",""),
array("abba","4","","",""),
array("aventura","4","","",""),
array("achmed the dead terrorist","4","","","")),
"b" => array(
array("best buy","0","2","3",""),
array("bank of america","0","2","3",""),
array("bebo","0","2","3",""),
array("bed bath and beyond","0","3","",""),
array("barnes and noble","0","3","",""),
array("bbc","0","2","",""),
array("barack obama","0","3","",""),
array("britney spears","2","4","",""),
array("baby names","2","3","",""),
array("blockbuster","0","","",""),
array("borders","0","","",""),
array("bbc news","0","","",""),
array("blackberry","1","","",""),
array("blackberry storm","1","","",""),
array("blu ray","1","","",""),
array("blackberry bold","1","","",""),
array("blackberry curve","1","","",""),
array("bluetooth headset","1","","",""),
array("blackberry unlocked","1","","",""),
array("battlestar galactica","1","","",""),
array("blu ray player","1","","",""),
array("bakugan","1","","",""),
array("babies r us","2","","",""),
array("barbie","2","","",""),
array("banana republic","2","","",""),
array("b&q","2","","",""),
array("barack obama biography","3","","",""),
array("bestbuy.com","3","","",""),
array("burlington coat factory","3","","",""),
array("beyonce","4","","",""),
array("beyonce single ladies","4","","",""),
array("britney spears circus","4","","",""),
array("britney spears womanizer","4","","",""),
array("beyonce if i were a boy","4","","",""),
array("bob marley","4","","",""),
array("beyonce diva","4","","",""),
array("bon jovi","4","","",""),
array("basshunter","4","","","")),
"c" => array(
array("craigslist","0","2","3",""),
array("cnn","0","2","3",""),
array("circuit city","0","2","3",""),
array("costco","0","2","",""),
array("club penguin","0","2","",""),
array("coldplay","1","4","",""),
array("currency converter","0","","",""),
array("comcast","0","","",""),
array("capital one","0","","",""),
array("comcast.net","0","","",""),
array("cheap flights","0","","",""),
array("cell phones","1","","",""),
array("coffee maker","1","","",""),
array("canon","1","","",""),
array("call of duty 4","1","","",""),
array("camera","1","","",""),
array("canon powershot","1","","",""),
array("canon 50d","1","","",""),
array("coraline","1","","",""),
array("crocs","1","","",""),
array("cingular","2","","",""),
array("calendar","2","","",""),
array("christina ricci","2","","",""),
array("california lottery","2","","",""),
array("cartoon network","2","","",""),
array("craigslist.com","3","","",""),
array("craigs list","3","","",""),
array("coin values","3","","",""),
array("cheap airline tickets","3","","",""),
array("charlotte russe","3","","",""),
array("calculator","3","","",""),
array("cnn.com","3","","",""),
array("chris brown","4","","",""),
array("circus","4","","",""),
array("charlie bit my finger","4","","",""),
array("christina aguilera","4","","",""),
array("circus britney spears","4","","",""),
array("celine dion","4","","",""),
array("crazy frog","4","","",""),
array("camp rock","4","","",""),
array("crush","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("disney channel","0","2","3",""),
array("dell","0","2","",""),
array("delta","0","2","",""),
array("disney","0","2","",""),
array("dish network","0","2","",""),
array("driving directions","2","3","",""),
array("dancing with the stars","2","3","",""),
array("directions","2","3","",""),
array("direct tv","0","","",""),
array("dominos","0","","",""),
array("dillards","0","","",""),
array("download.com","0","","",""),
array("digital camera","1","","",""),
array("dvd","1","","",""),
array("dvd player","1","","",""),
array("ds","1","","",""),
array("dexter","1","","",""),
array("ds games","1","","",""),
array("dvd movies","1","","",""),
array("digital photo frame","1","","",""),
array("dexter season 3","1","","",""),
array("depeche mode","1","","",""),
array("delta airlines","2","","",""),
array("dictionary.com","3","","",""),
array("dictionary online","3","","",""),
array("dogpile","3","","",""),
array("definitions","3","","",""),
array("definition","3","","",""),
array("disturbia","4","","",""),
array("don omar","4","","",""),
array("dance","4","","",""),
array("dane cook","4","","",""),
array("demi lovato","4","","",""),
array("disturbed","4","","",""),
array("decode","4","","",""),
array("day and night","4","","",""),
array("dragon ball z","4","","",""),
array("david archuleta","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("espn","0","2","3",""),
array("eminem","1","2","4",""),
array("expedia","0","2","",""),
array("express","0","2","",""),
array("ed hardy","0","1","",""),
array("edward cullen","0","","",""),
array("ebay motors","0","","",""),
array("earth","0","","",""),
array("ebuddy","0","","",""),
array("exchange rates","0","","",""),
array("external hard drive","1","","",""),
array("empire total war","1","","",""),
array("eat this not that","1","","",""),
array("earbuds","1","","",""),
array("eclipse","1","","",""),
array("earphones","1","","",""),
array("external hard drive 1tb","1","","",""),
array("eee pc","1","","",""),
array("ecards","2","","",""),
array("emma watson","2","","",""),
array("enterprise","2","","",""),
array("eva longoria","2","","",""),
array("easyjet","2","","",""),
array("ebay.com","3","","",""),
array("english to spanish translation","3","","",""),
array("early pregnancy symptoms","3","","",""),
array("expedia.com","3","","",""),
array("electoral college","3","","",""),
array("espn.com","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("enterprise car rental","3","","",""),
array("enrique iglesias","4","","",""),
array("evanescence","4","","",""),
array("evolution of dance","4","","",""),
array("eye of the tiger","4","","",""),
array("elvis presley","4","","",""),
array("elton john","4","","",""),
array("enya","4","","",""),
array("eric clapton","4","","",""),
array("eminem lose yourself","4","","","")),
"f" => array(
array("facebook","0","2","3",""),
array("food network","0","2","3",""),
array("fox news","0","2","3",""),
array("free online games","0","2","3",""),
array("firefox","0","2","",""),
array("fedex","0","2","",""),
array("free games","0","3","",""),
array("family guy","1","4","",""),
array("free music downloads","2","3","",""),
array("facebook login","0","","",""),
array("friendster","0","","",""),
array("flickr","0","","",""),
array("fallout 3","1","","",""),
array("flash drive","1","","",""),
array("futurama","1","","",""),
array("fireproof","1","","",""),
array("fleshlight","1","","",""),
array("friday the 13th","1","","",""),
array("fireproof dvd","1","","",""),
array("food processor","1","","",""),
array("final fantasy","1","","",""),
array("fafsa","2","","",""),
array("fantasy football","2","","",""),
array("ford","2","","",""),
array("facebook.com","3","","",""),
array("free myspace layouts","3","","",""),
array("free ringtones","3","","",""),
array("free music","3","","",""),
array("funny","4","","",""),
array("fred","4","","",""),
array("funny video","4","","",""),
array("funny cats","4","","",""),
array("funny accidents","4","","",""),
array("fall out boy","4","","",""),
array("funny pranks","4","","",""),
array("fall for you","4","","",""),
array("fight","4","","","")),
"g" => array(
array("google","0","2","3",""),
array("gmail","0","2","3",""),
array("games","0","2","3",""),
array("google maps","0","3","",""),
array("google earth","0","3","",""),
array("gamestop","0","3","",""),
array("gap","0","2","",""),
array("guitar hero world tour","1","4","",""),
array("google search","2","3","",""),
array("google chrome","0","","",""),
array("google translate","0","","",""),
array("gossip girl","0","","",""),
array("gps","1","","",""),
array("garmin","1","","",""),
array("guitar hero","1","","",""),
array("garmin gps","1","","",""),
array("guitar","1","","",""),
array("garmin nuvi","1","","",""),
array("guess","1","","",""),
array("gps garmin","1","","",""),
array("gears of war 2","1","","",""),
array("game","2","","",""),
array("gisele bundchen","2","","",""),
array("geico","2","","",""),
array("google homepage","2","","",""),
array("gas prices","2","","",""),
array("google.com","3","","",""),
array("gmail.com","3","","",""),
array("global warming","3","","",""),
array("green day","4","","",""),
array("ghost","4","","",""),
array("guns n roses","4","","",""),
array("gaza","4","","",""),
array("gummy bear song","4","","",""),
array("gucci mane","4","","",""),
array("gian marco","4","","",""),
array("girlfriend","4","","",""),
array("ghost caught on tape","4","","","")),
"h" => array(
array("hotmail","0","2","3",""),
array("home depot","0","2","3",""),
array("honda","0","2","",""),
array("hsbc","0","2","",""),
array("horoscope","0","2","",""),
array("harry potter","1","2","",""),
array("high school musical 3","1","4","",""),
array("horoscopes","2","3","",""),
array("halloween costumes","2","3","",""),
array("hulu","0","","",""),
array("hp","0","","",""),
array("hollister","0","","",""),
array("house","0","","",""),
array("heroes","0","","",""),
array("halo wars","1","","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("halo 3","1","","",""),
array("humidifier","1","","",""),
array("handbags","1","","",""),
array("hello kitty","1","","",""),
array("hard drive","1","","",""),
array("hi5","2","","",""),
array("holiday inn","2","","",""),
array("how to get pregnant","3","","",""),
array("how much should i weigh","3","","",""),
array("hotmail.com","3","","",""),
array("how long do drugs stay in your system","3","","",""),
array("how to tie a tie","3","","",""),
array("halloween costumes for adults","3","","",""),
array("hot n cold","4","","",""),
array("heartless","4","","",""),
array("hannah montana","4","","",""),
array("hadise","4","","",""),
array("happy tree friends","4","","",""),
array("hot n cold katy perry","4","","",""),
array("heartless kanye west","4","","",""),
array("high school musical","4","","",""),
array("halo","4","","","")),
"i" => array(
array("imdb","0","2","3",""),
array("itunes","0","2","3",""),
array("ikea","0","2","3",""),
array("iphone","0","1","2",""),
array("irs","0","2","3",""),
array("ipod","1","2","3",""),
array("ipod touch","0","1","",""),
array("images","0","","",""),
array("isohunt","0","","",""),
array("indian railways","0","","",""),
array("irctc","0","","",""),
array("ipod nano","1","","",""),
array("iphone 3g","1","","",""),
array("ipod touch 2nd generation","1","","",""),
array("iphone 3g unlocked","1","","",""),
array("itouch","1","","",""),
array("ipod classic","1","","",""),
array("imac","1","","",""),
array("internet explorer","2","","",""),
array("ign","2","","",""),
array("imeem","2","","",""),
array("internal revenue service","2","","",""),
array("inspirational quotes","3","","",""),
array("is raven symone pregnant","3","","",""),
array("is santa claus real","3","","",""),
array("iq test","3","","",""),
array("is ciara a man","3","","",""),
array("if i were a boy","4","","",""),
array("im yours","4","","",""),
array("i kissed a girl- kate perry","4","","",""),
array("if i were a boy beyonce","4","","",""),
array("infinity","4","","",""),
array("im so paid","4","","",""),
array("infinity 2008","4","","",""),
array("i hated this part","4","","",""),
array("iron maiden","4","","",""),
array("i miss you","4","","","")),
"j" => array(
array("jobs","0","2","3",""),
array("jokes","0","2","3",""),
array("jonas brothers","1","3","4",""),
array("jcpenney","0","2","",""),
array("java","0","2","",""),
array("jennifer aniston","0","2","",""),
array("job search","0","3","",""),
array("jason mraz","1","4","",""),
array("jennifer lopez","2","4","",""),
array("jet blue","0","","",""),
array("john travolta","0","","",""),
array("jett travolta","0","","",""),
array("jetstar","0","","",""),
array("jillian michaels","1","","",""),
array("juicy couture","1","","",""),
array("james patterson","1","","",""),
array("juicer","1","","",""),
array("jodi picoult","1","","",""),
array("jewelry","1","","",""),
array("john mayer","1","","",""),
array("james bond","1","","",""),
array("jessica simpson","2","","",""),
array("jessica alba","2","","",""),
array("jillian harris","2","","",""),
array("jetblue","2","","",""),
array("john mccain","3","","",""),
array("jobs in my area","3","","",""),
array("john mccain biography","3","","",""),
array("jcpenny.com","3","","",""),
array("jennifer hudson","3","","",""),
array("jc penny","3","","",""),
array("just dance","4","","",""),
array("justin timberlake","4","","",""),
array("jeff dunham","4","","",""),
array("jizzed in my pants","4","","",""),
array("just dance lady gaga","4","","",""),
array("jason mraz im yours","4","","",""),
array("jackass","4","","","")),
"k" => array(
array("kmart","0","2","3",""),
array("kanye west","0","1","4",""),
array("kelly clarkson","1","2","4",""),
array("kohls","0","3","",""),
array("kim kardashian","0","2","",""),
array("katy perry","0","4","",""),
array("kristen stewart","0","2","",""),
array("kay jewelers","0","3","",""),
array("kings of leon","1","4","",""),
array("kazaa","2","3","",""),
array("kelly blue book","0","","",""),
array("kijiji","0","","",""),
array("kayak","0","","",""),
array("kindle","1","","",""),
array("kindle 2","1","","",""),
array("killzone 2","1","","",""),
array("kindle books","1","","",""),
array("kindle 1","1","","",""),
array("kindle store","1","","",""),
array("keurig","1","","",""),
array("kara dioguardi","2","","",""),
array("kelley blue book","2","","",""),
array("katie holmes","2","","",""),
array("kohl's","2","","",""),
array("keira knightley","2","","",""),
array("kohls.com","3","","",""),
array("kmart.com","3","","",""),
array("kids games","3","","",""),
array("kennedy half dollar worth","3","","",""),
array("king tut","3","","",""),
array("kidney stones","3","","",""),
array("katy perry hot n cold","4","","",""),
array("kiss","4","","",""),
array("kiss me thru the phone","4","","",""),
array("kanye west heartless","4","","",""),
array("katt williams","4","","",""),
array("korn","4","","","")),
"l" => array(
array("limewire","0","2","3",""),
array("lyrics","0","2","3",""),
array("lost","0","1","2",""),
array("lady gaga","0","1","4",""),
array("lil wayne","0","3","4",""),
array("love quotes","0","2","3",""),
array("lowes","0","3","",""),
array("love poems","2","3","",""),
array("ll bean","0","","",""),
array("lands end","0","","",""),
array("love","0","","",""),
array("laptop","1","","",""),
array("laptop computer","1","","",""),
array("lego","1","","",""),
array("lcd tv","1","","",""),
array("luggage","1","","",""),
array("lord of the rings","1","","",""),
array("lego star wars","1","","",""),
array("left 4 dead","1","","",""),
array("lindsay lohan","2","","",""),
array("lowe's","2","","",""),
array("launch","2","","",""),
array("las vegas","2","","",""),
array("lottery","2","","",""),
array("lyrics to songs","3","","",""),
array("lowes.com","3","","",""),
array("lyrics.com","3","","",""),
array("lil waynes daughter","3","","",""),
array("linkin park","4","","",""),
array("love story","4","","",""),
array("let it rock","4","","",""),
array("lady gaga just dance","4","","",""),
array("live your life","4","","",""),
array("love lockdown","4","","",""),
array("leona lewis","4","","",""),
array("lady gaga poker face","4","","","")),
"m" => array(
array("myspace","0","2","3",""),
array("mapquest","0","2","3",""),
array("msn","0","2","3",""),
array("maps","0","2","3",""),
array("music","1","2","4",""),
array("macys","0","3","",""),
array("myspace layouts","0","3","",""),
array("miniclip","0","","",""),
array("mapquest driving directions","0","","",""),
array("msnbc","0","","",""),
array("mortgage calculator","0","","",""),
array("macbook","1","","",""),
array("mp3 player","1","","",""),
array("mac mini","1","","",""),
array("mario kart wii","1","","",""),
array("macbook pro","1","","",""),
array("micro sd","1","","",""),
array("mp3","1","","",""),
array("mouse","1","","",""),
array("microsoft office 2007","1","","",""),
array("mail","2","","",""),
array("map","2","","",""),
array("macy's","2","","",""),
array("mariska hargitay","2","","",""),
array("malin akerman","2","","",""),
array("myspace.com","3","","",""),
array("mapquest.com","3","","",""),
array("msn.com","3","","",""),
array("map quest","3","","",""),
array("michael jackson","4","","",""),
array("miley cyrus","4","","",""),
array("metallica","4","","",""),
array("mariah carey","4","","",""),
array("madonna","4","","",""),
array("mad","4","","",""),
array("molotov","4","","",""),
array("miss independent","4","","",""),
array("my life","4","","","")),
"n" => array(
array("netflix","0","2","3",""),
array("nfl","0","2","3",""),
array("news","0","3","",""),
array("nordstrom","0","2","",""),
array("nbc","0","3","",""),
array("new york times","0","3","",""),
array("nokia","0","2","",""),
array("nba","0","2","",""),
array("nissan","0","2","",""),
array("northwest airlines","0","2","",""),
array("nascar","2","3","",""),
array("naruto","2","4","",""),
array("nintendo ds","1","","",""),
array("netbook","1","","",""),
array("nintendo wii","1","","",""),
array("nikon d90","1","","",""),
array("nintendo ds games","1","","",""),
array("nike","1","","",""),
array("nikon d60","1","","",""),
array("no line on the horizon","1","","",""),
array("nokia e71","1","","",""),
array("nintendo ds lite","1","","",""),
array("niki taylor","2","","",""),
array("nascar.com","3","","",""),
array("nfl.com","3","","",""),
array("napa auto parts","3","","",""),
array("name meanings","3","","",""),
array("nickelback","4","","",""),
array("ne-yo","4","","",""),
array("naruto shippuden","4","","",""),
array("nirvana","4","","",""),
array("nelly","4","","",""),
array("numa numa","4","","",""),
array("nigahiga","4","","",""),
array("notorious big","4","","",""),
array("ninja cat","4","","","")),
"o" => array(
array("obama","0","1","3","4"),
array("orkut","0","2","3",""),
array("office depot","0","2","3",""),
array("old navy","0","2","3",""),
array("online games","0","2","3",""),
array("orbitz","0","2","",""),
array("overstock","0","2","",""),
array("oprah","0","2","",""),
array("office max","0","2","",""),
array("online dictionary","2","3","",""),
array("open office","0","","",""),
array("outliers","1","","",""),
array("oakley","1","","",""),
array("one tree hill","1","","",""),
array("ooma","1","","",""),
array("onkyo","1","","",""),
array("oakley sunglasses","1","","",""),
array("office 2007","1","","",""),
array("oblivion","1","","",""),
array("out of captivity","1","","",""),
array("olive garden","2","","",""),
array("overstock.com","3","","",""),
array("ovulation calculator","3","","",""),
array("olympics","3","","",""),
array("online pregnancy test","3","","",""),
array("obama song","4","","",""),
array("oasis","4","","",""),
array("obama inauguration","4","","",""),
array("one more drink","4","","",""),
array("one step at a time","4","","",""),
array("old greg","4","","",""),
array("obama inauguration speech","4","","",""),
array("one","4","","",""),
array("obama speech","4","","","")),
"p" => array(
array("photobucket","0","2","3",""),
array("pizza hut","0","2","3",""),
array("people search","0","2","3",""),
array("paypal","0","2","",""),
array("pottery barn","0","2","",""),
array("priceline","0","2","",""),
array("pokemon","1","4","",""),
array("poems","2","3","",""),
array("pregnancy","2","3","",""),
array("pandora","0","","",""),
array("pirate bay","0","","",""),
array("papa johns","0","","",""),
array("people","0","","",""),
array("ps3","1","","",""),
array("psp","1","","",""),
array("playstation 3","1","","",""),
array("p90x","1","","",""),
array("ps3 games","1","","",""),
array("pokemon platinum","1","","",""),
array("portable dvd player","1","","",""),
array("psp games","1","","",""),
array("ps3 console","1","","",""),
array("pogo","2","","",""),
array("powerball","2","","",""),
array("pregnancy week by week","3","","",""),
array("pregnancy first signs","3","","",""),
array("periodic table","3","","",""),
array("periodic table of elements","3","","",""),
array("photobucket.com","3","","",""),
array("pink","4","","",""),
array("paramore","4","","",""),
array("poker face","4","","",""),
array("pink so what","4","","",""),
array("phil collins","4","","",""),
array("paramore decode","4","","",""),
array("pink sober","4","","",""),
array("plies","4","","",""),
array("pop champagne","4","","","")),
"q" => array(
array("quotes","0","2","3",""),
array("qvc","0","2","3",""),
array("quantum of solace","0","1","4",""),
array("quizzes","0","2","3",""),
array("quickbooks","0","1","2",""),
array("qantas","0","2","",""),
array("quicktime","0","2","",""),
array("quiznos","0","2","",""),
array("qwest","0","2","",""),
array("queen","1","4","",""),
array("quizilla","2","3","",""),
array("quest diagnostics","0","","",""),
array("quickbooks pro 2009","1","","",""),
array("quicken","1","","",""),
array("quiksilver","1","","",""),
array("quantum of solace dvd","1","","",""),
array("quarantine","1","","",""),
array("queer as folk","1","","",""),
array("quicken 2009","1","","",""),
array("query string","2","","",""),
array("qvc.com","3","","",""),
array("quotes by famous people","3","","",""),
array("quotes on life","3","","",""),
array("quotes about life","3","","",""),
array("questions to ask your boyfriend","3","","",""),
array("quotes to live by","3","","",""),
array("queen bohemian rhapsody","4","","",""),
array("queens of the stone age","4","","",""),
array("queensberry","4","","",""),
array("queen we will rock you","4","","",""),
array("que tengo que hacer","4","","",""),
array("quest crew","4","","",""),
array("quality","4","","",""),
array("queen don't stop me now","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("espn","0","2","3",""),
array("eminem","1","2","4",""),
array("expedia","0","2","",""),
array("express","0","2","",""),
array("ed hardy","0","1","",""),
array("edward cullen","0","","",""),
array("ebay motors","0","","",""),
array("earth","0","","",""),
array("ebuddy","0","","",""),
array("exchange rates","0","","",""),
array("external hard drive","1","","",""),
array("empire total war","1","","",""),
array("eat this not that","1","","",""),
array("earbuds","1","","",""),
array("eclipse","1","","",""),
array("earphones","1","","",""),
array("external hard drive 1tb","1","","",""),
array("eee pc","1","","",""),
array("ecards","2","","",""),
array("emma watson","2","","",""),
array("enterprise","2","","",""),
array("eva longoria","2","","",""),
array("easyjet","2","","",""),
array("ebay.com","3","","",""),
array("english to spanish translation","3","","",""),
array("early pregnancy symptoms","3","","",""),
array("expedia.com","3","","",""),
array("electoral college","3","","",""),
array("espn.com","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("enterprise car rental","3","","",""),
array("enrique iglesias","4","","",""),
array("evanescence","4","","",""),
array("evolution of dance","4","","",""),
array("eye of the tiger","4","","",""),
array("elvis presley","4","","",""),
array("elton john","4","","",""),
array("enya","4","","",""),
array("eric clapton","4","","",""),
array("eminem lose yourself","4","","","")),
"s" => array(
array("sears","0","2","3",""),
array("southwest airlines","0","2","3",""),
array("skype","0","2","",""),
array("staples","0","2","",""),
array("sams club","0","3","",""),
array("sprint","0","2","",""),
array("sony","0","2","",""),
array("slumdog millionaire","0","1","",""),
array("song lyrics","2","3","",""),
array("shakira","2","4","",""),
array("sports authority","0","","",""),
array("samsung","0","","",""),
array("street fighter 4","1","","",""),
array("shoes","1","","",""),
array("star wars","1","","",""),
array("street fighter iv","1","","",""),
array("sunglasses","1","","",""),
array("slumdog millionaire soundtrack","1","","",""),
array("sims 3","1","","",""),
array("street fighter","1","","",""),
array("sd card","1","","",""),
array("southwest","2","","",""),
array("sudoku","2","","",""),
array("sarah palin","3","","",""),
array("search engines","3","","",""),
array("symptoms of pregnancy in the first week","3","","",""),
array("sears.com","3","","",""),
array("spanish dictionary","3","","",""),
array("song lyric search","3","","",""),
array("single ladies","4","","",""),
array("soulja boy","4","","",""),
array("sean paul","4","","",""),
array("slipknot","4","","",""),
array("single ladies beyonce","4","","",""),
array("selena gomez","4","","",""),
array("superhuman","4","","",""),
array("so what","4","","",""),
array("smosh","4","","","")),
"t" => array(
array("twilight","0","1","3","4"),
array("target","0","2","3",""),
array("travelocity","0","2","3",""),
array("taylor swift","1","2","4",""),
array("toys r us","0","3","",""),
array("ticketmaster","0","2","",""),
array("thesaurus","0","3","",""),
array("translator","0","3","",""),
array("tv guide","0","3","",""),
array("tattoos","2","3","",""),
array("twilight movie","3","4","",""),
array("tmobile","0","","",""),
array("toyota","0","","",""),
array("twilight dvd","1","","",""),
array("the shack","1","","",""),
array("turbotax","1","","",""),
array("tv","1","","",""),
array("twilight series","1","","",""),
array("the fray","1","","",""),
array("transformers","1","","",""),
array("twilight merchandise","1","","",""),
array("the bachelor","2","","",""),
array("t-mobile","2","","",""),
array("tesco","2","","",""),
array("tagged","2","","",""),
array("twitter","2","","",""),
array("target.com","3","","",""),
array("t.i","4","","",""),
array("taylor swift love story","4","","",""),
array("the game","4","","",""),
array("the killers","4","","",""),
array("titanic","4","","",""),
array("tom and jerry","4","","",""),
array("t pain","4","","","")),
"u" => array(
array("usps","0","2","3",""),
array("ups","0","2","3",""),
array("united airlines","0","2","3",""),
array("ufc","0","2","4",""),
array("utube","0","3","",""),
array("us airways","0","2","",""),
array("uggs","0","1","",""),
array("u2","1","4","",""),
array("umbrella","1","4","",""),
array("ugg boots","1","3","",""),
array("used cars","2","3","",""),
array("u tube","2","3","",""),
array("utorrent","0","","",""),
array("ups tracking","0","","",""),
array("urban dictionary","0","","",""),
array("u2 no line on the horizon","1","","",""),
array("unlocked cell phones","1","","",""),
array("usb flash drive","1","","",""),
array("usb hub","1","","",""),
array("under armour","1","","",""),
array("underworld","1","","",""),
array("univision","2","","",""),
array("utusan malaysia","2","","",""),
array("usaa","2","","",""),
array("united states map","3","","",""),
array("utube.com","3","","",""),
array("unique baby names","3","","",""),
array("usher","4","","",""),
array("untouched","4","","",""),
array("una","4","","",""),
array("ufo","4","","",""),
array("undead hollywood","4","","",""),
array("unforgivable","4","","",""),
array("untouched the veronicas","4","","","")),
"v" => array(
array("video","0","2","3","4"),
array("verizon wireless","0","2","3",""),
array("verizon","0","2","3",""),
array("victoria secret","0","3","",""),
array("vodafone","0","2","",""),
array("valkyrie","0","4","",""),
array("victoria's secret","1","2","",""),
array("vanessa hudgens","2","4","",""),
array("value city furniture","2","3","",""),
array("vlc","0","","",""),
array("virgin mobile","0","","",""),
array("virgin","0","","",""),
array("veoh","0","","",""),
array("vacuum cleaner","1","","",""),
array("van morrison","1","","",""),
array("vacuum","1","","",""),
array("video camera","1","","",""),
array("verizon cell phones","1","","",""),
array("vera bradley","1","","",""),
array("vizio","1","","",""),
array("vans","1","","",""),
array("video games","1","","",""),
array("vh1","2","","",""),
array("volkswagen","2","","",""),
array("vonage","2","","",""),
array("very early symptoms of pregnancy","3","","",""),
array("videos","3","","",""),
array("verizon.com","3","","",""),
array("very early pregnancy signs","3","","",""),
array("vampires","3","","",""),
array("viva la vida","4","","",""),
array("vicente fernandez","4","","",""),
array("van halen","4","","",""),
array("vegas","4","","",""),
array("videos de risa","4","","",""),
array("viva la vida coldplay","4","","",""),
array("vampire weekend","4","","","")),
"w" => array(
array("wikipedia","0","2","3",""),
array("weather","0","2","3",""),
array("white pages","0","2","3",""),
array("webkinz","0","1","2",""),
array("walmart","0","3","",""),
array("www.youtube.com","0","3","",""),
array("www.yahoo.com","0","","",""),
array("wiki","0","","",""),
array("wells fargo","0","","",""),
array("web md","0","","",""),
array("wii","1","","",""),
array("wii fit","1","","",""),
array("watchmen","1","","",""),
array("wii games","1","","",""),
array("wii console","1","","",""),
array("wireless router","1","","",""),
array("watches","1","","",""),
array("webcam","1","","",""),
array("wii fit bundle","1","","",""),
array("wal mart","2","","",""),
array("wallpaper","2","","",""),
array("wachovia","2","","",""),
array("walgreens","2","","",""),
array("washington mutual","2","","",""),
array("wamu","2","","",""),
array("walmart.com","3","","",""),
array("www.google.com","3","","",""),
array("what happened to jeeves","3","","",""),
array("what does my name mean","3","","",""),
array("where can i find pictures of hairstyles","3","","",""),
array("womanizer","4","","",""),
array("whatever you like","4","","",""),
array("wwe","4","","",""),
array("when i grow up","4","","",""),
array("wisin y yandel","4","","",""),
array("womanizer britney","4","","",""),
array("whitney houston","4","","",""),
array("wow","4","","",""),
array("westlife","4","","",""),
array("whatever you like ti","4","","","")),
"x" => array(
array("xbox 360","0","1","2","3"),
array("xbox","0","1","2","3"),
array("xm radio","0","2","3",""),
array("xbox 360 games","0","1","3",""),
array("xanax","0","2","3",""),
array("xbox live","0","1","",""),
array("x factor","0","4","",""),
array("xvid","0","2","",""),
array("xe","0","","",""),
array("xkcd","0","","",""),
array("xbox 360 console","1","","",""),
array("xbox 360 controller","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("xbox 360 wireless adapter","1","","",""),
array("xbox 360 elite","1","","",""),
array("xbox live gold","1","","",""),
array("xm","2","","",""),
array("xhamster movies","2","","",""),
array("xerox","2","","",""),
array("xenical","2","","",""),
array("xbox 360 red ring of death","2","","",""),
array("x tube","3","","",""),
array("xbox 360 cheats","3","","",""),
array("xanga","3","","",""),
array("xm satellite radio","3","","",""),
array("x tube videos","3","","",""),
array("x factor 2008","4","","",""),
array("xzibit","4","","",""),
array("xtreme","4","","",""),
array("xatzigiannis","4","","",""),
array("xavier naidoo","4","","",""),
array("x men origins wolverine trailer","4","","",""),
array("xbox 720","4","","","")),
"y" => array(
array("youtube","0","2","3","4"),
array("yahoo","0","2","3",""),
array("yahoo mail","0","2","3",""),
array("yellow pages","0","2","3",""),
array("yahoo messenger","0","2","",""),
array("yahoo maps","0","2","",""),
array("yes man","1","4","",""),
array("young jeezy","1","4","",""),
array("youtube videos","2","3","",""),
array("you tube","2","3","",""),
array("yahoo answers","0","","",""),
array("yahoo finance","0","","",""),
array("y8","0","","",""),
array("yahoo.com mail","0","","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yoga dvd","1","","",""),
array("your baby can read","1","","",""),
array("yeah yeah yeahs","1","","",""),
array("yarn","1","","",""),
array("yo gabba gabba","1","","",""),
array("yugioh","1","","",""),
array("yamaha","2","","",""),
array("yahoo games","2","","",""),
array("yahoo.com","3","","",""),
array("youtube.com","3","","",""),
array("yellowpages.com","3","","",""),
array("you tube.com","3","","",""),
array("you found me","4","","",""),
array("you can have whatever you like","4","","",""),
array("you","4","","",""),
array("you found me the fray","4","","",""),
array("young buck","4","","",""),
array("you and me","4","","",""),
array("youtube poop","4","","","")),
"z" => array(
array("zip codes","0","2","3",""),
array("zales","0","2","3",""),
array("zac efron","2","3","4",""),
array("zappos","0","2","",""),
array("zillow","0","2","",""),
array("zune","0","1","",""),
array("zedge","0","2","",""),
array("zeitgeist","0","4","",""),
array("zelda","1","4","",""),
array("zellers","0","","",""),
array("zip codes by city","0","","",""),
array("zero punctuation","0","","",""),
array("zack and miri","1","","",""),
array("zumba","1","","",""),
array("zippo","1","","",""),
array("zune 120","1","","",""),
array("zune accessories","1","","",""),
array("zippo lighter","1","","",""),
array("zojirushi","1","","",""),
array("zen","1","","",""),
array("zaba search","2","","",""),
array("zuma","2","","",""),
array("zaba","2","","",""),
array("zip code lookup","2","","",""),
array("zip code finder","3","","",""),
array("zodiac signs","3","","",""),
array("zipcodes","3","","",""),
array("zip code directory","3","","",""),
array("zillatube","3","","",""),
array("zip codes listings","3","","",""),
array("zodiac signs meanings","3","","",""),
array("zombie","4","","",""),
array("zz top","4","","",""),
array("zidane","4","","",""),
array("zoey 101","4","","",""),
array("zombie nation","4","","",""),
array("zion","4","","",""),
array("zac efron and vanessa hudgens in bed","4","","","")));
?>