<?php $topResults = array(
"a" => array(
array("amazon","0","1","2",""),
array("aol","0","2","",""),
array("apple","0","1","",""),
array("american airlines","0","2","",""),
array("at&t","2","3","",""),
array("att","0","","",""),
array("aim","0","","",""),
array("abc","0","","",""),
array("amc","0","","",""),
array("amtrak","0","","",""),
array("ask","0","","",""),
array("apple tv","1","","",""),
array("airsoft guns","1","","",""),
array("adidas","1","","",""),
array("avatar","1","","",""),
array("alarm clock","1","","",""),
array("apple ipad","1","","",""),
array("archos","1","","",""),
array("airsoft","1","","",""),
array("ask jeeves","2","","",""),
array("american idol","2","","",""),
array("autotrader","2","","",""),
array("american express","2","","",""),
array("angelina jolie","2","","",""),
array("addicting games","2","","",""),
array("aaron hernandez","3","","",""),
array("amy irving","3","","",""),
array("afi life achievement award","3","","",""),
array("apartments for rent","3","","",""),
array("airline tickets","3","","",""),
array("att.com","3","","",""),
array("are vampires real","3","","",""),
array("area codes","3","","",""),
array("address search","3","","",""),
array("airplanes","4","","",""),
array("alejandro lady gaga","4","","",""),
array("airplanes b.o.b","4","","",""),
array("annoying orange","4","","",""),
array("akon","4","","",""),
array("alejandro","4","","",""),
array("alicia keys","4","","",""),
array("airplanes hayley williams","4","","",""),
array("avril lavigne","4","","",""),
array("america's got talent 2010","4","","","")),
"b" => array(
array("best buy","0","2","3",""),
array("bed bath and beyond","0","2","3",""),
array("bank of america","0","2","",""),
array("bing","0","3","",""),
array("blockbuster","0","2","",""),
array("barnes and noble","0","2","",""),
array("britney spears","2","4","",""),
array("baby names","2","3","",""),
array("big 5","0","","",""),
array("borders","0","","",""),
array("big lots","0","","",""),
array("bp","0","","",""),
array("blackberry","1","","",""),
array("blackberry torch","1","","",""),
array("beauty and the beast","1","","",""),
array("bluetooth headset","1","","",""),
array("black ops","1","","",""),
array("backpack","1","","",""),
array("blackberry bold 9700","1","","",""),
array("blackberry unlocked","1","","",""),
array("bose","1","","",""),
array("boots","1","","",""),
array("blank","2","","",""),
array("bbc","2","","",""),
array("babies r us","2","","",""),
array("be the dean","3","","",""),
array("bake for the cure","3","","",""),
array("betty crocker","3","","",""),
array("bing.com","3","","",""),
array("bestbuy.com","3","","",""),
array("best buy.com","3","","",""),
array("baby justin bieber","4","","",""),
array("billionaire","4","","",""),
array("beyonce","4","","",""),
array("baby","4","","",""),
array("billionaire travis mccoy","4","","",""),
array("black eyed peas","4","","",""),
array("bad romance","4","","",""),
array("break your heart","4","","",""),
array("bob marley","4","","","")),
"c" => array(
array("craigslist","0","2","",""),
array("chase","0","2","",""),
array("costco","0","2","",""),
array("cnn","0","2","",""),
array("calorie counter","3","4","",""),
array("california dmv","0","","",""),
array("citibank","0","","",""),
array("carmax","0","","",""),
array("cnet","0","","",""),
array("cvs","0","","",""),
array("craigslist los angeles","0","","",""),
array("civilization 5","1","","",""),
array("call of duty black ops","1","","",""),
array("camera","1","","",""),
array("canon 7d","1","","",""),
array("coffee maker","1","","",""),
array("costumes","1","","",""),
array("crocs","1","","",""),
array("cataclysm","1","","",""),
array("cell phone","1","","",""),
array("canon","1","","",""),
array("circuit city","2","","",""),
array("chat","2","","",""),
array("cingular","2","","",""),
array("cartoon network","2","","",""),
array("capital one","2","","",""),
array("comcast","2","","",""),
array("cameron wake","3","","",""),
array("chris sarandon","3","","",""),
array("caleb hanie","3","","",""),
array("cheap airline tickets","3","","",""),
array("cash for clunkers","3","","",""),
array("cheap flights","3","","",""),
array("cellular service","3","","",""),
array("car rentals","3","","",""),
array("calculator","3","","",""),
array("california gurls katy perry","4","","",""),
array("chris brown","4","","",""),
array("cooler than me mike posner","4","","",""),
array("chris brown deuces","4","","",""),
array("charlie bit my finger","4","","",""),
array("cooler than me","4","","",""),
array("christina aguilera","4","","",""),
array("california gurls katy perry lyrics","4","","",""),
array("ciara","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("delta airlines","0","2","3",""),
array("dmv","0","2","",""),
array("droid x","0","1","",""),
array("drake","0","4","",""),
array("dell","0","2","",""),
array("driving directions","2","3","",""),
array("disneyland","0","","",""),
array("dodgers","0","","",""),
array("dominos","0","","",""),
array("direct tv","0","","",""),
array("dead rising 2","1","","",""),
array("digital camera","1","","",""),
array("dexter","1","","",""),
array("diapers","1","","",""),
array("dsi","1","","",""),
array("dvd player","1","","",""),
array("d7000","1","","",""),
array("dsi xl","1","","",""),
array("dvd","1","","",""),
array("disney channel","2","","",""),
array("dancing with the stars","2","","",""),
array("dish network","2","","",""),
array("danica patrick","2","","",""),
array("directv","2","","",""),
array("danny woodhead","3","","",""),
array("dwight","3","","",""),
array("deputados","3","","",""),
array("disneychannel.com","3","","",""),
array("does justin bieber have a girlfriend","3","","",""),
array("distance between 2 cities","3","","",""),
array("dictionary.com","3","","",""),
array("dynamite taio cruz","4","","",""),
array("drake find your love","4","","",""),
array("double rainbow","4","","",""),
array("david guetta","4","","",""),
array("dynamite","4","","",""),
array("drake miss me","4","","",""),
array("demi lovato","4","","",""),
array("drake over","4","","",""),
array("deuces chris brown","4","","","")),
"e" => array(
array("eminem","0","1","2","4"),
array("ebay","0","2","3",""),
array("espn","0","2","",""),
array("expedia","0","2","",""),
array("enterprise car rental","2","3","",""),
array("edc","0","","",""),
array("edd","0","","",""),
array("evite","0","","",""),
array("espn3","0","","",""),
array("edison","0","","",""),
array("etsy","0","","",""),
array("external hard drive","1","","",""),
array("eclipse","1","","",""),
array("earphones","1","","",""),
array("earth","1","","",""),
array("eat pray love","1","","",""),
array("earbuds","1","","",""),
array("eclipse dvd","1","","",""),
array("ethernet cable","1","","",""),
array("espresso machine","1","","",""),
array("ecards","2","","",""),
array("elin nordegren","2","","",""),
array("ebay motors","2","","",""),
array("eva longoria","2","","",""),
array("eharmony","2","","",""),
array("eva amurri","3","","",""),
array("espnu college town","3","","",""),
array("edwards","3","","",""),
array("ebay.com","3","","",""),
array("expedia.com","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("english to spanish translation","3","","",""),
array("engagement rings","3","","",""),
array("eminem not afraid","4","","",""),
array("eminem love the way you lie","4","","",""),
array("enrique iglesias i like it","4","","",""),
array("enrique iglesias","4","","",""),
array("eminem recovery","4","","",""),
array("eminem ft rihanna","4","","",""),
array("eenie meenie justin bieber","4","","",""),
array("eenie meenie","4","","",""),
array("eminem beautiful","4","","","")),
"f" => array(
array("facebook","0","2","3",""),
array("firefox","0","2","",""),
array("fedex","0","2","",""),
array("fafsa","0","2","",""),
array("food network","0","2","",""),
array("family guy","1","4","",""),
array("free online games","2","3","",""),
array("free music downloads","2","3","",""),
array("facebook login","0","","",""),
array("fifa","0","","",""),
array("fandango","0","","",""),
array("frys","0","","",""),
array("forever 21","0","","",""),
array("fifa 11","1","","",""),
array("freedom","1","","",""),
array("flash drive","1","","",""),
array("fallout new vegas","1","","",""),
array("final fantasy xiv","1","","",""),
array("fable 3","1","","",""),
array("f1 2010","1","","",""),
array("food processor","1","","",""),
array("fleshlight","1","","",""),
array("fox news","2","","",""),
array("fantasy football","2","","",""),
array("ford","2","","",""),
array("face transplant","3","","",""),
array("fail whale","3","","",""),
array("free ringtones","3","","",""),
array("free games","3","","",""),
array("free people search","3","","",""),
array("find a person","3","","",""),
array("free credit report","3","","",""),
array("funny video","4","","",""),
array("funny","4","","",""),
array("fred","4","","",""),
array("female hair transplant","4","","",""),
array("funny pranks","4","","",""),
array("funny cats","4","","",""),
array("find your love drake","4","","",""),
array("flip top","4","","",""),
array("fireflies","4","","","")),
"g" => array(
array("google maps","0","2","3",""),
array("glee","0","1","4",""),
array("games","0","2","3",""),
array("gmail","0","2","",""),
array("google earth","0","2","",""),
array("google","2","4","",""),
array("google search","2","3","",""),
array("google.com","0","","",""),
array("google translate","0","","",""),
array("gamestop","0","","",""),
array("google voice","0","","",""),
array("gary coleman","0","","",""),
array("gps","1","","",""),
array("garmin","1","","",""),
array("gift card","1","","",""),
array("guitar","1","","",""),
array("gran turismo 5","1","","",""),
array("get him to the greek","1","","",""),
array("garmin gps","1","","",""),
array("guitar hero","1","","",""),
array("garmin nuvi","1","","",""),
array("google homepage","2","","",""),
array("gap","2","","",""),
array("greeting cards","2","","",""),
array("guitar tabs","2","","",""),
array("gainesville shooting","3","","",""),
array("gainesville sun","3","","",""),
array("great wolf lodge","3","","",""),
array("google search engine","3","","",""),
array("games.com","3","","",""),
array("girl games","3","","",""),
array("games for kids","3","","",""),
array("gummy bear song","4","","",""),
array("gucci mane","4","","",""),
array("green day","4","","",""),
array("ghost","4","","",""),
array("getting over you david guetta","4","","",""),
array("gorillaz","4","","",""),
array("ghost caught on tape","4","","",""),
array("guns n roses","4","","","")),
"h" => array(
array("hulu","0","2","3",""),
array("home depot","0","2","3",""),
array("hotmail","0","2","",""),
array("honda","0","2","",""),
array("halo reach","1","4","",""),
array("halloween costumes","1","2","",""),
array("halo","1","4","",""),
array("harry potter","1","2","",""),
array("halloween","1","3","",""),
array("how to kiss","3","4","",""),
array("hollywood bowl","0","","",""),
array("h&m","0","","",""),
array("hp","0","","",""),
array("hotels.com","0","","",""),
array("hbo","0","","",""),
array("hertz","0","","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("how to train your dragon","1","","",""),
array("hello kitty","1","","",""),
array("halloween decorations","1","","",""),
array("horoscopes","2","","",""),
array("holiday inn","2","","",""),
array("hi5","2","","",""),
array("harian metro","2","","",""),
array("halloweentown","3","","",""),
array("how much should i weigh","3","","",""),
array("how to get pregnant","3","","",""),
array("how do you spell a word","3","","",""),
array("how to make a website","3","","",""),
array("hotmail.com","3","","",""),
array("hey soul sister","4","","",""),
array("hannah montana","4","","",""),
array("harry potter and the deathly hallows trailer","4","","",""),
array("happy tree friends","4","","",""),
array("hello good morning","4","","",""),
array("hannah montana songs","4","","",""),
array("hallelujah","4","","","")),
"i" => array(
array("itunes","0","2","3",""),
array("iphone 4","0","1","4",""),
array("ipad","0","1","3",""),
array("iphone","0","1","2",""),
array("ikea","0","2","",""),
array("imdb","0","2","",""),
array("inception","0","4","",""),
array("irs","0","2","",""),
array("ign","0","2","",""),
array("ipod touch","1","3","",""),
array("ipod","1","2","",""),
array("inspirational quotes","2","3","",""),
array("images","0","","",""),
array("ipod nano","1","","",""),
array("iron man 2","1","","",""),
array("ipod touch 4th generation","1","","",""),
array("iphone 4 case","1","","",""),
array("iphone 3gs","1","","",""),
array("internet explorer","2","","",""),
array("imeem","2","","",""),
array("ice road truckers","3","","",""),
array("inbetweeners","3","","",""),
array("infertile","3","","",""),
array("is the world going to end in 2012","3","","",""),
array("italy travel","3","","",""),
array("internet explorer 8","3","","",""),
array("i love the way you lie","4","","",""),
array("i like it enrique iglesias","4","","",""),
array("i like it","4","","",""),
array("inception trailer","4","","",""),
array("impossible shontelle","4","","",""),
array("i wanna be a billionaire","4","","",""),
array("in my head jason derulo","4","","",""),
array("inna","4","","","")),
"j" => array(
array("justin bieber","0","1","3","4"),
array("jobs","0","2","3",""),
array("java","0","2","",""),
array("jokes","0","2","",""),
array("jet blue","0","","",""),
array("john wooden","0","","",""),
array("justin tv","0","","",""),
array("jamba juice","0","","",""),
array("jersey shore","0","","",""),
array("jack in the box","0","","",""),
array("jimmy eat world","1","","",""),
array("jillian michaels","1","","",""),
array("juicer","1","","",""),
array("juicy couture","1","","",""),
array("jansport backpack","1","","",""),
array("jewelry box","1","","",""),
array("jack3d","1","","",""),
array("jewelry","1","","",""),
array("john legend","1","","",""),
array("jessica simpson","2","","",""),
array("jcpenney","2","","",""),
array("jessica alba","2","","",""),
array("jennifer lopez","2","","",""),
array("jennifer aniston","2","","",""),
array("jetblue","2","","",""),
array("jennifer love hewitt","2","","",""),
array("jay cutler","3","","",""),
array("jong","3","","",""),
array("jack conway","3","","",""),
array("jobs in my area","3","","",""),
array("justin bieber cell number","3","","",""),
array("job search","3","","",""),
array("jcpenney.com","3","","",""),
array("justin bieber quiz","3","","",""),
array("justin bieber baby","4","","",""),
array("justin bieber eenie meenie","4","","",""),
array("justin bieber one time","4","","",""),
array("justin bieber somebody to love","4","","",""),
array("justin bieber never say never","4","","",""),
array("jason derulo ridin solo","4","","",""),
array("justin bieber love me","4","","",""),
array("justin timberlake","4","","",""),
array("jay z","4","","","")),
"k" => array(
array("kmart","0","2","3",""),
array("katy perry","0","1","4",""),
array("kohls","0","3","",""),
array("ktla","0","","",""),
array("kroq","0","","",""),
array("kayak","0","","",""),
array("kcrw","0","","",""),
array("kaiser","0","","",""),
array("knotts berry farm","0","","",""),
array("kfc","0","","",""),
array("kindle","1","","",""),
array("kindle cover","1","","",""),
array("kinect","1","","",""),
array("keurig","1","","",""),
array("kindle books","1","","",""),
array("k cups","1","","",""),
array("keyboard","1","","",""),
array("kitchenaid mixer","1","","",""),
array("kindle dx","1","","",""),
array("kim kardashian","2","","",""),
array("kelley blue book","2","","",""),
array("kohl's","2","","",""),
array("kelly clarkson","2","","",""),
array("kristen stewart","2","","",""),
array("kate gosselin","2","","",""),
array("keira knightley","2","","",""),
array("katie holmes","2","","",""),
array("katherine heigl","2","","",""),
array("kelly ripa","3","","",""),
array("kandi","3","","",""),
array("keri","3","","",""),
array("kohls.com","3","","",""),
array("kelly blue book","3","","",""),
array("kmart.com","3","","",""),
array("kids games","3","","",""),
array("kijiji","3","","",""),
array("katy perry california girlz","4","","",""),
array("katy perry california","4","","",""),
array("keong racun","4","","",""),
array("kesha your love is my drug","4","","",""),
array("kiss","4","","",""),
array("kid cudi","4","","",""),
array("kanye west power","4","","",""),
array("kanye west","4","","",""),
array("katy perry teenage dream","4","","","")),
"l" => array(
array("lyrics","0","2","3",""),
array("lost","0","1","2",""),
array("lady gaga","1","2","4",""),
array("lil wayne","1","2","4",""),
array("lakers","0","3","",""),
array("lowes","0","3","",""),
array("limewire","0","2","",""),
array("linkin park","1","4","",""),
array("love poems","2","3","",""),
array("love quotes","2","3","",""),
array("la times","0","","",""),
array("lax","0","","",""),
array("la fitness","0","","",""),
array("lacma","0","","",""),
array("lausd","0","","",""),
array("laptop","1","","",""),
array("lego","1","","",""),
array("luggage","1","","",""),
array("lego star wars","1","","",""),
array("laptop computer","1","","",""),
array("lcd tv","1","","",""),
array("lindsay lohan","2","","",""),
array("lowe's","2","","",""),
array("las vegas","2","","",""),
array("lisa kelly","3","","",""),
array("lecture","3","","",""),
array("lyrics to songs","3","","",""),
array("lowes.com","3","","",""),
array("lingerie","3","","",""),
array("love the way you lie","4","","",""),
array("lady gaga alejandro","4","","",""),
array("love the way you lie eminem","4","","",""),
array("loan mods","4","","",""),
array("lady gaga bad romance","4","","",""),
array("love the way you lie lyrics","4","","",""),
array("love","4","","","")),
"m" => array(
array("myspace","0","2","",""),
array("mapquest","0","2","",""),
array("msn","0","2","",""),
array("maps","0","3","",""),
array("mtv","0","2","",""),
array("movies","0","2","",""),
array("macy's","0","2","",""),
array("music","2","4","",""),
array("michaels","0","","",""),
array("metrolink","0","","",""),
array("metro pcs","0","","",""),
array("mouse","1","","",""),
array("macbook","1","","",""),
array("mp3 player","1","","",""),
array("macbook pro","1","","",""),
array("modern family","1","","",""),
array("maroon 5","1","","",""),
array("micro sd","1","","",""),
array("medal of honor","1","","",""),
array("madden 11","1","","",""),
array("mad men","1","","",""),
array("mail","2","","",""),
array("miniclip","2","","",""),
array("megan fox","2","","",""),
array("monday night football live","3","","",""),
array("mlb","3","","",""),
array("microsoft bing","3","","",""),
array("mapquest driving directions","3","","",""),
array("myspace layouts","3","","",""),
array("mortgage calculator","3","","",""),
array("medical dictionary","3","","",""),
array("math answers","3","","",""),
array("meaning of names","3","","",""),
array("michael jackson","4","","",""),
array("miley cyrus","4","","",""),
array("my wife having an affair","4","","",""),
array("mariah carey","4","","",""),
array("my first kiss","4","","",""),
array("miley cyrus can't be tamed","4","","",""),
array("metallica","4","","",""),
array("magic b.o.b","4","","",""),
array("miley cyrus party in the usa","4","","","")),
"n" => array(
array("netflix","0","2","3",""),
array("nissan","0","2","3",""),
array("nordstrom","0","2","",""),
array("nba","0","2","",""),
array("news","0","3","",""),
array("nbc","0","2","",""),
array("nike","0","1","",""),
array("nfl","2","3","",""),
array("nascar","2","3","",""),
array("newegg","0","","",""),
array("noaa","0","","",""),
array("npr","0","","",""),
array("netbook","1","","",""),
array("nintendo ds","1","","",""),
array("nikon d90","1","","",""),
array("nikon d7000","1","","",""),
array("nokia n8","1","","",""),
array("nintendo dsi","1","","",""),
array("nikon d5000","1","","",""),
array("nook","1","","",""),
array("nba 2k11","1","","",""),
array("nick jr","2","","",""),
array("nokia","2","","",""),
array("northwest airlines","2","","",""),
array("nene leakes","3","","",""),
array("name meanings","3","","",""),
array("netflix.com","3","","",""),
array("nudyphotos","3","","",""),
array("nissan.com","3","","",""),
array("not afraid eminem","4","","",""),
array("nicki minaj","4","","",""),
array("never say never","4","","",""),
array("never say never justin bieber","4","","",""),
array("nicki minaj your love","4","","",""),
array("nigahiga","4","","",""),
array("not afraid","4","","",""),
array("new songs 2010","4","","",""),
array("nickelback","4","","",""),
array("nothing on you b.o.b","4","","","")),
"o" => array(
array("old navy","0","2","3",""),
array("orbitz","0","2","",""),
array("office depot","0","2","",""),
array("overstock","0","2","",""),
array("olive garden","0","2","",""),
array("online dictionary","2","3","",""),
array("online games","2","3","",""),
array("omg","2","4","",""),
array("oc fair","0","","",""),
array("osh","0","","",""),
array("oc register","0","","",""),
array("occ","0","","",""),
array("octa","0","","",""),
array("operation dark heart","1","","",""),
array("oakley","1","","",""),
array("otterbox","1","","",""),
array("otterbox iphone 4","1","","",""),
array("office 2010","1","","",""),
array("oakley sunglasses","1","","",""),
array("obama's wars","1","","",""),
array("one tree hill","1","","",""),
array("office chair","1","","",""),
array("ooma","1","","",""),
array("oprah","2","","",""),
array("orkut","2","","",""),
array("overland trail","3","","",""),
array("orphan","3","","",""),
array("offensive line","3","","",""),
array("online pregnancy test","3","","",""),
array("ovulation calendar","3","","",""),
array("ovulation calculator","3","","",""),
array("overstock.com","3","","",""),
array("omg usher","4","","",""),
array("oil rig employment","4","","",""),
array("old spice commercial","4","","",""),
array("old spice","4","","",""),
array("one time justin bieber","4","","",""),
array("one time","4","","",""),
array("over drake","4","","",""),
array("ordinary girl-hannah montana","4","","",""),
array("once upon a time in mumbai","4","","","")),
"p" => array(
array("photobucket","0","2","",""),
array("paypal","0","2","",""),
array("pizza hut","0","2","",""),
array("pottery barn","0","2","",""),
array("priceline","0","2","",""),
array("people search","2","3","",""),
array("pandora","0","","",""),
array("petco","0","","",""),
array("power 106","0","","",""),
array("party city","0","","",""),
array("pac-man 30th anniversary","0","","",""),
array("ps3","1","","",""),
array("playstation 3","1","","",""),
array("psp","1","","",""),
array("playstation move","1","","",""),
array("p90x","1","","",""),
array("ps3 move","1","","",""),
array("pillow pets","1","","",""),
array("ps3 games","1","","",""),
array("ps3 console","1","","",""),
array("posters","1","","",""),
array("pogo","2","","",""),
array("powerball","2","","",""),
array("people magazine","2","","",""),
array("petsmart","2","","",""),
array("pumpkin carvings","3","","",""),
array("phaedra parks","3","","",""),
array("plenty of fish","3","","",""),
array("pregnancy week by week","3","","",""),
array("priceline.com","3","","",""),
array("people finder","3","","",""),
array("phone number lookup","3","","",""),
array("people search for free","3","","",""),
array("pregnancy symptoms","3","","",""),
array("paramore","4","","",""),
array("pretty boy swag","4","","",""),
array("pitbull","4","","",""),
array("pyramid charice","4","","",""),
array("pink","4","","",""),
array("party in the usa","4","","",""),
array("pretty boy swag soulja boy","4","","",""),
array("pyramid","4","","",""),
array("poker face","4","","",""),
array("pokemon","4","","","")),
"q" => array(
array("quickbooks","0","1","2","3"),
array("quotes","0","2","3",""),
array("qvc","0","2","",""),
array("quicktime","0","2","",""),
array("quiznos","0","2","",""),
array("quest diagnostics","0","2","",""),
array("quotes about life","0","3","",""),
array("quicksilver","0","1","",""),
array("queen","1","4","",""),
array("quran","1","4","",""),
array("quizzes","2","3","",""),
array("queen mary","0","","",""),
array("quinoa","0","","",""),
array("quicken","1","","",""),
array("quiksilver","1","","",""),
array("quickbooks pro 2010","1","","",""),
array("quilt","1","","",""),
array("quicken 2011","1","","",""),
array("queen of hearts costume","1","","",""),
array("qwest","2","","",""),
array("query string","2","","",""),
array("quizilla","2","","",""),
array("qbs","3","","",""),
array("quarterbacks","3","","",""),
array("quotes of the day","3","","",""),
array("quotes and sayings","3","","",""),
array("quinceanera dresses","3","","",""),
array("quick mileage city to city","3","","",""),
array("queen bohemian rhapsody","4","","",""),
array("quest crew","4","","",""),
array("queen we will rock you","4","","",""),
array("queen don't stop me now","4","","",""),
array("queens of the stone age","4","","",""),
array("queen i want to break free","4","","",""),
array("queen somebody to love","4","","",""),
array("queen seondeok","4","","","")),
"e" => array(
array("eminem","0","1","2","4"),
array("ebay","0","2","3",""),
array("espn","0","2","",""),
array("expedia","0","2","",""),
array("enterprise car rental","2","3","",""),
array("edc","0","","",""),
array("edd","0","","",""),
array("evite","0","","",""),
array("espn3","0","","",""),
array("edison","0","","",""),
array("etsy","0","","",""),
array("external hard drive","1","","",""),
array("eclipse","1","","",""),
array("earphones","1","","",""),
array("earth","1","","",""),
array("eat pray love","1","","",""),
array("earbuds","1","","",""),
array("eclipse dvd","1","","",""),
array("ethernet cable","1","","",""),
array("espresso machine","1","","",""),
array("ecards","2","","",""),
array("elin nordegren","2","","",""),
array("ebay motors","2","","",""),
array("eva longoria","2","","",""),
array("eharmony","2","","",""),
array("eva amurri","3","","",""),
array("espnu college town","3","","",""),
array("edwards","3","","",""),
array("ebay.com","3","","",""),
array("expedia.com","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("english to spanish translation","3","","",""),
array("engagement rings","3","","",""),
array("eminem not afraid","4","","",""),
array("eminem love the way you lie","4","","",""),
array("enrique iglesias i like it","4","","",""),
array("enrique iglesias","4","","",""),
array("eminem recovery","4","","",""),
array("eminem ft rihanna","4","","",""),
array("eenie meenie justin bieber","4","","",""),
array("eenie meenie","4","","",""),
array("eminem beautiful","4","","","")),
"s" => array(
array("southwest airlines","0","2","3",""),
array("skype","0","2","",""),
array("sears","0","2","",""),
array("staples","0","2","",""),
array("sprint","0","2","",""),
array("song lyrics","2","3","",""),
array("shakira","2","4","",""),
array("sigalert","0","","",""),
array("subway","0","","",""),
array("starbucks","0","","",""),
array("speed test","0","","",""),
array("steam","0","","",""),
array("shoes","1","","",""),
array("silly bandz","1","","",""),
array("starcraft 2","1","","",""),
array("sunglasses","1","","",""),
array("scott pilgrim","1","","",""),
array("star wars","1","","",""),
array("sd card","1","","",""),
array("search amazon co","1","","",""),
array("supernatural","1","","",""),
array("speakers","1","","",""),
array("sony","2","","",""),
array("sandra bullock","2","","",""),
array("sarah palin","2","","",""),
array("sister wives episode 2","3","","",""),
array("scare tactics","3","","",""),
array("sunday night football","3","","",""),
array("spanish dictionary","3","","",""),
array("signs of pregnancy","3","","",""),
array("sexy","3","","",""),
array("swine flu symptoms","3","","",""),
array("spanish translator","3","","",""),
array("shakira waka waka","4","","",""),
array("solo","4","","",""),
array("somebody to love justin bieber","4","","",""),
array("selena gomez","4","","",""),
array("sexist video of man and woman","4","","",""),
array("solo iyaz","4","","",""),
array("shane dawson","4","","",""),
array("soulja boy","4","","",""),
array("stereo love","4","","","")),
"t" => array(
array("target","0","2","3",""),
array("taylor swift","1","2","4",""),
array("twitter","0","3","",""),
array("tmz","0","2","",""),
array("ticketmaster","0","2","",""),
array("travelocity","0","2","",""),
array("toy story 3","1","4","",""),
array("trey songz","1","4","",""),
array("translator","0","","",""),
array("thesaurus","0","","",""),
array("tmobile","0","","",""),
array("time warner cable","0","","",""),
array("trader joes","0","","",""),
array("tv","1","","",""),
array("true blood","1","","",""),
array("twilight","1","","",""),
array("the office","1","","",""),
array("the girl with the dragon tattoo","1","","",""),
array("toy story","1","","",""),
array("telescope","1","","",""),
array("toys r us","2","","",""),
array("toyota","2","","",""),
array("tagged","2","","",""),
array("t-mobile","2","","",""),
array("tiger woods","2","","",""),
array("tcheca","3","","",""),
array("tattoo designs","3","","",""),
array("tattoos","3","","",""),
array("translate english to spanish","3","","",""),
array("teen pregnancy signs","3","","",""),
array("translate spanish to english","3","","",""),
array("telephone directory","3","","",""),
array("tires","3","","",""),
array("teach me how to dougie","4","","",""),
array("teenage dream katy perry","4","","",""),
array("tik tok","4","","",""),
array("taio cruz dynamite","4","","",""),
array("the annoying orange","4","","",""),
array("tom and jerry","4","","",""),
array("teenage dream","4","","","")),
"u" => array(
array("ufc","0","2","4",""),
array("usps","0","2","",""),
array("ups","0","2","",""),
array("united airlines","0","2","",""),
array("univision","0","2","",""),
array("us bank","0","2","",""),
array("uggs","1","3","",""),
array("usher","1","4","",""),
array("used cars","2","3","",""),
array("us airways","2","3","",""),
array("utube","0","","",""),
array("urban outfitters","0","","",""),
array("uhaul","0","","",""),
array("ups tracking","0","","",""),
array("unlocked cell phones","1","","",""),
array("undefined","1","","",""),
array("usb flash drive","1","","",""),
array("umbrella","1","","",""),
array("usb hub","1","","",""),
array("under armour","1","","",""),
array("ugg boots","1","","",""),
array("uncharted 2","1","","",""),
array("utusan malaysia","2","","",""),
array("usaa","2","","",""),
array("us open","3","","",""),
array("ubs","3","","",""),
array("used cars for sale","3","","",""),
array("unique baby names","3","","",""),
array("unemployment benefits","3","","",""),
array("us airways.com","3","","",""),
array("used cars for sale in my area","3","","",""),
array("usher omg","4","","",""),
array("usher there goes my baby","4","","",""),
array("u2","4","","",""),
array("unthinkable alicia keys","4","","",""),
array("ufo","4","","",""),
array("usher daddy's home","4","","",""),
array("usher yeah","4","","",""),
array("up all night drake nicki minaj","4","","","")),
"v" => array(
array("verizon","0","2","3",""),
array("verizon wireless","0","2","3",""),
array("vans","0","1","",""),
array("verizon cell phones","1","3","",""),
array("victoria's secret","1","2","",""),
array("vanessa hudgens","2","4","",""),
array("vons","0","","",""),
array("vlc","0","","",""),
array("virgin america","0","","",""),
array("vimeo","0","","",""),
array("volaris","0","","",""),
array("victoria secret","0","","",""),
array("ventura county fair","0","","",""),
array("vacuum cleaner","1","","",""),
array("vampire diaries","1","","",""),
array("vera bradley","1","","",""),
array("video camera","1","","",""),
array("vibratores for women","1","","",""),
array("vacuum","1","","",""),
array("vibram five fingers","1","","",""),
array("video","2","","",""),
array("vh1","2","","",""),
array("value city furniture","2","","",""),
array("victoria beckham","2","","",""),
array("virgin mobile","2","","",""),
array("vonage","2","","",""),
array("vick","3","","",""),
array("viktor bout","3","","",""),
array("virginia ironside","3","","",""),
array("verizon.com","3","","",""),
array("verizonwireless.com","3","","",""),
array("virtual worlds","3","","",""),
array("very early symptoms of pregnancy","3","","",""),
array("vevo","4","","",""),
array("vybz kartel","4","","",""),
array("vanilla twilight","4","","",""),
array("vicente fernandez","4","","",""),
array("vampire weekend","4","","",""),
array("videos grasiosos","4","","",""),
array("van halen","4","","",""),
array("vanilla twilight owl city","4","","",""),
array("victorious","4","","","")),
"w" => array(
array("weather","0","2","3",""),
array("white pages","0","2","3",""),
array("wwe","2","3","4",""),
array("wells fargo","0","2","",""),
array("wikipedia","0","2","",""),
array("webmd","0","2","",""),
array("walgreens","0","2","",""),
array("walmart","0","","",""),
array("www.facebook.com","0","","",""),
array("wiki","0","","",""),
array("winrar","0","","",""),
array("wii","1","","",""),
array("watches","1","","",""),
array("wii games","1","","",""),
array("wireless router","1","","",""),
array("windows 7","1","","",""),
array("webcam","1","","",""),
array("wii console","1","","",""),
array("world of warcraft","1","","",""),
array("william shakespeare","1","","",""),
array("wireless mouse","1","","",""),
array("wal mart","2","","",""),
array("webkinz","2","","",""),
array("wachovia","2","","",""),
array("willis mcgahee","3","","",""),
array("waka","3","","",""),
array("what does my last name mean","3","","",""),
array("where can i watch free movies online","3","","",""),
array("what is love","3","","",""),
array("what is the meaning of my name","3","","",""),
array("when will the world end","3","","",""),
array("waka waka","4","","",""),
array("waka waka shakira","4","","",""),
array("we no speak americano","4","","",""),
array("waving flag","4","","",""),
array("wisin y yandel","4","","",""),
array("wiz khalifa","4","","",""),
array("waving flag k'naan","4","","",""),
array("what if jason derulo","4","","",""),
array("waka flocka flames","4","","","")),
"x" => array(
array("xbox 360","1","2","3","4"),
array("xbox live","0","1","2",""),
array("xm radio","0","2","3",""),
array("xbox","0","1","",""),
array("x games","0","2","",""),
array("xanax","0","2","",""),
array("x games 2010","0","4","",""),
array("xbox 360 slim","1","4","",""),
array("xbox 360 games","1","3","",""),
array("xbox cheats","2","3","",""),
array("x factor","2","4","",""),
array("xkcd","0","","",""),
array("xe","0","","",""),
array("xfire","0","","",""),
array("xbmc","0","","",""),
array("xbox 360 console","1","","",""),
array("xbox 360 controller","1","","",""),
array("xbox 360 wireless adapter","1","","",""),
array("xbox live 12 month","1","","",""),
array("xbox 360 elite","1","","",""),
array("xvid","2","","",""),
array("x17","2","","",""),
array("xerox","2","","",""),
array("xbox 360 cheats","3","","",""),
array("x ray schools","3","","",""),
array("xbox 360 cheat codes","3","","",""),
array("xxl tv live","3","","",""),
array("xbox 360 problems","3","","",""),
array("xm satellite radio","3","","",""),
array("xb gensan","4","","",""),
array("x factor 2010","4","","",""),
array("xzibit","4","","",""),
array("x","4","","",""),
array("xb gensan in show time","4","","",""),
array("xbox 360 kinect","4","","","")),
"y" => array(
array("youtube","0","2","3","4"),
array("yahoo mail","0","2","3",""),
array("yahoo","0","2","",""),
array("yahoo maps","0","2","",""),
array("yellow pages","0","3","",""),
array("young jeezy","1","4","",""),
array("yelp","0","","",""),
array("yahoo answers","0","","",""),
array("yahoomail.com","0","","",""),
array("yahoo movies","0","","",""),
array("yahoo finance","0","","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yo gabba gabba","1","","",""),
array("yoga dvd","1","","",""),
array("yugioh cards","1","","",""),
array("yarn","1","","",""),
array("your baby can read","1","","",""),
array("yugioh","1","","",""),
array("yankee candle","1","","",""),
array("youtube video","2","","",""),
array("yahoo messenger","2","","",""),
array("youtube broadcast yourself","2","","",""),
array("yamaha","2","","",""),
array("yahoo games","2","","",""),
array("yahoo music","2","","",""),
array("yosemite falls","3","","",""),
array("yoko ono","3","","",""),
array("youtube videos","3","","",""),
array("yellowpages.com","3","","",""),
array("yellow pages.com","3","","",""),
array("yahoo.com","3","","",""),
array("youtube music","3","","",""),
array("your love nicki minaj","4","","",""),
array("your love is my drug","4","","",""),
array("your love","4","","",""),
array("your love is my drug kesha","4","","",""),
array("you belong with me","4","","",""),
array("young money","4","","",""),
array("yolanda be cool we no speak americano","4","","",""),
array("you belong with me taylor swift","4","","","")),
"z" => array(
array("zip codes","0","2","3",""),
array("zumba","0","1","4",""),
array("zune","0","1","2",""),
array("zillow","0","2","",""),
array("zappos","0","2","",""),
array("zac brown band","1","4","",""),
array("zodiac signs","2","3","",""),
array("zac efron","2","4","",""),
array("zara","0","","",""),
array("zumiez","0","","",""),
array("zoosk","0","","",""),
array("z pizza","0","","",""),
array("z gallerie","0","","",""),
array("zune hd","1","","",""),
array("zumba fitness dvd","1","","",""),
array("zippo","1","","",""),
array("zhu zhu pets","1","","",""),
array("zoobles","1","","",""),
array("zumba dvd","1","","",""),
array("zelda","1","","",""),
array("zales","2","","",""),
array("zuma","2","","",""),
array("zaba search","2","","",""),
array("zedge","2","","",""),
array("zack snyder","3","","",""),
array("zip code finder","3","","",""),
array("zip code list","3","","",""),
array("zucchini bread recipes","3","","",""),
array("zucchini recipes","3","","",""),
array("zip code lookup","3","","",""),
array("zip code directory","3","","",""),
array("zappos.com","3","","",""),
array("zombie","4","","",""),
array("zombie cranberries","4","","",""),
array("zz top","4","","",""),
array("zidane","4","","",""),
array("zach galifianakis","4","","",""),
array("zzirgrizz","4","","",""),
array("zombieland","4","","","")));
?>