<?php $topResults = array(
"a" => array(
array("amazon","0","2","",""),
array("aol","0","2","",""),
array("american idol","0","2","",""),
array("american airlines","0","2","",""),
array("apple","0","1","",""),
array("addicting games","0","2","",""),
array("adele","1","4","",""),
array("allegiant air","0","","",""),
array("att","0","","",""),
array("auto trader","0","","",""),
array("abc","0","","",""),
array("air conditioner","1","","",""),
array("asus transformer","1","","",""),
array("airsoft guns","1","","",""),
array("adidas","1","","",""),
array("apple tv","1","","",""),
array("android","1","","",""),
array("airsoft","1","","",""),
array("android tablet","1","","",""),
array("anna kournikova","2","","",""),
array("at&t","2","","",""),
array("autotrader","2","","",""),
array("arnold schwarzenegger","2","","",""),
array("amy winehouse","2","","",""),
array("ashley olsen","3","","",""),
array("adrianne curry","3","","",""),
array("ashley hebert","3","","",""),
array("apartments for rent","3","","",""),
array("answers.com","3","","",""),
array("airline tickets","3","","",""),
array("are vampires real","3","","",""),
array("apple store","3","","",""),
array("am i pregnant quiz","3","","",""),
array("amazon.com","3","","",""),
array("adele someone like you","4","","",""),
array("adele rolling in the deep","4","","",""),
array("akon","4","","",""),
array("all of the lights kanye west","4","","",""),
array("alienware aurora desktop","4","","",""),
array("annoying orange","4","","",""),
array("avril lavigne what the hell","4","","",""),
array("avril lavigne","4","","",""),
array("american idol 2011","4","","","")),
"b" => array(
array("bank of america","0","2","3",""),
array("best buy","0","2","3",""),
array("bed bath and beyond","0","2","3",""),
array("bing","0","2","3",""),
array("barnes and noble","0","2","",""),
array("babies r us","0","2","",""),
array("britney spears","2","4","",""),
array("bellagio","0","","",""),
array("big 5","0","","",""),
array("blockbuster","0","","",""),
array("borders","0","","",""),
array("blackberry","1","","",""),
array("born this way","1","","",""),
array("blackberry torch","1","","",""),
array("beats by dre","1","","",""),
array("backpack","1","","",""),
array("brink","1","","",""),
array("bose","1","","",""),
array("bluetooth headset","1","","",""),
array("blackberry playbook","1","","",""),
array("black ops","1","","",""),
array("blank","2","","",""),
array("brad pitt","2","","",""),
array("bristol palin","2","","",""),
array("bad teacher","3","","",""),
array("bbb","3","","",""),
array("boston globe","3","","",""),
array("baby names","3","","",""),
array("bmi calculator","3","","",""),
array("baby names and meanings","3","","",""),
array("black and yellow wiz khalifa","4","","",""),
array("bluetooth mobile phone spy","4","","",""),
array("bruno mars","4","","",""),
array("black eyed peas","4","","",""),
array("black eyed peas just can't get enough","4","","",""),
array("born this way lady gaga","4","","",""),
array("beyonce","4","","",""),
array("bruno mars lazy song","4","","",""),
array("bruno mars grenade","4","","","")),
"c" => array(
array("craigslist","0","2","3",""),
array("cnn","0","2","",""),
array("chase","0","2","",""),
array("costco","0","2","",""),
array("capital one","2","3","",""),
array("craigslist las vegas","0","","",""),
array("csn","0","","",""),
array("ccsd","0","","",""),
array("carmax","0","","",""),
array("clark county assessor","0","","",""),
array("cox","0","","",""),
array("camera","1","","",""),
array("crocs","1","","",""),
array("canon 7d","1","","",""),
array("canon","1","","",""),
array("coffee maker","1","","",""),
array("canon 60d","1","","",""),
array("cell phone","1","","",""),
array("call of duty black ops","1","","",""),
array("crysis 2","1","","",""),
array("converse","1","","",""),
array("christina ricci dress","2","","",""),
array("cartoon network","2","","",""),
array("comcast","2","","",""),
array("club penguin","2","","",""),
array("continental airlines","2","","",""),
array("conan the barbarian","3","","",""),
array("craiglist","3","","",""),
array("cake boss","3","","",""),
array("cheap airline tickets","3","","",""),
array("calculator","3","","",""),
array("cheap flights","3","","",""),
array("calorie counter","3","","",""),
array("currency converter","3","","",""),
array("chris brown","4","","",""),
array("chris brown look at me now","4","","",""),
array("cat daddy","4","","",""),
array("chris brown beautiful people","4","","",""),
array("chris brown yeah 3x","4","","",""),
array("christina aguilera","4","","",""),
array("charlie bit my finger","4","","",""),
array("coming home","4","","",""),
array("california gurls katy perry","4","","",""),
array("carrie underwood","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("dancing with the stars","0","2","",""),
array("danica patrick","2","3","",""),
array("delta airlines","2","3","",""),
array("driving directions","2","3","",""),
array("dmv nevada","0","","",""),
array("delta","0","","",""),
array("dillards","0","","",""),
array("dominos","0","","",""),
array("dmv","0","","",""),
array("disneyland","0","","",""),
array("direct tv","0","","",""),
array("disney","0","","",""),
array("digital camera","1","","",""),
array("diapers","1","","",""),
array("dehumidifier","1","","",""),
array("dvd player","1","","",""),
array("dexter","1","","",""),
array("doctor who","1","","",""),
array("dirt 3","1","","",""),
array("dyson","1","","",""),
array("dsi","1","","",""),
array("d7000","1","","",""),
array("disney channel","2","","",""),
array("debbie harry","2","","",""),
array("dell","2","","",""),
array("dead wrestlers","2","","",""),
array("david schwimmer","2","","",""),
array("diabetes treatments","3","","",""),
array("daniel ellsberg","3","","",""),
array("does justin bieber have a girlfriend","3","","",""),
array("definitions.com","3","","",""),
array("dictionary online","3","","",""),
array("disneychannel.com","3","","",""),
array("drake","4","","",""),
array("dubstep","4","","",""),
array("down on me","4","","",""),
array("dynamite taio cruz","4","","",""),
array("david guetta","4","","",""),
array("deadmau5","4","","",""),
array("down on me jeremiah ft 50 cent","4","","",""),
array("dynamite","4","","",""),
array("don omar","4","","",""),
array("dr dre i need a doctor","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("espn","0","1","2",""),
array("expedia","0","2","3",""),
array("enterprise car rental","2","3","",""),
array("easter 2011","0","","",""),
array("extreme thing 2011","0","","",""),
array("edible arrangements","0","","",""),
array("edc","0","","",""),
array("etsy","0","","",""),
array("eppicard","0","","",""),
array("enterprise","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("eddie vedder","1","","",""),
array("eee pad transformer","1","","",""),
array("electronic cigarette","1","","",""),
array("espresso machine","1","","",""),
array("ebooks","1","","",""),
array("external hard drive 1tb","1","","",""),
array("elin nordegren","2","","",""),
array("evangeline lilly","2","","",""),
array("eva longoria","2","","",""),
array("emma watson","2","","",""),
array("elizabeth smart","2","","",""),
array("ebay motors","2","","",""),
array("evelyn lozada","3","","",""),
array("expedia.com","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("extreme couponing","3","","",""),
array("engagement rings","3","","",""),
array("early signs of pregnancy","3","","",""),
array("eminem","4","","",""),
array("et katty perry","4","","",""),
array("et","4","","",""),
array("eminem not afraid","4","","",""),
array("enrique iglesias tonight","4","","",""),
array("eminem i need a doctor","4","","",""),
array("enrique iglesias","4","","",""),
array("epic mealtime","4","","",""),
array("epic rap battles of history","4","","",""),
array("et katty perry lyrics","4","","","")),
"f" => array(
array("facebook","0","2","3",""),
array("fandango","0","2","",""),
array("food network","0","2","",""),
array("fox news","0","2","",""),
array("fedex","0","2","",""),
array("free online games","2","3","",""),
array("free music downloads","2","3","",""),
array("facebook login","0","","",""),
array("frys","0","","",""),
array("firefox","0","","",""),
array("forever 21","0","","",""),
array("fafsa","0","","",""),
array("fan","1","","",""),
array("flash drive","1","","",""),
array("free kindle books","1","","",""),
array("food processor","1","","",""),
array("futon","1","","",""),
array("flashlight","1","","",""),
array("feather hair extension","1","","",""),
array("fathers day gifts","1","","",""),
array("flowers","1","","",""),
array("frontline plus for dogs","1","","",""),
array("fac","2","","",""),
array("fantasy football","2","","",""),
array("ford","2","","",""),
array("face transplant","3","","",""),
array("florida","3","","",""),
array("free ringtones","3","","",""),
array("free games","3","","",""),
array("free credit report","3","","",""),
array("find a person","3","","",""),
array("first name meanings","3","","",""),
array("friday","4","","",""),
array("friday rebecca black","4","","",""),
array("funny video","4","","",""),
array("firework katy perry","4","","",""),
array("funny","4","","",""),
array("funny pranks","4","","",""),
array("fast and furious 5","4","","",""),
array("fred","4","","",""),
array("female hair transplant","4","","",""),
array("funny cats","4","","","")),
"g" => array(
array("google","0","2","3","4"),
array("google maps","0","2","3",""),
array("games","0","2","3",""),
array("glee","0","1","4",""),
array("gmail","0","2","",""),
array("google search","2","3","",""),
array("google translate","0","","",""),
array("gamestop","0","","",""),
array("google earth","0","","",""),
array("green valley ranch","0","","",""),
array("geico","0","","",""),
array("gps","1","","",""),
array("game of thrones","1","","",""),
array("gift card","1","","",""),
array("galaxy tab","1","","",""),
array("garmin","1","","",""),
array("gaga","1","","",""),
array("gears of war 3","1","","",""),
array("grill","1","","",""),
array("garmin gps","1","","",""),
array("goo","2","","",""),
array("gwyneth paltrow","2","","",""),
array("gas prices","2","","",""),
array("gigi goyette","2","","",""),
array("glenn beck","2","","",""),
array("ghost hunters","3","","",""),
array("great pyramid markings","3","","",""),
array("germany","3","","",""),
array("google.com","3","","",""),
array("google search engine","3","","",""),
array("gnc","3","","",""),
array("grenade bruno mars","4","","",""),
array("give me everything pitbull","4","","",""),
array("grenade","4","","",""),
array("gummy bear song","4","","",""),
array("give me everything","4","","",""),
array("grenade bruno mars lyrics","4","","",""),
array("gucci mane","4","","",""),
array("green day","4","","","")),
"h" => array(
array("home depot","0","2","3",""),
array("hotmail","0","2","",""),
array("hulu","0","2","",""),
array("honda","0","2","",""),
array("how to kiss","3","4","",""),
array("h&m","0","","",""),
array("house of blues las vegas","0","","",""),
array("hp","0","","",""),
array("hoover dam","0","","",""),
array("horoscope","0","","",""),
array("hollister","0","","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("harry potter","1","","",""),
array("hunger games","1","","",""),
array("hello kitty","1","","",""),
array("htc","1","","",""),
array("hammock","1","","",""),
array("hard drive","1","","",""),
array("halo reach","1","","",""),
array("htc thunderbolt","1","","",""),
array("horoscopes","2","","",""),
array("hi5","2","","",""),
array("halle berry","2","","",""),
array("heidi montag","2","","",""),
array("harian metro","2","","",""),
array("hsn","2","","",""),
array("hidden","3","","",""),
array("haleh sahabi","3","","",""),
array("hiv infections","3","","",""),
array("how much should i weigh","3","","",""),
array("how to get pregnant","3","","",""),
array("how many calories should i eat a day","3","","",""),
array("how do you spell a word","3","","",""),
array("home depot.com","3","","",""),
array("harry potter and the deathly hallows part 2 trailer","4","","",""),
array("happy tree friends","4","","",""),
array("hey soul sister","4","","",""),
array("hold it against me","4","","",""),
array("hangover 2 trailer","4","","",""),
array("hello","4","","",""),
array("hollywood undead","4","","",""),
array("higher taio cruz","4","","",""),
array("hannah montana","4","","","")),
"i" => array(
array("irs","0","2","3",""),
array("ipad","0","1","3",""),
array("itunes","0","2","",""),
array("imdb","0","2","",""),
array("ipad 2","0","1","",""),
array("ikea","0","2","",""),
array("indeed","0","2","",""),
array("ipod","1","2","",""),
array("iphone","1","2","",""),
array("iphone 5","0","","",""),
array("ihop","0","","",""),
array("ign","0","","",""),
array("iphone 4","1","","",""),
array("ipod touch","1","","",""),
array("iphone 4 case","1","","",""),
array("ipod touch 4th generation","1","","",""),
array("ipad 2 case","1","","",""),
array("ipod nano","1","","",""),
array("indy 500 2011","2","","",""),
array("internet explorer","2","","",""),
array("illinois lottery","2","","",""),
array("illinois","3","","",""),
array("is the world going to end in 2012","3","","",""),
array("instant math answers free","3","","",""),
array("inspirational quotes","3","","",""),
array("is pneumonia contagious","3","","",""),
array("images","3","","",""),
array("is bronchitis contagious","3","","",""),
array("information on sponges","3","","",""),
array("i need a doctor","4","","",""),
array("i need a doctor eminem","4","","",""),
array("i just had sex-akon","4","","",""),
array("im coming home","4","","",""),
array("insidious trailer","4","","",""),
array("indian songs","4","","",""),
array("i love you","4","","",""),
array("its friday","4","","",""),
array("i just had sex- lonely island","4","","",""),
array("inna","4","","","")),
"j" => array(
array("justin bieber","0","1","2","3"),
array("jcpenney","0","2","",""),
array("jennifer lopez","2","4","",""),
array("jet blue","0","","",""),
array("java","0","","",""),
array("jack in the box","0","","",""),
array("jobs in las vegas","0","","",""),
array("justin tv","0","","",""),
array("jersey shore","0","","",""),
array("joanns","0","","",""),
array("japan","0","","",""),
array("juicer","1","","",""),
array("jillian michaels","1","","",""),
array("jack3d","1","","",""),
array("juicy couture","1","","",""),
array("jewelry box","1","","",""),
array("james patterson","1","","",""),
array("jordan shoes","1","","",""),
array("jawbone","1","","",""),
array("jansport backpack","1","","",""),
array("jeff conaway","2","","",""),
array("jodie foster","2","","",""),
array("jane seymour","2","","",""),
array("jennifer aniston","2","","",""),
array("jessica simpson","2","","",""),
array("justin timberlake","2","","",""),
array("jennifer love hewitt","2","","",""),
array("ja rule","3","","",""),
array("jamie howell","3","","",""),
array("jean-bertrand aristide","3","","",""),
array("justin bieber cell number","3","","",""),
array("justin bieber phone number for real","3","","",""),
array("jcpenney.com","3","","",""),
array("jobs in my area","3","","",""),
array("justin bieber quiz","3","","",""),
array("jobs","3","","",""),
array("justin bieber baby","4","","",""),
array("jennifer lopez on the floor","4","","",""),
array("justin bieber never say never","4","","",""),
array("judas lady gaga","4","","",""),
array("just can't get enough black eyed peas","4","","",""),
array("judas","4","","",""),
array("just the way you are","4","","",""),
array("just cant get enough","4","","","")),
"k" => array(
array("kmart","0","2","3",""),
array("kohls","0","3","",""),
array("kayak","0","1","",""),
array("kelly blue book","0","3","",""),
array("kindle","1","3","",""),
array("kelley blue book","2","3","",""),
array("katy perry","2","4","",""),
array("knotts berry farm","0","","",""),
array("ktnv","0","","",""),
array("kfc","0","","",""),
array("kinkos","0","","",""),
array("klas tv","0","","",""),
array("knpr","0","","",""),
array("kindle cover","1","","",""),
array("kinect","1","","",""),
array("keurig","1","","",""),
array("k cups","1","","",""),
array("kindle case","1","","",""),
array("knife","1","","",""),
array("keyboard","1","","",""),
array("kitchenaid mixer","1","","",""),
array("kim kardashian","2","","",""),
array("kirstie alley","2","","",""),
array("kim clijsters","2","","",""),
array("kate gosselin","2","","",""),
array("kohl's","2","","",""),
array("kristen stewart","2","","",""),
array("katie holmes","2","","",""),
array("king abdullah","3","","",""),
array("kids games","3","","",""),
array("kellybluebook.com","3","","",""),
array("kia","3","","",""),
array("kohls coupons","3","","",""),
array("katy perry et","4","","",""),
array("katy perry firework","4","","",""),
array("kanye west","4","","",""),
array("kesha we r who we r","4","","",""),
array("kid cudi","4","","",""),
array("kelly rowland motivation","4","","",""),
array("kanye west all of the lights","4","","",""),
array("katy perry teenage dream","4","","",""),
array("kesha blown","4","","","")),
"l" => array(
array("lady gaga","1","2","4",""),
array("lowes","0","3","",""),
array("lady gaga born this way","1","4","",""),
array("lyrics","2","3","",""),
array("love quotes","2","3","",""),
array("lil wayne","2","4","",""),
array("las vegas review journal","0","","",""),
array("las vegas sun","0","","",""),
array("las vegas weather","0","","",""),
array("las vegas news","0","","",""),
array("lvac","0","","",""),
array("las vegas craigslist","0","","",""),
array("las vegas dmv","0","","",""),
array("louis vuitton","0","","",""),
array("las vegas library","0","","",""),
array("la noire","1","","",""),
array("laptop computer","1","","",""),
array("luggage","1","","",""),
array("lego","1","","",""),
array("lady gaga born this way album","1","","",""),
array("laptop","1","","",""),
array("lego star wars","1","","",""),
array("lego pirates of the caribbean","1","","",""),
array("lindsay lohan","2","","",""),
array("lisa kudrow","2","","",""),
array("lowe's home improvement","2","","",""),
array("limewire","2","","",""),
array("lee dewyze","2","","",""),
array("lebron james","2","","",""),
array("lizzy caplan","3","","",""),
array("libya","3","","",""),
array("louise o'brien","3","","",""),
array("lowes.com","3","","",""),
array("lyrics to songs","3","","",""),
array("love poems","3","","",""),
array("lingerie","3","","",""),
array("look at me now chris brown","4","","",""),
array("lazy song bruno mars","4","","",""),
array("look at me now","4","","",""),
array("lady gaga judas","4","","",""),
array("lmfao party rock anthem","4","","",""),
array("lazy song","4","","",""),
array("lil wayne 6 foot 7 foot","4","","","")),
"m" => array(
array("mapquest","0","2","3",""),
array("msn","0","2","",""),
array("maps","0","3","",""),
array("myspace","0","2","",""),
array("minecraft","0","4","",""),
array("michaels","0","3","",""),
array("music","2","3","",""),
array("miley cyrus","2","4","",""),
array("mandalay bay","0","","",""),
array("macys","0","","",""),
array("msnbc","0","","",""),
array("mgm grand","0","","",""),
array("macbook pro","1","","",""),
array("mortal kombat","1","","",""),
array("mp3 player","1","","",""),
array("macbook","1","","",""),
array("modern warfare 3","1","","",""),
array("motorola xoom","1","","",""),
array("micro sd","1","","",""),
array("mouse","1","","",""),
array("macbook air","1","","",""),
array("mac","1","","",""),
array("mail","2","","",""),
array("maria sharapova","2","","",""),
array("macy's","2","","",""),
array("megan fox","2","","",""),
array("movies","2","","",""),
array("maria shriver","3","","",""),
array("mahmoud abdel salam omar","3","","",""),
array("mapquest driving directions","3","","",""),
array("math answers","3","","",""),
array("macys.com","3","","",""),
array("medical dictionary","3","","",""),
array("michael jackson","4","","",""),
array("mariah carey","4","","",""),
array("mac miller","4","","",""),
array("maharaja lawak","4","","",""),
array("metallica","4","","",""),
array("motivation kelly rowland","4","","",""),
array("moment 4 life","4","","",""),
array("marry you bruno mars","4","","","")),
"n" => array(
array("netflix","0","2","3",""),
array("nba","0","2","",""),
array("news","0","2","",""),
array("nordstrom","0","2","",""),
array("nevada dmv","0","","",""),
array("nv energy","0","","",""),
array("nevada unemployment","0","","",""),
array("nevada state bank","0","","",""),
array("nevada federal credit union","0","","",""),
array("nick","0","","",""),
array("nook","1","","",""),
array("nokia n8","1","","",""),
array("nikon d7000","1","","",""),
array("nintendo ds","1","","",""),
array("nikon d3100","1","","",""),
array("nintendo 3ds","1","","",""),
array("nook color","1","","",""),
array("nike","1","","",""),
array("nikon","1","","",""),
array("nikon d5100","1","","",""),
array("nick jr","2","","",""),
array("noodling","2","","",""),
array("nfl","2","","",""),
array("nascar","2","","",""),
array("nickelodeon","2","","",""),
array("nbc","2","","",""),
array("niecy nash","3","","",""),
array("nuclear shutdown","3","","",""),
array("nadya suleman","3","","",""),
array("name meanings","3","","",""),
array("names and meaning","3","","",""),
array("nissan","3","","",""),
array("nickelodeon games","3","","",""),
array("naked","3","","",""),
array("nissan cars","3","","",""),
array("nicki minaj","4","","",""),
array("nigahiga","4","","",""),
array("nicki minaj super bass","4","","",""),
array("never say never","4","","",""),
array("new songs 2011","4","","",""),
array("never say never justin bieber","4","","",""),
array("nicki minaj moment 4 life","4","","",""),
array("nyan cat","4","","",""),
array("nickelback","4","","",""),
array("no hands","4","","","")),
"o" => array(
array("office depot","0","2","3",""),
array("old navy","0","2","3",""),
array("orbitz","0","2","",""),
array("overstock","0","2","",""),
array("online dictionary","2","3","",""),
array("olive garden","0","","",""),
array("office max","0","","",""),
array("orleans","0","","",""),
array("orchard bank","0","","",""),
array("omegle","0","","",""),
array("open office","0","","",""),
array("oakley","1","","",""),
array("otterbox","1","","",""),
array("oakley sunglasses","1","","",""),
array("otterbox iphone 4","1","","",""),
array("opi","1","","",""),
array("opi nail polish","1","","",""),
array("office chair","1","","",""),
array("oakley sunglasses for men","1","","",""),
array("outdoor speakers","1","","",""),
array("outdoor furniture","1","","",""),
array("olivia wilde","2","","",""),
array("owen wilson","2","","",""),
array("oprah winfrey","2","","",""),
array("omg","2","","",""),
array("orkut","2","","",""),
array("octomom","3","","",""),
array("online pregnancy test","3","","",""),
array("ovulation calculator","3","","",""),
array("ovulation calendar","3","","",""),
array("online games","3","","",""),
array("online calculator","3","","",""),
array("obituary searches","3","","",""),
array("on the floor jennifer lopez","4","","",""),
array("on the floor","4","","",""),
array("osama bin laden","4","","",""),
array("osama bin laden dead","4","","",""),
array("osama bin laden video","4","","",""),
array("on the floor jennifer lopez ft pitbull","4","","",""),
array("on my level wiz khalifa","4","","",""),
array("one time justin bieber","4","","",""),
array("omg usher","4","","",""),
array("on the floor lyrics","4","","","")),
"p" => array(
array("pandora","0","2","",""),
array("pizza hut","0","2","",""),
array("paypal","0","2","",""),
array("photobucket","0","2","",""),
array("priceline","0","2","",""),
array("portal 2","1","4","",""),
array("people search","2","3","",""),
array("parentlink","0","","",""),
array("papa johns","0","","",""),
array("pirate bay","0","","",""),
array("petco","0","","",""),
array("petsmart","0","","",""),
array("ps3","1","","",""),
array("playstation 3","1","","",""),
array("psp","1","","",""),
array("p90x","1","","",""),
array("portable air conditioner","1","","",""),
array("plants vs zombies","1","","",""),
array("portable dvd player","1","","",""),
array("pokemon","1","","",""),
array("ps3 controller","1","","",""),
array("patricia heaton","2","","",""),
array("pogo","2","","",""),
array("powerball","2","","",""),
array("poptropica","2","","",""),
array("phil ivey","3","","",""),
array("pbs","3","","",""),
array("p chidambaram","3","","",""),
array("pregnancy week by week","3","","",""),
array("phone number lookup","3","","",""),
array("prom dresses","3","","",""),
array("people search for free","3","","",""),
array("people finder","3","","",""),
array("put my word in a sentence","3","","",""),
array("price tag","4","","",""),
array("party rock anthem","4","","",""),
array("pitbull","4","","",""),
array("pink","4","","",""),
array("price tag jesse j","4","","",""),
array("party rock anthem lmfao","4","","",""),
array("paramore","4","","",""),
array("pacquiao vs mosley","4","","",""),
array("put it down on me","4","","","")),
"q" => array(
array("qvc","0","2","3",""),
array("quotes","0","2","3",""),
array("quickbooks","1","2","3",""),
array("qwop","0","4","",""),
array("quest diagnostics","0","2","",""),
array("quiznos","0","2","",""),
array("quicktime","0","2","",""),
array("quotes about life","0","3","",""),
array("queen","1","4","",""),
array("quest diagnostics las vegas","0","","",""),
array("quibids","0","","",""),
array("queen elizabeth","0","","",""),
array("quickbooks pro 2011","1","","",""),
array("quicken","1","","",""),
array("quiksilver","1","","",""),
array("queen mattress","1","","",""),
array("quilt","1","","",""),
array("quinoa","1","","",""),
array("queen bed frame","1","","",""),
array("queen sheet set","1","","",""),
array("qwest","2","","",""),
array("query string","2","","",""),
array("qatar airways","2","","",""),
array("quentin tarantino","2","","",""),
array("quotes of the day","3","","",""),
array("quizzes","3","","",""),
array("quotes and sayings","3","","",""),
array("quick mileage city to city","3","","",""),
array("questions and answers","3","","",""),
array("qvc home shopping","3","","",""),
array("queen bohemian rhapsody","4","","",""),
array("quest crew","4","","",""),
array("qgjumbdaqiw","4","","",""),
array("qzu9orzlkb8","4","","",""),
array("queen we will rock you","4","","",""),
array("queens of the stone age","4","","",""),
array("qro4yzeyl0i","4","","",""),
array("queen don't stop me now","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("espn","0","1","2",""),
array("expedia","0","2","3",""),
array("ebay motors","0","2","",""),
array("enterprise car rental","2","3","",""),
array("edc","0","","",""),
array("easter 2011","0","","",""),
array("etsy","0","","",""),
array("edible arrangements","0","","",""),
array("eppicard","0","","",""),
array("enterprise","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("eddie vedder","1","","",""),
array("eee pad transformer","1","","",""),
array("electronic cigarette","1","","",""),
array("espresso machine","1","","",""),
array("ebooks","1","","",""),
array("external hard drive 1tb","1","","",""),
array("elin nordegren","2","","",""),
array("evangeline lilly","2","","",""),
array("eva longoria","2","","",""),
array("emma watson","2","","",""),
array("elizabeth smart","2","","",""),
array("evelyn lozada","3","","",""),
array("expedia.com","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("extreme couponing","3","","",""),
array("engagement rings","3","","",""),
array("early signs of pregnancy","3","","",""),
array("eminem","4","","",""),
array("et katty perry","4","","",""),
array("et","4","","",""),
array("eminem not afraid","4","","",""),
array("enrique iglesias tonight","4","","",""),
array("eminem i need a doctor","4","","",""),
array("enrique iglesias","4","","",""),
array("epic mealtime","4","","",""),
array("epic rap battles of history","4","","",""),
array("et katty perry lyrics","4","","","")),
"s" => array(
array("southwest airlines","0","2","3",""),
array("sears","0","2","3",""),
array("skype","0","2","",""),
array("sprint","0","2","",""),
array("southwest gas","0","","",""),
array("smiths","0","","",""),
array("sams club","0","","",""),
array("spirit airlines","0","","",""),
array("station casinos","0","","",""),
array("speed test","0","","",""),
array("sunglasses","1","","",""),
array("search amazon.com","1","","",""),
array("samsung galaxy tab","1","","",""),
array("samsung galaxy s2","1","","",""),
array("star wars","1","","",""),
array("sd card","1","","",""),
array("skullcandy headphones","1","","",""),
array("speakers","1","","",""),
array("starcraft 2","1","","",""),
array("samsung galaxy","1","","",""),
array("sandra bullock","2","","",""),
array("social security","2","","",""),
array("sarah mclachlan","2","","",""),
array("search","2","","",""),
array("staples","2","","",""),
array("sara rue","2","","",""),
array("seattle mariners","3","","",""),
array("silk road","3","","",""),
array("so you think you can dance","3","","",""),
array("scary maze game","3","","",""),
array("sears.com","3","","",""),
array("spanish dictionary","3","","",""),
array("sexy","3","","",""),
array("song lyrics","3","","",""),
array("shakira","4","","",""),
array("selena gomez","4","","",""),
array("super bass nicki minaj","4","","",""),
array("selena gomez who says","4","","",""),
array("super bass","4","","",""),
array("smosh","4","","",""),
array("soulja boy","4","","",""),
array("skrillex","4","","",""),
array("snoop dogg","4","","",""),
array("stereo love","4","","","")),
"t" => array(
array("twitter","0","2","3",""),
array("travelocity","0","2","3",""),
array("target","0","2","",""),
array("translator","0","3","",""),
array("ticketmaster","0","2","",""),
array("tmz","0","2","",""),
array("taylor swift","2","4","",""),
array("thesaurus","0","","",""),
array("tmobile","0","","",""),
array("turbo tax","0","","",""),
array("tumblr","0","","",""),
array("true blood season 3","1","","",""),
array("tablet","1","","",""),
array("true blood","1","","",""),
array("tent","1","","",""),
array("tangled","1","","",""),
array("the help","1","","",""),
array("true grit","1","","",""),
array("toms","1","","",""),
array("the hunger games","1","","",""),
array("trampoline","1","","",""),
array("tiger woods","2","","",""),
array("toys r us","2","","",""),
array("tagged","2","","",""),
array("t-mobile","2","","",""),
array("tom vilsack","3","","",""),
array("translate english to spanish","3","","",""),
array("tattoo designs","3","","",""),
array("translate spanish to english","3","","",""),
array("travelocity.com","3","","",""),
array("teen pregnancy signs","3","","",""),
array("tattoos","3","","",""),
array("the lazy song bruno mars","4","","",""),
array("teach me how to dougie","4","","",""),
array("the lazy song","4","","",""),
array("till the world ends britney spears","4","","",""),
array("the show goes on lupe fiasco","4","","",""),
array("tom and jerry","4","","",""),
array("transformers 3 official trailer","4","","",""),
array("trey songz","4","","",""),
array("thor","4","","","")),
"u" => array(
array("united airlines","0","2","3",""),
array("us airways","0","2","3",""),
array("usps","0","2","",""),
array("ups","0","2","",""),
array("us bank","0","2","",""),
array("usaa","0","2","",""),
array("ups tracking","0","3","",""),
array("ufc","0","4","",""),
array("used cars","2","3","",""),
array("unlv","0","","",""),
array("utube","0","","",""),
array("unlocked cell phones","1","","",""),
array("usb flash drive","1","","",""),
array("umbrella","1","","",""),
array("under armour","1","","",""),
array("usb hub","1","","",""),
array("unbroken","1","","",""),
array("ukulele","1","","",""),
array("uncharted 2","1","","",""),
array("usb","1","","",""),
array("uncharted","1","","",""),
array("ufc 130 live stream","2","","",""),
array("univision","2","","",""),
array("uma thurman","2","","",""),
array("used cars for sale in my area","3","","",""),
array("used cars for sale","3","","",""),
array("unique baby names","3","","",""),
array("unclaimed money","3","","",""),
array("unemployment benefits","3","","",""),
array("usairways.com","3","","",""),
array("usher","4","","",""),
array("usher more","4","","",""),
array("usher dj got us falling in love","4","","",""),
array("ufo","4","","",""),
array("u2","4","","",""),
array("usher omg","4","","",""),
array("unorthodox wretch 32","4","","",""),
array("usher yeah","4","","",""),
array("udin sedunia","4","","","")),
"v" => array(
array("verizon","0","2","3",""),
array("victoria secret","0","3","",""),
array("vans","0","1","",""),
array("victoria's secret","1","2","",""),
array("verizon wireless","2","3","",""),
array("vanessa hudgens","2","4","",""),
array("venetian","0","","",""),
array("vons","0","","",""),
array("virgin america","0","","",""),
array("valley of fire","0","","",""),
array("vlc","0","","",""),
array("volaris","0","","",""),
array("vdara","0","","",""),
array("vacuum cleaner","1","","",""),
array("verizon cell phones","1","","",""),
array("video camera","1","","",""),
array("vera bradley","1","","",""),
array("vacuum","1","","",""),
array("vampire diaries","1","","",""),
array("vitamix","1","","",""),
array("vibram five fingers","1","","",""),
array("vicki gunvalson","2","","",""),
array("victoria beckham","2","","",""),
array("vh1","2","","",""),
array("virgin mobile","2","","",""),
array("valerie bertinelli","2","","",""),
array("video","2","","",""),
array("vanessa minnillo","3","","",""),
array("vivica fox","3","","",""),
array("virginia","3","","",""),
array("verizon.com","3","","",""),
array("very early symptoms of pregnancy","3","","",""),
array("verizonwireless.com","3","","",""),
array("videos","3","","",""),
array("victorious","4","","",""),
array("vevo","4","","",""),
array("vybz kartel","4","","",""),
array("victoria justice","4","","",""),
array("video lucu","4","","",""),
array("vybz kartel 2011","4","","",""),
array("van halen","4","","",""),
array("vi sao","4","","",""),
array("vicente fernandez","4","","","")),
"w" => array(
array("white pages","0","2","3",""),
array("walmart","0","2","",""),
array("weather","0","2","",""),
array("wells fargo","0","2","",""),
array("wikipedia","0","2","",""),
array("walgreens","0","2","",""),
array("webmd","0","2","",""),
array("www.facebook.com","0","","",""),
array("weather las vegas","0","","",""),
array("whole foods","0","","",""),
array("wii","1","","",""),
array("wii games","1","","",""),
array("watch","1","","",""),
array("wireless router","1","","",""),
array("windows 7","1","","",""),
array("webcam","1","","",""),
array("wii console","1","","",""),
array("wallet","1","","",""),
array("wireless mouse","1","","",""),
array("watches for men","1","","",""),
array("webkinz","2","","",""),
array("wwe","2","","",""),
array("wachovia","2","","",""),
array("weather boston","3","","",""),
array("weather nyc","3","","",""),
array("wsop","3","","",""),
array("what is justin biebers phone number","3","","",""),
array("what does my last name mean","3","","",""),
array("what is the meaning of my name","3","","",""),
array("what is love","3","","",""),
array("what does my dream mean","3","","",""),
array("where can i watch free movies online","3","","",""),
array("wiz khalifa","4","","",""),
array("written in the stars","4","","",""),
array("who says selena gomez","4","","",""),
array("wiz khalifa roll up","4","","",""),
array("waka waka shakira","4","","",""),
array("website traffic generation","4","","",""),
array("what the hell avril lavigne","4","","",""),
array("who says","4","","",""),
array("written in the stars tinie tempah","4","","",""),
array("wiz khalifa on my level","4","","","")),
"x" => array(
array("xbox 360","1","2","3","4"),
array("xbox","0","1","3",""),
array("xm radio","0","2","3",""),
array("xbox live","0","1","2",""),
array("xoom","0","1","",""),
array("xbox 360 console","1","3","",""),
array("xbox 360 games","1","3","",""),
array("x factor","2","4","",""),
array("x107.5","0","","",""),
array("xs las vegas","0","","",""),
array("xda","0","","",""),
array("xkcd","0","","",""),
array("xtranormal","0","","",""),
array("xbmc","0","","",""),
array("xbox 360 controller","1","","",""),
array("xbox 360 kinect","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("xperia play","1","","",""),
array("xanax","2","","",""),
array("x17","2","","",""),
array("xem phim","2","","",""),
array("xvid","2","","",""),
array("x games","2","","",""),
array("xbox cheats","2","","",""),
array("xxl movie","3","","",""),
array("xbox 360 cheats","3","","",""),
array("xxl tv live","3","","",""),
array("xm satellite radio","3","","",""),
array("xbox live 2 month free trial","3","","",""),
array("xjawz","4","","",""),
array("x men first class trailer","4","","",""),
array("x factor 2011","4","","",""),
array("xxl movie six","4","","",""),
array("xzibit","4","","",""),
array("x men first class","4","","",""),
array("xftfxcyqtdk","4","","",""),
array("x","4","","","")),
"y" => array(
array("youtube","0","2","3","4"),
array("yahoo","0","2","3",""),
array("yahoo mail","0","2","3",""),
array("yellow pages","0","2","3",""),
array("yahoo maps","0","2","",""),
array("y8","0","2","",""),
array("yelp","0","","",""),
array("youtube to mp3","0","","",""),
array("yahoo answers","0","","",""),
array("yahoo finance","0","","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yugioh cards","1","","",""),
array("yoga dvd","1","","",""),
array("yugioh","1","","",""),
array("yo gabba gabba","1","","",""),
array("yogurt maker","1","","",""),
array("yarn","1","","",""),
array("yoga pants","1","","",""),
array("yoyo","1","","",""),
array("youtube video","2","","",""),
array("youtube broadcast yourself","2","","",""),
array("yahoo messenger","2","","",""),
array("yahoo music","2","","",""),
array("yashpal malik","3","","",""),
array("yemen","3","","",""),
array("youtube videos","3","","",""),
array("yahoo mail login","3","","",""),
array("yellowpages.com","3","","",""),
array("youtube music","3","","",""),
array("yeah 3x","4","","",""),
array("yeah 3x chris brown","4","","",""),
array("young jeezy","4","","",""),
array("your favorite martian","4","","",""),
array("you belong with me","4","","",""),
array("you belong with me taylor swift","4","","",""),
array("young money","4","","",""),
array("yogscast","4","","",""),
array("yelawolf","4","","","")),
"z" => array(
array("zumba","0","1","3","4"),
array("zappos","0","2","3",""),
array("zip codes","0","2","3",""),
array("zillow","0","2","",""),
array("zune","0","1","",""),
array("zales","0","2","",""),
array("zombie","1","4","",""),
array("zodiac signs","2","3","",""),
array("zion national park","0","","",""),
array("zumiez","0","","",""),
array("zillow las vegas","0","","",""),
array("zappos jobs","0","","",""),
array("zumba fitness dvd","1","","",""),
array("zippo","1","","",""),
array("zune hd","1","","",""),
array("zelda","1","","",""),
array("zumba dvd","1","","",""),
array("zumba wii","1","","",""),
array("zippo lighter","1","","",""),
array("zsa zsa gabor","2","","",""),
array("zach galifianakis","2","","",""),
array("zach braff","2","","",""),
array("zooey deschanel","2","","",""),
array("zuma","2","","",""),
array("zip code finder","3","","",""),
array("zappos.com","3","","",""),
array("zip code lookup","3","","",""),
array("zip code list","3","","",""),
array("zip code maps free","3","","",""),
array("zodiac compatibility","3","","",""),
array("zac brown band","4","","",""),
array("zaz je veux","4","","",""),
array("zac brown band colder weather","4","","",""),
array("zombie cranberries","4","","",""),
array("zaz","4","","",""),
array("zeitgeist","4","","",""),
array("zz top","4","","",""),
array("zeldaxlove64","4","","","")));
?>