<?php $topResults = array(
"a" => array(
array("amazon","0","2","",""),
array("aol","0","2","",""),
array("american idol","0","2","",""),
array("american airlines","0","2","",""),
array("apple","0","1","",""),
array("adele","1","4","",""),
array("allegiant air","0","","",""),
array("att","0","","",""),
array("auto trader","0","","",""),
array("aol mail","0","","",""),
array("addicting games","0","","",""),
array("air conditioner","1","","",""),
array("asus transformer","1","","",""),
array("airsoft guns","1","","",""),
array("apple tv","1","","",""),
array("adidas","1","","",""),
array("airsoft","1","","",""),
array("android","1","","",""),
array("angry birds","1","","",""),
array("abe vigoda","2","","",""),
array("anne hathaway","2","","",""),
array("at&t","2","","",""),
array("anna kournikova","2","","",""),
array("autotrader","2","","",""),
array("ann coulter","2","","",""),
array("anarchy","3","","",""),
array("alabama tornadoes","3","","",""),
array("amanda bynes","3","","",""),
array("apartments for rent","3","","",""),
array("answers.com","3","","",""),
array("airline tickets","3","","",""),
array("are vampires real","3","","",""),
array("apple store","3","","",""),
array("am i pregnant quiz","3","","",""),
array("amazon.com","3","","",""),
array("adele rolling in the deep","4","","",""),
array("adele someone like you","4","","",""),
array("akon","4","","",""),
array("annoying orange","4","","",""),
array("all of the lights kanye west","4","","",""),
array("avril lavigne","4","","",""),
array("avril lavigne what the hell","4","","",""),
array("alienware aurora desktop","4","","",""),
array("american idol 2011","4","","","")),
"b" => array(
array("bank of america","0","2","3",""),
array("best buy","0","2","3",""),
array("bed bath and beyond","0","2","3",""),
array("bing","0","2","3",""),
array("barnes and noble","0","2","",""),
array("babies r us","0","2","",""),
array("britney spears","2","4","",""),
array("big 5","0","","",""),
array("bellagio","0","","",""),
array("blockbuster","0","","",""),
array("big lots","0","","",""),
array("blackberry","1","","",""),
array("blackberry torch","1","","",""),
array("beats by dre","1","","",""),
array("born this way","1","","",""),
array("book of mormon","1","","",""),
array("battlefield 3","1","","",""),
array("backpack","1","","",""),
array("bose","1","","",""),
array("bluetooth headset","1","","",""),
array("black ops","1","","",""),
array("blank","2","","",""),
array("brigitte nielsen","2","","",""),
array("blake lively","2","","",""),
array("bed","3","","",""),
array("black hole","3","","",""),
array("bella vita tattoo","3","","",""),
array("baby names","3","","",""),
array("bmi calculator","3","","",""),
array("baby names and meanings","3","","",""),
array("bluetooth mobile phone spy","4","","",""),
array("bruno mars","4","","",""),
array("bruno mars lazy song","4","","",""),
array("black and yellow wiz khalifa","4","","",""),
array("black eyed peas","4","","",""),
array("beyonce","4","","",""),
array("black eyed peas just can't get enough","4","","",""),
array("baby justin bieber","4","","",""),
array("born this way lady gaga","4","","","")),
"c" => array(
array("craigslist","0","2","3",""),
array("cnn","0","2","",""),
array("chase","0","2","",""),
array("costco","0","2","",""),
array("casey anthony","2","3","",""),
array("capital one","2","3","",""),
array("craigslist las vegas","0","","",""),
array("csn","0","","",""),
array("ccsd","0","","",""),
array("carmax","0","","",""),
array("clark county assessor","0","","",""),
array("cox","0","","",""),
array("camera","1","","",""),
array("crocs","1","","",""),
array("canon 7d","1","","",""),
array("canon","1","","",""),
array("coffee maker","1","","",""),
array("canon 60d","1","","",""),
array("cell phone","1","","",""),
array("call of duty black ops","1","","",""),
array("chromebook","1","","",""),
array("converse","1","","",""),
array("cartoon network","2","","",""),
array("comcast","2","","",""),
array("continental airlines","2","","",""),
array("club penguin","2","","",""),
array("california","3","","",""),
array("capital one financial corp","3","","",""),
array("cheap airline tickets","3","","",""),
array("calculator","3","","",""),
array("cheap flights","3","","",""),
array("calorie counter","3","","",""),
array("currency converter","3","","",""),
array("chris brown","4","","",""),
array("chris brown look at me now","4","","",""),
array("cat daddy","4","","",""),
array("chris brown beautiful people","4","","",""),
array("chris brown yeah 3x","4","","",""),
array("christina aguilera","4","","",""),
array("charlie bit my finger","4","","",""),
array("california king bed","4","","",""),
array("coming home","4","","",""),
array("california gurls katy perry","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("dancing with the stars","0","2","",""),
array("delta airlines","2","3","",""),
array("driving directions","2","3","",""),
array("dmv nevada","0","","",""),
array("delta","0","","",""),
array("dillards","0","","",""),
array("dominos","0","","",""),
array("dmv","0","","",""),
array("disneyland","0","","",""),
array("direct tv","0","","",""),
array("disney","0","","",""),
array("duke nukem forever","1","","",""),
array("digital camera","1","","",""),
array("diapers","1","","",""),
array("dehumidifier","1","","",""),
array("dvd player","1","","",""),
array("dexter","1","","",""),
array("doctor who","1","","",""),
array("dsi","1","","",""),
array("duke nukem","1","","",""),
array("dyson","1","","",""),
array("disney channel","2","","",""),
array("dakota fanning","2","","",""),
array("dell","2","","",""),
array("dish network","2","","",""),
array("dash diet","2","","",""),
array("directv","2","","",""),
array("dave chappelle","3","","",""),
array("diabetes risks","3","","",""),
array("deshon marman","3","","",""),
array("does justin bieber have a girlfriend","3","","",""),
array("definitions.com","3","","",""),
array("dictionary online","3","","",""),
array("disneychannel.com","3","","",""),
array("drake","4","","",""),
array("dubstep","4","","",""),
array("down on me","4","","",""),
array("david guetta","4","","",""),
array("down on me jeremiah ft 50 cent","4","","",""),
array("dynamite taio cruz","4","","",""),
array("don omar","4","","",""),
array("deadmau5","4","","",""),
array("don omar danza kuduro","4","","",""),
array("danza kuduro","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("eminem","1","2","4",""),
array("espn","0","2","",""),
array("enterprise car rental","2","3","",""),
array("edc","0","","",""),
array("easter 2011","0","","",""),
array("etsy","0","","",""),
array("edible arrangements","0","","",""),
array("eppicard","0","","",""),
array("enterprise","0","","",""),
array("ebay motors","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("electronic cigarette","1","","",""),
array("espresso machine","1","","",""),
array("eee pad transformer","1","","",""),
array("electric razor","1","","",""),
array("eddie vedder","1","","",""),
array("ebooks","1","","",""),
array("elisabeth hasselbeck","2","","",""),
array("emma watson","2","","",""),
array("elin nordegren","2","","",""),
array("eva longoria","2","","",""),
array("early hitler letter","2","","",""),
array("enchanted","3","","",""),
array("elizabeth hurley","3","","",""),
array("ed balls","3","","",""),
array("expedia.com","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("extreme couponing","3","","",""),
array("et katty perry","4","","",""),
array("et","4","","",""),
array("eminem not afraid","4","","",""),
array("epic mealtime","4","","",""),
array("eminem i need a doctor","4","","",""),
array("eurovision 2011","4","","",""),
array("enrique iglesias tonight","4","","",""),
array("epic rap battles of history","4","","",""),
array("enrique iglesias","4","","","")),
"f" => array(
array("facebook","0","2","3",""),
array("firefox","0","2","",""),
array("fox news","0","2","",""),
array("food network","0","2","",""),
array("fedex","0","2","",""),
array("free online games","2","3","",""),
array("free music downloads","2","3","",""),
array("fandango","0","","",""),
array("facebook login","0","","",""),
array("frys","0","","",""),
array("forever 21","0","","",""),
array("fafsa","0","","",""),
array("fathers day gifts","1","","",""),
array("fan","1","","",""),
array("flash drive","1","","",""),
array("free kindle books","1","","",""),
array("food processor","1","","",""),
array("feather hair extension","1","","",""),
array("futon","1","","",""),
array("flashlight","1","","",""),
array("fathers day","1","","",""),
array("fire pit","1","","",""),
array("fat joe","2","","",""),
array("fantasy football","2","","",""),
array("ford","2","","",""),
array("frank hill","3","","",""),
array("free ringtones","3","","",""),
array("free games","3","","",""),
array("free credit report","3","","",""),
array("find a person","3","","",""),
array("first name meanings","3","","",""),
array("free people search","3","","",""),
array("friday rebecca black","4","","",""),
array("friday","4","","",""),
array("funny video","4","","",""),
array("firework katy perry","4","","",""),
array("fast and furious 5","4","","",""),
array("funny","4","","",""),
array("funny pranks","4","","",""),
array("fred","4","","",""),
array("fast five","4","","",""),
array("funny cats","4","","","")),
"g" => array(
array("google","0","2","3","4"),
array("google maps","0","2","3",""),
array("games","0","2","3",""),
array("glee","0","1","4",""),
array("gmail","0","2","",""),
array("google search","2","3","",""),
array("google translate","0","","",""),
array("google earth","0","","",""),
array("gamestop","0","","",""),
array("green valley ranch","0","","",""),
array("geico","0","","",""),
array("gps","1","","",""),
array("game of thrones","1","","",""),
array("gift card","1","","",""),
array("garmin","1","","",""),
array("galaxy tab","1","","",""),
array("galaxy tab 10.1","1","","",""),
array("go the f to sleep","1","","",""),
array("garmin gps","1","","",""),
array("gears of war 3","1","","",""),
array("goo","2","","",""),
array("gas prices","2","","",""),
array("george takei","2","","",""),
array("gap","2","","",""),
array("god particle","2","","",""),
array("guillain barre syndrome","3","","",""),
array("gabrielle giffords","3","","",""),
array("george osborne","3","","",""),
array("google.com","3","","",""),
array("google search engine","3","","",""),
array("gnc","3","","",""),
array("give me everything pitbull","4","","",""),
array("grenade bruno mars","4","","",""),
array("give me everything","4","","",""),
array("gummy bear song","4","","",""),
array("grenade","4","","",""),
array("glee friday","4","","",""),
array("give me everything tonight pitbull ft. ne-yo afrojack & nayer","4","","",""),
array("green day","4","","","")),
"h" => array(
array("home depot","0","2","3",""),
array("hotmail","0","2","",""),
array("hulu","0","2","",""),
array("harry potter","1","3","",""),
array("harry potter and the deathly hallows part 2 trailer","3","4","",""),
array("how to kiss","3","4","",""),
array("h&m","0","","",""),
array("hoover dam","0","","",""),
array("hp","0","","",""),
array("house of blues las vegas","0","","",""),
array("hollister","0","","",""),
array("hot topic","0","","",""),
array("hotels.com","0","","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("hunger games","1","","",""),
array("hammock","1","","",""),
array("hello kitty","1","","",""),
array("halo reach","1","","",""),
array("htc","1","","",""),
array("hard drive","1","","",""),
array("heart rate monitor","1","","",""),
array("hangover 3","2","","",""),
array("horoscopes","2","","",""),
array("hi5","2","","",""),
array("halle berry","2","","",""),
array("heidi montag","2","","",""),
array("harian metro","2","","",""),
array("honda","2","","",""),
array("heart problems","3","","",""),
array("how much should i weigh","3","","",""),
array("how to get pregnant","3","","",""),
array("how many calories should i eat a day","3","","",""),
array("how do you spell a word","3","","",""),
array("home depot.com","3","","",""),
array("hangover 2 trailer","4","","",""),
array("happy tree friends","4","","",""),
array("hey soul sister","4","","",""),
array("hello","4","","",""),
array("happy birthday song","4","","",""),
array("hollywood undead","4","","",""),
array("how to love lil wayne","4","","",""),
array("hannah montana","4","","","")),
"i" => array(
array("ipad","0","1","3",""),
array("iphone","1","2","3",""),
array("irs","0","2","",""),
array("itunes","0","2","",""),
array("imdb","0","2","",""),
array("ikea","0","2","",""),
array("ipad 2","0","1","",""),
array("indeed","0","2","",""),
array("ign","0","2","",""),
array("ipod","1","2","",""),
array("iphone 5","0","","",""),
array("ihop","0","","",""),
array("iphone 4","1","","",""),
array("ipod touch","1","","",""),
array("iphone 4 case","1","","",""),
array("ipod touch 4th generation","1","","",""),
array("ipad 2 case","1","","",""),
array("ipod nano","1","","",""),
array("internet explorer","2","","",""),
array("illinois lottery","2","","",""),
array("ibm","3","","",""),
array("indiana","3","","",""),
array("is the world going to end in 2012","3","","",""),
array("instant math answers free","3","","",""),
array("inspirational quotes","3","","",""),
array("is pneumonia contagious","3","","",""),
array("images","3","","",""),
array("is bronchitis contagious","3","","",""),
array("i need a doctor","4","","",""),
array("i just had sex-akon","4","","",""),
array("i need a doctor eminem","4","","",""),
array("im coming home","4","","",""),
array("insidious trailer","4","","",""),
array("i love you","4","","",""),
array("indian songs","4","","",""),
array("i just had sex- lonely island","4","","",""),
array("if i die young the band perry","4","","",""),
array("im into you jennifer lopez","4","","","")),
"j" => array(
array("justin bieber","0","1","3","4"),
array("jcpenney","0","2","",""),
array("jobs","2","3","",""),
array("jennifer lopez","2","4","",""),
array("jet blue","0","","",""),
array("java","0","","",""),
array("jack in the box","0","","",""),
array("jobs in las vegas","0","","",""),
array("justin tv","0","","",""),
array("jersey shore","0","","",""),
array("joanns","0","","",""),
array("japan","0","","",""),
array("juicer","1","","",""),
array("just go with it","1","","",""),
array("jillian michaels","1","","",""),
array("jackie evancho","1","","",""),
array("jack3d","1","","",""),
array("juicy couture","1","","",""),
array("jewelry box","1","","",""),
array("jane eyre","1","","",""),
array("jordan shoes","1","","",""),
array("jennifer connelly","2","","",""),
array("jennifer aniston","2","","",""),
array("jessica simpson","2","","",""),
array("jennifer hudson","2","","",""),
array("johnny depp","2","","",""),
array("jennifer love hewitt","2","","",""),
array("justin timberlake","2","","",""),
array("jk rowling","3","","",""),
array("joss stone","3","","",""),
array("j k rowling","3","","",""),
array("justin bieber cell number","3","","",""),
array("justin bieber phone number for real","3","","",""),
array("jcpenney.com","3","","",""),
array("jobs in my area","3","","",""),
array("justin bieber quiz","3","","",""),
array("justin bieber baby","4","","",""),
array("judas lady gaga","4","","",""),
array("jennifer lopez on the floor","4","","",""),
array("justin bieber never say never","4","","",""),
array("judas","4","","",""),
array("just can't get enough black eyed peas","4","","",""),
array("jar of hearts","4","","",""),
array("just the way you are","4","","","")),
"k" => array(
array("kmart","0","2","3",""),
array("kohls","0","3","",""),
array("kayak","0","1","",""),
array("kelly blue book","0","3","",""),
array("kindle","1","3","",""),
array("katy perry","2","4","",""),
array("knotts berry farm","0","","",""),
array("ktnv","0","","",""),
array("kfc","0","","",""),
array("kinkos","0","","",""),
array("klas tv","0","","",""),
array("kate middleton","0","","",""),
array("kinect","1","","",""),
array("kindle cover","1","","",""),
array("keurig","1","","",""),
array("k cups","1","","",""),
array("kindle case","1","","",""),
array("knife","1","","",""),
array("keyboard","1","","",""),
array("kitchenaid mixer","1","","",""),
array("karina smirnoff","2","","",""),
array("kim kardashian","2","","",""),
array("kate hudson","2","","",""),
array("kristen stewart","2","","",""),
array("kelley blue book","2","","",""),
array("kate gosselin","2","","",""),
array("katie holmes","2","","",""),
array("katie couric","2","","",""),
array("keri hilson","3","","",""),
array("kim cattrall","3","","",""),
array("kim clijsters","3","","",""),
array("kids games","3","","",""),
array("kellybluebook.com","3","","",""),
array("kia","3","","",""),
array("katy perry et","4","","",""),
array("katy perry firework","4","","",""),
array("kelly rowland motivation","4","","",""),
array("kanye west","4","","",""),
array("kid cudi","4","","",""),
array("kesha we r who we r","4","","",""),
array("kanye west all of the lights","4","","",""),
array("kesha blown","4","","",""),
array("kiss","4","","","")),
"l" => array(
array("lady gaga","1","2","4",""),
array("lowes","0","3","",""),
array("lady gaga born this way","1","4","",""),
array("lyrics","2","3","",""),
array("love quotes","2","3","",""),
array("las vegas review journal","0","","",""),
array("las vegas sun","0","","",""),
array("las vegas weather","0","","",""),
array("las vegas news","0","","",""),
array("lvac","0","","",""),
array("las vegas craigslist","0","","",""),
array("las vegas dmv","0","","",""),
array("las vegas library","0","","",""),
array("louis vuitton","0","","",""),
array("la noire","1","","",""),
array("laptop computer","1","","",""),
array("lego","1","","",""),
array("luggage","1","","",""),
array("laptop","1","","",""),
array("lego star wars","1","","",""),
array("lord of the rings","1","","",""),
array("laptop bag","1","","",""),
array("larry hagman","2","","",""),
array("lauren alaina","2","","",""),
array("lindsay lohan","2","","",""),
array("limewire","2","","",""),
array("lowe's home improvement","2","","",""),
array("lauryn hill","2","","",""),
array("les paul","2","","",""),
array("lady gaga meat dress","3","","",""),
array("least free state","3","","",""),
array("lauren spierer","3","","",""),
array("lowes.com","3","","",""),
array("lyrics to songs","3","","",""),
array("love poems","3","","",""),
array("lingerie","3","","",""),
array("look at me now chris brown","4","","",""),
array("lazy song bruno mars","4","","",""),
array("lil wayne","4","","",""),
array("look at me now","4","","",""),
array("lady gaga judas","4","","",""),
array("lmfao party rock anthem","4","","",""),
array("lazy song","4","","",""),
array("lil wayne 6 foot 7 foot","4","","","")),
"m" => array(
array("mapquest","0","2","3",""),
array("msn","0","2","",""),
array("maps","0","3","",""),
array("myspace","0","2","",""),
array("minecraft","0","4","",""),
array("modern warfare 3","1","4","",""),
array("music","2","3","",""),
array("miley cyrus","2","4","",""),
array("michael jackson","2","4","",""),
array("mandalay bay","0","","",""),
array("macys","0","","",""),
array("msnbc","0","","",""),
array("michaels","0","","",""),
array("mgm grand","0","","",""),
array("macbook pro","1","","",""),
array("mp3 player","1","","",""),
array("macbook","1","","",""),
array("mortal kombat","1","","",""),
array("micro sd","1","","",""),
array("motorola xoom","1","","",""),
array("macbook air","1","","",""),
array("mouse","1","","",""),
array("mac","1","","",""),
array("mila kunis","2","","",""),
array("morgan freeman","2","","",""),
array("mail","2","","",""),
array("megan fox","2","","",""),
array("mets","3","","",""),
array("milwaukee brewers","3","","",""),
array("minnesota twins","3","","",""),
array("mapquest driving directions","3","","",""),
array("math answers","3","","",""),
array("macys.com","3","","",""),
array("medical dictionary","3","","",""),
array("motivation kelly rowland","4","","",""),
array("mariah carey","4","","",""),
array("mac miller","4","","",""),
array("mean taylor swift","4","","",""),
array("marry you bruno mars","4","","",""),
array("metallica","4","","","")),
"n" => array(
array("netflix","0","2","3",""),
array("nordstrom","0","2","",""),
array("nevada dmv","0","","",""),
array("nv energy","0","","",""),
array("nevada unemployment","0","","",""),
array("nba","0","","",""),
array("nevada state bank","0","","",""),
array("nevada federal credit union","0","","",""),
array("nick","0","","",""),
array("news","0","","",""),
array("nook","1","","",""),
array("nintendo 3ds","1","","",""),
array("nintendo ds","1","","",""),
array("nikon d7000","1","","",""),
array("nokia n8","1","","",""),
array("nikon d3100","1","","",""),
array("nook color","1","","",""),
array("nike","1","","",""),
array("nikon","1","","",""),
array("nikon d5100","1","","",""),
array("natalie portman","2","","",""),
array("nicole kidman","2","","",""),
array("nick jr","2","","",""),
array("nfl","2","","",""),
array("new dog breeds","2","","",""),
array("nintendo wii 2","2","","",""),
array("neil patrick harris","2","","",""),
array("nascar","2","","",""),
array("natalie kenly","3","","",""),
array("nikki reed","3","","",""),
array("nancy bener","3","","",""),
array("name meanings","3","","",""),
array("names and meaning","3","","",""),
array("nissan","3","","",""),
array("nickelodeon games","3","","",""),
array("naked","3","","",""),
array("nissan cars","3","","",""),
array("nicki minaj","4","","",""),
array("nigahiga","4","","",""),
array("nicki minaj super bass","4","","",""),
array("never say never","4","","",""),
array("new songs 2011","4","","",""),
array("never say never justin bieber","4","","",""),
array("nicki minaj moment 4 life","4","","",""),
array("nyan cat","4","","",""),
array("nickelback","4","","",""),
array("no hands","4","","","")),
"o" => array(
array("old navy","0","2","3",""),
array("orbitz","0","2","",""),
array("office depot","0","2","",""),
array("overstock","0","2","",""),
array("online dictionary","2","3","",""),
array("online games","2","3","",""),
array("olive garden","0","","",""),
array("office max","0","","",""),
array("orleans","0","","",""),
array("orchard bank","0","","",""),
array("omegle","0","","",""),
array("oprah","0","","",""),
array("oakley","1","","",""),
array("oakley sunglasses","1","","",""),
array("otterbox","1","","",""),
array("otterbox iphone 4","1","","",""),
array("opi","1","","",""),
array("oakley sunglasses for men","1","","",""),
array("opi nail polish","1","","",""),
array("office chair","1","","",""),
array("outdoor speakers","1","","",""),
array("oblivion","1","","",""),
array("omg","2","","",""),
array("oprah winfrey","2","","",""),
array("orkut","2","","",""),
array("oil stocks","2","","",""),
array("obese","3","","",""),
array("ohio","3","","",""),
array("oracle corp","3","","",""),
array("online pregnancy test","3","","",""),
array("ovulation calculator","3","","",""),
array("ovulation calendar","3","","",""),
array("online calculator","3","","",""),
array("on the floor jennifer lopez","4","","",""),
array("on the floor","4","","",""),
array("osama bin laden","4","","",""),
array("osama bin laden video","4","","",""),
array("osama bin laden dead","4","","",""),
array("on the floor jennifer lopez ft pitbull","4","","",""),
array("on my level wiz khalifa","4","","",""),
array("on the floor lyrics","4","","",""),
array("one time justin bieber","4","","",""),
array("osama bin laden death video","4","","","")),
"p" => array(
array("pandora","0","2","",""),
array("pizza hut","0","2","",""),
array("paypal","0","2","",""),
array("priceline","0","2","",""),
array("photobucket","0","2","",""),
array("portal 2","1","4","",""),
array("people search","2","3","",""),
array("parentlink","0","","",""),
array("papa johns","0","","",""),
array("pirate bay","0","","",""),
array("playstation network","0","","",""),
array("petsmart","0","","",""),
array("ps3","1","","",""),
array("playstation 3","1","","",""),
array("psp","1","","",""),
array("p90x","1","","",""),
array("portable air conditioner","1","","",""),
array("ps3 controller","1","","",""),
array("pool","1","","",""),
array("portable dvd player","1","","",""),
array("pokemon","1","","",""),
array("pippa middleton","2","","",""),
array("pogo","2","","",""),
array("poptropica","2","","",""),
array("plentyoffish","2","","",""),
array("phil mickelson","3","","",""),
array("petra ecclestone","3","","",""),
array("pulseless heart","3","","",""),
array("pregnancy week by week","3","","",""),
array("phone number lookup","3","","",""),
array("prom dresses","3","","",""),
array("people search for free","3","","",""),
array("people finder","3","","",""),
array("put my word in a sentence","3","","",""),
array("party rock anthem","4","","",""),
array("price tag","4","","",""),
array("pitbull","4","","",""),
array("price tag jesse j","4","","",""),
array("pink","4","","",""),
array("party rock anthem lmfao","4","","",""),
array("pacquiao vs mosley","4","","",""),
array("pirates of the caribbean 4 official trailer","4","","",""),
array("paramore","4","","","")),
"q" => array(
array("qvc","0","2","3",""),
array("quotes","0","2","3",""),
array("quickbooks","1","2","3",""),
array("qwop","0","4","",""),
array("quest diagnostics","0","2","",""),
array("quiznos","0","2","",""),
array("quicktime","0","2","",""),
array("quotes about life","0","3","",""),
array("queen","1","4","",""),
array("quest diagnostics las vegas","0","","",""),
array("quibids","0","","",""),
array("queen elizabeth","0","","",""),
array("quickbooks pro 2011","1","","",""),
array("quicken","1","","",""),
array("quiksilver","1","","",""),
array("queen mattress","1","","",""),
array("quilt","1","","",""),
array("queen bed frame","1","","",""),
array("quinoa","1","","",""),
array("queen sheet set","1","","",""),
array("qwest","2","","",""),
array("query string","2","","",""),
array("qatar airways","2","","",""),
array("quentin tarantino","2","","",""),
array("quotes of the day","3","","",""),
array("quizzes","3","","",""),
array("quotes and sayings","3","","",""),
array("quick mileage city to city","3","","",""),
array("questions and answers","3","","",""),
array("qvc home shopping","3","","",""),
array("queen bohemian rhapsody","4","","",""),
array("quest crew","4","","",""),
array("queen we will rock you","4","","",""),
array("queens of the stone age","4","","",""),
array("queen don't stop me now","4","","",""),
array("qgjumbdaqiw","4","","",""),
array("queen somebody to love","4","","",""),
array("qro4yzeyl0i","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("eminem","1","2","4",""),
array("espn","0","2","",""),
array("enterprise car rental","2","3","",""),
array("edc","0","","",""),
array("easter 2011","0","","",""),
array("etsy","0","","",""),
array("edible arrangements","0","","",""),
array("eppicard","0","","",""),
array("enterprise","0","","",""),
array("ebay motors","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("electronic cigarette","1","","",""),
array("espresso machine","1","","",""),
array("eee pad transformer","1","","",""),
array("electric razor","1","","",""),
array("eddie vedder","1","","",""),
array("ebooks","1","","",""),
array("elisabeth hasselbeck","2","","",""),
array("emma watson","2","","",""),
array("elin nordegren","2","","",""),
array("eva longoria","2","","",""),
array("early hitler letter","2","","",""),
array("enchanted","3","","",""),
array("elizabeth hurley","3","","",""),
array("ed balls","3","","",""),
array("expedia.com","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("extreme couponing","3","","",""),
array("et katty perry","4","","",""),
array("et","4","","",""),
array("eminem not afraid","4","","",""),
array("epic mealtime","4","","",""),
array("eminem i need a doctor","4","","",""),
array("eurovision 2011","4","","",""),
array("epic rap battles of history","4","","",""),
array("enrique iglesias","4","","",""),
array("enrique iglesias tonight","4","","","")),
"s" => array(
array("sears","0","2","3",""),
array("sprint","0","2","",""),
array("southwest airlines","2","3","",""),
array("selena gomez","2","4","",""),
array("southwest","0","","",""),
array("skype","0","","",""),
array("southwest gas","0","","",""),
array("smiths","0","","",""),
array("spirit airlines","0","","",""),
array("sams club","0","","",""),
array("station casinos","0","","",""),
array("starbucks","0","","",""),
array("sunglasses","1","","",""),
array("search amazon.com","1","","",""),
array("samsung galaxy tab","1","","",""),
array("samsung galaxy s2","1","","",""),
array("samsung galaxy tab 10.1","1","","",""),
array("sd card","1","","",""),
array("star wars","1","","",""),
array("skullcandy headphones","1","","",""),
array("speakers","1","","",""),
array("samsung galaxy","1","","",""),
array("susan sarandon","2","","",""),
array("sandra bullock","2","","",""),
array("shania twain","2","","",""),
array("sarah palin","2","","",""),
array("search","2","","",""),
array("staples","2","","",""),
array("shangri la","3","","",""),
array("samsonite","3","","",""),
array("shirley bond","3","","",""),
array("scary maze game","3","","",""),
array("sears.com","3","","",""),
array("spanish dictionary","3","","",""),
array("sexy","3","","",""),
array("song lyrics","3","","",""),
array("super bass nicki minaj","4","","",""),
array("shakira","4","","",""),
array("super bass","4","","",""),
array("selena gomez who says","4","","",""),
array("smosh","4","","",""),
array("skrillex","4","","",""),
array("soulja boy","4","","",""),
array("snoop dogg","4","","",""),
array("shakira waka waka","4","","","")),
"t" => array(
array("target","0","2","",""),
array("twitter","0","2","",""),
array("translator","0","3","",""),
array("ticketmaster","0","2","",""),
array("tmz","0","2","",""),
array("travelocity","0","2","",""),
array("taylor swift","2","4","",""),
array("thesaurus","0","","",""),
array("tumblr","0","","",""),
array("tmobile","0","","",""),
array("town square las vegas","0","","",""),
array("true grit","1","","",""),
array("tablet","1","","",""),
array("true blood season 3","1","","",""),
array("true blood","1","","",""),
array("tent","1","","",""),
array("the help","1","","",""),
array("toms","1","","",""),
array("the hunger games","1","","",""),
array("tangled","1","","",""),
array("trampoline","1","","",""),
array("titanic ii","2","","",""),
array("tiger woods","2","","",""),
array("toys r us","2","","",""),
array("tagged","2","","",""),
array("tatum o neal","3","","",""),
array("tupac shakur","3","","",""),
array("tori spelling","3","","",""),
array("translate english to spanish","3","","",""),
array("tattoo designs","3","","",""),
array("translate spanish to english","3","","",""),
array("travelocity.com","3","","",""),
array("teen pregnancy signs","3","","",""),
array("tattoos","3","","",""),
array("the lazy song bruno mars","4","","",""),
array("teach me how to dougie","4","","",""),
array("the lazy song","4","","",""),
array("till the world ends britney spears","4","","",""),
array("transformers 3 official trailer","4","","",""),
array("the show goes on lupe fiasco","4","","",""),
array("tom and jerry","4","","",""),
array("talking dog","4","","",""),
array("taylor swift mean","4","","","")),
"u" => array(
array("united airlines","0","2","3",""),
array("us airways","0","2","3",""),
array("ufc","0","2","4",""),
array("usps","0","2","",""),
array("ups","0","2","",""),
array("usaa","0","2","",""),
array("ups tracking","0","3","",""),
array("used cars","2","3","",""),
array("unlv","0","","",""),
array("utube","0","","",""),
array("us bank","0","","",""),
array("unlocked cell phones","1","","",""),
array("usb flash drive","1","","",""),
array("under armour","1","","",""),
array("umbrella","1","","",""),
array("uncharted 3","1","","",""),
array("usb hub","1","","",""),
array("unbroken","1","","",""),
array("uncharted","1","","",""),
array("ukulele","1","","",""),
array("uncharted 2","1","","",""),
array("univision","2","","",""),
array("utusan malaysia","2","","",""),
array("university of phoenix","2","","",""),
array("used cars for sale in my area","3","","",""),
array("used cars for sale","3","","",""),
array("unique baby names","3","","",""),
array("unclaimed money","3","","",""),
array("unemployment benefits","3","","",""),
array("usairways.com","3","","",""),
array("usher","4","","",""),
array("usher more","4","","",""),
array("usher dj got us falling in love","4","","",""),
array("ufo","4","","",""),
array("u2","4","","",""),
array("usana philippines","4","","",""),
array("unorthodox wretch 32","4","","",""),
array("usher omg","4","","",""),
array("usher yeah","4","","","")),
"v" => array(
array("verizon","0","2","3",""),
array("victoria secret","0","3","",""),
array("vans","0","1","",""),
array("vevo","0","4","",""),
array("victoria's secret","1","2","",""),
array("verizon wireless","2","3","",""),
array("vanessa hudgens","2","4","",""),
array("virgin mobile","2","3","",""),
array("venetian","0","","",""),
array("vons","0","","",""),
array("virgin america","0","","",""),
array("valley of fire","0","","",""),
array("vlc","0","","",""),
array("volaris","0","","",""),
array("vacuum cleaner","1","","",""),
array("verizon cell phones","1","","",""),
array("video camera","1","","",""),
array("vera bradley","1","","",""),
array("vacuum","1","","",""),
array("vitamix","1","","",""),
array("vampire diaries","1","","",""),
array("victorinox","1","","",""),
array("vh1","2","","",""),
array("victoria beckham","2","","",""),
array("valerie bertinelli","2","","",""),
array("video","2","","",""),
array("value city furniture","2","","",""),
array("violent torpedo of truth","3","","",""),
array("verizon.com","3","","",""),
array("very early symptoms of pregnancy","3","","",""),
array("verizonwireless.com","3","","",""),
array("videos","3","","",""),
array("virtual worlds","3","","",""),
array("victorious","4","","",""),
array("victoria justice","4","","",""),
array("vybz kartel","4","","",""),
array("video lucu","4","","",""),
array("vybz kartel 2011","4","","",""),
array("victoria justice beggin on your knees","4","","",""),
array("van halen","4","","",""),
array("vicente fernandez","4","","","")),
"w" => array(
array("white pages","0","2","3",""),
array("walmart","0","2","",""),
array("weather","0","2","",""),
array("wells fargo","0","2","",""),
array("wikipedia","0","2","",""),
array("walgreens","0","2","",""),
array("webmd","0","2","",""),
array("wii","1","3","",""),
array("www.facebook.com","0","","",""),
array("weather las vegas","0","","",""),
array("whole foods","0","","",""),
array("wii games","1","","",""),
array("watch","1","","",""),
array("wireless router","1","","",""),
array("windows 7","1","","",""),
array("wii u","1","","",""),
array("webcam","1","","",""),
array("wallet","1","","",""),
array("wii console","1","","",""),
array("watches for men","1","","",""),
array("webkinz","2","","",""),
array("wwe","2","","",""),
array("wesley snipes","2","","",""),
array("walmart express","3","","",""),
array("weiner doll","3","","",""),
array("what is justin biebers phone number","3","","",""),
array("what does my last name mean","3","","",""),
array("what is the meaning of my name","3","","",""),
array("what is love","3","","",""),
array("what does my dream mean","3","","",""),
array("where can i watch free movies online","3","","",""),
array("wiz khalifa","4","","",""),
array("written in the stars","4","","",""),
array("who says selena gomez","4","","",""),
array("wiz khalifa roll up","4","","",""),
array("waka waka shakira","4","","",""),
array("website traffic generation","4","","",""),
array("what the hell avril lavigne","4","","",""),
array("who says","4","","",""),
array("written in the stars tinie tempah","4","","",""),
array("wiz khalifa on my level","4","","","")),
"x" => array(
array("xbox 360","1","2","3","4"),
array("xbox","0","1","3",""),
array("xm radio","0","2","3",""),
array("xbox live","0","1","2",""),
array("xoom","0","1","",""),
array("xanax","0","2","",""),
array("xbox 360 console","1","3","",""),
array("xbox 360 games","1","3","",""),
array("x factor","2","4","",""),
array("x107.5","0","","",""),
array("xda","0","","",""),
array("xkcd","0","","",""),
array("xs las vegas","0","","",""),
array("xtranormal","0","","",""),
array("xbox 360 controller","1","","",""),
array("xbox 360 kinect","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("xbox 360 wireless adapter","1","","",""),
array("x-men first class","2","","",""),
array("x17","2","","",""),
array("xem phim","2","","",""),
array("xvid","2","","",""),
array("xbox cheats","2","","",""),
array("xxl movie","3","","",""),
array("xbox 360 cheats","3","","",""),
array("xxl tv live","3","","",""),
array("xm satellite radio","3","","",""),
array("xbox live 2 month free trial","3","","",""),
array("xjawz","4","","",""),
array("x men first class trailer","4","","",""),
array("x factor 2011","4","","",""),
array("x men first class","4","","",""),
array("xxl movie six","4","","",""),
array("xzibit","4","","",""),
array("xftfxcyqtdk","4","","",""),
array("x","4","","","")),
"y" => array(
array("youtube","0","2","3","4"),
array("yahoo","0","2","3",""),
array("yahoo mail","0","2","3",""),
array("yellow pages","0","2","3",""),
array("yahoo maps","0","2","",""),
array("y8","0","2","",""),
array("yelp","0","","",""),
array("youtube to mp3","0","","",""),
array("yahoo answers","0","","",""),
array("yahoo finance","0","","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yugioh cards","1","","",""),
array("yoga dvd","1","","",""),
array("yugioh","1","","",""),
array("yo gabba gabba","1","","",""),
array("yarn","1","","",""),
array("yogurt maker","1","","",""),
array("yoga pants","1","","",""),
array("yoyo","1","","",""),
array("youtube video","2","","",""),
array("youtube broadcast yourself","2","","",""),
array("yahoo messenger","2","","",""),
array("yahoo music","2","","",""),
array("youtube videos","3","","",""),
array("yahoo mail login","3","","",""),
array("yellowpages.com","3","","",""),
array("youtube music","3","","",""),
array("youtube.com","3","","",""),
array("yahoo mail inbox","3","","",""),
array("yeah 3x","4","","",""),
array("yeah 3x chris brown","4","","",""),
array("young jeezy","4","","",""),
array("your favorite martian","4","","",""),
array("you belong with me","4","","",""),
array("you belong with me taylor swift","4","","",""),
array("young money","4","","",""),
array("yogscast","4","","",""),
array("yelawolf","4","","","")),
"z" => array(
array("zumba","0","1","3","4"),
array("zappos","0","2","3",""),
array("zip codes","0","2","3",""),
array("zillow","0","2","",""),
array("zune","0","1","",""),
array("zales","0","2","",""),
array("zac brown band","1","4","",""),
array("zodiac signs","2","3","",""),
array("zion national park","0","","",""),
array("zumiez","0","","",""),
array("zillow las vegas","0","","",""),
array("zappos jobs","0","","",""),
array("zippo","1","","",""),
array("zumba fitness dvd","1","","",""),
array("zelda","1","","",""),
array("zune hd","1","","",""),
array("zumba dvd","1","","",""),
array("zumba wii","1","","",""),
array("zippo lighter","1","","",""),
array("zsa zsa gabor","2","","",""),
array("zocor warning","2","","",""),
array("zooey deschanel","2","","",""),
array("zuma","2","","",""),
array("zoe saldana","2","","",""),
array("zip code finder","3","","",""),
array("zappos.com","3","","",""),
array("zip code lookup","3","","",""),
array("zip code list","3","","",""),
array("zip code maps free","3","","",""),
array("zodiac compatibility","3","","",""),
array("zombie","4","","",""),
array("zaz je veux","4","","",""),
array("zac brown band colder weather","4","","",""),
array("zombie cranberries","4","","",""),
array("zaz","4","","",""),
array("zeitgeist","4","","",""),
array("zz top","4","","",""),
array("zeldaxlove64","4","","","")));
?>