<?php $topResults = array(
"a" => array(
array("amazon","0","2","3",""),
array("argos","0","2","",""),
array("aol","0","2","",""),
array("autotrader","0","2","",""),
array("apple","0","1","",""),
array("asda","0","2","",""),
array("ask.com","0","3","",""),
array("ask jeeves","2","3","",""),
array("addicting games","0","","",""),
array("american airlines","0","","",""),
array("abc","0","","",""),
array("acdc","1","","",""),
array("acer aspire one","1","","",""),
array("adidas","1","","",""),
array("apple iphone","1","","",""),
array("american girl","1","","",""),
array("animal crossing","1","","",""),
array("alarm clock","1","","",""),
array("animal crossing city folk","1","","",""),
array("asus","1","","",""),
array("alessandra ambrosio","2","","",""),
array("abby elliott","2","","",""),
array("aaa","2","","",""),
array("american automobile association","2","","",""),
array("ask jeeves a question","3","","",""),
array("area codes","3","","",""),
array("area code lookup","3","","",""),
array("algorithm","3","","",""),
array("amazon.com","3","","",""),
array("aishwarya rai","3","","",""),
array("adriana lima","3","","",""),
array("akon","4","","",""),
array("avril lavigne","4","","",""),
array("alicia keys","4","","",""),
array("american boy","4","","",""),
array("aventura","4","","",""),
array("ashley tisdale","4","","",""),
array("abba","4","","",""),
array("amy winehouse","4","","",""),
array("arcangel","4","","",""),
array("akon dangerous","4","","","")),
"b" => array(
array("barack obama","0","1","3","4"),
array("britney spears","1","2","3","4"),
array("best buy","0","2","3",""),
array("beyonce","1","2","4",""),
array("bebo","0","2","",""),
array("bbc","0","2","",""),
array("bank of america","0","2","",""),
array("blackberry storm","0","1","",""),
array("bed bath and beyond","0","3","",""),
array("bbc news","0","","",""),
array("bbc sport","0","","",""),
array("boots","0","","",""),
array("bakugan","1","","",""),
array("blu ray","1","","",""),
array("blackberry","1","","",""),
array("blackberry bold","1","","",""),
array("batman","1","","",""),
array("blu ray player","1","","",""),
array("british broadcasting corporation","2","","",""),
array("berita harian","2","","",""),
array("brooke shields","2","","",""),
array("babies r us","2","","",""),
array("baby names","3","","",""),
array("barnes and noble","3","","",""),
array("better business bureau","3","","",""),
array("books","3","","",""),
array("burlington coat factory","3","","",""),
array("bmi calculator","3","","",""),
array("basshunter","4","","",""),
array("beyonce if i were a boy","4","","",""),
array("bob marley","4","","",""),
array("bon jovi","4","","",""),
array("beyonce single ladies","4","","",""),
array("bleeding love","4","","",""),
array("blink 182","4","","","")),
"c" => array(
array("craigslist","0","2","3",""),
array("cnn","0","2","",""),
array("currency converter","0","2","",""),
array("circuit city","0","2","",""),
array("costco","0","3","",""),
array("currys","0","2","",""),
array("christina aguilera","1","4","",""),
array("calendar","2","3","",""),
array("chris brown","3","4","",""),
array("club penguin","0","","",""),
array("comet","0","","",""),
array("comcast","0","","",""),
array("cheap flights","0","","",""),
array("call of duty world at war","1","","",""),
array("call of duty","1","","",""),
array("cell phones","1","","",""),
array("christmas","1","","",""),
array("camera","1","","",""),
array("canon","1","","",""),
array("coffee maker","1","","",""),
array("call of duty 5","1","","",""),
array("call of duty 4","1","","",""),
array("camilla belle","2","","",""),
array("cable news network","2","","",""),
array("cellular nonlinear network","2","","",""),
array("cool nicknames","2","","",""),
array("chicks with swords","3","","",""),
array("craigs list","3","","",""),
array("conversion chart","3","","",""),
array("calendar for the year 2008","3","","",""),
array("cartoon network games","3","","",""),
array("consumer reports","3","","",""),
array("coldplay","4","","",""),
array("camp rock","4","","",""),
array("charlie bit my finger","4","","",""),
array("celine dion","4","","",""),
array("crush","4","","",""),
array("crazy frog","4","","",""),
array("ciara","4","","",""),
array("cookie jar","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("dell","0","2","",""),
array("debenhams","0","2","",""),
array("disney","0","2","",""),
array("delta","0","2","",""),
array("driving directions","2","3","",""),
array("disney channel","0","","",""),
array("dancing with the stars","0","","",""),
array("daylight savings time","0","","",""),
array("dominos","0","","",""),
array("dow jones","0","","",""),
array("digital camera","1","","",""),
array("dark knight","1","","",""),
array("dvd","1","","",""),
array("digital photo frame","1","","",""),
array("david cook","1","","",""),
array("ds games","1","","",""),
array("dead space","1","","",""),
array("ds","1","","",""),
array("digital picture frame","1","","",""),
array("dvd player","1","","",""),
array("directions","2","","",""),
array("delta airlines","2","","",""),
array("dmv","2","","",""),
array("department of motor vehicles","2","","",""),
array("definition","3","","",""),
array("distance","3","","",""),
array("dictionary online","3","","",""),
array("distance between 2 cities","3","","",""),
array("distance between locations","3","","",""),
array("definitions","3","","",""),
array("dictionary.com","3","","",""),
array("dogs","3","","",""),
array("disturbia","4","","",""),
array("dangerous","4","","",""),
array("don omar","4","","",""),
array("disturbed","4","","",""),
array("dance","4","","",""),
array("disturbia rihanna","4","","",""),
array("demi lovato","4","","",""),
array("dragon ball z","4","","",""),
array("dane cook","4","","",""),
array("dj tiesto","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("eminem","1","2","4",""),
array("espn","0","2","",""),
array("easyjet","0","2","",""),
array("enya","1","4","",""),
array("ebay uk","0","","",""),
array("election results","0","","",""),
array("exchange rates","0","","",""),
array("ebuddy","0","","",""),
array("election","0","","",""),
array("electoral college","0","","",""),
array("external hard drive","1","","",""),
array("elmo live","1","","",""),
array("elmo","1","","",""),
array("eclipse","1","","",""),
array("ed hardy","1","","",""),
array("electric blanket","1","","",""),
array("eat this not that","1","","",""),
array("eee pc","1","","",""),
array("ecards","2","","",""),
array("enterprise","2","","",""),
array("eva longoria","2","","",""),
array("express","2","","",""),
array("email","2","","",""),
array("early pregnancy symptoms","3","","",""),
array("english dictionary","3","","",""),
array("encyclopedia","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("expedia.com","3","","",""),
array("eagles of death metal","3","","",""),
array("enterprise car rental","3","","",""),
array("enrique iglesias","4","","",""),
array("evanescence","4","","",""),
array("elvis presley","4","","",""),
array("evolution of dance","4","","",""),
array("elton john","4","","",""),
array("eric clapton","4","","",""),
array("emo","4","","",""),
array("eye of the tiger","4","","","")),
"f" => array(
array("facebook","0","2","3",""),
array("free games","0","2","3",""),
array("food network","0","2","3",""),
array("family guy","1","3","4",""),
array("fox news","0","2","",""),
array("facebook login","0","2","",""),
array("fallout 3","0","1","",""),
array("firefox","0","","",""),
array("friendster","0","","",""),
array("free online games","0","","",""),
array("flickr","0","","",""),
array("fable 2","1","","",""),
array("flash drive","1","","",""),
array("futurama","1","","",""),
array("far cry 2","1","","",""),
array("fisher price","1","","",""),
array("friends","1","","",""),
array("food processor","1","","",""),
array("fallout","1","","",""),
array("foreign accent syndrome","2","","",""),
array("fantasy football","2","","",""),
array("fafsa","2","","",""),
array("friends reunited","2","","",""),
array("freida pinto","2","","",""),
array("free music","3","","",""),
array("free downloads","3","","",""),
array("free desktop themes downloads","3","","",""),
array("flowers","3","","",""),
array("free puppies","3","","",""),
array("free resume formats","3","","",""),
array("funny","4","","",""),
array("fred","4","","",""),
array("funny video","4","","",""),
array("fall for you","4","","",""),
array("funny cats","4","","",""),
array("funny accidents","4","","",""),
array("fall out boy","4","","",""),
array("forever","4","","",""),
array("fergie","4","","","")),
"g" => array(
array("google","0","2","3",""),
array("games","0","2","3",""),
array("gmail","0","2","",""),
array("google maps","0","3","",""),
array("google earth","0","3","",""),
array("gamestop","0","3","",""),
array("gap","0","2","",""),
array("gears of war 2","1","4","",""),
array("guitar hero world tour","1","4","",""),
array("guitar hero","1","4","",""),
array("game","2","3","",""),
array("gumtree","0","","",""),
array("gamespot","0","","",""),
array("google translate","0","","",""),
array("gps","1","","",""),
array("gears of war","1","","",""),
array("garmin","1","","",""),
array("guitar hero world tour wii","1","","",""),
array("garmin gps","1","","",""),
array("get smart","1","","",""),
array("guitar","1","","",""),
array("google search","2","","",""),
array("guinness world records","2","","",""),
array("girlfriend nicknames","2","","",""),
array("gloria estefan","2","","",""),
array("geico","2","","",""),
array("google.com","3","","",""),
array("gisele bundchen","3","","",""),
array("grapefruit diet","3","","",""),
array("gnc","3","","",""),
array("green day","4","","",""),
array("ghost","4","","",""),
array("guns n roses","4","","",""),
array("got money","4","","",""),
array("girlfriend","4","","",""),
array("get silly","4","","",""),
array("gucci mane","4","","","")),
"h" => array(
array("hotmail","0","2","3",""),
array("halloween costumes","0","1","2",""),
array("home depot","0","2","3",""),
array("hannah montana","1","3","4",""),
array("halloween","0","4","",""),
array("hsbc","0","2","",""),
array("hmv","0","2","",""),
array("hi5","0","2","",""),
array("harry potter","1","2","",""),
array("high school musical 3","1","4","",""),
array("high school musical","1","4","",""),
array("hulu","0","","",""),
array("hp","0","","",""),
array("halifax","0","","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("humidifier","1","","",""),
array("hellboy 2","1","","",""),
array("hello kitty","1","","",""),
array("harian metro","2","","",""),
array("hongkong and shanghai banking corporation","2","","",""),
array("his master's voice","2","","",""),
array("how to get pregnant","3","","",""),
array("how to tie a tie","3","","",""),
array("how much should i weigh","3","","",""),
array("heidi klum","3","","",""),
array("heath ledger","3","","",""),
array("how many feet in a mile","3","","",""),
array("how long do drugs stay in your system","3","","",""),
array("hot n cold","4","","",""),
array("happy tree friends","4","","",""),
array("hot and cold","4","","",""),
array("high school musical 2","4","","",""),
array("hot n cold katy perry","4","","",""),
array("hot","4","","","")),
"i" => array(
array("iphone","0","1","2","3"),
array("ikea","0","2","3",""),
array("itunes","0","2","3",""),
array("ipod","1","2","3",""),
array("imdb","0","2","",""),
array("images","0","3","",""),
array("ign","0","2","",""),
array("ipod touch","0","1","",""),
array("irs","2","3","",""),
array("itv","0","","",""),
array("isohunt","0","","",""),
array("indian railways","0","","",""),
array("ipod nano","1","","",""),
array("iphone 3g","1","","",""),
array("iron man","1","","",""),
array("ipod shuffle","1","","",""),
array("indiana jones","1","","",""),
array("ipod classic","1","","",""),
array("itouch","1","","",""),
array("internet explorer","2","","",""),
array("u.s. internal revenue service","2","","",""),
array("imeem","2","","",""),
array("inmates","3","","",""),
array("inspirational quotes","3","","",""),
array("inmate search","3","","",""),
array("internet dictionary","3","","",""),
array("if i were a boy","4","","",""),
array("im yours","4","","",""),
array("i kissed a girl- kate perry","4","","",""),
array("in the ayer","4","","",""),
array("if i were a boy beyonce","4","","",""),
array("iron maiden","4","","",""),
array("infinity","4","","",""),
array("infinity 2008","4","","",""),
array("i kissed a girl'","4","","",""),
array("ice cube","4","","","")),
"j" => array(
array("jobs","0","2","3",""),
array("java","0","2","3",""),
array("jokes","0","2","3",""),
array("jennifer hudson","0","2","",""),
array("john lewis","0","2","",""),
array("jcpenney","0","2","",""),
array("jeff dunham","1","4","",""),
array("jonas brothers","1","4","",""),
array("jason mraz","1","4","",""),
array("jessica simpson","2","3","",""),
array("jessica alba","2","3","",""),
array("jennifer lopez","2","4","",""),
array("john mccain","0","","",""),
array("joe the plumber","0","","",""),
array("jet blue","0","","",""),
array("job centre","0","","",""),
array("james bond","1","","",""),
array("john legend","1","","",""),
array("james patterson","1","","",""),
array("juicy couture","1","","",""),
array("jewelry","1","","",""),
array("journey to the center of the earth","1","","",""),
array("john adams","1","","",""),
array("jennifer aniston","2","","",""),
array("jeeves","3","","",""),
array("jobs in my area","3","","",""),
array("jail inmates","3","","",""),
array("job listings","3","","",""),
array("jc penny","3","","",""),
array("just dance","4","","",""),
array("justin timberlake","4","","",""),
array("jesse mccartney","4","","",""),
array("jackass","4","","",""),
array("jason mraz im yours","4","","",""),
array("jonas brothers burning up","4","","","")),
"k" => array(
array("kanye west","0","1","3","4"),
array("kmart","0","2","3",""),
array("kings of leon","0","1","4",""),
array("kohls","0","3","",""),
array("kelly blue book","0","3","",""),
array("kijiji","0","2","",""),
array("katy perry","0","4","",""),
array("kim kardashian","0","3","",""),
array("kfc","0","2","",""),
array("kazaa","2","3","",""),
array("kelly clarkson","2","4","",""),
array("kayak","0","","",""),
array("kindle","1","","",""),
array("kung fu panda","1","","",""),
array("kung fu panda dvd","1","","",""),
array("keyboard","1","","",""),
array("kindle store","1","","",""),
array("kitchenaid mixer","1","","",""),
array("keurig","1","","",""),
array("keane","1","","",""),
array("kelley blue book","2","","",""),
array("kohl's","2","","",""),
array("keira knightley","2","","",""),
array("kbb","2","","",""),
array("katie holmes","2","","",""),
array("kate moss","3","","",""),
array("kt tunstall","3","","",""),
array("kids","3","","",""),
array("kay jewelers","3","","",""),
array("katy perry hot n cold","4","","",""),
array("kiss","4","","",""),
array("korn","4","","",""),
array("kid rock","4","","",""),
array("kanye west love lockdown","4","","",""),
array("katy perry i kissed a girl'","4","","","")),
"l" => array(
array("limewire","0","2","3",""),
array("lyrics","0","2","3",""),
array("lil wayne","0","3","4",""),
array("lowes","0","3","",""),
array("love quotes","0","2","",""),
array("lost","1","2","",""),
array("lindsay lohan","2","3","",""),
array("lotto","0","","",""),
array("lloyds tsb","0","","",""),
array("linens and things","0","","",""),
array("littlewoods","0","","",""),
array("line rider","0","","",""),
array("laptop","1","","",""),
array("lego","1","","",""),
array("left 4 dead","1","","",""),
array("little big planet","1","","",""),
array("leapster","1","","",""),
array("lego star wars","1","","",""),
array("laptop computer","1","","",""),
array("luggage","1","","",""),
array("littlest pet shop","1","","",""),
array("launch","2","","",""),
array("lowe's","2","","",""),
array("love poems","2","","",""),
array("lottery","2","","",""),
array("las vegas","2","","",""),
array("lowes.com","3","","",""),
array("last names","3","","",""),
array("lyrics to songs","3","","",""),
array("locations","3","","",""),
array("love","3","","",""),
array("live your life","4","","",""),
array("linkin park","4","","",""),
array("let it rock","4","","",""),
array("love lockdown","4","","",""),
array("leona lewis","4","","",""),
array("love story","4","","",""),
array("lollipop","4","","",""),
array("lady gaga","4","","",""),
array("low","4","","","")),
"m" => array(
array("myspace","0","2","3",""),
array("mapquest","0","2","3",""),
array("maps","0","2","3",""),
array("music","1","3","4",""),
array("msn","0","2","",""),
array("miniclip","0","2","",""),
array("macys","0","3","",""),
array("mininova","0","2","",""),
array("metallica","1","4","",""),
array("miley cyrus","3","4","",""),
array("myspace layouts","0","","",""),
array("msnbc","0","","",""),
array("mapquest driving directions","0","","",""),
array("macbook","1","","",""),
array("mp3 player","1","","",""),
array("macbook pro","1","","",""),
array("mp3","1","","",""),
array("micro sd","1","","",""),
array("mamma mia","1","","",""),
array("mario kart wii","1","","",""),
array("movies","1","","",""),
array("mail","2","","",""),
array("malin akerman","2","","",""),
array("macy's","2","","",""),
array("marks and spencer","2","","",""),
array("metric conversion table","3","","",""),
array("metric conversion chart","3","","",""),
array("myspace.com","3","","",""),
array("map","3","","",""),
array("michael jackson","4","","",""),
array("madonna","4","","",""),
array("mariah carey","4","","",""),
array("my life","4","","",""),
array("miss independent","4","","",""),
array("mia","4","","",""),
array("miley cyrus 7 things","4","","","")),
"n" => array(
array("naruto","1","3","4",""),
array("next","0","2","",""),
array("nbc","0","2","",""),
array("new york times","0","3","",""),
array("national lottery","0","2","",""),
array("nickelback","1","4","",""),
array("news","0","","",""),
array("nfl","0","","",""),
array("netflix","0","","",""),
array("nokia","0","","",""),
array("natwest","0","","",""),
array("new look","0","","",""),
array("nintendo ds","1","","",""),
array("nintendo wii","1","","",""),
array("nintendo ds games","1","","",""),
array("nintendo ds lite","1","","",""),
array("nikon d90","1","","",""),
array("nike","1","","",""),
array("nightmare before christmas","1","","",""),
array("nikon d40","1","","",""),
array("natalie gulbis","2","","",""),
array("nascar","2","","",""),
array("national association for stock car auto racing","2","","",""),
array("nba","2","","",""),
array("national basketball association","2","","",""),
array("national broadcasting corporation","2","","",""),
array("nuclear, biological, and chemical","2","","",""),
array("nonja","3","","",""),
array("ninjuice","3","","",""),
array("ningiants","3","","",""),
array("new movies","3","","",""),
array("nissan","3","","",""),
array("northwest airlines","3","","",""),
array("niki taylor","3","","",""),
array("ninjatar","3","","",""),
array("no air","4","","",""),
array("numa numa","4","","",""),
array("nelly","4","","",""),
array("nirvana","4","","",""),
array("naruto shippuden","4","","",""),
array("ne-yo","4","","",""),
array("nelly furtado","4","","",""),
array("nigahiga","4","","","")),
"o" => array(
array("obama","0","1","3","4"),
array("orkut","0","2","3",""),
array("old navy","0","2","3",""),
array("online games","0","2","3",""),
array("office depot","0","2","3",""),
array("oasis","0","1","4",""),
array("orange","0","2","",""),
array("orbitz","0","2","",""),
array("one tree hill","1","4","",""),
array("online dictionary","2","3","",""),
array("office max","2","3","",""),
array("o2","0","","",""),
array("odeon","0","","",""),
array("outliers","1","","",""),
array("oakley","1","","",""),
array("olpc","1","","",""),
array("onkyo","1","","",""),
array("obama t-shirt","1","","",""),
array("oakley sunglasses","1","","",""),
array("oblivion","1","","",""),
array("oprah","2","","",""),
array("overstock","2","","",""),
array("overstock.com","3","","",""),
array("oxford dictionary","3","","",""),
array("olive garden","3","","",""),
array("one step at a time","4","","",""),
array("obama song","4","","",""),
array("obama speech","4","","",""),
array("old greg","4","","",""),
array("one","4","","",""),
array("offspring","4","","",""),
array("one republic","4","","","")),
"p" => array(
array("pizza hut","0","2","3",""),
array("pokemon","1","3","4",""),
array("photobucket","0","2","",""),
array("paypal","0","2","",""),
array("palin","0","4","",""),
array("pink","1","4","",""),
array("people search","2","3","",""),
array("poems","2","3","",""),
array("pc world","0","","",""),
array("pandora","0","","",""),
array("party city","0","","",""),
array("pirate bay","0","","",""),
array("prop 8","0","","",""),
array("play.com","0","","",""),
array("ps3","1","","",""),
array("psp","1","","",""),
array("playstation 3","1","","",""),
array("portable dvd player","1","","",""),
array("psp 3000","1","","",""),
array("ps3 games","1","","",""),
array("psp games","1","","",""),
array("playstation 2","1","","",""),
array("paula abdul","2","","",""),
array("presidential codenames","2","","",""),
array("pogo","2","","",""),
array("powerball","2","","",""),
array("pottery barn","2","","",""),
array("paris hilton","3","","",""),
array("pictures","3","","",""),
array("passport application","3","","",""),
array("periodic table","3","","",""),
array("pregnancy first signs","3","","",""),
array("phrases","3","","",""),
array("pink so what","4","","",""),
array("paper planes","4","","",""),
array("paramore","4","","",""),
array("phil collins","4","","",""),
array("pink floyd","4","","",""),
array("pose","4","","",""),
array("plies","4","","","")),
"q" => array(
array("quantum of solace","0","1","2","4"),
array("quotes","0","2","3",""),
array("qvc","0","2","3",""),
array("quicktime","0","2","3",""),
array("qantas","0","2","",""),
array("quarantine","0","4","",""),
array("quiznos","0","3","",""),
array("queen","1","4","",""),
array("queens of the stone age","1","4","",""),
array("quest diagnostics","0","","",""),
array("quizzes","0","","",""),
array("quiz","0","","",""),
array("q-tip","1","","",""),
array("quickbooks","1","","",""),
array("quicken","1","","",""),
array("quiksilver","1","","",""),
array("queer as folk","1","","",""),
array("quickbooks pro 2009","1","","",""),
array("quantum of solace soundtrack","1","","",""),
array("quality, value, convenience","2","","",""),
array("queensland and northern territory aerial services","2","","",""),
array("quit smoking","2","","",""),
array("quality inn","2","","",""),
array("qatar airways","2","","",""),
array("questions","3","","",""),
array("quotes by famous people","3","","",""),
array("quotes on life","3","","",""),
array("quick weight loss","3","","",""),
array("quizes","3","","",""),
array("quotes about life","3","","",""),
array("queen bohemian rhapsody","4","","",""),
array("quantum of solace trailer","4","","",""),
array("quarantine trailer","4","","",""),
array("queen we will rock you","4","","",""),
array("qlimax","4","","",""),
array("querida enemiga","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("eminem","1","2","4",""),
array("espn","0","2","",""),
array("easyjet","0","2","",""),
array("enya","1","4","",""),
array("ebay uk","0","","",""),
array("election results","0","","",""),
array("exchange rates","0","","",""),
array("ebuddy","0","","",""),
array("election","0","","",""),
array("electoral college","0","","",""),
array("external hard drive","1","","",""),
array("elmo live","1","","",""),
array("elmo","1","","",""),
array("eclipse","1","","",""),
array("ed hardy","1","","",""),
array("electric blanket","1","","",""),
array("eat this not that","1","","",""),
array("eee pc","1","","",""),
array("ecards","2","","",""),
array("enterprise","2","","",""),
array("eva longoria","2","","",""),
array("express","2","","",""),
array("email","2","","",""),
array("early pregnancy symptoms","3","","",""),
array("english dictionary","3","","",""),
array("encyclopedia","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("expedia.com","3","","",""),
array("eagles of death metal","3","","",""),
array("enterprise car rental","3","","",""),
array("enrique iglesias","4","","",""),
array("evanescence","4","","",""),
array("elvis presley","4","","",""),
array("evolution of dance","4","","",""),
array("elton john","4","","",""),
array("eric clapton","4","","",""),
array("emo","4","","",""),
array("eye of the tiger","4","","","")),
"s" => array(
array("southwest airlines","0","2","3",""),
array("sears","0","2","3",""),
array("staples","0","2","3",""),
array("sarah palin","0","4","",""),
array("skype","0","2","",""),
array("snl","0","4","",""),
array("sams club","0","3","",""),
array("sprint","0","2","",""),
array("sony","0","2","",""),
array("shakira","2","4","",""),
array("sky sports","0","","",""),
array("star wars","1","","",""),
array("shoes","1","","",""),
array("spore","1","","",""),
array("sex and the city","1","","",""),
array("scrubs","1","","",""),
array("stephenie meyer","1","","",""),
array("stephen king","1","","",""),
array("sunglasses","1","","",""),
array("sewing machine","1","","",""),
array("sd card","1","","",""),
array("song lyrics","2","","",""),
array("shania twain","2","","",""),
array("southwest","2","","",""),
array("spanish dictionary","3","","",""),
array("search engines","3","","",""),
array("sample letters","3","","",""),
array("spanish translation","3","","",""),
array("spanish english translation","3","","",""),
array("social security","3","","",""),
array("soulja boy","4","","",""),
array("so what","4","","",""),
array("slipknot","4","","",""),
array("sean paul","4","","",""),
array("so what pink","4","","",""),
array("swagger like us","4","","",""),
array("selena gomez","4","","","")),
"t" => array(
array("twilight","0","1","2","4"),
array("target","0","2","3",""),
array("toys r us","0","2","3",""),
array("taylor swift","1","2","4",""),
array("tesco","0","2","",""),
array("ticketmaster","0","2","",""),
array("thesaurus","0","3","",""),
array("translator","0","3","",""),
array("travelocity","0","3","",""),
array("tv guide","0","","",""),
array("tmobile","0","","",""),
array("the dark knight","1","","",""),
array("twilight soundtrack","1","","",""),
array("toys","1","","",""),
array("twilight series","1","","",""),
array("the office","1","","",""),
array("the shack","1","","",""),
array("tropic thunder","1","","",""),
array("transformers","1","","",""),
array("tagged","2","","",""),
array("t www youtube","2","","",""),
array("t-mobile","2","","",""),
array("tattoos","2","","",""),
array("the algorithm","3","","",""),
array("themes","3","","",""),
array("tyra banks","3","","",""),
array("target.com","3","","",""),
array("time zones","3","","",""),
array("t.i","4","","",""),
array("the game","4","","",""),
array("titanic","4","","",""),
array("take a bow","4","","",""),
array("tokio hotel","4","","",""),
array("twilight trailer","4","","",""),
array("techno","4","","",""),
array("thriller","4","","","")),
"u" => array(
array("ups","0","2","3",""),
array("united airlines","0","2","3",""),
array("ufc","0","2","4",""),
array("utube","0","3","",""),
array("usps","0","2","",""),
array("u2","1","4","",""),
array("umbrella","1","4","",""),
array("usher","1","4","",""),
array("used cars","2","3","",""),
array("u tube","2","3","",""),
array("utorrent","0","","",""),
array("urban dictionary","0","","",""),
array("us airways","0","","",""),
array("ucas","0","","",""),
array("ups tracking","0","","",""),
array("uggs","1","","",""),
array("ugg boots","1","","",""),
array("unlocked cell phones","1","","",""),
array("under armour","1","","",""),
array("usb flash drive","1","","",""),
array("usb hub","1","","",""),
array("usb drive","1","","",""),
array("uninterruptible power supply","2","","",""),
array("united parcel service","2","","",""),
array("united states postal service","2","","",""),
array("utusan malaysia","2","","",""),
array("united states map","3","","",""),
array("units of measurement","3","","",""),
array("unique baby names","3","","",""),
array("us map","3","","",""),
array("united states maps","3","","",""),
array("una","4","","",""),
array("ufo","4","","",""),
array("unforgivable","4","","",""),
array("undertaker","4","","",""),
array("usher trading places","4","","",""),
array("underoath","4","","","")),
"v" => array(
array("video","0","2","3","4"),
array("verizon wireless","0","2","3",""),
array("verizon","0","2","3",""),
array("vanessa hudgens","2","3","4",""),
array("vodafone","0","2","",""),
array("victoria secret","0","3","",""),
array("victoria's secret","1","2","",""),
array("virgin","0","","",""),
array("vlc","0","","",""),
array("virgin media","0","","",""),
array("virgin mobile","0","","",""),
array("vue","0","","",""),
array("vests","1","","",""),
array("vacuum cleaner","1","","",""),
array("video games","1","","",""),
array("video camera","1","","",""),
array("vera bradley","1","","",""),
array("vacuum","1","","",""),
array("victorinox","1","","",""),
array("valkyria chronicles","1","","",""),
array("vince flynn","1","","",""),
array("vh1","2","","",""),
array("vonage","2","","",""),
array("volkswagen","2","","",""),
array("veoh","2","","",""),
array("vanessa anne hudgens","3","","",""),
array("victorias secret","3","","",""),
array("videos","3","","",""),
array("very early symptoms of pregnancy","3","","",""),
array("veterans day","3","","",""),
array("viva la vida","4","","",""),
array("viva la vida coldplay","4","","",""),
array("vicente fernandez","4","","",""),
array("van halen","4","","",""),
array("video de sexos","4","","",""),
array("vegas","4","","",""),
array("vanilla ice","4","","",""),
array("vampire weekend","4","","","")),
"w" => array(
array("wikipedia","0","2","3",""),
array("weather","0","2","3",""),
array("white pages","0","2","3",""),
array("webkinz","0","1","2",""),
array("walmart","0","3","",""),
array("www.yahoo.com","0","3","",""),
array("www.youtube.com","0","3","",""),
array("woolworths","0","2","",""),
array("world of warcraft","1","4","",""),
array("wiki","0","","",""),
array("wells fargo","0","","",""),
array("wii","1","","",""),
array("wii fit","1","","",""),
array("wii games","1","","",""),
array("wii console","1","","",""),
array("wall-e","1","","",""),
array("wrath of the lich king","1","","",""),
array("wii music","1","","",""),
array("watches","1","","",""),
array("wal mart","2","","",""),
array("webmd","2","","",""),
array("world's best bottoms","2","","",""),
array("wallpaper","2","","",""),
array("walgreens","2","","",""),
array("www.google.com","3","","",""),
array("what happened to jeeves","3","","",""),
array("walmart.com","3","","",""),
array("web md","3","","",""),
array("womanizer","4","","",""),
array("whatever you like","4","","",""),
array("when i grow up","4","","",""),
array("wisin y yandel","4","","",""),
array("wwe","4","","",""),
array("whitney houston","4","","",""),
array("wow","4","","",""),
array("with you","4","","",""),
array("whatever you like ti","4","","","")),
"x" => array(
array("xbox 360","0","1","2","3"),
array("xbox","1","2","3","4"),
array("xm radio","0","2","3",""),
array("xanax","0","2","3",""),
array("xbox 360 games","0","1","3",""),
array("x factor","0","4","",""),
array("xe","0","2","",""),
array("xbox live","0","1","",""),
array("xkcd","0","","",""),
array("xboard","0","","",""),
array("xvid","0","","",""),
array("xbox 360 console","1","","",""),
array("xbox 360 elite","1","","",""),
array("xbox 360 controller","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("xsi","1","","",""),
array("xbox games","1","","",""),
array("xfactor","2","","",""),
array("xhamster movies","2","","",""),
array("x men","2","","",""),
array("x17","2","","",""),
array("xlxx","2","","",""),
array("x tube","3","","",""),
array("xanga","3","","",""),
array("xbox 360 cheats","3","","",""),
array("xbox cheats","3","","",""),
array("xxl magazine","3","","",""),
array("x factor 2008","4","","",""),
array("xzibit","4","","",""),
array("xavier naidoo","4","","",""),
array("xxl","4","","",""),
array("x factor hero","4","","",""),
array("xuxa","4","","",""),
array("xtreme","4","","","")),
"y" => array(
array("youtube","0","2","3","4"),
array("yahoo","0","2","3",""),
array("yahoo mail","0","2","3",""),
array("yellow pages","0","2","3",""),
array("yahoo messenger","0","2","",""),
array("young jeezy","1","4","",""),
array("you","2","4","",""),
array("youtube videos","2","3","",""),
array("yahoo finance","0","","",""),
array("yahoo answers","0","","",""),
array("yell","0","","",""),
array("yahoo maps","0","","",""),
array("youtube uk","0","","",""),
array("yoga","1","","",""),
array("yoga mat","1","","",""),
array("yo gabba gabba","1","","",""),
array("yoga dvd","1","","",""),
array("yarn","1","","",""),
array("yankee candle","1","","",""),
array("you being beautiful","1","","",""),
array("yugioh","1","","",""),
array("your baby can read","1","","",""),
array("y8","2","","",""),
array("yahoo games","2","","",""),
array("yahoo chat","2","","",""),
array("yahoo.com","3","","",""),
array("you tube","3","","",""),
array("youtube.com","3","","",""),
array("yellowpages.com","3","","",""),
array("you tube.com","3","","",""),
array("you can have whatever you like","4","","",""),
array("you can vote however you like","4","","",""),
array("yes we can","4","","",""),
array("you and me","4","","",""),
array("young buck","4","","",""),
array("yelle","4","","",""),
array("your guardian angel","4","","","")),
"z" => array(
array("zac efron","0","2","3","4"),
array("zip codes","0","2","3",""),
array("zappos","0","2","",""),
array("zillow","0","2","",""),
array("zeitgeist","0","4","",""),
array("zavvi","0","2","",""),
array("zedge","0","2","",""),
array("zune","0","1","",""),
array("zelda","1","4","",""),
array("zombie","1","4","",""),
array("zara","0","","",""),
array("zero punctuation","0","","",""),
array("zippo","1","","",""),
array("zumba","1","","",""),
array("zune 120","1","","",""),
array("zen","1","","",""),
array("zune accessories","1","","",""),
array("zippo lighter","1","","",""),
array("zac brown band","1","","",""),
array("zales","2","","",""),
array("zellers","2","","",""),
array("zoo","2","","",""),
array("zuma","2","","",""),
array("zip code finder","3","","",""),
array("zip code directory","3","","",""),
array("zodiac signs","3","","",""),
array("zip code map","3","","",""),
array("zip code maps free","3","","",""),
array("zip code list","3","","",""),
array("zip code","3","","",""),
array("zip code search","3","","",""),
array("zidane","4","","",""),
array("zz top","4","","",""),
array("zoey 101","4","","",""),
array("zion","4","","",""),
array("zombie nation","4","","",""),
array("zaho","4","","","")));
?>