<?php $topResults = array(
"a" => array(
array("amazon","0","2","3",""),
array("aol","0","2","3",""),
array("addicting games","0","2","",""),
array("american airlines","0","2","",""),
array("ask.com","0","3","",""),
array("att wireless","0","3","",""),
array("abc","0","2","",""),
array("apple","0","1","",""),
array("american idol","2","4","",""),
array("american express","0","","",""),
array("amtrak","0","","",""),
array("acer aspire one","1","","",""),
array("adidas","1","","",""),
array("airsoft guns","1","","",""),
array("audio books","1","","",""),
array("atlas shrugged","1","","",""),
array("act like a lady think like a man","1","","",""),
array("apple iphone","1","","",""),
array("asus","1","","",""),
array("airsoft","1","","",""),
array("ask jeeves","2","","",""),
array("aim","2","","",""),
array("anna kournikova","2","","",""),
array("annika sorenstam","2","","",""),
array("amazon.com","3","","",""),
array("aol.com","3","","",""),
array("att","3","","",""),
array("ask for kids","3","","",""),
array("ask","3","","",""),
array("american eagle","3","","",""),
array("akon","4","","",""),
array("amy winehouse","4","","",""),
array("alicia keys","4","","",""),
array("apologize","4","","",""),
array("avril lavigne","4","","",""),
array("ashley tisdale","4","","",""),
array("alvin and the chipmunks","4","","",""),
array("aventura","4","","",""),
array("achmed","4","","","")),
"b" => array(
array("best buy","0","2","3",""),
array("bank of america","0","2","3",""),
array("bed bath and beyond","0","2","3",""),
array("barnes and noble","0","2","3",""),
array("baby names","0","2","3",""),
array("barack obama","0","3","",""),
array("blockbuster","0","2","",""),
array("burlington coat factory","0","3","",""),
array("britney spears","2","4","",""),
array("bebo","2","3","",""),
array("black friday","0","","",""),
array("best buy stores","0","","",""),
array("blackberry","1","","",""),
array("battlestar galactica","1","","",""),
array("bolt","1","","",""),
array("blackberry storm","1","","",""),
array("blu ray","1","","",""),
array("blackberry curve","1","","",""),
array("blackberry bold","1","","",""),
array("bluetooth headset","1","","",""),
array("blackberry unlocked","1","","",""),
array("bakugan","1","","",""),
array("bbc","2","","",""),
array("babies r us","2","","",""),
array("barack obama biography","3","","",""),
array("bestbuy.com","3","","",""),
array("beyonce","4","","",""),
array("bleeding love","4","","",""),
array("bob marley","4","","",""),
array("bubbly","4","","",""),
array("basshunter","4","","",""),
array("britney","4","","",""),
array("bon jovi","4","","",""),
array("blink 182","4","","",""),
array("bloopers","4","","","")),
"c" => array(
array("craigslist","0","2","3",""),
array("cnn","0","2","3",""),
array("circuit city","0","2","3",""),
array("capital one","0","2","",""),
array("costco","0","","",""),
array("continental airlines","0","","",""),
array("club penguin","0","","",""),
array("comcast.net","0","","",""),
array("chase","0","","",""),
array("comcast","0","","",""),
array("cell phones","1","","",""),
array("canon powershot","1","","",""),
array("coffee maker","1","","",""),
array("canon","1","","",""),
array("crocs","1","","",""),
array("camera","1","","",""),
array("call of duty 4","1","","",""),
array("canon 50d","1","","",""),
array("converse","1","","",""),
array("charlaine harris","1","","",""),
array("cingular","2","","",""),
array("cartoon network","2","","",""),
array("cars","2","","",""),
array("cheryl burke","2","","",""),
array("courtney thorne smith","2","","",""),
array("calendar","2","","",""),
array("craigslist.com","3","","",""),
array("craigs list","3","","",""),
array("coin values","3","","",""),
array("cheap airline tickets","3","","",""),
array("charlotte russe","3","","",""),
array("calculator","3","","",""),
array("cnn.com","3","","",""),
array("chris brown","4","","",""),
array("cascada","4","","",""),
array("celine dion","4","","",""),
array("ciara","4","","",""),
array("crank that","4","","",""),
array("creu","4","","",""),
array("charlie bit me","4","","",""),
array("christina aguilera","4","","",""),
array("carrie underwood","4","","",""),
array("chris crocker","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("disney channel","0","2","3",""),
array("dell","0","2","",""),
array("driving directions","2","3","",""),
array("directions","2","3","",""),
array("dancing with the stars","2","3","",""),
array("dillards","0","","",""),
array("delta","0","","",""),
array("disney","0","","",""),
array("dominos","0","","",""),
array("dictionary webster","0","","",""),
array("direct tv","0","","",""),
array("davids bridal","0","","",""),
array("digital camera","1","","",""),
array("dvd","1","","",""),
array("ds","1","","",""),
array("dvd player","1","","",""),
array("ds games","1","","",""),
array("dvd movies","1","","",""),
array("dexter","1","","",""),
array("depeche mode","1","","",""),
array("digital photo frame","1","","",""),
array("dexter season 3","1","","",""),
array("delta airlines","2","","",""),
array("danica mckellar","2","","",""),
array("dish network","2","","",""),
array("dmv","2","","",""),
array("dictionary.com","3","","",""),
array("dictionary online","3","","",""),
array("dogpile","3","","",""),
array("definitions","3","","",""),
array("definition","3","","",""),
array("dsds","4","","",""),
array("dance","4","","",""),
array("dane cook","4","","",""),
array("don omar","4","","",""),
array("daft punk","4","","",""),
array("dmx","4","","",""),
array("dragonforce","4","","",""),
array("dwight howard","4","","",""),
array("disturbed","4","","",""),
array("dj tiesto","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("espn","0","2","3",""),
array("eminem","1","2","4",""),
array("expedia","0","2","",""),
array("ebay.com","0","3","",""),
array("ed hardy","0","1","",""),
array("express","0","2","",""),
array("ebay motors","0","2","",""),
array("english to spanish translation","0","3","",""),
array("election results","0","","",""),
array("easter 2009","0","","",""),
array("external hard drive","1","","",""),
array("eat this not that","1","","",""),
array("empire total war","1","","",""),
array("eclipse","1","","",""),
array("easter","1","","",""),
array("earbuds","1","","",""),
array("earphones","1","","",""),
array("external hard drive 1tb","1","","",""),
array("ecards","2","","",""),
array("enterprise","2","","",""),
array("eva longoria","2","","",""),
array("easyjet","2","","",""),
array("early pregnancy symptoms","3","","",""),
array("expedia.com","3","","",""),
array("electoral college","3","","",""),
array("espn.com","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("enterprise car rental","3","","",""),
array("enrique iglesias","4","","",""),
array("evanescence","4","","",""),
array("edison chen","4","","",""),
array("emo","4","","",""),
array("evolution of dance","4","","",""),
array("edison","4","","",""),
array("elvis","4","","",""),
array("elton john","4","","",""),
array("enya","4","","","")),
"f" => array(
array("facebook","0","2","3",""),
array("food network","0","2","3",""),
array("free online games","0","2","3",""),
array("facebook login","0","2","",""),
array("fox news","0","3","",""),
array("fedex","0","2","",""),
array("fafsa","0","2","",""),
array("family guy","1","4","",""),
array("flo rida","1","4","",""),
array("free music downloads","2","3","",""),
array("firefox","0","","",""),
array("fandango","0","","",""),
array("forever 21","0","","",""),
array("flash drive","1","","",""),
array("fallout 3","1","","",""),
array("fireproof","1","","",""),
array("fleshlight","1","","",""),
array("flip video","1","","",""),
array("food processor","1","","",""),
array("final fantasy","1","","",""),
array("futurama","1","","",""),
array("false news","2","","",""),
array("fantasy football","2","","",""),
array("ford","2","","",""),
array("facebook.com","3","","",""),
array("free games","3","","",""),
array("free myspace layouts","3","","",""),
array("free ringtones","3","","",""),
array("free music","3","","",""),
array("funny","4","","",""),
array("fergie","4","","",""),
array("funny videos","4","","",""),
array("fights","4","","",""),
array("foo fighters","4","","",""),
array("fall out boy","4","","",""),
array("funny cats","4","","",""),
array("flashing lights","4","","","")),
"g" => array(
array("gmail","0","2","3",""),
array("google maps","0","2","3",""),
array("google earth","0","2","3",""),
array("games","0","2","3",""),
array("gamestop","0","3","",""),
array("google.com","0","3","",""),
array("gap","0","2","",""),
array("garmin","0","1","",""),
array("guitar hero","1","4","",""),
array("guitar","1","4","",""),
array("google","2","3","",""),
array("google search","2","3","",""),
array("gossip girl","0","","",""),
array("geico","0","","",""),
array("gps","1","","",""),
array("guitar hero metallica","1","","",""),
array("garmin gps","1","","",""),
array("guitar hero world tour","1","","",""),
array("garmin nuvi","1","","",""),
array("g1","1","","",""),
array("guess","1","","",""),
array("google homepage","2","","",""),
array("greeting cards","2","","",""),
array("guitar tabs","2","","",""),
array("gmail.com","3","","",""),
array("global warming","3","","",""),
array("green day","4","","",""),
array("ghost","4","","",""),
array("girlfriend","4","","",""),
array("get low","4","","",""),
array("gimme more","4","","",""),
array("good charlotte","4","","",""),
array("gwen stefani","4","","",""),
array("guitar hero 3","4","","","")),
"h" => array(
array("hotmail","0","2","3",""),
array("home depot","0","2","3",""),
array("harry potter","1","2","4",""),
array("house","0","1","",""),
array("halo 3","1","4","",""),
array("hannah montana","1","4","",""),
array("horoscopes","2","3","",""),
array("halloween costumes","2","3","",""),
array("hulu","0","","",""),
array("hollister","0","","",""),
array("hobby lobby","0","","",""),
array("hp","0","","",""),
array("horoscope","0","","",""),
array("hgtv","0","","",""),
array("hallmark","0","","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("halo wars","1","","",""),
array("handbags","1","","",""),
array("hello kitty","1","","",""),
array("hard drive","1","","",""),
array("honda","2","","",""),
array("holiday inn","2","","",""),
array("hi5","2","","",""),
array("hsbc","2","","",""),
array("hairstyles","2","","",""),
array("how to get pregnant","3","","",""),
array("how much should i weigh","3","","",""),
array("hotmail.com","3","","",""),
array("how long do drugs stay in your system","3","","",""),
array("how to tie a tie","3","","",""),
array("halloween costumes for adults","3","","",""),
array("high school musical","4","","",""),
array("happy tree friends","4","","",""),
array("hot","4","","",""),
array("high school musical 2","4","","",""),
array("hip hop","4","","",""),
array("hilary duff","4","","",""),
array("heidi montag","4","","","")),
"i" => array(
array("iphone","0","1","2","4"),
array("imdb","0","2","3",""),
array("ikea","0","2","3",""),
array("itunes","0","2","3",""),
array("irs","0","2","3",""),
array("ipod","1","2","3",""),
array("imeem","0","2","",""),
array("ipod touch","0","1","",""),
array("inauguration day 2009","0","","",""),
array("images","0","","",""),
array("ikea usa","0","","",""),
array("ipod nano","1","","",""),
array("iphone 3g","1","","",""),
array("ipod shuffle","1","","",""),
array("iphone 3g unlocked","1","","",""),
array("ipod touch 2nd generation","1","","",""),
array("itouch","1","","",""),
array("ipod classic","1","","",""),
array("internet explorer","2","","",""),
array("ign","2","","",""),
array("internal revenue service","2","","",""),
array("inspirational quotes","3","","",""),
array("is raven symone pregnant","3","","",""),
array("is santa claus real","3","","",""),
array("iq test","3","","",""),
array("is ciara a man","3","","",""),
array("iron maiden","4","","",""),
array("indiana jones","4","","",""),
array("iron man","4","","",""),
array("independent","4","","",""),
array("incubus","4","","",""),
array("i love you","4","","",""),
array("in the end","4","","",""),
array("i miss you","4","","",""),
array("ice cube","4","","","")),
"j" => array(
array("jobs","0","2","3",""),
array("jokes","0","2","3",""),
array("jonas brothers","1","3","4",""),
array("jcpenney","0","2","",""),
array("java","0","2","",""),
array("juicy couture","0","1","",""),
array("jillian michaels","1","2","",""),
array("jennifer lopez","2","4","",""),
array("jet blue","0","","",""),
array("joann fabrics","0","","",""),
array("john travolta","0","","",""),
array("jett travolta","0","","",""),
array("jcrew","0","","",""),
array("james bond","1","","",""),
array("jason mraz","1","","",""),
array("james patterson","1","","",""),
array("juicer","1","","",""),
array("jewelry","1","","",""),
array("jodi picoult","1","","",""),
array("jim jones","1","","",""),
array("jessica simpson","2","","",""),
array("jessica alba","2","","",""),
array("jetblue","2","","",""),
array("jade goody","2","","",""),
array("john mccain","3","","",""),
array("jobs in my area","3","","",""),
array("john mccain biography","3","","",""),
array("job search","3","","",""),
array("jcpenny.com","3","","",""),
array("jennifer hudson","3","","",""),
array("jc penny","3","","",""),
array("jeff dunham","4","","",""),
array("justin timberlake","4","","",""),
array("jackass","4","","",""),
array("jojo","4","","",""),
array("jumper","4","","",""),
array("james blunt","4","","",""),
array("janet jackson","4","","",""),
array("jack johnson","4","","","")),
"k" => array(
array("kmart","0","2","3",""),
array("kelly clarkson","1","2","4",""),
array("kohls","0","3","",""),
array("kay jewelers","0","3","",""),
array("kim kardashian","0","2","",""),
array("kanye west","1","4","",""),
array("kazaa","2","3","",""),
array("kelly blue book","0","","",""),
array("kinkos","0","","",""),
array("kayak","0","","",""),
array("kroger","0","","",""),
array("kawasaki disease","0","","",""),
array("kristen stewart","0","","",""),
array("kindle","1","","",""),
array("kindle 2","1","","",""),
array("keri hilson","1","","",""),
array("killzone 2","1","","",""),
array("kindle books","1","","",""),
array("kindle 1","1","","",""),
array("kings of leon","1","","",""),
array("keyboard","1","","",""),
array("kelley blue book","2","","",""),
array("kohl's","2","","",""),
array("keira knightley","2","","",""),
array("katie holmes","2","","",""),
array("kbb","2","","",""),
array("kfc","2","","",""),
array("kohls.com","3","","",""),
array("kmart.com","3","","",""),
array("kids games","3","","",""),
array("kennedy half dollar worth","3","","",""),
array("king tut","3","","",""),
array("kidney stones","3","","",""),
array("kimbo","4","","",""),
array("kimbo slice","4","","",""),
array("kiss kiss","4","","",""),
array("kiss","4","","",""),
array("korn","4","","",""),
array("komik","4","","",""),
array("kurtlar vadisi","4","","",""),
array("kissing","4","","","")),
"l" => array(
array("lost","0","1","2","4"),
array("lyrics","0","2","3",""),
array("limewire","0","2","3",""),
array("love quotes","0","2","3",""),
array("lowes","0","3","",""),
array("love poems","2","3","",""),
array("lil wayne","3","4","",""),
array("linens and things","0","","",""),
array("lands end","0","","",""),
array("louis vuitton","0","","",""),
array("line rider","0","","",""),
array("linkedin","0","","",""),
array("laptop","1","","",""),
array("laptop computer","1","","",""),
array("liberty and tyranny","1","","",""),
array("lego","1","","",""),
array("lady gaga","1","","",""),
array("lcd tv","1","","",""),
array("luggage","1","","",""),
array("lego star wars","1","","",""),
array("let the right one in","1","","",""),
array("lindsay lohan","2","","",""),
array("lowe's","2","","",""),
array("las vegas","2","","",""),
array("launch","2","","",""),
array("lottery","2","","",""),
array("lyrics to songs","3","","",""),
array("lowes.com","3","","",""),
array("lyrics.com","3","","",""),
array("lil waynes daughter","3","","",""),
array("low","4","","",""),
array("linkin park","4","","",""),
array("leona lewis","4","","",""),
array("love","4","","",""),
array("love song","4","","",""),
array("lupe fiasco","4","","",""),
array("ludacris","4","","",""),
array("lil mama","4","","","")),
"m" => array(
array("myspace","0","2","3",""),
array("mapquest","0","2","3",""),
array("msn","0","2","3",""),
array("myspace layouts","0","2","3",""),
array("maps","0","2","3",""),
array("music","1","2","4",""),
array("macys","0","3","",""),
array("msnbc","0","","",""),
array("mapquest driving directions","0","","",""),
array("mortgage calculator","0","","",""),
array("miniclip","0","","",""),
array("macbook","1","","",""),
array("mp3 player","1","","",""),
array("mark levin","1","","",""),
array("micro sd","1","","",""),
array("mp3","1","","",""),
array("mouse","1","","",""),
array("macbook pro","1","","",""),
array("mac mini","1","","",""),
array("mark levin liberty and tyranny","1","","",""),
array("mail","2","","",""),
array("microsoft","2","","",""),
array("macy's","2","","",""),
array("martina hingis","2","","",""),
array("myspace.com","3","","",""),
array("mapquest.com","3","","",""),
array("msn.com","3","","",""),
array("map quest","3","","",""),
array("michael jackson","4","","",""),
array("metallica","4","","",""),
array("miley cyrus","4","","",""),
array("mika","4","","",""),
array("madonna","4","","",""),
array("mariah carey","4","","",""),
array("mario","4","","",""),
array("my chemical romance","4","","",""),
array("maroon 5","4","","","")),
"n" => array(
array("netflix","0","2","3",""),
array("nfl","0","2","3",""),
array("nbc","0","3","",""),
array("new york times","0","3","",""),
array("nordstrom","0","2","",""),
array("news","0","3","",""),
array("northwest airlines","0","2","",""),
array("nascar","2","3","",""),
array("naruto","2","4","",""),
array("npr","0","","",""),
array("noaa","0","","",""),
array("nickelodeon","0","","",""),
array("nintendo ds","1","","",""),
array("netbook","1","","",""),
array("nintendo ds games","1","","",""),
array("nikon d90","1","","",""),
array("nintendo wii","1","","",""),
array("nike","1","","",""),
array("nikon d60","1","","",""),
array("nintendo ds lite","1","","",""),
array("nikon d40","1","","",""),
array("nokia e71","1","","",""),
array("nokia","2","","",""),
array("nissan","2","","",""),
array("nadya suleman","2","","",""),
array("natasha bedingfield","2","","",""),
array("nascar.com","3","","",""),
array("nfl.com","3","","",""),
array("napa auto parts","3","","",""),
array("name meanings","3","","",""),
array("no one","4","","",""),
array("nirvana","4","","",""),
array("nickelback","4","","",""),
array("nelly furtado","4","","",""),
array("nelly","4","","",""),
array("nightwish","4","","",""),
array("nba","4","","",""),
array("nigga","4","","",""),
array("naruto shippuden","4","","","")),
"o" => array(
array("obama","0","1","3","4"),
array("office depot","0","2","3",""),
array("old navy","0","2","3",""),
array("online games","0","2","3",""),
array("online dictionary","0","2","3",""),
array("orbitz","0","2","",""),
array("oprah","0","2","",""),
array("overstock","0","2","",""),
array("office max","0","2","",""),
array("olive garden","0","2","",""),
array("one tree hill","1","4","",""),
array("oasis","1","4","",""),
array("orkut","2","3","",""),
array("outliers","1","","",""),
array("oakley","1","","",""),
array("oakley sunglasses","1","","",""),
array("ooma","1","","",""),
array("onkyo","1","","",""),
array("office 2007","1","","",""),
array("oakley sunglasses for men","1","","",""),
array("overstock.com","3","","",""),
array("ovulation calculator","3","","",""),
array("olympics","3","","",""),
array("online pregnancy test","3","","",""),
array("one republic","4","","",""),
array("our song","4","","",""),
array("old greg","4","","",""),
array("one","4","","",""),
array("omarion","4","","",""),
array("one love","4","","",""),
array("om shanti om","4","","","")),
"p" => array(
array("photobucket","0","2","3",""),
array("pizza hut","0","2","3",""),
array("people search","0","2","3",""),
array("paypal","0","2","",""),
array("pottery barn","0","2","",""),
array("pokemon","1","4","",""),
array("poems","2","3","",""),
array("pregnancy","2","3","",""),
array("pandora","0","","",""),
array("papa johns","0","","",""),
array("petsmart","0","","",""),
array("poptropica","0","","",""),
array("pirate bay","0","","",""),
array("ps3","1","","",""),
array("psp","1","","",""),
array("playstation 3","1","","",""),
array("pokemon platinum","1","","",""),
array("p90x","1","","",""),
array("pearl jam","1","","",""),
array("ps3 games","1","","",""),
array("portable dvd player","1","","",""),
array("psp games","1","","",""),
array("pogo","2","","",""),
array("powerball","2","","",""),
array("priceline","2","","",""),
array("pregnancy week by week","3","","",""),
array("pregnancy first signs","3","","",""),
array("periodic table","3","","",""),
array("periodic table of elements","3","","",""),
array("photobucket.com","3","","",""),
array("paramore","4","","",""),
array("piece of me","4","","",""),
array("pink","4","","",""),
array("panic at the disco","4","","",""),
array("pink floyd","4","","",""),
array("plies","4","","",""),
array("pitbull","4","","",""),
array("panda","4","","",""),
array("papa roach","4","","","")),
"q" => array(
array("quotes","0","2","3",""),
array("qvc","0","2","3",""),
array("quizzes","0","2","3",""),
array("quizilla","0","2","3",""),
array("quicktime","0","2","",""),
array("quantum of solace","0","1","",""),
array("quiznos","0","2","",""),
array("quotes about life","0","3","",""),
array("qwest","0","2","",""),
array("quickbooks","1","2","",""),
array("queen","1","4","",""),
array("queer as folk","1","4","",""),
array("quest diagnostics","0","","",""),
array("quantum of solace dvd","1","","",""),
array("quantum of solace blu-ray","1","","",""),
array("quickbooks pro 2009","1","","",""),
array("quicken","1","","",""),
array("quiksilver","1","","",""),
array("queensryche","1","","",""),
array("qantas","2","","",""),
array("query string","2","","",""),
array("qvc.com","3","","",""),
array("quotes by famous people","3","","",""),
array("quotes on life","3","","",""),
array("questions to ask your boyfriend","3","","",""),
array("quotes to live by","3","","",""),
array("queens of the stone age","4","","",""),
array("quaresma","4","","",""),
array("qlimax","4","","",""),
array("quizas","4","","",""),
array("que paso muchacho","4","","",""),
array("quagmire","4","","",""),
array("quran","4","","",""),
array("quentin","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("espn","0","2","3",""),
array("eminem","1","2","4",""),
array("expedia","0","2","",""),
array("ebay.com","0","3","",""),
array("ed hardy","0","1","",""),
array("express","0","2","",""),
array("ebay motors","0","2","",""),
array("english to spanish translation","0","3","",""),
array("election results","0","","",""),
array("easter 2009","0","","",""),
array("external hard drive","1","","",""),
array("eat this not that","1","","",""),
array("empire total war","1","","",""),
array("eclipse","1","","",""),
array("easter","1","","",""),
array("earbuds","1","","",""),
array("earphones","1","","",""),
array("external hard drive 1tb","1","","",""),
array("ecards","2","","",""),
array("enterprise","2","","",""),
array("eva longoria","2","","",""),
array("easyjet","2","","",""),
array("early pregnancy symptoms","3","","",""),
array("expedia.com","3","","",""),
array("electoral college","3","","",""),
array("espn.com","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("enterprise car rental","3","","",""),
array("enrique iglesias","4","","",""),
array("evanescence","4","","",""),
array("edison chen","4","","",""),
array("emo","4","","",""),
array("evolution of dance","4","","",""),
array("edison","4","","",""),
array("elvis","4","","",""),
array("elton john","4","","",""),
array("enya","4","","","")),
"s" => array(
array("southwest airlines","0","2","3",""),
array("sears","0","2","3",""),
array("sams club","0","3","",""),
array("staples","0","2","",""),
array("sprint","0","2","",""),
array("skype","0","2","",""),
array("song lyrics","2","3","",""),
array("shakira","2","4","",""),
array("spanish translation","0","","",""),
array("sports authority","0","","",""),
array("starbucks","0","","",""),
array("sparknotes","0","","",""),
array("shoes","1","","",""),
array("street fighter 4","1","","",""),
array("star wars","1","","",""),
array("sunglasses","1","","",""),
array("slumdog millionaire","1","","",""),
array("shoes women","1","","",""),
array("sd card","1","","",""),
array("steve harvey act like a lady think like a man","1","","",""),
array("star trek","1","","",""),
array("sony cybershot","1","","",""),
array("sony","2","","",""),
array("shawn johnson","2","","",""),
array("sudoku","2","","",""),
array("sarah palin","3","","",""),
array("search engines","3","","",""),
array("symptoms of pregnancy in the first week","3","","",""),
array("sears.com","3","","",""),
array("spanish dictionary","3","","",""),
array("song lyric search","3","","",""),
array("soulja boy","4","","",""),
array("simple plan","4","","",""),
array("step up 2","4","","",""),
array("sean kingston","4","","",""),
array("slipknot","4","","",""),
array("sean paul","4","","",""),
array("superstar","4","","",""),
array("snoop dogg","4","","",""),
array("south park","4","","","")),
"t" => array(
array("target","0","2","3",""),
array("twilight","0","1","3",""),
array("toys r us","0","2","3",""),
array("thesaurus","0","2","3",""),
array("travelocity","0","2","3",""),
array("tv guide","0","2","3",""),
array("ticketmaster","0","2","",""),
array("translator","0","3","",""),
array("twitter","0","2","",""),
array("tattoos","2","3","",""),
array("tmobile","0","","",""),
array("twilight dvd","1","","",""),
array("twilight series","1","","",""),
array("twilight soundtrack","1","","",""),
array("the shack","1","","",""),
array("twilight merchandise","1","","",""),
array("tv","1","","",""),
array("the dream","1","","",""),
array("turbotax","1","","",""),
array("twilight blu ray","1","","",""),
array("toyota","2","","",""),
array("t-mobile","2","","",""),
array("target.com","3","","",""),
array("twilight movie","3","","",""),
array("timbaland","4","","",""),
array("thriller","4","","",""),
array("t-pain","4","","",""),
array("tokio hotel","4","","",""),
array("taylor swift","4","","",""),
array("tarkan","4","","",""),
array("titanic","4","","",""),
array("top gear","4","","",""),
array("techno","4","","",""),
array("timberland","4","","","")),
"u" => array(
array("usps","0","2","3",""),
array("ups","0","2","3",""),
array("united airlines","0","2","3",""),
array("ufc","0","2","4",""),
array("utube","0","3","",""),
array("us airways","0","2","",""),
array("uggs","0","1","",""),
array("usaa","0","2","",""),
array("u2","1","4","",""),
array("umbrella","1","4","",""),
array("used cars","2","3","",""),
array("ups tracking","0","","",""),
array("urban dictionary","0","","",""),
array("unlocked cell phones","1","","",""),
array("usb flash drive","1","","",""),
array("u2 no line on the horizon","1","","",""),
array("usb hub","1","","",""),
array("under armour","1","","",""),
array("underworld","1","","",""),
array("usb drive","1","","",""),
array("utusan malaysia","2","","",""),
array("univision","2","","",""),
array("uhaul","2","","",""),
array("united states map","3","","",""),
array("u tube","3","","",""),
array("ugg boots","3","","",""),
array("utube.com","3","","",""),
array("unique baby names","3","","",""),
array("usher","4","","",""),
array("ufo","4","","",""),
array("uri geller","4","","",""),
array("unforgivable","4","","",""),
array("undertaker","4","","",""),
array("unfaithful","4","","",""),
array("underoath","4","","","")),
"v" => array(
array("verizon wireless","0","2","3",""),
array("verizon","0","2","3",""),
array("video","2","3","4",""),
array("victoria secret","0","3","",""),
array("vh1","0","2","",""),
array("vera bradley","0","1","",""),
array("value city furniture","0","3","",""),
array("victoria's secret","1","2","",""),
array("vanessa hudgens","2","4","",""),
array("valkyrie","0","","",""),
array("vlc","0","","",""),
array("vanguard","0","","",""),
array("veoh","0","","",""),
array("vacuum cleaner","1","","",""),
array("venture brothers season 3","1","","",""),
array("video camera","1","","",""),
array("vacuum","1","","",""),
array("verizon cell phones","1","","",""),
array("van morrison","1","","",""),
array("vans","1","","",""),
array("victorinox","1","","",""),
array("valerie bertinelli","2","","",""),
array("vanessa redgrave","2","","",""),
array("volkswagen","2","","",""),
array("vonage","2","","",""),
array("very early symptoms of pregnancy","3","","",""),
array("videos","3","","",""),
array("verizon.com","3","","",""),
array("very early pregnancy signs","3","","",""),
array("vampires","3","","",""),
array("van halen","4","","",""),
array("valerie","4","","",""),
array("vicente fernandez","4","","",""),
array("valentine","4","","",""),
array("vince carter","4","","",""),
array("valentines day","4","","",""),
array("vida guerra","4","","",""),
array("vanilla sky","4","","","")),
"w" => array(
array("weather","0","2","3",""),
array("wikipedia","0","2","3",""),
array("white pages","0","2","3",""),
array("webkinz","0","1","2",""),
array("walmart","0","3","",""),
array("walgreens","0","2","",""),
array("wells fargo","0","2","",""),
array("wwe","2","4","",""),
array("web md","0","","",""),
array("www.yahoo.com","0","","",""),
array("www.myspace.com","0","","",""),
array("wii","1","","",""),
array("wii fit","1","","",""),
array("watchmen","1","","",""),
array("wii games","1","","",""),
array("wii console","1","","",""),
array("watches","1","","",""),
array("wireless router","1","","",""),
array("webcam","1","","",""),
array("wii fit bundle","1","","",""),
array("wal mart","2","","",""),
array("webmd","2","","",""),
array("weight watchers","2","","",""),
array("walmart.com","3","","",""),
array("www.google.com","3","","",""),
array("what happened to jeeves","3","","",""),
array("what does my name mean","3","","",""),
array("www.youtube.com","3","","",""),
array("where can i find pictures of hairstyles","3","","",""),
array("with you","4","","",""),
array("wow","4","","",""),
array("wisin y yandel","4","","",""),
array("westlife","4","","",""),
array("whitney houston","4","","",""),
array("world of warcraft","4","","",""),
array("what is love","4","","",""),
array("what hurts the most","4","","",""),
array("weird al","4","","","")),
"x" => array(
array("xbox 360","0","1","2","3"),
array("xm radio","0","2","3",""),
array("xbox live","0","1","2",""),
array("xbox 360 games","0","1","3",""),
array("xanax","0","2","3",""),
array("xanga","0","3","",""),
array("xbox","1","3","",""),
array("xkcd","0","","",""),
array("xm radio online","0","","",""),
array("xcel energy","0","","",""),
array("xbox 720","0","","",""),
array("xbox 360 console","1","","",""),
array("xbox 360 controller","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("xbox 360 elite","1","","",""),
array("xbox 360 wireless adapter","1","","",""),
array("xsi","1","","",""),
array("xbox cheats","2","","",""),
array("xvid","2","","",""),
array("xbox games","2","","",""),
array("xhamster movies","2","","",""),
array("xerox","2","","",""),
array("xenical","2","","",""),
array("x tube","3","","",""),
array("xbox 360 cheats","3","","",""),
array("xm satellite radio","3","","",""),
array("x tube videos","3","","",""),
array("x factor","4","","",""),
array("xzibit","4","","",""),
array("xuxa","4","","",""),
array("xavier naidoo","4","","",""),
array("xxl","4","","",""),
array("x japan","4","","",""),
array("xtreme","4","","",""),
array("x-men","4","","",""),
array("x games","4","","","")),
"y" => array(
array("youtube","0","2","3","4"),
array("yahoo","0","2","3",""),
array("yahoo mail","0","2","3",""),
array("yellow pages","0","2","3",""),
array("yahoo maps","0","2","",""),
array("yahoo messenger","0","2","",""),
array("yahoo games","0","2","",""),
array("yahoo answers","0","","",""),
array("yahoo finance","0","","",""),
array("yahoo.com mail","0","","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yeah yeah yeahs","1","","",""),
array("yoga dvd","1","","",""),
array("your baby can read","1","","",""),
array("yes man","1","","",""),
array("yanni","1","","",""),
array("yo gabba gabba","1","","",""),
array("yarn","1","","",""),
array("yeah yeah yeahs it's blitz","1","","",""),
array("youtube video","2","","",""),
array("yamaha","2","","",""),
array("ymca","2","","",""),
array("yahoo.com","3","","",""),
array("youtube.com","3","","",""),
array("you tube","3","","",""),
array("yellowpages.com","3","","",""),
array("youtube videos","3","","",""),
array("you tube.com","3","","",""),
array("yes we can","4","","",""),
array("yıldız tilbe","4","","",""),
array("your guardian angel","4","","",""),
array("yaprak dökümü","4","","",""),
array("young jeezy","4","","",""),
array("yelle","4","","",""),
array("yahh","4","","",""),
array("you","4","","",""),
array("yael naim","4","","","")),
"z" => array(
array("zip codes","0","2","3",""),
array("zales","0","2","3",""),
array("zac efron","2","3","4",""),
array("zillow","0","2","",""),
array("zappos","0","2","",""),
array("zune","0","1","",""),
array("zodiac signs","0","3","",""),
array("zelda","1","4","",""),
array("zip code finder","2","3","",""),
array("zip codes by city","0","","",""),
array("zumiez","0","","",""),
array("zabasearch","0","","",""),
array("zero punctuation","0","","",""),
array("zumba","1","","",""),
array("zippo","1","","",""),
array("zune 120","1","","",""),
array("zack and miri","1","","",""),
array("zune accessories","1","","",""),
array("zippo lighter","1","","",""),
array("zen","1","","",""),
array("zenith dtt901","1","","",""),
array("zaba search","2","","",""),
array("zuma","2","","",""),
array("zip code lookup","2","","",""),
array("zedge","2","","",""),
array("zipcodes","3","","",""),
array("zip code directory","3","","",""),
array("zillatube","3","","",""),
array("zip codes listings","3","","",""),
array("zodiac signs meanings","3","","",""),
array("zednik","4","","",""),
array("zidane","4","","",""),
array("zombie","4","","",""),
array("zoey 101","4","","",""),
array("zion","4","","",""),
array("zz top","4","","",""),
array("zara","4","","",""),
array("zeitgeist","4","","","")));
?>