<?php $topResults = array(
"a" => array(
array("american idol","0","2","4",""),
array("amazon","0","2","",""),
array("aol","0","2","",""),
array("american airlines","0","2","",""),
array("autotrader","0","2","",""),
array("american express","0","2","",""),
array("apple","0","1","",""),
array("ask.com","0","","",""),
array("addicting games","0","","",""),
array("abc","0","","",""),
array("adidas","1","","",""),
array("airsoft guns","1","","",""),
array("arkham asylum","1","","",""),
array("adventureland","1","","",""),
array("alarm clock","1","","",""),
array("aion","1","","",""),
array("acer aspire one","1","","",""),
array("audio books","1","","",""),
array("airsoft","1","","",""),
array("ask jeeves","2","","",""),
array("argos","2","","",""),
array("angelina jolie","2","","",""),
array("at&t","2","","",""),
array("att","3","","",""),
array("açaí berry","3","","",""),
array("aaa","3","","",""),
array("att.com","3","","",""),
array("airline tickets","3","","",""),
array("avg","3","","",""),
array("att wireless","3","","",""),
array("area codes","3","","",""),
array("alltel","3","","",""),
array("am i pregnant","3","","",""),
array("akon","4","","",""),
array("adam lambert","4","","",""),
array("akon beautiful","4","","",""),
array("avril lavigne","4","","",""),
array("american idol 2009","4","","",""),
array("aventura","4","","",""),
array("adam lambert american idol","4","","",""),
array("akon right now na na na","4","","",""),
array("arcangel","4","","","")),
"b" => array(
array("best buy","0","2","3",""),
array("bank of america","0","2","3",""),
array("barnes and noble","0","2","3",""),
array("baby names","0","2","3",""),
array("babies r us","0","2","3",""),
array("bed bath and beyond","0","2","",""),
array("blockbuster","0","2","",""),
array("britney spears","2","4","",""),
array("borders","0","","",""),
array("bank of america online banking","0","","",""),
array("babelfish","0","","",""),
array("batman arkham asylum","1","","",""),
array("blackberry","1","","",""),
array("blackberry curve","1","","",""),
array("blackberry unlocked","1","","",""),
array("backpack","1","","",""),
array("blu ray","1","","",""),
array("batman","1","","",""),
array("beatles","1","","",""),
array("bluetooth headset","1","","",""),
array("blackberry bold","1","","",""),
array("bbc","2","","",""),
array("bebo","2","","",""),
array("barack obama","3","","",""),
array("baby shower games","3","","",""),
array("books","3","","",""),
array("bmi","3","","",""),
array("breast cancer","3","","",""),
array("beyonce","4","","",""),
array("britains got talent","4","","",""),
array("britains got talent 2009","4","","",""),
array("boom boom pow","4","","",""),
array("beyonce halo","4","","",""),
array("black eyed peas","4","","",""),
array("bob marley","4","","",""),
array("beyonce single ladies","4","","",""),
array("beautiful","4","","","")),
"c" => array(
array("craigslist","0","2","",""),
array("cnn","0","2","",""),
array("circuit city","0","2","",""),
array("costco","0","2","",""),
array("capital one","0","2","",""),
array("comcast","0","2","",""),
array("continental airlines","0","","",""),
array("comcast.net","0","","",""),
array("chase","0","","",""),
array("club penguin","0","","",""),
array("cell phones","1","","",""),
array("canon powershot","1","","",""),
array("crocs","1","","",""),
array("coffee maker","1","","",""),
array("camera","1","","",""),
array("charlaine harris","1","","",""),
array("canon","1","","",""),
array("coraline","1","","",""),
array("converse","1","","",""),
array("call of duty modern warfare 2","1","","",""),
array("cingular","2","","",""),
array("chat","2","","",""),
array("cartoon network","2","","",""),
array("currency converter","2","","",""),
array("cheap flights","3","","",""),
array("cars","3","","",""),
array("coupons","3","","",""),
array("car rentals","3","","",""),
array("cheap airline tickets","3","","",""),
array("cheap hotels","3","","",""),
array("clip art","3","","",""),
array("checks","3","","",""),
array("cheat codes","3","","",""),
array("cars.com","3","","",""),
array("chris brown","4","","",""),
array("ciara","4","","",""),
array("charlie bit my finger","4","","",""),
array("crack a bottle","4","","",""),
array("coldplay","4","","",""),
array("christina aguilera","4","","",""),
array("crazy frog","4","","",""),
array("celine dion","4","","",""),
array("charlie the unicorn","4","","",""),
array("carrie underwood","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("dell","0","2","3",""),
array("disney channel","0","2","",""),
array("dancing with the stars","0","2","",""),
array("driving directions","2","3","",""),
array("directions","2","3","",""),
array("dish network","2","3","",""),
array("dmv","2","3","",""),
array("dictionary.com","0","","",""),
array("dillards","0","","",""),
array("delta","0","","",""),
array("davids bridal","0","","",""),
array("disney","0","","",""),
array("dominos","0","","",""),
array("digital camera","1","","",""),
array("dexter","1","","",""),
array("dvd player","1","","",""),
array("dvd","1","","",""),
array("dsi","1","","",""),
array("dexter season 3","1","","",""),
array("dan brown","1","","",""),
array("ds games","1","","",""),
array("ds","1","","",""),
array("dehumidifier","1","","",""),
array("delta airlines","2","","",""),
array("dhl","2","","",""),
array("dogs","3","","",""),
array("direct tv","3","","",""),
array("dresses","3","","",""),
array("diabetes","3","","",""),
array("dead and gone","4","","",""),
array("day and night","4","","",""),
array("demi lovato","4","","",""),
array("don't trust me","4","","",""),
array("disturbia","4","","",""),
array("dance","4","","",""),
array("dragon ball z","4","","",""),
array("disturbed","4","","",""),
array("don omar","4","","",""),
array("day and night kid cudi","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("ed hardy","0","1","3",""),
array("eminem","1","2","4",""),
array("espn","0","2","",""),
array("ebay motors","0","2","",""),
array("ecards","2","3","",""),
array("easter 2009","0","","",""),
array("english to spanish translation","0","","",""),
array("edible arrangements","0","","",""),
array("express","0","","",""),
array("enterprise","0","","",""),
array("external hard drive","1","","",""),
array("entourage","1","","",""),
array("eat this not that","1","","",""),
array("external hard drive 1tb","1","","",""),
array("earbuds","1","","",""),
array("earphones","1","","",""),
array("electric guitar","1","","",""),
array("eclipse","1","","",""),
array("enterprise car rental","2","","",""),
array("easyjet","2","","",""),
array("eva longoria","2","","",""),
array("evan rachel wood","2","","",""),
array("ebay.com","3","","",""),
array("eharmony","3","","",""),
array("expedia.com","3","","",""),
array("eharmony.com","3","","",""),
array("earth day 2009","3","","",""),
array("engagement rings","3","","",""),
array("enrique iglesias","4","","",""),
array("eminem we made you","4","","",""),
array("evanescence","4","","",""),
array("eminem crack a bottle","4","","",""),
array("evolution of dance","4","","",""),
array("eye of the tiger","4","","",""),
array("elvis presley","4","","",""),
array("eminem lose yourself","4","","",""),
array("elton john","4","","","")),
"f" => array(
array("free online games","0","2","3",""),
array("facebook","0","2","",""),
array("facebook login","0","2","",""),
array("fafsa","0","2","",""),
array("fox news","0","2","",""),
array("food network","0","2","",""),
array("fedex","0","2","",""),
array("family guy","1","4","",""),
array("free music downloads","2","3","",""),
array("firefox","0","","",""),
array("fandango","0","","",""),
array("forever 21","0","","",""),
array("flash drive","1","","",""),
array("fallout 3","1","","",""),
array("food processor","1","","",""),
array("final fantasy","1","","",""),
array("fan","1","","",""),
array("fleshlight","1","","",""),
array("friends","1","","",""),
array("flip video","1","","",""),
array("futon","1","","",""),
array("ford","2","","",""),
array("fantasy football","2","","",""),
array("free ringtones","3","","",""),
array("free games","3","","",""),
array("flowers","3","","",""),
array("find people","3","","",""),
array("free ecards","3","","",""),
array("free people search","3","","",""),
array("free samples","3","","",""),
array("free credit report","3","","",""),
array("fred","4","","",""),
array("funny","4","","",""),
array("flo rida","4","","",""),
array("funny video","4","","",""),
array("florida right round","4","","",""),
array("funny cats","4","","",""),
array("fast and furious 4","4","","",""),
array("funny accidents","4","","",""),
array("fights","4","","","")),
"g" => array(
array("games","0","2","3",""),
array("gmail","0","2","",""),
array("google maps","0","2","",""),
array("google earth","0","2","",""),
array("gossip girl","0","1","",""),
array("guitar","1","4","",""),
array("google","2","4","",""),
array("gap","2","3","",""),
array("gmail.com","0","","",""),
array("google.com","0","","",""),
array("gamestop","0","","",""),
array("geico","0","","",""),
array("google translate","0","","",""),
array("gps","1","","",""),
array("garmin","1","","",""),
array("garmin gps","1","","",""),
array("guitar hero 5","1","","",""),
array("garmin nuvi","1","","",""),
array("guitar hero","1","","",""),
array("gossip girl season 2","1","","",""),
array("gps garmin","1","","",""),
array("google search","2","","",""),
array("google homepage","2","","",""),
array("greeting cards","2","","",""),
array("glenn beck controversy","2","","",""),
array("global warming","3","","",""),
array("gnc","3","","",""),
array("gout","3","","",""),
array("gucci","3","","",""),
array("gay","3","","",""),
array("genital warts","3","","",""),
array("game","3","","",""),
array("grocery coupons","3","","",""),
array("green day","4","","",""),
array("gummy bear song","4","","",""),
array("ghost","4","","",""),
array("guns n roses","4","","",""),
array("girlfriend","4","","",""),
array("ghost caught on tape","4","","",""),
array("gummy bear","4","","",""),
array("gives you hell music video","4","","","")),
"h" => array(
array("home depot","0","2","3",""),
array("honda","0","2","3",""),
array("hotmail","0","2","",""),
array("house","0","1","",""),
array("harry potter","1","2","",""),
array("hannah montana","1","4","",""),
array("halloween costumes","2","3","",""),
array("hulu","0","","",""),
array("hollister","0","","",""),
array("hp","0","","",""),
array("horoscope","0","","",""),
array("hgtv","0","","",""),
array("hobby lobby","0","","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("house season 5","1","","",""),
array("hannah montana the movie","1","","",""),
array("halo 3","1","","",""),
array("harry potter and the half blood prince","1","","",""),
array("hello kitty","1","","",""),
array("horoscopes","2","","",""),
array("hi5","2","","",""),
array("holiday inn","2","","",""),
array("hsbc","2","","",""),
array("historyiframev","2","","",""),
array("how much should i weigh","3","","",""),
array("hotels","3","","",""),
array("herpes","3","","",""),
array("hotels.com","3","","",""),
array("hpv","3","","",""),
array("how to kiss","3","","",""),
array("how to write a resume","3","","",""),
array("halo","4","","",""),
array("halo beyonce","4","","",""),
array("hoedown throwdown","4","","",""),
array("hot n cold","4","","",""),
array("happy tree friends","4","","",""),
array("high school musical 3","4","","",""),
array("heartless","4","","",""),
array("high school musical","4","","",""),
array("hollywood","4","","","")),
"i" => array(
array("iphone","0","1","2","3"),
array("itunes","0","2","3",""),
array("ipod","1","2","3",""),
array("irs","0","2","",""),
array("imdb","0","2","",""),
array("ikea","0","2","",""),
array("images","0","3","",""),
array("imeem","0","2","",""),
array("ipod touch","1","3","",""),
array("internet explorer","2","3","",""),
array("inauguration day 2009","0","","",""),
array("irs forms","0","","",""),
array("ikea usa","0","","",""),
array("iphone 3gs","1","","",""),
array("ipod nano","1","","",""),
array("iphone 3g","1","","",""),
array("iphone 3g unlocked","1","","",""),
array("ipod shuffle","1","","",""),
array("itouch","1","","",""),
array("iphone case","1","","",""),
array("ign","2","","",""),
array("internal revenue service","2","","",""),
array("iq test","3","","",""),
array("italy","3","","",""),
array("iq tests","3","","",""),
array("ireland","3","","",""),
array("im on a boat","4","","",""),
array("i love college","4","","",""),
array("im yours","4","","",""),
array("if i were a boy","4","","",""),
array("infinity","4","","",""),
array("iron maiden","4","","",""),
array("i love college asher roth","4","","",""),
array("if u seek amy","4","","",""),
array("i dreamed a dream","4","","",""),
array("i kissed a girl- kate perry","4","","","")),
"j" => array(
array("jokes","0","2","3",""),
array("jobs","0","2","3",""),
array("java","0","2","3",""),
array("jcpenney","0","2","",""),
array("jet blue","0","3","",""),
array("jason mraz","1","4","",""),
array("jonas brothers","1","4","",""),
array("jennifer lopez","2","4","",""),
array("john travolta","0","","",""),
array("joann fabrics","0","","",""),
array("joaquin phoenix","0","","",""),
array("jon and kate plus 8","0","","",""),
array("jett travolta","0","","",""),
array("julia child","1","","",""),
array("julia child mastering the art of french cooking","1","","",""),
array("jansport backpack","1","","",""),
array("julie and julia","1","","",""),
array("jillian michaels","1","","",""),
array("james patterson","1","","",""),
array("juicer","1","","",""),
array("juicy couture","1","","",""),
array("jessica simpson","2","","",""),
array("jessica alba","2","","",""),
array("jasmine fiore","2","","",""),
array("jennifer aniston","2","","",""),
array("joan cusack","2","","",""),
array("job search","3","","",""),
array("jordans","3","","",""),
array("jc penney","3","","",""),
array("jc penny","3","","",""),
array("jeep","3","","",""),
array("john mccain","3","","",""),
array("jai ho","4","","",""),
array("just dance","4","","",""),
array("justin timberlake","4","","",""),
array("jeff dunham","4","","",""),
array("jesse mccartney","4","","",""),
array("just dance lady gaga","4","","",""),
array("jason mraz im yours","4","","","")),
"k" => array(
array("kmart","0","2","3",""),
array("kohls","0","3","",""),
array("kelly blue book","0","3","",""),
array("kayak","0","3","",""),
array("kim kardashian","0","2","",""),
array("kings of leon","1","4","",""),
array("kid cudi","1","4","",""),
array("kelly clarkson","2","4","",""),
array("kbb","2","3","",""),
array("kay jewelers","0","","",""),
array("kroger","0","","",""),
array("kinkos","0","","",""),
array("kawasaki disease","0","","",""),
array("kaiser permanente","0","","",""),
array("kindle","1","","",""),
array("kindle 2","1","","",""),
array("kindle dx","1","","",""),
array("keyboard","1","","",""),
array("kingdom hearts","1","","",""),
array("keurig","1","","",""),
array("kindle books","1","","",""),
array("knife","1","","",""),
array("kelley blue book","2","","",""),
array("kohl's","2","","",""),
array("kazaa","2","","",""),
array("keira knightley","2","","",""),
array("katie holmes","2","","",""),
array("kfc","2","","",""),
array("kijiji","3","","",""),
array("kohls.com","3","","",""),
array("kayak.com","3","","",""),
array("kia","3","","",""),
array("kmart.com","3","","",""),
array("kiss me thru the phone","4","","",""),
array("kanye west","4","","",""),
array("katy perry","4","","",""),
array("kiss me through the phone","4","","",""),
array("kiss","4","","",""),
array("keri hilson","4","","",""),
array("knock you down","4","","","")),
"l" => array(
array("lyrics","0","2","3",""),
array("limewire","0","2","3",""),
array("lost","0","1","2",""),
array("lady gaga","0","1","4",""),
array("love poems","0","2","3",""),
array("lowes","0","3","",""),
array("love quotes","0","2","",""),
array("las vegas","2","3","",""),
array("lil wayne","3","4","",""),
array("love","3","4","",""),
array("linkedin","0","","",""),
array("lands end","0","","",""),
array("lyrics.com","0","","",""),
array("laptop","1","","",""),
array("laptop computer","1","","",""),
array("lego","1","","",""),
array("lego star wars","1","","",""),
array("luggage","1","","",""),
array("lcd tv","1","","",""),
array("laptop bag","1","","",""),
array("lost season 5","1","","",""),
array("lindsay lohan","2","","",""),
array("lowe's","2","","",""),
array("launch","2","","",""),
array("lottery","2","","",""),
array("lingerie","3","","",""),
array("loans","3","","",""),
array("lyrics to songs","3","","",""),
array("love story","4","","",""),
array("lady gaga poker face","4","","",""),
array("linkin park","4","","",""),
array("lady gaga just dance","4","","",""),
array("love story taylor swift","4","","",""),
array("let it rock","4","","",""),
array("like a boss","4","","","")),
"m" => array(
array("maps","0","2","3",""),
array("music","2","3","4",""),
array("myspace","0","2","",""),
array("mapquest","0","2","",""),
array("msn","0","2","",""),
array("myspace layouts","0","3","",""),
array("miniclip","0","2","",""),
array("michael jackson","1","4","",""),
array("movies","2","3","",""),
array("macys","0","","",""),
array("mapquest driving directions","0","","",""),
array("mortgage calculator","0","","",""),
array("msnbc","0","","",""),
array("mp3 player","1","","",""),
array("macbook","1","","",""),
array("madden 10","1","","",""),
array("mouse","1","","",""),
array("mastering the art of french cooking","1","","",""),
array("macbook pro","1","","",""),
array("mad men","1","","",""),
array("mp3","1","","",""),
array("micro sd","1","","",""),
array("miss universe 2009","2","","",""),
array("mail","2","","",""),
array("macy's","2","","",""),
array("myspace.com","3","","",""),
array("match.com","3","","",""),
array("math","3","","",""),
array("music videos","3","","",""),
array("macy","3","","",""),
array("map","3","","",""),
array("miley cyrus","4","","",""),
array("metallica","4","","",""),
array("mariah carey","4","","",""),
array("madonna","4","","",""),
array("mad","4","","",""),
array("metro station shake it","4","","",""),
array("miley cyrus the climb","4","","",""),
array("mad world","4","","","")),
"n" => array(
array("netflix","0","2","3",""),
array("nordstrom","0","2","3",""),
array("news","0","2","3",""),
array("northwest airlines","0","2","",""),
array("nfl","0","2","",""),
array("new moon","1","4","",""),
array("nike","1","3","",""),
array("nascar","2","3","",""),
array("nissan","2","3","",""),
array("naruto","2","4","",""),
array("nbc","0","","",""),
array("natasha richardson","0","","",""),
array("new york times","0","","",""),
array("nickelodeon","0","","",""),
array("npr","0","","",""),
array("nintendo ds","1","","",""),
array("netbook","1","","",""),
array("nintendo dsi","1","","",""),
array("nikon d90","1","","",""),
array("nokia n97","1","","",""),
array("nintendo wii","1","","",""),
array("nintendo ds games","1","","",""),
array("netbook computers","1","","",""),
array("nokia","2","","",""),
array("nba","2","","",""),
array("name meanings","3","","",""),
array("names","3","","",""),
array("nada","3","","",""),
array("new york","3","","",""),
array("nickelback","4","","",""),
array("nigahiga","4","","",""),
array("ne-yo","4","","",""),
array("nirvana","4","","",""),
array("numa numa","4","","",""),
array("naruto shippuden","4","","",""),
array("nelly","4","","",""),
array("new moon trailer","4","","","")),
"o" => array(
array("orbitz","0","2","3",""),
array("office depot","0","2","3",""),
array("old navy","0","2","3",""),
array("office max","0","2","3",""),
array("overstock","0","2","3",""),
array("obama","0","3","4",""),
array("online games","0","2","3",""),
array("oprah","0","2","",""),
array("olive garden","0","2","",""),
array("one tree hill","1","4","",""),
array("online dictionary","2","3","",""),
array("oscars","0","","",""),
array("one tree hill season 6","1","","",""),
array("oakley","1","","",""),
array("outliers","1","","",""),
array("organic chemistry","1","","",""),
array("oakley sunglasses","1","","",""),
array("ooma","1","","",""),
array("office 2007","1","","",""),
array("owl city","1","","",""),
array("oakley sunglasses for men","1","","",""),
array("orkut","2","","",""),
array("overstock.com","3","","",""),
array("orbitz.com","3","","",""),
array("on a boat","4","","",""),
array("oasis","4","","",""),
array("obama song","4","","",""),
array("one","4","","",""),
array("old greg","4","","",""),
array("our song","4","","",""),
array("offspring","4","","",""),
array("ozzy osbourne","4","","","")),
"p" => array(
array("pizza hut","0","2","3",""),
array("paypal","0","2","3",""),
array("priceline","0","2","3",""),
array("photobucket","0","2","",""),
array("prom dresses","0","3","",""),
array("pottery barn","0","2","",""),
array("people search","2","3","",""),
array("poems","2","3","",""),
array("pregnancy","2","3","",""),
array("pandora","0","","",""),
array("papa johns","0","","",""),
array("poptropica","0","","",""),
array("pirate bay","0","","",""),
array("ps3","1","","",""),
array("ps3 slim","1","","",""),
array("playstation 3","1","","",""),
array("psp","1","","",""),
array("p90x","1","","",""),
array("ps3 games","1","","",""),
array("ps3 console","1","","",""),
array("posters","1","","",""),
array("portable dvd player","1","","",""),
array("playstation 3 console","1","","",""),
array("pogo","2","","",""),
array("powerball","2","","",""),
array("people finder","3","","",""),
array("proxy","3","","",""),
array("priceline.com","3","","",""),
array("poker face","4","","",""),
array("pink","4","","",""),
array("poker face lady gaga","4","","",""),
array("paramore","4","","",""),
array("paul potts","4","","",""),
array("prom queen","4","","",""),
array("pitbull","4","","",""),
array("pokemon","4","","",""),
array("pink floyd","4","","",""),
array("pink sober","4","","","")),
"q" => array(
array("quotes","0","2","3",""),
array("qvc","0","2","3",""),
array("quicktime","0","2","3",""),
array("quizzes","0","2","3",""),
array("qwest","0","2","3",""),
array("quiznos","0","2","",""),
array("quest diagnostics","0","2","",""),
array("quicken","0","1","",""),
array("quizilla","0","2","",""),
array("queen","1","4","",""),
array("quickbooks","1","3","",""),
array("quantum of solace","1","4","",""),
array("queens of the stone age","1","4","",""),
array("quotes about life","0","","",""),
array("quiksilver","1","","",""),
array("quickbooks pro 2009","1","","",""),
array("queer as folk","1","","",""),
array("queen latifah","1","","",""),
array("quilt","1","","",""),
array("qantas","2","","",""),
array("query string","2","","",""),
array("questions","3","","",""),
array("quest","3","","",""),
array("quit smoking","3","","",""),
array("quiz","3","","",""),
array("que tengo que hacer","4","","",""),
array("quest crew","4","","",""),
array("queen bohemian rhapsody","4","","",""),
array("que tengo que hacer daddy","4","","",""),
array("queen we will rock you","4","","",""),
array("queen don't stop me now","4","","",""),
array("queensryche","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("ed hardy","0","1","3",""),
array("eminem","1","2","4",""),
array("espn","0","2","",""),
array("ebay motors","0","2","",""),
array("ecards","2","3","",""),
array("easter 2009","0","","",""),
array("english to spanish translation","0","","",""),
array("edible arrangements","0","","",""),
array("express","0","","",""),
array("enterprise","0","","",""),
array("external hard drive","1","","",""),
array("entourage","1","","",""),
array("eat this not that","1","","",""),
array("external hard drive 1tb","1","","",""),
array("earbuds","1","","",""),
array("earphones","1","","",""),
array("electric guitar","1","","",""),
array("eclipse","1","","",""),
array("enterprise car rental","2","","",""),
array("easyjet","2","","",""),
array("eva longoria","2","","",""),
array("evan rachel wood","2","","",""),
array("ebay.com","3","","",""),
array("eharmony","3","","",""),
array("expedia.com","3","","",""),
array("eharmony.com","3","","",""),
array("earth day 2009","3","","",""),
array("engagement rings","3","","",""),
array("enrique iglesias","4","","",""),
array("eminem we made you","4","","",""),
array("evanescence","4","","",""),
array("eminem crack a bottle","4","","",""),
array("evolution of dance","4","","",""),
array("eye of the tiger","4","","",""),
array("elvis presley","4","","",""),
array("eminem lose yourself","4","","",""),
array("elton john","4","","","")),
"s" => array(
array("sears","0","2","3",""),
array("staples","0","2","3",""),
array("southwest airlines","0","2","",""),
array("skype","0","2","",""),
array("sprint","0","2","",""),
array("shoes","1","3","",""),
array("song lyrics","2","3","",""),
array("shakira","2","4","",""),
array("sams club","0","","",""),
array("spanish translation","0","","",""),
array("slumdog millionaire","0","","",""),
array("sparknotes","0","","",""),
array("sports authority","0","","",""),
array("snow leopard","1","","",""),
array("star trek","1","","",""),
array("star wars","1","","",""),
array("snow leopard mac os x 10.6","1","","",""),
array("sunglasses","1","","",""),
array("sims 3","1","","",""),
array("smallville season 8","1","","",""),
array("sd card","1","","",""),
array("scrubs","1","","",""),
array("sony","2","","",""),
array("sudoku","2","","",""),
array("samsung","2","","",""),
array("swine flu","3","","",""),
array("singlesnet.com","3","","",""),
array("science fair projects","3","","",""),
array("student loans","3","","",""),
array("search engines","3","","",""),
array("sears.com","3","","",""),
array("susan boyle","4","","",""),
array("soulja boy","4","","",""),
array("single ladies","4","","",""),
array("stanky leg","4","","",""),
array("slipknot","4","","",""),
array("selena gomez","4","","",""),
array("sean paul","4","","",""),
array("shake it","4","","",""),
array("smosh","4","","","")),
"t" => array(
array("twilight","0","1","3","4"),
array("travelocity","0","2","3",""),
array("target","0","2","",""),
array("ticketmaster","0","2","",""),
array("tv guide","0","2","",""),
array("turbo tax","0","3","",""),
array("toys r us","2","3","",""),
array("toyota","2","3","",""),
array("tattoos","2","3","",""),
array("travel","2","3","",""),
array("twitter","0","","",""),
array("thesaurus","0","","",""),
array("tmz","0","","",""),
array("translator","0","","",""),
array("true blood","1","","",""),
array("transformers","1","","",""),
array("tv","1","","",""),
array("the time travelers wife","1","","",""),
array("transformers revenge of the fallen","1","","",""),
array("twilight series","1","","",""),
array("time travelers wife","1","","",""),
array("the beatles","1","","",""),
array("the office","1","","",""),
array("t-mobile","2","","",""),
array("tesco","2","","",""),
array("tires","3","","",""),
array("tattoo","3","","",""),
array("tattoo designs","3","","",""),
array("taylor swift","4","","",""),
array("the climb","4","","",""),
array("taylor swift love story","4","","",""),
array("t.i","4","","",""),
array("the climb miley cyrus","4","","",""),
array("turn my swag on","4","","",""),
array("tom and jerry","4","","",""),
array("the game","4","","",""),
array("titanic","4","","","")),
"u" => array(
array("us airways","0","2","3",""),
array("ufc","1","2","4",""),
array("usps","0","2","",""),
array("ups","0","2","",""),
array("utube","0","3","",""),
array("united airlines","0","2","",""),
array("usaa","0","2","",""),
array("u2","1","4","",""),
array("umbrella","1","4","",""),
array("uggs","1","3","",""),
array("used cars","2","3","",""),
array("ups tracking","0","","",""),
array("urban dictionary","0","","",""),
array("usps tracking","0","","",""),
array("us bank","0","","",""),
array("unlocked cell phones","1","","",""),
array("usb flash drive","1","","",""),
array("up","1","","",""),
array("usb hub","1","","",""),
array("uncharted","1","","",""),
array("under armour","1","","",""),
array("utusan malaysia","2","","",""),
array("u tube","2","","",""),
array("univision","2","","",""),
array("used books","3","","",""),
array("used cars for sale","3","","",""),
array("university of phoenix","3","","",""),
array("us air","3","","",""),
array("us cellular","3","","",""),
array("universal joint","3","","",""),
array("usher","4","","",""),
array("undead hollywood","4","","",""),
array("untouched","4","","",""),
array("ufo","4","","",""),
array("unforgivable","4","","",""),
array("una","4","","",""),
array("undertaker","4","","","")),
"v" => array(
array("verizon wireless","0","2","3",""),
array("verizon","0","2","3",""),
array("victoria secret","0","3","",""),
array("vh1","0","2","",""),
array("vanguard","0","2","",""),
array("victoria's secret","1","2","",""),
array("video","2","4","",""),
array("vanessa hudgens","2","4","",""),
array("vonage","2","3","",""),
array("vlc","0","","",""),
array("value city furniture","0","","",""),
array("vrbo","0","","",""),
array("veoh","0","","",""),
array("verizon fios","0","","",""),
array("vacuum cleaner","1","","",""),
array("vera bradley","1","","",""),
array("video camera","1","","",""),
array("vampire diaries","1","","",""),
array("verizon cell phones","1","","",""),
array("vacuum","1","","",""),
array("vampire academy","1","","",""),
array("vans","1","","",""),
array("victorinox","1","","",""),
array("volkswagen","2","","",""),
array("vodafone","2","","",""),
array("vıdeos","3","","",""),
array("virgin mobile","3","","",""),
array("verizon.com","3","","",""),
array("volcanoes","3","","",""),
array("viagra","3","","",""),
array("verizonwireless.com","3","","",""),
array("viva la vida","4","","",""),
array("vicente fernandez","4","","",""),
array("videos de risa","4","","",""),
array("van halen","4","","",""),
array("vegas","4","","",""),
array("viva la vida coldplay","4","","",""),
array("videos de terror","4","","",""),
array("vampire weekend","4","","","")),
"w" => array(
array("weather","0","2","3",""),
array("white pages","0","2","3",""),
array("walgreens","0","2","3",""),
array("wikipedia","0","2","",""),
array("webkinz","0","2","",""),
array("wells fargo","0","2","",""),
array("wii","1","3","",""),
array("wii fit","1","3","",""),
array("wwe","2","4","",""),
array("weight watchers","2","3","",""),
array("walmart","0","","",""),
array("web md","0","","",""),
array("www.yahoo.com","0","","",""),
array("wachovia","0","","",""),
array("windows 7","1","","",""),
array("wii games","1","","",""),
array("wii sports resort","1","","",""),
array("watchmen","1","","",""),
array("wireless router","1","","",""),
array("watches","1","","",""),
array("wii console","1","","",""),
array("webcam","1","","",""),
array("wal mart","2","","",""),
array("webmd","2","","",""),
array("what does my name mean","3","","",""),
array("what is global warming","3","","",""),
array("wedding dresses","3","","",""),
array("what is love","3","","",""),
array("we made you","4","","",""),
array("womanizer","4","","",""),
array("wisin y yandel","4","","",""),
array("wrestlemania 25","4","","",""),
array("whatever you like","4","","",""),
array("white horse","4","","",""),
array("when i grow up","4","","",""),
array("whitney houston","4","","",""),
array("westlife","4","","","")),
"x" => array(
array("xbox 360","0","1","2","3"),
array("xbox","0","1","3","4"),
array("xbox live","0","1","2",""),
array("xm radio","0","2","3",""),
array("xvid","0","2","",""),
array("xbox 360 games","1","3","",""),
array("xbox cheats","2","3","",""),
array("xanax","2","3","",""),
array("xe","0","","",""),
array("xs cargo","0","","",""),
array("xkcd","0","","",""),
array("xplornet","0","","",""),
array("xfire","0","","",""),
array("xbox 360 console","1","","",""),
array("xbox 360 elite","1","","",""),
array("xbox 360 controller","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("xbox 360 wireless adapter","1","","",""),
array("xbox live points","1","","",""),
array("xhamster movies","2","","",""),
array("xbox games","2","","",""),
array("xerox","2","","",""),
array("xenical","2","","",""),
array("xbox 360 cheats","3","","",""),
array("xyzal","3","","",""),
array("xbox360","3","","",""),
array("xango","3","","",""),
array("x factor","4","","",""),
array("xzibit","4","","",""),
array("x men origins wolverine trailer","4","","",""),
array("x factor 2009","4","","",""),
array("x factor 2008","4","","",""),
array("x men","4","","",""),
array("xatzigiannis","4","","",""),
array("x men origins","4","","","")),
"y" => array(
array("youtube","0","2","4",""),
array("yahoo mail","0","2","3",""),
array("yellow pages","0","2","3",""),
array("yahoo","0","2","",""),
array("yahoo maps","0","2","",""),
array("yahoo messenger","0","2","",""),
array("yeah yeah yeahs","1","4","",""),
array("yahoo answers","0","","",""),
array("yahoo.com mail","0","","",""),
array("yahoo finance","0","","",""),
array("ymca","0","","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yoga dvd","1","","",""),
array("yugioh cards","1","","",""),
array("your baby can read","1","","",""),
array("yo gabba gabba","1","","",""),
array("yugioh","1","","",""),
array("yarn","1","","",""),
array("yogurt maker","1","","",""),
array("yahoo search","2","","",""),
array("youtube video","2","","",""),
array("yamaha","2","","",""),
array("yahoo games","2","","",""),
array("yellowpages.com","3","","",""),
array("yellow pages.com","3","","",""),
array("yellow book","3","","",""),
array("yellowbook.com","3","","",""),
array("yeast infection","3","","",""),
array("yellowbook","3","","",""),
array("yaz","3","","",""),
array("yahoo.com","3","","",""),
array("young jeezy","4","","",""),
array("you found me","4","","",""),
array("you spin me right round","4","","",""),
array("yusuf güney","4","","",""),
array("you spin my head right round","4","","",""),
array("you found me the fray","4","","",""),
array("you can get it all","4","","",""),
array("your a jerk","4","","","")),
"z" => array(
array("zune","0","1","2","3"),
array("zip codes","0","2","3",""),
array("zappos","0","2","3",""),
array("zodiac signs","0","2","3",""),
array("zales","0","2","3",""),
array("zillow","0","2","",""),
array("zumba","1","4","",""),
array("zelda","1","4","",""),
array("zombie","1","4","",""),
array("zac efron","2","4","",""),
array("zuma","2","3","",""),
array("zip codes by city","0","","",""),
array("zabasearch","0","","",""),
array("zillow.com search","0","","",""),
array("zero punctuation","0","","",""),
array("zune hd","1","","",""),
array("zhu zhu pets","1","","",""),
array("zippo","1","","",""),
array("zippo lighter","1","","",""),
array("zeitoun","1","","",""),
array("zune accessories","1","","",""),
array("zip code lookup","2","","",""),
array("zip code finder","2","","",""),
array("zwinky","3","","",""),
array("zappos.com","3","","",""),
array("zwinky.com","3","","",""),
array("zip code","3","","",""),
array("zz top","4","","",""),
array("zeitgeist","4","","",""),
array("zidane","4","","",""),
array("zombie nation","4","","",""),
array("zoey 101","4","","",""),
array("zac brown band","4","","","")));
?>