<?php $topResults = array(
"a" => array(
array("amazon","0","2","",""),
array("aol","0","2","",""),
array("apple","0","1","",""),
array("addicting games","0","2","",""),
array("adele","1","4","",""),
array("amtrak","0","","",""),
array("airtran","0","","",""),
array("american eagle","0","","",""),
array("arundel mills mall","0","","",""),
array("american express","0","","",""),
array("aacps","0","","",""),
array("arkham city","1","","",""),
array("apple tv","1","","",""),
array("angry birds","1","","",""),
array("airsoft guns","1","","",""),
array("adidas","1","","",""),
array("amazon prime","1","","",""),
array("amazon mom","1","","",""),
array("asus transformer","1","","",""),
array("at&t","2","","",""),
array("autotrader","2","","",""),
array("american idol","2","","",""),
array("american airlines","2","","",""),
array("amanda knox","2","","",""),
array("alicia sacramone","2","","",""),
array("ali landry","2","","",""),
array("albert pujols","3","","",""),
array("airline baby ban","3","","",""),
array("albert pujols stats","3","","",""),
array("apartments for rent","3","","",""),
array("answers.com","3","","",""),
array("airline tickets","3","","",""),
array("are vampires real","3","","",""),
array("apple store","3","","",""),
array("am i pregnant quiz","3","","",""),
array("amazon.com","3","","",""),
array("adele someone like you","4","","",""),
array("adele rolling in the deep","4","","",""),
array("avril lavigne","4","","",""),
array("adele set fire to the rain","4","","",""),
array("akon","4","","",""),
array("annoying orange","4","","",""),
array("amy winehouse","4","","",""),
array("amber cole","4","","",""),
array("avenged sevenfold","4","","","")),
"b" => array(
array("bank of america","0","2","3",""),
array("best buy","0","2","3",""),
array("bed bath and beyond","0","2","3",""),
array("barnes and noble","0","2","",""),
array("britney spears","2","4","",""),
array("beyonce","2","4","",""),
array("bing","2","3","",""),
array("baltimore sun","0","","",""),
array("bge","0","","",""),
array("baltimore ravens","0","","",""),
array("baltimore grand prix","0","","",""),
array("baltimore city public schools","0","","",""),
array("baltimore county public schools","0","","",""),
array("battlefield 3","1","","",""),
array("batman arkham city","1","","",""),
array("blackberry","1","","",""),
array("beats by dre","1","","",""),
array("boots","1","","",""),
array("batman","1","","",""),
array("bose","1","","",""),
array("blackberry torch","1","","",""),
array("bluetooth headset","1","","",""),
array("backpack","1","","",""),
array("blank","2","","",""),
array("ben stiller","2","","",""),
array("bethenny frankel","2","","",""),
array("berkman","3","","",""),
array("bernard madoff","3","","",""),
array("best floor cleaners","3","","",""),
array("baby names","3","","",""),
array("bmi calculator","3","","",""),
array("baby names and meanings","3","","",""),
array("bruno mars","4","","",""),
array("beyonce best thing i never had","4","","",""),
array("bruno mars lazy song","4","","",""),
array("bodyguard songs","4","","",""),
array("black eyed peas","4","","",""),
array("baby justin bieber","4","","",""),
array("black and yellow wiz khalifa","4","","",""),
array("britney spears i wanna go","4","","","")),
"c" => array(
array("craigslist","0","2","3",""),
array("capital one","0","2","3",""),
array("cnn","0","2","",""),
array("comcast","0","2","",""),
array("costco","0","2","",""),
array("coldplay","1","4","",""),
array("casey anthony","2","3","",""),
array("christina aguilera","2","4","",""),
array("comcast.net","0","","",""),
array("carmax","0","","",""),
array("ccbc","0","","",""),
array("chick fil a","0","","",""),
array("cbs","0","","",""),
array("costumes","1","","",""),
array("captain america","1","","",""),
array("camera","1","","",""),
array("call of duty modern warfare 3","1","","",""),
array("coffee maker","1","","",""),
array("cell phone","1","","",""),
array("cars 2","1","","",""),
array("crocs","1","","",""),
array("canon","1","","",""),
array("chase","2","","",""),
array("chaz bono","2","","",""),
array("continental airlines","2","","",""),
array("chris bosh","3","","",""),
array("chris hansen","3","","",""),
array("cheap airline tickets","3","","",""),
array("calculator","3","","",""),
array("cheap flights","3","","",""),
array("calorie counter","3","","",""),
array("currency converter","3","","",""),
array("chris brown","4","","",""),
array("california king bed","4","","",""),
array("cat daddy","4","","",""),
array("chris brown look at me now","4","","",""),
array("cobra starship you make me feel","4","","",""),
array("champagne showers lmfao","4","","",""),
array("chamak challo","4","","",""),
array("charlie bit my finger","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("driving directions","0","2","3",""),
array("dead island","1","4","",""),
array("delta airlines","2","3","",""),
array("dominos","0","","",""),
array("directions","0","","",""),
array("delta","0","","",""),
array("dropbox","0","","",""),
array("disney","0","","",""),
array("dc metro","0","","",""),
array("dutch wonderland","0","","",""),
array("dsw","0","","",""),
array("dark souls","1","","",""),
array("digital camera","1","","",""),
array("diablo 3","1","","",""),
array("diapers","1","","",""),
array("droid bionic","1","","",""),
array("dvd player","1","","",""),
array("dsi","1","","",""),
array("doctor who","1","","",""),
array("dexter","1","","",""),
array("demi moore","2","","",""),
array("disney channel","2","","",""),
array("danica patrick","2","","",""),
array("dancing with the stars","2","","",""),
array("drew rosenhaus","2","","",""),
array("dish network","2","","",""),
array("dell","2","","",""),
array("daylight savings","3","","",""),
array("dia de los muertos","3","","",""),
array("dia de los muertos art","3","","",""),
array("does justin bieber have a girlfriend","3","","",""),
array("definitions.com","3","","",""),
array("dictionary online","3","","",""),
array("disneychannel.com","3","","",""),
array("drake","4","","",""),
array("dubstep","4","","",""),
array("drake headlines","4","","",""),
array("david guetta","4","","",""),
array("danza kuduro","4","","",""),
array("don omar danza kuduro","4","","",""),
array("demi lovato skyscraper","4","","",""),
array("dappy no regrets","4","","",""),
array("deadmau5","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("espn","0","2","",""),
array("evanescence","1","4","",""),
array("edline","0","","",""),
array("espn fantasy football","0","","",""),
array("espn3","0","","",""),
array("etsy","0","","",""),
array("evite","0","","",""),
array("express","0","","",""),
array("enterprise","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("electric blanket","1","","",""),
array("espresso machine","1","","",""),
array("ebooks","1","","",""),
array("electronic cigarette","1","","",""),
array("earrings","1","","",""),
array("ethernet cable","1","","",""),
array("evangeline lilly","2","","",""),
array("ellen degeneres","2","","",""),
array("evan rachel wood","2","","",""),
array("elin nordegren","2","","",""),
array("elephant butte lake","2","","",""),
array("eva longoria","2","","",""),
array("emilio estevez","2","","",""),
array("emma watson","3","","",""),
array("elizabeth taylor","3","","",""),
array("erin brady","3","","",""),
array("expedia.com","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("extreme couponing","3","","",""),
array("enterprise car rental","3","","",""),
array("eminem","4","","",""),
array("eminem space bound","4","","",""),
array("epic rap battles of history","4","","",""),
array("enrique iglesias","4","","",""),
array("epic meal time","4","","",""),
array("eminem not afraid","4","","",""),
array("eminem lose yourself","4","","",""),
array("everyday im shuffling","4","","",""),
array("eminem lighters","4","","","")),
"f" => array(
array("facebook","0","2","3","4"),
array("fox news","0","2","",""),
array("firefox","0","2","",""),
array("food network","0","2","",""),
array("fedex","0","2","",""),
array("free online games","2","3","",""),
array("forever 21","0","","",""),
array("fandango","0","","",""),
array("fox 45","0","","",""),
array("fafsa","0","","",""),
array("franklin square hospital","0","","",""),
array("fifa 12","1","","",""),
array("forza 4","1","","",""),
array("flash drive","1","","",""),
array("free kindle books","1","","",""),
array("fast five","1","","",""),
array("food processor","1","","",""),
array("flashlight","1","","",""),
array("fisher price","1","","",""),
array("futon","1","","",""),
array("floor lamp","1","","",""),
array("friendster","2","","",""),
array("fantasy football","2","","",""),
array("ford","2","","",""),
array("fantasia barrino","2","","",""),
array("free printable halloween decorations","3","","",""),
array("funny halloween jokes","3","","",""),
array("free music downloads","3","","",""),
array("free ringtones","3","","",""),
array("free games","3","","",""),
array("free credit report","3","","",""),
array("find a person","3","","",""),
array("first name meanings","3","","",""),
array("funny video","4","","",""),
array("foster the people pumped up kicks","4","","",""),
array("fly nicki minaj","4","","",""),
array("funny","4","","",""),
array("friday rebecca black","4","","",""),
array("funny pranks","4","","",""),
array("freddiew","4","","",""),
array("fred","4","","",""),
array("firework katy perry","4","","","")),
"g" => array(
array("google","0","2","3","4"),
array("google maps","0","2","3",""),
array("gmail","0","2","",""),
array("gears of war 3","1","4","",""),
array("google search","2","3","",""),
array("games","2","3","",""),
array("google translate","0","","",""),
array("google plus","0","","",""),
array("google earth","0","","",""),
array("geico","0","","",""),
array("gamestop","0","","",""),
array("giant","0","","",""),
array("greyhound","0","","",""),
array("gps","1","","",""),
array("galaxy s2","1","","",""),
array("game of thrones","1","","",""),
array("green lantern","1","","",""),
array("gift card","1","","",""),
array("garmin","1","","",""),
array("galaxy tab","1","","",""),
array("guitar","1","","",""),
array("galaxy tab 10.1","1","","",""),
array("goo","2","","",""),
array("godiva candy","2","","",""),
array("gap","2","","",""),
array("gisele bundchen","2","","",""),
array("glenn beck","2","","",""),
array("gm uaw agreement","3","","",""),
array("game 6 series","3","","",""),
array("gm uaw contract","3","","",""),
array("google.com","3","","",""),
array("google search engine","3","","",""),
array("gnc","3","","",""),
array("give me everything pitbull","4","","",""),
array("gucci gucci","4","","",""),
array("glee","4","","",""),
array("grenade bruno mars","4","","",""),
array("god gave me you","4","","",""),
array("gym class heroes stereo hearts","4","","",""),
array("good life one republic","4","","",""),
array("gummy bear song","4","","","")),
"h" => array(
array("home depot","0","2","3",""),
array("hotmail","0","2","",""),
array("hulu","0","2","",""),
array("halloween costumes","1","2","",""),
array("hershey park","0","","",""),
array("howard county library","0","","",""),
array("hhgregg","0","","",""),
array("howard community college","0","","",""),
array("hollister","0","","",""),
array("h&m","0","","",""),
array("hcpss","0","","",""),
array("headphones","1","","",""),
array("hp touchpad","1","","",""),
array("harry potter","1","","",""),
array("hdmi cable","1","","",""),
array("halloween","1","","",""),
array("hello kitty","1","","",""),
array("halloween decorations","1","","",""),
array("harry potter and the deathly hallows part 2","1","","",""),
array("humidifier","1","","",""),
array("how to tie a tie","2","","",""),
array("halle berry","2","","",""),
array("hayden panettiere","2","","",""),
array("hilary duff","2","","",""),
array("hulk hogan","2","","",""),
array("heidi montag","2","","",""),
array("hunter s thompson","3","","",""),
array("haley joel osment","3","","",""),
array("hunter s thompson quotes","3","","",""),
array("how much should i weigh","3","","",""),
array("how to kiss","3","","",""),
array("how to get pregnant","3","","",""),
array("how many calories should i eat a day","3","","",""),
array("how do you spell a word","3","","",""),
array("home depot.com","3","","",""),
array("how to love lil wayne","4","","",""),
array("how to love","4","","",""),
array("headlines drake","4","","",""),
array("happy birthday song","4","","",""),
array("honey badger","4","","",""),
array("how to love lil wayne official video","4","","",""),
array("happy tree friends","4","","",""),
array("headlines","4","","",""),
array("how to hate lil wayne","4","","",""),
array("hello","4","","","")),
"i" => array(
array("ipad","0","1","3",""),
array("iphone 5","0","4","",""),
array("ikea","0","2","",""),
array("imdb","0","2","",""),
array("itunes","0","2","",""),
array("indeed","0","2","",""),
array("irs","0","2","",""),
array("images","0","3","",""),
array("iphone 4s","1","4","",""),
array("iphone","1","2","",""),
array("ipad 3","0","","",""),
array("ing direct","0","","",""),
array("ipad 2","1","","",""),
array("iphone 4","1","","",""),
array("ipod touch","1","","",""),
array("iphone 4 case","1","","",""),
array("iphone 4s case","1","","",""),
array("ipod","1","","",""),
array("ipod nano","1","","",""),
array("internet explorer","2","","",""),
array("ios 5","2","","",""),
array("isohunt","2","","",""),
array("illinois lottery","2","","",""),
array("international criminal court","3","","",""),
array("index today","3","","",""),
array("islamist ennahda","3","","",""),
array("is the world going to end in 2012","3","","",""),
array("instant math answers free","3","","",""),
array("inspirational quotes","3","","",""),
array("is pneumonia contagious","3","","",""),
array("is bronchitis contagious","3","","",""),
array("if i die young the band perry","4","","",""),
array("im on one","4","","",""),
array("i wanna go britney spears","4","","",""),
array("i love you like a love song selena gomez","4","","",""),
array("in the dark dev","4","","",""),
array("i need a doctor","4","","",""),
array("i just had sex-akon","4","","",""),
array("im on one drake","4","","","")),
"j" => array(
array("justin bieber","1","3","4",""),
array("jcpenney","0","2","",""),
array("jobs","1","3","",""),
array("jennifer lopez","2","4","",""),
array("johns hopkins","0","","",""),
array("joann fabrics","0","","",""),
array("johns hopkins hospital","0","","",""),
array("jersey shore","0","","",""),
array("jet blue","0","","",""),
array("jcrew","0","","",""),
array("johns hopkins jobs","0","","",""),
array("jhed","0","","",""),
array("java","0","","",""),
array("just dance 3","1","","",""),
array("juicer","1","","",""),
array("jurassic park","1","","",""),
array("jewelry box","1","","",""),
array("juicy couture","1","","",""),
array("just dance 3 wii","1","","",""),
array("jacket","1","","",""),
array("jurassic park blu ray","1","","",""),
array("jennifer aniston","2","","",""),
array("julianne hough","2","","",""),
array("jean claude van damme","2","","",""),
array("jasper arkansas","2","","",""),
array("jessica simpson","2","","",""),
array("johnny depp","2","","",""),
array("janet jackson","2","","",""),
array("joseph son","2","","",""),
array("josh hamilton","3","","",""),
array("jenelle evans","3","","",""),
array("jfk turtles","3","","",""),
array("justin bieber cell number","3","","",""),
array("justin bieber phone number for real","3","","",""),
array("jcpenney.com","3","","",""),
array("jobs in my area","3","","",""),
array("justin bieber quiz","3","","",""),
array("justin bieber baby","4","","",""),
array("jennifer lopez on the floor","4","","",""),
array("jar of hearts","4","","",""),
array("justin bieber never say never","4","","",""),
array("jar of hearts christina perri","4","","",""),
array("j cole work out","4","","",""),
array("j cole","4","","",""),
array("jason derulo don't want go home","4","","","")),
"k" => array(
array("kmart","0","2","3",""),
array("kindle","0","1","3",""),
array("kohls","0","3","",""),
array("kelly clarkson","1","4","",""),
array("katy perry","2","4","",""),
array("kayak","0","","",""),
array("kings dominion","0","","",""),
array("kennedy center","0","","",""),
array("kbb","0","","",""),
array("kreayshawn","0","","",""),
array("khan academy","0","","",""),
array("kaiser permanente","0","","",""),
array("kindle fire","1","","",""),
array("keurig","1","","",""),
array("kinect","1","","",""),
array("k cups","1","","",""),
array("kindle cover","1","","",""),
array("kitchenaid mixer","1","","",""),
array("keurig coffee maker","1","","",""),
array("keyboard","1","","",""),
array("kim kardashian","2","","",""),
array("kelly ripa","2","","",""),
array("kelley blue book","2","","",""),
array("khloe kardashian","2","","",""),
array("kate gosselin","2","","",""),
array("kelly charlie's angels","2","","",""),
array("kristen stewart","2","","",""),
array("katie holmes","2","","",""),
array("kp org member sign in","3","","",""),
array("kp sign","3","","",""),
array("kansas city","3","","",""),
array("kelly blue book","3","","",""),
array("kids games","3","","",""),
array("kellybluebook.com","3","","",""),
array("kia","3","","",""),
array("katy perry last friday night t.g.i.f","4","","",""),
array("kesha","4","","",""),
array("kanye west","4","","",""),
array("kid cudi","4","","",""),
array("kreayshawn gucci gucci","4","","",""),
array("kevjumba","4","","",""),
array("katy perry firework","4","","",""),
array("katy perry et","4","","","")),
"l" => array(
array("love quotes","0","2","3",""),
array("lowes","0","3","",""),
array("louis vuitton","0","1","",""),
array("lady gaga","2","4","",""),
array("lyrics","2","3","",""),
array("linkedin","0","","",""),
array("long and foster","0","","",""),
array("living social","0","","",""),
array("letmewatchthis","0","","",""),
array("labcorp","0","","",""),
array("lands end","0","","",""),
array("lord and taylor","0","","",""),
array("laptop computer","1","","",""),
array("lion king","1","","",""),
array("luggage","1","","",""),
array("lego star wars","1","","",""),
array("legos","1","","",""),
array("laptop","1","","",""),
array("leappad","1","","",""),
array("levis","1","","",""),
array("laptop bag","1","","",""),
array("lindsay lohan","2","","",""),
array("lauren alaina","2","","",""),
array("limewire","2","","",""),
array("lebron james","2","","",""),
array("leann rimes","2","","",""),
array("lowe's home improvement","2","","",""),
array("lowes stores","2","","",""),
array("last minute halloween costumes","3","","",""),
array("last minute halloween costumes for women","3","","",""),
array("last 19th century","3","","",""),
array("lowes.com","3","","",""),
array("lyrics to songs","3","","",""),
array("love poems","3","","",""),
array("lingerie","3","","",""),
array("lil wayne","4","","",""),
array("lil wayne how to love","4","","",""),
array("lmfao party rock anthem","4","","",""),
array("lmfao","4","","",""),
array("look at me now chris brown","4","","",""),
array("lazy song bruno mars","4","","",""),
array("lighters eminem","4","","",""),
array("lighters","4","","",""),
array("lady gaga you and i","4","","","")),
"m" => array(
array("mapquest","0","2","3",""),
array("maps","0","3","",""),
array("msn","0","2","",""),
array("music","1","3","",""),
array("mva","0","","",""),
array("macys","0","","",""),
array("md lottery","0","","",""),
array("maryland state fair","0","","",""),
array("msnbc","0","","",""),
array("m&t bank","0","","",""),
array("michaels","0","","",""),
array("macbook pro","1","","",""),
array("modern warfare 3","1","","",""),
array("mw3","1","","",""),
array("macbook air","1","","",""),
array("mp3 player","1","","",""),
array("macbook","1","","",""),
array("mouse","1","","",""),
array("monster high","1","","",""),
array("motorola xoom","1","","",""),
array("myspace","2","","",""),
array("michael douglas","2","","",""),
array("minka kelly","2","","",""),
array("mail","2","","",""),
array("milla jovovich","2","","",""),
array("muhammad ali","2","","",""),
array("megan fox","2","","",""),
array("miley cyrus","2","","",""),
array("marie osmond","3","","",""),
array("matt holliday","3","","",""),
array("mel gibson","3","","",""),
array("mapquest driving directions","3","","",""),
array("math answers","3","","",""),
array("macys.com","3","","",""),
array("medical dictionary","3","","",""),
array("moves like jagger","4","","",""),
array("moves like jagger maroon 5","4","","",""),
array("michael jackson","4","","",""),
array("mayweather vs ortiz","4","","",""),
array("mayweather ortiz knockout","4","","",""),
array("mac miller","4","","",""),
array("maroon 5","4","","",""),
array("minecraft","4","","",""),
array("marry you bruno mars","4","","",""),
array("mr saxobeat","4","","","")),
"n" => array(
array("netflix","0","2","3",""),
array("nfl","0","2","",""),
array("nordstrom","0","2","",""),
array("national weather service","0","2","",""),
array("nicki minaj","2","4","",""),
array("noaa","0","","",""),
array("news","0","","",""),
array("new york times","0","","",""),
array("nick","0","","",""),
array("nbc","0","","",""),
array("national hurricane center","0","","",""),
array("nintendo 3ds","1","","",""),
array("nintendo ds","1","","",""),
array("nook","1","","",""),
array("nike","1","","",""),
array("nikon d7000","1","","",""),
array("nikon","1","","",""),
array("nikon d3100","1","","",""),
array("nba 2k12","1","","",""),
array("nokia n9","1","","",""),
array("nikon d5100","1","","",""),
array("nick jr","2","","",""),
array("nascar","2","","",""),
array("nancy shevell","2","","",""),
array("nba","2","","",""),
array("nickelodeon","2","","",""),
array("new beavis and butthead","3","","",""),
array("new beavis and butthead 2011","3","","",""),
array("net worth","3","","",""),
array("name meanings","3","","",""),
array("names and meaning","3","","",""),
array("nissan","3","","",""),
array("nickelodeon games","3","","",""),
array("naked","3","","",""),
array("nissan cars","3","","",""),
array("nicki minaj super bass","4","","",""),
array("nigahiga","4","","",""),
array("new songs 2011","4","","",""),
array("next to you chris brown ft justin bieber","4","","",""),
array("nyan cat","4","","",""),
array("no sleep wiz khalifa","4","","",""),
array("nickelback","4","","",""),
array("nirvana","4","","",""),
array("never say never","4","","","")),
"o" => array(
array("old navy","0","2","3",""),
array("office depot","0","2","",""),
array("orbitz","0","2","",""),
array("overstock","0","2","",""),
array("online dictionary","2","3","",""),
array("orioles","0","","",""),
array("oovoo","0","","",""),
array("ocean city","0","","",""),
array("omegle","0","","",""),
array("otakon","0","","",""),
array("orchard bank","0","","",""),
array("otterbox iphone 4","1","","",""),
array("otterbox iphone 4s","1","","",""),
array("otterbox","1","","",""),
array("oakley","1","","",""),
array("oakley sunglasses","1","","",""),
array("office chair","1","","",""),
array("oxyelite pro","1","","",""),
array("opi","1","","",""),
array("otterbox defender iphone 4","1","","",""),
array("otterbox defender iphone 4s","1","","",""),
array("omg","2","","",""),
array("omarosa manigault","2","","",""),
array("online banks","2","","",""),
array("oprah winfrey","2","","",""),
array("oil prices","2","","",""),
array("october 28 2011","3","","",""),
array("october 28 2011 mayan","3","","",""),
array("o' lantern patterns","3","","",""),
array("online pregnancy test","3","","",""),
array("ovulation calculator","3","","",""),
array("ovulation calendar","3","","",""),
array("online games","3","","",""),
array("online calculator","3","","",""),
array("one direction what makes you beautiful","4","","",""),
array("on the floor jennifer lopez","4","","",""),
array("otis","4","","",""),
array("one direction","4","","",""),
array("otis kanye west","4","","",""),
array("on the floor","4","","",""),
array("olly murs heart skips a beat","4","","",""),
array("one republic good life","4","","",""),
array("on my level wiz khalifa","4","","",""),
array("one republic","4","","","")),
"p" => array(
array("pandora","0","2","",""),
array("party city","0","2","",""),
array("paypal","0","2","",""),
array("pizza hut","0","2","",""),
array("people search","2","3","",""),
array("papa johns","0","","",""),
array("powerball","0","","",""),
array("pnc","0","","",""),
array("pottermore","0","","",""),
array("people","0","","",""),
array("petsmart","0","","",""),
array("ps3","1","","",""),
array("playstation 3","1","","",""),
array("psp","1","","",""),
array("ps3 controller","1","","",""),
array("posters","1","","",""),
array("pirates of the caribbean","1","","",""),
array("projector","1","","",""),
array("p90x","1","","",""),
array("pirates of the caribbean on stranger tides","1","","",""),
array("printer","1","","",""),
array("powerball results july 20,2011","2","","",""),
array("pogo","2","","",""),
array("photobucket","2","","",""),
array("paris jackson","2","","",""),
array("priceline","2","","",""),
array("project runway winner","3","","",""),
array("puss in boots","3","","",""),
array("peter schiff","3","","",""),
array("pregnancy week by week","3","","",""),
array("phone number lookup","3","","",""),
array("prom dresses","3","","",""),
array("people search for free","3","","",""),
array("people finder","3","","",""),
array("put my word in a sentence","3","","",""),
array("party rock anthem","4","","",""),
array("pumped up kicks","4","","",""),
array("pitbull","4","","",""),
array("pitbull give me everything","4","","",""),
array("pumped up kicks foster the people","4","","",""),
array("party rock anthem lmfao","4","","",""),
array("price tag","4","","",""),
array("pitbull rain over me","4","","",""),
array("party rock","4","","",""),
array("pink","4","","","")),
"q" => array(
array("qvc","0","2","3",""),
array("quotes","0","2","3",""),
array("quest diagnostics","0","2","",""),
array("quotes about life","0","3","",""),
array("quiznos","0","2","",""),
array("quicktime","0","2","",""),
array("queen","1","4","",""),
array("queenstown outlets","0","","",""),
array("qwop","0","","",""),
array("qdoba","0","","",""),
array("quadratic formula","0","","",""),
array("quicken 2012","1","","",""),
array("quickbooks","1","","",""),
array("quicken","1","","",""),
array("quiksilver","1","","",""),
array("quilt","1","","",""),
array("queen of hearts costume","1","","",""),
array("queen mattress","1","","",""),
array("queen bed frame","1","","",""),
array("quinoa","1","","",""),
array("queen latifah","2","","",""),
array("qwest","2","","",""),
array("query string","2","","",""),
array("quadruple rainbow","2","","",""),
array("quality inn","2","","",""),
array("queen elizabeth ii","3","","",""),
array("queen anne","3","","",""),
array("quebec city","3","","",""),
array("quotes of the day","3","","",""),
array("quizzes","3","","",""),
array("quotes and sayings","3","","",""),
array("quick mileage city to city","3","","",""),
array("quickie miguel","4","","",""),
array("queen bohemian rhapsody","4","","",""),
array("queen don't stop me now","4","","",""),
array("quest crew","4","","",""),
array("queen somebody to love","4","","",""),
array("queen we will rock you","4","","",""),
array("quickie","4","","",""),
array("quickie miguel with lyrics","4","","",""),
array("queens of the stone age","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("espn","0","2","",""),
array("evanescence","1","4","",""),
array("edline","0","","",""),
array("espn fantasy football","0","","",""),
array("espn3","0","","",""),
array("etsy","0","","",""),
array("evite","0","","",""),
array("express","0","","",""),
array("enterprise","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("electric blanket","1","","",""),
array("espresso machine","1","","",""),
array("ebooks","1","","",""),
array("electronic cigarette","1","","",""),
array("earrings","1","","",""),
array("ethernet cable","1","","",""),
array("evangeline lilly","2","","",""),
array("ellen degeneres","2","","",""),
array("evan rachel wood","2","","",""),
array("elin nordegren","2","","",""),
array("elephant butte lake","2","","",""),
array("eva longoria","2","","",""),
array("emilio estevez","2","","",""),
array("emma watson","3","","",""),
array("elizabeth taylor","3","","",""),
array("erin brady","3","","",""),
array("expedia.com","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("extreme couponing","3","","",""),
array("enterprise car rental","3","","",""),
array("eminem","4","","",""),
array("eminem space bound","4","","",""),
array("epic rap battles of history","4","","",""),
array("enrique iglesias","4","","",""),
array("epic meal time","4","","",""),
array("eminem not afraid","4","","",""),
array("eminem lose yourself","4","","",""),
array("everyday im shuffling","4","","",""),
array("eminem lighters","4","","","")),
"s" => array(
array("sears","0","2","3",""),
array("sprint","0","2","",""),
array("staples","0","2","",""),
array("skype","0","2","",""),
array("southwest airlines","2","3","",""),
array("southwest","0","","",""),
array("safeway","0","","",""),
array("sams club","0","","",""),
array("spotify","0","","",""),
array("stevenson university","0","","",""),
array("suntrust","0","","",""),
array("steve jobs","1","","",""),
array("samsung galaxy s2","1","","",""),
array("skyrim","1","","",""),
array("star wars","1","","",""),
array("search amazon.com","1","","",""),
array("samsung galaxy tab 10.1","1","","",""),
array("steve jobs biography","1","","",""),
array("sunglasses","1","","",""),
array("samsung galaxy tab","1","","",""),
array("samsung galaxy","1","","",""),
array("scarlett johansson","2","","",""),
array("sandra bullock","2","","",""),
array("salon meritage","2","","",""),
array("sarah palin","2","","",""),
array("search","2","","",""),
array("st louis cardinals","3","","",""),
array("statue of liberty","3","","",""),
array("st.louis cardinals","3","","",""),
array("scary maze game","3","","",""),
array("sears.com","3","","",""),
array("spanish dictionary","3","","",""),
array("sexy","3","","",""),
array("song lyrics","3","","",""),
array("super bass nicki minaj","4","","",""),
array("someone like you adele","4","","",""),
array("stereo hearts gym class heroes","4","","",""),
array("selena gomez","4","","",""),
array("super bass","4","","",""),
array("selena gomez love you like a love song","4","","",""),
array("skrillex","4","","",""),
array("smosh","4","","",""),
array("shakira","4","","",""),
array("she will lil wayne","4","","","")),
"t" => array(
array("target","0","2","",""),
array("twitter","0","2","",""),
array("thesaurus","0","2","",""),
array("ticketmaster","0","2","",""),
array("travelocity","0","2","",""),
array("taylor swift","2","4","",""),
array("translate","0","","",""),
array("towson university","0","","",""),
array("tumblr","0","","",""),
array("tmz","0","","",""),
array("the weather channel","0","","",""),
array("tablet","1","","",""),
array("transformers","1","","",""),
array("touchpad","1","","",""),
array("the walking dead","1","","",""),
array("toms","1","","",""),
array("the help","1","","",""),
array("thor","1","","",""),
array("thermos","1","","",""),
array("the hunger games","1","","",""),
array("tv stand","1","","",""),
array("toys r us","2","","",""),
array("tiger woods","2","","",""),
array("terrell owens","2","","",""),
array("tagged","2","","",""),
array("tebow","3","","",""),
array("texas rangers","3","","",""),
array("time change","3","","",""),
array("translate english to spanish","3","","",""),
array("tattoo designs","3","","",""),
array("translate spanish to english","3","","",""),
array("translator","3","","",""),
array("travelocity.com","3","","",""),
array("teen pregnancy signs","3","","",""),
array("tattoos","3","","",""),
array("teach me how to dougie","4","","",""),
array("teach me how to dougie official video","4","","",""),
array("tonight tonight hot chelle rae","4","","",""),
array("teri meri bodyguard","4","","",""),
array("the lazy song bruno mars","4","","",""),
array("tyler the creator","4","","",""),
array("tom and jerry","4","","",""),
array("tonight tonight","4","","",""),
array("trey songz","4","","","")),
"u" => array(
array("us airways","0","2","3",""),
array("united airlines","0","2","3",""),
array("usps","0","2","",""),
array("ups","0","2","",""),
array("usaa","0","2","",""),
array("ups tracking","0","3","",""),
array("ufc","2","4","",""),
array("used cars","2","3","",""),
array("university of maryland","0","","",""),
array("urban dictionary","0","","",""),
array("umbc","0","","",""),
array("usa jobs","0","","",""),
array("uncharted 3","1","","",""),
array("ugg","1","","",""),
array("under armour","1","","",""),
array("umbrella","1","","",""),
array("ugg boots","1","","",""),
array("unlocked cell phones","1","","",""),
array("usb flash drive","1","","",""),
array("uncharted","1","","",""),
array("usb hub","1","","",""),
array("ugg boots women","1","","",""),
array("upcoming","2","","",""),
array("unemployment benefits","2","","",""),
array("univision","2","","",""),
array("united kingdom","3","","",""),
array("us embassy","3","","",""),
array("us born century","3","","",""),
array("used cars for sale in my area","3","","",""),
array("used cars for sale","3","","",""),
array("unique baby names","3","","",""),
array("usher","4","","",""),
array("up up and away lil wayne","4","","",""),
array("usher dj got us falling in love","4","","",""),
array("u2","4","","",""),
array("ufo","4","","",""),
array("ultimate dog teaser","4","","",""),
array("usher more","4","","",""),
array("usher yeah","4","","",""),
array("uberhaxornova","4","","","")),
"v" => array(
array("verizon wireless","0","2","3",""),
array("verizon","0","2","3",""),
array("victoria secret","0","3","",""),
array("virgin mobile","0","2","",""),
array("vera bradley","0","1","",""),
array("verizon.net","0","","",""),
array("verizon email","0","","",""),
array("value city","0","","",""),
array("verizon fios","0","","",""),
array("vlc","0","","",""),
array("vacuum cleaner","1","","",""),
array("verizon cell phones","1","","",""),
array("vans","1","","",""),
array("video camera","1","","",""),
array("vacuum","1","","",""),
array("vaporizer","1","","",""),
array("vampire diaries","1","","",""),
array("vitamix","1","","",""),
array("vibratorsfor women","1","","",""),
array("victoria's secret","2","","",""),
array("vanessa hudgens","2","","",""),
array("victoria beckham","2","","",""),
array("vh1","2","","",""),
array("video","2","","",""),
array("value city furniture","2","","",""),
array("vanguard","2","","",""),
array("vitamin d study","3","","",""),
array("vlad the impaler","3","","",""),
array("vlad the impaler coins","3","","",""),
array("verizon.com","3","","",""),
array("very early symptoms of pregnancy","3","","",""),
array("verizonwireless.com","3","","",""),
array("videos","3","","",""),
array("victorious","4","","",""),
array("vevo","4","","",""),
array("victoria justice","4","","",""),
array("vybz kartel","4","","",""),
array("video seksual 2011","4","","",""),
array("valerie amy winehouse","4","","",""),
array("video lucu","4","","",""),
array("vampire diaries season 3","4","","",""),
array("vybz kartel 2011","4","","",""),
array("viva la vida","4","","","")),
"w" => array(
array("white pages","0","2","3",""),
array("weather","0","2","",""),
array("walmart","0","2","",""),
array("wikipedia","0","2","",""),
array("wwe","2","4","",""),
array("www.facebook.com","0","","",""),
array("wbal","0","","",""),
array("wjz","0","","",""),
array("washington post","0","","",""),
array("wachovia","0","","",""),
array("www.yahoo.com","0","","",""),
array("wii","1","","",""),
array("wii games","1","","",""),
array("watch","1","","",""),
array("wireless router","1","","",""),
array("walking dead","1","","",""),
array("windows 7","1","","",""),
array("wallet","1","","",""),
array("wii console","1","","",""),
array("wireless mouse","1","","",""),
array("watches for men","1","","",""),
array("wells fargo","2","","",""),
array("webmd","2","","",""),
array("womens world cup 2011","2","","",""),
array("world's oldest car","2","","",""),
array("whitney houston","2","","",""),
array("world series","3","","",""),
array("world series winners","3","","",""),
array("weather houston","3","","",""),
array("what is justin biebers phone number","3","","",""),
array("what does my last name mean","3","","",""),
array("what is the meaning of my name","3","","",""),
array("what is love","3","","",""),
array("what does my dream mean","3","","",""),
array("where can i watch free movies online","3","","",""),
array("wiz khalifa","4","","",""),
array("without you david guetta","4","","",""),
array("waka waka shakira","4","","",""),
array("wiz khalifa on my level","4","","",""),
array("without you","4","","",""),
array("wiz khalifa no sleep","4","","",""),
array("who says selena gomez","4","","",""),
array("where dem girlz at official video","4","","",""),
array("we found love","4","","","")),
"x" => array(
array("xbox","0","1","3",""),
array("xm radio","0","2","3",""),
array("xbox live","0","1","2",""),
array("xbox 360","1","2","3",""),
array("x factor","0","4","",""),
array("xanax","0","2","",""),
array("xbox 360 games","1","3","",""),
array("xperia play","1","3","",""),
array("x factor 2011","2","4","",""),
array("xfinity","0","","",""),
array("xkcd","0","","",""),
array("xfinity tv","0","","",""),
array("xpose fitness","0","","",""),
array("xs baltimore","0","","",""),
array("xbox 360 console","1","","",""),
array("xbox 360 controller","1","","",""),
array("xoom","1","","",""),
array("xbox 360 kinect","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("x-men first class","2","","",""),
array("xvid","2","","",""),
array("xxxv full movie","2","","",""),
array("xha","2","","",""),
array("xnxsxs","2","","",""),
array("xxl movie","3","","",""),
array("xbox 360 cheats","3","","",""),
array("xxl tv live","3","","",""),
array("xm satellite radio","3","","",""),
array("xbox live 2 month free trial","3","","",""),
array("x factor 2011 uk","4","","",""),
array("x factor usa","4","","",""),
array("xjawz","4","","",""),
array("x factor usa 2011","4","","",""),
array("x factor australia 2011","4","","",""),
array("x factor auditions 2011","4","","",""),
array("xx3","4","","",""),
array("xzibit","4","","","")),
"y" => array(
array("youtube","0","2","3","4"),
array("yahoo mail","0","2","3",""),
array("yahoo","0","3","",""),
array("yellow pages","0","3","",""),
array("youtube to mp3","0","","",""),
array("yahoo fantasy football","0","","",""),
array("yahoo finance","0","","",""),
array("y8","0","","",""),
array("yahoo maps","0","","",""),
array("yelp","0","","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yarn","1","","",""),
array("yo gabba gabba","1","","",""),
array("yugioh cards","1","","",""),
array("yankee candle","1","","",""),
array("yoga dvd","1","","",""),
array("yugioh","1","","",""),
array("yoga pants","1","","",""),
array("yogurt maker","1","","",""),
array("yahoo calendar","2","","",""),
array("yahoo sports","2","","",""),
array("yahoo answers","2","","",""),
array("yahoo weather","2","","",""),
array("yahoo horoscopes","2","","",""),
array("yahoo people search","2","","",""),
array("yahoo bookmarks","2","","",""),
array("yahoo travel","2","","",""),
array("youngman lotus automobile","3","","",""),
array("yucatan peninsula","3","","",""),
array("youtube videos","3","","",""),
array("yahoo mail login","3","","",""),
array("yellowpages.com","3","","",""),
array("youtube music","3","","",""),
array("you and i lady gaga","4","","",""),
array("you make me feel cobra starship","4","","",""),
array("you and i","4","","",""),
array("yogscast","4","","",""),
array("you make me feel","4","","",""),
array("young jeezy","4","","",""),
array("yeah 3x chris brown","4","","",""),
array("yonkers","4","","",""),
array("yourfavoritemartian","4","","","")),
"z" => array(
array("zappos","0","2","3",""),
array("zip codes","0","2","3",""),
array("zodiac signs","0","2","3",""),
array("zumba","1","3","4",""),
array("zillow","0","2","",""),
array("zooey deschanel","0","2","",""),
array("zoe saldana","0","2","",""),
array("zombie","1","4","",""),
array("z104.3","0","","",""),
array("zabasearch","0","","",""),
array("zipcar","0","","",""),
array("zara","0","","",""),
array("zune","1","","",""),
array("zelda","1","","",""),
array("zippo","1","","",""),
array("zune hd","1","","",""),
array("zumba fitness dvd","1","","",""),
array("zone one","1","","",""),
array("zelda skyward sword","1","","",""),
array("zippo lighter","1","","",""),
array("zsa zsa gabor","2","","",""),
array("zales","2","","",""),
array("zuma","2","","",""),
array("zedge","2","","",""),
array("zuccotti park","3","","",""),
array("zone voa news syrian","3","","",""),
array("zhejiang youngman","3","","",""),
array("zip code finder","3","","",""),
array("zappos.com","3","","",""),
array("zip code lookup","3","","",""),
array("zaz je veux","4","","",""),
array("zac brown band","4","","",""),
array("zindagi na milegi dobara songs","4","","",""),
array("zumba dance workout","4","","",""),
array("zombie cranberries","4","","",""),
array("zombie makeup","4","","",""),
array("zaz","4","","",""),
array("zac brown band knee deep","4","","","")));
?>