<?php $topResults = array(
"a" => array(
array("amazon","0","2","3"),
array("argos","0","2",""),
array("aol","0","2",""),
array("autotrader","0","2",""),
array("apple","0","1",""),
array("asda","0","2",""),
array("ask jeeves","2","3",""),
array("at t","0","",""),
array("american airlines","0","",""),
array("avg","0","",""),
array("addicting games","0","",""),
array("acer aspire one","1","",""),
array("apple iphone","1","",""),
array("ac dc","1","",""),
array("adidas","1","",""),
array("aspire one","1","",""),
array("asus","1","",""),
array("alarm clock","1","",""),
array("airsoft","1","",""),
array("archos","1","",""),
array("amanda peet","2","",""),
array("angelina jolie","2","",""),
array("abc","2","",""),
array("american broadcasting corporation","2","",""),
array("ask jeeves a question","3","",""),
array("ask.com","3","",""),
array("area codes","3","",""),
array("area code lookup","3","",""),
array("algorithm","3","",""),
array("amazon.com","3","",""),
array("aishwarya rai","3","",""),
array("adriana lima","3","","")),
"b" => array(
array("best buy","0","2","3"),
array("bebo","0","2",""),
array("bbc","0","2",""),
array("bank of america","0","2",""),
array("britney spears","2","3",""),
array("baby names","2","3",""),
array("bernie mac","0","",""),
array("bbc news","0","",""),
array("bbc weather","0","",""),
array("big brother","0","",""),
array("bbc sport","0","",""),
array("beijing olympics","0","",""),
array("blu ray","1","",""),
array("brisingr","1","",""),
array("blackberry","1","",""),
array("bakugan","1","",""),
array("batman","1","",""),
array("breaking dawn","1","",""),
array("bose","1","",""),
array("bluetooth headset","1","",""),
array("bob dylan","1","",""),
array("boots","1","",""),
array("british broadcasting corporation","2","",""),
array("beth ostrosky","2","",""),
array("babies r us","2","",""),
array("bar refaeli","2","",""),
array("bed bath and beyond","3","",""),
array("barnes and noble","3","",""),
array("better business bureau","3","",""),
array("books","3","",""),
array("barack obama","3","",""),
array("burlington coat factory","3","",""),
array("bmi calculator","3","","")),
"c" => array(
array("craigslist","0","2","3"),
array("cnn","0","2",""),
array("costco","0","3",""),
array("currency converter","0","2",""),
array("circuit city","0","2",""),
array("club penguin","0","2",""),
array("currys","0","2",""),
array("calendar","2","3",""),
array("cuil","0","",""),
array("comcast","0","",""),
array("capital one","0","",""),
array("costumes","1","",""),
array("cell phones","1","",""),
array("canon","1","",""),
array("camera","1","",""),
array("coldplay","1","",""),
array("canon 50d","1","",""),
array("charlaine harris","1","",""),
array("call of duty 4","1","",""),
array("canon 5d","1","",""),
array("crocs","1","",""),
array("cable news network","2","",""),
array("cellular nonlinear network","2","",""),
array("cartoon network","2","",""),
array("chicks with swords","3","",""),
array("craigs list","3","",""),
array("conversion chart","3","",""),
array("calendar for the year 2008","3","",""),
array("cartoon network games","3","",""),
array("chris brown","3","",""),
array("consumer reports","3","","")),
"d" => array(
array("dictionary","0","2","3"),
array("dell","0","2",""),
array("disney","0","2",""),
array("dark knight","0","1",""),
array("delta","0","2",""),
array("driving directions","2","3",""),
array("disney channel","0","",""),
array("debenhams","0","",""),
array("dvla","0","",""),
array("dhl","0","",""),
array("dominos","0","",""),
array("dvd","1","",""),
array("digital camera","1","",""),
array("death magnetic","1","",""),
array("dexter","1","",""),
array("dvd player","1","",""),
array("d90","1","",""),
array("ds","1","",""),
array("david cook","1","",""),
array("dvd movies","1","",""),
array("directions","2","",""),
array("delta airlines","2","",""),
array("dmv","2","",""),
array("department of motor vehicles","2","",""),
array("dancing with the stars","2","",""),
array("definition","3","",""),
array("distance","3","",""),
array("dictionary online","3","",""),
array("distance between 2 cities","3","",""),
array("distance between locations","3","",""),
array("definitions","3","",""),
array("dictionary.com","3","",""),
array("dogs","3","","")),
"e" => array(
array("ebay","0","2","3"),
array("expedia","0","2","3"),
array("espn","0","2",""),
array("easyjet","0","2",""),
array("enterprise","0","2",""),
array("eminem","1","2",""),
array("ebay uk","0","",""),
array("ebuddy","0","",""),
array("exchange rates","0","",""),
array("earth","0","",""),
array("emirates","0","",""),
array("external hard drive","1","",""),
array("eragon","1","",""),
array("eclipse","1","",""),
array("entourage","1","",""),
array("eee pc","1","",""),
array("ed hardy","1","",""),
array("edgar sawtelle","1","",""),
array("eat this not that","1","",""),
array("earphones","1","",""),
array("ecards","2","",""),
array("elizabeth reaser","2","",""),
array("eddie van halen","2","",""),
array("eva longoria","2","",""),
array("early pregnancy symptoms","3","",""),
array("english dictionary","3","",""),
array("encyclopedia","3","",""),
array("english to spanish translation","3","",""),
array("earliest possible signs of pregnancy","3","",""),
array("expedia.com","3","",""),
array("eagles of death metal","3","",""),
array("enterprise car rental","3","","")),
"f" => array(
array("facebook","0","2","3"),
array("free games","0","2","3"),
array("facebook login","0","2",""),
array("fox news","0","2",""),
array("food network","0","3",""),
array("fandango","0","2",""),
array("fedex","0","2",""),
array("family guy","1","3",""),
array("firefox","0","",""),
array("friendster","0","",""),
array("flickr","0","",""),
array("fallout 3","1","",""),
array("forgetting sarah marshall","1","",""),
array("fable 2","1","",""),
array("flash drive","1","",""),
array("fifa 09","1","",""),
array("force unleashed","1","",""),
array("friends","1","",""),
array("final fantasy","1","",""),
array("futurama","1","",""),
array("fantasy football","2","",""),
array("fafsa","2","",""),
array("fergie","2","",""),
array("friends reunited","2","",""),
array("free music","3","",""),
array("free downloads","3","",""),
array("free desktop themes downloads","3","",""),
array("flowers","3","",""),
array("free puppies","3","",""),
array("free resume formats","3","","")),
"g" => array(
array("google maps","0","2","3"),
array("games","0","2","3"),
array("game","0","2","3"),
array("gmail","0","2",""),
array("google earth","0","3",""),
array("gumtree","0","2",""),
array("gamestop","0","3",""),
array("gap","0","2",""),
array("google","2","3",""),
array("greyhound","0","",""),
array("gamespot","0","",""),
array("gps","1","",""),
array("garmin","1","",""),
array("guitar hero","1","",""),
array("guitar hero world tour","1","",""),
array("gears of war 2","1","",""),
array("gossip girl","1","",""),
array("gears of war","1","",""),
array("guitar","1","",""),
array("get smart","1","",""),
array("garmin gps","1","",""),
array("google search","2","",""),
array("gwen ifill","2","",""),
array("geico","2","",""),
array("google.com","3","",""),
array("gisele bundchen","3","",""),
array("grapefruit diet","3","",""),
array("gnc","3","","")),
"h" => array(
array("hotmail","0","2","3"),
array("home depot","0","2","3"),
array("hsbc","0","2",""),
array("hi5","0","2",""),
array("heath ledger","0","3",""),
array("halloween costumes","1","2",""),
array("harry potter","1","2",""),
array("hannah montana","2","3",""),
array("hp","0","",""),
array("honda","0","",""),
array("hmv","0","",""),
array("halifax","0","",""),
array("hollister","0","",""),
array("halloween","1","",""),
array("headphones","1","",""),
array("heroes","1","",""),
array("hdmi cable","1","",""),
array("house","1","",""),
array("halo 3","1","",""),
array("how i met your mother","1","",""),
array("hard drive","1","",""),
array("halle berry","2","",""),
array("hongkong and shanghai banking corporation","2","",""),
array("hairstyles","2","",""),
array("how to get pregnant","3","",""),
array("how to tie a tie","3","",""),
array("how much should i weigh","3","",""),
array("heidi klum","3","",""),
array("how many feet in a mile","3","",""),
array("how long do drugs stay in your system","3","","")),
"i" => array(
array("iphone","0","1","2"),
array("ikea","0","2","3"),
array("itunes","0","2","3"),
array("irs","0","2","3"),
array("ipod","1","2","3"),
array("imdb","0","2",""),
array("ign","0","2",""),
array("images","0","3",""),
array("isohunt","0","",""),
array("indian railways","0","",""),
array("imax","0","",""),
array("ipod touch","1","",""),
array("iron man","1","",""),
array("ipod nano","1","",""),
array("iphone 3g","1","",""),
array("indiana jones","1","",""),
array("itouch","1","",""),
array("ipod classic","1","",""),
array("ipod shuffle","1","",""),
array("internet explorer","2","",""),
array("u.s. internal revenue service","2","",""),
array("imeem","2","",""),
array("inmates","3","",""),
array("inspirational quotes","3","",""),
array("inmate search","3","",""),
array("internet dictionary","3","","")),
"j" => array(
array("jobs","0","2","3"),
array("java","0","2","3"),
array("jokes","0","2","3"),
array("john lewis","0","2",""),
array("jonas brothers","0","1",""),
array("jessica simpson","2","3",""),
array("jessica alba","2","3",""),
array("jet blue","0","",""),
array("job centre","0","",""),
array("john edwards","0","",""),
array("joe biden","0","",""),
array("jetstar","0","",""),
array("jennifer hudson","1","",""),
array("jason mraz","1","",""),
array("james taylor","1","",""),
array("jeff dunham","1","",""),
array("john adams","1","",""),
array("john mayer","1","",""),
array("jazmine sullivan","1","",""),
array("jawbone","1","",""),
array("john legend","1","",""),
array("jennifer love hewitt","2","",""),
array("jessica biel","2","",""),
array("jcpenney","2","",""),
array("jennifer lopez","2","",""),
array("jeeves","3","",""),
array("jobs in my area","3","",""),
array("jail inmates","3","",""),
array("job listings","3","",""),
array("jc penny","3","","")),
"k" => array(
array("kmart","0","2","3"),
array("kelly blue book","0","3",""),
array("kohls","0","3",""),
array("katy perry","0","1",""),
array("kid rock","0","1",""),
array("kanye west","1","3",""),
array("kim kardashian","2","3",""),
array("kazaa","2","3",""),
array("kijiji","0","",""),
array("kayak","0","",""),
array("kfc","0","",""),
array("klm","0","",""),
array("kinkos","0","",""),
array("kindle","1","",""),
array("kings of leon","1","",""),
array("kung fu panda","1","",""),
array("keyboard","1","",""),
array("keane","1","",""),
array("kingdom hearts","1","",""),
array("keurig","1","",""),
array("kimbo slice vs seth petruzelli","2","",""),
array("kimberly buffington","2","",""),
array("kelley blue book","2","",""),
array("kelly clarkson","2","",""),
array("kohl's","2","",""),
array("keira knightley","2","",""),
array("kbb","2","",""),
array("kate moss","3","",""),
array("kt tunstall","3","",""),
array("kids","3","",""),
array("kay jewelers","3","","")),
"l" => array(
array("limewire","0","2","3"),
array("lyrics","0","2","3"),
array("lowes","0","3",""),
array("lego","0","1",""),
array("lost","1","2",""),
array("lil wayne","1","3",""),
array("lindsay lohan","2","3",""),
array("lotto","0","",""),
array("lloyds tsb","0","",""),
array("last minute","0","",""),
array("littlewoods","0","",""),
array("lg","0","",""),
array("linens and things","0","",""),
array("laptop","1","",""),
array("lego batman","1","",""),
array("luggage","1","",""),
array("lcd tv","1","",""),
array("little big planet","1","",""),
array("lord of the rings","1","",""),
array("lego star wars","1","",""),
array("launch","2","",""),
array("lowe's","2","",""),
array("love poems","2","",""),
array("lottery","2","",""),
array("las vegas","2","",""),
array("love quotes","2","",""),
array("lowes.com","3","",""),
array("last names","3","",""),
array("lyrics to songs","3","",""),
array("locations","3","",""),
array("love","3","","")),
"m" => array(
array("myspace","0","2","3"),
array("mapquest","0","2","3"),
array("maps","0","2","3"),
array("music","1","2","3"),
array("msn","0","2",""),
array("miniclip","0","2",""),
array("macys","0","3",""),
array("movies","0","1",""),
array("myspace layouts","0","",""),
array("michael phelps","0","",""),
array("mininova","0","",""),
array("metallica","1","",""),
array("mp3 player","1","",""),
array("macbook","1","",""),
array("mp3","1","",""),
array("msi wind","1","",""),
array("mamma mia","1","",""),
array("micro sd","1","",""),
array("madonna","1","",""),
array("misty may","2","",""),
array("mail","2","",""),
array("macy's","2","",""),
array("melissa etheridge","2","",""),
array("metric conversion table","3","",""),
array("metric conversion chart","3","",""),
array("myspace.com","3","",""),
array("miley cyrus","3","",""),
array("map","3","","")),
"n" => array(
array("nbc","0","2",""),
array("next","0","2",""),
array("national lottery","0","2",""),
array("natwest","0","2",""),
array("nissan","0","3",""),
array("naruto","1","3",""),
array("nbc olympics","0","",""),
array("netflix","0","",""),
array("news","0","",""),
array("nokia","0","",""),
array("national rail","0","",""),
array("nintendo ds","1","",""),
array("nintendo wii","1","",""),
array("nikon d90","1","",""),
array("nike","1","",""),
array("nightmare before christmas","1","",""),
array("nikon d80","1","",""),
array("nintendo ds games","1","",""),
array("new kids on the block","1","",""),
array("nicholas sparks","1","",""),
array("nascar","2","",""),
array("national association for stock car auto racing","2","",""),
array("nba","2","",""),
array("national basketball association","2","",""),
array("national broadcasting corporation","2","",""),
array("nuclear, biological, and chemical","2","",""),
array("nonja","3","",""),
array("ninjuice","3","",""),
array("ningiants","3","",""),
array("new movies","3","",""),
array("northwest airlines","3","",""),
array("niki taylor","3","",""),
array("ninjatar","3","",""),
array("new york times","3","","")),
"o" => array(
array("orkut","0","2","3"),
array("office depot","0","2","3"),
array("old navy","0","2","3"),
array("obama","0","1","3"),
array("orbitz","0","2",""),
array("online dictionary","2","3",""),
array("online games","2","3",""),
array("office max","2","3",""),
array("olympics","0","",""),
array("olympics 2008","0","",""),
array("o2","0","",""),
array("orange","0","",""),
array("olympic","0","",""),
array("oasis","1","",""),
array("one tree hill","1","",""),
array("oakley","1","",""),
array("onkyo","1","",""),
array("oblivion","1","",""),
array("office 2007","1","",""),
array("oakley sunglasses","1","",""),
array("olympus","1","",""),
array("omega","1","",""),
array("oprah","2","",""),
array("overstock","2","",""),
array("o j simpson","2","",""),
array("overstock.com","3","",""),
array("oxford dictionary","3","",""),
array("olive garden","3","","")),
"p" => array(
array("pizza hut","0","2","3"),
array("photobucket","0","2",""),
array("paypal","0","2",""),
array("pokemon","1","3",""),
array("people search","2","3",""),
array("poems","2","3",""),
array("pc world","0","",""),
array("pandora","0","",""),
array("pineapple express","0","",""),
array("pirate bay","0","",""),
array("people","0","",""),
array("post office","0","",""),
array("priceline","0","",""),
array("ps3","1","",""),
array("psp","1","",""),
array("playstation 3","1","",""),
array("paper trail","1","",""),
array("pink","1","",""),
array("planet earth","1","",""),
array("posters","1","",""),
array("ps3 games","1","",""),
array("portable dvd player","1","",""),
array("paris bennett","2","",""),
array("pogo","2","",""),
array("powerball","2","",""),
array("pottery barn","2","",""),
array("pregnancy","2","",""),
array("paris hilton","3","",""),
array("pictures","3","",""),
array("passport application","3","",""),
array("periodic table","3","",""),
array("pregnancy first signs","3","",""),
array("phrases","3","","")),
"q" => array(
array("quotes","0","2","3"),
array("qvc","0","2","3"),
array("quicktime","0","2","3"),
array("qantas","0","2",""),
array("quiznos","0","3",""),
array("qatar airways","0","2",""),
array("queen","1","2",""),
array("qwest","0","",""),
array("quiz","0","",""),
array("quizzes","0","",""),
array("quest diagnostics","0","",""),
array("quicken","1","",""),
array("quickbooks","1","",""),
array("queer as folk","1","",""),
array("quiksilver","1","",""),
array("quantum of solace","1","",""),
array("quicken 2009","1","",""),
array("queens of the stone age","1","",""),
array("quilt","1","",""),
array("queen of hearts costume","1","",""),
array("quality, value, convenience","2","",""),
array("queensland and northern territory aerial services","2","",""),
array("quality inn","2","",""),
array("query string","2","",""),
array("questions","3","",""),
array("quotes by famous people","3","",""),
array("quotes on life","3","",""),
array("quick weight loss","3","",""),
array("quizes","3","",""),
array("quotes about life","3","","")),
"e" => array(
array("ebay","0","2","3"),
array("expedia","0","2","3"),
array("espn","0","2",""),
array("easyjet","0","2",""),
array("enterprise","0","2",""),
array("eminem","1","2",""),
array("ebay uk","0","",""),
array("ebuddy","0","",""),
array("exchange rates","0","",""),
array("earth","0","",""),
array("emirates","0","",""),
array("external hard drive","1","",""),
array("eragon","1","",""),
array("eclipse","1","",""),
array("entourage","1","",""),
array("eee pc","1","",""),
array("ed hardy","1","",""),
array("edgar sawtelle","1","",""),
array("eat this not that","1","",""),
array("earphones","1","",""),
array("ecards","2","",""),
array("elizabeth reaser","2","",""),
array("eddie van halen","2","",""),
array("eva longoria","2","",""),
array("early pregnancy symptoms","3","",""),
array("english dictionary","3","",""),
array("encyclopedia","3","",""),
array("english to spanish translation","3","",""),
array("earliest possible signs of pregnancy","3","",""),
array("expedia.com","3","",""),
array("eagles of death metal","3","",""),
array("enterprise car rental","3","","")),
"s" => array(
array("sears","0","2","3"),
array("staples","0","2","3"),
array("southwest airlines","0","2","3"),
array("sprint","0","2",""),
array("sams club","0","3",""),
array("sony","0","2",""),
array("skype","0","",""),
array("shawn johnson","0","",""),
array("so you think you can dance","0","",""),
array("sky sports","0","",""),
array("spore","1","",""),
array("sex and the city","1","",""),
array("shoes","1","",""),
array("star wars","1","",""),
array("sleeping beauty","1","",""),
array("sex and the city movie","1","",""),
array("smallville","1","",""),
array("sunglasses","1","",""),
array("supernatural","1","",""),
array("scrubs","1","",""),
array("song lyrics","2","",""),
array("shakira","2","",""),
array("sophie okonedo","2","",""),
array("sarah palin","2","",""),
array("southwest","2","",""),
array("spanish dictionary","3","",""),
array("search engines","3","",""),
array("sample letters","3","",""),
array("spanish translation","3","",""),
array("spanish english translation","3","",""),
array("social security","3","","")),
"t" => array(
array("target","0","2","3"),
array("travelocity","0","2","3"),
array("toys r us","0","2","3"),
array("tesco","0","2",""),
array("ticketmaster","0","2",""),
array("tv guide","0","2",""),
array("the dark knight","0","1",""),
array("thesaurus","0","3",""),
array("toyota","0","2",""),
array("the sun","0","",""),
array("twilight","1","",""),
array("t.i","1","",""),
array("the office","1","",""),
array("the shack","1","",""),
array("transformers","1","",""),
array("toys","1","",""),
array("the killers","1","",""),
array("tv","1","",""),
array("the game","1","",""),
array("t-mobile","2","",""),
array("tattoos","2","",""),
array("travel","2","",""),
array("the algorithm","3","",""),
array("themes","3","",""),
array("tyra banks","3","",""),
array("target.com","3","",""),
array("time zones","3","",""),
array("translator","3","","")),
"u" => array(
array("ups","0","2","3"),
array("united airlines","0","2","3"),
array("used cars","0","2","3"),
array("utube","0","3",""),
array("usps","0","2",""),
array("us airways","0","2",""),
array("ufc","0","2",""),
array("u tube","2","3",""),
array("utorrent","0","",""),
array("urban dictionary","0","",""),
array("usain bolt","0","",""),
array("u2","1","",""),
array("uggs","1","",""),
array("unlocked cell phones","1","",""),
array("ugg boots","1","",""),
array("usb hub","1","",""),
array("usb flash drive","1","",""),
array("under armour","1","",""),
array("umbrella","1","",""),
array("unbox","1","",""),
array("usher","1","",""),
array("uninterruptible power supply","2","",""),
array("united parcel service","2","",""),
array("united states postal service","2","",""),
array("united states map","3","",""),
array("units of measurement","3","",""),
array("unique baby names","3","",""),
array("us map","3","",""),
array("united states maps","3","","")),
"v" => array(
array("verizon wireless","0","2","3"),
array("verizon","0","2","3"),
array("video","0","2","3"),
array("vodafone","0","2",""),
array("victoria secret","0","3",""),
array("vanessa hudgens","2","3",""),
array("virgin","0","",""),
array("vlc","0","",""),
array("vue","0","",""),
array("virgin media","0","",""),
array("virgin mobile","0","",""),
array("vacuum","1","",""),
array("vacuum cleaner","1","",""),
array("vans","1","",""),
array("vera bradley","1","",""),
array("video games","1","",""),
array("voice recorder","1","",""),
array("video camera","1","",""),
array("victorinox","1","",""),
array("vizio","1","",""),
array("v for vendetta","1","",""),
array("victoria's secret","2","",""),
array("vh1","2","",""),
array("vonage","2","",""),
array("volkswagen","2","",""),
array("veoh","2","",""),
array("vanessa anne hudgens","3","",""),
array("victorias secret","3","",""),
array("videos","3","",""),
array("very early symptoms of pregnancy","3","",""),
array("veterans day","3","","")),
"w" => array(
array("wikipedia","0","2","3"),
array("weather","0","2","3"),
array("white pages","0","2","3"),
array("webkinz","0","1","2"),
array("walmart","0","3",""),
array("wwe","0","2",""),
array("www.youtube.com","0","3",""),
array("wiki","0","",""),
array("winrar","0","",""),
array("wells fargo","0","",""),
array("wii","1","",""),
array("wii fit","1","",""),
array("wii games","1","",""),
array("wii console","1","",""),
array("watches","1","",""),
array("world of warcraft","1","",""),
array("wall-e","1","",""),
array("webcam","1","",""),
array("wrath of the lich king","1","",""),
array("wal mart","2","",""),
array("webmd","2","",""),
array("wallpaper","2","",""),
array("walgreens","2","",""),
array("world wrestling entertainment","2","",""),
array("www.google.com","3","",""),
array("what happened to jeeves","3","",""),
array("www.yahoo.com","3","",""),
array("walmart.com","3","",""),
array("web md","3","","")),
"x" => array(
array("xbox","0","1","2"),
array("xm radio","0","2","3"),
array("xanax","0","2","3"),
array("xbox 360","1","2","3"),
array("xbox live","0","1",""),
array("xbox 360 games","1","3",""),
array("xe","0","",""),
array("xkcd","0","",""),
array("xboard","0","",""),
array("x files","0","",""),
array("xvid","0","",""),
array("x games","0","",""),
array("xsi","1","",""),
array("xbox 360 elite","1","",""),
array("xbox 360 controller","1","",""),
array("x-files","1","",""),
array("xbox 360 console","1","",""),
array("xbox 360 hard drive","1","",""),
array("xfactor","2","",""),
array("x men","2","",""),
array("xhamster movies","2","",""),
array("x17","2","",""),
array("xlxx","2","",""),
array("xango","2","",""),
array("x tube","3","",""),
array("xanga","3","",""),
array("xbox 360 cheats","3","",""),
array("xbox cheats","3","",""),
array("xxl magazine","3","","")),
"y" => array(
array("youtube","0","2","3"),
array("yahoo","0","2","3"),
array("yahoo mail","0","2","3"),
array("yellow pages","0","2","3"),
array("yahoo messenger","0","2",""),
array("yamaha","0","1",""),
array("youtube videos","2","3",""),
array("yahoo answers","0","",""),
array("yell","0","",""),
array("yahoo maps","0","",""),
array("yahoo finance","0","",""),
array("young jeezy","1","",""),
array("yoga","1","",""),
array("yoga mat","1","",""),
array("yoga dvd","1","",""),
array("yo gabba gabba","1","",""),
array("yugioh","1","",""),
array("yarn","1","",""),
array("yes","1","",""),
array("year of the gentleman","1","",""),
array("you","2","",""),
array("y8","2","",""),
array("yahoo games","2","",""),
array("yahoo chat","2","",""),
array("yahoo.com","3","",""),
array("you tube","3","",""),
array("youtube.com","3","",""),
array("yellowpages.com","3","",""),
array("you tube.com","3","","")),
"z" => array(
array("zip codes","0","2","3"),
array("zappos","0","2",""),
array("zillow","0","2",""),
array("zune","0","1",""),
array("zedge","0","2",""),
array("zavvi","0","2",""),
array("zac efron","2","3",""),
array("zara","0","",""),
array("zero punctuation","0","",""),
array("zellers","0","",""),
array("ziphone","0","",""),
array("zelda","1","",""),
array("zippo","1","",""),
array("zumba","1","",""),
array("zen","1","",""),
array("zohan","1","",""),
array("zune 120","1","",""),
array("zz top","1","",""),
array("zojirushi","1","",""),
array("z-ro","1","",""),
array("zales","2","",""),
array("zoo","2","",""),
array("zwani","2","",""),
array("zuma","2","",""),
array("zip code finder","3","",""),
array("zip code directory","3","",""),
array("zodiac signs","3","",""),
array("zip code map","3","",""),
array("zip code maps free","3","",""),
array("zip code list","3","",""),
array("zip code","3","",""),
array("zip code search","3","","")));
?>