<?php $topResults = array(
"a" => array(
array("avatar","0","1","4",""),
array("amazon","0","2","",""),
array("aol","0","2","",""),
array("apple","0","1","",""),
array("american express","0","2","",""),
array("autotrader","0","2","",""),
array("american idol","2","4","",""),
array("american airlines","0","","",""),
array("ask.com","0","","",""),
array("addicting games","0","","",""),
array("at&t wireless","0","","",""),
array("alice in wonderland","1","","",""),
array("apple ipad","1","","",""),
array("airsoft guns","1","","",""),
array("assassins creed 2","1","","",""),
array("adidas","1","","",""),
array("airsoft","1","","",""),
array("audio books","1","","",""),
array("alarm clock","1","","",""),
array("ask jeeves","2","","",""),
array("ads bluelithium","2","","",""),
array("at&t","2","","",""),
array("amanda seyfried","2","","",""),
array("angelina jolie","2","","",""),
array("at t","3","","",""),
array("answers.com","3","","",""),
array("airline tickets","3","","",""),
array("att.com","3","","",""),
array("apartments for rent","3","","",""),
array("att","3","","",""),
array("area codes","3","","",""),
array("are vampires real","3","","",""),
array("am i pregnant","3","","",""),
array("aaa","3","","",""),
array("akon","4","","",""),
array("alicia keys","4","","",""),
array("avril lavigne","4","","",""),
array("annoying orange","4","","",""),
array("aventura","4","","",""),
array("alicia keys try sleeping with a broken heart","4","","",""),
array("alvin and the chipmunks","4","","",""),
array("american idol 2010","4","","","")),
"b" => array(
array("best buy","0","2","3",""),
array("bank of america","0","2","3",""),
array("bed bath and beyond","0","2","3",""),
array("baby names","0","2","3",""),
array("britney spears","1","2","4",""),
array("barnes and noble","0","2","",""),
array("beyonce","2","4","",""),
array("babies r us","2","3","",""),
array("brittany murphy","0","","",""),
array("bank of america online banking","0","","",""),
array("bing","0","","",""),
array("burlington coat factory","0","","",""),
array("blockbuster","0","","",""),
array("blackberry","1","","",""),
array("battlefield bad company 2","1","","",""),
array("bluetooth headset","1","","",""),
array("blu ray player","1","","",""),
array("blu ray","1","","",""),
array("blackberry bold 9700","1","","",""),
array("bioshock 2","1","","",""),
array("bose","1","","",""),
array("blackberry unlocked","1","","",""),
array("blank","2","","",""),
array("bbc","2","","",""),
array("baby shower games","3","","",""),
array("baby boy names","3","","",""),
array("bmi","3","","",""),
array("black friday 2009","3","","",""),
array("barack obama","3","","",""),
array("bad romance","4","","",""),
array("bedrock","4","","",""),
array("baby justin bieber","4","","",""),
array("bad romance lady gaga","4","","",""),
array("black eyed peas","4","","",""),
array("blah blah blah kesha","4","","",""),
array("black eyed peas meet me halfway","4","","",""),
array("bedrock lil wayne","4","","","")),
"c" => array(
array("craigslist","0","2","",""),
array("cnn","0","2","",""),
array("costco","0","2","",""),
array("chase","0","2","",""),
array("comcast","0","2","",""),
array("capital one","0","2","",""),
array("call of duty modern warfare 2","1","4","",""),
array("christina aguilera","2","4","",""),
array("comcast.net","0","","",""),
array("club penguin","0","","",""),
array("chase bank","0","","",""),
array("continental airlines","0","","",""),
array("canon 7d","1","","",""),
array("camera","1","","",""),
array("coffee maker","1","","",""),
array("crocs","1","","",""),
array("canon","1","","",""),
array("canon t2i","1","","",""),
array("converse","1","","",""),
array("coach","1","","",""),
array("canon powershot","1","","",""),
array("cingular","2","","",""),
array("chat","2","","",""),
array("cartoon network","2","","",""),
array("cheap airline tickets","3","","",""),
array("cheap flights","3","","",""),
array("coupons","3","","",""),
array("car rentals","3","","",""),
array("cars","3","","",""),
array("cheat codes","3","","",""),
array("calculator","3","","",""),
array("calorie counter","3","","",""),
array("cheap hotels","3","","",""),
array("clip art","3","","",""),
array("chris brown","4","","",""),
array("charlie bit my finger","4","","",""),
array("celine dion","4","","",""),
array("crazy frog","4","","",""),
array("coldplay","4","","",""),
array("chris brown crawl","4","","",""),
array("charlie the unicorn","4","","",""),
array("crawl chris brown","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("dell","0","2","3",""),
array("delta airlines","0","3","",""),
array("direct tv","0","3","",""),
array("disney channel","0","","",""),
array("dominos","0","","",""),
array("dillards","0","","",""),
array("discover card","0","","",""),
array("dick's sporting goods","0","","",""),
array("disney","0","","",""),
array("digital camera","1","","",""),
array("dsi","1","","",""),
array("dvd","1","","",""),
array("droid","1","","",""),
array("dsi xl","1","","",""),
array("dvd player","1","","",""),
array("dexter","1","","",""),
array("diary of a wimpy kid","1","","",""),
array("ds games","1","","",""),
array("ds","1","","",""),
array("dancing with the stars","2","","",""),
array("delta","2","","",""),
array("dennis hopper","2","","",""),
array("danica patrick","2","","",""),
array("dallas cowboys","2","","",""),
array("deal or no deal","2","","",""),
array("days of our lives","2","","",""),
array("daisuke takahashi","2","","",""),
array("dogs","3","","",""),
array("disneychannel.com","3","","",""),
array("driving directions","3","","",""),
array("delta.com","3","","",""),
array("dictionary.com","3","","",""),
array("dog breeds","3","","",""),
array("drake","4","","",""),
array("down","4","","",""),
array("david guetta","4","","",""),
array("do you remember jay sean","4","","",""),
array("down jay sean","4","","",""),
array("drake forever","4","","",""),
array("demi lovato","4","","",""),
array("don't stop believing","4","","",""),
array("drop the world","4","","",""),
array("drop it low","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("ebay motors","0","2","3",""),
array("espn","0","2","",""),
array("easter 2010","0","2","",""),
array("english to spanish translation","0","3","",""),
array("ed hardy","1","3","",""),
array("eminem","2","4","",""),
array("eharmony","2","3","",""),
array("express","0","","",""),
array("etsy","0","","",""),
array("evite","0","","",""),
array("elf yourself","0","","",""),
array("external hard drive","1","","",""),
array("easter","1","","",""),
array("earphones","1","","",""),
array("erykah badu","1","","",""),
array("easter basket","1","","",""),
array("earbuds","1","","",""),
array("external hard drive 1tb","1","","",""),
array("eclipse","1","","",""),
array("ethernet cable","1","","",""),
array("enterprise car rental","2","","",""),
array("emeril lagasse","2","","",""),
array("executive order","2","","",""),
array("ebay.com","3","","",""),
array("expedia.com","3","","",""),
array("eharmony.com","3","","",""),
array("engagement rings","3","","",""),
array("empire state of mind","4","","",""),
array("eminem beautiful","4","","",""),
array("enrique iglesias","4","","",""),
array("evanescence","4","","",""),
array("eminem lose yourself","4","","",""),
array("empire state of mind jay z","4","","",""),
array("elvis presley","4","","",""),
array("eye of the tiger","4","","",""),
array("everybody hurts","4","","","")),
"f" => array(
array("free online games","0","2","3",""),
array("facebook","0","2","",""),
array("facebook login","0","2","",""),
array("food network","0","2","",""),
array("fox news","0","2","",""),
array("fandango","0","2","",""),
array("fafsa","0","2","",""),
array("family guy","2","4","",""),
array("firefox","0","","",""),
array("fedex","0","","",""),
array("forever 21","0","","",""),
array("final fantasy xiii","1","","",""),
array("flash drive","1","","",""),
array("final fantasy","1","","",""),
array("final fantasy 13","1","","",""),
array("food inc","1","","",""),
array("fallout 3","1","","",""),
array("flip video","1","","",""),
array("fleshlight","1","","",""),
array("food processor","1","","",""),
array("fantastic mr fox","1","","",""),
array("face","2","","",""),
array("fidelity","2","","",""),
array("free ringtones","3","","",""),
array("free music downloads","3","","",""),
array("free games","3","","",""),
array("free ecards","3","","",""),
array("find people","3","","",""),
array("free music","3","","",""),
array("free people search","3","","",""),
array("find a person","3","","",""),
array("free credit report","3","","",""),
array("fireflies","4","","",""),
array("fireflies owl city","4","","",""),
array("funny video","4","","",""),
array("funny","4","","",""),
array("fred","4","","",""),
array("funny accidents","4","","",""),
array("forever","4","","",""),
array("forever drake lil wayne","4","","",""),
array("funny cats","4","","","")),
"g" => array(
array("games","0","2","3",""),
array("glee","0","1","4",""),
array("gmail","0","2","",""),
array("google maps","0","2","",""),
array("google earth","0","2","",""),
array("geico","0","2","",""),
array("google","2","4","",""),
array("google search","2","3","",""),
array("google.com","0","","",""),
array("gamestop","0","","",""),
array("google translate","0","","",""),
array("google images","0","","",""),
array("god of war 3","1","","",""),
array("gps","1","","",""),
array("god of war","1","","",""),
array("garmin","1","","",""),
array("gorillaz","1","","",""),
array("garmin gps","1","","",""),
array("guitar","1","","",""),
array("garmin nuvi","1","","",""),
array("gift card","1","","",""),
array("gap","2","","",""),
array("greeting cards","2","","",""),
array("george w bush","2","","",""),
array("global warming","3","","",""),
array("games.com","3","","",""),
array("gnc","3","","",""),
array("genital warts","3","","",""),
array("game cheats","3","","",""),
array("google search engine","3","","",""),
array("girl games","3","","",""),
array("gout","3","","",""),
array("gummy bear song","4","","",""),
array("giant squid in california","4","","",""),
array("green day","4","","",""),
array("grammy awards 2010","4","","",""),
array("gucci mane","4","","",""),
array("glee don't stop believe","4","","",""),
array("green day 21 guns","4","","",""),
array("guns n roses","4","","","")),
"h" => array(
array("hotmail","0","2","3",""),
array("home depot","0","2","3",""),
array("harry potter","1","2","",""),
array("hulu","0","","",""),
array("haiti","0","","",""),
array("hollister","0","","",""),
array("hobby lobby","0","","",""),
array("horoscope","0","","",""),
array("hp","0","","",""),
array("hotels.com","0","","",""),
array("harbor freight","0","","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("heavy rain","1","","",""),
array("htc hd2","1","","",""),
array("hard drive","1","","",""),
array("hello kitty","1","","",""),
array("heart rate monitor","1","","",""),
array("hdmi","1","","",""),
array("how to train your dragon","1","","",""),
array("horoscopes","2","","",""),
array("holiday inn","2","","",""),
array("honda","2","","",""),
array("health care reform","2","","",""),
array("h r 4872","2","","",""),
array("health care bill","2","","",""),
array("hgtv","2","","",""),
array("how much should i weigh","3","","",""),
array("how to kiss","3","","",""),
array("how to get pregnant","3","","",""),
array("halloween costumes","3","","",""),
array("hotmail.com","3","","",""),
array("how do you spell a word","3","","",""),
array("how to make a website","3","","",""),
array("how to write a resume","3","","",""),
array("hannah montana","4","","",""),
array("how low can you go ludacris","4","","",""),
array("happy tree friends","4","","",""),
array("hey soul sister","4","","",""),
array("hard rihanna","4","","",""),
array("halo","4","","",""),
array("halo beyonce","4","","",""),
array("how to jerk","4","","",""),
array("hallelujah","4","","",""),
array("hotel room service","4","","","")),
"i" => array(
array("itunes","0","2","3",""),
array("ipad","0","1","4",""),
array("ipod","1","2","3",""),
array("iphone","1","2","3",""),
array("imdb","0","2","",""),
array("ikea","0","2","",""),
array("irs","0","2","",""),
array("inspirational quotes","0","3","",""),
array("images","0","3","",""),
array("ipod touch","1","3","",""),
array("itunes download","0","","",""),
array("isohunt","0","","",""),
array("ikea usa","0","","",""),
array("ipod nano","1","","",""),
array("iphone 3gs","1","","",""),
array("iphone case","1","","",""),
array("itouch","1","","",""),
array("ipod shuffle","1","","",""),
array("ipod touch 3rd generation","1","","",""),
array("internet explorer","2","","",""),
array("iceland volcano","2","","",""),
array("imeem","2","","",""),
array("ign","2","","",""),
array("is the world going to end in 2012","3","","",""),
array("iq test","3","","",""),
array("is bronchitis contagious","3","","",""),
array("is pneumonia contagious","3","","",""),
array("in my head jason derulo","4","","",""),
array("i gotta feeling","4","","",""),
array("iyaz replay","4","","",""),
array("imma be","4","","",""),
array("in my head","4","","",""),
array("imma be black eyed peas","4","","",""),
array("i can transform ya chris brown","4","","",""),
array("im on a boat","4","","",""),
array("iron man 2 trailer","4","","","")),
"j" => array(
array("justin bieber","0","1","2","4"),
array("jokes","0","2","3",""),
array("jcpenney","0","2","",""),
array("joann fabrics","0","3","",""),
array("jobs","0","2","",""),
array("jet blue","0","","",""),
array("jersey shore","0","","",""),
array("justin tv","0","","",""),
array("jimmy johns","0","","",""),
array("java","0","","",""),
array("just cause 2","1","","",""),
array("jillian michaels","1","","",""),
array("juicer","1","","",""),
array("jimi hendrix","1","","",""),
array("jewelry","1","","",""),
array("juicy couture","1","","",""),
array("john mayer","1","","",""),
array("james patterson","1","","",""),
array("johnny cash","1","","",""),
array("jennifer love hewitt","2","","",""),
array("jessica simpson","2","","",""),
array("julianne moore","2","","",""),
array("jessica alba","2","","",""),
array("jennifer aniston","2","","",""),
array("jesse james","2","","",""),
array("jobs in my area","3","","",""),
array("job search","3","","",""),
array("jcpenney.com","3","","",""),
array("jc penney","3","","",""),
array("jobs for teens","3","","",""),
array("jordans","3","","",""),
array("jcp.com","3","","",""),
array("jobs.com","3","","",""),
array("justin bieber one time","4","","",""),
array("justin bieber baby","4","","",""),
array("jay z","4","","",""),
array("jason derulo in my head","4","","",""),
array("justin timberlake","4","","",""),
array("jason derulo","4","","",""),
array("justin bieber love me","4","","",""),
array("jay sean","4","","",""),
array("justin bieber one less lonelygirl","4","","","")),
"k" => array(
array("kmart","0","2","3",""),
array("kohls","0","3","",""),
array("kayak","0","3","",""),
array("kim kardashian","0","3","",""),
array("kindle","1","3","",""),
array("katy perry","2","4","",""),
array("kelly clarkson","2","4","",""),
array("kelly blue book","0","","",""),
array("kesha","0","","",""),
array("kay jewelers","0","","",""),
array("kroger","0","","",""),
array("kinkos","0","","",""),
array("ke ha","0","","",""),
array("keurig","1","","",""),
array("k cups","1","","",""),
array("kindle books","1","","",""),
array("kindle 2","1","","",""),
array("keyboard","1","","",""),
array("keurig coffee maker","1","","",""),
array("kindle cover","1","","",""),
array("kodak zi8","1","","",""),
array("kindle dx","1","","",""),
array("kim kardashian and reggie bush","2","","",""),
array("katrina hodge","2","","",""),
array("kohl's","2","","",""),
array("kate gosselin","2","","",""),
array("keira knightley","2","","",""),
array("kimora lee simmons","2","","",""),
array("kbb","2","","",""),
array("kohls.com","3","","",""),
array("kmart.com","3","","",""),
array("kids games","3","","",""),
array("kijiji","3","","",""),
array("kayak.com","3","","",""),
array("keisha tik tok","4","","",""),
array("kesha blah blah blah","4","","",""),
array("kiss","4","","",""),
array("kanye west","4","","",""),
array("kid cudi","4","","",""),
array("kiss me thru the phone","4","","",""),
array("kings of leon","4","","",""),
array("keri hilson","4","","","")),
"l" => array(
array("lady gaga","0","1","2","4"),
array("limewire","0","2","3",""),
array("lyrics","0","2","3",""),
array("love quotes","0","2","3",""),
array("lost","0","1","2",""),
array("lil wayne","2","3","4",""),
array("lowes","0","3","",""),
array("love poems","2","3","",""),
array("linkedin","0","","",""),
array("lands end","0","","",""),
array("louis vuitton","0","","",""),
array("ll zamenhof","0","","",""),
array("laptop","1","","",""),
array("lego","1","","",""),
array("luggage","1","","",""),
array("lego star wars","1","","",""),
array("laptop computer","1","","",""),
array("lord of the rings","1","","",""),
array("lcd tv","1","","",""),
array("little big planet","1","","",""),
array("lindsay lohan","2","","",""),
array("lowe's","2","","",""),
array("las vegas","2","","",""),
array("lyrics to songs","3","","",""),
array("lingerie","3","","",""),
array("lowes.com","3","","",""),
array("love","3","","",""),
array("lady gaga bad romance","4","","",""),
array("lady gaga paparazzi","4","","",""),
array("lady gaga poker face","4","","",""),
array("linkin park","4","","",""),
array("lady gaga telephone","4","","",""),
array("lil wayne no ceiling","4","","",""),
array("love story","4","","",""),
array("luge crash","4","","","")),
"m" => array(
array("music","1","2","3","4"),
array("maps","0","2","3",""),
array("myspace","0","2","",""),
array("msn","0","2","",""),
array("mapquest driving directions","0","2","",""),
array("mortgage calculator","0","3","",""),
array("modern warfare 2","1","4","",""),
array("michael jackson","1","4","",""),
array("miley cyrus","2","4","",""),
array("mapquest","0","","",""),
array("macys","0","","",""),
array("miniclip","0","","",""),
array("msnbc","0","","",""),
array("michaels","0","","",""),
array("mp3 player","1","","",""),
array("macbook","1","","",""),
array("mass effect 2","1","","",""),
array("macbook pro","1","","",""),
array("micro sd","1","","",""),
array("mp3","1","","",""),
array("mass effect","1","","",""),
array("movies","2","","",""),
array("macy's","2","","",""),
array("mtv","2","","",""),
array("megan fox","2","","",""),
array("myspace layouts","3","","",""),
array("music videos","3","","",""),
array("math answers","3","","",""),
array("match.com","3","","",""),
array("myspace backgrounds","3","","",""),
array("map","3","","",""),
array("medical dictionary","3","","",""),
array("mariah carey","4","","",""),
array("miley cyrus party in the usa","4","","",""),
array("metallica","4","","",""),
array("michael jackson billie jean","4","","",""),
array("meet me halfway","4","","",""),
array("madonna","4","","","")),
"n" => array(
array("netflix","0","2","3",""),
array("national weather service","0","2","",""),
array("news","0","3","",""),
array("new moon","1","4","",""),
array("nike","1","3","",""),
array("nascar","2","3","",""),
array("naruto","2","4","",""),
array("nada","2","3","",""),
array("nfl.com","0","","",""),
array("nordstrom","0","","",""),
array("new york times","0","","",""),
array("nbc","0","","",""),
array("nick jr","0","","",""),
array("noaa","0","","",""),
array("nickelodeon","0","","",""),
array("nintendo ds","1","","",""),
array("netbook","1","","",""),
array("nikon d90","1","","",""),
array("new moon dvd","1","","",""),
array("nintendo dsi","1","","",""),
array("nexus one","1","","",""),
array("nintendo wii","1","","",""),
array("nikon d5000","1","","",""),
array("nadya suleman","2","","",""),
array("ncaa basketball","2","","",""),
array("naomi campbell","2","","",""),
array("nasa","2","","",""),
array("north korea","2","","",""),
array("name meanings","3","","",""),
array("nissan","3","","",""),
array("netflix.com","3","","",""),
array("northwest airlines","3","","",""),
array("names","3","","",""),
array("nicki minaj","4","","",""),
array("naturally selena gomez","4","","",""),
array("nigahiga","4","","",""),
array("nickelback","4","","",""),
array("new songs 2010","4","","",""),
array("naruto shippuden","4","","",""),
array("nobody","4","","",""),
array("new boyz","4","","","")),
"o" => array(
array("office depot","0","2","3",""),
array("orbitz","0","2","3",""),
array("online games","0","2","3",""),
array("overstock","0","2","",""),
array("old navy","0","3","",""),
array("olive garden","0","2","",""),
array("office max","0","3","",""),
array("oprah","0","2","",""),
array("owl city","1","4","",""),
array("online dictionary","2","3","",""),
array("olympics","0","","",""),
array("olympics 2010","0","","",""),
array("oakley","1","","",""),
array("otterbox","1","","",""),
array("oakley sunglasses","1","","",""),
array("ooma","1","","",""),
array("office 2007","1","","",""),
array("outliers","1","","",""),
array("oakley sunglasses for men","1","","",""),
array("one tree hill","1","","",""),
array("office chair","1","","",""),
array("orkut","2","","",""),
array("omg","2","","",""),
array("osama bin laden","2","","",""),
array("overstock.com","3","","",""),
array("obama","3","","",""),
array("ovulation calendar","3","","",""),
array("ovulation calculator","3","","",""),
array("owl city fireflies","4","","",""),
array("one time","4","","",""),
array("one time justin bieber","4","","",""),
array("one less lonely justin bieber","4","","",""),
array("one republic all the right moves","4","","",""),
array("oh snsd","4","","",""),
array("on to the next one jay z","4","","",""),
array("one less lonely girl- justin bieber","4","","",""),
array("owl city vanilla twilight","4","","","")),
"p" => array(
array("paypal","0","2","3",""),
array("pandora","0","2","",""),
array("pizza hut","0","2","",""),
array("people search","2","3","",""),
array("poems","2","3","",""),
array("photobucket","0","","",""),
array("poptropica","0","","",""),
array("papa johns","0","","",""),
array("people of walmart","0","","",""),
array("pirate bay","0","","",""),
array("pbs kids","0","","",""),
array("people magazine","0","","",""),
array("ps3","1","","",""),
array("playstation 3","1","","",""),
array("p90x","1","","",""),
array("psp","1","","",""),
array("ps3 games","1","","",""),
array("ps3 console","1","","",""),
array("pokemon","1","","",""),
array("princess and the frog","1","","",""),
array("portable dvd player","1","","",""),
array("percy jackson","1","","",""),
array("pogo","2","","",""),
array("paula abdul","2","","",""),
array("petsmart","2","","",""),
array("perez hilton","2","","",""),
array("penelope cruz","2","","",""),
array("pregnancy week by week","3","","",""),
array("people finder","3","","",""),
array("prom dresses","3","","",""),
array("priceline.com","3","","",""),
array("pregnancy","3","","",""),
array("proxy","3","","",""),
array("pregnancy symptoms","3","","",""),
array("pants on the ground","4","","",""),
array("party in the usa","4","","",""),
array("pink","4","","",""),
array("pitbull","4","","",""),
array("paramore","4","","",""),
array("poker face","4","","",""),
array("paparazzi lady gaga","4","","",""),
array("poker face lady gaga","4","","",""),
array("party in the usa lyrics","4","","",""),
array("pink floyd","4","","","")),
"q" => array(
array("quotes","0","2","3",""),
array("qvc","0","2","",""),
array("quotes about life","0","3","",""),
array("quicktime","0","2","",""),
array("quest diagnostics","0","2","",""),
array("quiznos","0","2","",""),
array("quicken","0","1","",""),
array("quickbooks","1","3","",""),
array("queen","1","4","",""),
array("quizzes","2","3","",""),
array("quotes about love","0","","",""),
array("quotes to live by","0","","",""),
array("quick trim","0","","",""),
array("quickbooks pro 2010","1","","",""),
array("quicken 2010","1","","",""),
array("quiksilver","1","","",""),
array("queer as folk","1","","",""),
array("quantum of solace","1","","",""),
array("quicken essentials for mac","1","","",""),
array("quicken for mac","1","","",""),
array("query string","2","","",""),
array("qwest","2","","",""),
array("qantas","2","","",""),
array("qatar airways","2","","",""),
array("questions and answers","3","","",""),
array("questions","3","","",""),
array("quotes of the day","3","","",""),
array("qvc.com","3","","",""),
array("quit smoking","3","","",""),
array("quest","3","","",""),
array("queen bohemian rhapsody","4","","",""),
array("quest crew","4","","",""),
array("queen we will rock you","4","","",""),
array("queen don't stop me now","4","","",""),
array("queens of the stone age","4","","",""),
array("queen i want to break free","4","","",""),
array("queen somebody to love","4","","",""),
array("queen seondeok","4","","",""),
array("queen we are the champions","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("ebay motors","0","2","3",""),
array("espn","0","2","",""),
array("easter 2010","0","2","",""),
array("english to spanish translation","0","3","",""),
array("ed hardy","1","3","",""),
array("eminem","2","4","",""),
array("eharmony","2","3","",""),
array("express","0","","",""),
array("etsy","0","","",""),
array("evite","0","","",""),
array("elf yourself","0","","",""),
array("external hard drive","1","","",""),
array("easter","1","","",""),
array("earphones","1","","",""),
array("erykah badu","1","","",""),
array("easter basket","1","","",""),
array("earbuds","1","","",""),
array("external hard drive 1tb","1","","",""),
array("eclipse","1","","",""),
array("ethernet cable","1","","",""),
array("enterprise car rental","2","","",""),
array("emeril lagasse","2","","",""),
array("executive order","2","","",""),
array("ebay.com","3","","",""),
array("expedia.com","3","","",""),
array("eharmony.com","3","","",""),
array("engagement rings","3","","",""),
array("empire state of mind","4","","",""),
array("eminem beautiful","4","","",""),
array("enrique iglesias","4","","",""),
array("evanescence","4","","",""),
array("eminem lose yourself","4","","",""),
array("empire state of mind jay z","4","","",""),
array("elvis presley","4","","",""),
array("eye of the tiger","4","","",""),
array("everybody hurts","4","","","")),
"s" => array(
array("southwest airlines","0","2","3",""),
array("sears","0","2","3",""),
array("skype","0","2","",""),
array("sprint","0","2","",""),
array("shoes","1","3","",""),
array("snoop dogg","2","4","",""),
array("shakira","2","4","",""),
array("sams club","0","","",""),
array("spanish translation","0","","",""),
array("super bowl 2010","0","","",""),
array("staples","0","","",""),
array("sparknotes","0","","",""),
array("sports authority","0","","",""),
array("sony cybershot","1","","",""),
array("sherlock holmes","1","","",""),
array("sunglasses","1","","",""),
array("star wars","1","","",""),
array("star trek","1","","",""),
array("sd card","1","","",""),
array("sade","1","","",""),
array("sewing machine","1","","",""),
array("speakers","1","","",""),
array("sandra bullock","2","","",""),
array("sarah palin","2","","",""),
array("samsung","2","","",""),
array("scarlett johansson","2","","",""),
array("science fair projects","3","","",""),
array("song lyrics","3","","",""),
array("swine flu","3","","",""),
array("swine flu symptoms","3","","",""),
array("symptoms of swine flu","3","","",""),
array("spanish dictionary","3","","",""),
array("search engines","3","","",""),
array("selena gomez","4","","",""),
array("small wood projects","4","","",""),
array("soulja boy","4","","",""),
array("starstruck","4","","",""),
array("selena gomez naturally","4","","",""),
array("shane dawson","4","","",""),
array("single ladies","4","","",""),
array("say ahh trey songz","4","","","")),
"t" => array(
array("travelocity","0","2","3",""),
array("toys r us","0","2","3",""),
array("target","0","2","",""),
array("tmz","0","2","",""),
array("twilight","1","3","",""),
array("toyota","2","3","",""),
array("tattoos","2","3","",""),
array("taylor swift","2","4","",""),
array("tiger woods","0","","",""),
array("twitter","0","","",""),
array("translator","0","","",""),
array("thesaurus","0","","",""),
array("tmobile","0","","",""),
array("tv guide","0","","",""),
array("toy story","1","","",""),
array("the blind side","1","","",""),
array("tv","1","","",""),
array("true blood","1","","",""),
array("the help","1","","",""),
array("the big short","1","","",""),
array("the last song","1","","",""),
array("true blood season 2","1","","",""),
array("t2i","1","","",""),
array("transformers 3","2","","",""),
array("tagged","2","","",""),
array("t-mobile","2","","",""),
array("tattoo designs","3","","",""),
array("tires","3","","",""),
array("translate english to spanish","3","","",""),
array("teen pregnancy","3","","",""),
array("telephone directory","3","","",""),
array("tik tok","4","","",""),
array("tik tok keisha","4","","",""),
array("taylor swift you belong with me","4","","",""),
array("telephone lady gaga","4","","",""),
array("two is better than one","4","","",""),
array("tom and jerry","4","","",""),
array("tick tock","4","","",""),
array("trey songz","4","","",""),
array("tie me down","4","","","")),
"u" => array(
array("usher","1","2","4",""),
array("usps","0","2","",""),
array("ups","0","2","",""),
array("united airlines","0","3","",""),
array("us airways","0","3","",""),
array("uggs","1","3","",""),
array("ufc","2","4","",""),
array("unemployment","2","3","",""),
array("ups tracking","0","","",""),
array("urban dictionary","0","","",""),
array("urban outfitters","0","","",""),
array("usps tracking","0","","",""),
array("utorrent","0","","",""),
array("us bank","0","","",""),
array("unlocked cell phones","1","","",""),
array("usb flash drive","1","","",""),
array("up","1","","",""),
array("up in the air","1","","",""),
array("uncharted 2","1","","",""),
array("usb hub","1","","",""),
array("umbrella","1","","",""),
array("under armour","1","","",""),
array("united","2","","",""),
array("undercover boss","2","","",""),
array("uitm","2","","",""),
array("usaa","2","","",""),
array("univision","2","","",""),
array("used cars","3","","",""),
array("ugg boots","3","","",""),
array("used cars for sale","3","","",""),
array("unique baby names","3","","",""),
array("university of phoenix","3","","",""),
array("used books","3","","",""),
array("u2","4","","",""),
array("usher daddy's home","4","","",""),
array("usher papers","4","","",""),
array("ufo","4","","",""),
array("use somebody","4","","",""),
array("use somebody kings of leon","4","","",""),
array("unforgivable","4","","",""),
array("united states of pop 2009","4","","","")),
"v" => array(
array("verizon","0","2","3",""),
array("verizon wireless","0","3","",""),
array("victoria secret","0","3","",""),
array("vancouver 2010","0","4","",""),
array("vampire diaries","0","1","",""),
array("value city furniture","0","2","",""),
array("vh1","0","2","",""),
array("vera bradley","1","3","",""),
array("vampire weekend","1","4","",""),
array("vanessa hudgens","2","4","",""),
array("vlc","0","","",""),
array("verizon.net","0","","",""),
array("valentine's day movie","0","","",""),
array("vacuum cleaner","1","","",""),
array("video camera","1","","",""),
array("verizon cell phones","1","","",""),
array("vacuum","1","","",""),
array("vans","1","","",""),
array("vibratores for women","1","","",""),
array("victoria's secret","1","","",""),
array("video","2","","",""),
array("vicki kennedy","2","","",""),
array("vonage","2","","",""),
array("vanguard","2","","",""),
array("volkswagen","2","","",""),
array("victoria beckham","2","","",""),
array("verizon.com","3","","",""),
array("verizonwireless.com","3","","",""),
array("volcanoes","3","","",""),
array("videos","3","","",""),
array("virgin mobile","3","","",""),
array("viagra","3","","",""),
array("valentines day trailer","4","","",""),
array("various artists","4","","",""),
array("video phone","4","","",""),
array("valentines day","4","","",""),
array("video phone beyonce official video","4","","",""),
array("vanilla twilight","4","","",""),
array("vanilla twilight owl city","4","","","")),
"w" => array(
array("weather","0","2","3",""),
array("white pages","0","2","3",""),
array("wikipedia","0","2","",""),
array("webkinz","0","2","",""),
array("walgreens","0","2","",""),
array("wells fargo","0","2","",""),
array("wwe","2","4","",""),
array("walmart","0","","",""),
array("www.facebook.com","0","","",""),
array("watch-movies.net","0","","",""),
array("web md","0","","",""),
array("wii","1","","",""),
array("wii games","1","","",""),
array("wii fit","1","","",""),
array("windows 7","1","","",""),
array("wii console","1","","",""),
array("wii fit plus","1","","",""),
array("wireless router","1","","",""),
array("watches","1","","",""),
array("webcam","1","","",""),
array("wii fit plus with balance board","1","","",""),
array("wachovia","2","","",""),
array("wamu","2","","",""),
array("weight watchers","2","","",""),
array("what does my name mean","3","","",""),
array("what is love","3","","",""),
array("when will the world end","3","","",""),
array("what are the symptoms of swine flu","3","","",""),
array("what is global warming","3","","",""),
array("wedding dresses","3","","",""),
array("what does my last name mean","3","","",""),
array("weather forecast","3","","",""),
array("we are the world","4","","",""),
array("whatcha say","4","","",""),
array("we are the world haiti","4","","",""),
array("whatcha say jason derulo","4","","",""),
array("wisin y yandel","4","","",""),
array("we are the world 2010","4","","",""),
array("whitney houston","4","","",""),
array("westlife","4","","",""),
array("we are the world michael jackson","4","","","")),
"x" => array(
array("xbox 360","0","1","2","3"),
array("xm radio","0","2","3",""),
array("xbox live","0","1","2",""),
array("xanax","0","2","3",""),
array("xbox 360 games","0","1","3",""),
array("xbox 720","0","4","",""),
array("xbox","1","3","",""),
array("xbox 360 elite","1","3","",""),
array("xbox cheats","2","3","",""),
array("xkcd","0","","",""),
array("xcel energy","0","","",""),
array("xbmc","0","","",""),
array("xm radio online","0","","",""),
array("xbox 360 console","1","","",""),
array("xbox 360 controller","1","","",""),
array("xbox 360 wireless adapter","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("xbox 360 headset","1","","",""),
array("x games","2","","",""),
array("x17","2","","",""),
array("xerox","2","","",""),
array("xbox cheat codes","2","","",""),
array("xenical","2","","",""),
array("xbox 360 cheats","3","","",""),
array("xbox 360 cheat codes","3","","",""),
array("xbox360","3","","",""),
array("x factor 2009","4","","",""),
array("x factor","4","","",""),
array("xxl movie","4","","",""),
array("xzibit","4","","",""),
array("x factor 2010","4","","",""),
array("xatzigiannis","4","","",""),
array("xxl tv 18","4","","",""),
array("x factor 2010 danmark","4","","","")),
"y" => array(
array("youtube","0","2","3","4"),
array("yahoo mail","0","2","3",""),
array("yellow pages","0","2","3",""),
array("yahoo","0","2","",""),
array("youtube music","0","3","",""),
array("yahoo maps","0","2","",""),
array("young money","1","4","",""),
array("yahoo answers","0","","",""),
array("yahoo finance","0","","",""),
array("yelp","0","","",""),
array("yahoo music","0","","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yoga dvd","1","","",""),
array("yo gabba gabba","1","","",""),
array("yugioh cards","1","","",""),
array("your baby can read","1","","",""),
array("yakuza 3","1","","",""),
array("yugioh","1","","",""),
array("yarn","1","","",""),
array("youtube video","2","","",""),
array("yahoo messenger","2","","",""),
array("youtube broadcast yourself","2","","",""),
array("yamaha","2","","",""),
array("yahoo games","2","","",""),
array("youtube videos","3","","",""),
array("yellowpages.com","3","","",""),
array("yellow pages.com","3","","",""),
array("yahoo.com","3","","",""),
array("yellowbook.com","3","","",""),
array("yellow book","3","","",""),
array("you belong with me","4","","",""),
array("you belong with me taylor swift","4","","",""),
array("your a jerk","4","","",""),
array("young jeezy","4","","",""),
array("young money bedrock","4","","",""),
array("you belong with me taylor swift lyrics","4","","",""),
array("your love is my drug","4","","",""),
array("yetenek sizsiniz türkiye","4","","","")),
"z" => array(
array("zappos","0","2","3",""),
array("zodiac signs","0","2","3",""),
array("zhu zhu pets","0","1","3",""),
array("zales","0","2","3",""),
array("zune","0","1","2",""),
array("zillow","0","2","",""),
array("zip codes","0","3","",""),
array("zombieland","1","4","",""),
array("zumba","1","4","",""),
array("zhu zhu","1","3","",""),
array("zuma","2","3","",""),
array("zip code finder","2","3","",""),
array("zip codes by city","0","","",""),
array("zumiez","0","","",""),
array("zoe saldana","0","","",""),
array("zune hd","1","","",""),
array("zippo","1","","",""),
array("zumba fitness dvd","1","","",""),
array("zelda","1","","",""),
array("zumba dvd","1","","",""),
array("zydrunas ilgauskas","2","","",""),
array("zip code lookup","2","","",""),
array("zedge","2","","",""),
array("zappos.com","3","","",""),
array("zip code list","3","","",""),
array("zombie","4","","",""),
array("zac brown band","4","","",""),
array("zz top","4","","",""),
array("zac efron","4","","",""),
array("zidane","4","","",""),
array("zeitgeist","4","","",""),
array("zombieland trailer","4","","",""),
array("zombie nation","4","","","")));
?>