<?php $topResults = array(
"a" => array(
array("avatar","0","1","4",""),
array("amazon","0","2","",""),
array("aol","0","2","",""),
array("american airlines","0","2","",""),
array("apple","0","1","",""),
array("american express","0","2","",""),
array("at&t","0","2","",""),
array("american idol","2","4","",""),
array("addicting games","0","","",""),
array("ask.com","0","","",""),
array("at&t wireless","0","","",""),
array("assassins creed 2","1","","",""),
array("airsoft guns","1","","",""),
array("adidas","1","","",""),
array("alice in wonderland","1","","",""),
array("apple ipad","1","","",""),
array("alarm clock","1","","",""),
array("airsoft","1","","",""),
array("audio books","1","","",""),
array("ask jeeves","2","","",""),
array("autotrader","2","","",""),
array("argos","2","","",""),
array("angelina jolie","2","","",""),
array("att","3","","",""),
array("açaí berry","3","","",""),
array("aaa","3","","",""),
array("att.com","3","","",""),
array("airline tickets","3","","",""),
array("avg","3","","",""),
array("att wireless","3","","",""),
array("area codes","3","","",""),
array("alltel","3","","",""),
array("am i pregnant","3","","",""),
array("akon","4","","",""),
array("alicia keys","4","","",""),
array("avatar trailer","4","","",""),
array("alvin and the chipmunks","4","","",""),
array("avril lavigne","4","","",""),
array("aventura","4","","",""),
array("alvin and the chipmunks 2","4","","",""),
array("alicia keys try sleeping with a broken heart","4","","","")),
"b" => array(
array("best buy","0","2","3",""),
array("bank of america","0","2","3",""),
array("barnes and noble","0","2","3",""),
array("bed bath and beyond","0","2","",""),
array("blockbuster","0","2","",""),
array("britney spears","2","4","",""),
array("baby names","2","3","",""),
array("babies r us","2","3","",""),
array("brittany murphy","0","","",""),
array("bank of america online banking","0","","",""),
array("bing","0","","",""),
array("black friday 2009","0","","",""),
array("burlington coat factory","0","","",""),
array("bioshock 2","1","","",""),
array("blackberry","1","","",""),
array("blu ray player","1","","",""),
array("bluetooth headset","1","","",""),
array("blu ray","1","","",""),
array("bioshock","1","","",""),
array("bose","1","","",""),
array("blackberry unlocked","1","","",""),
array("boots","1","","",""),
array("blackberry bold 9700","1","","",""),
array("bbc","2","","",""),
array("bebo","2","","",""),
array("barack obama","3","","",""),
array("baby shower games","3","","",""),
array("books","3","","",""),
array("bmi","3","","",""),
array("breast cancer","3","","",""),
array("bad romance","4","","",""),
array("bad romance lady gaga","4","","",""),
array("beyonce","4","","",""),
array("bedrock","4","","",""),
array("black eyed peas","4","","",""),
array("black eyed peas meet me halfway","4","","",""),
array("britney spears 3","4","","",""),
array("boom boom pow","4","","",""),
array("beyonce sweet dreams","4","","","")),
"c" => array(
array("craigslist","0","2","",""),
array("cnn","0","2","",""),
array("costco","0","2","",""),
array("capital one","0","2","",""),
array("comcast","0","2","",""),
array("call of duty modern warfare 2","1","4","",""),
array("comcast.net","0","","",""),
array("chase","0","","",""),
array("club penguin","0","","",""),
array("chase bank","0","","",""),
array("continental airlines","0","","",""),
array("coffee maker","1","","",""),
array("cell phones","1","","",""),
array("camera","1","","",""),
array("canon 7d","1","","",""),
array("canon","1","","",""),
array("coach","1","","",""),
array("cordless phone","1","","",""),
array("computer speakers","1","","",""),
array("catcher in the rye","1","","",""),
array("circuit city","2","","",""),
array("cingular","2","","",""),
array("chat","2","","",""),
array("cartoon network","2","","",""),
array("currency converter","2","","",""),
array("cheap flights","3","","",""),
array("cars","3","","",""),
array("coupons","3","","",""),
array("car rentals","3","","",""),
array("cheap airline tickets","3","","",""),
array("cheap hotels","3","","",""),
array("clip art","3","","",""),
array("checks","3","","",""),
array("cheat codes","3","","",""),
array("cars.com","3","","",""),
array("chris brown","4","","",""),
array("charlie bit my finger","4","","",""),
array("christina aguilera","4","","",""),
array("celine dion","4","","",""),
array("crazy frog","4","","",""),
array("coldplay","4","","",""),
array("chris brown crawl","4","","",""),
array("conan o'brien","4","","",""),
array("crawl chris brown","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("dell","0","2","3",""),
array("disney channel","0","2","",""),
array("delta airlines","0","2","",""),
array("direct tv","0","3","",""),
array("droid","0","1","",""),
array("driving directions","2","3","",""),
array("directions","2","3","",""),
array("dish network","2","3","",""),
array("dmv","2","3","",""),
array("dominos","0","","",""),
array("dillards","0","","",""),
array("dick's sporting goods","0","","",""),
array("discover card","0","","",""),
array("digital camera","1","","",""),
array("dsi","1","","",""),
array("dvd","1","","",""),
array("dear john","1","","",""),
array("dexter","1","","",""),
array("dvd player","1","","",""),
array("dante's inferno","1","","",""),
array("ds games","1","","",""),
array("dragon age","1","","",""),
array("danica patrick","2","","",""),
array("dancing with the stars","2","","",""),
array("dogs","3","","",""),
array("dresses","3","","",""),
array("diabetes","3","","",""),
array("down","4","","",""),
array("drake","4","","",""),
array("down jay sean","4","","",""),
array("david guetta","4","","",""),
array("do you remember jay sean","4","","",""),
array("david after dentist","4","","",""),
array("demi lovato","4","","",""),
array("down jay sean lil wayne","4","","",""),
array("drake forever","4","","",""),
array("drop it low","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("eminem","1","2","4",""),
array("espn","0","2","",""),
array("ed hardy","1","3","",""),
array("ecards","2","3","",""),
array("express","0","","",""),
array("english to spanish translation","0","","",""),
array("elf yourself","0","","",""),
array("etsy","0","","",""),
array("ebay motors","0","","",""),
array("evite","0","","",""),
array("easter 2010","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("electric blanket","1","","",""),
array("external hard drive 1tb","1","","",""),
array("entourage","1","","",""),
array("ethernet cable","1","","",""),
array("emma","1","","",""),
array("enterprise car rental","2","","",""),
array("ellen degeneres","2","","",""),
array("easyjet","2","","",""),
array("evangeline lilly","2","","",""),
array("eva longoria","2","","",""),
array("ebay.com","3","","",""),
array("eharmony","3","","",""),
array("expedia.com","3","","",""),
array("eharmony.com","3","","",""),
array("earth day 2009","3","","",""),
array("engagement rings","3","","",""),
array("empire state of mind","4","","",""),
array("eminem beautiful","4","","",""),
array("enrique iglesias","4","","",""),
array("evanescence","4","","",""),
array("empire state of mind jay z","4","","",""),
array("elvis presley","4","","",""),
array("eminem lose yourself","4","","",""),
array("eye of the tiger","4","","",""),
array("evacuate the dance floor","4","","","")),
"f" => array(
array("free online games","0","2","3",""),
array("facebook","0","2","",""),
array("facebook login","0","2","",""),
array("food network","0","2","",""),
array("fox news","0","2","",""),
array("firefox","0","2","",""),
array("fedex","0","2","",""),
array("family guy","1","4","",""),
array("flowers","1","3","",""),
array("fandango","0","","",""),
array("forever 21","0","","",""),
array("funbrain","0","","",""),
array("final fantasy xiii","1","","",""),
array("flash drive","1","","",""),
array("fallout 3","1","","",""),
array("flip video","1","","",""),
array("food inc","1","","",""),
array("flip","1","","",""),
array("final fantasy","1","","",""),
array("food processor","1","","",""),
array("fafsa","2","","",""),
array("ford","2","","",""),
array("fantasy football","2","","",""),
array("free ringtones","3","","",""),
array("free games","3","","",""),
array("free music downloads","3","","",""),
array("find people","3","","",""),
array("free ecards","3","","",""),
array("free people search","3","","",""),
array("free samples","3","","",""),
array("free credit report","3","","",""),
array("fireflies","4","","",""),
array("fireflies owl city","4","","",""),
array("funny video","4","","",""),
array("funny","4","","",""),
array("fred","4","","",""),
array("funny accidents","4","","",""),
array("forever","4","","",""),
array("forever drake lil wayne","4","","",""),
array("funny cats","4","","","")),
"g" => array(
array("games","0","2","3",""),
array("glee","0","1","4",""),
array("gmail","0","2","",""),
array("google maps","0","2","",""),
array("google earth","0","2","",""),
array("google","2","4","",""),
array("gap","2","3","",""),
array("google.com","0","","",""),
array("gamestop","0","","",""),
array("google translate","0","","",""),
array("google wave","0","","",""),
array("google chrome","0","","",""),
array("gps","1","","",""),
array("game change","1","","",""),
array("god of war 3","1","","",""),
array("garmin","1","","",""),
array("guitar","1","","",""),
array("god of war","1","","",""),
array("garmin gps","1","","",""),
array("gift card","1","","",""),
array("guitar hero","1","","",""),
array("google search","2","","",""),
array("google homepage","2","","",""),
array("greeting cards","2","","",""),
array("guitar tabs","2","","",""),
array("global warming","3","","",""),
array("gnc","3","","",""),
array("gout","3","","",""),
array("gucci","3","","",""),
array("gay","3","","",""),
array("genital warts","3","","",""),
array("game","3","","",""),
array("grocery coupons","3","","",""),
array("gummy bear song","4","","",""),
array("green day","4","","",""),
array("glee don't stop believe","4","","",""),
array("grammy awards 2010","4","","",""),
array("green day 21 guns","4","","",""),
array("gangsta luv","4","","",""),
array("guns n roses","4","","",""),
array("ghost","4","","","")),
"h" => array(
array("home depot","0","2","3",""),
array("hotmail","0","2","",""),
array("haiti","0","4","",""),
array("hotels.com","0","3","",""),
array("harry potter","1","2","",""),
array("halo","1","4","",""),
array("honda","2","3","",""),
array("halloween costumes","2","3","",""),
array("hotels","2","3","",""),
array("hulu","0","","",""),
array("hollister","0","","",""),
array("hobby lobby","0","","",""),
array("hp","0","","",""),
array("horoscope","0","","",""),
array("harbor freight","0","","",""),
array("hdmi cable","1","","",""),
array("headphones","1","","",""),
array("heavy rain","1","","",""),
array("humidifier","1","","",""),
array("hello kitty","1","","",""),
array("hard drive","1","","",""),
array("hdmi","1","","",""),
array("heart rate monitor","1","","",""),
array("horoscopes","2","","",""),
array("hi5","2","","",""),
array("holiday inn","2","","",""),
array("hsbc","2","","",""),
array("how much should i weigh","3","","",""),
array("herpes","3","","",""),
array("hpv","3","","",""),
array("how to kiss","3","","",""),
array("how to write a resume","3","","",""),
array("hannah montana","4","","",""),
array("happy tree friends","4","","",""),
array("hard rihanna","4","","",""),
array("haiti earthquake","4","","",""),
array("how low can you go ludacris","4","","",""),
array("hotel room service","4","","",""),
array("halo beyonce","4","","",""),
array("how to jerk","4","","","")),
"i" => array(
array("iphone","0","1","2","3"),
array("itunes","0","2","3",""),
array("ipod touch","0","1","3",""),
array("ipod","1","2","3",""),
array("imdb","0","2","",""),
array("ikea","0","2","",""),
array("irs","0","2","",""),
array("internet explorer","2","3","",""),
array("itunes download","0","","",""),
array("inspirational quotes","0","","",""),
array("isohunt","0","","",""),
array("ikea usa","0","","",""),
array("ipad","1","","",""),
array("ipod nano","1","","",""),
array("iphone 3gs","1","","",""),
array("itouch","1","","",""),
array("iphone case","1","","",""),
array("ipod touch 3rd generation","1","","",""),
array("ipod touch case","1","","",""),
array("ign","2","","",""),
array("imeem","2","","",""),
array("internal revenue service","2","","",""),
array("iq test","3","","",""),
array("italy","3","","",""),
array("iq tests","3","","",""),
array("images","3","","",""),
array("ireland","3","","",""),
array("i gotta feeling","4","","",""),
array("iyaz replay","4","","",""),
array("i can transform ya chris brown","4","","",""),
array("iron man 2 trailer","4","","",""),
array("im on a boat","4","","",""),
array("ice cream paint job","4","","",""),
array("iron man 2","4","","",""),
array("i got a feeling black eyed peas","4","","",""),
array("in my head jason derulo","4","","",""),
array("im yours","4","","","")),
"j" => array(
array("jersey shore","0","1","4",""),
array("jokes","0","2","3",""),
array("jobs","0","2","3",""),
array("jcpenney","0","2","",""),
array("jet blue","0","3","",""),
array("justin bieber","0","4","",""),
array("java","2","3","",""),
array("justin tv","0","","",""),
array("joann fabrics","0","","",""),
array("jimmy johns","0","","",""),
array("jaimee grubbs","0","","",""),
array("jillian michaels","1","","",""),
array("jewelry","1","","",""),
array("john mayer","1","","",""),
array("juicer","1","","",""),
array("juicy couture","1","","",""),
array("just dance wii","1","","",""),
array("julia child","1","","",""),
array("james patterson","1","","",""),
array("jewelry box","1","","",""),
array("jessica simpson","2","","",""),
array("jessica alba","2","","",""),
array("jennifer lopez","2","","",""),
array("jaycee dugard","2","","",""),
array("jennifer garner","2","","",""),
array("jennifer aniston","2","","",""),
array("job search","3","","",""),
array("jordans","3","","",""),
array("jc penney","3","","",""),
array("jc penny","3","","",""),
array("jeep","3","","",""),
array("john mccain","3","","",""),
array("justin bieber one time","4","","",""),
array("jay z","4","","",""),
array("justin timberlake","4","","",""),
array("jason derulo","4","","",""),
array("jay sean","4","","",""),
array("jonas brothers","4","","",""),
array("jay sean down","4","","",""),
array("justin bieber love me","4","","","")),
"k" => array(
array("kmart","0","2","3",""),
array("kohls","0","3","",""),
array("kelly blue book","0","3","",""),
array("kayak","0","3","",""),
array("kim kardashian","0","2","",""),
array("kelly clarkson","2","4","",""),
array("kbb","2","3","",""),
array("kay jewelers","0","","",""),
array("kroger","0","","",""),
array("kinkos","0","","",""),
array("kesha","0","","",""),
array("kristen stewart","0","","",""),
array("kindle","1","","",""),
array("keurig","1","","",""),
array("kindle 2","1","","",""),
array("kindle books","1","","",""),
array("k cups","1","","",""),
array("kindle cover","1","","",""),
array("kindle dx","1","","",""),
array("kodak zi8","1","","",""),
array("keyboard","1","","",""),
array("keurig coffee maker","1","","",""),
array("kelley blue book","2","","",""),
array("kohl's","2","","",""),
array("kara dioguardi","2","","",""),
array("kazaa","2","","",""),
array("keira knightley","2","","",""),
array("katie holmes","2","","",""),
array("kijiji","3","","",""),
array("kohls.com","3","","",""),
array("kayak.com","3","","",""),
array("kia","3","","",""),
array("kmart.com","3","","",""),
array("keisha tik tok","4","","",""),
array("katy perry","4","","",""),
array("kanye west","4","","",""),
array("kiss","4","","",""),
array("kid cudi","4","","",""),
array("kiss me thru the phone","4","","",""),
array("kesha blah blah blah","4","","",""),
array("kings of leon","4","","",""),
array("keri hilson","4","","","")),
"l" => array(
array("lady gaga","0","1","4",""),
array("limewire","0","2","3",""),
array("lyrics","0","2","3",""),
array("lil wayne","1","3","4",""),
array("lowes","0","3","",""),
array("lost","1","2","",""),
array("love poems","2","3","",""),
array("las vegas","2","3","",""),
array("lands end","0","","",""),
array("love quotes","0","","",""),
array("linkedin","0","","",""),
array("louis vuitton","0","","",""),
array("ll zamenhof","0","","",""),
array("lady gaga hermaphrodite","0","","",""),
array("laptop","1","","",""),
array("lego","1","","",""),
array("laptop computer","1","","",""),
array("lego star wars","1","","",""),
array("luggage","1","","",""),
array("lady antebellum","1","","",""),
array("lcd tv","1","","",""),
array("lindsay lohan","2","","",""),
array("lindsey vonn","2","","",""),
array("lowe's","2","","",""),
array("launch","2","","",""),
array("lottery","2","","",""),
array("lingerie","3","","",""),
array("love","3","","",""),
array("loans","3","","",""),
array("lyrics to songs","3","","",""),
array("lady gaga bad romance","4","","",""),
array("lady gaga paparazzi","4","","",""),
array("lady gaga poker face","4","","",""),
array("linkin park","4","","",""),
array("love story","4","","",""),
array("lil wayne no ceiling","4","","",""),
array("lady gaga telephone","4","","",""),
array("leona lewis","4","","","")),
"m" => array(
array("maps","0","2","3",""),
array("music","2","3","4",""),
array("myspace","0","2","",""),
array("mapquest","0","2","",""),
array("msn","0","2","",""),
array("miniclip","0","2","",""),
array("modern warfare 2","1","4","",""),
array("michael jackson","1","4","",""),
array("movies","2","3","",""),
array("macys","0","","",""),
array("mapquest driving directions","0","","",""),
array("mortgage calculator","0","","",""),
array("michaels","0","","",""),
array("msnbc","0","","",""),
array("mass effect 2","1","","",""),
array("mp3 player","1","","",""),
array("macbook","1","","",""),
array("mass effect","1","","",""),
array("macbook pro","1","","",""),
array("mag","1","","",""),
array("mp3","1","","",""),
array("mario kart wii","1","","",""),
array("mail","2","","",""),
array("megan fox","2","","",""),
array("macy's","2","","",""),
array("myspace.com","3","","",""),
array("myspace layouts","3","","",""),
array("match.com","3","","",""),
array("math","3","","",""),
array("music videos","3","","",""),
array("macy","3","","",""),
array("map","3","","",""),
array("miley cyrus","4","","",""),
array("mariah carey","4","","",""),
array("miley cyrus party in the usa","4","","",""),
array("metallica","4","","",""),
array("meet me halfway","4","","",""),
array("michael jackson billie jean","4","","",""),
array("meet me halfway black eyed peas","4","","","")),
"n" => array(
array("netflix","0","2","3",""),
array("nordstrom","0","2","3",""),
array("new moon","0","1","4",""),
array("news","0","2","3",""),
array("northwest airlines","0","2","",""),
array("nascar","2","3","",""),
array("nissan","2","3","",""),
array("naruto","2","4","",""),
array("nfl.com","0","","",""),
array("new york times","0","","",""),
array("nick jr","0","","",""),
array("nbc","0","","",""),
array("nickelodeon","0","","",""),
array("netbook","1","","",""),
array("nintendo ds","1","","",""),
array("nintendo wii","1","","",""),
array("new moon dvd","1","","",""),
array("nexus one","1","","",""),
array("nikon d90","1","","",""),
array("nintendo dsi","1","","",""),
array("nokia n900","1","","",""),
array("nikon d5000","1","","",""),
array("nfl","2","","",""),
array("nokia","2","","",""),
array("nba","2","","",""),
array("name meanings","3","","",""),
array("nike","3","","",""),
array("names","3","","",""),
array("nada","3","","",""),
array("new york","3","","",""),
array("nicki minaj","4","","",""),
array("nigahiga","4","","",""),
array("nickelback","4","","",""),
array("naturally selena gomez","4","","",""),
array("naruto shippuden","4","","",""),
array("nobody","4","","",""),
array("new boyz","4","","",""),
array("new york jay z","4","","","")),
"o" => array(
array("office depot","0","2","3",""),
array("overstock","0","2","3",""),
array("orbitz","0","2","3",""),
array("old navy","0","2","3",""),
array("online games","0","2","3",""),
array("office max","0","2","3",""),
array("owl city","0","1","4",""),
array("oprah","0","2","",""),
array("online dictionary","2","3","",""),
array("olive garden","0","","",""),
array("open office","0","","",""),
array("oakley","1","","",""),
array("ooma","1","","",""),
array("otterbox","1","","",""),
array("one tree hill","1","","",""),
array("outliers","1","","",""),
array("office 2007","1","","",""),
array("oakley sunglasses","1","","",""),
array("office chair","1","","",""),
array("on the brink","1","","",""),
array("olympics schedule","2","","",""),
array("orkut","2","","",""),
array("obama","3","","",""),
array("overstock.com","3","","",""),
array("orbitz.com","3","","",""),
array("owl city fireflies","4","","",""),
array("one time","4","","",""),
array("one time justin bieber","4","","",""),
array("one less lonely justin bieber","4","","",""),
array("one republic all the right moves","4","","",""),
array("one less lonely girl- justin bieber","4","","",""),
array("one time lyrics","4","","",""),
array("obsessed mariah carey","4","","",""),
array("owl city vanilla twilight","4","","","")),
"p" => array(
array("pizza hut","0","2","3",""),
array("paypal","0","2","3",""),
array("photobucket","0","2","",""),
array("pottery barn","0","2","",""),
array("people search","2","3","",""),
array("poems","2","3","",""),
array("priceline","2","3","",""),
array("pregnancy","2","3","",""),
array("pandora","0","","",""),
array("poptropica","0","","",""),
array("papa johns","0","","",""),
array("people of walmart","0","","",""),
array("pirate bay","0","","",""),
array("party city","0","","",""),
array("ps3","1","","",""),
array("playstation 3","1","","",""),
array("psp","1","","",""),
array("p90x","1","","",""),
array("ps3 games","1","","",""),
array("percy jackson","1","","",""),
array("ps3 console","1","","",""),
array("portable dvd player","1","","",""),
array("pokemon","1","","",""),
array("psp go","1","","",""),
array("pogo","2","","",""),
array("powerball","2","","",""),
array("prom dresses","3","","",""),
array("people finder","3","","",""),
array("proxy","3","","",""),
array("priceline.com","3","","",""),
array("pants on the ground","4","","",""),
array("party in the usa","4","","",""),
array("pitbull","4","","",""),
array("pink","4","","",""),
array("paparazzi lady gaga","4","","",""),
array("poker face","4","","",""),
array("paramore","4","","",""),
array("poker face lady gaga","4","","",""),
array("party in the usa lyrics","4","","",""),
array("pitbull i know you want me","4","","","")),
"q" => array(
array("quotes","0","2","3",""),
array("qvc","0","2","3",""),
array("quicktime","0","2","3",""),
array("quest diagnostics","0","2","",""),
array("quiznos","0","2","",""),
array("quicken","0","1","",""),
array("quickbooks","1","3","",""),
array("queen","1","4","",""),
array("quizzes","2","3","",""),
array("qwest","2","3","",""),
array("quotes about life","0","","",""),
array("quotes about love","0","","",""),
array("quotes to live by","0","","",""),
array("quotes and sayings","0","","",""),
array("quicken 2010","1","","",""),
array("quickbooks pro 2010","1","","",""),
array("quiksilver","1","","",""),
array("quicken deluxe 2010","1","","",""),
array("queer as folk","1","","",""),
array("quick trim","1","","",""),
array("quicken for mac","1","","",""),
array("qantas","2","","",""),
array("query string","2","","",""),
array("quizilla","2","","",""),
array("questions","3","","",""),
array("quest","3","","",""),
array("quit smoking","3","","",""),
array("quiz","3","","",""),
array("queen bohemian rhapsody","4","","",""),
array("quest crew","4","","",""),
array("queen we will rock you","4","","",""),
array("queen don't stop me now","4","","",""),
array("queens of the stone age","4","","",""),
array("queen i want to break free","4","","",""),
array("queen somebody to love","4","","",""),
array("que tengo que hacer","4","","",""),
array("queen we are the champions","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("eminem","1","2","4",""),
array("espn","0","2","",""),
array("ed hardy","1","3","",""),
array("ecards","2","3","",""),
array("express","0","","",""),
array("english to spanish translation","0","","",""),
array("elf yourself","0","","",""),
array("etsy","0","","",""),
array("ebay motors","0","","",""),
array("evite","0","","",""),
array("easter 2010","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("electric blanket","1","","",""),
array("external hard drive 1tb","1","","",""),
array("entourage","1","","",""),
array("ethernet cable","1","","",""),
array("emma","1","","",""),
array("enterprise car rental","2","","",""),
array("ellen degeneres","2","","",""),
array("easyjet","2","","",""),
array("evangeline lilly","2","","",""),
array("eva longoria","2","","",""),
array("ebay.com","3","","",""),
array("eharmony","3","","",""),
array("expedia.com","3","","",""),
array("eharmony.com","3","","",""),
array("earth day 2009","3","","",""),
array("engagement rings","3","","",""),
array("empire state of mind","4","","",""),
array("eminem beautiful","4","","",""),
array("enrique iglesias","4","","",""),
array("evanescence","4","","",""),
array("empire state of mind jay z","4","","",""),
array("elvis presley","4","","",""),
array("eminem lose yourself","4","","",""),
array("eye of the tiger","4","","",""),
array("evacuate the dance floor","4","","","")),
"s" => array(
array("sears","0","2","3",""),
array("staples","0","2","3",""),
array("southwest airlines","0","2","",""),
array("skype","0","2","",""),
array("sprint","0","2","",""),
array("shoes","1","3","",""),
array("song lyrics","2","3","",""),
array("shakira","2","4","",""),
array("spanish translation","0","","",""),
array("sams club","0","","",""),
array("sports authority","0","","",""),
array("sparknotes","0","","",""),
array("sesame street","0","","",""),
array("sony cybershot","1","","",""),
array("sade","1","","",""),
array("star trek","1","","",""),
array("star wars","1","","",""),
array("snow blower","1","","",""),
array("sd card","1","","",""),
array("sunglasses","1","","",""),
array("super mario bros wii","1","","",""),
array("sony reader","1","","",""),
array("sony","2","","",""),
array("sudoku","2","","",""),
array("school closings","2","","",""),
array("swine flu","3","","",""),
array("singlesnet.com","3","","",""),
array("science fair projects","3","","",""),
array("student loans","3","","",""),
array("search engines","3","","",""),
array("sears.com","3","","",""),
array("selena gomez","4","","",""),
array("susan boyle","4","","",""),
array("soulja boy","4","","",""),
array("single ladies","4","","",""),
array("shane dawson","4","","",""),
array("sweet dreams beyonce","4","","",""),
array("snoop dogg","4","","",""),
array("shakira she wolf","4","","",""),
array("selena gomez naturally","4","","","")),
"t" => array(
array("toys r us","0","2","3",""),
array("travelocity","0","2","3",""),
array("target","0","2","",""),
array("tv guide","0","2","",""),
array("twilight","1","3","",""),
array("turbo tax","1","3","",""),
array("toyota","2","3","",""),
array("tattoos","2","3","",""),
array("tiger woods","0","","",""),
array("twitter","0","","",""),
array("thesaurus","0","","",""),
array("translator","0","","",""),
array("tmz","0","","",""),
array("tmobile","0","","",""),
array("true blood","1","","",""),
array("tv","1","","",""),
array("this is it","1","","",""),
array("turbotax 2009","1","","",""),
array("the help","1","","",""),
array("the hangover","1","","",""),
array("true blood season 2","1","","",""),
array("the office","1","","",""),
array("ticketmaster","2","","",""),
array("t-mobile","2","","",""),
array("tesco","2","","",""),
array("tanith belbin","2","","",""),
array("tires","3","","",""),
array("tattoo","3","","",""),
array("tattoo designs","3","","",""),
array("travel","3","","",""),
array("tik tok","4","","",""),
array("taylor swift","4","","",""),
array("tik tok keisha","4","","",""),
array("taylor swift you belong with me","4","","",""),
array("tick tock","4","","",""),
array("telephone lady gaga","4","","",""),
array("the climb","4","","",""),
array("tick tock keisha","4","","",""),
array("tom and jerry","4","","",""),
array("tie me down","4","","","")),
"u" => array(
array("us airways","0","2","3",""),
array("ufc","0","2","4",""),
array("usps","0","2","",""),
array("ups","0","2","",""),
array("united airlines","0","2","",""),
array("uggs","1","3","",""),
array("usher","1","4","",""),
array("used cars","2","3","",""),
array("ups tracking","0","","",""),
array("urban outfitters","0","","",""),
array("urban dictionary","0","","",""),
array("usps tracking","0","","",""),
array("utorrent","0","","",""),
array("up","1","","",""),
array("uncharted 2","1","","",""),
array("usb flash drive","1","","",""),
array("unlocked cell phones","1","","",""),
array("ugg boots","1","","",""),
array("usb hub","1","","",""),
array("under armour","1","","",""),
array("umbrella","1","","",""),
array("utusan malaysia","2","","",""),
array("u tube","2","","",""),
array("univision","2","","",""),
array("usaa","2","","",""),
array("used books","3","","",""),
array("used cars for sale","3","","",""),
array("university of phoenix","3","","",""),
array("utube","3","","",""),
array("us air","3","","",""),
array("us cellular","3","","",""),
array("universal joint","3","","",""),
array("u2","4","","",""),
array("usher papers","4","","",""),
array("ufo","4","","",""),
array("use somebody","4","","",""),
array("unforgivable","4","","",""),
array("use somebody kings of leon","4","","",""),
array("up in the air trailer","4","","",""),
array("ufc knockouts","4","","","")),
"v" => array(
array("verizon wireless","0","2","3",""),
array("verizon","0","2","3",""),
array("victoria secret","0","3","",""),
array("vampire diaries","0","1","",""),
array("vh1","0","2","",""),
array("vampire weekend","1","4","",""),
array("vanessa hudgens","2","4","",""),
array("vonage","2","3","",""),
array("vlc","0","","",""),
array("verizon.net","0","","",""),
array("virgin america","0","","",""),
array("value city furniture","0","","",""),
array("victoria's secret coupons","0","","",""),
array("valentines day gifts","1","","",""),
array("vacuum cleaner","1","","",""),
array("valentines day","1","","",""),
array("valentines day gifts for him","1","","",""),
array("video camera","1","","",""),
array("verizon cell phones","1","","",""),
array("vera bradley","1","","",""),
array("vibratores for women","1","","",""),
array("video","2","","",""),
array("valentine's day","2","","",""),
array("victoria's secret","2","","",""),
array("volkswagen","2","","",""),
array("vodafone","2","","",""),
array("vıdeos","3","","",""),
array("virgin mobile","3","","",""),
array("verizon.com","3","","",""),
array("volcanoes","3","","",""),
array("viagra","3","","",""),
array("verizonwireless.com","3","","",""),
array("video phone","4","","",""),
array("valentines day trailer","4","","",""),
array("video phone beyonce official video","4","","",""),
array("vanilla twilight","4","","",""),
array("various artists","4","","",""),
array("veer","4","","",""),
array("vanilla twilight owl city","4","","",""),
array("veer songs","4","","","")),
"w" => array(
array("weather","0","2","3",""),
array("white pages","0","2","3",""),
array("walgreens","0","2","3",""),
array("wikipedia","0","2","",""),
array("webkinz","0","2","",""),
array("wells fargo","0","2","",""),
array("wii","1","3","",""),
array("wii fit","1","3","",""),
array("wwe","2","4","",""),
array("walmart","0","","",""),
array("www.facebook.com","0","","",""),
array("watch-movies.net","0","","",""),
array("web md","0","","",""),
array("wii games","1","","",""),
array("wii console","1","","",""),
array("wii fit plus","1","","",""),
array("windows 7","1","","",""),
array("wii fit plus with balance board","1","","",""),
array("wireless router","1","","",""),
array("watches","1","","",""),
array("wii remote","1","","",""),
array("wal mart","2","","",""),
array("webmd","2","","",""),
array("wachovia","2","","",""),
array("what does my name mean","3","","",""),
array("what is global warming","3","","",""),
array("wedding dresses","3","","",""),
array("what is love","3","","",""),
array("weight watchers","3","","",""),
array("whatcha say","4","","",""),
array("whatcha say jason derulo","4","","",""),
array("wisin y yandel","4","","",""),
array("whitney houston","4","","",""),
array("whatcha say lyrics","4","","",""),
array("westlife","4","","",""),
array("wwe raw","4","","",""),
array("we are the world","4","","",""),
array("wedding dance","4","","","")),
"x" => array(
array("xbox 360","0","1","2","3"),
array("xm radio","0","2","3",""),
array("xbox live","0","1","2",""),
array("xanax","0","2","3",""),
array("xbox 360 games","0","1","3",""),
array("xbox 720","0","4","",""),
array("xbox","1","3","",""),
array("xbox cheats","2","3","",""),
array("xkcd","0","","",""),
array("xcel energy","0","","",""),
array("xm radio online","0","","",""),
array("xbmc","0","","",""),
array("xbox 360 console","1","","",""),
array("xbox 360 elite","1","","",""),
array("xbox 360 controller","1","","",""),
array("xbox 360 wireless adapter","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("xbox 360 headset","1","","",""),
array("xhamster","2","","",""),
array("xvid","2","","",""),
array("xbox games","2","","",""),
array("xerox","2","","",""),
array("xenical","2","","",""),
array("xbox 360 cheats","3","","",""),
array("xyzal","3","","",""),
array("xbox360","3","","",""),
array("xango","3","","",""),
array("x factor 2009","4","","",""),
array("x factor","4","","",""),
array("xxl movie","4","","",""),
array("xzibit","4","","",""),
array("x factor 2009 auditions","4","","",""),
array("xatzigiannis","4","","",""),
array("xmas songs","4","","",""),
array("x men","4","","","")),
"y" => array(
array("youtube","0","2","4",""),
array("yahoo mail","0","2","3",""),
array("yellow pages","0","2","3",""),
array("yahoo","0","2","",""),
array("yahoo maps","0","2","",""),
array("yahoo messenger","0","2","",""),
array("young money","1","4","",""),
array("youtube music","0","","",""),
array("yahoo answers","0","","",""),
array("yahoo finance","0","","",""),
array("yelp","0","","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yoga dvd","1","","",""),
array("yo gabba gabba","1","","",""),
array("yarn","1","","",""),
array("yugioh cards","1","","",""),
array("your baby can read","1","","",""),
array("yugioh","1","","",""),
array("yeasayer","1","","",""),
array("yahoo search","2","","",""),
array("youtube video","2","","",""),
array("yamaha","2","","",""),
array("yahoo games","2","","",""),
array("yellowpages.com","3","","",""),
array("yellow pages.com","3","","",""),
array("yellow book","3","","",""),
array("yellowbook.com","3","","",""),
array("yeast infection","3","","",""),
array("yellowbook","3","","",""),
array("yaz","3","","",""),
array("yahoo.com","3","","",""),
array("you belong with me","4","","",""),
array("you belong with me taylor swift","4","","",""),
array("your a jerk","4","","",""),
array("young jeezy","4","","",""),
array("young money bedrock","4","","",""),
array("you belong with me taylor swift lyrics","4","","",""),
array("your love is my drug","4","","",""),
array("your a jerk new boyz","4","","","")),
"z" => array(
array("zune","0","1","2","3"),
array("zappos","0","2","3",""),
array("zip codes","0","2","3",""),
array("zodiac signs","0","2","3",""),
array("zales","0","2","3",""),
array("zillow","0","2","",""),
array("zhu zhu pets","0","1","",""),
array("zombieland","1","4","",""),
array("zumba","1","4","",""),
array("zac efron","2","4","",""),
array("zuma","2","3","",""),
array("zip codes by city","0","","",""),
array("zumiez","0","","",""),
array("zero punctuation","0","","",""),
array("zune hd","1","","",""),
array("zhu zhu","1","","",""),
array("zippo","1","","",""),
array("zelda","1","","",""),
array("zumba fitness dvd","1","","",""),
array("zi8","1","","",""),
array("zip code lookup","2","","",""),
array("zip code finder","2","","",""),
array("zwinky","3","","",""),
array("zappos.com","3","","",""),
array("zwinky.com","3","","",""),
array("zip code","3","","",""),
array("zombie","4","","",""),
array("zz top","4","","",""),
array("zac brown band","4","","",""),
array("zach galifianakis","4","","",""),
array("zombieland trailer","4","","",""),
array("zeitgeist","4","","",""),
array("zidane","4","","","")));
?>