<?php $topResults = array(
"a" => array(
array("at&t","2","3","",""),
array("asus transformer prime","1","","",""),
array("amazon prime","1","","",""),
array("angry birds","1","","",""),
array("apple tv","1","","",""),
array("airsoft guns","1","","",""),
array("android tablet","1","","",""),
array("adele","1","","",""),
array("adidas","1","","",""),
array("assassins creed revelations","1","","",""),
array("apple","1","","",""),
array("amazon","2","","",""),
array("aol","2","","",""),
array("arsenio hall","2","","",""),
array("anne hathaway","2","","",""),
array("autotrader","2","","",""),
array("ask jeeves","2","","",""),
array("american idol","2","","",""),
array("american airlines","2","","",""),
array("aretha franklin","2","","",""),
array("alabama football","3","","",""),
array("airline baby ban","3","","",""),
array("annalynne mccord","3","","",""),
array("amazon.com","3","","",""),
array("apartments for rent","3","","",""),
array("att","3","","",""),
array("answers.com","3","","",""),
array("apple store","3","","",""),
array("airline tickets","3","","","")),
"b" => array(
array("best buy","2","3","",""),
array("bank of america","2","3","",""),
array("barnes and noble","2","3","",""),
array("bed bath and beyond","2","3","",""),
array("beats by dre","1","","",""),
array("blackberry","1","","",""),
array("battlefield 3","1","","",""),
array("beats","1","","",""),
array("bose","1","","",""),
array("blu ray player","1","","",""),
array("blackberry playbook","1","","",""),
array("boots","1","","",""),
array("bluetooth headset","1","","",""),
array("backpack","1","","",""),
array("beyonce","2","","",""),
array("blank","2","","",""),
array("brandi glanville","2","","",""),
array("bing","2","","",""),
array("britney spears","2","","",""),
array("belle starr","2","","",""),
array("billy the kid","3","","",""),
array("bam margera","3","","",""),
array("bathroom cleaning tips","3","","",""),
array("baby names","3","","",""),
array("bmi calculator","3","","",""),
array("babies r us","3","","","")),
"c" => array(
array("craigslist","2","3","",""),
array("camera","1","","",""),
array("coffee maker","1","","",""),
array("calendars 2012 wall calendars","1","","",""),
array("canon t3i","1","","",""),
array("call of duty modern warfare 3","1","","",""),
array("christmas tree","1","","",""),
array("crocs","1","","",""),
array("coach","1","","",""),
array("canon","1","","",""),
array("christmas lights","1","","",""),
array("chase","2","","",""),
array("cnn","2","","",""),
array("costco","2","","",""),
array("capital one","2","","",""),
array("comcast","2","","",""),
array("continental airlines","2","","",""),
array("cartoon network","2","","",""),
array("charlie sheen","2","","",""),
array("club penguin","2","","",""),
array("coachella","3","","",""),
array("coachella 2012","3","","",""),
array("chris hansen","3","","",""),
array("cheap airline tickets","3","","",""),
array("craigslist.org","3","","",""),
array("calculator","3","","",""),
array("cheap flights","3","","",""),
array("coupons","3","","",""),
array("charlotte russe","3","","","")),
"d" => array(
array("dictionary","2","3","",""),
array("delta airlines","2","3","",""),
array("digital camera","1","","",""),
array("dvd player","1","","",""),
array("diablo 3","1","","",""),
array("doctor who","1","","",""),
array("diapers","1","","",""),
array("dexter","1","","",""),
array("ds games","1","","",""),
array("digital photo frame","1","","",""),
array("dyson","1","","",""),
array("downton abbey","1","","",""),
array("demi moore","2","","",""),
array("dick clark","2","","",""),
array("disney channel","2","","",""),
array("dakota fanning","2","","",""),
array("debra messing","2","","",""),
array("dancing with the stars","2","","",""),
array("dump godaddy day","2","","",""),
array("dish network","2","","",""),
array("doomsday clock","3","","",""),
array("david crowder band","3","","",""),
array("dixville notch","3","","",""),
array("dictionary online","3","","",""),
array("definitions.com","3","","",""),
array("driving directions","3","","",""),
array("direct tv","3","","",""),
array("dictionary definitions","3","","","")),
"e" => array(
array("ebay","2","3","",""),
array("expedia","2","3","",""),
array("external hard drive","1","","",""),
array("earbuds","1","","",""),
array("earphones","1","","",""),
array("electric blanket","1","","",""),
array("elf on the shelf","1","","",""),
array("earrings","1","","",""),
array("ebooks","1","","",""),
array("espresso machine","1","","",""),
array("elliptical","1","","",""),
array("ethernet cable","1","","",""),
array("elly mae clampett","2","","",""),
array("espn","2","","",""),
array("eva mendes","2","","",""),
array("emily watson","2","","",""),
array("ellen barkin","2","","",""),
array("elin nordegren","2","","",""),
array("eva longoria","2","","",""),
array("enterprise car rental","2","","",""),
array("elizabeth taylor","3","","",""),
array("emma watson","3","","",""),
array("erin brady","3","","",""),
array("ebay motors","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("extreme couponing","3","","",""),
array("earliest pregnancy sign","3","","","")),
"f" => array(
array("facebook","2","3","",""),
array("free online games","2","3","",""),
array("free kindle books","1","","",""),
array("flash drive","1","","",""),
array("food processor","1","","",""),
array("fifa 12","1","","",""),
array("flashlight","1","","",""),
array("final fantasy xiii-2","1","","",""),
array("floor lamp","1","","",""),
array("fossil","1","","",""),
array("free books","1","","",""),
array("futon","1","","",""),
array("friendster","2","","",""),
array("fox news","2","","",""),
array("food network","2","","",""),
array("fedex","2","","",""),
array("ford","2","","",""),
array("frances bean cobain","2","","",""),
array("firefox","2","","",""),
array("fantasy football","2","","",""),
array("free pinewood derby templates","3","","",""),
array("federal w 4 form","3","","",""),
array("free music downloads","3","","",""),
array("facebook login","3","","",""),
array("free ringtones","3","","",""),
array("free credit report","3","","",""),
array("free games","3","","",""),
array("free resume form to print","3","","","")),
"g" => array(
array("games","1","2","3",""),
array("google","2","3","",""),
array("gmail","2","3","",""),
array("google search","2","3","",""),
array("google maps","2","3","",""),
array("gift card","1","","",""),
array("gps","1","","",""),
array("galaxy nexus","1","","",""),
array("game of thrones","1","","",""),
array("galaxy s2","1","","",""),
array("garmin","1","","",""),
array("guitar","1","","",""),
array("galaxy tab","1","","",""),
array("galaxy note","1","","",""),
array("goo","2","","",""),
array("gaga boyfriend","2","","",""),
array("gold prices","2","","",""),
array("gold price drop","2","","",""),
array("glenn beck","2","","",""),
array("girl scout cookies","3","","",""),
array("george lucas","3","","",""),
array("good carbohydrates list","3","","",""),
array("google.com","3","","",""),
array("gnc","3","","","")),
"h" => array(
array("hotmail","2","3","",""),
array("home depot","2","3","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("hunger games","1","","",""),
array("harry potter","1","","",""),
array("humidifier","1","","",""),
array("hello kitty","1","","",""),
array("hp touchpad","1","","",""),
array("hdmi","1","","",""),
array("hard drive","1","","",""),
array("helicopter","1","","",""),
array("human barbie","2","","",""),
array("hulu","2","","",""),
array("how to tie a tie","2","","",""),
array("halle berry","2","","",""),
array("heidi montag","2","","",""),
array("hi5","2","","",""),
array("hawaii elevated train","2","","",""),
array("honda","2","","",""),
array("hostess","3","","",""),
array("honey badger","3","","",""),
array("haley joel osment","3","","",""),
array("how much should i weigh","3","","",""),
array("how to kiss","3","","",""),
array("how to get pregnant","3","","",""),
array("how many calories should i eat a day","3","","",""),
array("hotmail.com","3","","","")),
"i" => array(
array("ipad","1","3","",""),
array("iphone","1","2","",""),
array("itunes","2","3","",""),
array("irs","2","3","",""),
array("ipad 2","1","","",""),
array("ipod touch","1","","",""),
array("iphone 4s","1","","",""),
array("iphone 4s case","1","","",""),
array("ipod","1","","",""),
array("iphone 4 case","1","","",""),
array("ipad 2 case","1","","",""),
array("iphone 4","1","","",""),
array("ipad rumors","2","","",""),
array("imdb","2","","",""),
array("ikea","2","","",""),
array("internet explorer","2","","",""),
array("indeed","2","","",""),
array("isohunt","2","","",""),
array("illinois lottery","2","","",""),
array("irs 1099 tax forms","3","","",""),
array("irs tax tables 2012","3","","",""),
array("is the world going to end in 2012","3","","",""),
array("is selena gomez pregnant","3","","",""),
array("is santa claus real yes or no","3","","",""),
array("instant math answers free","3","","",""),
array("inspirational quotes","3","","","")),
"j" => array(
array("justin bieber","1","2","",""),
array("jobs","2","3","",""),
array("juicer","1","","",""),
array("just dance 3","1","","",""),
array("jewelry","1","","",""),
array("just dance 3 wii","1","","",""),
array("jewelry box","1","","",""),
array("just dance","1","","",""),
array("juicy couture","1","","",""),
array("jillian michaels","1","","",""),
array("jeans","1","","",""),
array("jennifer aniston","2","","",""),
array("justin and jessica","2","","",""),
array("jay z","2","","",""),
array("jcpenney","2","","",""),
array("jim toth","2","","",""),
array("jennifer lopez","2","","",""),
array("jessica simpson","2","","",""),
array("julianne hough","2","","",""),
array("jon huntsman","3","","",""),
array("jfk turtles","3","","",""),
array("jamie weinstein","3","","",""),
array("jcpenney.com","3","","",""),
array("justin bieber phone number for real","3","","",""),
array("justin bieber quiz","3","","",""),
array("jobs in my area","3","","",""),
array("jobs hiring in my area","3","","",""),
array("justin bieber cell number","3","","","")),
"k" => array(
array("kindle","1","3","",""),
array("katy perry","2","3","",""),
array("kmart","2","3","",""),
array("kindle fire","1","","",""),
array("kindle fire case","1","","",""),
array("keurig","1","","",""),
array("kinect","1","","",""),
array("kindle cover","1","","",""),
array("kindle fire accessories","1","","",""),
array("kindle touch","1","","",""),
array("k cups","1","","",""),
array("kindle fire cover","1","","",""),
array("kim kardashian","2","","",""),
array("kate middleton","2","","",""),
array("keith jackson","2","","",""),
array("kelley blue book","2","","",""),
array("kate gosselin","2","","",""),
array("kelly clarkson","2","","",""),
array("kimbella vanderhee","2","","",""),
array("kid cudi","2","","",""),
array("korean tv drama series","3","","",""),
array("king james bible online","3","","",""),
array("kohls","3","","",""),
array("kelly blue book","3","","",""),
array("kia","3","","",""),
array("kim kardashian and ray j full video","3","","",""),
array("kohls coupons","3","","","")),
"l" => array(
array("limewire","2","3","",""),
array("love quotes","2","3","",""),
array("laptop","1","","",""),
array("leappad","1","","",""),
array("lego","1","","",""),
array("lego star wars","1","","",""),
array("luggage","1","","",""),
array("lalaloopsy","1","","",""),
array("laptop computer","1","","",""),
array("lord of the rings","1","","",""),
array("louis vuitton","1","","",""),
array("led tv","1","","",""),
array("lady gaga","2","","",""),
array("lindsay lohan","2","","",""),
array("lowe's home improvement","2","","",""),
array("leann rimes","2","","",""),
array("lakeasha rutledge draft","2","","",""),
array("lyrics","2","","",""),
array("lowes stores","2","","",""),
array("linkedin","2","","",""),
array("lsu","3","","",""),
array("lsu football","3","","",""),
array("latest tylenol recall","3","","",""),
array("lowes","3","","",""),
array("lyrics to songs","3","","",""),
array("lingerie","3","","",""),
array("love poems","3","","",""),
array("love calculator","3","","","")),
"m" => array(
array("mapquest","2","3","",""),
array("msn","2","3","",""),
array("macbook pro","1","","",""),
array("mp3 player","1","","",""),
array("modern warfare 3","1","","",""),
array("micro sd card","1","","",""),
array("macbook air","1","","",""),
array("monster high","1","","",""),
array("mw3","1","","",""),
array("macbook","1","","",""),
array("modernist cuisine","1","","",""),
array("movies","1","","",""),
array("myspace","2","","",""),
array("mail","2","","",""),
array("mary tyler moore","2","","",""),
array("mega millions","2","","",""),
array("mariah carey","2","","",""),
array("megan fox","2","","",""),
array("minimum wage","2","","",""),
array("miley cyrus","2","","",""),
array("mitt romney","3","","",""),
array("molly sims","3","","",""),
array("martin luther king jr","3","","",""),
array("mapquest driving directions","3","","",""),
array("maps","3","","",""),
array("macys.com","3","","",""),
array("math answers","3","","",""),
array("mapquest.com","3","","","")),
"n" => array(
array("nike","1","3","",""),
array("netflix","2","3","",""),
array("nook","1","","",""),
array("nintendo 3ds","1","","",""),
array("nintendo ds","1","","",""),
array("netbook","1","","",""),
array("nook tablet","1","","",""),
array("nikon","1","","",""),
array("nikon d7000","1","","",""),
array("nba 2k12","1","","",""),
array("nikon d3100","1","","",""),
array("nfl draft 2012","2","","",""),
array("new girl scout cookie","2","","",""),
array("nick jr","2","","",""),
array("nordstrom","2","","",""),
array("nascar","2","","",""),
array("nbc sports network","2","","",""),
array("nick cannon","2","","",""),
array("news","2","","",""),
array("nba","2","","",""),
array("new hampshire primary","3","","",""),
array("neville","3","","",""),
array("nh primary","3","","",""),
array("nissan","3","","",""),
array("names and meaning","3","","",""),
array("nissan cars","3","","",""),
array("name meanings","3","","",""),
array("national weather service","3","","","")),
"o" => array(
array("old navy","2","3","",""),
array("office depot","2","3","",""),
array("online dictionary","2","3","",""),
array("otterbox iphone 4","1","","",""),
array("otterbox iphone 4s","1","","",""),
array("otterbox","1","","",""),
array("oakley","1","","",""),
array("otterbox ipod touch 4g","1","","",""),
array("otterbox ipad 2","1","","",""),
array("office chair","1","","",""),
array("opi nail polish","1","","",""),
array("oakley sunglasses","1","","",""),
array("otterbox defender iphone 4s","1","","",""),
array("oprah winfrey","2","","",""),
array("omg","2","","",""),
array("ohio earthquakes","2","","",""),
array("orbitz","2","","",""),
array("overstock","2","","",""),
array("oil prices","2","","",""),
array("olivia wilde","2","","",""),
array("one life to live full episodes","3","","",""),
array("original mapquest","3","","",""),
array("one life to live spoilers","3","","",""),
array("online pregnancy test","3","","",""),
array("ovulation calculator","3","","",""),
array("ovulation calendar","3","","",""),
array("orbitz.com","3","","","")),
"p" => array(
array("people search","2","3","",""),
array("ps3","1","","",""),
array("playstation 3","1","","",""),
array("psp","1","","",""),
array("p90x","1","","",""),
array("ps3 games","1","","",""),
array("ps3 controller","1","","",""),
array("ps vita","1","","",""),
array("playbook","1","","",""),
array("ps3 console","1","","",""),
array("prime","1","","",""),
array("pandora","2","","",""),
array("pippa middleton","2","","",""),
array("paypal","2","","",""),
array("pizza hut","2","","",""),
array("pogo","2","","",""),
array("photobucket","2","","",""),
array("priceline","2","","",""),
array("playstation vita","2","","",""),
array("poptropica","2","","",""),
array("photos","3","","",""),
array("pseb 10th class result","3","","",""),
array("printable shapes","3","","",""),
array("pregnancy week by week","3","","",""),
array("phone number lookup","3","","",""),
array("people search for free","3","","",""),
array("pregnancy calculator","3","","",""),
array("pottery barn","3","","",""),
array("put my word in a sentence","3","","","")),
"q" => array(
array("qvc","2","3","",""),
array("quotes","2","3","",""),
array("quicken","1","","",""),
array("quickbooks","1","","",""),
array("quicken 2012","1","","",""),
array("quiksilver","1","","",""),
array("quickbooks pro 2012","1","","",""),
array("quelf","1","","",""),
array("quilt","1","","",""),
array("qwirkle","1","","",""),
array("queen mattress","1","","",""),
array("queen","1","","",""),
array("queen elizabeth","2","","",""),
array("quest diagnostics","2","","",""),
array("quicktime","2","","",""),
array("queen latifah","2","","",""),
array("qwest","2","","",""),
array("quiznos","2","","",""),
array("query string","2","","",""),
array("quality inn","2","","",""),
array("questions and answers","3","","",""),
array("quest labs","3","","",""),
array("quest laboratories locations","3","","",""),
array("qvc home shopping","3","","",""),
array("quotes about life","3","","",""),
array("quotes of the day","3","","",""),
array("quotes and sayings","3","","",""),
array("quick mileage city to city","3","","","")),
"e" => array(
array("ebay","2","3","",""),
array("expedia","2","3","",""),
array("external hard drive","1","","",""),
array("earbuds","1","","",""),
array("earphones","1","","",""),
array("electric blanket","1","","",""),
array("elf on the shelf","1","","",""),
array("earrings","1","","",""),
array("ebooks","1","","",""),
array("espresso machine","1","","",""),
array("elliptical","1","","",""),
array("ethernet cable","1","","",""),
array("espn","2","","",""),
array("elly mae clampett","2","","",""),
array("eva mendes","2","","",""),
array("emily watson","2","","",""),
array("elin nordegren","2","","",""),
array("ellen barkin","2","","",""),
array("eva longoria","2","","",""),
array("enterprise car rental","2","","",""),
array("elizabeth taylor","3","","",""),
array("emma watson","3","","",""),
array("erin brady","3","","",""),
array("ebay motors","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("extreme couponing","3","","",""),
array("earliest pregnancy sign","3","","","")),
"s" => array(
array("southwest airlines","2","3","",""),
array("sears","2","3","",""),
array("skyrim","1","","",""),
array("skylanders","1","","",""),
array("samsung galaxy s2","1","","",""),
array("search amazon.com","1","","",""),
array("shoes","1","","",""),
array("star wars","1","","",""),
array("skylanders figures","1","","",""),
array("sd card","1","","",""),
array("star wars the old republic","1","","",""),
array("samsung galaxy tab 10.1","1","","",""),
array("salma hayek","2","","",""),
array("sandra bullock","2","","",""),
array("staples","2","","",""),
array("sarah palin","2","","",""),
array("savannah brinson","2","","",""),
array("scarlett johansson","2","","",""),
array("snoop dogg","2","","",""),
array("sprint","2","","",""),
array("snopes fact check","3","","",""),
array("sign in page","3","","",""),
array("state unemployment office","3","","",""),
array("scary maze game","3","","",""),
array("spanish dictionary","3","","",""),
array("spanish to english translation","3","","",""),
array("science fair projects","3","","",""),
array("spell check","3","","","")),
"t" => array(
array("target","2","3","",""),
array("toys r us","2","3","",""),
array("tablet","1","","",""),
array("tv","1","","",""),
array("the hunger games","1","","",""),
array("the help","1","","",""),
array("transformer prime","1","","",""),
array("toms","1","","",""),
array("toshiba thrive","1","","",""),
array("toys","1","","",""),
array("treadmill","1","","",""),
array("twilight","1","","",""),
array("twitter","2","","",""),
array("travelocity","2","","",""),
array("thesaurus","2","","",""),
array("tiger woods","2","","",""),
array("ticketmaster","2","","",""),
array("tmz","2","","",""),
array("taylor swift","2","","",""),
array("tagged","2","","",""),
array("the game","3","","",""),
array("the bachelor","3","","",""),
array("toronto international film festival","3","","",""),
array("translate english to spanish","3","","",""),
array("travelocity.com","3","","",""),
array("translate spanish to english","3","","",""),
array("target.com","3","","",""),
array("teen pregnancy signs","3","","","")),
"u" => array(
array("ugg boots","1","3","",""),
array("united airlines","2","3","",""),
array("us airways","2","3","",""),
array("usaa","2","3","",""),
array("used cars","2","3","",""),
array("uggs","1","","",""),
array("under armour","1","","",""),
array("uncharted 3","1","","",""),
array("usb flash drive","1","","",""),
array("unlocked cell phones","1","","",""),
array("usb hub","1","","",""),
array("uncharted","1","","",""),
array("ugg boots women","1","","",""),
array("umbrella","1","","",""),
array("usps","2","","",""),
array("ups","2","","",""),
array("upcoming","2","","",""),
array("us bank","2","","",""),
array("ufc","2","","",""),
array("univision","2","","",""),
array("uses for hydrogen peroxide","3","","",""),
array("unscramble letters","3","","",""),
array("usually","3","","",""),
array("used cars for sale in my area","3","","",""),
array("ups tracking","3","","","")),
"v" => array(
array("victoria's secret","1","2","",""),
array("verizon wireless","2","3","",""),
array("verizon","2","3","",""),
array("virgin mobile","2","3","",""),
array("van halen","2","3","",""),
array("vacuum cleaner","1","","",""),
array("vera bradley","1","","",""),
array("vans","1","","",""),
array("verizon cell phones","1","","",""),
array("vitamix","1","","",""),
array("vaporizer","1","","",""),
array("video camera","1","","",""),
array("vibratorsfor women","1","","",""),
array("vacuum","1","","",""),
array("vanessa hudgens","2","","",""),
array("victoria gotti","2","","",""),
array("victoria beckham","2","","",""),
array("vh1","2","","",""),
array("video","2","","",""),
array("vitamin d study","3","","",""),
array("video play video","3","","",""),
array("verizon.com","3","","",""),
array("verizonwireless.com","3","","",""),
array("victoria secret","3","","",""),
array("very early symptoms of pregnancy","3","","","")),
"w" => array(
array("white pages","2","3","",""),
array("wii","1","","",""),
array("wii games","1","","",""),
array("wireless router","1","","",""),
array("wii console","1","","",""),
array("watch","1","","",""),
array("wii remote","1","","",""),
array("wallet","1","","",""),
array("wireless headphones","1","","",""),
array("windows 7","1","","",""),
array("wii controller","1","","",""),
array("walmart","2","","",""),
array("weather","2","","",""),
array("wells fargo","2","","",""),
array("wikipedia","2","","",""),
array("webmd","2","","",""),
array("wwe","2","","",""),
array("walgreens","2","","",""),
array("webkinz","2","","",""),
array("weight watchers","2","","",""),
array("w 2 form 2011","3","","",""),
array("what is a thesis statement","3","","",""),
array("what is an ecosystem","3","","",""),
array("what does my last name mean","3","","",""),
array("what is the meaning of my name","3","","",""),
array("what does my name mean","3","","",""),
array("what does my dream mean","3","","",""),
array("walmart.com","3","","",""),
array("what is a hobnocker","3","","","")),
"x" => array(
array("xbox 360","1","2","3",""),
array("xbox live","1","2","",""),
array("xbox 360 console","1","3","",""),
array("xm radio","2","3","",""),
array("xbox","1","","",""),
array("xbox 360 kinect","1","","",""),
array("xbox 360 controller","1","","",""),
array("xbox 360 games","1","","",""),
array("xbox kinect","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("xbox games","1","","",""),
array("x factor winner","2","","",""),
array("x-men first class","2","","",""),
array("xvid","2","","",""),
array("xxxv full movie","2","","",""),
array("xanax","2","","",""),
array("xha","2","","",""),
array("xnxsxs","2","","",""),
array("xcel energy","3","","",""),
array("xps","3","","",""),
array("xperia","3","","",""),
array("xxl movie","3","","",""),
array("xbox 360 cheats","3","","",""),
array("xxl tv live","3","","",""),
array("xfinity.com","3","","","")),
"y" => array(
array("youtube","2","3","",""),
array("yahoo mail","2","3","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yarn","1","","",""),
array("yoga dvd","1","","",""),
array("yoga pants","1","","",""),
array("yankee candle","1","","",""),
array("young jeezy","1","","",""),
array("yo gabba gabba","1","","",""),
array("yugioh cards","1","","",""),
array("yugioh","1","","",""),
array("yahoo calendar","2","","",""),
array("yahoo sports","2","","",""),
array("yahoo answers","2","","",""),
array("yahoo weather","2","","",""),
array("yahoo bookmarks","2","","",""),
array("yahoo horoscopes","2","","",""),
array("yahoo people search","2","","",""),
array("yahoo travel","2","","",""),
array("yahoomail sign in page","3","","",""),
array("yahoo mail sign","3","","",""),
array("yahoo","3","","",""),
array("yellow pages","3","","",""),
array("yahoo mail login","3","","",""),
array("youtube videos","3","","",""),
array("youtube.com","3","","",""),
array("yellowpages.com","3","","","")),
"z" => array(
array("zumba","1","3","",""),
array("zappos","2","3","",""),
array("zip codes","2","3","",""),
array("zodiac signs","2","3","",""),
array("zelda","1","","",""),
array("zippo","1","","",""),
array("zune","1","","",""),
array("zumba wii","1","","",""),
array("zumba fitness dvd","1","","",""),
array("zumba dvd","1","","",""),
array("zelda skyward sword","1","","",""),
array("zippo lighter","1","","",""),
array("zombie","1","","",""),
array("zooey deschanel","2","","",""),
array("zsa zsa gabor","2","","",""),
array("zillow","2","","",""),
array("zoe saldana","2","","",""),
array("zombie bees","2","","",""),
array("zales","2","","",""),
array("zuma","2","","",""),
array("z beyonce baby","3","","",""),
array("zolashonda rhimes","3","","",""),
array("zinah jennings","3","","",""),
array("zip code finder","3","","",""),
array("zappos.com","3","","",""),
array("zip code lookup","3","","","")));
?>