<?php $topResults = array(
"a" => array(
array("amazon","0","2","",""),
array("aol","0","2","",""),
array("american airlines","0","2","",""),
array("addicting games","0","2","",""),
array("att","0","","",""),
array("academy","0","","",""),
array("ask","0","","",""),
array("autozone","0","","",""),
array("apple","0","","",""),
array("abc","0","","",""),
array("assassins creed brotherhood","1","","",""),
array("apple tv","1","","",""),
array("avatar","1","","",""),
array("american girl","1","","",""),
array("airsoft guns","1","","",""),
array("android tablet","1","","",""),
array("alarm clock","1","","",""),
array("archos 101","1","","",""),
array("american girl doll","1","","",""),
array("adidas","1","","",""),
array("ask jeeves","2","","",""),
array("american idol","2","","",""),
array("at&t","2","","",""),
array("autotrader","2","","",""),
array("american express","2","","",""),
array("angelina jolie","2","","",""),
array("alina kabaeva","3","","",""),
array("amanda beard","3","","",""),
array("angie harmon","3","","",""),
array("are vampires real","3","","",""),
array("answers.com","3","","",""),
array("ancestry.com","3","","",""),
array("apartments for rent","3","","",""),
array("airline tickets","3","","",""),
array("att.com","3","","",""),
array("am i pregnant quiz","3","","",""),
array("airplanes","4","","",""),
array("annoying orange","4","","",""),
array("akon","4","","",""),
array("alejandro lady gaga","4","","",""),
array("airplanes b.o.b","4","","",""),
array("a year without rain selena gomez","4","","",""),
array("antoine dodson","4","","",""),
array("alicia keys","4","","",""),
array("avril lavigne","4","","",""),
array("all i do is win","4","","","")),
"b" => array(
array("best buy","0","2","3",""),
array("bed bath and beyond","0","2","3",""),
array("bank of america","0","2","",""),
array("barnes and noble","0","2","",""),
array("blockbuster","0","2","",""),
array("babies r us","0","2","",""),
array("black friday 2010","0","3","",""),
array("britney spears","2","4","",""),
array("baby names","2","3","",""),
array("bing","0","","",""),
array("big lots","0","","",""),
array("burlington coat factory","0","","",""),
array("black ops","1","","",""),
array("blackberry","1","","",""),
array("blu ray player","1","","",""),
array("barbie","1","","",""),
array("boots","1","","",""),
array("bose","1","","",""),
array("board games","1","","",""),
array("blackberry torch","1","","",""),
array("bose headphones","1","","",""),
array("beats by dre","1","","",""),
array("blank","2","","",""),
array("bbc","2","","",""),
array("best friends animal society","3","","",""),
array("blake edwards","3","","",""),
array("bbf","3","","",""),
array("black friday ads","3","","",""),
array("black friday sales","3","","",""),
array("black friday","3","","",""),
array("bruno mars just the way you are","4","","",""),
array("billionaire","4","","",""),
array("baby justin bieber","4","","",""),
array("beyonce","4","","",""),
array("bruno mars","4","","",""),
array("bottoms up","4","","",""),
array("baby","4","","",""),
array("bottoms up trey songz","4","","",""),
array("billionaire travis mccoy","4","","","")),
"c" => array(
array("craigslist","0","2","",""),
array("chase","0","2","",""),
array("cnn","0","2","",""),
array("costco","0","2","",""),
array("capital one","0","2","",""),
array("craigslist dallas","0","","",""),
array("carmax","0","","",""),
array("cinemark","0","","",""),
array("chase online","0","","",""),
array("cbs","0","","",""),
array("call of duty black ops","1","","",""),
array("camera","1","","",""),
array("coffee maker","1","","",""),
array("christmas tree","1","","",""),
array("christmas decorations","1","","",""),
array("christmas ornaments","1","","",""),
array("canon t2i","1","","",""),
array("call of duty","1","","",""),
array("calendars","1","","",""),
array("christmas lights","1","","",""),
array("circuit city","2","","",""),
array("cingular","2","","",""),
array("cartoon network","2","","",""),
array("chat","2","","",""),
array("comcast","2","","",""),
array("captain beefheart","3","","",""),
array("christmas in washington 2010","3","","",""),
array("cleveland harbor west pierhead lighthouse","3","","",""),
array("cheap airline tickets","3","","",""),
array("calculator","3","","",""),
array("cheap flights","3","","",""),
array("coupons","3","","",""),
array("cheat codes","3","","",""),
array("cheap halloween costumes","3","","",""),
array("credit cards","3","","",""),
array("calorie counter","4","","",""),
array("california gurls katy perry","4","","",""),
array("club cant handle me flo rida","4","","",""),
array("cher lloyd","4","","",""),
array("chris brown","4","","",""),
array("chris brown deuces","4","","",""),
array("cooler than me mike posner","4","","",""),
array("charlie bit my finger","4","","",""),
array("ciara","4","","",""),
array("christina aguilera","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("dancing with the stars","0","2","",""),
array("delta airlines","2","3","",""),
array("driving directions","2","3","",""),
array("dallas morning news","0","","",""),
array("dillards","0","","",""),
array("dallas cowboys","0","","",""),
array("dominos","0","","",""),
array("dart","0","","",""),
array("dfw airport","0","","",""),
array("direct tv","0","","",""),
array("dallas arboretum","0","","",""),
array("dsi","1","","",""),
array("digital camera","1","","",""),
array("despicable me","1","","",""),
array("ds games","1","","",""),
array("dsi xl","1","","",""),
array("digital photo frame","1","","",""),
array("digital picture frame","1","","",""),
array("dvd player","1","","",""),
array("donkey kong country returns","1","","",""),
array("ds","1","","",""),
array("disney channel","2","","",""),
array("dell","2","","",""),
array("dish network","2","","",""),
array("dmv","2","","",""),
array("directv","2","","",""),
array("danica patrick","2","","",""),
array("danilo gallinari","3","","",""),
array("don van vliet","3","","",""),
array("denise richards","3","","",""),
array("definitions.com","3","","",""),
array("disneychannel.com","3","","",""),
array("does justin bieber have a girlfriend","3","","",""),
array("download free music","3","","",""),
array("dynamite taio cruz","4","","",""),
array("drake","4","","",""),
array("dj got us falling in love","4","","",""),
array("dynamite","4","","",""),
array("deuces chris brown","4","","",""),
array("deuces remix","4","","",""),
array("david guetta","4","","",""),
array("double rainbow","4","","",""),
array("dubstep","4","","",""),
array("drake find your love","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("espn","0","2","",""),
array("english to spanish translation","0","3","",""),
array("eminem","2","4","",""),
array("evite","0","","",""),
array("etsy","0","","",""),
array("express","0","","",""),
array("eecu","0","","",""),
array("eddie long","0","","",""),
array("espn3","0","","",""),
array("external hard drive","1","","",""),
array("eclipse","1","","",""),
array("epic mickey","1","","",""),
array("electric blanket","1","","",""),
array("elf on the shelf","1","","",""),
array("eclipse dvd","1","","",""),
array("earphones","1","","",""),
array("eat pray love","1","","",""),
array("earbuds","1","","",""),
array("easy bake oven","1","","",""),
array("enterprise car rental","2","","",""),
array("elin nordegren","2","","",""),
array("ecards","2","","",""),
array("ebay motors","2","","",""),
array("emma watson","2","","",""),
array("eva longoria","2","","",""),
array("eastern washington university","3","","",""),
array("earle herrera","3","","",""),
array("eastern washington","3","","",""),
array("ebay.com","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("expedia.com","3","","",""),
array("engagement rings","3","","",""),
array("eminem not afraid","4","","",""),
array("eminem love the way you lie","4","","",""),
array("eminem no love","4","","",""),
array("enrique iglesias i like it","4","","",""),
array("enrique iglesias","4","","",""),
array("estoy enamorado wisin y yandel","4","","",""),
array("eminem recovery","4","","",""),
array("eenie meenie justin bieber","4","","",""),
array("eminem lose yourself","4","","","")),
"f" => array(
array("facebook","0","2","3","4"),
array("fox news","0","2","",""),
array("firefox","0","2","",""),
array("fedex","0","2","",""),
array("food network","0","2","",""),
array("fifa 11","1","4","",""),
array("family guy","1","4","",""),
array("free online games","2","3","",""),
array("free music downloads","2","3","",""),
array("facebook login","0","","",""),
array("frys","0","","",""),
array("forever 21","0","","",""),
array("funbrain","0","","",""),
array("fox 4 news","0","","",""),
array("flip video","1","","",""),
array("flip","1","","",""),
array("food processor","1","","",""),
array("fable 3","1","","",""),
array("flash drive","1","","",""),
array("fallout new vegas","1","","",""),
array("fantasia","1","","",""),
array("fushigi ball","1","","",""),
array("fantasy football","2","","",""),
array("fafsa","2","","",""),
array("ford","2","","",""),
array("flava flav","3","","",""),
array("free shipping friday","3","","",""),
array("free ringtones","3","","",""),
array("free games","3","","",""),
array("find a person","3","","",""),
array("free credit report","3","","",""),
array("free people search","3","","",""),
array("funny video","4","","",""),
array("fred","4","","",""),
array("funny","4","","",""),
array("funny pranks","4","","",""),
array("flo rida club cant handle me","4","","",""),
array("flip top","4","","",""),
array("funny cats","4","","","")),
"g" => array(
array("games","0","1","2","3"),
array("google maps","0","2","3",""),
array("glee","0","1","4",""),
array("gmail","0","2","",""),
array("google earth","0","2","",""),
array("google","2","4","",""),
array("google.com","0","","",""),
array("gamestop","0","","",""),
array("google translate","0","","",""),
array("gaylord texan","0","","",""),
array("garland isd","0","","",""),
array("gps","1","","",""),
array("gift card","1","","",""),
array("gran turismo 5","1","","",""),
array("garmin","1","","",""),
array("guitar","1","","",""),
array("garmin gps","1","","",""),
array("gloves","1","","",""),
array("galaxy tab","1","","",""),
array("google search","2","","",""),
array("goo","2","","",""),
array("google homepage","2","","",""),
array("gap","2","","",""),
array("geico","2","","",""),
array("girl kills herself over facebook post","3","","",""),
array("gallinari","3","","",""),
array("gallo","3","","",""),
array("global warming","3","","",""),
array("games.com","3","","",""),
array("games for kids","3","","",""),
array("girl games","3","","",""),
array("google search engine","3","","",""),
array("gummy bear song","4","","",""),
array("g6","4","","",""),
array("gucci mane","4","","",""),
array("green day","4","","",""),
array("ghost","4","","",""),
array("glee toxic","4","","",""),
array("gorillaz","4","","",""),
array("glee britney spears","4","","","")),
"h" => array(
array("halloween costumes","0","2","3",""),
array("hotmail","0","2","",""),
array("hulu","0","2","",""),
array("home depot","0","2","",""),
array("honda","0","2","",""),
array("harry potter","1","2","",""),
array("how to kiss","3","4","",""),
array("hobby lobby","0","","",""),
array("house of blues dallas","0","","",""),
array("half price books","0","","",""),
array("hollister","0","","",""),
array("hp","0","","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("hello kitty","1","","",""),
array("humidifier","1","","",""),
array("halo reach","1","","",""),
array("how to train your dragon","1","","",""),
array("harry potter lego","1","","",""),
array("hard drive","1","","",""),
array("how i met your mother","1","","",""),
array("horoscopes","2","","",""),
array("holiday inn","2","","",""),
array("hi5","2","","",""),
array("harian metro","2","","",""),
array("habilitante","3","","",""),
array("happybdaytayloryork","3","","",""),
array("happybdaytayloryorkbr","3","","",""),
array("how much should i weigh","3","","",""),
array("how to get pregnant","3","","",""),
array("how long does it take to digest gum","3","","",""),
array("how do you spell a word","3","","",""),
array("hotmail.com","3","","",""),
array("hey soul sister","4","","",""),
array("hannah montana","4","","",""),
array("harry potter and the deathly hallows trailer","4","","",""),
array("happy tree friends","4","","",""),
array("hannah montana songs","4","","",""),
array("hallelujah","4","","",""),
array("halo","4","","",""),
array("happy birthday","4","","",""),
array("happy birthday song","4","","","")),
"i" => array(
array("itunes","0","2","3",""),
array("iphone","1","2","3",""),
array("ikea","0","2","",""),
array("imdb","0","2","",""),
array("ipad","0","1","",""),
array("irs","0","2","",""),
array("ign","0","2","",""),
array("ipod touch","1","3","",""),
array("ipod","1","2","",""),
array("inspirational quotes","2","3","",""),
array("indeed","0","","",""),
array("ihop","0","","",""),
array("images","0","","",""),
array("irving isd","0","","",""),
array("ipod nano","1","","",""),
array("inception","1","","",""),
array("iphone 4","1","","",""),
array("ipod touch 4th generation","1","","",""),
array("itouch","1","","",""),
array("ipad case","1","","",""),
array("internet explorer","2","","",""),
array("imeem","2","","",""),
array("insider trading","3","","",""),
array("inter-bayern","3","","",""),
array("is the world going to end in 2012","3","","",""),
array("is bronchitis contagious","3","","",""),
array("is pneumonia contagious","3","","",""),
array("is it going to rain","3","","",""),
array("i love the way you lie","4","","",""),
array("i like it enrique iglesias","4","","",""),
array("i like it","4","","",""),
array("impossible shontelle","4","","",""),
array("i wanna be a billionaire","4","","",""),
array("if i die young","4","","",""),
array("if i die young the band perry","4","","",""),
array("if i had you adam lambert","4","","",""),
array("i love the way you lie lyrics","4","","",""),
array("inna","4","","","")),
"j" => array(
array("justin bieber","0","1","4",""),
array("jobs","0","2","3",""),
array("jcpenney","0","2","",""),
array("jason's deli","0","","",""),
array("james avery","0","","",""),
array("jimmy johns","0","","",""),
array("java","0","","",""),
array("jack in the box","0","","",""),
array("justin tv","0","","",""),
array("john lennon","0","","",""),
array("just dance 2","1","","",""),
array("jewelry box","1","","",""),
array("just dance 2 wii","1","","",""),
array("just dance","1","","",""),
array("juicy couture","1","","",""),
array("just dance wii","1","","",""),
array("juicer","1","","",""),
array("josh groban","1","","",""),
array("jewelry armoire","1","","",""),
array("jessica simpson","2","","",""),
array("jennifer aniston","2","","",""),
array("jennifer lopez","2","","",""),
array("jessica alba","2","","",""),
array("jennifer love hewitt","2","","",""),
array("jetblue","2","","",""),
array("jokes","2","","",""),
array("jessica biel","2","","",""),
array("julianne hough is that so wrong","3","","",""),
array("jennifer mcdaniel","3","","",""),
array("joel anthony","3","","",""),
array("jobs in my area","3","","",""),
array("justin bieber cell number","3","","",""),
array("jcpenney.com","3","","",""),
array("job search","3","","",""),
array("joann fabrics","3","","",""),
array("justin bieber phone number for real","3","","",""),
array("justin bieber baby","4","","",""),
array("just the way you are","4","","",""),
array("just the way you are bruno mars","4","","",""),
array("just a dream nelly","4","","",""),
array("justin bieber eenie meenie","4","","",""),
array("just a dream","4","","",""),
array("justin bieber somebody to love","4","","",""),
array("justin bieber one time","4","","",""),
array("just the way you are bruno mars lyrics","4","","","")),
"k" => array(
array("kmart","0","2","3",""),
array("katy perry","0","2","4",""),
array("kohls","0","3","",""),
array("kelley blue book","0","2","",""),
array("kindle","1","3","",""),
array("kanye west","1","4","",""),
array("kroger","0","","",""),
array("keller isd","0","","",""),
array("krld","0","","",""),
array("k104","0","","",""),
array("kinkos","0","","",""),
array("kayak","0","","",""),
array("kinect","1","","",""),
array("keurig","1","","",""),
array("kindle cover","1","","",""),
array("keurig coffee maker","1","","",""),
array("kitchenaid mixer","1","","",""),
array("kinect sensor","1","","",""),
array("kindle gift card","1","","",""),
array("kinect xbox 360","1","","",""),
array("kim kardashian","2","","",""),
array("kohl's","2","","",""),
array("kate gosselin","2","","",""),
array("kristen stewart","2","","",""),
array("katie holmes","2","","",""),
array("kelly clarkson","2","","",""),
array("keira knightley","2","","",""),
array("katee sackhoff","3","","",""),
array("kalil","3","","",""),
array("kevin hart","3","","",""),
array("kohls.com","3","","",""),
array("kelly blue book","3","","",""),
array("kmart.com","3","","",""),
array("kids games","3","","",""),
array("katy perry teenage dream","4","","",""),
array("katy perry california girlz","4","","",""),
array("kesha take it off","4","","",""),
array("kid cudi","4","","",""),
array("kanye west power","4","","",""),
array("kiss","4","","",""),
array("kesha your love is my drug","4","","",""),
array("katy b on a mission","4","","","")),
"l" => array(
array("lyrics","0","2","3",""),
array("love quotes","0","2","3",""),
array("lowes","0","3","",""),
array("limewire","0","2","",""),
array("lady gaga","2","4","",""),
array("love poems","2","3","",""),
array("lil wayne","2","4","",""),
array("linkedin","0","","",""),
array("la fitness","0","","",""),
array("lisd","0","","",""),
array("louis vuitton","0","","",""),
array("lands end","0","","",""),
array("lotto texas","0","","",""),
array("legos","1","","",""),
array("lego star wars","1","","",""),
array("leapster explorer","1","","",""),
array("laptop computer","1","","",""),
array("luggage","1","","",""),
array("lego harry potter","1","","",""),
array("leapster","1","","",""),
array("leapster 2","1","","",""),
array("lalaloopsy","1","","",""),
array("lego city","1","","",""),
array("lindsay lohan","2","","",""),
array("las vegas","2","","",""),
array("lowe's home improvement","2","","",""),
array("lost","2","","",""),
array("lizzy seeberg","3","","",""),
array("lunar eclipse december 2010","3","","",""),
array("larry king","3","","",""),
array("lyrics to songs","3","","",""),
array("lowes.com","3","","",""),
array("lingerie","3","","",""),
array("love the way you lie","4","","",""),
array("like a g6","4","","",""),
array("linkin park","4","","",""),
array("lady gaga alejandro","4","","",""),
array("love the way you lie eminem","4","","",""),
array("love","4","","",""),
array("lady gaga bad romance","4","","",""),
array("love the way you lie lyrics","4","","","")),
"m" => array(
array("music","2","3","4",""),
array("mapquest","0","2","",""),
array("myspace","0","2","",""),
array("msn","0","2","",""),
array("maps","0","3","",""),
array("michael jackson","1","4","",""),
array("miley cyrus","2","4","",""),
array("metro pcs","0","","",""),
array("michaels","0","","",""),
array("mlb","0","","",""),
array("msnbc","0","","",""),
array("mtv","0","","",""),
array("minecraft","0","","",""),
array("mp3 player","1","","",""),
array("macbook","1","","",""),
array("macbook pro","1","","",""),
array("melissa and doug","1","","",""),
array("mad men","1","","",""),
array("macbook air","1","","",""),
array("mp3","1","","",""),
array("mario kart wii","1","","",""),
array("monster high","1","","",""),
array("mail","2","","",""),
array("movies","2","","",""),
array("macy's","2","","",""),
array("megan fox","2","","",""),
array("miniclip","2","","",""),
array("marisa tomei","3","","",""),
array("miracle on 34th street","3","","",""),
array("maureen o hara","3","","",""),
array("mapquest driving directions","3","","",""),
array("math answers","3","","",""),
array("medical dictionary","3","","",""),
array("meaning of names","3","","",""),
array("myspace layouts","3","","",""),
array("magic b.o.b","4","","",""),
array("mine taylor swift","4","","",""),
array("mariah carey","4","","",""),
array("metallica","4","","",""),
array("magic","4","","",""),
array("mine","4","","",""),
array("maroon 5","4","","","")),
"n" => array(
array("netflix","0","2","3",""),
array("news","0","2","3",""),
array("nfl","0","2","",""),
array("nordstrom","0","2","",""),
array("nbc","0","2","",""),
array("nissan","2","3","",""),
array("ntta","0","","",""),
array("ntb","0","","",""),
array("northpark mall","0","","",""),
array("new york times","0","","",""),
array("neiman marcus","0","","",""),
array("nook","1","","",""),
array("nintendo ds","1","","",""),
array("nintendo dsi","1","","",""),
array("nerf","1","","",""),
array("nintendo dsi xl","1","","",""),
array("nintendo wii","1","","",""),
array("nikon d7000","1","","",""),
array("nintendo ds games","1","","",""),
array("nook color","1","","",""),
array("nintendo ds lite","1","","",""),
array("nick jr","2","","",""),
array("nascar","2","","",""),
array("nba","2","","",""),
array("nokia","2","","",""),
array("nikki sixx","3","","",""),
array("nagging","3","","",""),
array("nancy e katz","3","","",""),
array("name meanings","3","","",""),
array("netflix.com","3","","",""),
array("names and meaning","3","","",""),
array("northwest airlines","3","","",""),
array("nicki minaj","4","","",""),
array("nelly just a dream","4","","",""),
array("not afraid eminem","4","","",""),
array("no love eminem","4","","",""),
array("nigahiga","4","","",""),
array("no love","4","","",""),
array("never say never","4","","",""),
array("nelly","4","","",""),
array("no love eminem lil wayne","4","","",""),
array("new songs 2010","4","","","")),
"o" => array(
array("old navy","0","2","3",""),
array("online games","0","2","3",""),
array("office depot","0","2","",""),
array("orbitz","0","2","",""),
array("overstock","0","2","",""),
array("olive garden","0","2","",""),
array("oprah","0","2","",""),
array("online dictionary","2","3","",""),
array("omg","2","4","",""),
array("office max","0","","",""),
array("o'reilly auto parts","0","","",""),
array("open office","0","","",""),
array("otterbox","1","","",""),
array("oakley","1","","",""),
array("ornaments","1","","",""),
array("oakley sunglasses","1","","",""),
array("otterbox iphone 4","1","","",""),
array("orbeez","1","","",""),
array("one tree hill","1","","",""),
array("office chair","1","","",""),
array("office 2010","1","","",""),
array("olivia","1","","",""),
array("orkut","2","","",""),
array("omegle","3","","",""),
array("orange caramel","3","","",""),
array("obese","3","","",""),
array("overstock.com","3","","",""),
array("online pregnancy test","3","","",""),
array("ovulation calendar","3","","",""),
array("ovulation calculator","3","","",""),
array("omg usher","4","","",""),
array("one time justin bieber","4","","",""),
array("oil rig employment","4","","",""),
array("one time","4","","",""),
array("one republic secrets","4","","",""),
array("ok go","4","","",""),
array("old spice commercial","4","","",""),
array("oasis","4","","",""),
array("olly murs please don't let me go","4","","","")),
"p" => array(
array("pizza hut","0","2","",""),
array("photobucket","0","2","",""),
array("paypal","0","2","",""),
array("petsmart","0","2","",""),
array("priceline","0","2","",""),
array("people search","2","3","",""),
array("pandora","0","","",""),
array("party city","0","","",""),
array("papa johns","0","","",""),
array("pei wei","0","","",""),
array("poptropica","0","","",""),
array("ps3","1","","",""),
array("playstation 3","1","","",""),
array("pillow pets","1","","",""),
array("psp","1","","",""),
array("portable dvd player","1","","",""),
array("ps3 games","1","","",""),
array("p90x","1","","",""),
array("ps3 console","1","","",""),
array("playstation move","1","","",""),
array("ps3 move","1","","",""),
array("pogo","2","","",""),
array("powerball","2","","",""),
array("people magazine","2","","",""),
array("pottery barn","2","","",""),
array("pineapple express","3","","",""),
array("provo tabernacle fire","3","","",""),
array("pacific palisades","3","","",""),
array("pregnancy week by week","3","","",""),
array("priceline.com","3","","",""),
array("phone number lookup","3","","",""),
array("people finder","3","","",""),
array("people search for free","3","","",""),
array("pregnancy symptoms","3","","",""),
array("paramore","4","","",""),
array("paranormal activity 2 trailer official","4","","",""),
array("pretty boy swag","4","","",""),
array("pitbull","4","","",""),
array("pink","4","","",""),
array("party in the usa","4","","",""),
array("pyramid charice","4","","",""),
array("paramore the only exception","4","","",""),
array("pokemon","4","","",""),
array("poker face","4","","","")),
"q" => array(
array("quickbooks","0","1","2","3"),
array("quotes","0","2","3",""),
array("qvc","0","2","3",""),
array("quest diagnostics","0","2","",""),
array("quiznos","0","2","",""),
array("quicktime","0","2","",""),
array("quotes about life","0","3","",""),
array("quicken","0","1","",""),
array("queen","1","4","",""),
array("quizzes","2","3","",""),
array("quizlet","0","","",""),
array("quia","0","","",""),
array("qwirkle","1","","",""),
array("quiksilver","1","","",""),
array("quicken 2011","1","","",""),
array("quilt","1","","",""),
array("quesadilla maker","1","","",""),
array("quicksilver","1","","",""),
array("quelf","1","","",""),
array("qwest","2","","",""),
array("query string","2","","",""),
array("quizilla","2","","",""),
array("quaziggyziggyzam","3","","",""),
array("quotes of the day","3","","",""),
array("quotes and sayings","3","","",""),
array("qvc home shopping","3","","",""),
array("quote of the day","3","","",""),
array("queen bohemian rhapsody","4","","",""),
array("quest crew","4","","",""),
array("queen we will rock you","4","","",""),
array("quisiera pasabordo","4","","",""),
array("queen don't stop me now","4","","",""),
array("queens of the stone age","4","","",""),
array("queen somebody to love","4","","",""),
array("quisiera","4","","",""),
array("quran","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("espn","0","2","",""),
array("english to spanish translation","0","3","",""),
array("eminem","2","4","",""),
array("evite","0","","",""),
array("etsy","0","","",""),
array("express","0","","",""),
array("eecu","0","","",""),
array("eddie long","0","","",""),
array("espn3","0","","",""),
array("external hard drive","1","","",""),
array("eclipse","1","","",""),
array("epic mickey","1","","",""),
array("electric blanket","1","","",""),
array("elf on the shelf","1","","",""),
array("eclipse dvd","1","","",""),
array("earphones","1","","",""),
array("eat pray love","1","","",""),
array("earbuds","1","","",""),
array("easy bake oven","1","","",""),
array("enterprise car rental","2","","",""),
array("elin nordegren","2","","",""),
array("ecards","2","","",""),
array("ebay motors","2","","",""),
array("emma watson","2","","",""),
array("eva longoria","2","","",""),
array("eastern washington university","3","","",""),
array("earle herrera","3","","",""),
array("eastern washington","3","","",""),
array("ebay.com","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("expedia.com","3","","",""),
array("engagement rings","3","","",""),
array("eminem not afraid","4","","",""),
array("eminem love the way you lie","4","","",""),
array("eminem no love","4","","",""),
array("enrique iglesias i like it","4","","",""),
array("enrique iglesias","4","","",""),
array("estoy enamorado wisin y yandel","4","","",""),
array("eminem recovery","4","","",""),
array("eenie meenie justin bieber","4","","",""),
array("eminem lose yourself","4","","","")),
"s" => array(
array("southwest airlines","0","2","3",""),
array("skype","0","2","",""),
array("sears","0","2","",""),
array("sprint","0","2","",""),
array("song lyrics","2","3","",""),
array("shakira","2","4","",""),
array("state fair of texas","0","","",""),
array("sams club","0","","",""),
array("smu","0","","",""),
array("star telegram","0","","",""),
array("speed test","0","","",""),
array("starbucks","0","","",""),
array("star wars","1","","",""),
array("swiss legend men's commander collection watch","1","","",""),
array("slippers","1","","",""),
array("snuggie","1","","",""),
array("stocking stuffers","1","","",""),
array("squinkies","1","","",""),
array("samsung galaxy tab","1","","",""),
array("sd card","1","","",""),
array("sewing machine","1","","",""),
array("socks","1","","",""),
array("staples","2","","",""),
array("sandra bullock","2","","",""),
array("sony","2","","",""),
array("sarah palin","2","","",""),
array("space shuttle launch","3","","",""),
array("shelley malil","3","","",""),
array("sparta prague","3","","",""),
array("science fair projects","3","","",""),
array("spanish dictionary","3","","",""),
array("scary maze game","3","","",""),
array("sexy","3","","",""),
array("spanish translator","3","","",""),
array("shakira waka waka","4","","",""),
array("selena gomez","4","","",""),
array("sexist video of man and woman","4","","",""),
array("shane dawson","4","","",""),
array("solo","4","","",""),
array("somebody to love justin bieber","4","","",""),
array("stereo love","4","","",""),
array("soulja boy","4","","",""),
array("smosh","4","","","")),
"t" => array(
array("taylor swift","1","2","4",""),
array("target","0","2","",""),
array("ticketmaster","0","2","",""),
array("toys r us","2","3","",""),
array("texas rangers","0","","",""),
array("texas state fair","0","","",""),
array("texas lottery","0","","",""),
array("thesaurus","0","","",""),
array("translate","0","","",""),
array("texas workforce commission","0","","",""),
array("twitter","0","","",""),
array("tcu","0","","",""),
array("toy story 3","1","","",""),
array("tron","1","","",""),
array("twilight","1","","",""),
array("toy story","1","","",""),
array("the pacific","1","","",""),
array("telescope","1","","",""),
array("true blood","1","","",""),
array("tangled","1","","",""),
array("the walking dead","1","","",""),
array("travelocity","2","","",""),
array("toyota","2","","",""),
array("tagged","2","","",""),
array("tiger woods","2","","",""),
array("t-mobile","2","","",""),
array("tmz","2","","",""),
array("tax deductible donation","3","","",""),
array("the beaver","3","","",""),
array("the edge of darkness","3","","",""),
array("tattoo designs","3","","",""),
array("translate english to spanish","3","","",""),
array("tattoos","3","","",""),
array("teen pregnancy signs","3","","",""),
array("translate spanish to english","3","","",""),
array("thanksgiving history","3","","",""),
array("teenage dream katy perry","4","","",""),
array("teach me how to dougie","4","","",""),
array("teenage dream","4","","",""),
array("trey songz","4","","",""),
array("take it off kesha","4","","",""),
array("taio cruz dynamite","4","","",""),
array("taylor swift mine","4","","",""),
array("tom and jerry","4","","",""),
array("tik tok","4","","","")),
"u" => array(
array("ufc","0","2","4",""),
array("usps","0","2","",""),
array("ups","0","2","",""),
array("usaa","0","2","",""),
array("ugg boots","1","3","",""),
array("united airlines","2","3","",""),
array("us airways","2","3","",""),
array("used cars","2","3","",""),
array("unt","0","","",""),
array("uta","0","","",""),
array("utube","0","","",""),
array("ups tracking","0","","",""),
array("university of texas","0","","",""),
array("utd","0","","",""),
array("uggs","1","","",""),
array("under armour","1","","",""),
array("ugg boots women","1","","",""),
array("usb flash drive","1","","",""),
array("uggs boots for women","1","","",""),
array("unlocked cell phones","1","","",""),
array("umbrella","1","","",""),
array("uncharted 2","1","","",""),
array("udraw","1","","",""),
array("utusan malaysia","2","","",""),
array("us bank","2","","",""),
array("univision","2","","",""),
array("u of i","3","","",""),
array("university of illinois","3","","",""),
array("uefa champions","3","","",""),
array("unique baby names","3","","",""),
array("ugg boots on sale","3","","",""),
array("unemployment benefits","3","","",""),
array("usher","4","","",""),
array("usher dj got us falling in love","4","","",""),
array("u smile justin bieber","4","","",""),
array("u smile","4","","",""),
array("usher omg","4","","",""),
array("u smile justin bieber official music video","4","","",""),
array("usher there goes my baby","4","","",""),
array("u2","4","","",""),
array("ufo","4","","","")),
"v" => array(
array("verizon wireless","0","2","3",""),
array("verizon","0","2","3",""),
array("victoria secret","0","3","",""),
array("vampire diaries","0","1","",""),
array("vonage","0","2","",""),
array("victoria's secret","1","2","",""),
array("vanessa hudgens","2","4","",""),
array("vlc","0","","",""),
array("verizon fios","0","","",""),
array("viewpoint bank","0","","",""),
array("verizon.net","0","","",""),
array("vimeo","0","","",""),
array("vera bradley","1","","",""),
array("video camera","1","","",""),
array("vacuum cleaner","1","","",""),
array("video games","1","","",""),
array("vans","1","","",""),
array("vizio","1","","",""),
array("vacuum","1","","",""),
array("vibratores for women","1","","",""),
array("video","2","","",""),
array("vh1","2","","",""),
array("value city furniture","2","","",""),
array("virgin mobile","2","","",""),
array("victoria beckham","2","","",""),
array("villanova football","3","","",""),
array("valencia-schalke","3","","",""),
array("venezuela libre","3","","",""),
array("verizon.com","3","","",""),
array("verizonwireless.com","3","","",""),
array("volcanoes","3","","",""),
array("very early symptoms of pregnancy","3","","",""),
array("vybz kartel","4","","",""),
array("vicente fernandez","4","","",""),
array("victorious","4","","",""),
array("videos grasiosos","4","","",""),
array("vampire weekend","4","","",""),
array("vanilla twilight","4","","",""),
array("viva la vida","4","","",""),
array("videos de risa","4","","",""),
array("van halen","4","","","")),
"w" => array(
array("white pages","0","2","3",""),
array("walmart","0","2","",""),
array("weather","0","2","",""),
array("wells fargo","0","2","",""),
array("wikipedia","0","2","",""),
array("walgreens","0","2","",""),
array("wwe","2","4","",""),
array("wfaa","0","","",""),
array("www.facebook.com","0","","",""),
array("web md","0","","",""),
array("www.yahoo.com","0","","",""),
array("wii","1","","",""),
array("wii games","1","","",""),
array("wii console","1","","",""),
array("wii fit","1","","",""),
array("wii remote","1","","",""),
array("world of warcraft","1","","",""),
array("watch","1","","",""),
array("wii controller","1","","",""),
array("wireless router","1","","",""),
array("webcam","1","","",""),
array("webmd","2","","",""),
array("webkinz","2","","",""),
array("wachovia","2","","",""),
array("wind energy","3","","",""),
array("wannabe","3","","",""),
array("whitehall","3","","",""),
array("what does my name mean","3","","",""),
array("what does my last name mean","3","","",""),
array("what is justin biebers phone number","3","","",""),
array("what is the meaning of my name","3","","",""),
array("what is love","3","","",""),
array("when will the world end","3","","",""),
array("waka waka","4","","",""),
array("waka waka shakira","4","","",""),
array("we no speak americano","4","","",""),
array("written in the stars","4","","",""),
array("wiz khalifa","4","","",""),
array("wisin y yandel","4","","",""),
array("waka flocka flames","4","","",""),
array("weight loss methods","4","","",""),
array("whip my hair","4","","","")),
"x" => array(
array("xbox","0","1","3",""),
array("xm radio","0","2","3",""),
array("xbox live","0","1","2",""),
array("xbox 360","1","2","3",""),
array("xbox kinect","0","1","",""),
array("xbox 360 console","1","3","",""),
array("xbox 360 games","1","3","",""),
array("x factor","2","4","",""),
array("x-rays","0","","",""),
array("xkcd","0","","",""),
array("xtranormal","0","","",""),
array("xbmc","0","","",""),
array("xda","0","","",""),
array("xanga","0","","",""),
array("xbox 360 kinect","1","","",""),
array("xbox 360 controller","1","","",""),
array("xbox games","1","","",""),
array("xbox controller","1","","",""),
array("xanax","2","","",""),
array("xbox cheats","2","","",""),
array("x games","2","","",""),
array("x17","2","","",""),
array("xvid","2","","",""),
array("xerox","2","","",""),
array("xbox 360 cheats","3","","",""),
array("xbox 360 elite","3","","",""),
array("xbox 360 cheat codes","3","","",""),
array("xbox 360 problems","3","","",""),
array("xxl tv live","3","","",""),
array("x factor 2010","4","","",""),
array("x factor 2010 auditions","4","","",""),
array("x factor 2010 judges houses","4","","",""),
array("x factor judges houses 2010","4","","",""),
array("xbox 360 slim","4","","",""),
array("x","4","","",""),
array("xxl movie six","4","","",""),
array("xzibit","4","","",""),
array("x factor 2010 boot camp","4","","","")),
"y" => array(
array("youtube","0","2","3","4"),
array("yellow pages","0","2","3",""),
array("yahoo","0","2","",""),
array("yahoo mail","0","2","",""),
array("yahoo maps","0","2","",""),
array("youtube music","0","3","",""),
array("yahoomail.com","0","","",""),
array("yahoo fantasy football","0","","",""),
array("yahoo music","0","","",""),
array("yahoo answers","0","","",""),
array("yoga mat","1","","",""),
array("yo gabba gabba","1","","",""),
array("yankee candle","1","","",""),
array("yoga","1","","",""),
array("yarn","1","","",""),
array("yoga dvd","1","","",""),
array("yankees","1","","",""),
array("yugioh cards","1","","",""),
array("your baby can read","1","","",""),
array("yoga pants","1","","",""),
array("youtube video","2","","",""),
array("youtube broadcast yourself","2","","",""),
array("yahoo messenger","2","","",""),
array("yahoo games","2","","",""),
array("y8","2","","",""),
array("yao ming","3","","",""),
array("year end","3","","",""),
array("youtube videos","3","","",""),
array("yellowpages.com","3","","",""),
array("youtube.com","3","","",""),
array("yellow pages.com","3","","",""),
array("youtube music videos","3","","",""),
array("your love nicki minaj","4","","",""),
array("your love is my drug","4","","",""),
array("young jeezy","4","","",""),
array("your love","4","","",""),
array("you belong with me","4","","",""),
array("you belong with me taylor swift","4","","",""),
array("young money","4","","",""),
array("yolanda be cool we no speak americano","4","","",""),
array("you smile justin bieber","4","","","")),
"z" => array(
array("zip codes","0","2","3",""),
array("zales","0","2","3",""),
array("zumba","0","1","4",""),
array("zodiac signs","0","2","3",""),
array("zappos","0","2","",""),
array("zillow","0","2","",""),
array("zune","0","1","",""),
array("zach galifianakis","0","4","",""),
array("zhu zhu pets","1","3","",""),
array("zhu zhu","1","3","",""),
array("zombie","1","4","",""),
array("zac efron","2","4","",""),
array("zumiez","0","","",""),
array("zara","0","","",""),
array("zoobles","1","","",""),
array("zumba wii","1","","",""),
array("zune hd","1","","",""),
array("zippo","1","","",""),
array("zumba fitness dvd","1","","",""),
array("zsa zsa gabor","2","","",""),
array("zuma","2","","",""),
array("zooey deschanel","2","","",""),
array("zaba search","2","","",""),
array("zip code finder","3","","",""),
array("zappos.com","3","","",""),
array("zip code list","3","","",""),
array("zhu zhu pet","3","","",""),
array("zip code lookup","3","","",""),
array("zac brown band","4","","",""),
array("zombie cranberries","4","","",""),
array("zzirgrizz","4","","",""),
array("zz top","4","","",""),
array("zain malik","4","","",""),
array("zvezde granda 2010","4","","","")));
?>