<?php $topResults = array(
"a" => array(
array("amazon","0","2","",""),
array("aol","0","2","",""),
array("apple","0","1","",""),
array("american airlines","0","2","",""),
array("adele","1","4","",""),
array("att","0","","",""),
array("ask","0","","",""),
array("abc","0","","",""),
array("addicting games","0","","",""),
array("amc","0","","",""),
array("american eagle","0","","",""),
array("airsoft guns","1","","",""),
array("apple tv","1","","",""),
array("adidas","1","","",""),
array("amazon mom","1","","",""),
array("android tablet","1","","",""),
array("arcade fire","1","","",""),
array("airsoft","1","","",""),
array("assassins creed brotherhood","1","","",""),
array("apophis asteroid","2","","",""),
array("at&t","2","","",""),
array("autotrader","2","","",""),
array("american idol","2","","",""),
array("angelina jolie","2","","",""),
array("ashlee simpson","2","","",""),
array("amanda knox","2","","",""),
array("air force tanker","3","","",""),
array("amber portwood","3","","",""),
array("academy of country music","3","","",""),
array("are vampires real","3","","",""),
array("answers.com","3","","",""),
array("ancestry.com","3","","",""),
array("apartments for rent","3","","",""),
array("airline tickets","3","","",""),
array("att.com","3","","",""),
array("am i pregnant quiz","3","","",""),
array("akon","4","","",""),
array("annoying orange","4","","",""),
array("avril lavigne","4","","",""),
array("airplanes","4","","",""),
array("avril lavigne what the hell","4","","",""),
array("alicia keys","4","","",""),
array("adele rolling in the deep","4","","",""),
array("avenged sevenfold","4","","",""),
array("antoine dodson","4","","","")),
"b" => array(
array("best buy","0","2","3",""),
array("bed bath and beyond","0","2","3",""),
array("bank of america","0","2","",""),
array("bing","0","2","",""),
array("barnes and noble","0","2","",""),
array("black friday","0","3","",""),
array("britney spears","2","4","",""),
array("black swan","0","","",""),
array("borders","0","","",""),
array("blockbuster","0","","",""),
array("big lots","0","","",""),
array("blackberry","1","","",""),
array("black ops","1","","",""),
array("bulletstorm","1","","",""),
array("blackberry torch","1","","",""),
array("beats by dre","1","","",""),
array("bluetooth headset","1","","",""),
array("backpack","1","","",""),
array("bose","1","","",""),
array("blu ray player","1","","",""),
array("blackberry unlocked","1","","",""),
array("blank","2","","",""),
array("brett favre","2","","",""),
array("brooklyn decker","2","","",""),
array("babies r us","2","","",""),
array("boeing tanker","3","","",""),
array("bandera","3","","",""),
array("bob crow","3","","",""),
array("black friday 2010","3","","",""),
array("baby names","3","","",""),
array("black friday ads","3","","",""),
array("black friday sales","3","","",""),
array("black and yellow wiz khalifa","4","","",""),
array("black and yellow","4","","",""),
array("bruno mars grenade","4","","",""),
array("black eyed peas","4","","",""),
array("bruno mars","4","","",""),
array("bruno mars just the way you are","4","","",""),
array("beyonce","4","","",""),
array("baby justin bieber","4","","",""),
array("bottoms up","4","","","")),
"c" => array(
array("craigslist","0","2","",""),
array("cnn","0","2","",""),
array("chase","0","2","",""),
array("costco","0","2","",""),
array("coach","0","1","",""),
array("christina aguilera","2","4","",""),
array("carrie underwood","2","3","",""),
array("comcast","0","","",""),
array("comcast.net","0","","",""),
array("cnet","0","","",""),
array("cbs","0","","",""),
array("cvs","0","","",""),
array("call of duty black ops","1","","",""),
array("camera","1","","",""),
array("coffee maker","1","","",""),
array("canon 7d","1","","",""),
array("canon t2i","1","","",""),
array("crocs","1","","",""),
array("canon 60d","1","","",""),
array("canon","1","","",""),
array("cell phone","1","","",""),
array("chelsea clinton","2","","",""),
array("charlie sheen","2","","",""),
array("capital one","2","","",""),
array("cartoon network","2","","",""),
array("celtics trade","3","","",""),
array("cystic fibrosis","3","","",""),
array("cheap airline tickets","3","","",""),
array("calculator","3","","",""),
array("cheap flights","3","","",""),
array("coupons","3","","",""),
array("cheat codes","3","","",""),
array("cheap halloween costumes","3","","",""),
array("credit cards","3","","",""),
array("chris brown","4","","",""),
array("creative writing jobs","4","","",""),
array("coming home","4","","",""),
array("california gurls katy perry","4","","",""),
array("charlie bit my finger","4","","",""),
array("cat daddy","4","","",""),
array("chris brown yeah 3x","4","","",""),
array("club cant handle me flo rida","4","","",""),
array("chris brown deuces","4","","","")),
"d" => array(
array("dictionary","0","2","3",""),
array("dell","0","2","",""),
array("delta airlines","2","3","",""),
array("driving directions","2","3","",""),
array("delta","0","","",""),
array("dillards","0","","",""),
array("dsw","0","","",""),
array("dominos","0","","",""),
array("dmv","0","","",""),
array("discover","0","","",""),
array("disney","0","","",""),
array("direct tv","0","","",""),
array("dead space 2","1","","",""),
array("diapers","1","","",""),
array("digital camera","1","","",""),
array("dragon age 2","1","","",""),
array("dvd player","1","","",""),
array("dead space","1","","",""),
array("droid x","1","","",""),
array("d7000","1","","",""),
array("dsi","1","","",""),
array("dexter","1","","",""),
array("disney channel","2","","",""),
array("dancing with the stars","2","","",""),
array("diet soda","2","","",""),
array("dish network","2","","",""),
array("disneyland","2","","",""),
array("directv","2","","",""),
array("discovery launch","3","","",""),
array("daniel lider","3","","",""),
array("danny ainge","3","","",""),
array("definitions.com","3","","",""),
array("disneychannel.com","3","","",""),
array("does justin bieber have a girlfriend","3","","",""),
array("download free music","3","","",""),
array("drake","4","","",""),
array("dynamite taio cruz","4","","",""),
array("dubstep","4","","",""),
array("dynamite","4","","",""),
array("dirty bit","4","","",""),
array("david guetta","4","","",""),
array("dj got us falling in love","4","","",""),
array("do it like a dude","4","","",""),
array("down on me","4","","",""),
array("deadmau5","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("eminem","1","2","4",""),
array("espn","0","2","",""),
array("etsy","0","","",""),
array("express","0","","",""),
array("elizabeth edwards","0","","",""),
array("espn3","0","","",""),
array("egypt","0","","",""),
array("easter 2011","0","","",""),
array("e","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("esperanza spalding","1","","",""),
array("electronic cigarette","1","","",""),
array("elliptical","1","","",""),
array("ethernet cable","1","","",""),
array("espresso machine","1","","",""),
array("ebooks","1","","",""),
array("elizabeth taylor","2","","",""),
array("ellen degeneres","2","","",""),
array("elin nordegren","2","","",""),
array("enterprise car rental","2","","",""),
array("elvis presley enterprises","2","","",""),
array("eva longoria","2","","",""),
array("earthquake hawaii","3","","",""),
array("edc","3","","",""),
array("elmer","3","","",""),
array("ebay.com","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("expedia.com","3","","",""),
array("engagement rings","3","","",""),
array("eminem not afraid","4","","",""),
array("enrique iglesias","4","","",""),
array("eminem love the way you lie","4","","",""),
array("enrique iglesias tonight","4","","",""),
array("eminem no love","4","","",""),
array("enrique iglesias i like it","4","","",""),
array("eminem lose yourself","4","","",""),
array("evanescence","4","","",""),
array("eminem when im gone","4","","","")),
"f" => array(
array("facebook","0","2","3","4"),
array("fedex","0","2","",""),
array("fox news","0","2","",""),
array("food network","0","2","",""),
array("ford","0","2","",""),
array("free online games","2","3","",""),
array("free music downloads","2","3","",""),
array("firefox","0","","",""),
array("frostwire","0","","",""),
array("fox","0","","",""),
array("forever 21","0","","",""),
array("fafsa","0","","",""),
array("flash drive","1","","",""),
array("free kindle books","1","","",""),
array("food processor","1","","",""),
array("flowers","1","","",""),
array("flip video","1","","",""),
array("futon","1","","",""),
array("fifa 11","1","","",""),
array("flashlight","1","","",""),
array("flip","1","","",""),
array("floor lamp","1","","",""),
array("fantasia barrino","2","","",""),
array("fergie","2","","",""),
array("fantasy football","2","","",""),
array("ford recall","3","","",""),
array("facetime","3","","",""),
array("free ringtones","3","","",""),
array("free games","3","","",""),
array("find a person","3","","",""),
array("free credit report","3","","",""),
array("free people search","3","","",""),
array("firework katy perry","4","","",""),
array("funny video","4","","",""),
array("firework","4","","",""),
array("funny","4","","",""),
array("fred","4","","",""),
array("funny pranks","4","","",""),
array("funny cats","4","","",""),
array("family guy","4","","",""),
array("firework katy perry lyrics","4","","","")),
"g" => array(
array("glee","0","1","2","4"),
array("google maps","0","2","3",""),
array("games","0","2","3",""),
array("gmail","0","2","",""),
array("google.com","0","","",""),
array("google translate","0","","",""),
array("google earth","0","","",""),
array("gamestop","0","","",""),
array("gap","0","","",""),
array("google images","0","","",""),
array("gps","1","","",""),
array("gift card","1","","",""),
array("galaxy tab","1","","",""),
array("garmin","1","","",""),
array("guitar","1","","",""),
array("garmin gps","1","","",""),
array("guess","1","","",""),
array("g shock","1","","",""),
array("gran turismo 5","1","","",""),
array("google","2","","",""),
array("google search","2","","",""),
array("goo","2","","",""),
array("gisele bundchen","2","","",""),
array("gwyneth paltrow","2","","",""),
array("google homepage","2","","",""),
array("gaddafi shot","3","","",""),
array("goran dragic","3","","",""),
array("gabriel aubry","3","","",""),
array("global warming","3","","",""),
array("games.com","3","","",""),
array("games for kids","3","","",""),
array("girl games","3","","",""),
array("google search engine","3","","",""),
array("grenade bruno mars","4","","",""),
array("grenade","4","","",""),
array("green and yellow","4","","",""),
array("g6","4","","",""),
array("gummy bear song","4","","",""),
array("grenade bruno mars lyrics","4","","",""),
array("gucci mane","4","","",""),
array("granade bruno mars","4","","",""),
array("green day","4","","","")),
"h" => array(
array("hotmail","0","2","",""),
array("hulu","0","2","",""),
array("home depot","0","2","",""),
array("honda","0","2","",""),
array("hgtv","0","2","",""),
array("halle berry","2","3","",""),
array("how to kiss","3","4","",""),
array("hp","0","","",""),
array("hollister","0","","",""),
array("hobby lobby","0","","",""),
array("h&m","0","","",""),
array("horoscope","0","","",""),
array("headphones","1","","",""),
array("hdmi cable","1","","",""),
array("harry potter","1","","",""),
array("humidifier","1","","",""),
array("hello kitty","1","","",""),
array("hard drive","1","","",""),
array("halo reach","1","","",""),
array("hdmi","1","","",""),
array("htc evo","1","","",""),
array("htc","1","","",""),
array("horoscopes","2","","",""),
array("hi5","2","","",""),
array("heidi montag","2","","",""),
array("harian metro","2","","",""),
array("hangover 2 trailer","3","","",""),
array("half men","3","","",""),
array("how much should i weigh","3","","",""),
array("how to get pregnant","3","","",""),
array("how long does it take to digest gum","3","","",""),
array("how do you spell a word","3","","",""),
array("halloween costumes","3","","",""),
array("hotmail.com","3","","",""),
array("hold it against me","4","","",""),
array("hey soul sister","4","","",""),
array("hannah montana","4","","",""),
array("hey baby pitbull","4","","",""),
array("hold my hand akon michael jackson","4","","",""),
array("higher taio cruz","4","","",""),
array("hold it against me britney spears","4","","",""),
array("happy tree friends","4","","",""),
array("hello","4","","","")),
"i" => array(
array("itunes","0","2","3",""),
array("irs","0","2","3",""),
array("ikea","0","2","",""),
array("imdb","0","2","",""),
array("ipad","0","1","",""),
array("indeed","0","2","",""),
array("ipod touch","1","3","",""),
array("ipod","1","2","",""),
array("iphone","1","2","",""),
array("inspirational quotes","2","3","",""),
array("images","0","","",""),
array("iphone 5","0","","",""),
array("ign","0","","",""),
array("ipad 2","0","","",""),
array("iphone 4","1","","",""),
array("iphone 4 case","1","","",""),
array("ipod nano","1","","",""),
array("ipod touch 4th generation","1","","",""),
array("ipad case","1","","",""),
array("iphone 3gs","1","","",""),
array("internet explorer","2","","",""),
array("illinois lottery","2","","",""),
array("ileana cabra","3","","",""),
array("imran tahir","3","","",""),
array("is the world going to end in 2012","3","","",""),
array("is bronchitis contagious","3","","",""),
array("is pneumonia contagious","3","","",""),
array("is it going to rain","3","","",""),
array("i love the way you lie","4","","",""),
array("im coming home","4","","",""),
array("if i die young","4","","",""),
array("i whip my hair back and forth","4","","",""),
array("if i die young the band perry","4","","",""),
array("inna","4","","",""),
array("indian songs","4","","",""),
array("i love you","4","","",""),
array("i like it enrique iglesias","4","","",""),
array("impossible shontelle","4","","","")),
"j" => array(
array("justin bieber","0","1","2","4"),
array("jobs","0","2","3",""),
array("jcpenney","0","2","",""),
array("jennifer aniston","2","3","",""),
array("jet blue","0","","",""),
array("java","0","","",""),
array("jcrew","0","","",""),
array("jersey shore","0","","",""),
array("jokes","0","","",""),
array("jeep","0","","",""),
array("jimmy johns","0","","",""),
array("juicer","1","","",""),
array("just dance 2","1","","",""),
array("jillian michaels","1","","",""),
array("just dance","1","","",""),
array("juicy couture","1","","",""),
array("jack3d","1","","",""),
array("jewelry box","1","","",""),
array("justified","1","","",""),
array("just dance 2 wii","1","","",""),
array("julia roberts","2","","",""),
array("jennifer hudson","2","","",""),
array("jessica simpson","2","","",""),
array("jennifer lopez","2","","",""),
array("jennifer love hewitt","2","","",""),
array("jessica alba","2","","",""),
array("jeff green","3","","",""),
array("justin tennison","3","","",""),
array("jobs in my area","3","","",""),
array("justin bieber cell number","3","","",""),
array("jcpenney.com","3","","",""),
array("job search","3","","",""),
array("joann fabrics","3","","",""),
array("justin bieber phone number for real","3","","",""),
array("justin bieber baby","4","","",""),
array("just the way you are","4","","",""),
array("just the way you are bruno mars","4","","",""),
array("just a dream nelly","4","","",""),
array("just a dream","4","","",""),
array("justin bieber somebody to love","4","","",""),
array("justin bieber pray","4","","",""),
array("justin bieber eenie meenie","4","","",""),
array("jar of hearts","4","","","")),
"k" => array(
array("kmart","0","2","3",""),
array("kindle","0","1","3",""),
array("kohls","0","3","",""),
array("kanye west","0","4","",""),
array("katy perry","2","4","",""),
array("kayak","0","","",""),
array("kroger","0","","",""),
array("kesha","0","","",""),
array("kbb","0","","",""),
array("kfc","0","","",""),
array("kia","0","","",""),
array("killzone 3","1","","",""),
array("kinect","1","","",""),
array("kindle cover","1","","",""),
array("keurig","1","","",""),
array("k cups","1","","",""),
array("kindle case","1","","",""),
array("keyboard","1","","",""),
array("knife","1","","",""),
array("kinect games","1","","",""),
array("kim kardashian","2","","",""),
array("kristin chenoweth","2","","",""),
array("kelley blue book","2","","",""),
array("kohl's","2","","",""),
array("kate gosselin","2","","",""),
array("kathy griffin","2","","",""),
array("kristen stewart","2","","",""),
array("katie holmes","2","","",""),
array("kendrick perkins","3","","",""),
array("kellie pickler","3","","",""),
array("kyle jacobs","3","","",""),
array("kohls.com","3","","",""),
array("kelly blue book","3","","",""),
array("kmart.com","3","","",""),
array("kids games","3","","",""),
array("katy perry firework","4","","",""),
array("katy perry teenage dream","4","","",""),
array("kid cudi","4","","",""),
array("kesha take it off","4","","",""),
array("kesha we r who we r","4","","",""),
array("katy perry california girlz","4","","",""),
array("keri hilson","4","","",""),
array("kiss","4","","","")),
"l" => array(
array("lyrics","0","2","3",""),
array("love quotes","0","2","3",""),
array("lady gaga","1","2","4",""),
array("lowes","0","3","",""),
array("limewire","0","2","",""),
array("lego","0","1","",""),
array("lil wayne","2","4","",""),
array("linkedin","0","","",""),
array("lands end","0","","",""),
array("lunar eclipse","0","","",""),
array("llbean","0","","",""),
array("lunar eclipse 2010","0","","",""),
array("laptop computer","1","","",""),
array("luggage","1","","",""),
array("laptop","1","","",""),
array("lego star wars","1","","",""),
array("little big planet 2","1","","",""),
array("laptop bag","1","","",""),
array("louis vuitton","1","","",""),
array("lcd tv","1","","",""),
array("lindsay lohan","2","","",""),
array("lowe's home improvement","2","","",""),
array("lady antebellum","2","","",""),
array("lebron james","2","","",""),
array("leann rimes","2","","",""),
array("lauren alaina","3","","",""),
array("lebrick","3","","",""),
array("libia","3","","",""),
array("lyrics to songs","3","","",""),
array("love poems","3","","",""),
array("lowes.com","3","","",""),
array("lingerie","3","","",""),
array("like a g6","4","","",""),
array("love the way you lie","4","","",""),
array("linkin park","4","","",""),
array("love the way you lie part 2","4","","",""),
array("lady gaga bad romance","4","","",""),
array("lil wayne drop the world","4","","",""),
array("lil wayne right above it","4","","",""),
array("lady gaga alejandro","4","","","")),
"m" => array(
array("music","2","3","4",""),
array("mapquest","0","2","",""),
array("msn","0","2","",""),
array("maps","0","3","",""),
array("myspace","0","2","",""),
array("miley cyrus","2","4","",""),
array("macys","0","","",""),
array("msnbc","0","","",""),
array("miniclip","0","","",""),
array("michaels","0","","",""),
array("mega millions","0","","",""),
array("minecraft","0","","",""),
array("marvel vs capcom 3","1","","",""),
array("macbook pro","1","","",""),
array("macbook","1","","",""),
array("mp3 player","1","","",""),
array("mouse","1","","",""),
array("mumford and sons","1","","",""),
array("macbook air","1","","",""),
array("motorola xoom","1","","",""),
array("micro sd","1","","",""),
array("mac","1","","",""),
array("mail","2","","",""),
array("maria sharapova","2","","",""),
array("mel gibson","2","","",""),
array("megan fox","2","","",""),
array("macy's","2","","",""),
array("mullet haircut","3","","",""),
array("ministro giordani","3","","",""),
array("melame","3","","",""),
array("mapquest driving directions","3","","",""),
array("math answers","3","","",""),
array("medical dictionary","3","","",""),
array("meaning of names","3","","",""),
array("myspace layouts","3","","",""),
array("michael jackson","4","","",""),
array("mariah carey","4","","",""),
array("moment 4 life","4","","",""),
array("metallica","4","","",""),
array("moment for life","4","","",""),
array("magic b.o.b","4","","",""),
array("mr bean","4","","",""),
array("maroon 5","4","","","")),
"n" => array(
array("netflix","0","2","3",""),
array("news","0","2","3",""),
array("nfl","0","2","",""),
array("nordstrom","0","2","",""),
array("nba","0","2","",""),
array("nbc","0","2","",""),
array("nike","0","1","",""),
array("noaa","0","","",""),
array("new zodiac signs","0","","",""),
array("new york times","0","","",""),
array("nook","1","","",""),
array("nintendo ds","1","","",""),
array("nikon d7000","1","","",""),
array("nokia n8","1","","",""),
array("nintendo 3ds","1","","",""),
array("nook color","1","","",""),
array("nikon d3100","1","","",""),
array("nikon d90","1","","",""),
array("nikon","1","","",""),
array("nick jr","2","","",""),
array("nascar","2","","",""),
array("nicole kidman","2","","",""),
array("nickelodeon","2","","",""),
array("nenad krstic","3","","",""),
array("new york unclaimed funds","3","","",""),
array("nashville star","3","","",""),
array("name meanings","3","","",""),
array("netflix.com","3","","",""),
array("names and meaning","3","","",""),
array("northwest airlines","3","","",""),
array("nissan","3","","",""),
array("nicki minaj","4","","",""),
array("no hands","4","","",""),
array("nelly just a dream","4","","",""),
array("nigahiga","4","","",""),
array("never say never","4","","",""),
array("no hands waka","4","","",""),
array("nelly","4","","",""),
array("nicki minaj right through me","4","","",""),
array("never say never justin bieber","4","","",""),
array("nickelback","4","","","")),
"o" => array(
array("old navy","0","2","3",""),
array("office depot","0","2","",""),
array("orbitz","0","2","",""),
array("overstock","0","2","",""),
array("online dictionary","2","3","",""),
array("omg","2","4","",""),
array("oprah","0","","",""),
array("ophiuchus","0","","",""),
array("office max","0","","",""),
array("omegle","0","","",""),
array("olive garden","0","","",""),
array("oovoo","0","","",""),
array("otterbox","1","","",""),
array("oakley","1","","",""),
array("otterbox iphone 4","1","","",""),
array("oakley sunglasses","1","","",""),
array("opi","1","","",""),
array("office chair","1","","",""),
array("opi nail polish","1","","",""),
array("office 2010","1","","",""),
array("otterbox iphone 3gs","1","","",""),
array("oakley sunglasses for men","1","","",""),
array("olivia wilde","2","","",""),
array("oprah winfrey","2","","",""),
array("orkut","2","","",""),
array("ozzy osbourne","2","","",""),
array("olivier martinez","3","","",""),
array("okc","3","","",""),
array("oops wrong number","3","","",""),
array("overstock.com","3","","",""),
array("online pregnancy test","3","","",""),
array("ovulation calendar","3","","",""),
array("online games","3","","",""),
array("ovulation calculator","3","","",""),
array("omg usher","4","","",""),
array("one time justin bieber","4","","",""),
array("one republic secrets","4","","",""),
array("one in a million ne yo","4","","",""),
array("one in a million","4","","",""),
array("one republic","4","","",""),
array("ok iyaz","4","","",""),
array("oasis","4","","",""),
array("owl city","4","","","")),
"p" => array(
array("pandora","0","2","",""),
array("pizza hut","0","2","",""),
array("paypal","0","2","",""),
array("poptropica","0","2","",""),
array("pokemon","1","4","",""),
array("people search","2","3","",""),
array("picnik","0","","",""),
array("pottery barn","0","","",""),
array("petco","0","","",""),
array("people","0","","",""),
array("pirate bay","0","","",""),
array("pnc","0","","",""),
array("ps3","1","","",""),
array("playstation 3","1","","",""),
array("p90x","1","","",""),
array("psp","1","","",""),
array("ps3 controller","1","","",""),
array("ps3 console","1","","",""),
array("projector","1","","",""),
array("portable dvd player","1","","",""),
array("pokemon black","1","","",""),
array("pogo","2","","",""),
array("photobucket","2","","",""),
array("priceline","2","","",""),
array("plentyoffish","2","","",""),
array("powerball","2","","",""),
array("perry stone","3","","",""),
array("pan am flight 103","3","","",""),
array("pal norte","3","","",""),
array("pregnancy week by week","3","","",""),
array("priceline.com","3","","",""),
array("phone number lookup","3","","",""),
array("people finder","3","","",""),
array("people search for free","3","","",""),
array("pregnancy symptoms","3","","",""),
array("pink","4","","",""),
array("pitbull","4","","",""),
array("pink raise your glass","4","","",""),
array("paramore","4","","",""),
array("pray justin bieber","4","","",""),
array("please don't go mike posner","4","","",""),
array("party in the usa","4","","",""),
array("pink floyd","4","","",""),
array("perfect two","4","","","")),
"q" => array(
array("quotes","0","2","3",""),
array("qvc","0","2","3",""),
array("quickbooks","1","2","3",""),
array("qwop","0","4","",""),
array("quicktime","0","2","",""),
array("quotes about life","0","3","",""),
array("quicken","0","1","",""),
array("quest diagnostics","0","2","",""),
array("quiznos","0","2","",""),
array("qwest","0","2","",""),
array("queen","1","4","",""),
array("queens of the stone age","1","4","",""),
array("qatar","0","","",""),
array("quickbooks pro 2011","1","","",""),
array("quicken 2011","1","","",""),
array("quiksilver","1","","",""),
array("queen mattress","1","","",""),
array("quicken deluxe 2011","1","","",""),
array("quinoa","1","","",""),
array("queen rania","2","","",""),
array("query string","2","","",""),
array("quentin tarantino","2","","",""),
array("quotes of the day","3","","",""),
array("quizzes","3","","",""),
array("quotes and sayings","3","","",""),
array("qvc home shopping","3","","",""),
array("quote of the day","3","","",""),
array("questions to ask your boyfriend","3","","",""),
array("queen bohemian rhapsody","4","","",""),
array("qro4yzeyl0i","4","","",""),
array("quest crew","4","","",""),
array("queen we will rock you","4","","",""),
array("queen don't stop me now","4","","",""),
array("queen somebody to love","4","","",""),
array("queensland floods","4","","","")),
"e" => array(
array("ebay","0","2","3",""),
array("expedia","0","2","3",""),
array("eminem","1","2","4",""),
array("espn","0","2","",""),
array("etsy","0","","",""),
array("express","0","","",""),
array("elizabeth edwards","0","","",""),
array("espn3","0","","",""),
array("egypt","0","","",""),
array("easter 2011","0","","",""),
array("e","0","","",""),
array("external hard drive","1","","",""),
array("earphones","1","","",""),
array("earbuds","1","","",""),
array("esperanza spalding","1","","",""),
array("electronic cigarette","1","","",""),
array("elliptical","1","","",""),
array("ethernet cable","1","","",""),
array("espresso machine","1","","",""),
array("ebooks","1","","",""),
array("elizabeth taylor","2","","",""),
array("ellen degeneres","2","","",""),
array("elin nordegren","2","","",""),
array("enterprise car rental","2","","",""),
array("elvis presley enterprises","2","","",""),
array("eva longoria","2","","",""),
array("earthquake hawaii","3","","",""),
array("edc","3","","",""),
array("elmer","3","","",""),
array("ebay.com","3","","",""),
array("english to spanish translation","3","","",""),
array("earliest possible signs of pregnancy","3","","",""),
array("expedia.com","3","","",""),
array("engagement rings","3","","",""),
array("eminem not afraid","4","","",""),
array("enrique iglesias","4","","",""),
array("eminem love the way you lie","4","","",""),
array("enrique iglesias tonight","4","","",""),
array("eminem no love","4","","",""),
array("enrique iglesias i like it","4","","",""),
array("eminem lose yourself","4","","",""),
array("evanescence","4","","",""),
array("eminem when im gone","4","","","")),
"s" => array(
array("sears","0","2","",""),
array("skype","0","2","",""),
array("staples","0","2","",""),
array("sprint","0","2","",""),
array("southwest airlines","2","3","",""),
array("selena gomez","2","4","",""),
array("scarlett johansson","2","3","",""),
array("southwest","0","","",""),
array("sams club","0","","",""),
array("starbucks","0","","",""),
array("samsung","0","","",""),
array("steam","0","","",""),
array("speed test","0","","",""),
array("samsung galaxy tab","1","","",""),
array("sunglasses","1","","",""),
array("search amazon.com","1","","",""),
array("star wars","1","","",""),
array("sd card","1","","",""),
array("skullcandy headphones","1","","",""),
array("speakers","1","","",""),
array("sewing machine","1","","",""),
array("scale","1","","",""),
array("starcraft 2","1","","",""),
array("sandra bullock","2","","",""),
array("search","2","","",""),
array("smaller iphone","2","","",""),
array("shuttle launch","3","","",""),
array("sara rue","3","","",""),
array("science fair projects","3","","",""),
array("spanish dictionary","3","","",""),
array("song lyrics","3","","",""),
array("scary maze game","3","","",""),
array("sexy","3","","",""),
array("spanish translator","3","","",""),
array("shakira","4","","",""),
array("stereo love","4","","",""),
array("shakira waka waka","4","","",""),
array("soulja boy","4","","",""),
array("shane dawson","4","","",""),
array("smosh","4","","",""),
array("sexiest videos of 2008","4","","",""),
array("snsd","4","","",""),
array("snoop dogg","4","","","")),
"t" => array(
array("toys r us","0","2","3",""),
array("target","0","2","",""),
array("twitter","0","2","",""),
array("tmz","0","2","",""),
array("ticketmaster","0","2","",""),
array("tron","0","1","",""),
array("taylor swift","2","4","",""),
array("translate","0","","",""),
array("thesaurus","0","","",""),
array("tmobile","0","","",""),
array("tv guide","0","","",""),
array("tangled","1","","",""),
array("tablet","1","","",""),
array("turbotax 2010","1","","",""),
array("turbo tax","1","","",""),
array("treadmill","1","","",""),
array("tv stand","1","","",""),
array("true blood","1","","",""),
array("true blood season 3","1","","",""),
array("true grit","1","","",""),
array("tonya harding","2","","",""),
array("tiger woods","2","","",""),
array("travelocity","2","","",""),
array("tagged","2","","",""),
array("tanker announcement","3","","",""),
array("tanker contract","3","","",""),
array("tanker decision","3","","",""),
array("tattoo designs","3","","",""),
array("translate english to spanish","3","","",""),
array("tattoos","3","","",""),
array("teen pregnancy signs","3","","",""),
array("translate spanish to english","3","","",""),
array("thanksgiving history","3","","",""),
array("teach me how to dougie","4","","",""),
array("ted williams","4","","",""),
array("the time","4","","",""),
array("teenage dream katy perry","4","","",""),
array("tonight enrique iglesias","4","","",""),
array("tom and jerry","4","","",""),
array("trey songz","4","","",""),
array("transformers 3","4","","",""),
array("tik tok","4","","","")),
"u" => array(
array("ufc","0","2","4",""),
array("us airways","0","2","3",""),
array("usps","0","2","",""),
array("ups","0","2","",""),
array("usaa","0","2","",""),
array("uggs","0","1","",""),
array("ugg boots","1","3","",""),
array("united airlines","2","3","",""),
array("used cars","2","3","",""),
array("united","0","","",""),
array("ups tracking","0","","",""),
array("urban dictionary","0","","",""),
array("urban outfitters","0","","",""),
array("usb flash drive","1","","",""),
array("unlocked cell phones","1","","",""),
array("under armour","1","","",""),
array("usb hub","1","","",""),
array("unstoppable","1","","",""),
array("unbroken","1","","",""),
array("umbrella","1","","",""),
array("uncharted 2","1","","",""),
array("us bank","2","","",""),
array("univision","2","","",""),
array("utusan malaysia","2","","",""),
array("umami","3","","",""),
array("umami burger","3","","",""),
array("ubersocial","3","","",""),
array("unique baby names","3","","",""),
array("ugg boots on sale","3","","",""),
array("unemployment benefits","3","","",""),
array("usher","4","","",""),
array("usher dj got us falling in love","4","","",""),
array("usher more","4","","",""),
array("usher omg","4","","",""),
array("u2","4","","",""),
array("ufo","4","","",""),
array("usher there goes my baby","4","","",""),
array("usher yeah","4","","",""),
array("uelhwf8o7_u","4","","","")),
"v" => array(
array("verizon","0","2","3",""),
array("victoria secret","0","3","",""),
array("vans","0","1","",""),
array("victoria's secret","1","2","",""),
array("verizon wireless","2","3","",""),
array("vanessa hudgens","2","4","",""),
array("victoria beckham","2","3","",""),
array("verizon iphone","0","","",""),
array("vlc","0","","",""),
array("vimeo","0","","",""),
array("v","0","","",""),
array("virgo","0","","",""),
array("vrbo","0","","",""),
array("vuze","0","","",""),
array("valentines day","1","","",""),
array("vacuum cleaner","1","","",""),
array("verizon iphone 4 case","1","","",""),
array("vera bradley","1","","",""),
array("vacuum","1","","",""),
array("valentines day gifts for him","1","","",""),
array("video camera","1","","",""),
array("vampire diaries","1","","",""),
array("vh1","2","","",""),
array("valerie bertinelli","2","","",""),
array("virgin mobile","2","","",""),
array("value city furniture","2","","",""),
array("video","2","","",""),
array("vinny","3","","",""),
array("victoria hiley","3","","",""),
array("verizon.com","3","","",""),
array("verizonwireless.com","3","","",""),
array("volcanoes","3","","",""),
array("very early symptoms of pregnancy","3","","",""),
array("victorious","4","","",""),
array("vybz kartel","4","","",""),
array("vevo","4","","",""),
array("vampire weekend","4","","",""),
array("van halen","4","","",""),
array("victoria justice","4","","",""),
array("vicente fernandez","4","","",""),
array("viva la vida","4","","",""),
array("veena malik","4","","","")),
"w" => array(
array("white pages","0","2","3",""),
array("walmart","0","2","",""),
array("weather","0","2","",""),
array("wikipedia","0","2","",""),
array("wells fargo","0","2","",""),
array("walgreens","0","2","",""),
array("webmd","0","2","",""),
array("wikileaks","0","","",""),
array("www.facebook.com","0","","",""),
array("wiki","0","","",""),
array("wii","1","","",""),
array("wii games","1","","",""),
array("wireless router","1","","",""),
array("windows 7","1","","",""),
array("watch","1","","",""),
array("wii console","1","","",""),
array("webcam","1","","",""),
array("wireless mouse","1","","",""),
array("wii fit","1","","",""),
array("wallet","1","","",""),
array("welcome to facebook","2","","",""),
array("webkinz","2","","",""),
array("wwe","2","","",""),
array("west indies","3","","",""),
array("white chicks","3","","",""),
array("walter e ellis","3","","",""),
array("what does my name mean","3","","",""),
array("what does my last name mean","3","","",""),
array("what is justin biebers phone number","3","","",""),
array("what is the meaning of my name","3","","",""),
array("what is love","3","","",""),
array("when will the world end","3","","",""),
array("whats my name rihanna","4","","",""),
array("whip my hair","4","","",""),
array("wiz khalifa","4","","",""),
array("we r who we r","4","","",""),
array("waka waka","4","","",""),
array("waka waka shakira","4","","",""),
array("whats my name","4","","",""),
array("what the hell avril lavigne","4","","",""),
array("whip my hair willow smith","4","","",""),
array("willow smith whip my hair","4","","","")),
"x" => array(
array("xbox 360","1","2","3","4"),
array("xbox","0","1","3",""),
array("xbox live","0","1","2",""),
array("xm radio","0","2","3",""),
array("xbox kinect","0","1","",""),
array("xbox 360 console","1","3","",""),
array("xbox 360 kinect","1","4","",""),
array("xbox 360 games","1","3","",""),
array("x factor","2","4","",""),
array("xkcd","0","","",""),
array("xbmc","0","","",""),
array("xtranormal","0","","",""),
array("xfinity","0","","",""),
array("xda","0","","",""),
array("xe","0","","",""),
array("xoom","1","","",""),
array("xbox 360 controller","1","","",""),
array("xbox 360 hard drive","1","","",""),
array("xanax","2","","",""),
array("x17","2","","",""),
array("xem phim","2","","",""),
array("xhamstster","2","","",""),
array("x games","2","","",""),
array("xbox cheats","2","","",""),
array("xbox 360 cheats","3","","",""),
array("xbox 360 elite","3","","",""),
array("xbox 360 cheat codes","3","","",""),
array("xbox 360 problems","3","","",""),
array("xxl tv live","3","","",""),
array("x factor 2010","4","","",""),
array("xjawz","4","","",""),
array("xxl movie six","4","","",""),
array("xzibit","4","","",""),
array("x","4","","",""),
array("xscape","4","","",""),
array("xpynpn-tshq","4","","","")),
"y" => array(
array("youtube","0","2","3","4"),
array("yahoo","0","2","3",""),
array("yahoo mail","0","2","3",""),
array("yellow pages","0","2","3",""),
array("y8","0","2","",""),
array("yahoo maps","0","2","",""),
array("yelp","0","","",""),
array("yahoomail.com","0","","",""),
array("youtube to mp3","0","","",""),
array("yahoo finance","0","","",""),
array("yoga mat","1","","",""),
array("yoga","1","","",""),
array("yoga dvd","1","","",""),
array("yarn","1","","",""),
array("yo gabba gabba","1","","",""),
array("you don't know jack","1","","",""),
array("yugioh cards","1","","",""),
array("yoga pants","1","","",""),
array("yugioh","1","","",""),
array("your baby can read","1","","",""),
array("youtube video","2","","",""),
array("youtube broadcast yourself","2","","",""),
array("yahoo music","2","","",""),
array("yahoo messenger","2","","",""),
array("youtube videos","3","","",""),
array("yellowpages.com","3","","",""),
array("youtube music","3","","",""),
array("youtube.com","3","","",""),
array("yellow pages.com","3","","",""),
array("youtube music videos","3","","",""),
array("yeah 3x","4","","",""),
array("yeah 3x chris brown","4","","",""),
array("young jeezy","4","","",""),
array("your love nicki minaj","4","","",""),
array("you home","4","","",""),
array("you belong with me","4","","",""),
array("young money","4","","",""),
array("you belong with me taylor swift","4","","",""),
array("yamla pagla deewana","4","","","")),
"z" => array(
array("zodiac signs","0","2","3",""),
array("zip codes","0","2","3",""),
array("zumba","0","1","4",""),
array("zappos","0","2","",""),
array("zillow","0","2","",""),
array("zales","0","2","",""),
array("zune","0","1","",""),
array("zumba fitness","1","4","",""),
array("zodiac signs changed","0","","",""),
array("zodiac","0","","",""),
array("zara","0","","",""),
array("zumba wii","1","","",""),
array("zumba fitness dvd","1","","",""),
array("zune hd","1","","",""),
array("zippo","1","","",""),
array("zumba dvd","1","","",""),
array("zelda","1","","",""),
array("zippo lighter","1","","",""),
array("zooey deschanel","2","","",""),
array("zsa zsa gabor","2","","",""),
array("zuma","2","","",""),
array("zoe saldana","2","","",""),
array("zac efron","2","","",""),
array("zuhair murad","3","","",""),
array("zachary a chesser","3","","",""),
array("zhu zhu pets","3","","",""),
array("zip code finder","3","","",""),
array("zhu zhu","3","","",""),
array("zappos.com","3","","",""),
array("zip code list","3","","",""),
array("zhu zhu pet","3","","",""),
array("zombie","4","","",""),
array("zac brown band","4","","",""),
array("zaito vs abra","4","","",""),
array("zzirgrizz","4","","",""),
array("zeitgeist","4","","",""),
array("zombie cranberries","4","","",""),
array("zor ka jhatka","4","","",""),
array("zz top","4","","","")));
?>